### ISSUE TITLE
Organization not saved from "New Ticket" screen

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#837] opened 2017-03-10 21:45 UTC
### Infos:

* Used Zammad version: 1.3.x
* Operating system: hosted at zammd.com
* Browser + version: Vivaldi 1.7.735.46

### Expected behavior:

* Attribute "Organization" is being saved into the new contact

### Actual behavior:

* Attribute "Organization" is not being saved into the new contact

### Steps to reproduce the behavior:

* Create a new ticket
* Click "Send Mail"
* Focus the field "Customer*"
* Click the menu entry "+ Create new customer"
* Fill in First name, Last name, E-Mail address and Organization
* Save it
* Write a ticket and submit it
* Go to https://your.zammad.com/#manage (Settings > Users)
* You can already see here that the column "Organization" is empty
* Click the user to view its details → Organization is empty here, too

![screenshot-2017-03-10-223434](https://cloud.githubusercontent.com/assets/26226303/23814221/d8e8b5e4-05e2-11e7-89f8-402241b78578.png)

**Comment by martini** [comment] 2017-03-14 11:33
Hi @AND51 

thanks for your issue. The Organisation is an autocompletion field. This means the organization need to be created before.

An visual improvement for this ui element would be here fine? 

 -Martin

**Comment by AND51** [comment] 2017-03-15 15:38
Hi @martini ,

now I understand. Normally you have to go to Settings→Organization and create the organization beforehand.

Yes, a visual improvement would be finde. There is already a grey "Search..." text in the input field, but I didn't associate this with an autocomplete function.

Another suggestion:
You see the field "Kunde" in the screenshot's background? This is also an autocomplete field, but with a difference. If you type a brand new address there (something that doesn't exist in the autocomplete-list), then the entry will be created. Perhaps you can do the same with the "Organization"-field. If the entered organization doesn't exist yet, it is created the same way as going to Settings→Organization and creating the organization with name+the default values.

**Comment by rfool** [comment] 2017-03-19 08:12
Hi,

there should definitely be the Possibility to create an organization on the fly, as suggested by @AND51.

Just imagine that you get a call from a prospective customer: you wouldn't want to waste the first minutes of such call with the task of figuring out, how and in which order to create the records for organization, user and finally the ticket.

That should be possible in one step. Without distractions and mandatory fields!

**Comment by mobarre** [comment] 2017-08-16 14:08
I've stumbled upon the same issue, and the organizations I create don't appear in the autocomplete (except the original Zammad Foundation, which is double weird)
Digging-in deeper, I can see that requesting the API with api/v1/search/organization?query=Zam yields results, while any other valid requests yields nothing.
Querying with a wildcard only returns Zammad Foundation.

Something isn't right there :) Should that be a different bug report ?
Version is 1.5

**Comment by incognitozen** [comment] 2018-11-13 10:28
+1

Helping create organisation on the fly will cut down admin work for easy onboarding. I think this will also help with improving usability by letting agents create org as opposed to handing them admin rights.

**Comment by thorsteneckel** [comment] 2019-08-16 15:08
This is (technically) a duplicate of #512. So I'll close this one now.

**Closed by thorsteneckel** 2019-08-16 15:08 UTC
Labels: question
