### ISSUE TITLE
KB text design 

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#2626] opened 2019-06-26 11:06 UTC
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): Any
* Operating system:Any
* Database + version:Any
* Elasticsearch version:Any
* Browser + version: Any

### Expected behavior:
In writing an KB article you can use text design (Bold / italic, etc.)
But the public page does not display the design.

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-06-26 11:09
Hey,

sorry, but I do believe that this is not a bug, but a technical question.
Please, for the next time, consult our community for those requests (https://community.zammad.org)

Knowledgebase-Answers are by default drafts.
You have to change the visibility to public, so everyone can see.

![image](https://user-images.githubusercontent.com/6549061/60175355-a44fbb00-9813-11e9-97ac-a3473c3bb219.png)


Closing now.

**Closed as completed by MrGeneration** 2019-06-26 11:09 UTC
Labels: question, missing issue template, knowledge base
