### ISSUE TITLE
LDAP - "User without assigned LDAP groups" and "Role assignment based on groups" doesn't work with OpenDJ

### ISSUE THREAD

**Issue by moellert** [zammad/zammad#1510] opened 2017-10-05 13:28 UTC
* Used Zammad version: 2.0
* Used Zammad installation source: Package
* Operating system: CentOS7
* Browser + version: Chromium 61.0.3163.79 Built on Ubuntu , running on Ubuntu 16.04

It's the same behavior as described in #1179 and #1180.
The only difference is that I use OpenDJ as LDAP server and not OpenLDAP.
I think this is the problem, because obviously should it be fixed already.

Could you fix it for OpenDJ as well?

**Comment by thorsteneckel** [comment] 2017-10-05 13:31
Hi @moellert - What is the filter required for finding users in OpenDJ?

**Comment by moellert** [comment] 2017-10-06 06:27
I tried it with User Filter=(isMemberOf=cn=it,ou=group,ou=rgy,o=****,c=de), User Filter=(objectClass=person) and the default(given in the config menu) User Filter=(objectClass=posixaccount). 

All of them worked and got me the user I expected, but the role assignment hasn't worked and everyone got the default role "Customer".
Even if I configured to ignore user without assigned LDAP groups, they got synced with the role "Customer".

**Comment by thorsteneckel** [comment] 2017-10-24 09:38
Hi @moellert - could you please run the attached script as described. Would be interesting where the assignment fails.

1.) Create a file called `debug_ldap.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_ldap.rb` or `rails r debug_ldap.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_ldap.rb` file

```ruby
require 'ldap'
require 'ldap/group'

class Ldap
  class Group

    def user_roles(mapping, filter: nil)

      filter ||= filter()

      puts "filter = #{filter.inspect}\n"

      result = {}
      @ldap.search(filter, attributes: %w(dn member memberuid)) do |entry|
        puts "---------------------------------\n"
        puts "entry.dn.downcase = #{entry.dn.downcase.inspect}\n"
        puts "mapping = #{mapping.inspect}\n"

        roles = mapping[entry.dn.downcase]
        puts "roles = #{roles.inspect}\n"
        next if roles.blank?

        members = group_user_dns(entry)
        puts "members = #{members.inspect}\n"
        next if members.blank?

        members.each do |user_dn|
          user_dn_key = user_dn.downcase

          roles.each do |role|
            role = role.to_i

            result[user_dn_key] ||= []
            next if result[user_dn_key].include?(role)
            result[user_dn_key].push(role)
          end
        end
      end

      result
    end

    def group_user_dns(entry)
      puts "HERE 1\n"
      return entry[:member] if entry[:member].present?
      puts "HERE 2\n"
      return if entry[:memberuid].blank?
      puts "HERE 3\n"

      entry[:memberuid].collect do |uid|
        dn = nil
        @ldap.search("(uid=#{uid})", attributes: %w(dn)) do |user|
          dn = user.dn
        end
        puts "uid = #{uid.inspect}\n"
        puts "dn = #{dn.inspect}\n"
        dn
      end.compact
    end
  end
end

import = ImportJob.new(name: 'Import::Ldap', payload: ImportJob.last.payload)
import.start
```

**Comment by moellert** [comment] 2017-12-18 07:11
Hey @thorsteneckel I am really very sorry for missing this for such a long time, I went to vacations and had to go to the "Berufsschule" for like 500 years -.-
Now, I did what you wanted and I hope these 115 lines out of the original 26259 lines (with the same content over and over again) are enough for you.
[debug_ldap.txt](https://github.com/zammad/zammad/files/1563003/debug_ldap.txt)

**Comment by thorsteneckel** [comment] 2018-01-09 19:14
Hi @moellert - no worries :) Enjoy Berufsschule - life will never be as relaxed as at this time ;)

Thanks for the provided output. I tweaked the debugging script a bit. Could you please redo the same as above but with the following content:

```ruby
require 'ldap'
require 'ldap/group'

class Ldap
  class Group

    def user_roles(mapping, filter: nil)

      filter ||= filter()

      puts "filter = #{filter.inspect}\n"

      result = {}
      @ldap.search(filter)) do |entry|
        puts "---------------------------------\n"
        puts "entry.dn.downcase = #{entry.dn.downcase.inspect}\n"
        puts "mapping = #{mapping.inspect}\n"

        roles = mapping[entry.dn.downcase]
        puts "roles = #{roles.inspect}\n"
        next if roles.blank?

        members = group_user_dns(entry)
        puts "members = #{members.inspect}\n"
        next if members.blank?

        members.each do |user_dn|
          user_dn_key = user_dn.downcase

          roles.each do |role|
            role = role.to_i

            result[user_dn_key] ||= []
            next if result[user_dn_key].include?(role)
            result[user_dn_key].push(role)
          end
        end
      end

      result
    end

    def group_user_dns(entry)
      puts "HERE 1\n"
      return entry[:member] if entry[:member].present?
      puts "HERE 2\n"
      puts "entry: #{entry.inspect}"
      return group_user_dns_memberuid(entry) if entry[:memberuid].present?
      puts "HERE 3\n"
      return entry[:uniquemember] if entry[:uniquemember].present?
    end

    def group_user_dns_memberuid(entry)
      entry[:memberuid].collect do |uid|
        dn = nil
        @ldap.search("(uid=#{uid})", attributes: %w[dn]) do |user|
          dn = user.dn
        end
        dn
      end.compact
    end
  end
end

import = ImportJob.new(name: 'Import::Ldap', payload: ImportJob.last.payload)
import.start
```

I think we will find the issue soon 🤓

**Comment by moellert** [comment] 2018-01-10 08:23
Hey @thorsteneckel, I am just getting the following errors:
![errors](https://user-images.githubusercontent.com/30858921/34762403-f44a1f9e-f5e7-11e7-92c3-dc8b098907a9.png)

**Comment by thorsteneckel** [comment] 2018-01-10 08:26
Oh, I accidentally added a bracket to much. I updated the code above. Could you please retry?

**Comment by moellert** [comment] 2018-01-10 10:35
The script gave me the following output.
[debug_ldap.txt](https://github.com/zammad/zammad/files/1618380/debug_ldap.txt)

After running the script, the users got the assigned roles and all other users got inactivated. Like it should be. (Because I forgot to delete the script?)

**Comment by thorsteneckel** [comment] 2018-01-10 10:40
Nice! It means it worked :) We had a similar issue in the meantime and I fixed it yesterday. I took the changes into the test-script and apparently they fixed your issues, too. So this is a duplicate of #1664 (even as yours is older). Feel free to update your Zammad to the latest develop version or wait until Zammad 2.3 which will fix it too. Closing now. 🚀

**Closed by thorsteneckel** 2018-01-10 10:40 UTC
Labels: enhancement, integration, needs verification, waiting for feedback
