### ISSUE TITLE
LDAP - Filter "User without assigned LDAP groups" does not work as expected

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#1180] opened 2017-06-09 17:59 UTC
In the LDAP configuration there is the option to ignore users without assigned LDAP groups:

![ldap11](https://user-images.githubusercontent.com/3321655/26987852-630c11ce-4d4d-11e7-8a33-58c35b76d9cd.jpg)

This does not work as I would expect it (and how I think it would be useful).

My expectation is that no users which are matching any groups which are defined in "Rollen" in the screenshot above are not synced to Zammad.

Unfortunately I see users in my database who are synced, but who are not in my two groups "vorstand" and "trainer" which are configured to be used in Zammad.

It seems the filter checks if a user has "any" PosixGroup at all - but it does not filter the groups which are configured to play a role in Zammad. 

Finally these users are synced without any role assiged - not even a customer. When they log into Zammad, there is - ah - nothing for them to see. Which also makes no sense at all.

**Comment by thorsteneckel** [comment] 2017-06-11 16:14
Hi @jacotec - I created a debug script.

Please do the following:

1.) Configure your LDAP connection and start a synchronization as you did before.
2.) Create a file called `issue_1180.rb` in your Zammad directory
3.) Run the file from your Zammad directory via `zammad run rails r issue_1180.rb` or `rails r issue_1180.rb` as zammad user, depending on your installation source (package/source)
4.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
5.) Delete the `issue_1180.rb` file

Code:
```ruby
require 'import/ldap'
require 'import/ldap/user'

module Import
  class Ldap
    class User < Import::ModelResource

      def handle_args(resource, *args)
        @ldap_config     = args.shift
        @dn_roles        = args.shift
        @signup_role_ids = args.shift

        super(resource, *args)

        puts "--------------------\n"
        puts "Import::Ldap::User:\n"
        puts "ldap_config => #{@ldap_config.inspect}\n"
        puts "dn_roles => #{@dn_roles.inspect}\n"
        puts "signup_role_ids => #{@signup_role_ids.inspect}\n"
      end

      def import(resource, *args)
        puts "resource => #{resource.inspect}\n"
        normalized_entry = normalize_entry(resource)
        puts "normalized_entry => #{normalized_entry.inspect}\n"

        # extract the uid attribute and store it as
        # the remote ID so we can access it later
        # when working with ExternalSync
        @remote_id = normalized_entry[ @ldap_config[:user_uid].to_sym ]

        super(normalized_entry, *args)
      end

      def create_or_update(resource, *args)
        result = nil
        if skip?(resource)
          ldap_log(
            action:  "skipped -> #{@remote_id}",
            status:  'success',
            request: resource,
          )
        else
          catch(:no_roles_assigned) do
            determine_role_ids(resource)

            puts "create_role_ids => #{@create_role_ids.inspect}\n"
            puts "update_role_ids => #{@update_role_ids.inspect}\n"

            result = super(resource, *args)

            ldap_log(
              action:  "#{action} -> #{@resource.login}",
              status:  'success',
              request: resource,
            )
          end
        end

        result
      end
    end
  end
end

ImportJob.dry_run(name: 'Import::Ldap', payload: ImportJob.last.payload, delay: false)
``

Thanks!

**Comment by jacotec** [comment] 2017-06-12 20:31
Hi @thorsteneckel ,

ich habe Dir das Debugfile an die support-Email geschickt! Da sind mir zu viele Daten drin um das hier zu posten ;-)

**Comment by thorsteneckel** [comment] 2017-06-13 07:17
Hi @jacotec - Thanks for the file! Next round of debugging 🔔  Please proceed as described above just with the new script:

```ruby
require 'ldap'
require 'ldap/group'

class Ldap
  class Group

    def user_roles(mapping, filter: nil)

      puts "mapping = #{mapping.inspect}\n"
      puts "filter = #{filter.inspect}\n"

      filter ||= filter()
      puts "filter = #{filter.inspect}\n"

      result = {}
      @ldap.search(filter, attributes: %w(dn member)) do |entry|
        puts "-----------------------\n"
        puts "entry = #{entry.to_h.inspect}\n"

        members = entry[:member]
        next if members.blank?
        puts "members = #{members.inspect}\n"

        roles = mapping[entry.dn.downcase]
        puts "roles = #{roles.inspect}\n"
        next if roles.blank?

        members.each do |user_dn|
          puts "user_dn = #{user_dn.inspect}\n"
          user_dn_key = user_dn.downcase

          roles.each do |role|
            role = role.to_i
            puts "role = #{role.inspect}\n"

            result[user_dn_key] ||= []
            next if result[user_dn_key].include?(role)
            result[user_dn_key].push(role)
          end
        end
      end
      puts "result = #{result.inspect}\n"

      result
    end
  end
end

ImportJob.dry_run(name: 'Import::Ldap', payload: ImportJob.last.payload, delay: false)
```

**Comment by jacotec** [comment] 2017-06-13 16:38
@thorsteneckel Done!

Short one this time. Sent as a reply to your support ticket ;-)

**Comment by thorsteneckel** [comment] 2017-06-14 06:41
Thanks! We're getting closer. Seems like the LDAP group <-> LDAP user attribute has another name than we expected. Can you please run the following code again:

```ruby
require 'ldap'
require 'ldap/group'

class Ldap
  class Group

    def user_roles(mapping, filter: nil)

      puts "mapping = #{mapping.inspect}\n"
      puts "filter = #{filter.inspect}\n"

      filter ||= filter()
      puts "filter = #{filter.inspect}\n"

      result = {}
      @ldap.search(filter) do |entry|
        puts "-----------------------\n"
        puts "entry = #{entry.to_h.inspect}\n"

        members = entry[:member]
        next if members.blank?
        puts "members = #{members.inspect}\n"

        roles = mapping[entry.dn.downcase]
        puts "roles = #{roles.inspect}\n"
        next if roles.blank?

        members.each do |user_dn|
          puts "user_dn = #{user_dn.inspect}\n"
          user_dn_key = user_dn.downcase

          roles.each do |role|
            role = role.to_i
            puts "role = #{role.inspect}\n"

            result[user_dn_key] ||= []
            next if result[user_dn_key].include?(role)
            result[user_dn_key].push(role)
          end
        end
      end
      puts "result = #{result.inspect}\n"

      result
    end
  end
end

ImportJob.dry_run(name: 'Import::Ldap', payload: ImportJob.last.payload, delay: false)
```

Thanks!

**Comment by jacotec** [comment] 2017-06-15 17:13
Hi @thorsteneckel
Next debugfile sent to your Zammad as response to the ticket.

Apart from the groups assignment issue please don't forget that also users are synced which are not in the configured groups ;-)

**Comment by thorsteneckel** [comment] 2017-06-16 07:40
Back again with the next and hopefully last script (for this issue) 🤓

```ruby
require 'ldap'
require 'ldap/group'

class Ldap
  class Group

    def user_roles(mapping, filter: nil)

      filter ||= filter()

      result = {}
      @ldap.search(filter, attributes: %w(dn member memberuid)) do |entry|

        roles = mapping[entry.dn.downcase]
        next if roles.blank?

        puts "---------------------------------\n"
        puts "filter = #{filter.inspect}\n"
        puts "roles = #{roles.inspect}\n"

        members = group_user_dns(entry)
        puts "members = #{members.inspect}\n"
        next if members.blank?

        members.each do |user_dn|
          user_dn_key = user_dn.downcase

          roles.each do |role|
            role = role.to_i

            result[user_dn_key] ||= []
            next if result[user_dn_key].include?(role)
            result[user_dn_key].push(role)
          end
        end
      end

      result
    end

    def group_user_dns(entry)
      return entry[:member] if entry[:member].present?
      return if entry[:memberuid].blank?

      entry[:memberuid].collect do |uid|
        dn = nil
        @ldap.search("(uid=#{uid})", attributes: %w(dn)) do |entry|
          dn = entry.dn
        end
        puts "uid = #{uid.inspect}\n"
        puts "dn = #{dn.inspect}\n"
        dn
      end.compact
    end
  end
end

import = ImportJob.new(name: 'Import::Ldap', payload: ImportJob.last.payload)
import.start
```

I'll handle the other issue right after this one. There may be connections between them I have to rule out. Thanks again for your support here 🚀

**Comment by jacotec** [comment] 2017-06-16 11:29
@thorsteneckel Hast Post ;-)

**Comment by thorsteneckel** [comment] 2017-06-27 09:37
As discussed via mail: This is a sub-issue/duplicate of #1179 . The changes can be applied via an update to the latest stable in about 30 minutes from now. Thanks for your great help while debugging this.

PS: Removing of lost LDAP users ( #1211 ) is already included as well 🤓 🚀

**Closed by thorsteneckel** 2017-06-27 09:37 UTC
Labels: duplicate
