### ISSUE TITLE
Split does not grab article since 2.4 anymore 

### ISSUE THREAD

**Issue by AchuM** [zammad/zammad#1914] opened 2018-04-03 09:15 UTC
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: Ver 15.1 Distrib 10.1.26-MariaDB 
* Elasticsearch version: 5.6.8
* Browser + version: Chrome 65.0 

### Expected behavior:

*  Split should grab article as well as the original topic when it's clicked. 

### Actual behavior:

* It just opens a blank new ticket creation page. 

### Steps to reproduce the behavior:

* Split used to grab original topic as well as a note when it was clicked.  The old feature should be restored. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-04-03 09:38
Thanks for your feedback! Technically this is a duplicate of #1913. That's why I will close this issue now.

**Closed by thorsteneckel** 2018-04-03 09:38 UTC
