### ISSUE TITLE
Missing autocompletion for customers, when redirecting a ticket

### ISSUE THREAD

**Issue by hoamer** [zammad/zammad#2693] opened 2019-08-06 08:42 UTC
Hi,

when redirecting a ticket the autocompletion for customers isn't working.
Usually I would assume a request like "https://xxxxx.de/api/v1/search/user-organization?query=kontakt%40&_=15650789540".

Instead this request is made: "https://xxxxx.de/api/v1/users/search?term=kontakt%40".

### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Debian
* Browser + version:FF+Chrome

### Expected behavior:

*"https://xxxxx.de/api/v1/search/user-organization?query=kontakt%40&_=15650789540".

### Actual behavior:

*Instead this request is made: "https://xxxxx.de/api/v1/users/search?term=kontakt%40".

### Steps to reproduce the behavior:

*Hit "redirect" inside a ticket
*Fill textbox "To" with a string

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment] 2019-08-06 08:43
Pls verify it this is a duplicate of https://github.com/zammad/zammad/issues/2684

**Comment by MrGeneration** [comment] 2019-08-06 08:50
Duplicate of  #2684 
Please note that this is a technical question that should be fixed by rebuilding the search index.

For further help, please consult the community (https://community.zammad.org)

Thanks!

**Closed as completed by MrGeneration** 2019-08-06 08:50 UTC
Labels: duplicate, question
