### ISSUE TITLE
Agents must not create customers

### ISSUE THREAD

**Issue by peacoux** [zammad/zammad#2543] opened 2019-04-10 10:43 UTC
Hello, 
I'm am not sure if this ist the right place to adress this. 
How can I prevent a normal agent from creating users? I'd wish that only the admins can do this. Is there a way to fix this? Or am I doing something wrong?

The system is running on version 2.7.x. 

when I look into the settings of the role "agent", the check box "verwalte users"(manage users) is not activated.

Sorry but I couldnt find any information about it somewhere else...

**Comment by MrGeneration** [comment] 2019-04-10 11:37
Sorry, but Github is the wrong place for technical questions. For the next time, please use our Community: https://community.zammad.org .

This is actually working all as intended. "Verwalte users" (or "manage users") simply allows your agent/admin to do more to a user. Mainly regarding user rights, roles and changing the password (that's what a normal agent can't do).

As Zammad needs users as customers for ticket creation anyway, forbidding this is a bit unwanted in my opinion.


This has been discussed already, see:

* https://community.zammad.org/t/agents-must-not-create-new-customers/1247/8
* https://community.zammad.org/t/duplicate-creation-of-new-customer-in-role/1917

Closing now.

**Closed as completed by MrGeneration** 2019-04-10 11:37 UTC
Labels: question

**Comment by peacoux** [comment] 2019-04-10 12:35
for the background: I'd just like to have the option to forbid creating users/customers for certain users. Because some of them are just messing around with it and are creating the exact same customer up to 5 times or writing in the fields whatever they want... 

anyway - Thank you for your quick answer, I will discuss this further in the community forum!
