### ISSUE TITLE
Trigger is not executed when Action is Update and Attribute is Value

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3927] opened 2022-01-20 10:38 UTC
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #10100015

### Expected behavior:

* Create a trigger with condition `Ticket Action: Update` and `Attribute: value`
* updates any ticket value
* Trigger is executed

### Actual behavior:

* Trigger with condition `Ticket Action: Update` and `Attribute: value`
* Updates any ticket attribute, but not `Attribute`
* Trigger is not executed even though `Attribute` matches `value`
* Trigger is executed only if `Attribute` is updated to match `value`

### Steps to reproduce the behavior:

* Create a trigger with condition `Ticket Action: Update` and `Attribute: value`

### Possible solutions

**A**:

* clarify that using `Ticket Action: Update` and `Attribute: value` will check if the `Attribute` was updated 

**B**:

* change behavior that using `Ticket Action: Update` and `Attribute: value` will check only the value of `Attribute`
* this would be a breaking change

**C**:

* Separate conditions into Ticket selector and Action analyzer. 
* Ticket selector would check if ticket matches given values (as in **B**)
* Action analyzer would check if the change itself matches given conditions (as in **A**).
* This may affect Scheduler, Macro and other conditon-able tools as well

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by seljuck** [comment] 2022-01-21 16:31
I don't know if this the same issue. But if you update a ticket attribute but don't add an article, the Update Ticket Trigger doesn't get called either.

**Comment by MrGeneration** [comment] 2022-01-21 16:32
@seljuck this is what this issue actually is about.

**Comment by seljuck** [comment] 2022-01-21 16:34
Ok, thanks. I just also saw issue #3902 is a good description of what I'm dealing with.

**Comment by fliebe92** [comment] 2023-06-14 10:54
With the last changes to triggers, the reported behavior should be doable within Zammad.

Therefore, I am going to close this issue for now.

If you think closing is not correct, please, leave a comment and I'm happy to re-open it.

**Closed as completed by fliebe92** 2023-06-14 10:54 UTC
Labels: bug, trigger, ticket, verified

**Comment by Cybernisk** [comment] 2024-01-25 19:58
**Used Zammad version:** 6.2.0-1
Create a trigger with condition `Ticket Action is Updated` only (see attached screenshot)
**Expected behavior:** updates any ticket value -> Trigger is executed.
**Possible solutions**: Didn't test too much, but adding more conditions like for example `Status` and choose all statuses solves the issue.
I was trying to achieve two simple triggers for any new ticket and any updated. I'm not 100% sure, but, to my mind, this trigger should work in case of any updates of any ticket, but it doesn't. Why I think that it should work? Because another trigger with the only one condition `Ticket Action is Created` works for any created.

![2024-01-25_22-48-14](https://github.com/zammad/zammad/assets/10900425/53e6d96e-e84a-4e11-8a5c-f2ac32a17730)
