### ISSUE TITLE
OTRS import fails with runtime error

### ISSUE THREAD

**Issue by MPfiff** [zammad/zammad#590] opened 2017-01-05 13:24 UTC
Hi there,

## INFO:

Operating System: Debian 8.6
OTRS: 5.0.15

## Problem

I'm trying to import from OTRS 5.0.15 into latest Zammad. The import with the webinterface fails because I get no Users Tickets ...
Then I tried it with rails-CLI the I get an run time error. Does anyone has a solution for this problem?

Setting.get("import_otrs_user") # from cache
Setting.get("import_otrs_password") # from cache
Setting.get("import_otrs_endpoint") # from cache
Setting.get("import_otrs_endpoint_key") # from cache
thread#-: POST: http://srvhld002/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"State", :Limit=>"", :Offset=>                                                                                                                                                             "", :Diff=>0, "Action"=>"ZammadMigrator", "Key"=>"SUbcim81XLpyqhpCPeLk3DLHmnNnol                                                                                                                                                             sDZGYlErHR"}
Setting.get("import_otrs_user") # from cache
Setting.get("import_otrs_password") # from cache
thread#-: ERROR: Server Error: #<Net::HTTPInternalServerError 500 Internal Serve                                                                                                                                                             r Error readbody=true>!
RuntimeError: Can't connect to Zammad Migrator
        from /opt/zammad/lib/import/otrs.rb:26:in `request_json'
        from /opt/zammad/lib/import/otrs.rb:200:in `load'
        from /opt/zammad/lib/import/otrs.rb:331:in `start'
        from (irb):5
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rail                                                                                                                                                             s/commands/console.rb:110:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rail                                                                                                                                                             s/commands/console.rb:9:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rail                                                                                                                                                             s/commands/commands_tasks.rb:68:in `console'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rail                                                                                                                                                             s/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rail                                                                                                                                                             s/commands.rb:17:in `<top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'

Best regards
MPfiff

**Comment by thorsteneckel** [comment] 2017-01-13 08:43
Hi @MPfiff - sorry for the late response. There seems to be an error on the OTRS side. OTRS responds with an 500 status code which indicates an internal server error. That's bad 🤓 could you please reproduce the issue and send me the OTRS log so I can take a look what went wrong there? Thanks in advance.

**Comment by thorsteneckel** [comment] 2017-01-22 15:23
Hi @MPfiff - let me know if there are any updates. I'll close this for now. Feel free to add information and I will handle it.

**Closed by thorsteneckel** 2017-01-22 15:23 UTC
Labels: bug, import, waiting for feedback
