### ISSUE TITLE
Improve UX when using multiple browser tabs

### ISSUE THREAD

**Issue by gh-zammad** [zammad/zammad#1626] opened 2017-11-08 14:47 UTC
### Infos:

* Used Zammad version: 2.1.0-1510063280.01926199.stretch
* Used Zammad installation source: deb
* Operating system: Debian 9 (stretch)
* Browser + version: Firefox 52.4.0esr-1~deb9u1 on Debian on 9 (stretch)

### Expected behavior:

* One can work with multiple tickets and other stuff open at the same time in multiple tabs, like e.g. in Github, Gitlab, Trac etc., without cumbersome modal dialogs.

### Actual behavior:

* The session on all but the current tabs is suspended. When going back to the other tab, one has to confirm a dialogue. Sometimes, unsaved changes in that tab are lost, but even if not, it is annoying.

### Steps to reproduce the behavior:

* Open two tickets in two browser tabs and switch between the two tabs.

I'm fully aware, that this behaviour is "by design" and probably not easy to change.
But it is the one mayor annoyance all my colleagues complain about, so I report it anyway :~)
Just close it, if there is no realistic chance to improve the UX in that respect.

**Comment by martini** [comment] 2017-11-08 14:53
> Expected behavior:
> 
> One can work with multiple tickets and other stuff open at the same time in multiple tabs, like e.g. in > Github, Gitlab, Trac etc., without cumbersome modal dialogs.

How should be the behaviour with the already open (and probably already started working) tabs/tickets if you open a new Zammad in a new browser tab/window?

Should have each browser window own tabs? Or work in parallel in same tabs (mirroring browser windows)? And if you have own Zammad tabs in each browser window, how would you be able to restart working on already started Zammad tabs?

Thanks for any ideas. :)

**Comment by gh-zammad** [comment] 2017-11-08 15:17
So far, I thought about having only one browser open, but with multiple tabs. (Multiple windows are the same, if they are not "private windows" with own sessions.)

What would I want? I'ld say: just like in Github, Gitlab, Trac etc. because this is "known behaviour". No sync between tabs or windows - IMHO this is just not necessary.

**Comment by hanneshal** [comment] 2017-11-15 14:28
Sorry. I have to close this. Right now this is exactly what we want. 
Especially when multiple users work on tickets we need to sync. Otherwise this results in unexpected behaviour. 

Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes

**Closed by hanneshal** 2017-11-15 14:28 UTC

**Comment by Chinoman10** [comment] 2025-01-27 11:05
Since the community post was locked, preventing people from adding more comments/feedback, and perhaps provide some more guidance, I'll just leave a comment on this old issue instead, requesting **the number `#1` most requested feature** on Zammad to be unlocked for discussion.
Thanks in advance, and apologize for unearthing this almost decade-old issue.

**Comment by MrGeneration** [comment] 2025-01-27 11:10
A locked thread on our community forum does not restrict you from "adding your heart" to the first article. It also doesn't mean it's off the table, but simply that there was no activity on it for over 365 days. I've unlocked it, even though I don't see the benefit from that action.
