### ISSUE TITLE
Cannot create organizations using REST API with OAuth 2

### ISSUE THREAD

**Issue by luisdetlefsen** [zammad/zammad#2465] opened 2019-02-05 21:19 UTC
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): Docker
* Operating system: Debian GNU/Linux 9
* Browser + version: Chrome 

### Expected behavior:

* Organization should be created when doing a POST to  /api/v1/organizations with OAuth2

### Actual behavior:

* Receiving a 401 "Not authorized (token)!" from Zammad.

I, [2019-02-05T20:45:02.028026 #392-47221488174200]  INFO -- : Started POST "/api/v1/organizations?name=prontobpo" for 127.0.0.1 at 2019-02-05 20:45:02 +0000
I, [2019-02-05T20:45:02.038374 #392-47221488174200]  INFO -- : Processing by OrganizationsController#create as */*
I, [2019-02-05T20:45:02.038506 #392-47221488174200]  INFO -- :   Parameters: {"name"=>"prontobpo"}
I, [2019-02-05T20:45:02.057897 #392-47221488174200]  INFO -- : Enqueued UserDeviceLogJob (Job ID: 71a19961-0aee-4f59-8ea7-051a0a44c8e4) to DelayedJob(default) with arguments: "PostmanRuntime/7.4.0", "172.17.0.1", 3, nil, "token_auth"
I, [2019-02-05T20:45:02.062117 #392-47221488174200]  INFO -- : Completed 401 Unauthorized in 23ms (Views: 0.2ms | ActiveRecord: 7.6ms)
I, [2019-02-05T20:45:02.208142 #401-47044369696800]  INFO -- : 2019-02-05T20:45:02+0000: [Worker(host:087be4bfb9a4 pid:401)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=62) (queue=default) RUNNING
I, [2019-02-05T20:45:02.224598 #401-47044369696800]  INFO -- : Performing UserDeviceLogJob (Job ID: 71a19961-0aee-4f59-8ea7-051a0a44c8e4) from DelayedJob(default) with arguments: "PostmanRuntime/7.4.0", "172.17.0.1", 3, nil, "token_auth"
I, [2019-02-05T20:45:02.226526 #401-47044369696800]  INFO -- : Performed UserDeviceLogJob (Job ID: 71a19961-0aee-4f59-8ea7-051a0a44c8e4) from DelayedJob(default) in 1.78ms
I, [2019-02-05T20:45:02.229067 #401-47044369696800]  INFO -- : 2019-02-05T20:45:02+0000: [Worker(host:087be4bfb9a4 pid:401)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=62) (queue=default) COMPLETED after 0.0208

### Steps to reproduce the behavior:

* Create an access token in System -> API -> Applications
* Send POST to /api/v1/organizations and set the auth type to OAuth 2.0 with the access token that was set previously.
* 401 is returned by Zammad.

More info: A GET to /api/v1/organizations returns data just fine. If basic authentication is used instead of OAuth2 for the POST call, then the organization is created. So far the issue seems to be just when using OAuth2 with POST to /api/v1/organizations.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-02-06 08:20
Please provide at least the API call you're doing for verification.

Do I also get you correct, that oAuth2 in combination with API is a general problem?

**Comment by luisdetlefsen** [comment] 2019-02-06 15:24
It seems that the issue occurs just with this combination: using **OAuth2** and doing a **Post** to **/api/v1/organizations**.
If the authentication method is changed to Basic, the call is executed properly. The issue doesn't occur with any other API calls (that I have used so far). Please let me know if I need to provide more information. 

**This call returns a 401:**
curl --header "Authorization: Bearer b3e84aaad90d5cb714fb86d774eef89cce9bbd4af0b1c6677eeec1a227dcac76" --request POST http://localhost/api/v1/organizations/firstname=Bob

**But these calls return a 200:**
curl --request POST http://localhost/api/v1/organizations?name=Bob --user admin@admin.com:mypassword

curl --header "Authorization: Bearer b3e84aaad90d5cb714fb86d774eef89cce9bbd4af0b1c6677eeec1a227dcac76" --request GET http://localhost/api/v1/organizations

curl --header "Authorization: Bearer b3e84aaad90d5cb714fb86d774eef89cce9bbd4af0b1c6677eeec1a227dcac76" --request POST "http://localhost/api/v1/users?firstname=Bob&lastname=Smith&email=a@b.com"

**Comment by MrGeneration** [comment] 2019-03-29 15:20
Sorry for the delay.
This is not a bug, but works as designed.

The error message you receive when trying to use `http://localhost/api/v1/organizations/firstname=Bob` clearly states "no such route" - if you want to search for an organization, use `http://localhost/api/v1/organizations/search?query=Bob` (**GET**), that will work and help you.

**Comment by luisdetlefsen** [comment] 2019-03-29 15:24
Thanks for your reply. But I am not trying to search for an organization, I am trying to create one using the route that is specified in the api documentation.

**Comment by SummerStorm** [comment] 2019-04-02 14:40
Hi @luisdetlefsen,

To prevent a [XY communication problem](https://en.wikipedia.org/wiki/XY_problem), could you please clarify a bit on your use case here?

If you simply want to programmatically create user and/or organizations, then I would highly suggest using the user token approach. You would create an admin user, and create that user's Personal Access Token (via user -> profile -> token_access). That token will get you authenticated access to all the APIs. This is the tried-and-true approach and is much better supported than OAuth2.

If you are absolutely sure that you indeed need OAuth2, then I'll need to create a demo OAuth2 app to re-produce your issue.

**Comment by luisdetlefsen** [comment] 2019-04-02 15:10
@SummerStorm I appreciate that you provide an alternative solution, but I have a specific requirement to use OAuth2.

I hope this helps to clarify the use case. I need to create organizations through the REST API using OAuth2, but it is not working as expected. Zammad returns an http status of 401 instead of creating the organization. More details that could be useful to troubleshoot the issue: all other REST API calls seem to be working fine, i.e., all CRUD operations for users.

**Comment by thorsteneckel** [comment] 2019-04-02 15:27
Seems like this is a configuration error of your system. There is no difference in authentication between user and organization CRUD REST endpoints. All API endpoints authenticate the same way. Therefore there must be an error in the permission configuration of your system for managing organizations. I'll close this as a question. Please refer to the [community board](http://community.zammad.org/) for (technical) questions. We're happy to help there.
Please provide an example [free hosted instances](https://www.zammad.com/getting-started) in the community where we can reproduce your issue.

**Closed as completed by thorsteneckel** 2019-04-02 15:27 UTC
Labels: question
