### ISSUE TITLE
Feature enhancement, save attachments in ticket templates 

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#3947] opened 2022-02-02 16:08 UTC
### Infos:

* Used Zammad version: 5.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: 10100709 

### Expected behavior:

Support attachments for ticket templates. 

### Actual behavior:

Attachments are ignored if a ticket template is created or applyed.

### Steps to reproduce the behavior:

- open new ticket screen

- prefill the ticket and add an attachment to it
- save the ticket template via right sidebar
- open new ticket and try to use the template

  -=> No attachment is used.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-02-02 16:16
duplicate of #2175

**Closed as completed by MrGeneration** 2022-02-02 16:16 UTC
Labels: duplicate
