### ISSUE TITLE
Translation in French - bad escaping of quote characters on some strings

### ISSUE THREAD

**Issue by AnaelMobilia** [zammad/zammad#5095] opened 2024-03-22 17:01 UTC
### Used Zammad Version

6.2.0-1710845114.31c6f6c2.bookworm

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12.5
- Database + version:  postgresql 15.6-0+deb12u1
- Elasticsearch version: 8.12.2
- Browser + version: firefox 123

### Actual behaviour

Some strings translated in french have a bad display rendering on Zammad (`'`is replaced by `&#39;`).

Eg : 
- https://translations.zammad.org/translate/zammad/zammad-stable/fr/?checksum=ed7e41b4817f159c
- ![image](https://github.com/zammad/zammad/assets/6187125/04b33a19-b7b9-41e6-8f26-cc1d6e73f07e)

![image](https://github.com/zammad/zammad/assets/6187125/ce72e272-4e0d-43c2-83d3-5b88c56385d4)

It's not a global issue on all single quote as some are correctly rendered (with the same character on the weblate translation)

### Expected behaviour

Have a single quote

### Steps to reproduce the behaviour

- Change locale to French
- Go to admin panel

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment] 2024-04-05 11:46
Hi @AnaelMobilia, I was not able to reproduce this so far. This is FF 124 on MacOS:

<img width="331" alt="Bildschirmfoto 2024-04-05 um 13 45 09" src="https://github.com/zammad/zammad/assets/211281/1d57dfae-025e-40be-b53d-6d329823a842">

**Comment by AnaelMobilia** [comment] 2024-04-15 21:27
Hello @mgruner 
This occurs only on specific area.

For example, on the KB, you need to go to the third tab ("Menu Public").

Bests regards,
Anael

**Comment by mgruner** [comment] 2024-04-16 07:32
Thanks, I see it now.

**Comment by mgruner** [comment] 2024-04-16 08:42
@AnaelMobilia thanks again for your report and help with the French translation. The fix for this will be in Zammad 6.3 which will be released very soon.

**Closed as completed** 2024-04-16 08:41 UTC
Labels: bug, verified, localization
