### ISSUE TITLE
Zammad stops fetching IMAP emails if one email has malformed MIME (MIME of death)

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1877] opened 2018-03-19 09:49 UTC
### Infos:

* Used Zammad version: 2.3
* Operating system: Ubuntu 16.04

### Expected behavior:

* If Zammad can not process an email because of malformed MIME it should skip it

### Actual behavior:

* If Zammad can not process an email because of malformed MIME it logs:

I, [2018-03-19T09:06:52.219638 #15403]  INFO -- : fetching imap (xxx.xxx.xxx/support port=993,ssl=true,folder=INBOX,keep_on_server=false)
I, [2018-03-19T09:06:52.464934 #15403]  INFO -- :  - message 1/3
E, [2018-03-19T09:06:54.346617 #15403] ERROR -- : execute Channel.fetch (try_count 0) exited with a non standard-error #<SystemStackError: stack level too deep>

and stops fetching mails form that channel.

### Steps to reproduce the behavior:

* Try to parse a malfromed MIME.

I will provide you an example via support@zammad.com because of data protection reasons.

**EDIT @thorsteneckel:** Ticket# 1016716

**Comment by thorsteneckel** [comment] 2018-06-14 09:28
As discussed in Ticket# 1016716 the issue is not reproducible with the latest version of Zammad. Therefore I'm closing this issue as resolved.

**Closed by thorsteneckel** 2018-06-14 09:28 UTC
Labels: bug, channel, needs verification, prioritized by payment, waiting for feedback
