### ISSUE TITLE
Shift+Ctrl+T overlaps with "open closed tab" in Chrome

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#1485] opened 2017-09-28 01:22 UTC
When press Shift+CTRL+T within chrome the last closed tab reopens instead of enable the inline translation feature in Zammad.

Zammad:
![image](https://user-images.githubusercontent.com/6099976/30945008-e8eaa918-a3fb-11e7-8e18-16f20c2abce0.png)

Chrome:
![image](https://user-images.githubusercontent.com/6099976/30945018-f18e36e8-a3fb-11e7-9fbf-9219f4b94c3b.png)

Shift+CTRL+D works though it overlaps too:
Zammad: Show dashboard
Chrome: Save all tabs as bookmarks

### Infos:

* Used Zammad version: v2.0.0
* Used Zammad installation source: source
* Operating system: 
* Browser + version: Chrome 61 

### Expected behavior:

* Enable inline translation

### Actual behavior:

* Reopens the last closed tab

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment] 2017-09-28 09:54
Hi @MDXDave - This is a duplicate of the more problematic issue #656

**Closed by thorsteneckel** 2017-09-28 09:54 UTC
