### ISSUE TITLE
KB permission hardening seems to be faulty for none and reader

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#5124] opened 2024-04-13 19:20 UTC
### Used Zammad Version

6.3.x.615530436.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: verified on Google Chrome 123.0.6312.122 (Win)

### Actual behaviour

If you have reader permissions, you can up- and downgrade your permissions to none or editor freely. This is not role bound.
If you set none in a parent, you can't have editor as example in a child.

![reader-kb-permission](https://github.com/zammad/zammad/assets/6549061/d1251755-ca61-4010-8abc-662db095c5c4)

### Expected behaviour

I expect that if the parent category in the knowledge base has 'reader' permission for a role, I cannot set it to none in a child category. Same applies for 'none' permission: I do expect to be able to have higher permissions in the child than the parent.

Our pre-release documentation states this:

> In general, permissions of a parent category are inherited! If you want to grant edit permissions for a sub-category for a specific role for example, set the upper level to “reader” and the desired sub-category to “editor”. The other way round is not possible (permissions can only be widened, not restricted). If you can’t select permissions in the table, this could be the reason.

### Steps to reproduce the behaviour

- set reader in a parent
- go to any child and try to set lower permissions (none)

You can cross check this by using editor permissions where downgrading is not possible (as expected).

- set none in a parent
-  go to any child and try to set higher permissions (reader)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment] 2024-04-15 06:19
Maybe related to this one: https://github.com/zammad/zammad/issues/4893

**Comment by MrGeneration** [comment] 2024-04-15 12:32
It is a possible regression, yes.

**Comment by mgruner** [comment] 2024-04-16 08:45
@mantas

**Comment by mantas** [comment] 2024-04-16 15:53
Actually I think this is as designed. But I agree documentation wording shall be improved.

> set reader in a parent
> go to any child and try to set lower permissions (none)

User may be reader in parent. But (one of) children may be hidden from him. User is a reader in parent, thus he can't elevate his own permissions. Otherwise `none` option would be useless.

**Comment by MrGeneration** [comment] 2024-04-16 16:06
>> set reader in a parent
>> go to any child and try to set lower permissions (none)
>
> User may be reader in parent. But (one of) children may be hidden from him. User is a reader in parent, thus he can't elevate > his own permissions. Otherwise none option would be useless.

Okay.. you lost me once again.
On friday, I was told that the child of a parent category can have the same permission or higher, but not less.

This was what was shown to me visually too.

**Comment by mantas** [comment] 2024-04-16 16:10
> Okay.. you lost me once again. On friday, I was told that the child of a parent category can have the same permission or higher, but not less.
> 
> This was what was shown to me visually too.

Sorry, I was thinking about `reader/editor`. It completely fell off my mind to emphasize that `none` is not part of downgrade/upgrade.

**Comment by MrGeneration** [comment] 2024-04-16 16:13
> Sorry, I was thinking about reader/editor. It completely fell off my mind to emphasize that none is not part of downgrade/upgrade.

Okay. Interesting. Why can I not select `None` as `Editor` then?

I am confused... a lot.

**Comment by mantas** [comment] 2024-04-16 16:15
> Okay. Interesting. Why can I not select `None` as `Editor` then?
> 
> I am confused... a lot.

Do you mean set child of `Editor` as `None`? Someone having `Editor` in parent could change children permissions to make it visible to himself. But someone having `Reader` in parent could not touch children permissions.

**Comment by MrGeneration** [comment] 2024-04-16 16:16
The screen cast you can see is done by an administrator with all relevant permissions.
I am unable to follow what is right and wrong at this point.

**Comment by dominikklein** [comment] 2024-04-17 06:08
@MrGeneration Inside the roles in the screencast, all roles have in general `knowledge_base.editor` and `knowledge_base.reader` or?

**Comment by dominikklein** [comment] 2024-04-17 06:17
@mantas ~~I also see that there is some strange behaviour. When I'm `editor` inside the parent category, I can not change this in the child category for this role, but when I'm `reader` in the parent I can change it to everything for this role in the child category.
Should it not be the other way around? When I have `editor` in the parent category I should be able to change it to `reader` or `none` in the child category for this role.~~

(Maybe a call would be good to be on the same track)

Edited:

Ok, I think the knowledge base permissions are working completely the other way around would I understood? When on the parent category is `editor` as the highest permission selected, there is no possibility to change this for child categories, because of a "fixed" inheritance that can not be influenced.

**Comment by MrGeneration** [comment] 2024-04-17 07:56
> Inside the roles in the screencast, all roles have in general knowledge_base.editor and knowledge_base.reader or?

Yes, in the screencast in question all roles have full permission on the KB.
That was the result of me trying to desperately get it to work as "expected".

**Comment by mantas** [comment] 2024-04-22 09:13
Can we close this one after the last week's call?

**Comment by MrGeneration** [comment] 2024-04-22 10:15
Would you mind to summarize this, also in favor of https://github.com/zammad/zammad/issues/4893 so that everyone understands?

**Comment by mantas** [comment] 2024-04-22 13:39
Closing with following summary about current & correct functionality:

> In general, permissions of a parent category are inherited! If you want to grant "edit" permissions for a sub-category for a specific role for example, set the upper level to “reader” and the desired sub-category to “editor”. Same workflow applies to granting "none" permissions, effectivelly hiding a given sub-category. The other way round is not possible. Role with "editor" permission has full access to it's sub-categories, so it's pointless to limit it's permissions. "None" permissions also cannot be changed down the tree since there would be no path to access permitted sub-categories. If you can’t select permissions in the table, this could be the reason.

**Closed as completed by mantas** 2024-04-22 13:39 UTC
Labels: bug, verified, knowledge base
