### ISSUE TITLE
Default answer type and autofill of e-mail address

### ISSUE THREAD

**Issue by inbaz** [zammad/zammad#938] opened 2017-04-09 16:07 UTC
### Infos:

* Used Zammad version: 1.4.0
* Operating system: CentOS 7
* Browser + version: Firefox

### Expected behavior:

* When somebody wrote a new e-mail and a new ticket gets opened it would be great to have the e-mail answer as default value. And the e-mail address of the sender should be autofilled into the To: field of the answer.

### Actual behavior:

* At the moment the To: field is simply empty.

### Steps to reproduce the behavior:

* Create an email feed
* send email to zammad
* open the anwer block by clicking into the text field
* you see the default answer type for a simple note
* when you change to e-mail the To: field is empty.

**Comment by Hirbod** [comment] 2017-04-11 13:13
To field will be filles when you push the "answer" button, but yeah, I would also prefer a pre-filled form when manually switching from note to email.

**Comment by sthag** [comment] 2017-06-20 08:39
I also want to suggest a **configurable default behavior for an answer in general**. Not only for email.
It would be great if I could set public answer to the default. It's always an internal note.
This could be a system setting or a user bound setting. Maybe even a group or organisation setting.

**Comment by thorsteneckel** [comment] 2018-04-25 07:40
This is more or less a duplicate of #372 and will be addressed over there. Closing now.

**Closed by thorsteneckel** 2018-04-25 07:40 UTC
Labels: feature backlog, proposal, ticket
