### ISSUE TITLE
Can't bind websocket to ipv6 ip [::]

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#1687] opened 2017-12-03 17:52 UTC
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: source
* Operating system: ubuntu
* Browser + version: chrome 62

### Expected behavior:

* websocket can be started with ip "[::]" which is the ipv6 equivalent to "0.0.0.0".

### Actual behavior:

*  websocket process fails with:

```
zammad@2afbead7b431:~$ bundle exec script/websocket-server.rb -b [::] -p 6042 start
bundler: failed to load command: script/websocket-server.rb (script/websocket-server.rb)
RuntimeError: no acceptor (port is in use or requires root privileges)
  /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server'
  /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
  /usr/local/bundle/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:46:in `run'
  /usr/local/bundle/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:39:in `block in start'
  /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:171:in `run'
  /usr/local/bundle/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:35:in `start'
  script/websocket-server.rb:123:in `block in <top (required)>'
  /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
  /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
  script/websocket-server.rb:122:in `<top (required)>'
```

### Steps to reproduce the behavior:

* start websocket server with: 
  * bundle exec script/websocket-server.rb -b [::] -p 6042 start

Railsserver can be run flawlessly with:
* bundle exec rails server puma -b [::] -p 3000 -e production

**Comment by monotek** [comment] 2017-12-19 15:33
I've already tried. Same error.
It's in context of Kubernetes & the docker-compose container.

Imho it should work same way as in puma, where [::] is used. See:

https://github.com/zammad/zammad-docker-compose/blob/c6485593340aa9ab47a15c80be703394fdc30290/containers/zammad/docker-entrypoint.sh#L106

**Comment by muhammadn** [comment] 2017-12-20 14:42
@monotek i had forked zammad-docker-compose which you can review in this branch:

https://github.com/muhammadn/zammad-docker-compose/tree/ip6binding

Basically websockets will use [::] with the fix that i did on my [ip6binding](https://github.com/muhammadn/zammad/tree/ip6binding) branch

**Comment by muhammadn** [comment] 2017-12-21 10:46
Just to let you know for the docker build. 

I just build the `zammad` image locally and change all instances of `${IMAGE_REPO}:zammad${VERSION}` in docker-compose.yml to my own locally built of zammad image with the fix. 

```
╰─$ docker exec -it zammaddockercompose_zammad-websocket_1 bash
root@34e2922ca56f:/opt/zammad# ps auxww |grep script                                                                       
zammad       1  0.9  5.8 324712 119612 ?       Ssl  10:34   0:06 script/websocket-server.rb -b [::] -p 6042 start                                       
root       101  0.0  0.0    512     4 ?        D+   10:45   0:00 grep script
root@34e2922ca56f:/opt/zammad# nc -v -z -6 ::1 6042
Connection to ::1 6042 port [tcp/*] succeeded!
root@34e2922ca56f:/opt/zammad# nc -v -z -4 127.0.0.1 6042
Connection to 127.0.0.1 6042 port [tcp/*] succeeded!
root@34e2922ca56f:/opt/zammad# 
```

**Comment by monotek** [comment] 2017-12-21 12:28
did you uploaded you docker image somewhere?

**Comment by muhammadn** [comment] 2017-12-21 14:41
Just uploaded it on docker hub.

[https://hub.docker.com/r/muhammadn/zammad/](https://hub.docker.com/r/muhammadn/zammad/)

You can use the use my docker-compose.yml for tests which i have updated:

[https://github.com/muhammadn/zammad-docker-compose/blob/ip6binding/docker-compose.yml](https://github.com/muhammadn/zammad-docker-compose/blob/ip6binding/docker-compose.yml)

**Comment by monotek** [comment] 2017-12-25 11:31
Also your repo does not work on Ubuntu 17.10 for me: 

```

zammaddockercompose_zammad-init_1 exited with code 0
zammad-websocket_1      | starting websocket server...
zammad-scheduler_1      | starting scheduler...
zammad-nginx_1          | starting nginx...
zammad-websocket_1      | RuntimeError: no acceptor (port is in use or requires root privileges)
zammad-websocket_1      |   /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server'
zammad-websocket_1      |   /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
zammad-websocket_1      |   /usr/local/bundle/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:46:in `run'
zammad-websocket_1      |   /usr/local/bundle/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:39:in `block in start'
zammad-websocket_1      |   /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:171:in `run'
zammad-websocket_1      |   /usr/local/bundle/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:35:in `start'
zammad-websocket_1      |   script/websocket-server.rb:127:in `block in <top (required)>'
zammad-websocket_1      |   /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
zammad-websocket_1      |   /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
zammad-websocket_1      |   script/websocket-server.rb:122:in `<top (required)>'
zammad-websocket_1      | bundler: failed to load command: script/websocket-server.rb (script/websocket-server.rb)

```

**Comment by muhammadn** [comment] 2017-12-26 09:02
I did have that problem which is caused by an old image volume.

Solved it by doing `docker volume rm zammaddockercompose_zammad-data` and running `docker-compose up -d` again

**Comment by monotek** [comment] 2017-12-26 19:06
I doubt that, because in the entrypoint.sh script is a "rsync -a --delete" done from image to the volume, before the service is started. There shouldn't be any remains of the old volume.

See: https://github.com/zammad/zammad-docker-compose/blob/6888a87abd8a10e232fe15a33f7389dc6423571e/containers/zammad/docker-entrypoint.sh#L26

**Comment by thorsteneckel** [comment] 2019-04-18 06:47
Hi @monotek - can you please check if this is still relevant? I tried it on my local MBP and got no error:

```
$ bundle exec script/websocket-server.rb -b '[::]' -p 6042 start
2019-04-18T06:45:04Z:client(-) check unused idle connections...
2019-04-18T06:45:24Z:client(-) Status: websocket clients: 0
2019-04-18T06:45:24Z:client(-) Status: ajax clients: 0
```

Started listening:
```
netstat -vanp tcp |grep 6042                                  
tcp46      0      0  *.6042                 *.*                    LISTEN      131072 131072  87129      0 0x0100 0x00000006
```

EDIT:
We even got a test 😱 
https://github.com/zammad/zammad/blob/b6f277c97b6fd53211f4b5b13ca790961baf09a9/spec/scripts/websocket_server_spec.rb#L14-L41

**Comment by thorsteneckel** [comment] 2019-04-18 06:52
Seems like it [got fixed](https://github.com/zammad/zammad/commit/cd4dc311ae27bc36534d8a176675b699de25bc93#diff-9eb959bb62ce5e2783a4710454948172) some time ago but the issue was never closed. I'll close it for now. Let me know if there are any issues left.

**Closed by thorsteneckel** 2019-04-18 06:52 UTC
Labels: enhancement
