### ISSUE TITLE
Bulk Action -> JS Error - Bug

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#1053] opened 2017-05-08 06:12 UTC
### Infos:
* Used Zammad version: 1.5.0
* Used Zammad installation source: Ubuntu Package
* Operating system: Ubuntu 16.04 on 4 core VServer with 8GB memory.
* Browser: Google Chrome latest

### Expected behavior:

* Bulk action should happen. I drag 4 Tickets to a Macro.

### Actual behavior:

* When the mouse-up event happens you can see the following error in the Browser-Console and the JS thinks the mouse-button is still pressed.

### Browser Console Error!:
```
Uncaught TypeError: Cannot read property 'attr' of null
    at Array.complete (application-1dc4fd5….js:37)
    at p (application-1dc4fd5….js:6)
    at u (application-1dc4fd5….js:6)
```

**Comment by ThePatzen** [comment] 2017-05-11 06:23
@martini Any idea?

**Comment by martini** [comment] 2017-05-11 06:26
@ThePatzen sorry. Busy with earning money... 

I can't reproduce it, for me it works fine. But I believe in your problem. :)

Important for me are the drop zones (where your leave the ticket). Can you attache a little video do follow what are you doing exactly? Thanks!

**Comment by thorsteneckel** [comment] 2017-05-11 06:52
@ThePatzen - Please include the browser console in your video. Have you been to the database and removed entries or so?

**Comment by Munskin** [comment] 2017-05-11 14:44
Same problem here. 

`Uncaught TypeError: Cannot read property 'attr' of null
    at Array.complete (application-5a4dce19f4eceb937619af35311e6b976238c540083c8a6def225b0965fb2415.js:37)
    at p (application-5a4dce19f4eceb937619af35311e6b976238c540083c8a6def225b0965fb2415.js:6)
    at u (application-5a4dce19f4eceb937619af35311e6b976238c540083c8a6def225b0965fb2415.js:6)`

Which leaves the Bulk action in this state:

![image](https://cloud.githubusercontent.com/assets/7374747/25955239/f8033966-3668-11e7-9ae7-ae848d7b7101.png)

This happens in like 1 out of 10 times using the Bulk action.

**Comment by martini** [comment] 2017-05-11 23:57
Hi @ThePatzen 
hi @Munskin 

thanks for the description how to reproduce. I found timing issues which are fixed now in stable. Please update, feedback is welcome!

 -Martin

**Comment by Munskin** [comment] 2017-05-12 08:51
Thanks. After updating I haven't experienced this bug. So it seems fixed :)

**Comment by martini** [comment] 2017-05-12 12:01
Thanks for feedback @Munskin !

**Closed** 2017-05-12 12:01 UTC
Labels: bug
