### ISSUE TITLE
Setting article.from when using Ticket creation API

### ISSUE THREAD

**Issue by jag82** [zammad/zammad#1583] opened 2017-10-24 13:58 UTC
When creating a ticket with an article, I'd like to be able to set the 'from' field for the article:

PAYLOAD:
{
 "title": "Testing via direct POST",
 "group": "some group",
 "customer_id": "guess:test@test.test",
 "article": {
   "from": "another@email.address",
   "body": "some body",
   "type": "web",
   "internal": false
 },
 "note": "some note"
}

RESULT:
The "from" field of the article is the user whose token was used for api authorization.

I've also tried:
  "from": "guess:email@email.email"
  "from_id": "guess:email@email.email"
with the same result.

Is there a way to add an email or give an arbitrary string (e.g. Jane Doe) to the from field of Articles when creating tickets via the API?  For bonus points, is this documented somewhere?

**Comment by thorsteneckel** [comment] 2018-03-01 09:53
@rolfschmidt - I think this is a duplicate of #1805 and resolved thanks to your changes, am I right?

**Comment by rolfschmidt** [comment] 2018-03-01 10:46
Hi @jag82 ,
yes this is possible now in develop branch. Please take a look at my referenced note to this issue:

https://github.com/zammad/zammad/issues/1805#issuecomment-365326227

The new header should solve your problem too ;-)

If you have any questions, please let me know ;-)

(documentation with example curl requests are also given in the link above)

Best regards,
Rolf

**Closed by rolfschmidt** 2018-03-01 10:46 UTC
