### ISSUE TITLE
IMAP fetch stops because of request timeout

### ISSUE THREAD

**Issue by maggusf** [zammad/zammad#2321] opened 2018-10-29 16:43 UTC
### Infos:

* Used Zammad version: 2.7
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: psotgresql
* Elasticsearch version: latest in zammad 2.7
* Browser + version: mac os safari

### Expected behavior:

* email fetching with imap connection should not stop/hang unexpectedly 

### Actual behavior:

* fetching hangs without any error - monitoring site in settings shows that it got stuck for more than x hours (or days) - scheduler_out.log and scheduler_err.log is empty - no error in production.log
-> currently having a cron job to restart zammad-worker-1 service every 2 hours to fetch emails again

### Steps to reproduce the behavior:

* happens several times a days

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-10-29 18:18
Hi @maggusf - do you think this is a duplicate of #2043? What are the specs of your system (because of the relation to RAM limitations)?

**Comment by maggusf** [comment] 2018-10-31 08:54
Hi @thorsteneckel - our machine currently has 4 cores and 12GB RAM. Elasticsearch JVM currently starts with 4GB (as of /etc/elasticsearch/jvm.options). 
As we dont keep mails on server it might not be a duplicate of #2043

**Comment by thorsteneckel** [comment] 2018-10-31 09:19
That sounds sufficient - just one question: How many mails do you process on a regular day? Is your process completely killed or "just" stuck? If it was killed please check your log files if the linux out of memory (OOM) killer killed your process. If it's stuck let me know.

**Comment by maggusf** [comment] 2018-10-31 09:33
hi, process just got stuck - no info/error messages for OOM killer. 
cant say how many mails are processed each day, not more than 500, but not less than 50 - need more numbers? can I find somewhere in the postgresql database?

**Comment by thorsteneckel** [comment] 2018-10-31 09:48
Thanks! The rough number is enough to get a sense. In #2043 we're talking about 27k mails. So if the process got stuck please do the following:

- [Download the latest `rbspy` release](https://github.com/rbspy/rbspy/releases)
- Execute `rbspy` according to your setup and pass the PID parameter of your stuck process (e.g. `sudo ./rbspy record -p 4223`)
- Let `rbspy` run for about 10-15 seconds and stop it with `Ctrl-C`
- `rbspy` will print out some paths to the generated output files. Zip and upload them to this issue

**Comment by maggusf** [comment] 2018-10-31 09:51
hi thorsten, will do that tomorrow during public holiday in most parts of germany (as mails wont be processed during that time and I can't estimate when the problem happens) and come back to you asap.

**Comment by maggusf** [comment] 2018-11-02 07:32
took a while but it got stuck again yesterday evening around 20:43. used rbspy with process# of process number of last fetching imap entry (was script/scheduler.rb start -t). output files are attached
[zammad_issue_2321.zip](https://github.com/zammad/zammad/files/2541421/zammad_issue_2321.zip)

**Comment by thorsteneckel** [comment] 2018-11-02 07:39
Thanks! Can you please provide your `log/production.log` file around this time? Maybe 1 hour before and after that event?

**Comment by maggusf** [comment] 2018-11-02 07:41
hi thorsten, that would be difficult as there are a lot of personal info and customer data within the log. can a filter some lines for you?

**Comment by thorsteneckel** [comment] 2018-11-02 10:13
Hi @maggusf the "good" news is that we have the same issue on one of our hosted instance since a few days. I'm already investigating it and added debug code to get to the root cause. Could you provide the result of this grep so I can sync my results with your system:
`grep -E "Scheduler running...|Channel.fetch| ERROR " log/production.log`

Thanks!

**Comment by maggusf** [comment] 2018-11-02 10:20
sounds "good". ;) output file is attached
[zammad_issue_2321_grep_production.log.out.log](https://github.com/zammad/zammad/files/2542002/zammad_issue_2321_grep_production.log.out.log)

**Comment by thorsteneckel** [comment] 2018-11-06 15:18
This is fixed with the commit(s) above and will be available in the packages in about 30 minutes from now 🚀 feedback would be great!

**Closed as completed by thorsteneckel** 2018-11-06 15:18 UTC
Labels: bug, channel, verified

**Comment by maggusf** [comment] 2018-11-06 15:25
I am currently on a conference, will update Friday or beginning of next week and give feedback asap

**Comment by maggusf** [comment] 2018-11-12 06:05
seems to work now. messages like the following pop up now from time to time:
E, [2018-11-12T06:51:03.169393 #11128] ERROR -- : Can't use Channel::Driver::Imap: #<Timeout::Error: execution expired>

**Comment by thorsteneckel** [comment] 2018-11-12 07:43
Hi @maggusf - Thanks for the feedback! Yes, I forgot to mention that the cause of this error was that some of the IMAP connections had no timeout and were stuck. We added timeouts and therefore these previous stuck calls now die. This is problem in general because Zammad will do its job on the next fetch run but in general the availability of and connection of the IMAP server should get checked to reduce these errors.
