### ISSUE TITLE
Mails with attached audio file are unprocessed after upgrade to Zammad 3.3

### ISSUE THREAD

**Issue by theantmich** [zammad/zammad#2963] opened 2020-03-09 13:44 UTC
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): Package (apt)
* Operating system: Ubuntu 18.04
* Database + version: PostgreSQL 10.12
* Elasticsearch version: 7.6.0
* Browser + version: Chrome 80.0.3987.122

### Expected behavior:

*Emails coming in with an audio file as attachements are picked up by Zammad and open tickets as they normally should.

### Actual behavior:

*Emails with an audio file are left unprocessed by Zammad. Other mails are still coming in normally.

### Steps to reproduce the behavior:

*Have Zammad 3.3 freshly upgraded from 3.2. Send an email with an audio file (.wav) attached to the mail. It will get stuck in the processing.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-03-09 13:46
Looks like a regression of https://github.com/zammad/zammad/issues/2894

**Comment by theantmich** [comment] 2020-03-09 13:56
It could be. Initially, we upgraded to 3.3 to try to apply the fix to the #2894 bug.

**Comment by mantas** [comment] 2020-03-09 13:58
@theantmich any chance to get a sample email that fails to import?

**Comment by theantmich** [comment] 2020-03-09 14:54
@mantas 

I uploaded the email file as a png so that it can be added to the thread.
To see the email, change the file extension to .msg.

![Fw_ Message    de Antoine Michaud (279)](https://user-images.githubusercontent.com/61239471/76226344-1d514000-61f4-11ea-9adf-b7343fe3336c.png)

Thanks

EDIT : If that doesn't work, here's an actual image of the mail
![image](https://user-images.githubusercontent.com/61239471/76226621-80db6d80-61f4-11ea-9c2b-6ee4281347d9.png)

**Comment by MrGeneration** [comment] 2020-03-09 15:11
While importing works, this seems to be the known winmail.dat issue: https://github.com/zammad/zammad/issues/2403

I'll close this issue in favor for 2403.
Using conversion services helps, but right now Zammad itself fails doing so.

At least the example you provided is effected.

![image](https://user-images.githubusercontent.com/6549061/76228175-ab432000-6220-11ea-9dd0-557c04cf66a1.png)

**Closed as completed by MrGeneration** 2020-03-09 15:11 UTC
Labels: duplicate
