### ISSUE TITLE
 Pressing "Shift + Ctrl + N" opens a new private window

### ISSUE THREAD

**Issue by abckas** [zammad/zammad#1379] opened 2017-08-31 08:31 UTC
### Infos:

* Used Zammad version: 1.5.x
* Operating system: Windows 10
* Browser + version: Google Chrome Version 60.0.3112.113 (Offizieller Build) (64-Bit)

### Expected behavior:

* Pressing "Shift + Ctrl + N" opens the Window to create a new ticket

### Actual behavior:

* Pressing "Shift + Ctrl + N" opens a new private window in google chrome

### Steps to reproduce the behavior:

*  Pressing "Shift + Ctrl + N"

**Comment by thorsteneckel** [comment] 2017-08-31 08:33
Duplicate of #656.

**Closed by thorsteneckel** 2017-08-31 08:33 UTC
