### ISSUE TITLE
Setup and subsequent deletion of SLA 

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4359] opened 2022-11-15 11:58 UTC
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #10117018

### Expected behavior:

* When setting up an SLA and deleting it immediately afterwards, the calculated escalation time below the title of the ticket should disappear again.  

### Actual behavior:

* When setting up an SLA and deleting it immediately afterwards, the calculated escalation time below the title is kept until the next update (with article) of the ticket. A note suffices. 

### Steps to reproduce the behavior:

* Create SLA.
* Find "Escalation" time below ticket title. 
* Delete SLA.
* Find that "Escalation" below ticket title is still there. 
* Update ticket adding an article. 
* Calculated time for "Escalation" disappears.  

### Remark

* Usually one does not set up an SLA and deletes it immediately. So the impact/importance of this issue is rather low. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-11-15 12:12
Duplicate of #4353

**Closed as completed by MrGeneration** 2022-11-15 12:12 UTC
Labels: bug, verified, prioritised by payment
