### ISSUE TITLE
next_state_id was ignored

### ISSUE THREAD

**Issue by schmanat** [zammad/zammad#2287] opened 2018-10-15 11:07 UTC
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): DEB
* Operating system: Ubuntu LTS 16.04
* Database + version: PostgreSQL 9.5
* Elasticsearch version: latest
* Browser + version: Chrome (latest) and Firefox (latest)

### Expected behavior:

* If I update a state (pending reminder) and set the next_state_id to 2 (open) and wait until this date (and time) is reachted, nothing happen --> next_state_id is ignored

### Actual behavior:

* Update an existing State (for example: pending reminder)
* set the next_state_id to 2 (open) 
* create a ticket an change state to pending reminder
* wait until the end is reachted
* the ticket state stays to pending reminder

I have also created a thread in the [forum](https://community.zammad.org/t/own-states-next-state-id-not-working/1399) but without any response, so I think it could be a bug :)

### Steps to reproduce the behavior:

* Update an existing State (for example: pending reminder)
* set the next_state_id to 2 (open) 
* create a ticket an change state to pending reminder
* wait until the end is reachted
* the ticket state stays to pending reminder

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-10-15 11:29
I'm pretty confident that this is an issue limited to your instance. You can verify this by creating a free online instance [here](https://www.zammad.com/getting-started). In case you can reproduce the error on this instance please let us know here what the name of the instance is so we can have a look. Closing now.

**Comment by schmanat** [comment] 2018-10-15 12:32
Thanks for your hint with the free online instance. I can reproduce it. I've create the instance (dornbirn.zammad.com). 

First of all I list the state via API, I get the JSON Objects back
`https://dornbirn.zammad.com/api/v1/ticket_states/`

```json
{
        "id": 2,
        "state_type_id": 2,
        "name": "open",
        "next_state_id": null,
        "ignore_escalation": false,
        "default_create": false,
        "default_follow_up": true,
        "note": null,
        "active": true,
        "updated_by_id": 1,
        "created_by_id": 1,
        "created_at": "2018-10-15T11:57:08.338Z",
        "updated_at": "2018-10-15T11:57:08.338Z"
    },
{
        "id": 3,
        "state_type_id": null,
        "name": "pending reminder",
        "next_state_id": null,
        "ignore_escalation": true,
        "default_create": false,
        "default_follow_up": false,
        "note": null,
        "active": true,
        "updated_by_id": 1,
        "created_by_id": 1,
        "created_at": "2018-10-15T11:57:08.345Z",
        "updated_at": "2018-10-15T11:57:08.345Z"
    }
```

After that I do a put Request to update the state (pending reminder)
`https://dornbirn.zammad.com/api/v1/ticket_states/3`

```json
"next_state_id": 2
```

After that I checked if the Update was correct by getting the states again
`https://dornbirn.zammad.com/api/v1/ticket_states/`

```
{
        "id": 3,
        "state_type_id": 3,
        "name": "pending reminder",
        "next_state_id": null,
        "ignore_escalation": true,
        "default_create": false,
        "default_follow_up": false,
        "note": null,
        "active": true,
        "updated_by_id": 1,
        "created_by_id": 1,
        "created_at": "2018-10-15T11:57:08.345Z",
        "updated_at": "2018-10-15T11:57:08.345Z"
    }
```

The next step, was to create a ticket and set the state to "pending reminder". After the time was reached the state was still "pending reminder".

![2018-10-15 14_31_43-zammad helpdesk - 54003 - noch ein testticket](https://user-images.githubusercontent.com/1080148/46951068-241f6600-d087-11e8-9015-1497a7dce345.png)
![2018-10-15 14_31_32-zammad helpdesk - offen](https://user-images.githubusercontent.com/1080148/46951069-241f6600-d087-11e8-8752-10459fbf913a.png)

**Comment by thorsteneckel** [comment] 2018-10-15 12:50
Hi @schmanat - Thanks for reproducing it! We will have a look and let you know.

**Comment by rlue** [comment] 2018-10-24 10:50
Hi @schmanat,

Just discussed this issue with @martini, and it turns out that this is actually the intended behavior of the "pending reminder" state.

That is, "pending reminder" is for **reminders only**. You can create a new, custom "pending open" state that will automatically set the state to "open" when the designated date passes. (But be warned, _this will not send out any reminder notifications!_)

There are two ways to do this:

#### via `rails console`

```
$ zammad rails console
>> Ticket::State.create( \
     state_type_id: Ticket::StateType.find_by(name: 'pending action').id, \
     name: 'pending open', \
     next_state_id: Ticket::State.find_by(name: 'open').id, \
     ignore_escalation: true, \
     active: true, \
     created_by_id: 1, \
     updated_by_id: 1 \
   )
```

#### via REST API

1. Find the `state_type_id` of the "pending close" ticket state:

   ```
   # GET https://dornbirn.zammad.com/api/v1/ticket_states
   [ ...
     {"id"=>7,
     "state_type_id"=>4,
     "name"=>"pending close",
     "next_state_id"=>4,
     "ignore_escalation"=>true,
     "default_create"=>false,
     "default_follow_up"=>false,
     "note"=>nil,
     "active"=>true,
     "updated_by_id"=>1,
     "created_by_id"=>1,
     "created_at"=>"2018-10-24T10:43:45.114Z",
     "updated_at"=>"2018-10-24T10:43:45.114Z"}]
   ```

   Here, the `state_type_id` is **4**.

2. Create a new ticket state with the REST API using:

   * the `state_type_id` you found in Step 1,
   * the `next_state_id` you found in your last comment, and
   * the other attributes outlined in the `rails console` directions above.

   ```
   # POST https://dornbirn.zammad.com/api/v1/ticket_states
   ```

---

If, however, you want BOTH a reminder notification and automatic state switching, then you'll have to configure a [trigger](https://zammad-admin-documentation.readthedocs.io/en/latest/manage-trigger.html) that sets the ticket state to "open" when the "pending reminder" due date has passed.

If you need any more help, please don't hesitate to ask!

**Closed as completed by rlue** 2018-10-24 10:50 UTC
Labels: question
