### ISSUE TITLE
Object Manager: Change object type of an input field to dropdown failed 

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#631] opened 2017-01-17 08:00 UTC
![zammad_error_select](https://cloud.githubusercontent.com/assets/5445062/22012140/ee367748-dc92-11e6-93ea-05c46005427c.png)

The bug happens if you create a text field and update the database. Afterwards you change the field to an option field with the values of the given screenshot.

We also have users that told us that the problem also happens on the creation of new objects with the values of the given screenshot. For me the problem was only reproducible on changing fields, but there might be an relation. (Ticket#10091)

**Comment by rolfschmidt** [comment] 2017-02-06 09:02
Error: Invalid data_option[:options] or data_option[:relation] param

**Comment by thorsteneckel** [comment] 2018-01-25 17:01
Hi @muhammadn - this is a duplicate of the issue you are currently working on (I guess it was #1752), right? Can you please verify it's fixed, mark it as a duplicate, remove the other tags and close it if it's the case? Thanks!

**Comment by muhammadn** [comment] 2018-01-31 08:36
@thorsteneckel yes it is a duplicate issue which is fixed in #1752 

So i will close this issue now.

**Closed by muhammadn** 2018-01-31 08:36 UTC
Labels: admin area, bug
