### ISSUE TITLE
Wish: Make article content make better use of the available window width

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1181] opened 2017-06-09 18:13 UTC
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: DEB package
* Operating system: Linux (Debian 8)
* Browser + version: Firefox 50.1.0

### Expected behavior:

The article area (`class="ticket-article"`) either uses the whole/more of the available area (`div class="ticketZoom"`) or is configurable to a certain (maximum)  percentage to use.

### Actual behavior:

The article area doesn't grow over a certain width.  When working on wide screens this is a waste of screen space and makes more vertical scrolling necessary then it would when the text could expand horizontally

![zammad_articlezoom](https://user-images.githubusercontent.com/279232/26988443-bc51f274-4d4f-11e7-8391-49f3478ed792.png)

**Comment by martini** [comment] 2017-06-09 18:58
@fthommen is it a duplicate of? This would be already in master branch (available in next release).

**Comment by fthommen** [comment] 2017-06-09 20:24
@martini duplicate of which issue? ;-)  I haven't found an issue describing this.

**Comment by MrSnoozles** [comment] 2017-06-12 12:57
@fthommen I think it's a duplicate of #1059

**Comment by thorsteneckel** [comment] 2017-06-12 13:10
Thanks for your great support with our issues @MrSnoozles 😍 I think the issues you were looking for is #957 - and yes, it's a duplicate. If there are still issues with this please discuss it in the other issue with the assignee.

**Closed by thorsteneckel** 2017-06-12 13:10 UTC
