### ISSUE TITLE
Change Shortcut for Translation

### ISSUE THREAD

**Issue by bastolino** [zammad/zammad#3557] opened 2021-05-13 08:30 UTC
Hi everyone,

the shortcut Ctrl-Shift-T is for reopen the last recent closed tab in many browsers (at least Firefox and Chrome). This shortcut is superseded by zammad to show the translation-texts. Although this is really a good feature of zammad, it regularly blocks me from using that shortcut.
Moreover: If I am editing a ticket, noting something down, realizing I forgot to check something, I intuitively hit Ctrl-Shift-T to reopen the last tab. Unfortunately, the following happens:
- all my edited text has gone
- the translation-mode gets in
- the last tab in the browser does not start.

I acknowledge this is intended behaviour, but I'd appreciate having a possibility to deactivate that feature or move that shortcut to something else, that does not superseed a browser-shortcut.

Thanks a lot for helping me not getting any more gray hairs ;)

Best wishes
Sebastian

**Comment by MrGeneration** [comment] 2021-05-13 09:28
Duplicate of #656

**Closed as completed by MrGeneration** 2021-05-13 09:28 UTC
Labels: duplicate
