### ISSUE TITLE
Add possibility to drag and drop inline images between notices 

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#700] opened 2017-02-01 08:29 UTC
User recommendation:

It would be great if the user would have the possibility to drag and drop inline image of a previous article to the new article the user want to write ( Attachments of other articles would be cool too).

![zammad_feature_inline_image_drag_and_drop](https://cloud.githubusercontent.com/assets/5445062/22499708/a08cb168-e860-11e6-9b2e-be639b742e3a.png)

**Comment by thorsteneckel** [comment] 2017-02-01 08:41
Currently the used (, unmaintained and maybe outdated? 😖) file uploader doesn't support this: https://github.com/zammad/zammad/blob/6960e42f9d1e98770e7d3f58d59a5743dcb8aa7c/app/assets/javascripts/app/lib/base/jquery.fineuploader-3.0.js

**Comment by martini** [comment] 2017-02-01 08:42
@thorsteneckel it's no file uploader issue, it can be done via html5/d&d api.

**Comment by thorsteneckel** [comment] 2017-02-01 08:44
🚀 nice! Please just ignore my gibberish then

**Comment by thorsteneckel** [comment] 2020-01-20 16:06
This is a duplicate of #2192 - technically this one here is older. However, the other one is far more complete in its description. Therefore I will close this one in favor of #2192.

**Closed by thorsteneckel** 2020-01-20 16:06 UTC
Labels: UX/UI, feature backlog, frontend / JS app, proposal

**Comment by vitjok** [comment] 2020-03-17 19:43
#2192 is not about drag and drop, it is about "Right click on the image in the created article -> Copy".

#2192 is fixed in 3.3 but I still can reproduce #700. 

May be #2976 will fix #700? Not sure, because #2976 is about "CTRL-C, CTRL-V" and not about drag and drop.
