### ISSUE TITLE
Exclude retweets from search results if retweet tracking is disabled

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2571] opened 2019-05-13 10:25 UTC
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammad will not track retweets if disabled, even if it finds keywords within a retweet.

### Actual behavior:

Zammad will import retweets (even if disabled) as soon as one of your search phrases applies.

### Steps to reproduce the behavior:

* activate twitter integration with disabled retweet tracking
* create a tweet that contains one of your search phrases
* retweet that tweet
* find it in Zammad

### Information for developers:
This initially comes from a follow up in #627 

Technically, there seems to be no "initial" way of searching without retweets.
The following post might help: https://stackoverflow.com/questions/27941940/how-to-exclude-retweets-and-replies-in-a-search-api

Return samples can be found here:
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets

**Comment by orangesunny** [comment] 2020-08-17 12:45
I was pointed here by the Zammad customer support. For a start, we (the company with Zammad paid plan) would like to have the checkbox working. I don’t see this as an enhancement, it is clearly a bug if the checkbox does nothing.

<img width="660" alt="twitter checkbox" src="https://user-images.githubusercontent.com/23450011/90397458-2a723500-e098-11ea-96f2-3f26febf5033.png">

**Comment by MrGeneration** [comment] 2020-08-17 12:51
@orangesunny sorry for the confusion.
You're actually affected by this bug: https://github.com/zammad/zammad/issues/2736

The difference to this issue is that you don't use the search functionality for tweets.
I already updated the affected issue like it should be!

**Comment by thorsteneckel** [comment] 2020-08-21 14:21
This is actually an (older) duplicate of #2736 that wasn't on our radar because of the `enhancement` tag. @rlue already provided a fix #2736 it which is currently in review but will be releases with 3.5. I'll close this in favour of #2736.

**Closed as completed by thorsteneckel** 2020-08-21 14:21 UTC
Labels: duplicate
