### ISSUE TITLE
Elasticsearch Index reseted during ticket delete

### ISSUE THREAD

**Issue by athanasius-kircher** [zammad/zammad#2725] opened 2019-08-31 08:07 UTC
### Infos:

* Used Zammad version: 3.1.0
* Installation method (source, package, ..): source
* Operating system: Debian 9
* Database + version: MYSQL 5.7
* Elasticsearch version: 6.3.1
* Browser + version: -

We have a working Elasticsearch setuped for Zammad and followed the given instructions. After an initial indexing, triggered with `rake searchindex:rebuild`, we have over 4k docs in zammad_production_ticket (checked with `curl 'localhost:9200/_cat/indices?v'`) and the search works as expected. But after a while the search does not produce any results. So we checked the indices again and zammad_production_ticket has no docs left, but the other indices still have the data.

So we turned on the logging and could find the following info in the log (see below). After a ticket delete Zammad seems to drop the total ticket search index. This ticket delete seems to come from an automatisation, that is configured to filter tickets by a tag and delete them (see screen below).

As a workaround I can schedule this automatisation so that a cronjob afterwards starts reindexing.

### Expected behavior:
Elasticsearch indices should not be reseted by normal Zammad usage and user should not be forced to manually start reindexing.

### Actual behavior:

* Currently an action in Zammad resets the index. We think it is the described automatisation.

### Steps to reproduce the behavior:

* See description above.
- Setup elastic search
- Setup an automatisation that deletes a ticket
- Force automatisation to delete a ticket
- Check search for tickets or elasticsearch index

Yes I'm sure this is a bug and no feature request or a general question.

<img width="866" alt="automatisation" src="https://user-images.githubusercontent.com/1197748/64061149-a862d500-cbd6-11e9-80f4-65209df973d6.png">

```
I, [2019-08-30T17:04:37.907990 #29296-69901965119280]  INFO -- : execute Job.run (try_count 0)...
I, [2019-08-30T17:04:38.001669 #29296-69901965119280]  INFO -- : Deleted ticket from job {"ticket.action"=>{"value"=>"delete"}} Ticket.find(6496)
I, [2019-08-30T17:04:38.028344 #29296-69901965119280]  INFO -- : NOTICE create - self.created_by_id is different: 10/1
I, [2019-08-30T17:04:38.090850 #29296-69901965119280]  INFO -- : storge remove ....
I, [2019-08-30T17:04:38.103696 #29296-69901965119280]  INFO -- : storge remove ....
I, [2019-08-30T17:04:38.132261 #29296-69901965119280]  INFO -- : Enqueued SearchIndexJob (Job ID: 819ef510-4512-498c-a9fd-89309f213ea3) to DelayedJob(default) with ar
guments: "Ticket", 6496
I, [2019-08-30T17:04:38.137524 #29296-69901965119280]  INFO -- : Enqueued SearchIndexJob (Job ID: e4dcf79f-7ea3-4683-9809-8ef3cb6ab967) to DelayedJob(default) with ar
guments: "User", 1840
I, [2019-08-30T17:04:38.163114 #29296-69901965119280]  INFO -- : storge remove ....
I, [2019-08-30T17:04:38.168769 #29296-69901965119280]  INFO -- : Enqueued SearchIndexJob (Job ID: 5bd5e972-7c3b-4862-9bc5-6721316f38ad) to DelayedJob(default) with ar
guments: "Ticket", 6496
I, [2019-08-30T17:04:38.214379 #29296-69901965119280]  INFO -- : # curl -X DELETE "http://localhost:9200/zammad_production_ticket"
I, [2019-08-30T17:04:38.367806 #29296-69901965119280]  INFO -- : # 200
I, [2019-08-30T17:04:38.377395 #29296-69901965119280]  INFO -- : Enqueued SearchIndexJob (Job ID: 5c7ea705-744a-4b9a-9d65-128b0007dc60) to DelayedJob(default) with ar
guments: "User", 1840
```

**Comment by MrGeneration** [comment] 2019-09-03 09:07
Thanks for your report and sorry for asking back, I just want to make sure to understand if I got you correct:

You're saying that without running `rake searchindex:rebuild` Zammad does drop valid data from the searchindex, even though the data should be still there because e.g. the ticket is?

This then forces you to manually rebuild the index?

**Comment by athanasius-kircher** [comment] 2019-09-03 15:22
Yes that is exactly what I meant.

I have ticket (A) in my search index and can find it. After a while ticket (A), that does still exist, is not found anymore and dropped from the search index. I have not run `rake searchindex:rebuild` during this time.

If now, I start `rake searchindex:rebuild` again, ticket (A) can be found again.

To me, according to the logs above, it seems that an automated deletion of another ticket (B) leads to the drop of the total index.

**Comment by MrGeneration** [comment] 2019-09-25 16:57
I could verify this, this has nothing to do with scheduled deletion task, but rather the deletion itself. I can manually reproduce this by deleting any ticket I want.

This is properbly an indirect duplicate of https://github.com/zammad/zammad/issues/2742 - as I'm currently not sure if it only fixes the Knowledgebase-Part, I'll leave this open for now.

@thorsteneckel could you check if the above issue fix is going to address not just the KB but all parts in Zammad for ES later 5.6 ?

```
root@zammad:/opt/zammad# zammad run rails c
Loading production environment (Rails 5.2.3)
irb(main):001:0> Ticket.find(6).destroy
Ticket.find(6) notify TOUCH 2019-09-25 16:54:55 UTC
Enqueued SearchIndexJob (Job ID: 4a911df7-7065-4810-b87c-de7877762e79) to DelayedJob(default) with arguments: "Ticket", 6
Enqueued SearchIndexJob (Job ID: 6ccb2f8b-6748-4b83-ab59-e76c7434170c) to DelayedJob(default) with arguments: "KnowledgeBase::Answer::Translation", 23
Ticket::Article.find(12) notify DESTOY 2019-07-25 14:53:41 UTC
Ticket.find(6) notify UPDATED 2019-09-25 16:54:55 UTC
Enqueued SearchIndexJob (Job ID: 040d3cf8-00b6-4085-b83a-7e456bc3b44c) to DelayedJob(default) with arguments: "Ticket", 6
User.find(10) notify TOUCH 2019-09-25 16:54:55 UTC
Enqueued SearchIndexJob (Job ID: a2b35c4c-1e9d-470d-a16e-79d4a5287fe1) to DelayedJob(default) with arguments: "User", 10
Ticket::Article.find(11) notify DESTOY 2019-07-24 16:53:41 UTC
Ticket.find(6) notify UPDATED 2019-09-25 16:54:55 UTC
Enqueued SearchIndexJob (Job ID: 103fa81c-e395-4fcb-af7e-c35fd5fb3c3f) to DelayedJob(default) with arguments: "Ticket", 6
User.find(10) notify TOUCH 2019-09-25 16:54:55 UTC
Enqueued SearchIndexJob (Job ID: 2f169d5a-c461-476e-9608-f2fa7ffd9937) to DelayedJob(default) with arguments: "User", 10
Ticket.find(6) notify DESTOY 2019-09-25 16:54:55 UTC
# curl -X DELETE "http://localhost:9200/zammad_production_ticket"
# 200
User.find(10) notify TOUCH 2019-09-25 16:54:55 UTC
Enqueued SearchIndexJob (Job ID: f21d28f9-2578-43d4-a3d6-f2c3287a2494) to DelayedJob(default) with arguments: "User", 10
Setting.reset_change_id: set new cache, 90872815
Setting.set('kb_active_publicly', true)
Enqueued ChecksKbClientNotificationJob (Job ID: 296b8ddc-0f2e-483e-98d4-f2905633568b) to DelayedJob(default) with arguments: "KnowledgeBase::Answer", 12, "touch"
Enqueued ChecksKbClientNotificationJob (Job ID: 5d491eb0-0e07-4d22-bb35-6d6a3f23372d) to DelayedJob(default) with arguments: "KnowledgeBase::Category", 8, "touch"
=> #<Ticket id: 6, group_id: 1, priority_id: 2, state_id: 4, organization_id: nil, number: "71006", title: "complaint wrong delivery of order #51519891", owner_id: 1, customer_id: 10, note: nil, first_response_at: nil, first_response_escalation_at: nil, first_response_in_min: nil, first_response_diff_in_min: nil, close_at: "2019-09-25 16:54:55", close_escalation_at: nil, close_in_min: nil, close_diff_in_min: nil, update_escalation_at: nil, update_in_min: nil, update_diff_in_min: nil, last_contact_at: "2019-07-25 14:53:41", last_contact_agent_at: "2019-07-25 14:53:41", last_contact_customer_at: "2019-07-24 16:53:41", last_owner_update_at: nil, create_article_type_id: 1, create_article_sender_id: 2, article_count: 0, escalation_at: nil, pending_time: nil, type: nil, time_unit: nil, preferences: {}, updated_by_id: 5, created_by_id: 10, created_at: "2019-07-24 16:53:41", updated_at: "2019-09-25 16:54:55">
```

**Comment by thorsteneckel** [comment] 2019-09-25 17:02
This is duplicate of #2742 - a fix is in the making and currently going through QA. Closing now.

**Closed as completed by thorsteneckel** 2019-09-25 17:02 UTC
Labels: duplicate
