### ISSUE TITLE
Sending e-mail via SMTP gets stuck if TO/CC e-mail is invalid

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2550] opened 2019-04-23 09:30 UTC
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: -
* Elasticsearch version: -
* Browser + version: Firefox latest

### Expected behavior:

* When answering via reply button and adding an invalid e-mail address to "TO" or "CC" Zammad throws an error and notifies the user that the e-mail address is invalid and where without trying to actually send to the invalid e-mail.

### Actual behavior:

* Initially no error message, email sending for that particular group is completely stuck and has to be killed manually. After killing the mail sending process error message is shown identifying the issue with the typed email address:

> Delivery failed: "Unable to send email to 'testmail@example.com”': Can't use Channel::Driver::Smtp: #<Net::SMTPSyntaxError: 501 <testmail@example.com”>: malformed address: ”> may not follow <testmail@example.com >" 

It would be great if the mail sending process would not be initiated before the validity of the e-mail address is checked.

### Steps to reproduce the behavior:

* Create new ticket
* Answer via mail 
* Add receiver e-mail address to "TO" that has a trailing " symbol after the domain name.
* Try sending mail via smtp

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-04-23 09:52
Sorry, but I can't reproduce this.
My Zammad-Instance does send a E-Mail to the Mail-System, which tells Zammad to provide a valid address. Zammad does try this up to 4 times - the error you receive comes from your Mail-System.

Closing now.

![image](https://user-images.githubusercontent.com/6549061/56571956-51147e80-65be-11e9-8fe6-9b246b6c4ce0.png)

Edit:
This is the output after 4 times failing:
![image](https://user-images.githubusercontent.com/6549061/56572018-773a1e80-65be-11e9-8592-eac545929620.png)

**Closed as completed by MrGeneration** 2019-04-23 09:52 UTC
Labels: can't reproduce

**Comment by SEGGER-NV** [comment] 2019-04-23 11:20
Hello,

Thank you for investigating.
Does Zammad have no verification if the set e-mail is valid?
I just noticed that there is also a lack of checking when creating a new user. This looks like a design flaw to me that the only check that is being done that there is some top level domain in the email address string. It seems not to be checked anywhere if the email address is valid.
So something@something.de13123"""" would be a valid user email address...

**Comment by MrGeneration** [comment] 2019-04-23 11:37
As far as I'm aware, Zammad does not check if the address is valid.
When creating users, Zammad does check E-Adresses, but not completely. so test@example does not work, but test@example.com" does.

**Comment by multiOTP** [comment] 2021-01-28 12:54
> As far as I'm aware, Zammad does not check if the address is valid.
> When creating users, Zammad does check E-Adresses, but not completely. so test@example does not work, but [test@example.com](mailto:test@example.com)" does.

Please note that same thing happens if we choose in a ticket to send an Email to a user for which the email field is simply empty.

**Comment by MrGeneration** [comment] 2021-01-28 12:57
@multiOTP you're recycling a 2 year old issue.
Please don't. Above mentioned behavior is not a bug but will fail in any mail client if you fail to supply a correct mail address.

If there's a bug in Zammad, please create a new issue on this repo.
If this is a technical question, please create a community post over at https://community.zammad.org
