### ISSUE TITLE
Preset the "Wait for close" time

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#1142] opened 2017-05-28 19:06 UTC
Can the "Wait for close" time be preset?

**Comment by martini** [comment] 2017-05-28 19:12
@Linus2017 sorry for telling that, but this is a issue tracker - it's not support forum.

Second, if you create issue, please use the provided issue template. I can't understand your problem at all (no idea what your use case is, no idea what the problem is).

Thanks for understanding.

**Comment by Linus2017** [comment] 2017-05-28 19:27
Where can I find the support forum?

When selecting the status "pending close", a time point must be specified under pending till. Can this be preset (for example in three days)?

**Comment by MrGeneration** [comment] 2018-12-20 16:02
No reaction by user (github account has been removed).

I'm closing this issue.
For everyone that might be searchin our Support Forum, here's a link to our Community: https://community.zammad.org

**Closed by MrGeneration** 2018-12-20 16:02 UTC
Labels: question
