### ISSUE TITLE
Role assignments not set and manually set ones deleted on every LDAP sync

### ISSUE THREAD

**Issue by strangechoice** [zammad/zammad#1818] opened 2018-02-08 13:04 UTC
### Infos:
* Used Zammad version: 2.3 (2.3.0-1517979061.9566acac.stretch amd64)
* Installation method (source, package, ..): Debian Package stable 
* Operating system: Debian 9
* Database + version: ProstgreSQL 9.6.6
* Elasticsearch version: 5.6.7
* OpenLDAP version: 2.4.3 
* Browser + version: any

* ldap_config:
```
irb(main):002:0> pp Setting.get('ldap_config')
{"host_url"=>"ldaps://ldap.phil.hhu.de",
 "ssl_verify"=>true,
 "options"=>{"ou=Phil-Fak,o=HHU,c=de"=>"ou=Phil-Fak,o=HHU,c=de"},
 "option"=>"ou=Phil-Fak,o=HHU,c=de",
 "base_dn"=>"ou=Phil-Fak,o=HHU,c=de",
 "bind_user"=>"cn=admin,ou=Phil-Fak,o=HHU,c=de",
 "bind_pw"=>"XXXXXXX",
 "wizardData"=>
  {"backend_user_attributes"=>
    {"dn"=>
      "dn (e. g. cn=xxxxx,ou=hp-ilo,ou=systemusers,ou=Phil-Fak,o=HHU,c=de)",
     "uid"=>"uid (e. g. xxxxx)",
     "gidnumber"=>"gidnumber (e. g. 100)",
     "userpassword"=>
      "userpassword (e. g. {SSHA}XXXXXXXXXXXXXXXXXXXXXXXXXXXX)",
     "cn"=>"cn (e. g. Xxxxxx Xxxxx)",
     "loginshell"=>"loginshell (e. g. /bin/bash)",
     "gecos"=>"gecos (e. g. Xxxxxx Xxxxx)",
     "homedirectory"=>"homedirectory (e. g. /home/xxxxx)",
     "shadowlastchange"=>"shadowlastchange (e. g. 12690)",
     "uidnumber"=>"uidnumber (e. g. 1596)"},
   "backend_groups"=>
    {"cn=wheel,ou=groups,ou=phil-fak,o=hhu,c=de"=>
      "cn=wheel,ou=groups,ou=phil-fak,o=hhu,c=de",
      [...]
     "cn=pcadmin,ou=groups,ou=phil-fak,o=hhu,c=de"=>
      "cn=pcadmin,ou=groups,ou=phil-fak,o=hhu,c=de",
    [...]
     "cn=studdesk_admin,ou=groups,ou=phil-fak,o=hhu,c=de"=>
      "cn=studdesk_admin,ou=groups,ou=phil-fak,o=hhu,c=de"},
   "user_attributes"=>
    {"login"=>"Login",
     "firstname"=>"Firstname",
     "lastname"=>"Lastname",
     "email"=>"Email",
     "note"=>"Note",
     "web"=>"Web",
     "phone"=>"Phone",
     "mobile"=>"Mobile",
     "fax"=>"Fax",
     "department"=>"Department",
     "address"=>"Address"},
   "roles"=>{"1"=>"Admin", "2"=>"Agent", "3"=>"Customer"}},
 "user_uid"=>"uid",
 "user_filter"=>"(&(objectClass=pfactivity)(pfAccountType=Standard))",
 "group_uid"=>"dn",
 "group_filter"=>"(objectClass=posixgroup)",
 "user_attributes"=>{"uid"=>"login"},
 "group_role_map"=>
  {"cn=wheel,ou=groups,ou=phil-fak,o=hhu,c=de"=>["1"],
   "cn=pcadmin,ou=groups,ou=phil-fak,o=hhu,c=de"=>["2"]},
 "unassigned_users"=>"sigup_roles"}
```

File _/opt/zammad/lib/ldap/group.rb_ slightly modified:
```
--- group.rb.orig	2018-02-06 14:17:56.753011276 +0100
+++ group.rb	2018-02-06 14:38:47.071073028 +0100
@@ -144,7 +144,7 @@
       entry[:memberuid].collect do |uid|
         dn = nil
         @ldap.search("(uid=#{uid})", attributes: %w[dn]) do |user|
-          dn = user.dn
+          dn = user.dn if dn.blank?
         end
         dn
       end.compact
```

This patch makes sure the first found _dn_ is returned instead of the last one. Maybe the value of **ldap_config['user_filter']** should be respected in this context as well?

### Expected behavior:

* LDAP sync should assign _admin_ and _agent_ roles to all users in groups _wheel_ and _pcadmin_

### Actual behavior:

* all LDAP users get disabled
* no automatic role assignments
* manually assigned zammad groups are deleted from the users
* manually set role assignments are kept

### Steps to reproduce the behavior:

* trigger LDAP sync

We always had problems with role assignment via LDAP groups (not working) but the ones manually set were kept. We do not know exactly since which stable release it is broken, because we had an unnoticed hanging LDAP sync since August (sic) which survived several reboots of the machine. Problem persists since we killed this job via _irb(main):003:0> ImportJob.last.destroy_ a few days ago.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rlue** [comment] 2018-05-11 09:50
@strangechoice, I can only partially reproduce this behavior:

#### 1. ❌ all LDAP users get disabled

First, some background: each time you perform an LDAP sync, Zammad will deactivate **any users who were added in a previous LDAP sync but are absent from (or skipped in) the current one** (instead of removing them altogether).

Now, onto your problem: I noticed the following line in your LDAP settings hash:

```ruby
"user_attributes"=>{"uid"=>"login"}
```

When `login` is the **only** mapped user attribute, the LDAP sync skips over all user records (_i.e.,_ Zammad doesn't import anything). This is because all user records must have a First and Last Name.

If you do your initial sync with a valid user attribute mapping (_i.e.,_ one that includes first and last name), successfully import all the users into Zammad, and then update your sync settings to an invalid attribute mapping (_e.g.,_ only `"uid" => "login"`), then the next sync will treat all user records as absent, and then deactivate those users per the rule described above.

The lack of a validation on LDAP-Zammad user attribute mappings qualifies as a bug in its own right, though.

#### 2. ✅ no automatic role assignments

I can confirm this behavior. 

#### 3. ❓ manually assigned zammad groups are deleted from the users

I'm not sure I understand. Due to point 2 above, all users created by an LDAP sync are (re-)assigned to the default role. When selecting a default role, one rule is that it may not be a role which has `admin` or `ticket.agent` permissions.

But groups are only visible and configurable for users who have such permissions. Thus, LDAP-synced users lose their groups more as a consequence of being reassigned to the default role, rather than specifically having their group assignments reset.

#### 4. ❌ manually set role assignments are kept

In my experience, role assignments are always reset to the default role. 

---

We are currently working on this issue, but we would appreciate feedback about the issues we were not able to reproduce.

**Comment by rlue** [comment] 2018-05-15 04:14
Now that I've had a chance to investigate the problem more closely, can you tell me how your LDAP users and groups are associated? 

As you may have noticed in `lib/ldap/group.rb`, [the `Ldap::Group#user_roles` method looks for groups containing a `member`, `memberuid`, or `uniquemember` attribute](https://github.com/zammad/zammad/blob/develop/lib/ldap/group.rb#L83), and uses the value of that attribute for the user-role mapping. 

Given the patch you described to that class above, I assume your LDAP server stores those associations under the `memberuid` attribute. Is that correct?

**Comment by strangechoice** [comment] 2018-05-15 07:27
Hi rlue,

our LDAP tree is quite complex. The association between users and groups is the classic one between __posixAccount__ and __posixGroup__ aka __memberUid__ in __posixGroup__ and additionally the __gidNumber__ attribute in __posixAccount__ (could be ignored though in the context of Zammad...).

Users are in __ou=users,ou=phil-fak,o=hhu,c=de__
Groups are in __ou=groups,ou=phil-fak,o=hhu,c=de__

__posixAccount__ by itself does not provide attributes for __firstname__ and __lastname__, but we extended all our user objects with a self provided objectClass __pfNameinfo__. This objectClass sadly goes undetected by the Webfrontend.

The LDAP wizard detects __(objectClass=user)__ as __user_filter__, which is only used by three Systemusers in __ou=hp-ilo,ou=systemusers,ou=Phil-Fak,o=HHU,c=de__

It would be useful for us, if we could seperate __basedn__s for users and groups

To give you a more complete overview, I attach a simplified overview of our ldap tree:
![ldaptree](https://user-images.githubusercontent.com/3963703/40042553-1f5f5e3c-5822-11e8-84ea-be09a3cab756.png)

**Comment by rlue** [comment] 2018-05-15 08:13
Upon further consideration, this appears to describe a whole collection of problems arising from Zammad's incomplete handling of LDAP configurations. I'm going to close this issue as a duplicate of #1773, and [summarize/reference the problems you describe here in that thread](https://github.com/zammad/zammad/issues/1773#issuecomment-389082445).

Please let me know if I've overlooked or misstated anything.

---

As it turns out, I was only able to reproduce your original issue (point 2 above: role assignments not automatically set) because I was working with a misconfigured sample LDAP server on my local machine. Now that my sample LDAP server is configured correctly, role assignments are automatically set just fine.

To help us diagnose your issue, it would be a great help if you could:

1. Create a file called `debug_issue.rb` in your Zammad directory (usually `/opt/zammad`)
2. Run the file from your Zammad directory via `zammad run rails r debug_issue.rb` or `rails r debug_issue.rb` as zammad user, depending on your installation source (package/source)
3. Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4. Delete the `debug_issue.rb` file

```ruby
# debug_issue.rb

require 'mixin/rails_logger'

module Mixin
  module RailsLogger
    def self.logger
      @logger ||= Logger.new(log_to).tap do |logger|
        logger.level = :debug
      end
    end

    def self.log_to
      # STDOUT
      'debug_issue.log'
    end
  end
end


ImportJob.create(name: 'Import::Ldap').start
```

Thanks for your patience!

**Closed** 2018-05-15 08:13 UTC
Labels: LDAP, integration, verified

**Comment by rlue** [comment] 2018-05-16 00:39
Thanks for your email.

> It shows, that role assignment fails because other 
> parts of the ldap tree are returned in this search.

Are you referring to line 48, which lists the mapping stored in `dn_roles` (and created by `Ldap::Group#user_roles`)? Or did you see other output indicating that?

I suspect the problem may be the [`Ldap::Group#filter` method](https://github.com/zammad/zammad/blob/develop/lib/ldap/group.rb#L114-L116), which sets the search filter to whichever of the following objectClasses is [found first (via `Ldap::FilterLookup#lookup_filter`)](https://github.com/zammad/zammad/blob/develop/lib/ldap/filter_lookup.rb#L11-L19):

* `groupOfUniqueNames`,
* `group`,
* `posixgroup`, or
* `organization`.

If your user-role mapping points to `posixgroup` objects, but your LDAP schema contains `group` objects or `groupOfUniqueNames` objects, then `#filter` will return the wrong search filter to `#user_roles`.

Please let me know if that's correct (or if you have identified the problem elsewhere) so that I can update the main LDAP issue thread appropriately.

**Comment by strangechoice** [comment] 2018-05-16 07:38
Yes, I was referring to line 48, but I think the problem is in [`Ldap::Group#group_user_dns_memberuid` method](https://github.com/zammad/zammad/blob/develop/lib/ldap/group.rb#L143-L151). The search filter for `uid` should include `ldap_conf['user_filter']` as well. The found `dn`s for all role assignments are from other parts of the LDAP tree (`ou=hp-ilo,ou=systemusers,ou=phil-fak,o=hhu,c=de` and `ou=mailsettings,ou=phil-fak,o=hhu,c=de` instead of `ou=users,ou=phil-fak,o=hhu,c=de`)

This would not be the case if the search filter would be something like `"(&(uid=#{uid})" + ldap_conf['user_filter'] + ")"`

**Comment by rlue** [comment] 2018-05-17 01:36
That sounds reasonable. Since the LDAP configuration requires a more extensive redesign which we may not get to anytime soon, we're happy to add this change as a stopgap.

However, I can't confirm that this works without access to your LDAP server. Is there any chance you could run the script below (again, via `rails r`), and tell us if it fixes the problem on your end?

Or, does the all-users-get-deactivated-on-sync problem make that impractical?

```ruby
require 'ldap'
require 'ldap/user'
require 'ldap/group'

Rails.logger.level = :debug

class Ldap
  class Group

    def group_user_dns_memberuid(entry)
      entry[:memberuid].collect do |uid|
        dn = nil
        @ldap.search("(&(uid=#{uid})#{Import::Ldap.config[:user_filter]})", attributes: %w[dn]) do |user|
          dn = user.dn
        end
        dn
      end.compact
    end
  end
end

job = ImportJob.create(name: 'Import::Ldap', payload: {})

job.start

p job.reload.result
```

**Comment by strangechoice** [comment] 2018-05-17 12:16
It's working:

`{"skipped"=>553, "created"=>1, "updated"=>12, "unchanged"=>1913, "failed"=>0, "deactivated"=>0, "sum"=>2479, "total"=>2479, "role_ids"=>{3=>{"skipped"=>0, "created"=>1, "updated"=>0, "unchanged"=>1909, "failed"=>0, "deactivated"=>0, "sum"=>1910, "total"=>0}, 1=>{"skipped"=>0, "created"=>0, "updated"=>4, "unchanged"=>0, "failed"=>0, "deactivated"=>0, "sum"=>4, "total"=>0}, 2=>{"skipped"=>0, "created"=>0, "updated"=>12, "unchanged"=>4, "failed"=>0, "deactivated"=>0, "sum"=>16, "total"=>0}}}`

I had to modify the wizard generated `ldap_config` though:
`conf['user_filter'] = '(objectClass=pfNameinfo)'`
`conf['user_attributes'] = {"uid"=>"login", "pffirstname"=>"firstname", "pfsurname"=>"lastname"}`

The wizard wrongly detects `user_filter = '(objectClass=user)'` from users in `ou=hp-ilo,ou=systemusers,ou=phil-fak,o=hhu,c=de`
Therefore the `pfNameinfo` related attributes `pfFirstname` and `pfSurname` cannot be mapped to the corresponding Zammad attributes in the wizard.

Beside this limitations the LDAP integration is working right now. I've patched my `lib/ldap/group.rb` already. Would be nice, if this could go into one of the following releases...
