### ISSUE TITLE
Selecting specific users for overviews

### ISSUE THREAD

**Issue by dschuette** [zammad/zammad#1418] opened 2017-09-14 09:25 UTC
Used Zammad version: 1.5.x

**Current behaviour:**
If I want to make an overview available for specific users only I'll edit the overview and look up the user's name in the search field, then select that user for the Allowed-list. 
Email addresses currently are being listed instead of full names only if names are not available.
This makes it tricky to select the correct user if it's name is not unique. 

![grafik](https://user-images.githubusercontent.com/22240097/30422317-de373750-993f-11e7-9ed5-08cf871b1424.png)

**Expected behaviour:**
Search results should be unique, i.e. email addresses should always be listed. 
If space is sufficient, listing users' full names & email addresses (in brackets) would be even better.

**Comment by hanneshal** [comment] 2017-09-15 14:24
Hi @dschuette Can you upgrade to the latest version 2.0.1 an test this again please. 
We released it on Monday and I can't reproduce your issue.

regards 
Johannes

**Comment by natseg** [comment] 2017-09-17 23:56
Hi,
Can reproduce issue on:
- Zammad version: 2.1.x

- `[#<User id: 3, organization_id: 1, login: "dennis schuette", firstname: "Dennis", lastname: "Schuette", email: "test3@test.com", image: nil, image_source: nil, web: "", password: "$argon2i$v=19$m=65536,t=2,p=1$dKEQS8pTrrfdvgF1qUZ1...", phone: "", fax: "", mobile: "", department: "", street: "", zip: "", city: "", country: "", address: "", vip: false, verified: false, active: true, note: "", last_login: "2017-09-17 15:15:55", source: nil, login_failed: 0, out_of_office: false, out_of_office_start_at: nil, out_of_office_end_at: nil, out_of_office_replacement_id: nil, preferences: {"notification_config"=>{"matrix"=>{"create"=>{"criteria"=>{"owned_by_me"=>true, "owned_by_nobody"=>true, "no"=>false}, "channel"=>{"email"=>true, "online"=>true}}, "update"=>{"criteria"=>{"owned_by_me"=>true, "owned_by_nobody"=>true, "no"=>false}, "channel"=>{"email"=>true, "online"=>true}}, "reminder_reached"=>{"criteria"=>{"owned_by_me"=>true, "owned_by_nobody"=>false, "no"=>false}, "channel"=>{"email"=>true, "online"=>true}}, "escalation"=>{"criteria"=>{"owned_by_me"=>true, "owned_by_nobody"=>false, "no"=>false}, "channel"=>{"email"=>true, "online"=>true}}}}, "intro"=>true}, updated_by_id: 1, created_by_id: 1, created_at: "2017-09-17 15:14:12", updated_at: "2017-09-17 16:48:53">, #<User id: 4, organization_id: 1, login: "dennis schuette839", firstname: "Dennis", lastname: "Schuette", email: "test4@test.com", image: nil, image_source: nil, web: "", password: nil, phone: "", fax: "", mobile: "", department: "", street: "", zip: "", city: "", country: "", address: "", vip: false, verified: false, active: true, note: "", last_login: nil, source: nil, login_failed: 0, out_of_office: false, out_of_office_start_at: nil, out_of_office_end_at: nil, out_of_office_replacement_id: nil, preferences: {}, updated_by_id: 1, created_by_id: 1, created_at: "2017-09-17 16:48:53", updated_at: "2017-09-17 16:48:53">]`

- <img width="1156" alt="screen shot 2017-09-17 at 11 20 18" src="https://user-images.githubusercontent.com/6449818/30525702-8bfdecb0-9c03-11e7-8b6d-067f67e87aee.png">

**Comment by thorsteneckel** [comment] 2017-10-17 12:24
Fixed with the help of @natseg ! See the commit above for applied changes.

**Closed by thorsteneckel** 2017-10-17 12:24 UTC
Labels: enhancement, UX/UI
