### ISSUE TITLE
Problems importing from OTRS into zammad 2.0.0

### ISSUE THREAD

**Issue by MrDigit** [zammad/zammad#1467] opened 2017-09-24 16:27 UTC
Hello all,

in earlier versions I already had some importing tickets from OTRS, but it worked more or less.

Unfortunately I can't get the import working with current zammad.
I have ~6000 tickets in OTRS, the import process always stop somewhere between 1400-1500 tickets.

Versions:
zammad 2.0.0
OTRS: 5.0.16
OS: CentOS 7

Logfiles don't tell much, please see attached. Perhaps I missed something, but I can't see any serious errors in the logs.

[messages.txt](https://github.com/zammad/zammad/files/1327456/messages.txt)
[production.log](https://github.com/zammad/zammad/files/1327457/production.log)

Any possibilites to track down the problem ?

**Comment by hanneshal** [comment] 2017-09-26 09:35
Hi @MrDigit 

is there anything inside the OTRS Log or the Apache Error Log on OTRS side?

regards
Johannes

**Comment by MrDigit** [comment] 2017-09-26 19:54
apache error log please see attached.

[messages.txt](https://github.com/zammad/zammad/files/1334773/messages.txt)

OTRS log nothing interesting..

**Comment by thorsteneckel** [comment] 2017-10-18 14:18
Sorry for the delay. Can you please retry the import? If the error message occurs again please open it in your OTRS Zoom view via the URL: `https://your.tld/otrs/index.pl?Action=AgentTicketZoom;TicketID=*TicketID*` (replace `*TicketID*` with your TicketID).

Would be great to get some general info about the ticket. Dies it exist? Is it new? Is it merged etc. A screenshot would be great if possible.

**Comment by thorsteneckel** [comment] 2018-01-09 10:40
Closed due to missing feedback.

**Comment by MrDigit** [comment] 2018-02-18 17:58
Hello,

sorry the the delay. I tried it again today with zammad 2,3,0, unfortunately unsuccessful again;

![grafik](https://user-images.githubusercontent.com/23297630/36355050-68f21612-14dd-11e8-9269-46f3f4ecf69f.png)

[production.log](https://github.com/zammad/zammad/files/1734951/production.log)

Could you please give me a hint where to search for the error ?

Best regards
  MrDigit

**Comment by thorsteneckel** [comment] 2018-02-18 18:02
Hi @MrDigit - We are currently working on a major refactoring of the OTRS import. It will be ready around Zammad 2.4 or 2.5 - not sure yet. I can't see any related errors in the log file so I would recommend waiting for the refactoring. I'll let you know.

**Comment by MrDigit** [comment] 2018-02-18 19:13
One addition: this message (nothing more) can be found after import stopped in http errorlog of OTRS:

[Sun Feb 18 20:18:08 2018] [error] Software caused connection abort at /opt/otrs//Kernel/Output/HTML/Layout.pm line 1642.\n

Thanks for the fast response, I'll wait for the update.

**Comment by thorsteneckel** [comment] 2018-02-18 19:44
Thanks for the hint! Could you please provide that file? Might be of interest.

**Comment by MrDigit** [comment] 2018-02-19 07:33
Sorry, there is only that line I've posted in my last comment.

**Comment by thorsteneckel** [comment] 2018-02-19 07:36
Oh - I meant the `/opt/otrs//Kernel/Output/HTML/Layout.pm` file :)

**Comment by MrDigit** [comment] 2018-02-19 07:39
ah :)

https://github.com/OTRS/otrs/blob/rel-5_0/Kernel/Output/HTML/Layout.pm

**Comment by MrGeneration** [comment] 2018-12-24 11:02
Closing, Duplicate of https://github.com/zammad/zammad/issues/2107

**Closed by MrGeneration** 2018-12-24 11:02 UTC
Labels: bug, duplicate, import, needs verification
