### ISSUE TITLE
No Fetch Mail + IMAP Import KO

### ISSUE THREAD

**Issue by Wisou** [zammad/zammad#2061] opened 2018-06-08 10:06 UTC
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): package 
* Operating system: Debian
* Database + version: PSQL 9.4
* Elasticsearch version: 6.6.1
* Browser + version: Chrome or Firefox

### Expected behavior:

* IMAP job completes fully with fetch mail

### Actual behavior:

* randomly no import mail in zammad

Hi,

Randomly, Zammad don't import mail. For example 06-07-18, we have a error at 12:08 in production.log and after that no import
I, [2018-06-07T12:07:58.249502 #23173]  INFO -- : fetching imap (mail.xxxx.fr/support-tw@xxxx.fr port=993,ssl=true,folder=INBOX,keep_on_server=false)
I, [2018-06-07T12:07:58.586239 #558]  INFO -- : Completed 200 OK in 1012ms (Views: 289.6ms | ActiveRecord: 58.7ms)
E, [2018-06-07T12:08:00.501380 #23173] ERROR -- : thread_client 47092814220500 exited with error #<ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.495 seconds); all pooled connections were in use>
E, [2018-06-07T12:08:00.501506 #23173] ERROR -- : /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
  /opt/zammad/vendor/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:747:in `acquire_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:88:in `connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/calculations.rb:169:in `pluck'
  /opt/zammad/app/models/ticket/overviews.rb:20:in `all'
  /opt/zammad/app/models/ticket/overviews.rb:76:in `index'
  /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:23:in `load'
  /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:66:in `push'
  /opt/zammad/lib/sessions/client.rb:59:in `each'
  /opt/zammad/lib/sessions/client.rb:59:in `block in fetch'
  /opt/zammad/lib/sessions/client.rb:24:in `loop'
  /opt/zammad/lib/sessions/client.rb:24:in `fetch'
  /opt/zammad/lib/sessions/client.rb:7:in `initialize'
  /opt/zammad/lib/sessions.rb:669:in `new'
  /opt/zammad/lib/sessions.rb:669:in `thread_client'
  /opt/zammad/lib/sessions.rb:624:in `block (3 levels) in jobs'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2018-06-07T12:08:01.965557 #558]  INFO -- : Started GET "/api/v1/online_notifications/?full=true&_=1528360883133" for 127.0.0.1 at 2018-06-07 12:08:01 +0200
I, [2018-06-07T12:08:01.970322 #558]  INFO -- : Processing by OnlineNotificationsController#index as JSON
I, [2018-06-07T12:08:01.970380 #558]  INFO -- :   Parameters: {"full"=>"true", "_"=>"1528360883133"}
I, [2018-06-07T12:08:01.980899 #558]  INFO -- : Started GET "/api/v1/online_notifications/?full=true&_=1528355556525" for 127.0.0.1 at 2018-06-07 12:08:01 +0200
I, [2018-06-07T12:08:01.989233 #558]  INFO -- : Processing by OnlineNotificationsController#index as JSON
I, [2018-06-07T12:08:01.989309 #558]  INFO -- :   Parameters: {"full"=>"true", "_"=>"1528355556525"}
I, [2018-06-07T12:08:02.248065 #558]  INFO -- : Completed 200 OK in 278ms (Views: 42.1ms | ActiveRecord: 25.8ms)
I, [2018-06-07T12:08:03.063563 #558]  INFO -- : Completed 200 OK in 1074ms (Views: 403.2ms | ActiveRecord: 93.0ms)
E, [2018-06-07T12:08:06.392967 #23173] ERROR -- : thread_client 47092832757760 exited with error #<ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.197 seconds); all pooled connections were in use>
E, [2018-06-07T12:08:06.396050 #23173] ERROR -- : thread_client 47092821086380 exited with error #<ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.384 seconds); all pooled connections were in use>
E, [2018-06-07T12:08:06.957926 #23173] ERROR -- : /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
  /opt/zammad/vendor/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:747:in `acquire_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:88:in `connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/calculations.rb:169:in `pluck'
  /opt/zammad/app/models/ticket/overviews.rb:20:in `all'
  /opt/zammad/app/models/ticket/overviews.rb:76:in `index'
  /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:23:in `load'
  /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:66:in `push'
  /opt/zammad/lib/sessions/client.rb:59:in `each'
  /opt/zammad/lib/sessions/client.rb:59:in `block in fetch'
  /opt/zammad/lib/sessions/client.rb:24:in `loop'
  /opt/zammad/lib/sessions/client.rb:24:in `fetch'
  /opt/zammad/lib/sessions/client.rb:7:in `initialize'
  /opt/zammad/lib/sessions.rb:669:in `new'
  /opt/zammad/lib/sessions.rb:669:in `thread_client'
  /opt/zammad/lib/sessions.rb:624:in `block (3 levels) in jobs'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2018-06-07T12:08:07.207009 #23173] ERROR -- : /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
  /opt/zammad/vendor/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:747:in `acquire_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:88:in `connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/calculations.rb:169:in `pluck'
  /opt/zammad/app/models/ticket/overviews.rb:20:in `all'
  /opt/zammad/app/models/ticket/overviews.rb:76:in `index'
  /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:23:in `load'
  /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:66:in `push'
  /opt/zammad/lib/sessions/client.rb:59:in `each'
  /opt/zammad/lib/sessions/client.rb:59:in `block in fetch'
  /opt/zammad/lib/sessions/client.rb:24:in `loop'
  /opt/zammad/lib/sessions/client.rb:24:in `fetch'
  /opt/zammad/lib/sessions/client.rb:7:in `initialize'
  /opt/zammad/lib/sessions.rb:669:in `new'
  /opt/zammad/lib/sessions.rb:669:in `thread_client'
  /opt/zammad/lib/sessions.rb:624:in `block (3 levels) in jobs'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2018-06-07T12:08:09.338919 #23173] ERROR -- : thread_client 47092838753140 exited with error #<ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.284 seconds); all pooled connections were in use>
I, [2018-06-07T12:08:09.968273 #23173]  INFO -- :  - no message
E, [2018-06-07T12:08:11.257747 #23173] ERROR -- : /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
  /opt/zammad/vendor/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:747:in `acquire_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:88:in `connection'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/calculations.rb:169:in `pluck'
  /opt/zammad/app/models/ticket/overviews.rb:20:in `all'
  /opt/zammad/app/models/ticket/overviews.rb:76:in `index'
  /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:23:in `load'
  /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:66:in `push'
  /opt/zammad/lib/sessions/client.rb:59:in `each'
  /opt/zammad/lib/sessions/client.rb:59:in `block in fetch'
  /opt/zammad/lib/sessions/client.rb:24:in `loop'
  /opt/zammad/lib/sessions/client.rb:24:in `fetch'
  /opt/zammad/lib/sessions/client.rb:7:in `initialize'
  /opt/zammad/lib/sessions.rb:669:in `new'
  /opt/zammad/lib/sessions.rb:669:in `thread_client'
  /opt/zammad/lib/sessions.rb:624:in `block (3 levels) in jobs'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

**Comment by thorsteneckel** [comment] 2018-06-08 11:06
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

The error indicates that no DB connection could be established in the 5 seconds. This could be caused by your DB limiting connections. Feel free to start at thread over at our [community board](http://community.zammad.org/) and share your results.

**Closed as completed by thorsteneckel** 2018-06-08 11:06 UTC
Labels: question
