### ISSUE TITLE
Invalid default value for boolean value while altering the user object

### ISSUE THREAD

**Issue by stern105** [zammad/zammad#847] opened 2017-03-16 08:55 UTC
Adding a boolean field to an object results in a missing default value. The database can not be altered. Please see the screenshots attached at the bottom (_Steps to reproduce the behavior_) for an easy understanding of the issue.

### Error message:

* StatusCode: 500
* {"error":"Invalid default value for '<field name>'"}

### Steps to reproduce the behavior:

* Add a boolean field to a user object.
* Set any default value (e.g. default "false")
* Store and update data base.

![zammad-fehler_01](https://cloud.githubusercontent.com/assets/7080419/23988314/fb8869c4-0a2d-11e7-84ae-0b94a105861b.jpg)
![zammad-fehler_02](https://cloud.githubusercontent.com/assets/7080419/23988313/fb87ddce-0a2d-11e7-8a0a-5991f736b799.jpg)

### Infos:

* Used Zammad version: 1.3
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Any Browser (FireFox 52 / x64)

**Comment by martini** [comment] 2017-03-16 09:01
Thanks for bug report. May I ask wich database + version do you use?

**Comment by stern105** [comment] 2017-03-16 09:08
Hi martini, thanky for the quick reply!
I installed version 1.3.0 from https://docs.zammad.org/en/latest/install-ubuntu.html two days ago on a fresh Ubuntu LTS server. Since I am a PHP guy I am not sure how to get this information for you. I guess it is mysql? In that case the version would be 5.7.17-0ubuntu0.16.04.1

**Comment by DaniloE** [comment] 2017-12-06 11:59
Any news for this issue? We need this, to add an "escalated" attribute to a ticket. This doesn't only affect users. It seems to be broken in every boolean custom field.

**Comment by thorsteneckel** [comment] 2017-12-06 12:04
There is a pending pull request - https://github.com/zammad/zammad/pull/1656. We will address this issue in Zammad 2.4

**Comment by thorsteneckel** [comment] 2018-01-25 17:29
Hi @muhammadn - This is related to the pull request. Please have a look. Thanks!

**Comment by muhammadn** [comment] 2018-03-01 11:35
Duplicate of #1617 which is fixed in develop branch.

**Closed** 2018-03-12 09:34 UTC
Labels: admin area, bug, duplicate
