### ISSUE TITLE
2.9.x login issue after upgrade

### ISSUE THREAD

**Issue by potlaki** [zammad/zammad#2523] opened 2019-03-27 10:14 UTC
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): apt
* Operating system: Ubuntu 16.04 LTS
* Database + version: Postgresql 10
* Elasticsearch version: 6.6.1
* Browser + version: Firefox Quantum 66

### Expected behavior:

* Login as normal

### Actual behavior:

* When clicking on password, cursor jumps back to username and clears username field

### Steps to reproduce the behavior:

* Restarted zammad server and restarted the ubuntu server. Problem persists. We've cleared cache and cookies and tried Chrome browser. Multiple users in different locations experiencing the same problem.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by potlaki** [comment] 2019-03-27 10:19
Please note this is after an upgrade from 2.8.x to 2.9.x

**Comment by MrGeneration** [comment] 2019-03-27 11:37
Sorry, but I can't reproduce this.
Please provide a screencast and ensure you're not using any add-ons that might cause this issue.

In my tests it didn't matter if I tab into the password field or use the mouse. It just works.

**Comment by martini** [comment] 2019-03-27 11:43
Just  a side note:

1) check your `/opt/zammad/log/production.log`
2) Make sure that your database migrations are done by executing `zammad run rake db:migrate`

Everything else as @MrGeneration wrote.

**Comment by potlaki** [comment] 2019-03-27 12:15
hi guys,

Thank you for getting back to me. I've attachde a screen cast of the problem.

I've tailed my production log(/var/log/production.log) and every +-2 seconds I'm getting this:

Checking left over delayed job #<Delayed::Backend::ActiveRecord::Job id: 305520, priority: 0, attempts: 14, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "Unable to process POST request to elasticsearch UR...", run_at: "2019-03-26 15:08:00", locked_at: "2019-03-26 15:08:02", failed_at: nil, locked_by: "host:hostname pid:112452", queue: nil, created_at: "2019-03-25 03:37:57", updated_at: "2019-03-26 04:27:39"> started.



[zammad issue.zip](https://github.com/zammad/zammad/files/3013041/zammad.issue.zip)

**Comment by MrGeneration** [comment] 2019-03-27 13:05
The log entries are from a wrong configured elasticsearch (or even not running). This is out of scope of Github (sorry).

I still can't verify this issue, even when trying to use the auto complete function of Firefox.
Please disable all Add-Ons being used and ensure your Zammad does not have any changed code (no matter if CSS, javascript or application).

If the problem still persists, please register a hosted trial and try the same there again:
https://zammad.com/getting-started

(This will ensure that the problem lays not on your end)

Thanks before hand!

**Comment by potlaki** [comment] 2019-03-27 14:25
I've tried on Google Chrome, Firefox and Chromium and the problem persists. I have disabled all my add-ons. 

Other users experiencing the same problem are also using a variety of browsers and are less technical people. They do not have any add-ons on loaded to their browsers.

I'm going to try on the hosted trial, although I don't think it will help.

**Comment by potlaki** [comment] 2019-03-27 14:52
Hi guys,

The other thing is apt remove elasticsearch also removes zammad. I've tried this in our dev environment and completely lost zammad.

**Comment by MrGeneration** [comment] 2019-03-28 07:29
Please do not mix up Github-Issues. This is rather a technical question for our community, sorry.

**Comment by MrGeneration** [comment] 2019-06-11 08:10
Closing because of missing feedback (correct log entries).
We can't reproduce this at all. (sorry).

**Closed as completed** 2019-06-11 08:09 UTC
Labels: can't reproduce
