### ISSUE TITLE
Drop zone macro can create duplicate tags due to race condition

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2636] opened 2019-06-28 17:56 UTC
### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 9
* Database + version: postgres from zammad-docker-compose
* Elasticsearch version: ES from zammad-docker-compose
* Browser + version: Chrome 75

### Expected behavior:

* Selecting multiple tickets in an overview, and then dragging and dropping them onto a macro that tags the tickets with a tag that hasn't been created yet should create only a single instance of this tag, and then tag the tickets with this tag.

### Actual behavior:

* The macro may create multiple instances of the tag instead of a single one. Different tickets will be linked to different instances.

### Steps to reproduce the behavior:

* Create macro that tags tickets, ie:

	Tags: add: `test`
	
* Ensure that this tag does not exist yet.

* Select multiple tickets in an overview, and drop them onto this macro.

* Note that the tag list in the admin area will now contain the same tag multiple times.

	For example, I selected three tickets and tagged them with `test`:
		
	![image](https://user-images.githubusercontent.com/6863569/60360670-88e3dc00-99dc-11e9-8913-c497948dfc3b.png)

	The database shows that the tags were created in millisecond intervals:
	
	```
	zammad_production=# select * from tag_items where name = 'test';
	 id | name | name_downcase |       created_at        |       updated_at
	----+------+---------------+-------------------------+-------------------------
	 24 | test | test          | 2019-06-28 17:32:51.182 | 2019-06-28 17:32:51.182
	 25 | test | test          | 2019-06-28 17:32:51.19  | 2019-06-28 17:32:51.19
	 26 | test | test          | 2019-06-28 17:32:51.194 | 2019-06-28 17:32:51.194
	(3 Zeilen)
	```
### Background info

This looks like a classic race condition - the code probably does "does this macro exist yet? no? then create it", but this multiple times at the same time. The three requests were processed by three separate threads who all came to the conclusion that the tag didn't exist yet, and then each thread created its own instance of the tag.

I encountered it first in our production instance that runs with `WEB_CONCURRENCY=4`, and I was able to reproduce it in our testing instance both with `WEB_CONCURRENCY=2` and `WEB_CONCURRENCY` unset. While unset, Zammad created only two tags instead of three, but I believe this is probably random.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment] 2023-06-02 13:02
Hi @martinvonwittich,

I was using a current Zammad version and cannot reproduce the reported behavior anymore. Therefore I am going to close this issue. Feel free to re-open it with some new information.

Thanks for your understanding 😎

**Closed as completed by fliebe92** 2023-06-02 13:02 UTC
Labels: bug, verified, macros
