### ISSUE TITLE
Agent - Group assignment shows "<br>"

### ISSUE THREAD

**Issue by patrick-fox** [zammad/zammad#566] opened 2016-12-21 00:07 UTC
hi!

### Infos:

* Used Zammad version: 1.1.1-1481899824.264ddc0.xenial
* Operating system: Ubuntu 16.04.1 LTS
* Browser + version: Firefox 50.1.0

### Expected behavior:

* No "\<br\>" after a notice for a group

### Actual behavior:

* If a notice is active for a group it shows a \<br\> in the agent overview (/#manage/users)

### Steps to reproduce the behavior:

* Add a notice / comment to a group. There is no new line after the comment in the group.

BR,
Patrick

![agent_br](https://cloud.githubusercontent.com/assets/24594979/21372785/bc71d588-c719-11e6-9df7-dc0cdd46793e.PNG)

**Comment by monotek** [comment] 2016-12-21 12:16
Can't reproduce in 1.2 develop.
Closing.

**Comment by martini** [comment] 2016-12-21 13:08
I was able to reproduce it. Just add a note to a group.

<img width="649" alt="screen shot 2016-12-21 at 14 07 16" src="https://cloud.githubusercontent.com/assets/110226/21390367/de9ed3dc-c786-11e6-9123-ec27ff36d1ec.png">

**Comment by martini** [comment] 2016-12-21 13:13
Fixed in 1.0, 1.1 and develop.

**Closed by martini** 2016-12-21 13:13 UTC
Labels: bug

**Comment by monotek** [comment] 2016-12-21 13:42
Strange. Standard group already had a note.
