### ISSUE TITLE
The calendar shows Chilean holidays one day in advance

### ISSUE THREAD

**Issue by hmolinab** [zammad/zammad#3706] opened 2021-08-20 20:15 UTC
Hi Zammad team,

### Infos:

* Used Zammad version: zammad-4.1.0-1627506169.2b97d5a1.centos7.x86_64 
* Installation method (source, package, ..): rpm
* Operating system: Centos 7
* Database + version: PostgreSQL 10.17
* Elasticsearch version:  7.12
* Browser + version: Chrome, Firefox

### Expected behavior:

* The calendar must shows the holidays the right day

### Actual behavior:

* The calendar shows Chilean holidays one day in advance
![imagen](https://user-images.githubusercontent.com/85374371/130288515-7902a5a4-f2f4-46c6-9e80-344dda068840.png)

The right dates are:
| Date | Holiday |
|----|------|
| 09/17/2021 | Day off for National Day |
| 09/18/2021 | National Day |
| 09/19/2021 | Army Day |

### Steps to reproduce the behavior:

*Using the following calendar the behavior is the same:
https://calendar.google.com/calendar/ical/es.cl%23holiday%40group.v.calendar.google.com/public/basic.ics

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment] 2021-08-20 20:22
Hi @hmolinab ,

What is your Zammad time zone? As selected in Settings > Branding > Timezone.

**Comment by hmolinab** [comment] 2021-08-20 20:31
Hi Mantas,

It's the same as the calendar.
[image: imagen.png]

**Comment by mantas** [comment] 2021-08-20 20:47
Hmm, I couldn't reproduce it on my system. Are you able to reproduce this issue with a fresh install?

**Comment by MrGeneration** [comment] 2021-08-20 20:53
Works on my test instance as well. 
Same applies to the manual provided URL.

Closing.

**Comment by hmolinab** [comment] 2021-08-20 21:19
It's strange, I have 3 instance with the same behaviour.

the OS configuration:
![imagen](https://user-images.githubusercontent.com/85374371/130292891-cf470ad1-9349-4722-86ad-a5d60748864e.png)

The DB configuration:
![imagen](https://user-images.githubusercontent.com/85374371/130292943-12717092-d8e0-47fc-ad19-1ae47071ed61.png)

I've just updated the lab instance and I got the same result, I'm sorry you couldn't reproduce the problem.

**Comment by MrGeneration** [comment] 2021-08-20 21:20
Can you reproduce it in SaaS as well?

https://zammad.com/en/getting-started

**Comment by hmolinab** [comment] 2021-08-21 01:11
oh, yes, the same issue:
[image: imagen.png]
One day in advance. I've used many browsers and many desktops.

**Comment by mantas** [comment] 2021-08-21 06:25
Hmmm!

Could you confirm your steps to reproduce this on our SaaS?

- setup using Santiago as time zone
- add Chilean calendar with Santiago timezone

Anything else?

**Comment by MrGeneration** [comment] 2021-08-21 14:04
So the calendar of said SaaS instance holds these calendar information

**public_holidays**
```
{
   "2020-09-18"=>{"active"=>true, "summary"=>"National Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2020-09-19"=>{"active"=>true, "summary"=>"Army Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2020-10-12"=>{"active"=>true, "summary"=>"Columbus Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2020-10-31"=>{"active"=>true, "summary"=>"Reformation Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2020-11-01"=>{"active"=>true, "summary"=>"All Saints' Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2020-12-08"=>{"active"=>true, "summary"=>"Inmaculate Conception Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2020-12-25"=>{"active"=>true, "summary"=>"Christmas Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2021-01-01"=>{"active"=>true, "summary"=>"New Year's Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2021-04-01"=>{"active"=>true, "summary"=>"Maundy Thursday", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2021-04-02"=>{"active"=>true, "summary"=>"Good Friday", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2021-04-03"=>{"active"=>true, "summary"=>"Holy Saturday", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2021-04-04"=>{"active"=>true, "summary"=>"Easter Sunday", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2021-04-11"=>{"active"=>true, "summary"=>"Mayors and Regional Governors Elections", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   "2021-05-01"=>{"active"=>true, "summary"=>"Labor Day / May Day", "feed"=>"160a7eaff2083a81be93252922817ec6"},
   [...]
}
```

**ical_url**: `http://www.google.com/calendar/ical/en.cl%23holiday%40group.v.calendar.google.com/public/basic.ics`
**timezone**: `America/Santiago`
**Instance timezone**: `America/Santiago`
**ICS directly loaded from google**: [issue3706_ics.zip](https://github.com/zammad/zammad/files/7025596/issue3706_ics.zip)

That then confused me so I checked manually simulating an import:
![image](https://user-images.githubusercontent.com/6549061/130323913-bed49f05-5973-4381-8890-a31d7e1c6267.png)


My calendar reports actually two days "full day".
This also confirms in the ics file:
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20210917
DTEND;VALUE=DATE:20210918
DTSTAMP:20210821T134038Z
UID:20210917_kmotr7dj34itsb0n9ilgcuvcdk@google.com
CLASS:PUBLIC
CREATED:20210703T072834Z
DESCRIPTION:
LAST-MODIFIED:20210703T072834Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Day off for National Day
TRANSP:TRANSPARENT
END:VEVENT
```

When I revisited this topic in my own instance and re-checked with OPs initial screenshots that I also have 3 day offs in close day range - interestingly my calendar shows them as +1 day:
![image](https://user-images.githubusercontent.com/6549061/130323976-51af04f2-5d72-4c49-aaf9-b0ee06839bbc.png)

To that moment by browsers timezone was `Europe/Berlin`.
I then spoofed my browsers timezone to `America/Santiago` and guess what...
![image](https://user-images.githubusercontent.com/6549061/130324184-68d956c0-5a6c-4338-8438-3b6d6023d52f.png)


The UI translates (as on many places) date times to local time zones. In this case however this goes wrong because it's neither a UTC date nor should a calendar switch to local timezones (the day doesn't change and so shouldn't the display).

Currently checking for duplicates as this does ring a bell.

**Comment by MrGeneration** [comment] 2021-08-21 14:06
Regression of https://github.com/zammad/zammad/issues/2229

**Closed as completed** 2021-08-23 14:52 UTC
Labels: bug, UX/UI, verified, regression

**Comment by hmolinab** [comment] 2021-08-23 15:14
Oh, your are a very efficient team, good for you! Thanks!

¿How can I test the change?

**Comment by MrGeneration** [comment] 2021-08-23 15:22
Be patient and wait for the stable backport. After it has been backported wait 60-120 mins and you're good to go.

**Comment by mantas** [comment] 2021-08-23 19:59
Hi @hmolinab

This bugfix is now ported to stable. The updated package should be available in an hour or two.

**Comment by hmolinab** [comment] 2021-08-23 22:30
Hi Team,

Congratulations, it's ready!
[image: imagen.png]

Thanks!

Henry
