### ISSUE TITLE
dashboard: click on my tickets should open list of those tickets

### ISSUE THREAD

**Issue by ralfhauser** [zammad/zammad#2936] opened 2020-02-17 03:30 UTC
![image](https://user-images.githubusercontent.com/1681677/74621707-2f344b80-513e-11ea-8a86-62af4d51cfa1.png)

I would be great to be able to click on the yellow / in the red circle and get the list my tickets

**Comment by MrGeneration** [comment] 2020-02-17 07:37
Sorry but this is a feature requests.
Please do not post feature requests on this Github repository - the Zammad community is the better place for this: https://community.zammad.org .

Thank you for your time. Closing.

**Closed as completed by MrGeneration** 2020-02-17 07:37 UTC
Labels: duplicate

**Comment by thorsteneckel** [comment] 2020-02-17 07:39
Additionally this is a duplicate of #431
