### ISSUE TITLE
timezone issue with elasticsearch

### ISSUE THREAD

**Issue by chesty** [zammad/zammad#2085] opened 2018-06-17 04:54 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): zammad-docker-compose
* Ticket-ID: #1049736

### Expected behavior:

* zammad handles servers running in a different timezone to users, ie servers on UTC, timezone +10

### Actual behavior:

* lots of issues with elasticsearch, reports, pending reminders, any function that uses a time.

### Steps to reproduce the behavior:

* install an new zammad on a server in UTC, set your desktop to +10, set up imap to fetch emails, preferable emails sent in +10 timezone, look at reports, set pending reminder, search for tickets.

I'm not 100% sure this is a bug. I have 5% of the knowledge of zammad developers, so be skeptical about this report. I might be wrong. My thinking is here:

https://community.zammad.org/t/elasticsearch-is-only-being-used-for-user-and-organisation-queries-not-ticket-queries/821/15?u=chesty

> Oh noes, I think it’s a timezone issue. I think zammad assumes server and browser are running in the same timezone? can that be? The timestamp field for created_at and updated_at, etc, are timestamp (as apposed to timestamptz) and the times in them are (for me) UTC with no timezone info, where desktops and browsers are running in +10. I guess email timestamps would be +10 too with timezone info. so 2018-06-17 10:00:00 +10, but the time that gets stored in postgres would just be 2018-06-17 10:00:00 (no +10), and the created_at would be 2018-06-17 00:00:00
> 
> I think elasticsearch is timestamptz (the equivalent to) so when zammad is searching elasticsearch for a ticket within a narrow time period, the times are 10 hours out and the ticket isn’t found.
> 

another project I use is odoo, it converts all times into UTC before putting them in DB, and the view is responsible for displaying the time in the right timezone, it has access to the browsers timezone setting I guess.

**Comment by thorsteneckel** [comment] 2018-06-17 12:34
Hi @mantas - is this the same issue you are currently working on?

**Comment by mantas** [comment] 2018-06-17 16:53
@thorsteneckel yep! Even if it's technically not the same issue, it does fall in the same scope nicely.

Assigned this one to myself to keep track of it.

**Comment by chesty** [comment] 2018-06-18 02:09
Thank guys.

A few updates for your info which might help with testing the solution.

I set the servers timezone to +10, it looks like dates in created_at, etc, are still utc, which is good. It didn't fix the elasticsearch, it's still not finding tickets in elasticsearch and then using postgres. (I think that's what's happening)

I'm mainly updating this issue to mention if we add a reminder on a date before 10am, the date gets decremented. If we add a reminder on a date after 10am it doesn't.

**Comment by mantas** [comment] 2018-06-19 09:44
@chesty thank you for additional info. I can confirm there's an issue with ElasticSearch.

Regarding pending reminder, this issue is already addressed in #1693 . Fix is coming soon.

**Comment by chesty** [comment] 2018-06-19 11:45
Cheers mantas, would that be the same issue that affects the graph on reports?
I'm guessing not, but the graph problem also appears to be timezone related.

when my server was running on utc, the line on the graph was 9 or 10 hours out (9 doesn't make sense, 10 does but it looked to be 9 hours out), now the server is running on +10 there are no lines on the graph. There are tickets in the box below the empty graph.

Will I open a new ticket for the graph issue?

**Comment by mantas** [comment] 2018-06-19 12:30
@chesty ElasticSearch seems to be an isolated issue. Graph seems to be another issue. It'd be great if you could open a new ticket for it. Either way, I'm aware of it.

**Comment by KoJie** [comment] 2019-07-17 11:59
the behavior was also reported by a customer: T#1049736

**Comment by MrGeneration** [comment] 2019-07-17 11:59
This issue gets even worse, because since 3.0 we're calculating the timezone inside of reporting exports.
This will cause Zammad to deliver wrong exports.

In my case (GMT+2) Zammad insists that the ticket has been created 4 hours before that (so GMT-2) while the UTC times are perfectly fine.

Issue that introduced this change: https://github.com/zammad/zammad/issues/2594

**Comment by mantas** [comment] 2019-07-17 12:06
@MrGeneration I got this on my todo list and working on it to get away from KB once in a while. No ETA yet though. Let me know if I should prioritise it.

**Comment by martini** [comment] 2019-07-17 12:42
> This issue gets even worse, because since 3.0 we're calculating the timezone inside of reporting exports.
This will cause Zammad to deliver wrong exports.
>
> In my case (GMT+2) Zammad insists that the ticket has been created 4 hours before that (so GMT-2) while the UTC times are perfectly fine.
>
> Issue that introduced this change: #2594

JFI: The issue in #2594 was that excel is not supporting timezones. So for this we introduces to convert timestamps to agent localised timestamped in excel export. A not what timezone is used in export it as note in the excel sheet.

So please take care of that.

**Comment by martini** [comment] 2019-07-17 12:46
In general it would be nice to have a step by step description how the issue can e reproduced. 

Note: Zammad stores all timestamps as GMT and is converting it to local user time zone or to the app time zone. Even for the ticket selector all times are local user times but stored are GMT times always.

So can point me somebody how to reproduce the issue to make it clear? Thanks!

**Comment by KoJie** [comment] 2019-07-17 13:42
I'll try, hopefully it will help:

**Steps to reproduce the behavior (hosted instance):**

- I took a created ticket, created at 07/08/2019 14:31 (Timezone GMT+2)
![image](https://user-images.githubusercontent.com/22768032/61380291-62adaf80-a8a9-11e9-9d4a-5e03bc976072.png)


- I created a report of all tickets and got this in the Reporting-mask:
![image](https://user-images.githubusercontent.com/22768032/61379951-c97e9900-a8a8-11e9-9ce7-de0b55b22892.png)


- but in the exported Excel ticket list, the timestamp is as follows: 
![image](https://user-images.githubusercontent.com/22768032/61380060-fdf25500-a8a8-11e9-8d2b-92c1610c58d1.png)

**Comment by MrGeneration** [comment] 2020-04-28 13:39
Martin and I are sure, that this issue has beeen addressed by the following issues:

### Timezone issues within reporting

Issue https://github.com/zammad/zammad/issues/2594 addresses this, because from what I understand this issue is about e.g. pending reminders suddendly appearing to be one day earlier (because we exported information in UTC earlier). If you'd then search for this ticket based on that information, you'll get wrong results if you're unlucky. 

### Pending reminder issues itself
Because this issue is fairly old, it might be also relevant to this issue and thus be adressed: https://github.com/zammad/zammad/issues/1693


## Conclusion 

This is the reason why we're marking this as a duplicate of 2594 and 1693.
If we're wrong, please create a new issue and describe the scope and issue detailed. If it's about two things, please create several issues stating the link in between them. This helps us to understand those kinds of issues and hopefully safes time to understand scopes in the future.

Closing now. :)

**Closed as completed by MrGeneration** 2020-04-28 13:39 UTC
Labels: duplicate
