### ISSUE TITLE
backup script: tar - file changed warnings

### ISSUE THREAD

**Issue by lr1980** [zammad/zammad#2021] opened 2018-05-16 19:50 UTC
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: latest
* Browser + version: any

### Expected behavior:

* backup script that can used without errors or warnings (=no mails/logs from cron)

### Actual behavior:

* backup script can produce following warnings:
`tar: opt/zammad/tmp/cache_file_store_production: file changed as we read it`

It's safe to exclude the "tmp" directory?

**Comment by thegcat** [comment] 2019-06-28 08:24
We're having a similar issue (we're using borgbackup for backups, but the issue is the same). My experience with Rails apps is that `RAILS_ROOT/tmp` is safe to ignore, but I'd like a confirmation for this too.

If this is confirmed I'd be willing to contribute a patch accordingly.

**Comment by thegcat** [comment] 2019-06-28 11:20
Judging from https://github.com/zammad/zammad/blob/develop/lib/tasks/zammad/flush/cache.rake I'd say those directories (`tmp/cache*`) can be ignored when creating backups.

**Comment by monotek** [comment] 2019-06-28 12:51
Ups. Totally missed that ticket... PR is very welcome :-)

**Comment by MrGeneration** [comment] 2019-06-28 13:39
Yes, ignoring `tmp/` is safe to do. :-)

**Comment by thegcat** [comment] 2019-06-30 16:53
See PR in #2638

**Comment by thorsteneckel** [comment] 2019-07-01 06:56
Cool! Thanks @thegcat. @monotek can you please review the PR when you find the time? I'll do the GitLab -> GitHub dance then.

**Comment by thegcat** [comment] 2019-07-01 15:19
This probably can be considered fixed by #2638 and closed.

**Comment by thorsteneckel** [comment] 2019-07-01 15:27
Yes! Thanks a lot @thegcat for your contribution.

**Closed by thorsteneckel** 2019-07-01 15:27 UTC
Labels: enhancement
