### ISSUE TITLE
Ctrl+Backspace breaks text module selector

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#3021] opened 2020-04-16 15:36 UTC
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 10.3
* Database + version: postgresql 9.6.17 (from docker-compose)
* Elasticsearch version: 7.6.1 (from docker-compose)
* Browser + version: Chromium 80

### Expected behavior:

* When you type `::foo` to open the text module selector, and then hit Ctrl+Backspace to change `::foo` to `::`, the text module selector should continue to work normally.

### Actual behavior:

* The text module selector behaves very erratically after Ctrl+Backspace.

A short demonstration - using only backspace to delete text works fine and won't break the completion:

![1](https://user-images.githubusercontent.com/6863569/79475889-94a29c80-8008-11ea-800a-5c87ed1b99b9.gif)

But as soon as I press Ctrl+Backspace to delete the whole word at once, the completion behaves very erratically:

![2](https://user-images.githubusercontent.com/6863569/79475943-a8e69980-8008-11ea-92d8-74f83debb83e.gif)

### Steps to reproduce the behavior:

* Type `::foo`, hit Ctrl+Backspace to delete the `foo`, and attempt to use the completion.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-04-16 15:46
Hey,

is it possible that this is a duplicate of https://github.com/zammad/zammad/issues/2886 ?

**Comment by martinvonwittich** [comment] 2020-04-16 16:25
> is it possible that this is a duplicate of #2886 ?

Hmm, yes, that could be possible. On my first look at #2886 it seemed to describe a different problem (user wants to leave text module mode, but Zammad silently doesn't, causing data loss on the next return). But the fact that this:

- Type `::foo`
- Hit Ctrl+Backspace
- Type `bar`
- Hit Return

also removes the text `bar`, just like in #2886, seems to indicate that both issues probably have the same root cause.

**Comment by MrGeneration** [comment] 2020-07-30 09:44
Thanks for your feedback.
I'll close this as duplicate in favor of #2886 then.

Your issue should be covered by it, as on mantas comment: https://github.com/zammad/zammad/issues/2886#issuecomment-573119727

At least that's what I believe. :-)

**Closed as completed by MrGeneration** 2020-07-30 09:44 UTC
Labels: duplicate
