### ISSUE TITLE
New account Admin Fields available

### ISSUE THREAD

**Issue by gmartires** [zammad/zammad#1508] opened 2017-10-04 21:41 UTC
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...) DEB
* Operating system: Ubuntu 16.04
* Browser + version:  Edge

### Expected behavior:

* The new user should be in the ticket system or wait until the email is verified

### Actual behavior:

* The new user lands on costumer Dashboard but Admin fields available as if it was the admin fileds to create a new ticket. If I logged out and back in it show the correct fields

### Steps to reproduce the behavior:

* If I logged out and back in it show the correct fields but then the verification address dialog shows which is not working neither..Could anybody point me in the right direction? please!!!!!

**Comment by hanneshal** [comment] 2017-10-06 10:20
Hi @gmartires 
I'm sorry but it's not clear what the problem actually is.

> The new user should be in the ticket system or wait until the email is verified
What do you mean by that. What do you want to achieve?

regards 
Johannes

**Comment by gmartires** [comment] 2017-10-06 20:54
I guess I just didn't know what the normal behavior is.. What is supposed to happen when a new costumer created an account? 
Does the email is sent and the page freeze until you verify the email?
Does the user get to the dashboard and start creating tickets and then verified?

I had this situation where the new user was asked to add an account on the first ticket although the email is link to a organization - Domain in zammad.

**Comment by thorsteneckel** [comment] 2018-04-27 08:43
This is a duplicate of #1952 which is already fixed.

**Closed by thorsteneckel** 2018-04-27 08:43 UTC
Labels: question, waiting for feedback
