### ISSUE TITLE
agent with agent role and admin.user (managment user) can change the account group to admin

### ISSUE THREAD

**Issue by MBekspert** [zammad/zammad#1610] opened 2017-11-03 14:42 UTC
### Infos:

* Used Zammad version: 2.1.0-15095477
* Used Zammad installation source: package
* Operating system: Debian 9.2 (4.9.0-4-amd64)
* Browser + version: Firefox 56.0.1

### Expected behavior:

* agent with agent role and added admin.user (managment user) can change the account group to another user but only set agent or customer

### Actual behavior:

* An agent can set up an admin role, logon himself and become a system administrator

### Steps to reproduce the behavior:

* add to the role of agent the right to 'admin.user'

![obraz](https://user-images.githubusercontent.com/33098856/32379266-52b8ee22-c0ad-11e7-826d-f3fb78feff0a.png)

**Comment by thorsteneckel** [comment] 2018-03-27 10:10
As discussed with @martini - this works as intended. Users with `admin.user` permissions have the permission to change their own permissions to full `admin` or any other permission since it's part of the user administration. Closing now.

**Closed by thorsteneckel** 2018-03-27 10:10 UTC
Labels: wontfix
