### ISSUE TITLE
Telegram messages does not reach Zammad

### ISSUE THREAD

**Issue by louisyssel** [zammad/zammad#3369] opened 2021-01-15 11:47 UTC
### Infos:

* Used Zammad version: 3.6.0-1610377695.3480f859.centos7
* Installation method (source, package, ..): https://docs.zammad.org/en/latest/install/centos.html
* Operating system: Centos 7
* Database + version: postgres (PostgreSQL) 9.2.24
* Elasticsearch version: 5.6.16
* Browser + version: Any braowser

### Expected behavior: When the Telegram integration is installed and configured as per the Zammad documentation, when a message is sent from Telegram, there should be a notification and new ticket in Zammad.

*

### Actual behavior:

* Telegram Bot integration was done as per the Zammad documentation, the integration in Zammad gives no errors, and the Telegram client app gives no errors, but the messages are not coming up in Zammad.COmpletely unable to get any Telegram messages into Zammad.

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question. Yes

[production.log](https://github.com/zammad/zammad/files/5820266/production.log)

**Comment by MrGeneration** [comment] 2021-01-15 12:20
Duplicate of #2998

**Closed as completed by MrGeneration** 2021-01-15 12:20 UTC
Labels: duplicate

**Comment by louisyssel** [comment] 2021-01-15 12:24
Thank you, managed to resolve this. Thanks for the assistance.
