### ISSUE TITLE
LDAP authentication doen't work in 2.3.x

### ISSUE THREAD

**Issue by moellert** [zammad/zammad#1795] opened 2018-02-01 10:26 UTC
### Infos:

* Used Zammad version: 2.3.0-1517421506.32f17a3f.centos7
* Installation method (source, package, ..): package
* Operating system: CentOS7
* Database + version:  Postgres 9.2.23-3.el7_4
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* After an update from 2.2.x to 2.3.0-1517421506.32f17a3f it is still possible to login via LDAP authentication.

### Actual behavior:

* The LDAP authentication doesn't work anymore.

I had a Zammad 2.2.x installation with an LDAP sync and the authentication with my credentials worked fine.
Then I updated Zammad and now it says that my credentials are wrong. 
The log says the following:

![log](https://user-images.githubusercontent.com/30858921/35673483-fdf85a90-0741-11e8-8eac-e522c72d01e9.png)

In the LDAP configuration I saw that the LDAP attribute to Zammad attribute mapping for the "login" attribute changed from "uid" to "samaccountname" and now there are the email addresses instead of the usernames as login. 
Maybe this is the problem, but I can't verify this while there is no possibility to change this mapping(which would be nice)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Jean-Daniel** [comment] 2018-02-01 11:11
I also have this issue. This is because the ldap_config['user_attributes] now contains a mapping from 'samaccountname' to 'login' (and another one from 'uid' to 'login').

I managed to workaround that issue by updating the config (from the rails cli) to remove the erroneous mapping.

```
rails c
cfg = Setting.get('ldap_config')
cfg['user_attributes'] = {"uid"=>"login", "givenname"=>"firstname", "sn"=>"lastname", "mail"=>"email"}
Setting.set('ldap_config', cfg)
```

**Comment by moellert** [comment] 2018-02-01 14:20
Thanks @Jean-Daniel, this worked for me too.

But in system parts which are as important as the LDAP integration, you should not be dependent on workarounds and things should work as intended

**Comment by Jean-Daniel** [comment] 2018-02-01 16:39
I agree this is still a very bad bug. I think it is related to #1709

**Comment by thorsteneckel** [comment] 2018-02-01 20:18
Hi @moellert and @Jean-Daniel - can you please describe your migration path from Zammad 2.2 to 2.3. What were the steps that you've done? Have you changed your LDAP configuration afterwards?

It seems that your new config is wrong: `"samaccountname"=>"login"` is correct, `"uid"=>"login"` is wrong. The change to the wrong attribute causes wrong login attributes (`uid`-numbers instead of the known `samaccountname` value).

This is a issue related to #1709. We added more attributes to the list of uid-identifier attributes since `samaccountname` values can and have been not unique. So when updating to Zammad 2.3 a (async) process spawns and check if the `user_uid` attribute can/has to change. The `login` attribute was the same as the `user_uid` attribute in Zammad <= 2.2. We decided to use the `samaccountname` attribute as the new (hardcoded) default login attribute to avoid confusion and bad user experience when entering a cryptic long uid as a login.
However, there seems to be an issue in this migration path. Can you provide a mapping before your update to Zammad 2.3 so I can try to reproduce and fix this issue? Thanks!

**Comment by Jean-Daniel** [comment] 2018-02-01 22:26
My LDAP database don't have samaccountname. I'm using inetOrgPerson to store the user accounts and I'm using uid as rdn, so it is guarantee to be unique in my LDAP base (and it is not a number, but a account name).

Unfortunately, I did a couple of change while migrating and don't know which step exactly corrupted my settings. I think it occurred when I tried to "change" the LDAP settings after the upgrade.

**Comment by Jean-Daniel** [comment] 2018-02-01 22:40
By the way, when I try to update the LDAP, it nows include an empty line for login instead of selecting the right attribute as default (like it did before).

<img width="634" alt="capture d ecran 2018-02-01 a 23 38 24" src="https://user-images.githubusercontent.com/304649/35707206-25db2652-07a9-11e8-8e05-67c7ea21a3a3.png">

**Comment by moellert** [comment] 2018-02-02 07:06
Im not that familiar with our LDAP apart from the questions I ask our LDAP admin, but its the same behavior as described by Jean-Daniel. In my case the uid is also the accountname like moellert

After the update to 2.3 I changed the role mapping and saved the configuration, after this I saw that the attribute mapping has changed.
Back in the configuration I saw the same as in the screenshot and deleted the uid -> nothing mapping.
I am not quiet sure after which of these steps the LDAP auth was broke.
But I definitely need the uid as login.

This was my mapping before the update.
![screen](https://user-images.githubusercontent.com/30858921/35720896-f07eaa3c-07ef-11e8-9e39-d2f1511d0053.jpg)

**Comment by moellert** [comment] 2018-02-02 07:21
Ok, I tested to not delete the uid -> nothing mapping and after I save, the mapping changes from nothing -> samaccountname and uid -> nothing to samaccountname -> login and uid -> login
But anyways I can't login, neither with my email nor with my uid.

**Comment by thorsteneckel** [comment] 2018-02-05 13:46
Hi @moellert and @Jean-Daniel . This is fixed in the latest version of develop and stable in ~30 minutes from now. Feel free to update when possible. Would be great to get some feedback. Closing for now.

**Closed by thorsteneckel** 2018-02-05 13:46 UTC

**Comment by moellert** [comment] 2018-02-05 14:45
Hi @thorsteneckel, as fas as I can say it works fine. Like every time thanks for your fast help and fixes!

**Comment by thorsteneckel** [comment] 2018-02-05 15:38
Thanks for your fast feedback and kind words. You're welcome. 🚀
