### ISSUE TITLE
LDAP // An error occurred: PG::UniqueViolation: ERROR: duplicate key

### ISSUE THREAD

**Issue by Lightyear76** [zammad/zammad#1908] opened 2018-03-29 11:54 UTC
### Infos:

* Used Zammad version: 2.3
* Installation method (source, package, ..): git
* Operating system: Ubuntu 16.04
* Database + version: PostgreSQL 9.5.12
* Elasticsearch version: 5.6.8
* Browser + version: any

### Expected behavior:

* Each imported LDAP entry should be reflected in a separate Zammad account. There should be one Zammad account for one LDAP entry.

### Actual behavior:

* Some users are not imported
* Error message: "An error occurred: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_external_syncs_on_source_and_source_id" DETAIL: Key (source, source_id)=(Ldap::User, d2d87362-9d46-42b5-9f8d-c3b14cafb8ad) already exists. : UPDATE "external_syncs" SET "source_id" = $1, "updated_at" = $2 WHERE "external_syncs"."id" = $3"

### Steps to reproduce the behavior:

* Configure LDAP
* Start LDAP sync

**Comment by thorsteneckel** [comment] 2018-03-29 13:04
Hi @Lightyear76 ,

you are right. This should not happen. Could you please follow the steps I provide next. This will start the LDAP sync manually with debug mode on and create a file called `debug_issue.log` containing everything that has happened while syncing.

1.) Create a file called `debug_issue.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_issue.rb` or `rails r debug_issue.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_issue.rb` file

```ruby
require 'mixin/rails_logger'

module Mixin
  module RailsLogger
    def self.logger
      @logger ||= Logger.new(log_to).tap do |logger|
        logger.level = :debug
      end
    end

    def self.log_to
      # STDOUT
      'debug_issue.log'
    end
  end
end

ImportJob.create(name: 'Import::Ldap', payload: {}).start
```

Thanks in advance.

**Comment by aqustiq** [comment] 2018-04-02 15:24
same for me

**Comment by thorsteneckel** [comment] 2018-04-02 17:05
Hi @aqustiq - please do as I described in my first reply. Thanks to @Lightyear76 who already send the log file - we'll have a look at this next week as discussed via email 👍

**Comment by thorsteneckel** [comment] 2018-04-03 08:36
@aqustiq - just coming from a remote session with @Lightyear76 we found multiple entries in the ExternalSync table pointing to the same User. This is one possibility for the cause of this issue. We found those with the execution of `ExternalSync.connection.select_all("SELECT o_id, COUNT(*) FROM external_syncs GROUP BY o_id HAVING (COUNT(*) > 1)").to_a` in the [Zammad rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console).
Please run the command on your system and post the output.

**Comment by thorsteneckel** [comment] 2018-04-03 08:43
Since this is a relict of a bug fixed some time ago I'll flag it as a duplicate. Sadly I can't find the fix currently that's why I keep the other tags as well.
This issue can be resolved by executing the command above, see the `o_id` (first element in each result row), find the latest entry of it in the ExternalSync and destroy it.
Closing for now.

**Closed by thorsteneckel** 2018-04-03 08:43 UTC
Labels: LDAP, bug, duplicate

**Comment by aqustiq** [comment] 2018-04-03 16:05
Hi Thorsten,
My output of the command is: => [{"o_id"=>18, "count"=>2}]



Sincerely, Ion!Cordialement,  Ion!
IT Infrastructure Administrator

 

    On Tuesday, April 3, 2018, 4:36:28 AM EDT, Thorsten <notifications@github.com> wrote:  
 
 
@aqustiq - just coming from a remote session with @Lightyear76 we found multiple entries in the ExternalSync table pointing to the same User. This is one possibility for the cause of this issue. We found those with the execution of ExternalSync.connection.select_all("SELECT o_id, COUNT(*) FROM external_syncs GROUP BY o_id HAVING (COUNT(*) > 1)").to_a in the Zammad rails console.
Please run the command on your system and post the output.

**Comment by thorsteneckel** [comment] 2018-04-03 16:08
Hi @aqustiq - 🎯 It's the same issue as @Lightyear76 had. The solution is to delete the duplicate entry. You can do so by executing the following command on the [Zammad rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console):

`ExternalSync.where(o_id: 18).last.destroy`

This removed the later, duplicate entry for your local User with the ID `18`. Not the User but the sync entry.
