### ISSUE TITLE
Please update #372

### ISSUE THREAD

**Issue by digitalfredy** [zammad/zammad#4420] opened 2022-12-08 15:42 UTC
### Used Zammad Version

latest

### Environment

Zammad composer interface used to answer tickets.

### Actual behaviour

Concerning the answer from composer you offer an unclear GUI an we users reported it at #372 and we also reported it at https://community.zammad.org/t/answer-via-mail-per-default/2009

In both cases you are not leaving us to participate and you are not giving any updates.

Here we are 6 years latter with the same issue. I had used many trackers (otrs, gitlab, redmine, track, trac ...) and I will repeat same others users told you. 

Your compose interface is not clear. We want to made live easier to agents then please the option to made the send by email option default in composer because we are asking agents to use the button to switch to email and they forget or our hacks are not taking in count if the ticket is in some states.

I think the intention behind closing or blocking is to keep things clean but please update this stuff because from here it looks you are just ignoring the problem and silencing our voices.

### Expected behaviour

In the composer options

- https://admin-docs.zammad.org/en/latest/misc/composer.html

Add a new option to setup the default answer between the available options

![zamad-answer-options](https://user-images.githubusercontent.com/1372919/206489279-c0452172-82bc-44c3-a3c6-7886aee99baa.png)

You do not have to made email the default setup then we are not asking you to brake the default workflow but let us to choose what is best for our usecases because many of us wants to set email as default here.

### Steps to reproduce the behaviour

1. Do a brand new installation
2. Find someone that do not knows Zammad
3. Create a fake issue asking him to answer to it
4. You will see that with a high grade of probability this person will use the box to answer and will think is sending an email.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment] 2022-12-09 04:38
Duplicate of #372 - bumping and opening several issues to the same topic *does not* help or speed up any process.

Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.

**Closed as completed by MrGeneration** 2022-12-09 04:38 UTC
Labels: duplicate, question
