### ISSUE TITLE
Problem with LDAP synch

### ISSUE THREAD

**Issue by maggusf** [zammad/zammad#2131] opened 2018-07-17 07:25 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: postgresql
* Elasticsearch version: 5.6.8
* Browser + version: Safari 11.1.2

### Expected behavior:

* ldap synch working

### Actual behavior:

* very slow, mostly doesn't finish (fill_io error), having errors within the log during synch as following:

part of the log (showing the error):
```
E, [2018-07-17T09:17:45.312789 #12696] ERROR -- : When assigning attributes, you must pass a hash as an argument. (ArgumentError)
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.5/lib/active_model/attribute_assignment.rb:28:in `assign_attributes'
/opt/zammad/lib/sequencer/unit/import/common/model/associations/assign.rb:19:in `process'
/opt/zammad/lib/sequencer/unit/base.rb:200:in `process'
/opt/zammad/lib/sequencer.rb:65:in `block (4 levels) in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:64:in `block (3 levels) in process'
/opt/zammad/lib/sequencer/state.rb:149:in `process'
/opt/zammad/lib/sequencer.rb:62:in `block (2 levels) in process'
/opt/zammad/lib/sequencer/units.rb:29:in `block in each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer.rb:60:in `each_with_index'
/opt/zammad/lib/sequencer.rb:60:in `block in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:58:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/sequencer/unit/import/common/sub_sequence/mixin/base.rb:34:in `sequence_resource'
/opt/zammad/lib/sequencer/unit/import/ldap/users/sub_sequence.rb:17:in `block in process'
/opt/zammad/lib/ldap.rb:79:in `block in search'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:786:in `block (3 levels) in search'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:445:in `block (2 levels) in search'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:399:in `loop'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:399:in `block in search'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap/instrumentation.rb:19:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:388:in `search'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:784:in `block (2 levels) in search'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:1303:in `use_connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:783:in `block in search'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap/instrumentation.rb:19:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:782:in `search'
/opt/zammad/lib/ldap.rb:72:in `search'
/opt/zammad/lib/sequencer/unit/import/ldap/users/sub_sequence.rb:15:in `process'
/opt/zammad/lib/sequencer/unit/base.rb:200:in `process'
/opt/zammad/lib/sequencer.rb:65:in `block (4 levels) in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:64:in `block (3 levels) in process'
/opt/zammad/lib/sequencer/state.rb:149:in `process'
/opt/zammad/lib/sequencer.rb:62:in `block (2 levels) in process'
/opt/zammad/lib/sequencer/units.rb:29:in `block in each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer.rb:60:in `each_with_index'
/opt/zammad/lib/sequencer.rb:60:in `block in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:58:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/import/mixin/sequence.rb:15:in `process'
/opt/zammad/lib/import/integration_base.rb:98:in `start'
/opt/zammad/app/models/import_job.rb:24:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/performable_method.rb:26:in `perform'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'
/opt/zammad/app/models/scheduler.rb:355:in `block (3 levels) in worker'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/zammad/app/models/scheduler.rb:353:in `block (2 levels) in worker'
/opt/zammad/app/models/scheduler.rb:349:in `loop'
/opt/zammad/app/models/scheduler.rb:349:in `block in worker'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### Steps to reproduce the behavior:

* -

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-07-17 07:55
Hi @maggusf - this actually looks like a bug. Could you please do as follows:

1.) Create a file called `debug_issue.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_issue.rb` or `rails r debug_issue.rb` as zammad user, depending on your installation source (package/source)
3.) This will create a new file called `debug_issue.log`. Please upload this file here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_issue.rb` file

```ruby
require 'mixin/rails_logger'

module Mixin
  module RailsLogger
    def self.logger
      @logger ||= Logger.new(log_to).tap do |logger|
        logger.level = :debug
      end
    end

    def self.log_to
      'debug_issue.log'
    end
  end
end


ImportJob.create(name: 'Import::Ldap').start
```

**Comment by maggusf** [comment] 2018-07-17 09:46
Hi @thorsteneckel ,

just send the email with the log. I deleted all lines that contained sensitive data. If you need some more lines like last 3 before error or similar, I will run the script once again and give you those selected lines with manipulated sensitive data (like changing names, ldap infos etc.)

**Comment by thorsteneckel** [comment] 2018-07-17 09:54
Hi @maggusf - this is actually a duplicate of #2110 which the lovely @rlue is currently working on. So a fix is on the way. Thanks anyway for creating the issue and providing the information. Closing now.

**Closed as completed by thorsteneckel** 2018-07-17 09:54 UTC
Labels: duplicate
