### ISSUE TITLE
LDAP/Exchange UTF-8 Status Code 500

### ISSUE THREAD

**Issue by e311** [zammad/zammad#2140] opened 2018-07-24 07:57 UTC
### Infos:

* Used Zammad version:2.6.x
* Installation method (source, package, ..): DEP
* Operating system: ubuntu 18.04
* Database + version: psql (PostgreSQL) 10.4 (Ubuntu 10.4-0ubuntu0.18.04)
* Elasticsearch version:6.6.1 
* Browser + version:
Chrome 

### Expected behavior:
LDPA frame displayed (in config menue System --> Integration-->LDAP)  without error
*

### Actual behavior:

LDAP frame is not displayed. Frame remains empty with error message
Also API and Monitoring
![2018-07-24 08_35_07-microsoft edge](https://user-images.githubusercontent.com/18627219/43124340-31f4b8c6-8f27-11e8-88d7-69abd1361ca2.png)
*
StatusCode 500
{"error":"\"\\xC5\" from ASCII-8BIT to UTF-8"}

### Steps to reproduce the behavior:
only Configure LDAP. 

*
My Config:
  adapter: postgresql
  database: zammad
  pool: 50
  timeout: 5000
  encoding: utf8
  username: zammad

log/production.log:
```
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:69:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/rack/logger.rb:24:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/executor.rb:12:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/static.rb:125:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/engine.rb:522:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2018-07-24T09:47:49.326279 #12796]  INFO -- : Completed 500 Internal Server Error in 1121ms (Views: 0.3ms | ActiveRecord: 43.9ms)
I, [2018-07-24T09:47:50.981956 #12794]  INFO -- : 2018-07-24T09:47:50+0200: [Worker(host:support pid:12794)] Job Observer::UserDeviceLogJob (id=3437) RUNNING
I, [2018-07-24T09:47:51.081012 #12794]  INFO -- : 2018-07-24T09:47:51+0200: [Worker(host:support pid:12794)] Job Observer::UserDeviceLogJob (id=3437) COMPLETED after 0.0988
```
Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-07-24 09:33
Hi @e311 - could you please provide the upper part of the log, too? This is where the required information is printed out and which is currently missing. Additionally: Could you please describe the steps that you performed to get to the issue? This is currently not clear. Thanks!

**Comment by e311** [comment] 2018-07-24 10:08
Hi, 
i will try it. 
i open the (in admin --> system -->Integarion) LDAP. I start the configuration All fine. 
Domain DN User Password.
![3 ldap](https://user-images.githubusercontent.com/18627219/43130686-7fa83cae-8f37-11e8-88aa-034173a64e56.png)

I used the standart mapping. 
![4](https://user-images.githubusercontent.com/18627219/43130706-8772adca-8f37-11e8-90bd-476010b74d8b.png)

Ad the LDAP Config sreen ist look fine.
![6](https://user-images.githubusercontent.com/18627219/43130719-8ec62052-8f37-11e8-835e-bf6b7fe6722a.png)
I press safe. And i get error message.  
![7](https://user-images.githubusercontent.com/18627219/43130818-d35ffda0-8f37-11e8-9dac-9dfd68616b9b.png)

After i reload the Page the Frame is emty.
![2018-07-24 08_35_07-microsoft edge](https://user-images.githubusercontent.com/18627219/43130830-e0d22242-8f37-11e8-8e91-cbb2e1703b4a.png)



and here is the full log file:

[log.txt](https://github.com/zammad/zammad/files/2223087/log.txt)

**Comment by thorsteneckel** [comment] 2018-07-24 10:52
Hi @e311 - thanks for the comprehensive writeup! The interesting line in the log is this one:
```
E, [2018-07-24T11:39:30.491795 #973] ERROR -- : "\xC5" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/core_ext/object/json.rb:36:in `encode'
...
/opt/zammad/app/controllers/application_controller/renders_models.rb:70:in `model_update_render_item'
/opt/zammad/app/controllers/application_controller/renders_models.rb:66:in `model_update_render'
/opt/zammad/app/controllers/settings_controller.rb:31:in `update'
```

Which basically says that there are specially encoded chars in the LDAP settings which will get/got stored. I can see those in the log, too.

I think this is sufficiently enough to reproduce the issue. Thanks for your support so far. We will fix the issue.

**Comment by thorsteneckel** [comment] 2018-07-27 17:16
Please note that the Exchange integration is affected, too: #2152

**Comment by rlue** [comment] 2018-08-06 09:53
Hi @e311,

We've been digging into this issue and are pretty confident we understand what's going on, but we need to ask for your help again to be completely certain.

#### Step 1: Confirm the cause of the bug

Try the following line in your terminal, in the Zammad directory. If our suspicions are correct, then it should fail (_i.e.,_ raise an error and show a traceback):

    $ rails r "puts Setting.get('ldap_config').to_json"

If you saw a traceback for the same `Encoding::UndefinedConversionError` that you got in the initial bug report, then great — onto Step 2! If not, please confirm that you haven't reset your database or altered your LDAP configuration since the last time this bug occurred. If you're still not getting an error, please let us know so that we can continue to investigate.

#### Step 2: Send us one last bit of crucial information

Run the following command in your terminal:

    $ rails r "pp Setting.get('ldap_config').except('bind_pw')" > zammad_2140_debug_output.txt

Then, send the resulting file (`zammad_2140_debug_output.txt`) to support@zammad.com. Be sure to mention that the message is for Thorsten Eckel, and for bug #2140.

With this, we should be able to get a fix working right away.

Thanks again for all your help!

**Comment by e311** [comment] 2018-08-07 11:53
This is the First massege

serveradmin@support:/opt/zammad$ rails r "puts Setting.get('ldap_config').to_json"
Traceback (most recent call last):
        4: from bin/rails:3:in `<main>'
        3: from bin/rails:3:in `require_relative'
        2: from /opt/zammad/config/boot.rb:3:in `<top (required)>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)

 

Gesendet: Montag, 06. August 2018 um 11:53 Uhr
Von: "Ryan Lue" <notifications@github.com>
An: zammad/zammad <zammad@noreply.github.com>
Cc: e311 <falk_wantzen@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [zammad/zammad] LDAP/Exchange UTF-8 Status Code 500 (#2140)


Hi @e311,

We've been digging into this issue and are pretty confident we understand what's going on, but we need to ask for your help again to be completely certain.

Step 1: Confirm the cause of the bug

Try the following line in your terminal, in the Zammad directory. If our suspicions are correct, then it should fail (i.e., raise an error and show a traceback):

$ rails r "puts Setting.get('ldap_config').to_json"


If you saw a traceback for the same Encoding::UndefinedConversionError that you got in the initial bug report, then great — onto Step 2! If not, please confirm that you haven't reset your database or altered your LDAP configuration since the last time this bug occurred. If you're still not getting an error, please let us know so that we can continue to investigate.

Step 2: Send us one last bit of crucial information

Run the following command in your terminal:

   $ rails r "pp Setting.get('ldap_config').except('bind_pw')" > zammad_2140_debug_output.txt


Then, send the resulting file (zammad_2140_debug_output.txt) to support@zammad.com. Be sure to mention that the message is for Thorsten Eckel, and for bug #2140.

With this, we should be able to get a fix working right away.

Thanks again for all your help!

**Comment by e311** [comment] 2018-08-08 05:16
rails r "pp Setting.get('ldap_config').except('bind_pw')" > zammad_2140_debug_output.txt
prodruce a emty file (i can not upload because it is emty)

![befehl](https://user-images.githubusercontent.com/18627219/43817665-f21c0a00-9ada-11e8-920a-ad33e3a1ed01.PNG)
![output](https://user-images.githubusercontent.com/18627219/43817668-f42729e2-9ada-11e8-862b-37b01ae20000.PNG)

**Comment by thorsteneckel** [comment] 2018-08-08 06:37
Hi @e311 - Please try the following:

`zammad run rails r "pp Setting.get('ldap_config').except('bind_pw')" > zammad_2140_debug_output.txt`

OR:

`bundle exec rails r "pp Setting.get('ldap_config').except('bind_pw')" > zammad_2140_debug_output.txt`

but should be the first line.

**Comment by e311** [comment] 2018-08-08 11:19
I try the first Command:
The same as "Serveradmin" with sudo or with out sudo 
![image](https://user-images.githubusercontent.com/18627219/43834098-3d4c9526-9b0d-11e8-9b8b-00d2a3c24002.png)
Bundel my be not installed?
![image](https://user-images.githubusercontent.com/18627219/43834183-860ae9de-9b0d-11e8-9cb2-a30a4ca003e6.png)

**Comment by rlue** [comment] 2018-08-09 11:37
@e311, that's very strange. Let's ignore the second command (`bundle exec rails ...`) for now — I don't think that's the right path here. Could you maybe try to back up the log file and create a new empty one?

```
/opt/zammad:# gzip production.log
/opt/zammad:# mv production.log.gz production.log.15.gz
/opt/zammad:# touch production.log
/opt/zammad:# chown zammad.zammad production.log
/opt/zammad:# chmod 0644 production.log
/opt/zammad:# zammad run rails r "pp Setting.get('ldap_config').except('bind_pw')" > zammad_2140_debug_output.txt
```

Thanks for all your help working through this issue with us.

**Comment by MrGeneration** [comment] 2018-08-09 11:42
@rlue we did the commands yesterday with @e311 .

THe log has perfectly fine access rights, I double checked that.
I'll send you the ldap-config output in mattermost, in case you don't have it yet.

**Comment by rlue** [comment] 2018-08-09 23:52
Whoops, you totally sent me the log at the start of the day yesterday. Don't know how I missed it!

**Comment by rlue** [comment] 2018-08-09 23:58
@e311, I didn't see what I was expecting to see in your debug output. Now that @MrGeneration was able to help you get your `zammad run rails r ...` commands working, could you try the following again and tell me if it's raising the `Encoding::UndefinedConversionError` that this issue is for?

    $ rails r "puts Setting.get('ldap_config').to_json"

**Comment by e311** [comment] 2018-08-13 14:12
I get the Message "Your Ruby version is 2.5.1, but your Gemfile specified 2.4.4"
I sorry it will not work (i try all the thinks that Google say to me)

**Comment by monotek** [comment] 2018-08-13 14:21
Your Ruby & your Elasticsearch version are not compatible with Zammad.
Use Ruby 2.4.4 and Elasticsearch up to 5.6.

**Comment by rlue** [comment] 2018-08-14 04:07
@e311 sorry actually, totally my fault. Forgot to add `zammad r` again. -_-'

I meant

    $ zammad run rails r "puts Setting.get('ldap_config').to_json"

**Comment by e311** [comment] 2018-08-14 05:21
Ther is the message :

[Neues Textdokument (3).txt](https://github.com/zammad/zammad/files/2285597/Neues.Textdokument.3.txt)

**Comment by rlue** [comment] 2018-08-14 12:22
So the output from the last command was exactly what I was expecting. To sum up, it looks like some of the user attributes on your LDAP server have binary data values. Zammad tries to convert these to strings and then pass them around from the backend to the frontend, but since they're not actually strings, we wind up running into some encoding / conversion problems.

Of course, since I can't connect to your LDAP server, I can't be 100% sure that a fix will work until you try it for us. So, I'd like to ask your help on two more points:

1. The last time I asked you to run some commands and email us the output (last Wednesday), the commands I gave you weren't quite right, and didn't exactly give us the information we needed. Here's a script that should get it right this time ([download here](https://gist.githubusercontent.com/rlue/c47e05febb7cae618c11b77711a67c01/raw/25c671db92de7cfdbdeb37b0bef3611e3679b1b5/2140_bug_report.rb)):

   ```ruby
   # Place this script in your Zammad directory and run it with
   #
   #     $ zammad run rails r 2140_bug_report.rb
   #
   # It should create a file named 2140_bug_report.txt.
   # Please send this file to support@zammad.com, and mention that it's for Ryan.

   class Hash
     def deep_values
       values.map { |v| v.try(:deep_values) || v }.flatten
     end
   end

   string_values = Setting.get('ldap_config').except('bind_pw').deep_values.select { |v| v.is_a?(String) }

   File.binwrite('2140_bug_report.txt', Marshal.dump(string_values))
   ```

   Sorry to make you do it twice.

2. I've written a patch which I think should fix the issue. Basically, anytime it encounters a binary data value in the LDAP sync, it skips over it instead of trying to save it as a string.

   I'd like to confirm that the fix works on your machine before we merge these changes into the main codebase. Here is a [bugfixed version of the `lib/ldap/user.rb` file](https://gist.githubusercontent.com/rlue/a78a96b20f8087fd13ec511cc4d8bd02/raw/2d8835f7f272cd30b1a05379fc418ff5ddb8f100/user.rb).

   Download it and copy it to `/opt/zammad/lib/ldap/user.rb`, then **restart Zammad (important!)** and run through the entire LDAP configuration wizard again. Since you already have an existing LDAP configuration, that means you'll have to click on the "Change" button at the bottom of the panel:

   ![screenshot_20180814_201507](https://user-images.githubusercontent.com/12194123/44091184-35e25a04-9fff-11e8-8248-2fb243491a96.png)

If Step 2 **still** doesn't fix it for you, please run the script from Step 1 again, and be sure to send us **both** files.

Thanks again for your help and your patience!

**Comment by e311** [comment] 2018-08-14 13:00
I reboot the hole system, but i can not push the change Button.

![image](https://user-images.githubusercontent.com/18627219/44093048-9103cbac-9fd2-11e8-951b-f29c351be78d.png)

befor the patch
[2140_bug_report (Step1).txt](https://github.com/zammad/zammad/files/2286957/2140_bug_report.Step1.txt)

after the patch
[2140_bug_report(Step2).txt](https://github.com/zammad/zammad/files/2286949/2140_bug_report.Step2.txt)

i also Try a new LDAP configuration. I restore the System befor the LDAP conf. but ist the same result.

**Comment by e311** [comment] 2018-08-14 13:48
I have check the domain functional level. It is 2003 can this be the Problem

**Comment by rlue** [comment] 2018-08-14 15:23
> I reboot the hole system, but i can not push the change Button.

Thanks for clarifying this. I had not understood the scope of the problem, originally.

> i also Try a new LDAP configuration. I restore the System befor the LDAP conf. but ist the same result.

Do you mean you restored the system to before the LDAP conf, successfully ran through the whole wizard, and still wound up with the same problem? Or do you mean you tried to restore the system to before the LDAP conf, but you're still getting this error and can't get to the wizard?

If it's the former, then the patch still needs a little more work; I should have a fix for you tomorrow. If it's the latter, then you can try to reset the LDAP config with

    $ RAILS_ENV=production zammad run rails r "Setting.set('ldap_config', {})"

(You can leave out the `RAILS_ENV=production` part if you're doing this in a development environment.)

**Comment by e311** [comment] 2018-08-15 04:42
I restored a backup, The backup was created before I started the LDAP configuration for the first time.

**Comment by e311** [comment] 2018-08-15 05:12
I try to reset the LDAP con with
`$ RAILS_ENV=production zammad run rails r "Setting.set('ldap_config', {})"`
i not "reset" the conf, it still works. 
It now seems like the whole system is running, without an error message

(Without LDAP)

**Comment by rlue** [comment] 2018-08-15 10:17
Okay, so you're saying:

1. Zammad is working,
2. you currently have no LDAP sync configured, and
3. you're not getting an error message on the LDAP sync page anymore?

(To confirm point 2, you can run `RAILS_ENV=production zammad run rails r "puts Setting.get('ldap_config')"`, which should print `{}` to the console.)

---

If all of the above is true, and you have copied the patched version of `lib/ldap/user.rb` that I linked to above, can you try to set up the LDAP sync one more time, and tell me if you still run into the same problem?

Or if I've misunderstood, please let me know what the situation is.

Thanks.

**Comment by thorsteneckel** [comment] 2018-08-19 15:35
@rlue - JFI: Have a look at https://community.zammad.org/t/unable-to-access-ldap-in-integrations-statuscode-500/1116/5 😍

**Comment by e311** [comment] 2018-08-20 05:26
Sorry for the late reply. Yes everything correct. After the LDAP again configured, I had the same error again.

**Comment by thorsteneckel** [comment] 2018-08-22 06:37
@rlue - as @e311 already stated there is still something wrong: https://community.zammad.org/t/unable-to-access-ldap-in-integrations-statuscode-500/1116/21

**Comment by tbeitter** [comment] 2018-08-23 10:43
FYI: I've got the same issue and the patched user.rb did'nt work for me, too.
Thanks for your work in advance

**Comment by thorsteneckel** [comment] 2018-08-23 11:58
Everybody who still has the issue after changing the file and restarting the application please provide the error (including backtrace) from your `log/production.log` file. Thanks!

**Comment by rlue** [comment] 2018-08-24 10:36
@e311, @tbeitter, and everyone else who's currently experiencing this issue — I have [_yet another_ debugging script I'd like you to run](https://gist.githubusercontent.com/rlue/9d68ff3c56a49ecffbed09df84776c59/raw/649e46c26798ed5b069ea5db51f8f8c04032a380/2140_improved_bug_report.rb). I don't want to speak too soon, but this should really be the last one. 

Place it in your zammad directory and then run

    $ zammad run rails r 2140_improved_bug_report.rb

You will be prompted for your LDAP server URL and login credentials, and then the script will generate a file called `2140_debug_log.txt`. This file contains a sample of user attributes from your LDAP server, so if that might mean anything sensitive, **do NOT post it publicly**. Instead, send it to support@zammad.com, and mention it's for Ryan.

Thank you all for your continued patience as we work through this bug.

**Comment by e311** [comment] 2018-08-27 05:00
Hello, 
If i try to run the new script i get this  (LDAP is on) no file was created.

```
serveradmin@support:/opt/zammad$ sudo zammad run rails r 2140_improved_bug_report.rb
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:34:in `load': 2140_improved_bug_report.rb:77: invalid multibyte char (UTF-8) (SyntaxError)
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:34:in `perform'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'
serveradmin@support:/opt/zammad$
```

[production.log](https://github.com/zammad/zammad/files/2322444/production.log)

**Comment by redbear-ger** [comment] 2018-08-27 08:42
also have this ldap error... (ubuntu 16.04 installation through repo)

```
root@zammad01:/opt/zammad# zammad run rails r 2140_improved_bug_report.rb
Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.

/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37: trailing `_' in number
2140_improved_bug_report.rb
     ^
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37: syntax error, unexpected tIDENTIFIER, expecting end-of-input
2140_improved_bug_report.rb
```

**Comment by rlue** [comment] 2018-08-27 09:01
@redbear-ger, please ensure that `2140_improved_bug_report.rb` is in your `/opt/zammad` directory.

**Comment by rlue** [comment] 2018-08-27 09:09
@e311 whoops, that's a weird bug.

I've modified the script by removing some unnecessary multibyte characters from the console output. You can re-download the script and try again, or simply change the smart quotes on line 77 to regular quotes:

```ruby
# replace “#{default_base_dn}” with '#{default_base_dn}'
printf "Base DN (leave blank for default '#{default_base_dn}'): "
```

Not 100% sure this will fix it, but I have a hunch.

**Comment by redbear-ger** [comment] 2018-08-27 09:16
@rlue, no 2140_improved_bug_report.rb in /opt/zammad

**Comment by redbear-ger** [comment] 2018-08-27 10:05
btw: As soon as I delete the LDAP config ( RAILS_ENV=production zammad run rails r "Setting.set('ldap_config', {})" ), the problem disappears.

**Comment by rlue** [comment] 2018-08-27 11:36
@redbear-ger thanks for your quick feedback; please [download the bug report script](https://gist.githubusercontent.com/rlue/9d68ff3c56a49ecffbed09df84776c59/raw/649e46c26798ed5b069ea5db51f8f8c04032a380/2140_improved_bug_report.rb), place it in `/opt/zammad`, and try again.

Even if the problem is 100% gone now, it would help a lot to have your sample data so we can build tests to make sure this doesn't happen again.

**Comment by redbear-ger** [comment] 2018-08-27 13:06
The bug is gone but also the ldap integration ;)
Will Download the Report Script tonight

**Comment by hublux** [comment] 2018-08-29 09:52
Hello,
I have the same issue and tried all the suggestions above. None of them solve the problem.
So I decided to reproduce the issue on a dev system to give you a debug file without providing sensitive data.

The 2140_improved_bug_report.rb script returned me following text file:
[2140_debug_log.txt](https://github.com/zammad/zammad/files/2331649/2140_debug_log.txt)

Thanks!

**Comment by rlue** [comment] 2018-08-30 03:33
Thanks @hublux! For some reason, there are a bunch of places in the file where control characters (_e.g.,_ `^D`) are replaced with a literal carat (`^`) followed by a literal letter (`D`), and this is causing errors when trying to parse the file. Did you do anything to the file before uploading it, by any chance? (Say, opening it in a text editor, then closing it, and clicking "save changes"?) Or do you suppose that maybe GitHub might have done some kind of processing on it when you uploaded it?

To confirm that the original file is correctly formatted on your machine, please try the following command in your Zammad directory, and verify the output:

```
$ zammad run rails r "puts Marshal.load(File.read('2140_debug_log.txt')).first.inspect"

# should print the following:
["dn", "CN=Exchange Online-ApplicationAccount,OU=SBSUsers,OU=Users,OU=MyBusiness,DC=ebusiness,DC=local"]
```

If that's all working as expected, please email the file to support@zammad.com.

**Comment by hublux** [comment] 2018-08-30 08:32
Hello,
Thank you for your reply.

Indeed, it looks like some of my actions did change the file when I copied the content out of it.
checking it with cat, it looks a little bit different.

![grafik](https://user-images.githubusercontent.com/42802202/44839803-f6e63800-ac3f-11e8-9942-d4a1374eeac1.png)


I tried the command and receive the correct output.
![grafik](https://user-images.githubusercontent.com/42802202/44839320-c8b42880-ac3e-11e8-822d-160ea9c4b1f0.png)
I have sent the file to zammad support.

Here is also the new file
[2140_debug_log.txt](https://github.com/zammad/zammad/files/2335310/2140_debug_log.txt)

**Comment by rlue** [comment] 2018-08-30 10:33
@hublux, thanks again for your speedy feedback. I think there's something wrong with the debug script I wrote, because this new file isn't quite right either (it's missing a lot of data — 4kB, compared to the 16kB debug log you originally sent).

I've since patched the debug script to (hopefully) make the `2140_debug_log.txt` file more robust and safer to transmit without these weird encoding problems. Please [download it one more time](https://gist.githubusercontent.com/rlue/9d68ff3c56a49ecffbed09df84776c59/raw/649e46c26798ed5b069ea5db51f8f8c04032a380/2140_improved_bug_report.rb) and try again. (Feel free to include it in your reply on this thread, if it's more convenient for you.)

<details>
<p><summary>And if you're really curious to know what was wrong with the debug script...</summary></p>
<p>It originally took a Ruby hash, <a href="https://ruby-doc.org/core-2.5.1/Marshal.html">marshalled it</a>, and then wrote the marshalled data to a binary (encoding-less) 'text' file. I really don't know why binary text files would get corrupted when being transmitted from one machine to another, but that's what we're observing here.</p>
<p>This fix takes the marshalled data and base-64-encodes it before saving it to a regular, Unicode text file. That should make it safer to transmit without corruption, because what's more universal than Unicode?</p>
</details>

**Comment by hublux** [comment] 2018-08-30 11:56
[2140_debug_log.txt](https://github.com/zammad/zammad/files/2336038/2140_debug_log.txt)
There you have the output with the new script
regards!

**Comment by pc-coholic** [comment] 2018-08-30 13:46
Hey everyone,
also chiming in, as the same problem affects me, too - even after updating to the new `lib/ldap/user.rb`

[2140_debug_log.txt](https://github.com/zammad/zammad/files/2336350/2140_debug_log.txt)

I also started digging around a little bit in the `ldap_config`-hash and started getting rid of all the `!binary` contents. But it turned out, that even though I had 4 of these, only two screwed with the encoding.

I had to remove `usersmimecertificate` and `msexchmailboxsecuritydescriptor`.

The other two, `msexchmasteraccountsid` and `securityprotocol` did not cause any trouble.

**Comment by hublux** [comment] 2018-08-31 09:17
Hello,

Just to clarify, I'm not sure if this is obvious since I have not seen anybody mentioning this.
As a LDAP connection I use Active Directory with German as Systemlanguage. So I installed a new system and a seperate Domain. The only difference from the previous system where the issue occured is that on the new system the language is set to U.S English instead of German. With this setup there is no error to be found, everything working as expected. So I took my original zammad system where I had the problem and connected it with newly installed Domain and the problem is gone.

Running following on the working setup give me following output:
`sudo zammad run rails r "puts Setting.get('ldap_config').to_json"`

[workingsetup.txt](https://github.com/zammad/zammad/files/2339403/workingsetup.txt)

If I run the command to check the ldap config with the original setup it fails and receive following error:

![grafik](https://user-images.githubusercontent.com/42802202/44904195-c7eac780-ad0e-11e8-93fc-46ce42dcb29d.png)

Hope this helps you.
Regards!

**Comment by rlue** [comment] 2018-08-31 10:32
Thanks @hublux! We've got a fix in the works thanks to your input; it should be merged to `develop` shortly!

**Comment by tidet** [comment] 2018-09-03 05:13
![screenshot_1](https://user-images.githubusercontent.com/12529017/44968552-d9b7af00-af48-11e8-8e3c-da7fbb370388.png)

After Updating still get the same error. (But without Exchange-setup, only LDAP-Sync)

**Comment by rlue** [comment] 2018-09-03 07:48
Hi @tidet, thanks for the feedback. Please follow the directions in [this comment](https://github.com/zammad/zammad/issues/2140#issuecomment-415721670); your sample data will go a long way in helping us resolve this issue conclusively.

**Comment by hublux** [comment] 2018-09-03 08:03
Hi,
Just to inform I had the same issue again but the old config did still exist. So please proceed as following if you experince this issue again.

Delete the old config with following command:
`sudo RAILS_ENV=production zammad run rails r "Setting.set('ldap_config', {})"`

- stop zammad service

- update zammad

- start the zammad service again and try to reconfigure the ldap connection

After this I did not face any issue.

Regards

**Comment by tidet** [comment] 2018-09-03 08:21
@rlue should I try solution above or stay at current error for debugging purposes?
E-Mail with logfile is out to support@

**Comment by rlue** [comment] 2018-09-03 08:41
@tidet, now that we have your sample LDAP data, feel free to go ahead and try the above. I did find one value which _might_ still cause problems anyway, but it's probably fine. ~~And whether or not the directions above fix it for you, there'll be another patch in the pipeline coming later today.~~

**EDIT:** Changed my mind. Since the fix is working for you, I'm going to refrain from modifying the code and adding any unnecessary complexity until it's actually broken for someone.

**Comment by tidet** [comment] 2018-09-03 09:12
@hublux Fix worked for me, too.

**Closed as completed** 2018-09-03 10:07 UTC
Labels: bug, import, LDAP

**Comment by bnalpay** [comment] 2018-09-03 11:05
@hublux fixed as well

**Comment by tbeitter** [comment] 2018-09-05 08:56
we still face this issue. I did was @hublux wrote, deleted the config, updated zammad (2.6.0-1534939663.6d23dae9.stretch now), restarted zammad and configured our ldap connection. Do I have to manually patch code? Thanks in advance.

I was on holiday, sorry for the late reply here and if I missed anything :)

**Comment by hublux** [comment] 2018-09-05 09:35
Hi @tbeitter,
If you run this command do you receive any output:
`sudo zammad run rails r "puts Setting.get('ldap_config').to_json"`

If so check this out:
https://github.com/zammad/zammad/issues/2140#issuecomment-417605384

Regards

**Comment by tbeitter** [comment] 2018-09-05 09:39
Yes, I get an error similar to yours:

`"\xC2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)`

**Comment by hublux** [comment] 2018-09-05 09:49
Hi,

I just checked my version of Zammad I updated this morning:
![grafik](https://user-images.githubusercontent.com/42802202/45085651-7e7cec80-b101-11e8-9eeb-0ca228a5c7d5.png)
It differs from yours.

Could you please procceed again with these steps:
- Delete LDAP config
- stop zammad service
- update zammad again
- start zammad service

Regards

**Comment by tbeitter** [comment] 2018-09-05 10:51
@hublux that worked for me! Thanks!

**Comment by rlue** [comment] 2018-09-12 00:49
Big shout out to @hublux for all your help getting other users sorted out. e07f41ed now includes a database migration that should automatically clear faulty LDAP configurations so that any users who encounter this issue in the future should no longer have to deal with these manual steps.
