### ISSUE TITLE
Time accounting not triggered when using macros

### ISSUE THREAD

**Issue by msteeg** [zammad/zammad#2648] opened 2019-07-04 07:28 UTC
### Infos:

* Used Zammad version: 3.0.0
* Installation method (source, package, ..): source
* Operating system: CentOS 7
* Database + version: MariaDB 10.3
* Elasticsearch version: 5.6
* Browser + version: FF 60.7.2esr

Background: We're using macros for documenting routine tasks. So there is indeed some labor involved, that we like to track, even if the ticket will be quite generic.

### Expected behavior:

* (Note: time accounting is set up and confirmed working) When using macros within the ticket view to quickly change some ticket attributes and close it in fact, any change should do), time accounting should be triggered.

### Actual behavior:

* Using macros will not trigger the time accounting dialog. But manual changes will do so.

### Steps to reproduce the behavior:

- Set up time accounting for group and state changes
- create a macro that modifies some stuff, maybe set the ticket state to closed or something
- open a ticket in ticket view, which would normally trigger time accounting dialog
- use macro to modify ticket
- no time accounting dialog will pop up

Yes I'm sure this is a bug and no feature request or a general question.

Cheers,
M.

**Comment by MrGeneration** [comment] 2019-08-28 16:30
Sorry, but I can't reproduce this issue.
Reason behind this might be, because time accounting only is triggered when adding articles.

Please note that, because of the above, this might be blocked by this issue: https://github.com/zammad/zammad/issues/542


Can you please ensure, that whatever you want to do with the macro (while expecting time accounting dialogues) is working the manual way as well?

If so, please provide the exact configuration of your macro, I'll check again then. :-)

**Comment by msteeg** [comment] 2019-08-28 16:41
Hi,

this could indeed be related to the issue, you’re mentioning.
During manual testing, I noticed, that the accounting dialog only appears, when there are new notes. It does not appear, if you’re only changing ticket states, for example... Which aligns with your opinion. Our Macro supposed to add a note also, but due to issue #542 it won’t happen.

On the other hand: Is it intentional, that you’re required to add a note, if you want to hit the accounting dialogue? How do you track times spend just for ticket routing, e. g. if you need to find out, who’s the correct person to route to – Me personally don’t want to write down some light novels each time... Maybe it could make sense to have this configurable within the accounting settings page.

Cheers,
Marc

**Comment by MrGeneration** [comment] 2019-08-29 08:52
I get your point(s).
Currently this is working as designed and thus everything seems to be fine (except for my mentioned issue).


Extending the time accounting would be a feature request that I'd like to ask you to post on the Community ( https://community.zammad.org ). Right now it works as designed, even though it might not be optimal. :-)

As this is rather a feature request, I'd close this issue now. :)

**Closed as completed by MrGeneration** 2019-08-29 08:52 UTC
Labels: duplicate, works as designed / wontfix
