### ISSUE TITLE
Not possible to copy inline images from article to article (copy only image - directly via copy image)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2192] opened 2018-08-16 13:22 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-IDs: #1039044

### Expected behavior:

* take images via cut & past taken from an existing article

### Actual behavior:

* image is lost after submit

### Steps to reproduce the behavior:

- Download [ticket-21002-2.eml.zip](https://github.com/zammad/zammad/files/2219562/ticket-21002-2.eml.zip) and unzip
- `cat ~/Downloads/ticket-21002-2.eml | rails r 'Channel::Driver::MailStdin.new'`
- Open ticket im Zammad
- Right click on the image in the created article -> Copy
- Paste image from clipboard in the new article box
- Update ticket
- See image disappear

See:
![image_lost](https://user-images.githubusercontent.com/3873515/43081023-58e1c546-8e91-11e8-97d5-f5e1a6c137fb.gif)

**Comment by MatthiasBergen** [comment] 2020-02-21 12:37
I guess the same problem is causing copying external images to a ticket/knowledge base article.

See:
![Video_2020-02-21_133105](https://user-images.githubusercontent.com/39553659/75035202-41501a00-54af-11ea-9215-b2019aed6dee.gif)

**Comment by mantas** [comment] 2020-02-21 12:43
@MatthiasBergen image copy-paste support was recently improved. Bugfixes will be included in 3.3. 

Could you test against `develop` branch? Please open a new issue if it persists. It'd be great if you'd provide browser details and clipboard content.

**Comment by mantas** [comment] 2020-02-21 12:46
This issue cannot be reproduced in `develop` branch anymore. Looks like it was fixed along with other copy-paste issues. Closing.

**Closed as completed by mantas** 2020-02-21 12:46 UTC
Labels: bug, verified, prioritised by payment, frontend

**Comment by MatthiasBergen** [comment] 2020-02-21 12:56
Browser: BRAVE Version 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
OS: Windows 10 Version 1903 64 Bit

I installed Zammad on UBUNTU 18.04.04 LTS in version 3.2.0-1580110414.992e734c.bionic.
For the short video I used an article from heise.de, marked some text and the image, pressing CTRL+C, got back in Zammad and pressed CTRL+V.
Thats it.

Don't know how to test against develop-branch. But if it can't be reproduced I hope it is fixed in the new stable-release.

Thank you
