### ISSUE TITLE
Put the ticket number (not ID) in the URL

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#1050] opened 2017-05-05 19:54 UTC
### Infos:

* Used Zammad version: 1.5

### Expected behavior:

* Have ticket IDs/numbers in URL

### Actual behavior:

* URL contains a zoom-number like zammad.com/#ticket/zoom/58
* You don't know that the zoom-number is for.

### Background, Reasons

* You often copy the whole URL and paste it into other applications (YouTrack, Confluence, Mails, txt-files, …). Now if you open that YouTrack-ticket, your documentation in confluence, etc. you stumble upon the URL. Maybe you have not always the possibility to click+open the link or you just want to remember the ticket ID to manually type/paste it somewhere else.
* There is no obvious association between the ticket ID and the zoom-number, hence the zoom-number is completely unneccessary.
* You cannot conclude the ticket ID from the zoom-number and vice versa.
* Without this association you **must** click+open the link, even if this is not always possible, e. g. when you pasted the URL into a txt-file or into that tiny note-widget on your desktop.

I'm not sure about the consequences, i. e. how complex the implementation is. So I would like to put this up to discussion.

**Comment by htetpaingkyaw** [comment] 2018-02-03 06:25
Good

**Comment by helmo** [comment] 2022-03-07 20:31
Two related community questions:
- https://community.zammad.org/t/ability-to-link-to-zammad-tickets-via-number-instead-of-internal-id/2467

- https://community.zammad.org/t/mismatch-ticketnumbering-between-url-and-number/5654

We developed a quick redirect script work around this issue, 

index.php
```php 
<?php

/**
 * Redirect service for zammad tickets
 *
 * Usable in e.g. https://github.com/<org>/<repo>/settings/key_links
 *
 * Links can be used like: https://example.com/zammad1/421042
 * 
 * This strips the first two digits from the ticket number.
 * Zammed uses it's url's without that prefix.
 * But these is an offset sometimes :(
 */

function getUri() {
    $uri = explode("/", $_SERVER["REQUEST_URI"]);

    foreach ($uri as $i) {
        $check = str_replace('_','A', $i);
        if ($i != "" && preg_match("/[a-z0-9]/i", $string)) {
            die();
        }
    }
    $uri = array_slice($uri, 1);
    if (end($uri) == "")
        unset($uri[count($uri) - 1]);
    return $uri;
}

$uri = getUri();

$helpdesk = $uri[1];
$ticketNumber = intval(substr($uri[2], 2));

if ($helpdesk == "zammad1") { 
    $host = "helpdesk.example.com";
}
elseif ($helpdesk == "zammad2") {
    $host = "ticket.example.com";
    // Sometimes an offset is introduced by manual db actions or merges??? Just an example.
    if ($ticketNumber > 1000) {
        $ticketNumber++;
    }
}
else $host = null;

if (!empty($host)) {
    $url = "https://" . $host . "/#ticket/zoom/" . $ticketNumber;
    header("Location: " . $url, true, 302); 
}
else {
    header("401 Not Authorized");
}
```


With a .htaccess file:
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]
```

**Comment by pgassmann** [comment] 2022-07-05 08:43
related to https://github.com/zammad/zammad/issues/849

**Comment by MrGeneration** [comment] 2022-07-05 09:05
Duplicate of #849

**Closed by MrGeneration** 2022-07-05 09:05 UTC
Labels: enhancement
