### ISSUE TITLE
Allow submission of individual field data via forms

### ISSUE THREAD

**Issue by samtuke** [zammad/zammad#1109] opened 2017-05-17 13:11 UTC
Currently forms appear to be limited in what data can be submitted. Allow more data to be submitted via forms, particularly via hidden fields which can be populated with important data, such as user ID or account ID.

**Comment by thorsteneckel** [comment] 2018-08-02 11:31
Closing this as a duplicate of #1109 - because of a more comprehensive description. Feel free to subscribe over there for further notifications on the progress.

**Closed by thorsteneckel** 2018-08-02 11:31 UTC
Labels: enhancement
