### ISSUE TITLE
"StatusCode: 500" No configured hours found in calendar

### ISSUE THREAD

**Issue by autohausnielsen** [zammad/zammad#1396] opened 2017-09-10 15:26 UTC
I was working on a ticket and tried to delegate it to an agent. I got an error message from Zammad:

```
StatusCode: 500

{"error":"No configured hours found in calendar #\u003cCalendar id: 1, name: \"Germany_1\", timezone: \"Europe/Berlin\", business_hours: {}, default: true, ical_url: \"http://www.google.com/calendar/ical/de.german%23ho...\", public_holidays: {}, last_log: nil, last_sync: \"2017-09-07 15:33:57\", updated_by_id: 3, created_by_id: 1, created_at: \"2016-12-16 11:32:00\", updated_at: \"2017-09-07 15:33:57\"\u003e"}
```

Working hours in calendar "Germany_1" were empty. 

I don't know why they were suddenly missing, because I entered them a long time ago.

Problem with update to 2.1 ??

### Solution: 
Re-entered our workig hours.

### Infos:

* Used Zammad version:  2.1.1-1504879832.a4a513ed.xenial
* Used Zammad installation source: Ubuntu
* Operating system:  Ubuntu
* Browser + version:  Firefox

**Comment by martini** [comment] 2017-09-10 15:30
Hi @autohausnielsen 

yes. It's because of develop branch. In case you are on productive system, stable branch would be more stable. :)

Anyway, this issue is a duplicate of https://github.com/zammad/zammad/issues/1395 -> This means if you update your Ubuntu now, it should work again (working hours come back, macros are working again...).

Feedback is welcome!

 -Martin

**Closed** 2017-09-10 15:31 UTC
Labels: duplicate
