### ISSUE TITLE
Zammad getting stuck receiving mails

### ISSUE THREAD

**Issue by hhoechtl** [zammad/zammad#948] opened 2017-04-13 06:06 UTC
### Infos:

* Used Zammad version: 1.5.0
* Operating system: Docker
* Browser + version: Chrome latest

### Expected behavior:

* Zammad keeps working and receives mails

### Actual behavior:

* Zammad is not receiving any mails and continuously logging the following:

```
2017-04-12T17:56:42Z:client(6501043197) recipient attribute isn't a hash '{"user_id"=>[12]}'
2017-04-13T05:04:41Z:client(743461548) request spool data > '2017-04-12T14:23:02Z'
2017-04-13T05:04:41Z:client(743461548) send spool to (user_id=37)
2017-04-13T05:04:41Z:client(743461548) send spool to (user_id=37)
2017-04-13T05:04:41Z:client(743461548) send spool:sent event
2017-04-13T05:04:41Z:client(4601561089) request spool data > '2017-04-12T14:23:02Z'
2017-04-13T05:04:41Z:client(4601561089) send spool to (user_id=37)
2017-04-13T05:04:41Z:client(4601561089) send spool to (user_id=37)
2017-04-13T05:04:41Z:client(4601561089) send spool:sent event
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) do not send broadcast to it self
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
2017-04-13T05:04:43Z:client(743461548) recipient attribute isn't a hash '{"user_id"=>[37]}'
```

### Steps to reproduce the behavior:

* As I have no idea what causes that issue, I don't know how to reproduce it. It happens randomly every few days. A restart of the zammad container solves the issue temporarily.

**Comment by martini** [comment] 2017-04-17 10:58
Hi @hhoechtl 

i tried to find out what the error message cause. But I didn't found any hint. But the error message has nothing todo with email processing.

Any more infos/logs to share?

 -Martin

**Comment by hhoechtl** [comment] 2017-04-17 14:13
Hi @martini, unfortunately there's nothing more I can tell. We have 2 mail accounts that receive mails via Gmail IMAP. Is there something I could do to get a hint on what's causing it?

**Comment by martini** [comment] 2017-04-17 17:57
You can call the mail processing from command line this way:

`rails r 'Channel.fetch'`

**Comment by k-enis** [comment] 2017-04-25 08:45
Hello,
since today we aren't receiving emails in zammad. In the server error log I'm getting the same error message as above. I tried restart of the zammad container but it still doesn't fetch the emails.

I have added the changes from the commit above and now I'm getting the following error message:

`2017-04-25T08:21:49Z:client(3911995504) recipient attribute isn't a hash (ActionController::Parameters) {"user_id"=>[159]}
2017-04-25T08:21:49Z:client(3911995504) recipient attribute isn't a hash (ActionController::Parameters) {"user_id"=>[159]}
2017-04-25T08:21:49Z:client(3911995504) recipient attribute isn't a hash (ActionController::Parameters) {"user_id"=>[159]}
2017-04-25T08:21:49Z:client(3911995504) recipient attribute isn't a hash (ActionController::Parameters) {"user_id"=>[159]}`

Zammad Version: 1.4.0
Server:  CentOS 7
Browser: Firefox

**Comment by thorsteneckel** [comment] 2018-01-03 08:41
Hi @hhoechtl and @k-enis - we can't reproduce the error. If it's still present please provide further information on how to reproduce or contact us via support@zammad.com so we can have a remote session via TeamViewer. Closing for now.

**Closed by thorsteneckel** 2018-01-03 08:41 UTC
Labels: can't reproduce, wontfix
