### ISSUE TITLE
Reports (with own fields) not working

### ISSUE THREAD

**Issue by MadNBG** [zammad/zammad#2679] opened 2019-07-23 10:47 UTC
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): package
* Operating system: Docker
* Database + version: 
* Elasticsearch version:
* Browser + version:

We defined some fields under Settings > Objects > tickets. 
It's a drop-down-menue with several Topics (Bugs, Tickets, Orders...) 
From this, we want to create Reports. While generating a report, you can select those Topics. 
But in the graphical view, Nothing is shown. 
If you delete this rule, and use another one, this will work.  

In German:
Wir haben eigene Felder unter Einstellungen > Objekte > Tickets definiert. Es handelt sich um ein Drop-Down-Menü mit x Inhalten. Nun würden wir hierüber gerne einen Report erstellen. Bei der Reportgenerierung kann man die Auswahl bzw. das neue Feld anwählen. Es wird jedoch in der grafischen Ansicht nichts angezeigt. Löscht man diese Regel und verwendet andere, funktioniert es einwandfrei.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by gestoramd** [comment] 2019-07-25 18:41
In zammad 3.1 the same error continues when you use your fields.

the graphic goes blank

**Comment by gestoramd** [comment] 2019-07-25 18:44
[Report.zip](https://github.com/zammad/zammad/files/3432845/Report.zip)

**Comment by thorsteneckel** [comment] 2019-07-26 07:33
Thanks for reporting this and providing the video @gestoramd - that actually helps a lot. We will address this and have a look 👍

**Comment by MrGeneration** [comment] 2019-08-05 07:45
I believe that this is a indirect duplicate of #2517 which behaves exactly the same way (just with other attributes).

Thus, I'd like to close this for the sake of above mentioned issue. :-)

Thanks for reporting!

**Closed as completed by MrGeneration** 2019-08-05 07:45 UTC
Labels: can't reproduce

**Comment by MrGeneration** [comment] 2020-10-08 07:09
After re-visitting this with developers we could no longer reproduce this in a stable where above mentioned issue is not yet fixed. 
It seems like -in your case- you had tickets that appear on a not ticket in selector "Primeira Solucao" which actually delivers results as you can see in the screen from your video below:

![image](https://user-images.githubusercontent.com/6549061/95425846-361a0380-0945-11eb-9ccd-5953d33662af.png)

This might be my bad during verification.
