### ISSUE TITLE
Delete Spam User Accounts

### ISSUE THREAD

**Issue by semaf** [zammad/zammad#1260] opened 2017-07-17 00:44 UTC
After Ticket is tagged as spam, the user account should be deactivated and deleted and only email could be saved for spam detection. 

At the moment User is able to login. Can create a new ticket? Admin/Agent should be able to delete account too.

**Comment by dnauck** [comment] 2017-11-23 17:15
Possible duplicate of #381 and #380

**Comment by thorsteneckel** [comment] 2018-04-25 07:38
As @dnauck stated correctly this is a duplicate of #381 and will be addressed there. Closing now.

**Closed by thorsteneckel** 2018-04-25 07:38 UTC
Labels: enhancement, feature backlog
