### ISSUE TITLE
Zammad Chat widget - Personalizing chat

### ISSUE THREAD

**Issue by csMobility** [zammad/zammad#1625] opened 2017-11-08 14:17 UTC
### Infos:

* Used Zammad version: 2.1.0
* Used Zammad installation source: (source, package, ...) Linux-based package
* Operating system: Linux 
* Browser + version: Firefox 56.0.2 (64-Bit)

### Expected behavior:

* We would like to define chat options that personalize a chat when opened by an external given customer number and/or a customer name and/or....

### Actual behavior:

*  the chat holds only a sessionID (given by the system) and a base URL (the script is called by)
* the user is treated as anonymous
<img width="321" alt="grafik" src="https://user-images.githubusercontent.com/33482648/32553647-c1d3edf0-c497-11e7-9401-2410901a4eff.png">

### Steps to reproduce the behavior:

*

**Comment by csMobility** [comment] 2017-11-09 10:28
Could be a duplicate of feature wish https://github.com/zammad/zammad/issues/1407

Could somebody clarify if this https://github.com/zammad/zammad/issues/233 might suit as a workaround.

**Comment by thorsteneckel** [comment] 2017-11-10 11:17
You are right. This is a duplicate of #1407. If this workaround works (for you) is up to you. We plan to polish the chat functionality in some near future but have no concrete timeline yet.

**Closed by thorsteneckel** 2017-11-10 11:17 UTC
