### ISSUE TITLE
Object already exist (User)

### ISSUE THREAD

**Issue by morphxle** [zammad/zammad#998] opened 2017-04-26 14:40 UTC
Hello,

today i tried to create a new customer over the admin interface. 
Bit i only get an error. 

![snipimage](https://cloud.githubusercontent.com/assets/16727925/25440170/df8acafa-2a9e-11e7-9385-82ae59a58978.png)

There is no duplicate in the system, maximum a email that is sended to this address without a created user.

Thanks in advance
Jens

**Comment by martini** [comment] 2017-04-26 14:42
@morphxle Thanks!

### Infos:

* Used Zammad version: 
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version:

**Comment by morphxle** [comment] 2017-04-26 15:20
deb xenial stable 1.5.x on ubuntu 16.10

tested with chrome Version 58.0.3029.81 and edge in  38.14393.1066.0

The problem occurs only if you have already sent an email to this address, without an existing user.

**Comment by martini** [comment] 2017-04-28 13:38
Hi @morphxle 

thanks for feedback. 

> The problem occurs only if you have already sent an email to this address, without an existing user.

So can your test the following:

1) search for the user you want invite, make sure that this user is not existing
2) If you invite a new user, you still get the "Object already exist (User)" exists?

If the user already exists (e. g. because the your already sent an email to you Zammad), you can't invite him again, because it's already created (but we could think about that to invite users if they already exists).

**Comment by morphxle** [comment] 2017-04-28 14:29
hi @martini 
thanks for your feedback. 

The main reason of sending emails direct without creating a new user was the version 1.3 (no possibility to create a new user from the "Kunde ändern" dialog) Now it is no problem, but those adresses already in the db - Is it possible to delete the wrong entries or create custumers with those email addresses?

**Comment by martini** [comment] 2017-04-28 14:38
> Now it is no problem, but those adresses already in the db - Is it possible to delete the wrong entries or create custumers with those email addresses?

I didn't got it. :) Zammad is creating customers right after receiving the first email of the customer (or the customer was somewhere in CC). From this time on you can find the customer in your Zammad.

If you want to invite one of this customer, you will get the error message "Object already exist (User)". Because Zammad means "create customer and send invite email". **I would say, this is wrong. Zammad should be able to send an invite to an customer also if already existing.**

PS: One note info. If you want to create an email ticket (new ticket -> email outbound) and you have not already created the customer, just enter the email address of the customer in the "customer" field (without selecting an customer). The customer user will be created by Zammad automatically at ticket creation.

Greetings!

**Comment by martini** [comment] 2017-04-28 14:40
> Is it possible to delete the wrong entries or create custumers with those email addresses?

Currently it's not possible to delete customers via the UI. Via the backend you can delete customers without references (e. g. existing tickets). We already work on user merge via the UI (can't tell you an release date now).

**Comment by thorsteneckel** [comment] 2018-04-27 08:54
To me this reads as it would work as designed. Let me know if I got it wrong. Feel free to open a technical discussion over at our community board http://community.zammad.org/ if you think this should get changed and how to do so. Closing now.

**Closed by thorsteneckel** 2018-04-27 08:54 UTC
Labels: wontfix
