### ISSUE TITLE
FQDN in Zammad whit port, fails SMTP

### ISSUE THREAD

**Issue by PaulMora93** [zammad/zammad#5318] opened 2024-08-28 22:00 UTC
### Used Zammad Version

latest

### Environment

- Installation method: docker compose
- Operating system  ubuntu 20.04
- Database + version:  postgresql 15
- Elasticsearch version: latest
- Browser + version: firefox

### Actual behaviour

I configured a new ticket system with zammad, linked my office365 for incoming and outgoing mail, followed all the steps to register the oauth, but when sending an email I get Unable to send email to 'xxxxx@hotmail.com': Can't use Channel::Driver::Smtp: #<Net::SMTPSyntaxError: Net::SMTPSyntaxError>" then I saw a similar problem and they told me that it is the FQDN there my application is with a port and that port is used for the microsoft callback registered in azure, if I delete it it does not authenticate the office 365 account again, then I remove that port and there it does send the emails

### Expected behaviour

So maybe add a variable fqdn_without_port or remove the port automatically or allow to override the sender in the same form.

### Steps to reproduce the behaviour

install Zammad on an url with port and then try to set up smtp in the initial installation flow

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by mgruner** [comment] 2024-08-29 05:40
Looks like a duplicate of #5127

**Closed as not planned by mgruner** 2024-08-29 05:40 UTC
Labels: needs verification

**Comment by PaulMora93** [comment] 2024-08-29 13:19
There is no solution in that answer

**Comment by mgruner** [comment] 2024-08-29 13:21
Yes, it's an open issue.

**Comment by PaulMora93** [comment] 2024-08-29 13:25
I also have a problem with third-party authentication, with Microsoft Office, an error appears, I have also followed the tutorials on the official page, registering the application and everything but nothing
![auth-third](https://github.com/user-attachments/assets/e3fdb757-df95-45a5-95a6-d023f345f511)

nginx.conf

server {
    server_name pruebas.interpro.ec;
    listen 80;

    location /.well-known/acme-challenge/ {
        auth_basic off;
        allow all;
        root /usr/share/nginx/html;
        try_files $uri =404;
        break;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 805 ssl;  # Puerto para HTTPS
    server_name name.xxx.ec;

    ssl_certificate /etc/nginx/certs/certificate.crt;
    ssl_certificate_key /etc/nginx/certs/certificate.key;

    location / {
        proxy_pass http://pruebas.interpro.ec:8030;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

**Comment by MrGeneration** [comment] 2024-08-29 13:41
@PaulMora93 please consult the community for technical questions. Thank you.
https://community.zammad.org
