### ISSUE TITLE
Thread Erkennung

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#190] opened 2016-08-03 11:06 UTC
Oh, Mann. Zammad spricht mit sich selbst:

https://linuxhotel.zammad.com/#ticket/zoom/503

**Comment by rolfschmidt** [comment] 2017-04-21 07:35
Duplicate of https://github.com/zammad/zammad/issues/206

**Closed by rolfschmidt** 2017-04-21 07:35 UTC
Labels: duplicate

**Comment by DNF-SaS** [comment] 2018-02-26 18:04
Is it possible to trigger thread / followup - detection by using the API?
Will say: POST a new article into zammad via ticket_articles-API and it will get processed by the same code which is used when zammad receives an email.

**Comment by thorsteneckel** [comment] 2018-02-26 19:56
Hi @DNF-SaS - please don't post under closed issues and ask (technical) questions over at our community board https://community.zammad.org. Thanks!

**Comment by DNF-SaS** [comment] 2018-02-27 05:39
Thanks.
Created the question here: https://community.zammad.org/t/trigger-thread-followup-detection-by-using-the-api/352
