### ISSUE TITLE
Ensure Zammad only updates affected content (affects several)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2431] opened 2019-01-14 15:59 UTC
### Infos:

* Used Zammad version: 2.8 + develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any
* Ticket-ID: #1035538, #1033516, #1042393, #1044403, #1056313 

**Please note**
This issue affects several of Zammads parts:

* Organizations
* Users
* SLA (and thus Tickets)
* Calendar-Sync (partial SLA; ical sync for holidays)
* (API)

As this has several parts and is more of an enhancement, I changed the layout how I wrote this up, as expected and current behaviour is not needed in my opinion. I will describe all affected areas as good as possible, the solution is kinda the same for all of them.

## API

* When using user based authentication (instead of an API-Key) for e.g. searching, creating (etc), Zammad will always update the last login. This will cause the Organization to be updated - Zammad will also touch *every* single user that's part of the organization.
* Every update and touch will -beside touching the database object- also cause a reindex of the object within elasticsearch.

**Effect:** This causes Zammad to use extreme amounts of ressources for just one simple request and is (if you have let's say 50 members in one organization) take very high amounts of time to fullfill the request.

**Note:** In worst case, this can lead to a Zammad that can't fullfill all wanted requests.

## Calendar-Sync

* Calendar-Sync updates are running daily and will fetch the current holidays from e.g. ical sources. As since might update sla-related things within tickets, Zammad will touch all tickets - at this moment "updated_at" get's updated and nothing is being logged (no history entry as well).

## Organizations

* Updated on an orgnization (e.g. a note) will cause Zammad to touch every use. In the moment this happens, Zammad will update "updated_at" for the user as well and reindex the object. 
* Changing information within the organization shouldn't bother user objects, as they're childs and have no linked information that's needed in that object.

**Effect:** The more members an organization has, the worse this behaviour gets - it will take time that's not needed.

## Users

* Updating Users will cause an update for the organization and it's members. It should be enough to update only the needed objects (so if something will change them)

**Effect:** The more members an organization has, the worse this behaviour gets - it will take time that's not needed.

## SLA

* When changing SLA settings, Zammad will touch every tickets. This makes sense at it has to check if the tickets meet the new SLA times. Problem is, that Zammad will update every ticket that matches the SLA options. If the number of tickets that match the SLA rules get higher, this will slow down Zammad drastically.
* Another problem with SLA is, that zammad will regulary recreate SLA statistics. This will touch any affected ticket object which will also cause Zammad to take systems ressources (and might even lead to Zammad being temporarily not available).

**Note** This will cause a reindex of all objects affected.

### Resolution

The resolution would be to ensure that Zammad only updated database entries (and reindexes objects), if they've changed. This will take a lot of important time and ensure that Zammad will stay performant if Zammad deals with larger companies and organizations.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-01-22 14:36
This is sorta related to: https://github.com/zammad/zammad/issues/2298

**Comment by thorsteneckel** [comment] 2020-02-18 14:52
Hey @rolfschmidt - this is fixed with https://github.com/zammad/zammad/commit/ed8a152f28a18e6d070dadbba2e79e524a3b42f7 and is a duplicate of #2911 - right?

**Comment by rolfschmidt** [comment] 2020-02-18 15:06
@thorsteneckel yes i think so.

**Comment by thorsteneckel** [comment] 2020-02-18 15:11
Perfect ❤️ This is something that @MrGeneration will be happy to hear about 👂 Closing now.

**Closed as completed by thorsteneckel** 2020-02-18 15:11 UTC
Labels: duplicate

**Comment by MrGeneration** [comment] 2020-02-18 15:15
Oh baby, I'm absolutely thrilled about these news. 😏 

Edit: Thanks for your efforts!
