### ISSUE TITLE
Error creating ticket with changed Ticket Number Format

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#228] opened 2016-10-19 22:04 UTC
If i change settings "Ticket Number Format" from Increment to Date i get the follwoing error when trying to add a new ticket:

> StatusCode: 500
> {"error":"undefined method `[]' for false:FalseClass"}

**Comment by monotek** [comment] 2016-11-15 22:19
Works in 1.1. if only Ticket Number Format is changed.

After als changing:

Ticket Number Increment Date
Ticket Number Increment

I got the old error. Even if i changed the last 2 options to the old values.

**Comment by martini** [comment] 2016-11-16 05:30
JFI, duplicate of https://github.com/zammad/zammad/issues/413, fix is on the way.

**Closed by martini** 2016-11-16 05:30 UTC
Labels: duplicate
