### ISSUE TITLE
Set "TO" field (on reply) to the actuall Customer not the initial one

### ISSUE THREAD

**Issue by schmanat** [zammad/zammad#2239] opened 2018-09-19 06:15 UTC
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): deb
* Operating system: Ubuntu 16.04
* Database + version: PostgreSQL 9.5
* Elasticsearch version: 5.5.x
* Browser + version: Chrome, Firefox, IE 11(all latest versions)

### Expected behavior:

* If I change the customer of a ticket and want to reply with e-mail the actuall customer should be set to the "TO" Field not the initial Customer

### Actual behavior:

* If a Ticket was created from Customer A and the Agent change it the Customer B the reply (with E-Mail) set the To field to Customer A

### Steps to reproduce the behavior:

* Create a Ticket with Customer A
* Agent should now change it to Customer B
* Agent click on "reply"
* The "To" filed is now filled with the E-Mail Adress of the initial Customer (Customer A).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-09-19 08:42
Hi @schmanat - This works as designed. "Reply" means reply to that certain article but not to the Customer of the ticket as described in https://github.com/zammad/zammad/issues/2184#issuecomment-422709614.

However, to achieve the desired behavior you have two options:

1. Create a new Article by clicking in the text area. Change the Article Type to "Email". Insert the name of the Customer in the `To` autocomplete field. From now on you can reply to this message.

2. Create a Trigger that will automatically send the content of an external note to the Customer of the Ticket. You can then configure your Zammad to have external Articles as default. You now can just enter the Article text area, write your text and hit the submit button 🚀

The second option is already best practice for a lot of Zammad (power) users because it ensures that you a) always reach the customer (of the Ticket) and b) the customer (of the Ticket) is always notified about external notes, too. 🙌 

If this doesn't fit your needs please open a topic over at the [community board](http://community.zammad.org/) and we can discuss this further.

Closing now.

**Closed as completed by thorsteneckel** 2018-09-19 08:42 UTC
Labels: works as designed / wontfix

**Comment by schmanat** [comment] 2018-09-19 11:15
ok thanks a lot for your answer, I will try the second option.
