### ISSUE TITLE
many unprocessable mails

### ISSUE THREAD

**Issue by Dookalis** [zammad/zammad#4132] opened 2022-06-17 08:32 UTC
### Infos:

* Used Zammad version: 5.1.x
* Installation method (source, package, ..): package
* Operating system: debian 10
* Database + version: mariadb 10.5.15
* Elasticsearch version: 7.8.1
* Browser + version: Chrome 102.0.5005.115

### Expected behavior:

* {"healthy"=>true, "message"=>"success", "token"=>"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}

### Actual behavior:

* {"healthy":false,"message":"unprocessable mails: 9","issues":["unprocessable mails: 9"],"actions":[],"token":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}

### Steps to reproduce the behavior:

* zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/d41d8cd98f00b204e9800998ecf8427e.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<NoMethodError: undefined method `match?' for nil:NilClass>"
Traceback (most recent call last):
        27: from /opt/zammad/bin/rails:9:in `<main>'
        26: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        25: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        24: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands.rb:18:in `<main>'
        23: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/command.rb:46:in `invoke'
        22: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/command/base.rb:69:in `perform'
        21: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        20: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        19: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        18: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `perform'
        17: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `eval'
        16: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
        15: from /opt/zammad/app/models/channel/email_parser.rb:505:in `process_unprocessable_mails'
        14: from /opt/zammad/app/models/channel/email_parser.rb:505:in `glob'
        13: from /opt/zammad/app/models/channel/email_parser.rb:506:in `block in process_unprocessable_mails'
        12: from /opt/zammad/app/models/channel/email_parser.rb:120:in `process'
        11: from /opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
        10: from /opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
         9: from /opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
         8: from /opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
         7: from /opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
         6: from /opt/zammad/app/models/channel/email_parser.rb:121:in `block in process'
         5: from /opt/zammad/app/models/channel/email_parser.rb:157:in `_process'
         4: from /opt/zammad/app/models/channel/email_parser.rb:157:in `each'
         3: from /opt/zammad/app/models/channel/email_parser.rb:160:in `block in _process'
         2: from /opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
         1: from /opt/zammad/app/models/channel/filter/identify_sender.rb:153:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:165:in `populate_attributes!': undefined method `match?' for nil:NilClass (NoMethodError)
        16: from /opt/zammad/bin/rails:9:in `<main>'
        15: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        14: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        13: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands.rb:18:in `<main>'
        12: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/command.rb:46:in `invoke'
        11: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/command/base.rb:69:in `perform'
        10: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
         9: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
         8: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
         7: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `perform'
         6: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `eval'
         5: from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
         4: from /opt/zammad/app/models/channel/email_parser.rb:505:in `process_unprocessable_mails'
         3: from /opt/zammad/app/models/channel/email_parser.rb:505:in `glob'
         2: from /opt/zammad/app/models/channel/email_parser.rb:506:in `block in process_unprocessable_mails'
         1: from /opt/zammad/app/models/channel/email_parser.rb:118:in `process'
/opt/zammad/app/models/channel/email_parser.rb:136:in `rescue in process': #<NoMethodError: undefined method `match?' for nil:NilClass> (RuntimeError)
/opt/zammad/app/models/channel/filter/identify_sender.rb:165:in `populate_attributes!'
/opt/zammad/app/models/channel/filter/identify_sender.rb:153:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
/opt/zammad/app/models/channel/email_parser.rb:160:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:157:in `each'
/opt/zammad/app/models/channel/email_parser.rb:157:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:121:in `block in process'
/opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
/opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
/opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
/opt/zammad/vendor/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:120:in `process'
/opt/zammad/app/models/channel/email_parser.rb:506:in `block in process_unprocessable_mails'
/opt/zammad/app/models/channel/email_parser.rb:505:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:505:in `process_unprocessable_mails'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `eval'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands/runner/runner_command.rb:45:in `perform'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/command/base.rb:69:in `perform'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/command.rb:46:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/commands.rb:18:in `<main>'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/zammad/bin/rails:9:in `<main>'

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-06-17 08:36
Ensure you're running the latest Zammad 5.1 stable version.
I've never seen this error in 5.1.

**Comment by Dookalis** [comment] 2022-06-17 08:40
Update available but little different from my version
zammad/unknown 5.1.1-1655388925.3b513dc6.buster amd64 [upgradable from: 5.1.1-1651218076.e3861908.buster]

**Comment by Dookalis** [comment] 2022-06-17 08:41
I try update now and reboot server

**Comment by Dookalis** [comment] 2022-06-17 09:02
No, It didn't help me unfortunately.. Problem still exists. unprocessable mails: 9

**Comment by MrGeneration** [comment] 2022-06-17 09:14
Please provide the affected emails to `enjoy [at] zammad [dot] com`, mention this issue and to hand it to "Marcel".
I'll have a look in my next time window.

**Comment by Dookalis** [comment] 2022-06-17 10:25
We are just launching the zamad system. I deleted the emails from the unprocessable_mail folder. If the letters accumulate in it again, I will forward the letters to you. But I did not understand where and in what form?

**Comment by MrGeneration** [comment] 2022-06-17 10:50
No please don't. Cases may differ from time to time and may even be technical questions.
If you want to contact us as vendor directly with priority, you can always consider to get a support contract to enable you with that.

I'm closing this as `can't reproduce` as we can't reproduce it right now with the given information.
If you have further question about above, please create a post at the community as this repository is for bug reports only: https://community.zammad.org .

**Closed as completed by MrGeneration** 2022-06-17 10:50 UTC
Labels: can't reproduce
