### ISSUE TITLE
ERROR: invalid byte sequence for encoding "UTF8": 0xb5

### ISSUE THREAD

**Issue by Chren** [zammad/zammad#3019] opened 2020-04-16 01:57 UTC
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): docker
* Operating system: centos7
* Database + version:jjj
* Elasticsearch version:xxs
* Browser + version:chrome 80.0.3987.163

### Expected behavior:

* Fetch every income email and create ticket

### Actual behavior:
- channel is active but not fetched for 2 days
- Failed to run scheduled job 'Check Channels'. Cause: Failed to run Channel.fetch after 10 tries #<ActiveRecord::StatementInvalid: PG::CharacterNotInRepertoire: ERROR: invalid byte sequence for encoding "UTF8": 0xb5 : UPDATE "channels" SET "status_in" = $1, "last_log_in" = $2, "preferences" = $3, "updated_at" = $4 WHERE "channels"."id" = $5>

### Steps to reproduce the behavior:

* add email account, it works for the first time, then when some new emails(maybe contain Chinese characters) received, it no more works,

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-04-16 13:22
Thanks for your report.
Please provide the full traceback from within your production.log.

If this is caused during a Channel.fetch, please also provide the mail that's causing this issue if possible.

Edit: Please also provide more information on the channel configuration of the affected channel (POP3/IMAP) and what MTA (e.g. dovecot) Zammad is talking to while fetching.

**Comment by MrGeneration** [comment] 2022-03-25 21:35
Due to missing feedback and not being able to reproduce it I'm closing this issue.

**Closed as completed by MrGeneration** 2022-03-25 21:35 UTC
Labels: can't reproduce
