### ISSUE TITLE
App.ControllerForm returns no params on IE 11

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3144] opened 2020-07-31 09:04 UTC
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* App.ControllerForm.params should return params on IE11

### Actual behavior:

* params are empty in IE 11

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2020-08-04 09:46
@MrGeneration just verified that this is the actual root cause of #2609. The other issue is older and has more references to it (while being only the description of a symptom) and will be therefore used as the main issue. I'll close this one as a duplicate.

**Closed as completed by thorsteneckel** 2020-08-04 09:46 UTC
Labels: duplicate
