### ISSUE TITLE
New line when pasting links or text

### ISSUE THREAD

**Issue by enoch85** [zammad/zammad#4747] opened 2023-08-07 13:01 UTC
### Used Zammad Version

6.0.0-1686136655.9f6ee5a5.buster 

### Environment

- Installation method:package
- Operating system Ubuntu 22.04
- Database + version:  PostgreSQL 14
- Elasticsearch version: Not sure
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] Firefox 115.0.2 

### Actual behaviour

[Screencast from 2023-08-07 14:58:01.webm](https://github.com/zammad/zammad/assets/4511254/99553021-b8f9-4f9c-b759-45d0d13b13de)

### Expected behaviour

No new line on every paste.

### Steps to reproduce the behaviour

See video above.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment] 2023-08-07 13:03
Duplicate of #3716

**Closed as completed by MrGeneration** 2023-08-07 13:03 UTC
Labels: duplicate
