### ISSUE TITLE
Internal tickets (NOT articles!)

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1556] opened 2017-10-18 13:36 UTC
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

Being able to create internal tickets (NOT articles):
* without assigned customer for managing general internal issues
* with specific customer assigned but not visible to him

--> 1) a workaround is to create some internal dummy customer for assinging tickets to him - but that's just some sort of workaround and not very comfortable (also see https://github.com/zammad/zammad/issues/1345)
--> 2) internal articles are possible but no internal tickets; 1) is definitely no option for this as it gets very very chaotic this way

### Actual behavior:

no internal tickets; only internal articles

**Comment by thorsteneckel** [comment] 2018-03-01 09:45
This is actually a duplicate of #1404

**Closed by thorsteneckel** 2018-03-01 09:45 UTC
Labels: proposal
