### ISSUE TITLE
rake searchindex:rebuild defect

### ISSUE THREAD

**Issue by bc1000** [zammad/zammad#2673] opened 2019-07-17 15:17 UTC
### Infos:

* Used Zammad version: zammad-3.1.0-1562942376.fb3e2d49.centos7.x86_64
* Installation method (source, package, ..):  yum
* Operating system: Centos 7
* Database + version: 
* Elasticsearch version: elasticsearch-5.6.16
* Browser + version:

### Expected behavior:

*

### Actual behavior:

* admin user cannot see any users in zammad user management
* cannot rebuild elastic search after update to 3.1. 
elasticsearchlog throws a lot of Exceptoions like:
[2019-07-17T17:13:01,879][DEBUG][o.e.a.b.TransportBulkAction] [JWOnIkN] failed to execute pipeline [zammad279471607532] for document [zammad_production_user/_doc/300]
java.lang.IllegalArgumentException: pipeline with id [zammad279471607532] does not exist
        at org.elasticsearch.ingest.PipelineExecutionService.getPipeline(PipelineExecutionService.java:194) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.ingest.PipelineExecutionService.access$100(PipelineExecutionService.java:41) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.ingest.PipelineExecutionService$2.doRun(PipelineExecutionService.java:88) [elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) [elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.16.jar:5.6.16]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

### Steps to reproduce the behavior:

*
zammad run rake searchindex:rebuild
I, [2019-07-17T17:09:30.939735 #16296-47325589718520]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "User", "Organization", "Ticket", "KnowledgeBase::Answer::Translation"])
drop indexes...I, [2019-07-17T17:09:31.340370 #16296-47325589718520]  INFO -- : # curl -X GET "http://localhost:9200"
I, [2019-07-17T17:09:31.362396 #16296-47325589718520]  INFO -- : # 200
I, [2019-07-17T17:09:31.362686 #16296-47325589718520]  INFO -- : # curl -X DELETE "http://localhost:9200/"
I, [2019-07-17T17:09:31.366324 #16296-47325589718520]  INFO -- : # 400
done
I, [2019-07-17T17:09:31.366438 #16296-47325589718520]  INFO -- : # curl -X GET "http://localhost:9200"
I, [2019-07-17T17:09:31.368769 #16296-47325589718520]  INFO -- : # 200
delete pipeline (pipeline)... I, [2019-07-17T17:09:31.368892 #16296-47325589718520]  INFO -- : # curl -X DELETE "http://localhost:9200/_ingest/pipeline/zammad279471607532"
I, [2019-07-17T17:09:31.375240 #16296-47325589718520]  INFO -- : # 404
done
create indexes...I, [2019-07-17T17:09:31.375346 #16296-47325589718520]  INFO -- : # curl -X GET "http://localhost:9200"
I, [2019-07-17T17:09:31.377502 #16296-47325589718520]  INFO -- : # 200
rake aborted!
Can't find config setting 'es_multi_index'
/opt/zammad/app/models/setting.rb:37:in `set'
/opt/zammad/lib/tasks/search_index_es.rake:32:in `block (2 levels) in <main>'
/opt/zammad/lib/tasks/search_index_es.rake:152:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'
Tasks: TOP => searchindex:rebuild
(See full trace by running task with --trace)

zammad run rails r "Setting.get('es_multi_index')"
I, [2019-07-17T17:17:05.938369 #28932-47215094867440]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "User", "Organization", "Ticket", "KnowledgeBase::Answer::Translation"])

 zammad run rails r "Setting.set('es_multi_index', false)"
I, [2019-07-17T17:17:38.273334 #30254-47173225031180]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "User", "Organization", "Ticket", "KnowledgeBase::Answer::Translation"])
Traceback (most recent call last):
        18: from /opt/zammad/bin/rails:9:in `<main>'
        17: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        16: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        15: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
        14: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        13: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        12: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        11: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        10: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         9: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
         8: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
         7: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
         6: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         5: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         4: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         3: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
         2: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
         1: from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
/opt/zammad/app/models/setting.rb:37:in `set': Can't find config setting 'es_multi_index' (RuntimeError)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-07-17 15:26
Sorry but I believe that this is a duplicate of https://github.com/zammad/zammad/issues/2663
and also a technical questions.

For the next time, please use our community for technical questions (https://community.zammad.org)

Manually run `zammad run rake db:migrate` and try again.
Please carefully check the log output.

If you still have trouble, please consult our community. :-)

**Closed as completed by MrGeneration** 2019-07-17 15:26 UTC
Labels: duplicate, question

**Comment by bc1000** [comment] 2019-07-17 15:52
I do not see a technical question. I just want to help to fix bugs.

`zammad run rake db:migrate` fixed it, thank you
