### ISSUE TITLE
Contact with customer via e-mail mailbox 

### ISSUE THREAD

**Issue by Papelman** [zammad/zammad#1355] opened 2017-08-22 14:19 UTC
### Infos:

* Used Zammad version: 1.5.x 
* Used Zammad installation source:
* Operating system: Win10
* Browser + version: Firefox 50.0

### Expected behavior:

* Customer responses on an existing ticket->Agent gets an update e-mail with the answer of the customer
* if the agent responses on this e-mail from his email mailbox, the answer is written in the ticket in Zammad and the customer gets an e-mail with this answer
-also if the agent responses on this e-mail, he don´t gets a update e-mail from zammad

### Actual behavior:

*  if the agent responses on the update e-mail, the answer is written in the ticket in Zammad, but the customer don´t get this answer as e-mail
* the agent has to sign in zammad to send an answer to the customer

### Steps to reproduce the behavior:

* configurate in channel->email that the agent gets an email, if a customer creates a ticket
* write from customer email mailbox an email to [support@example.de] to create a ticket
* if the agent gets the email, that the ticket was updated, then response with the email mailbox system
* the customer won´t get an update

**Comment by thorsteneckel** [comment] 2020-07-29 13:20
It took a while but we've realised that this is actually a duplicate of #1203  – therefore closing now.

**Closed by thorsteneckel** 2020-07-29 13:20 UTC
Labels: feature backlog, ticket
