### ISSUE TITLE
Default locale not working on fresh install

### ISSUE THREAD

**Issue by tarreislam** [zammad/zammad#2806] opened 2019-11-11 21:38 UTC
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): https://docs.zammad.org/en/latest/install-ubuntu.html
* Operating system: ubuntu 16
* Database + version: ....
* Elasticsearch version: ...
* Browser + version: IE 11, Chrome  78.0.3904.97 (Official Build) (64-bit)

### Expected behavior:

* Default locale to be `english `or whatever is set at `settings/branding`

### Actual behavior:

* https://www.youtube.com/watch?v=U06jlgpMtQs
* https://i.imgur.com/ZXIuvKC.png

### Steps to reproduce the behavior:

1. setup fresh ubuntu 16.04
2. install zammad as described in https://docs.zammad.org/en/latest/install-ubuntu.html
2. visit `localhost/` 

### More info

```
App.i18n.detectBrowserLocale()
"ru"
```

```
console.log('window.navigator.languages', window.navigator.languages)
console.log('window.navigator.userLanguage', window.navigator.userLanguage)
console.log('window.navigator.language', window.navigator.language)

window.navigator.languages (7) ["en-US", "en-SE", "sv-SE", "sv", "en", "ru", "de"]
window.navigator.userLanguage undefined
window.navigator.language en-US
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-11-11 22:52
This is a duplicate of https://github.com/zammad/zammad/issues/2505
(as you already discovered :) )

**Closed as completed by MrGeneration** 2019-11-11 22:52 UTC
Labels: duplicate
