### ISSUE TITLE
grouping tickets by priority - wrong order

### ISSUE THREAD

**Issue by alex-LE** [zammad/zammad#2158] opened 2018-07-31 10:07 UTC
When grouping tickets by priority, the order is a bit strange.
Higher priority will be shown on the bottom.
Doesn't it make more sense to show the highes prio on top of the list?

It looks like this:

![grafik](https://user-images.githubusercontent.com/1616675/43453302-0a7a3aee-94ba-11e8-8706-bfeabef09bdd.png)

Sure, i can sort them by prio, but we want to sort them by date.

Alex

**Comment by martini** [comment] 2018-07-31 10:20
Hi @alex-LE 

thanks for the issue. Good news. It's already implemented. And available in next stable. It's a duplicate of #1213 😻

 -Martin

**Closed as completed by martini** 2018-07-31 10:20 UTC
Labels: duplicate
