### ISSUE TITLE
Inline translation hotkey broken in Edge & Chrome

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4076] opened 2022-05-03 12:50 UTC
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): all 
* Operating system: all 
* Database + version: all 
* Elasticsearch version: all 
* Browser + version: all 

### Expected behavior:

* It should be possible to change translations inline via CTRL+SHIFT+T in Edge & Chrome.

### Actual behavior:

* Translations only can be changed in Firefox/Safari.

### Steps to reproduce the behavior:

* Open ticket overview in Edge or Chrome
* Press CTRL+SHIFT+T to translate
* New tab will open, not translations.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-05-03 13:30
Duplicate of #656

**Closed as completed by MrGeneration** 2022-05-03 13:30 UTC
Labels: duplicate
