### ISSUE TITLE
"Update Database" plus restart does not work correctly

### ISSUE THREAD

**Issue by MartinBorg** [zammad/zammad#1025] opened 2017-04-28 22:51 UTC
### Infos:

* Used Zammad version: 1.5.0-1493368946.f3f4792.jessie
* Used Zammad installation source: deb
* Operating system: Debian 8
* Browser + version: n/a

### Expected behavior:

* After adding custom fields to the "User" model, clicking "Update Database", and restarting zammad, the field should be available and the information/warning
> Database Update required
>
> Changes were made that require a database update. This might take some time where the system can't be used. Please execute database changes only in a maintenance time-slot.

should be gone.

### Actual behavior:

* I'm not sure, whether the new field is really there: It is present in the model of the Rails console, but I do not see it in the UI.
* The information/warning remains. I added multiple fields, but the warning mentions only the last field added.

### Steps to reproduce the behavior:

* See above.

**Comment by MartinBorg** [comment] 2017-04-28 23:06
Question: Can I click on "Discard Changes" without any bad consequences?

**Comment by martini** [comment] 2017-04-28 23:09
> Question: Can I click on "Discard Changes" without any bad consequences?

Yes you can do. Since Zammad need to get restarted after database changes, all wanted changes get collected until you click on "Update Database".

If you press "Discard Changes" all wanted changes will get discarded.

**Comment by martini** [comment] 2017-04-28 23:12
I can't reproduce the "Actual behavior" (for my all fields are shown in the UI after "Update Database" and restarting Zammad - also the information/warning is gone). Can you give me a step by step instruction how to reproduce it? Thanks a lot!

**Comment by MartinBorg** [comment] 2017-04-28 23:38
I added a number of fields to the `User` model: `street`, `zip`, `city`, finally `country`. In between I clicked `Update Database` and restarted, just to see the fields to take effect. Everything went fine until the last field.

When I discard the changes, everything looks good, but if I create the `country` field again, I see the same behaviour as described in the original report.

**Comment by martini** [comment] 2017-04-28 23:50
Thanks for the description how to reproduce. Now I got it. Zammad is not setting change to done. Will be fixed soon!

**Comment by MartinBorg** [comment] 2017-04-28 23:51
Thanks!

Just in case this might help:

I discarded the change again, `country` does not appear in the UI of the objects administration anymore, but I can see the field in the `User` model on the rails console.

**Comment by martini** [comment] 2017-04-28 23:53
> I discarded the change again, country does not appear in the UI of the objects administration anymore, but I can see the field in the User model on the rails console.

I can confirm that (the reason is, the database change is done, but the information is not stored - this is the reason why you can see it via rails console). One more info, that behaviour is only for fields which are already existing. So if you create a new (never used field) it should work fine (until you edit it again).

**Comment by MartinBorg** [comment] 2017-04-29 00:01
I see. I don't know anything about rails (or ruby), but is there a way to remove the field safely from the console?

**Comment by martini** [comment] 2017-04-29 00:04
> I see. I don't know anything about rails (or ruby), but is there a way to remove the field safely from the console?

Sure. Just take care, that it's not existing in "Admin -> Objects -> Model" first. Then:

```
rails c
ActiveRecord::Migration.remove_column users, country
```

**Comment by MartinBorg** [comment] 2017-04-29 00:49
Thanks, this worked perfectly. (I had to prefix `users` and `country` with a colon, though.)

**Comment by martini** [comment] 2017-04-30 18:52
@MartinBorg It's fixed in develop, stable, stable-1.4, stable-1.3 and stable 1.2.

Feedback would be nice! Thanks!

**Comment by MartinBorg** [comment] 2017-05-02 12:41
Seems to work fine now, thanks again!

**Comment by martini** [comment] 2017-05-02 12:42
Thanks for feedback!

**Closed by martini** 2017-05-02 12:42 UTC
Labels: bug
