### ISSUE TITLE
untrapped exception in pythonfilter although the input works for e-mail accounts

### ISSUE THREAD

**Issue by Tealk** [zammad/zammad#3202] opened 2020-09-18 14:09 UTC
### Infos:

* Used Zammad version: 3.4.x 
* Installation method:  package
* Operating system: Debian 10

### Expected behavior:

* Registering an SMTP mail server

### Actual behavior:

* The Error message: 451 4.3.0 pymilter: untrapped exception in pythonfilter

### Steps to reproduce the behavior:

* Entering mail data in e-mail notifications in the same way as for e-mail accounts
![image](https://user-images.githubusercontent.com/12276250/93607083-27d16b00-f9c9-11ea-8bfc-5d9d387c2d03.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-09-18 14:14
Sorry but that's a technical question.
The error message you receive directly comes from your mail server.

Please use the Zammad community for technical questions or feature requests: https://community.zammad.org
You can also have a look at our support contracts in case you require business grade support: https://zammad.com/pricing#selfhosted

Closing.

**Closed as completed by MrGeneration** 2020-09-18 14:14 UTC
Labels: question

**Comment by Tealk** [comment] 2020-09-18 14:19
And why @MrGeneration  do I only get this error when I enter the mail server at "E-Mail Notification", but when I enter the same server with the same data at "E-Mail Accounts", I don't get an error message.
For me this is clearly a bug, because in one function it allows the outgoing mail server, in the other function it does not.

![image](https://user-images.githubusercontent.com/12276250/93608724-40db1b80-f9cb-11ea-945c-428b7266c6e1.png)

**Comment by MrGeneration** [comment] 2020-09-18 14:30
Please open a thread at the community.
This is **not a bug**.
