### ISSUE TITLE
Can't select users

### ISSUE THREAD

**Issue by NvL-WEAP** [zammad/zammad#2068] opened 2018-06-11 20:32 UTC
Today we've started testing Zammad to replace our hesk environment. However on my docker and standalone debian installation, we encounter the same issue.

We are not able to select a customer, when we create a new ticket. Only when we create a new user, we can select it after the creation. But were not able to find the user on the next ticket.

The users are stored and active as customers. The API request for the typeahead returns no results;

https://XXX/api/v1/search/user-organization?query=nick&_=1528748629367
```
{"assets":{},"result":[]}
```

The same thing happens if we edit a user in the user manager, and want to add a (existing) company;

https://XXX/api/v1/search/organization?query=open&limit=40&_=1528748234588
```
{"assets":{},"result":[]}
```

A request to https://XXX/api/v1/users/ does return data with the previous queried users

Were using the latest debian repository installation **zammad v. 2.5.x**

Kind regards and keep up to good work!

**Comment by NvL-WEAP** [comment] 2018-06-12 17:53
FYI, today's update (2.5.0-1528809753.920474b8.stretch) over (2.5.0-1528366750.1c3298e0.stretch) results in the same issue.

I hardly can't believe this is a problem by design, cause it would effect all the up-to-date installations. Without this working, you simply can't create a ticket (besides email import).

**Comment by thorsteneckel** [comment] 2018-06-13 08:01
Hi @NvL-WEAP  - first of all, many thanks for your participation on the Zammad open source project. We can't reproduce this on any of our instances. Even docker is working fine for us. In general it's mandatory to add a customer before creating a ticket. This works as designed. However, after creating a customer the use is available in all places (creation etc.). So im pretty sure there is something wrong with your setup. Can you verify the behavior in one of our online instances at https://zammad.com/getting-started

Regardless of the cause please use the [community board](http://community.zammad.org/) first before creating an issue if not sure if it's actually an issue affecting everyone. Otherwise everybody (more than 100 people) will receive an email for each issue (comment) which creates a lot of noise. 

If you need our commercial support you can always contact us over at support@zammad.com

I'll close this issue now. Thanks for your understanding.

**Closed as completed by thorsteneckel** 2018-06-13 08:01 UTC
Labels: can't reproduce

**Comment by NvL-WEAP** [comment] 2018-06-19 21:08
Hi, if anyone else encounters this issue; 

i have no explanation for this behaviour in the docker installation. But my debian installation had a non-functional elasticsearch, due the fact JAVA wasn't installed. After the installation of JAVA the statistics worked, but i suppose elasticsearch is used for the typeahead aswel. 

A fresh installation of zammad after elasticsearch was working properly fixed the issue.

**Comment by lukrop** [comment] 2018-07-05 16:29
I experienced the same after upgrading to 2.5. Looks like somehow the `es_url` got set. Running
`zammad run rails r "Setting.set('es_url', '')"` Solved the issue for me.

I already wondered why the report function did show some UI elements but complained about not being able to connect to elasticsearch.. It showed "Elasticsearch need to be configured!" before. After unsetting `es_url` it shows that text again and users are selectable again.

Thanks @NvL-WEAP for driving me in the right direction.
@thorsteneckel I'd guess this has to be some kind of bug in the upgrade process.

**Comment by NvL-WEAP** [comment] 2018-07-05 16:41
@lukrop glad i could point you in the right direction.

Another update from me, for somebody with similar issues :) If anybody has a working Zammad but the global search isn't working. This may be caused due a to recent elastic search version. In my case 6.5. The latest version Zammad currently supports is 5.6.10.

If you need to downgrade elasticsearch, don't forget to rebuild the zammad index afterwards.

You can find the full documentation here;
https://docs.zammad.org/en/latest/install-elasticsearch.html

**Comment by lukrop** [comment] 2018-08-21 08:23
Somehow the ``es_url`` got set again during package upgrade to ``2.6.0-1534819024.ea425d50.jessie``
