### ISSUE TITLE
Can't un-link i-doit Objects in a Ticket

### ISSUE THREAD

**Issue by PhoenixZeroDown** [zammad/zammad#1733] opened 2018-01-03 09:14 UTC
## Infos:

-     Used Zammad version: 2.2.X
-     Used Zammad installation source: DEB
-     Operating system: Debian 8
-     Browser + version: Firefox 57.0.3
-     i-doit Version 1.94 Open

## Expected behavior:

Un-link an i-doit Object in a Ticket:
Open specified Ticket, go to the i-doit Tab and delete linked i-doit object.

## Actual behavior:

If you open the same Ticket after you have deleted the i-doit Object Link, it re-appears, so once you add an i-doit Object to a Ticket, it cannot be undone.
 
## Steps to reproduce the behavior:

Link an i-doit Object an try to delete the Link

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by gwingend** [comment] 2018-02-21 21:54
This has been fixed.

**Comment by monotek** [comment] 2018-02-22 06:15
@PhoenixZeroDown
Can you verify please?

**Comment by gwingend** [comment] 2018-02-22 07:03
To be correct:
Unlinking the object in zammad works correct.

But there is still an issue on the idoit side:
If you unlink the CI from the ticket in zammad and check the unlinked CI in idoit, it still has the ticket assigned.

We already reported this as a bug and it has been verified by @martini

**Comment by thorsteneckel** [comment] 2018-02-22 08:25
Just reproduced this on our test instance. The cause for the Issue is [this line](https://github.com/zammad/zammad/blob/develop/app/controllers/integration/idoit_controller.rb#L44). Further investigation why concat was used in the first place is required.

**Comment by thorsteneckel** [comment] 2018-02-27 15:55
Hi @PhoenixZeroDown and @gwingend . This is now fixed in develop with the commit above and will be released with Zammad 2.4. Closing now.

**Closed by thorsteneckel** 2018-02-27 15:55 UTC
Labels: bug, integration

**Comment by PhoenixZeroDown** [comment] 2018-03-28 06:13
Found some spare time and gave it a quick shot. Works as a expected. Thanks a lot.
