### ISSUE TITLE
Not possible to create a ticket manually

### ISSUE THREAD

**Issue by Freev4lley** [zammad/zammad#1615] opened 2017-11-06 13:59 UTC
### Infos:

* Used Zammad version: 2.1 (OTRS migration)
* Used Zammad installation source: source
* Operating system: centos 7
* Browser + version: Firefox 56.0.2

### Expected behavior:

* Manually create a new ticket

### Actual behavior:

* After filling in the forms and clicking Create, nothing happens. Although the created task is visible on the left edge, no ticket is created. The following can be seen in the log:

I, [2017-11-06T13:43:38.733722 #20450]  INFO -- :   Rendering inline template
I, [2017-11-06T13:43:38.734417 #20450]  INFO -- :   Rendered inline template (0.6ms)
I, [2017-11-06T13:43:38.736012 #20450]  INFO -- : Completed 404 Not Found in 7ms (Views: 1.0ms | ActiveRecord: 1.9ms)
I, [2017-11-06T13:43:43.977484 #20451]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2017-11-06T13:43:43.979525 #20451]  INFO -- : fetching pop3 (removed port=110,ssl=false)
I, [2017-11-06T13:43:43.989731 #20451]  INFO -- :  - no message
I, [2017-11-06T13:43:43.989876 #20451]  INFO -- : done
I, [2017-11-06T13:44:14.035959 #20451]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2017-11-06T13:44:14.040009 #20451]  INFO -- : fetching pop3 (removed port=110,ssl=false)
I, [2017-11-06T13:44:14.050922 #20451]  INFO -- :  - no message
I, [2017-11-06T13:44:14.051087 #20451]  INFO -- : done
I, [2017-11-06T13:44:33.777071 #20451]  INFO -- : Scheduler running...
I, [2017-11-06T13:44:38.915565 #20450]  INFO -- : Started GET "/nginx_status" for 127.0.0.1 at 2017-11-06 13:44:38 +0000
I, [2017-11-06T13:44:38.920429 #20450]  INFO -- : Processing by ErrorsController#routing as TEXT
I, [2017-11-06T13:44:38.920713 #20450]  INFO -- :   Parameters: {"a"=>"nginx_status"}
E, [2017-11-06T13:44:38.925476 #20450] ERROR -- : No route matches [GET] /nginx_status (ActionController::RoutingError)

![zammad](https://user-images.githubusercontent.com/25385261/32444026-7654a94c-c301-11e7-8d6d-145f374c80fd.png)

### Steps to reproduce the behavior:

* Create new ticket and safe it

**Comment by thorsteneckel** [comment] 2017-11-06 14:04
This is a duplicate of #1175.

**Closed by thorsteneckel** 2017-11-06 14:04 UTC
