### ISSUE TITLE
Bug: Custom Group Objects Not Displayed in Signature on New Ticket Creation, Visible Only on Replies

### ISSUE THREAD

**Issue by Nico-Breiter** [zammad/zammad#4959] opened 2023-11-30 19:07 UTC
### Used Zammad Version

6.1

### Environment

- Installation method: Docker Compose
- Operating system: Debian 11
- Database + version: postgres:15.3-alpine
- Elasticsearch version: 8.8.0
- Browser + version: Edge 119.0.2151.72

### Actual behaviour

When creating tickets, the custom group objects are no longer displayed in the signature. Instead of the variable, only a "-" is output.

However, when responding to an existing ticket, these are displayed.

I think this is a bug.

### Expected behaviour

The desired behavior would be that variables are output both when creating a ticket and when responding to a ticket.

### Steps to reproduce the behaviour

1. Create a group object "signature_email_address" as a text field.
2. Enter the email in the field "signature_email_address".
3. In the signature, output the variable #{ticket.group.signature_email_address}.
4. Store the signature in the group.
5. Display the signature when creating a ticket.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2023-11-30 21:08
Duplicate of https://github.com/zammad/zammad/issues/4448? At least it's related.

**Comment by Nico-Breiter** [comment] 2023-12-03 02:09
> Duplicate of #4448? At least it's related.

Hello, yes that sounds exactly like the problem.

**Closed as completed** 2023-12-03 20:55 UTC
Labels: duplicate
