### ISSUE TITLE
problem migrating from OTRS "500 internal server error"

### ISSUE THREAD

**Issue by elmeligy** [zammad/zammad#1487] opened 2017-09-28 14:58 UTC
Dears

I am new to Zammad , tried a new installation and migrating my data from OTRS 4
installation was smooth from source
then when started the migration , I got "500 internal server error"
after further investigation , I got the following from the Zammad server

`
2.4.1 :001 > Import::OTRS.start
thread#-: Start import...
thread#-: POST: http://x.x.x.x/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Action=>"ZammadMigrator", :Key=>"xxx"}
thread#-: loading SysConfig...
thread#-: POST: http://x.x.x.x/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"SysConfig", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"xxx"}
Setting.reset_change_id: set new cache, 573080391
Setting.set(http_type, "http")
Setting.reset_change_id: set new cache, 264479151
Setting.set(organization, "Insideout Today ")
Setting.reset_change_id: set new cache, 703537370
Setting.set(system_id, "97")
Setting.reset_change_id: set new cache, 65738976
Setting.set(ticket_hook, "Ticket#")
Setting.reset_change_id: set new cache, 15387915
Setting.set(ticket_number, "Ticket::Number::Date")
Setting.reset_change_id: set new cache, 599696142
Setting.set(ticket_number_date, {:checksum=>true})
thread#-: loading DynamicField...
thread#-: POST: http://x.x.x.x/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"DynamicField", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"xxx"}
thread#-: loading State...
thread#-: POST: http://x.x.x.x/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"State", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"xxx"}
thread#-: update Ticket::State.find_by(id: 2)
thread#-: update Ticket::State.find_by(id: 7)
thread#-: update Ticket::State.find_by(id: 9)
thread#-: update Ticket::State.find_by(id: 5)
thread#-: update Ticket::State.find_by(id: 6)
thread#-: update Ticket::State.find_by(id: 4)
thread#-: update Ticket::State.find_by(id: 1)
thread#-: update Ticket::State.find_by(id: 8)
thread#-: update Ticket::State.find_by(id: 3)
thread#-: loading Priority...
thread#-: POST: http://x.x.x.x/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"Priority", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"xxx"}
thread#-: ERROR: Server Error: #<Net::HTTPInternalServerError 500 Internal Server Error readbody=true>!
`
from the OTRS server , I got the following apache logs

`
[Thu Sep 28 16:30:30.750507 2017] [:error] [pid 31998] Can't locate object method "new" via package "Kernel::System::Zammad::Migrator::Priority" at /opt/otrs/Kernel/System/ObjectManager.pm line 222.\n
[Thu Sep 28 16:31:15.957432 2017] [:error] [pid 2464] Can't locate object method "_GenericGet" via package "Kernel::System::Zammad::Migrator::Priority" at /opt/otrs/Kernel/System/Zammad/Migrator/GenericBase.pm line 88.\n
`

[production.log](https://github.com/zammad/zammad/files/1341330/production.log)

### Infos:

* Used Zammad version: 2.0.0
* Used Zammad installation source: (source)
* Operating system: Ubuntu 16.04 LTS
* Browser + version: 

### Expected behavior:

* migration to succeed

### Actual behavior:

* migration fails

### Steps to reproduce the behavior:

* new installation from source
* OTRS 4.0
* installed the 2 OTRS addons normally
* started migration as per Zammad`s installation guide
[production.log](https://github.com/zammad/zammad/files/1341339/production.log)

**Comment by NeverMin** [comment] 2017-09-28 15:12
Hi @elmeligy , please **RESET** your migrator key in otrs ASAP, because I knew it.

**Comment by thorsteneckel** [comment] 2017-10-18 14:21
Hi @elmeligy - Can you still reproduce the error? Seems that the installation of your package went somehow wrong. Please restart your apache webserver if you are using mod_perl. If you can still reproduce the error please check your package manager. Are there any messages? Please provide a screenshot if not. Thanks!

**Comment by elmeligy** [comment] 2017-10-22 11:30
hi all

I was able to fix this issue by upgrading my perl
once I am done , the migration went smooth with no errors.


-- 

Thanks and best regards,



     *Ahmed Atef*
     Infrastructure Consultant



     *InsideOut Today*

     7B Omar Shaaban,
     Nasr city, Cairo



     T +202 24149624
     F +202 26904981
     M +2 01278660199

     InsideOut.Today <http://insideout.today/>

     Twitter @atefelmeligy
     Linkedin http://eg.linkedin.com/pub/ahmed-elmeligy/3b/850/a26/



[image: Facebook] <https://www.facebook.com/insideout.today>[image: Twitter]
<https://twitter.com/InsideOut_Today>[image: LinkedIn]
<https://www.linkedin.com/company/1426808?trk=tyah&trkInfo=tarId%3A1406462313669%2Ctas%3Ainsideout%20Tod%2Cidx%3A1-1-1>[image:
Flickr] <http://www.flickr.com/photos/interactegypt>[image: foursquare]
<https://foursquare.com/v/interact-egypt/4d99d5fd744f37043f3e1058>[image:
Meetup] <http://www.meetup.com/Egypt-Startups/>[image: SlideShare]
<http://www.slideshare.net/interactegypt/presentations>[image: WordPress]
<http://blog.insideout.today/>[image: YouTube]
<https://www.youtube.com/channel/UCUaW5Dj3_DewkbHo4lFLWxA>



[image: HelixWare Signature 3]
Easy to use and reliable video hosting platform, Try out HelixWare for free
<https://helixware.tv/>[image:
https://ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif]

**Comment by thorsteneckel** [comment] 2017-10-22 14:52
Great! Thanks for your feedback. Closing.

**Closed by thorsteneckel** 2017-10-22 14:52 UTC
Labels: bug, needs verification, waiting for feedback
