### ISSUE TITLE
Creation of overview fails

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1014] opened 2017-04-28 09:35 UTC
### Infos:

* Used Zammad version: 1.6.0-1492943947.6b405ce.jessie
* Used Zammad installation source: deb develop
* Operating system: debian jessie
* Browser + version: several chrome, several firefox, ie11, edge

### Expected behavior:

* on creation of overview this should be created

### Actual behavior:

* creation of overview fails with No value found for 'roles' with id ""
![image](https://cloud.githubusercontent.com/assets/23480845/25523386/bdd4c640-2c06-11e7-978f-0c1ddd8e7e9c.png)

Overview is created anyway, but role assignment is not saved. This applies to overviews for customers, agents and admin

### Steps to reproduce the behavior:

* create new overview

**Comment by martini** [comment] 2017-04-28 13:08
@babakkazemi is it an upgrade or fresh installation?

**Comment by babakkazemi** [comment] 2017-04-28 14:03
@martini it is an upgrade, last version was 1.5.0.something :-)

**Comment by martini** [comment] 2017-04-28 14:11
@babakkazemi thanks for fast reply. And the issue still exists? Is remote login possible? I can't reproduce it. :-/

**Comment by babakkazemi** [comment] 2017-04-28 15:35
@martini I didn't update further yet. Issue exists for me.
If you like, I can give you access sometimes next week via teamviewer or do you need an own account?

**Comment by martini** [comment] 2017-05-01 10:13
JFI: Now I was able to reproduce it. Will be fixed ASAP.

**Comment by babakkazemi** [comment] 2017-05-01 10:17
Great, I didn't try to de-select "-". Works perfectly, thanks!

**Comment by martini** [comment] 2017-05-02 17:20
Fixed in development and stable branch. Also ins packages.

**Closed by martini** 2017-05-02 17:20 UTC
Labels: bug
