### ISSUE TITLE
emails gone because of error while configuring

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#243] opened 2016-10-20 16:43 UTC
Hi there, i configured a testaccount with about 100 mails in the inbox. the wizard told me that 105 mails will be deleted from the server and imported to the system. 

In the last step i got an error (sorry, didnt know wich one). The Mailaccount wasn't added and no mails where imported in the system. 

BUT: All Mails are gone from the inbox. Not good!

**Comment by thorsteneckel** [comment] 2016-10-20 19:55
Hi @Julian0o - thats really bad! Is there any chance to provide us an log file of the actions taken and maybe some error logs? You can find all the logs in the log/ directory of your zammad instance.

**Comment by Julian0o** [comment] 2016-10-20 19:57
@thorsteneckel I already deleted the container. :( 
I will try to reproduce the problem because this is a very critical issue.

**Comment by thorsteneckel** [comment] 2016-10-20 19:58
I totally agree with you! I'm awaiting your response. Thanks!

**Comment by Julian0o** [comment] 2016-10-20 20:03
hmm. i did a new configuration with the same mail settings and got no error... but this time i only had 2 mails in the inbox. Maybe the Problem occurs if you have a bunch of mails in there...

**Comment by thorsteneckel** [comment] 2016-10-20 20:04
We'll try to reproduce this as soon as possible.

**Comment by eliasp** [comment] 2016-10-21 09:41
I'd rather prefer the IMAP approach to this. OTRS had the same issue.

Instead of downloading mails and deleting them from the server, sync them and leave them in the original mailbox. Just set the `SEEN` flag after a successful ticket creation or in worst case set a custom/configurable flag.

Otherwise one can easily end up with a scenario like the one initially described in this issue, but this also makes it difficult/more complicated to account for scenarios where the originating mailbox is also used for message archiving etc.

**Comment by MrSnoozles** [comment] 2016-10-24 09:03
I figure this is quite a fundamental change but would it in general be possible to add the IMAP approach?

**Comment by Hirbod** [comment] 2017-07-05 13:54
+1 - use the IMAP SEEN Flag or any Custom flag or create a MAILBOX (INBOX.IMPORTED) and move the processed mails into that folder, instead of deleting them. It shouldn't be a breaking change. Best option would be: let the user decide. Add a checkbox (delete mails from IMAP after import or not)

**Comment by AND51** [comment] 2017-07-05 14:28
Taken from #955 


===begin quote===
@eliasp, thanks for your comment from #243! At the moment, I think setting a flag is the best way.I'd prefer a custom flag, because the SEEN-flag can be changed too easily. Imagine you want to browse through the original mails in Roundcube. Too easiliy you click a mail which is marked 'read' then. Or the other way around: You mark a mail as UNSEEN. Possibly, this would make Zammad import the same old mail, so you'll end up with 2 tickets.

Another solution might be, if Zammad compares each new/unseen mail with its own database to see if a particular mail has already been imported. So the flags wouldn't matter.
===end quote===

**Comment by besendorf** [comment] 2017-11-03 13:31
Is there any progress on this. The Flag mentioned in #955 seems like a good idea.
This would really help me in our usecase of zammad.

**Comment by hanneshal** [comment] 2017-11-16 09:35
The flag is already there. So I think we can close this?

**Comment by MrGeneration** [comment] 2022-06-08 15:09
I agree.
Administrators can decide if Zammad shall remove all mails from the mailbox or keep them (aka mark as read).
Additionally Zammad will warn administrators with big mailboxes if there's potentially happening a lot of damage.

More information about this can be found in the admin documentation: https://admin-docs.zammad.org/en/latest/channels/email/index.html.
If you need further clarification, please consult the community https://community.zammad.org.

**Closed by MrGeneration** 2022-06-08 15:09 UTC
Labels: enhancement
