### ISSUE TITLE
entries within own tree-select objects not working like created

### ISSUE THREAD

**Issue by procon-itsupport** [zammad/zammad#1686] opened 2017-12-01 13:38 UTC
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: deb-package
* Operating system: Debian 8
* Browser + version: Chrome, Firefox (both up to date)

### Expected behavior:

* selection within own created objects with Tree-Select will be shown as created at the settings

### Actual behavior & steps to reproduce the behavior:

* selection within own created objects with Tree-Select is mixed:

2 main categories with subentries are possible, for example:

- main category 1
  - main category 1, subentry 1
  - main category 1, subentry 2
  - …
- main category 2
  - main category 2, subentry 1
  - main category 2, subentry 2
  - …

If we add a third main category with subentries we can see the following effects:
- effect 1:
The subentries of the selected main category will not be displayed but of a different one.
(see at the example "Main category 3")

- effect 2:
If you select a main category to see the subentries, the subentries of the following main categories are sorted in alphabetical order mixed with subentries from other main categories.
(see at the example "Main category 4")

- effect 3:
If you create a new ticket the default is that there is a category choosen instead of an "-". Because of that the system is using a category by itself the parameter "mandatory field" is without a function. Because the system is filling out that field the service-agent is not forced to choose an entry to finish the creation of a new ticket.
	
**_Examples:_**
		
- main category  1
  - main category 1, subentry 1
  - main category 1, subentry 2
  - …
- main category 2
  - main category 2, subentry 1
  - main category 2, subentry 2
  - …
- main category **3**
  - main category **4**, subentry 1
  - main category **4**, subentry 2
  - …
- main category **4**
  - main category **2**, subentry 1
  - main category **2**, subentry 2
  - main category **3**, subentry 1
  - main category **3**, subentry 2
  - main category **4**, subentry 1
  - main category **4**, subentry 2
  - main category **5**, subentry 1
  - main category **5**, subentry 2
- main category **5**
  - main category **2**, subentry 1
  - main category **2**, subentry 2
  - …
	□ …
	□ …

**_Workaround:_**

Between the main categories and the subentries we have to create (for us) useless main categories without subentries (have to be tested for every object, no pattern found)
	
**Example for workaround:**
	
- main category 1
  - main category 1, subentry 1
  - main category 1, subentry 2
  - …
- **main category 2 (useless)**
- main category 3
  - main category 3, subentry 1
  - main category 3, subentry 2
  - …
- **main category 4 (useless)**
- main category 5
  - main category 5, subentry 1
  - main category 5, subentry 2
  - …
- main category 6
  - main category 6, subentry 1
  - main category 6, subentry 2
  - …
	□ …
	□ …

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-02-21 14:44
This is a duplicate of #1660 - But thanks for the comprehensive writeup! It made things very clear.

**Closed** 2018-02-21 16:24 UTC
Labels: duplicate
