### ISSUE TITLE
Website shows "Loading..."

### ISSUE THREAD

**Issue by Syncnaptic** [zammad/zammad#3477] opened 2021-03-26 16:36 UTC
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): package
* Operating system: ubuntu 18.04-LTS
* Database + version:
* Elasticsearch version:
* Browser + version: any

### Expected behavior:

* after Update, loading the zammad webinterface

### Actual behavior:

* Website shows the zammad-bird and "Loading..."
![Screenshot 2021-03-26 173512](https://user-images.githubusercontent.com/41864444/112663916-a831c680-8e59-11eb-8aab-8f060b5bb1ce.png)

* in the Chrome console I get:
![Screenshot 2021-03-26 172110](https://user-images.githubusercontent.com/41864444/112662237-bed71e00-8e57-11eb-86d9-67f9f233e43a.png)

### Steps to reproduce the behavior:

* After the update to 4.0, the .css file was not loading
* I then used `zammad run rake assets:precompile` after this I get the current error

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-03-26 16:40
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by b90g** [comment] 2021-04-02 19:05
Sorry to bother but upgrading from 3.6.1 to 4.0.0 i experience the same Issue.

## Infos:

    Used Zammad version: 4.0
    Installation method (source, package, ..): source
    Operating system: debian (sid)
    Database + version: mysql
    Elasticsearch version: latest
    Browser + version: Firefox

## Expected behavior:

    after Update, loading the zammad webinterface

## Actual behavior:

Displays Loading and nothing after,

was able to trigger /#login once but after login there was a white void.

Want me to open a new issue? @MrGeneration

**Comment by b90g** [comment] 2021-04-02 19:06
also precompile complains about Yarn missing.

**Comment by Syncnaptic** [comment] 2021-04-02 19:23
here is a workaround I did to get it back running, but I can't use 4.0 features like the mentions. 
https://community.zammad.org/t/website-shows-loading-after-update-to-4-0/6484

**Comment by MrGeneration** [comment] 2021-04-02 20:14
Please specify the Firefox version you're using and list, if any, the installed addons of that Browser.

**Comment by b90g** [comment] 2021-04-03 11:12
Firefox 87 in private window without addons.

also thanks Syncnaptic for the workarround, i read that allready but i thought it would be worth a bug report :)

**Comment by MrGeneration** [comment] 2021-04-15 16:15
Just for your information:
All mentioned workarounds to not help. Restarting, pulling, asset re-compiling does not fix this issue.

I finally found an environment were this appears. Still needs verification and finding the root cause of this. 
Affected number of instances is very low (from what I can tell) but draws the instance completely useless. It's not limited to a browser, I currently am guessing a specific configuration.

**Comment by MrGeneration** [comment] 2021-04-15 16:57
@Syncnaptic @b90g Please ensure that your Zammad installation is a vanilla installation. This means: No custom changes at all.

If your installation is vanilla and recompiling assets ( `rake assets:precompile; systemctl restart zammad` ) does **not**, please contact support [at] zammad [dot] com. Reference this issue and me (Marcel).

**Comment by b90g** [comment] 2021-04-16 08:06
(Ticket#1086124)

**Comment by MrGeneration** [comment] 2021-04-19 15:16
I've had a look together with @b90g and we couldn't force this issue by using the latest stable directly from Github.
Please note that our documentation does state the differences: `Get the latest stable release of Zammad here, or find the initial version at https://ftp.zammad.com.`

Versions from `ftp.zammad.com` are initial versions and may contain bugs / issues which may lead to broken updates or installations. Especially with the current release (with broken dependencies during the release day) this may be troublesome.

If you can, please use the stable zip from github and adapt the documentation commands accordingly.

Closing as `can't reproduce`

**Closed as completed by MrGeneration** 2021-04-19 15:16 UTC
Labels: can't reproduce
