### ISSUE TITLE
FeatureRequest: Mark someone insight a message

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#1144] opened 2017-05-29 06:56 UTC
Hi!

It would be great to mark a colleague insight a internal message in the way it works on twitter or facebook (@Name ..).
This should also triggers a notification for this user.

Best Regards,
David

**Comment by thorsteneckel** [comment] 2017-05-29 06:58
This is a duplicate of #208.

**Closed by thorsteneckel** 2017-05-29 06:58 UTC
