### ISSUE TITLE
"Warten auf Erinnerung" - Inconsistent timestamps

### ISSUE THREAD

**Issue by uli-heller** [zammad/zammad#2366] opened 2018-11-22 05:14 UTC
### Infos:

* Used Zammad version: 2.7.0
* Installation method (source, package, ..): source
* Operating system: ubuntu 18.04
* Database + version: mariadb
* Elasticsearch version: -
* Browser + version: chrome latest

### Screenshot:

![image](https://user-images.githubusercontent.com/1677414/48882970-a8e76780-ee1d-11e8-9db3-5f8d79f0dcea.png)

### Expected behavior:

* Current time: 6 am
* Warten auf Erinnerung: Yesterday, ~5pm
* Notification: ~5 hours ago

### Actual behavior:

* Notification: ~13 hours ago

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by uli-heller** [comment] 2018-11-22 05:35
I just realized that I received a notification email ~5 hours ago (at 1am). Maybe due to some kind of escalation mechanism?

The email says this:

* Subject: Warten auf Erinnerung erreicht! (Test-Anforderung von Uli mit erweiterter Follow-Up-Erkennung) [Ticket#26375]
* Body:
```
Zammad Helpdesk Benachrichtigung
Hallo Uli,

dieses Ticket benötigt Deine Aufmerksamkeit, warten auf Erinnerung für (Test-Anforderung von Uli mit erweiterter Follow-Up-Erkennung) mit dem Kunden "Uli Heller (daemons point GmbH)" ist erreicht.
```

So probably no escalation...

**Comment by thorsteneckel** [comment] 2018-11-22 07:44
Hi @uli-heller - I'm not sure yet if this is really a bug or a technical question. To figure this out we need so dig deeper and I need some more information from you. However, for each comment we write on this an email to more than 100 people is send. So please create a thread in the [community board](http://community.zammad.org/) with all the information in place, mention me via @thorsteneckel and I'll have a look. If it's actually a bug we will address it further.

Some information I'll need from you in the community post are:
- Can you reproduce this or was it a one time thing
- While reproducing it: Are there any negative entries in Admin -> System -> Monitoring view?
- Please provide your `log/production.log` file from this period of time (by sending it to support@zammad.com and refer to me and this issue)

Might be a duplicate of: https://github.com/zammad/zammad/issues/2157

**Comment by thorsteneckel** [comment] 2018-11-22 07:53
Oh I haven't read the #2157 in detail - this is actually a duplicate. Therefore closing now.

**Comment by mantas** [comment] 2021-08-26 12:36
Reopening because #2157 is painfully similar but technically they ain't related.

**Closed as completed** 2021-08-30 07:51 UTC
Labels: bug, verified
