### ISSUE TITLE
Required field is not required on updating tickets

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1259] opened 2017-07-16 18:45 UTC
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: 
* Operating system: any
* Browser + version: any

### Steps to reproduce
* Create a required ticket field for ticket zoom
* After creating a ticket, the required field is marked as required but actually not required

**Comment by q16marvin** [comment] 2017-09-07 14:15
any news to this?

**Comment by jjw244** [comment] 2017-09-28 20:25
Which field are you referring to @martini?

I'm running Zammad version 1.5.0 locally and have no issue with required fields as long as information is put into the field.  Can you tell me what field is "required" but is not supposed to be?

**Comment by q16marvin** [comment] 2017-10-10 07:50
hi, also in new 2.0 version this bug is there. do you know when it will be fixed?

**Comment by HappyTepid** [comment] 2017-11-01 09:23
I didn't realise my issue (#1599) was a dupe of this one, apologies. I only realised this was an issue with date fields as my other required field is a dropdown and when you make those required, the blank value at the top of the list disappears, forcing the user to select *something*.

**Comment by q16marvin** [comment] 2017-11-20 12:53
any news to this? i still cant use zammad because this "issue" :(

**Comment by q16marvin** [comment] 2018-03-27 07:44
I'm so sorry to annoy you, but is there any chance to get it fixed? this bug is now open so long and i love zammad, but i cant still use it... hope there is any way

**Comment by thorsteneckel** [comment] 2018-03-27 08:01
Dear @q16marvin ,

first of all, many thanks for your participation on the Zammad open source project.

Not usual as with proprietary software, we finance Zammad through service. So it's less money we have at our disposal to push Zammad.

If you would like to support Zammad, you can do so via Zammad Support: https://zammad.com/pricing#selfhosted

For all issues it is generally important that we tag an issue as soon as it is included in a release. This means that manual enquiry only minimizes the available resources but not the speed of implementation.

Thank you for your understanding.

**Comment by thorsteneckel** [comment] 2018-04-22 18:04
This issue is still open. Can be reproduced (with date, text etc. fields). This is caused by a missing check for required attribute over here:

https://github.com/zammad/zammad/blob/6b2e43baefdd199d8b781e9ab8c94aaa0b848194/app/assets/javascripts/app/models/_application_model.coffee#L121-L171

**Comment by SummerStorm** [comment] 2019-04-04 11:42
Fixed by 444e48e3772eb4abf8fb00170dca3d08ad65955f.

**Closed by SummerStorm** 2019-04-04 11:42 UTC
Labels: bug, object manager attribute, ticket, verified
