### ISSUE TITLE
Inactive users show up within autocomplete of the CC field

### ISSUE THREAD

**Issue by uli-heller** [zammad/zammad#2079] opened 2018-06-14 14:14 UTC
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): source
* Operating system: linux, ubuntu 18.04
* Database + version: mysql-5.7.22
* Elasticsearch version: 5.6.8
* Browser + version: chrome 67
* Please drop me a note in case you need the log file...

### Expected behavior:

* When starting to type within the CC field, autocomplete only active users

### Actual behavior:

* When starting to type within the CC field, inactive users show up within the autocomplete list

### Steps to reproduce the behavior:

* Create a user
* Mark the user "active: no"
* Create a new email ticket (bottom left: +, top right: email)
* Start typing the user's name within the CC field and watch the autocomplete show up

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-06-14 15:00
Duplicate of #721. Closing.

**Closed as completed by thorsteneckel** 2018-06-14 15:00 UTC
Labels: duplicate

**Comment by uli-heller** [comment] 2018-06-14 15:11
A duplicate, really? #721 is about ticket creation by an inactive user. This is about ticket creation of an active user. Are there any actions planned? I mean: You probably cannot prevent an inactive user from
creating tickets, since s/he might still sending emails to zammad. But it should probably be easier to fix the autocomplete. Similar to #2010 ... But never mind :(

**Comment by thorsteneckel** [comment] 2018-06-14 15:14
Thanks for response and engagement! Technically it's a duplicate :) Sorry, I should have made this clearer.

**Comment by uli-heller** [comment] 2018-06-14 15:21
Sorry for asking again, you don't have to bother answering, it is not an urgent topic.

* What are the plans related to #721? I think you have to "keep" the user and do some special actions in
  case of incoming emails, etc. I imagine this is quite complex
* Isn't it much more difficult to fix #721? For #2079, you probably have to change just a single SQL 
  statement (something like `... and active = true`, I'm guessing)

My collegues complain about the autocomplete. I think I'll write a sql script which removes the inactive users completely. Good enough for me ;) Or I look for the SQL statement and create a PR ;)
