### ISSUE TITLE
Double slash in Zammad URL on Chrome for iOS and Android

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1186] opened 2017-06-17 10:09 UTC
### Infos:

* Used Zammad version: 1.6.0, 1.6.1, 2.0.0 (but irrelevant, I must have a wrong nginx config)
* Used Zammad installation source: debian package develop
* Operating system: debian jessie
* Browser + version: Chrome for iOS and Android

### Expected behavior:

* URL should be "https://sub.domain.tld/#ticket/view"

### Actual behavior:

* URL is "http://sub.domain.tld//#ticket/view"

### Steps to reproduce the behavior:

* open our zammad installation, see double slash
I think I must have some configuration error in my /etc/nginx/sites-enabled/zammad.conf, please see attachment

Our nginx config and site config is attached
[nginx.conf.txt](https://github.com/zammad/zammad/files/1082475/nginx.conf.txt)
[zammad.conf.txt](https://github.com/zammad/zammad/files/1082476/zammad.conf.txt)

**Comment by martini** [comment] 2017-06-20 13:31
Hi @babakkazemi 

I can't find anything bad in the config. Is there an public url where I can see the actual behaviour?

 -Martin

**Comment by babakkazemi** [comment] 2017-06-21 09:44
Hi @martini 
I could set you up with an account? martin@edenhofer.de?
Babak

**Comment by martini** [comment] 2017-06-21 09:46
Yes, please!  🤠

**Comment by babakkazemi** [comment] 2017-06-21 09:59
You've got mail :neckbeard:

**Comment by babakkazemi** [comment] 2017-09-12 15:21
Anything new here? Issue still exists in build 2406
maybe connected with #959

**Comment by thorsteneckel** [comment] 2018-03-01 09:10
Sorry to say but we are not able to reproduce it. Please provide a detailed instruction on how to reproduce it and/or provide access to an affected system. Closing now.

**Comment by babakkazemi** [comment] 2018-03-01 09:23
@thorsteneckel I provided an account to @martini in June last year - if you need access, I am happy to provide you access. Problem still exists in our current installation, 2.3.0-1518189665.73199b9b.jessie

**Comment by thorsteneckel** [comment] 2018-03-01 09:25
Wasn't aware of that. Thread indicated that this did not help resolving the issue. Reopening.

**Comment by thorsteneckel** [comment] 2018-06-22 14:57
Duplicate of #223. Closing.

**Closed by thorsteneckel** 2018-06-22 14:57 UTC
Labels: can't reproduce, wontfix
