### ISSUE TITLE
Elasticsearch failed to start (Result: signal)

### ISSUE THREAD

**Issue by chrstmnn** [zammad/zammad#1768] opened 2018-01-23 11:16 UTC
Hi,

I tried to install elasticsearch for zammad on centOS 7.
Installing was fine without errors, but starting elasticsearch doesn't work.

with `systemctl status elasticsearch` I get the following:
`elasticsearch.service - Elasticsearch Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled) Active: failed (Result: signal) since Mo 2018-01-22 12:08:50 UTC; 3min 20s ago Docs: http://www.elastic.co Process: 12924 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.conf=${CONF_DIR} (code=killed, signal=KILL) Process: 12921 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS) Main PID: 12924 (code=killed, signal=KILL)`

Anyone an idea what I could do?

Thanks in advance

**Comment by muhammadn** [comment] 2018-01-23 11:19
This is a technical question and not a bug/enhancement issue. For technical questions please go to https://community.zammad.org

Closing this as this is a technical question.

**Closed by muhammadn** 2018-01-23 11:19 UTC

**Comment by martini** [comment] 2018-01-23 11:29
One more side note, `code=killed, signal=KILL` please check your available memory for elasticsearch.
