### ISSUE TITLE
Missing-attachment-warning where word "attachment" is in quote

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#387] opened 2016-11-09 14:49 UTC
I got the warning that I forgot to attach the attachement, but the word "Anhang" appeared in quoted text.  

like:
> bla bla bla Anhang bla bla bla

**Comment by dennykorsukewitz** [comment] 2019-07-26 08:09
Hi @zabarabab 
thanks for report.

The issue is also described here: #2325 
Since the other is better described, we will close this one here.

**Closed by dennykorsukewitz** 2019-07-26 08:09 UTC
Labels: UX/UI, enhancement
