### ISSUE TITLE
No new Twitter DMs

### ISSUE THREAD

**Issue by noezdev** [zammad/zammad#2381] opened 2018-11-29 20:05 UTC
Since a few days we cannot receive new twitter direct messages:

In monitor it shows:

- Channel: Twitter::Account in key:{"id"=>XYZ, "screen_name"=>"XYZ", "name"=>"XYZ"}; Can't use stream for channel (17): Twitter::Error::NotFound
- 12 failing background jobs
- Failed to run background job #1 'BackgroundJobSearchIndex' 10 time(s) with 240 attempt(s).

Twitter mentions  are not affected.

**Comment by thorsteneckel** [comment] 2018-11-30 07:20
Hi @noezdev - this is a duplicate of #2023. We're in the final phase of the required changes and the fix will be available very soon.

**Closed as completed by thorsteneckel** 2018-11-30 07:20 UTC
Labels: duplicate
