### ISSUE TITLE
Time tracking isnt working proberly

### ISSUE THREAD

**Issue by unclesam87** [zammad/zammad#2899] opened 2020-01-21 10:24 UTC
### Infos:

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04 LTS
* Database + version: MariaDB 10.x
* Elasticsearch version: 7.x
* Browser + version: Firefox 72.01

### Expected behavior:

* Track Time every time u change something at a Ticket

### Actual behavior:

*Sometimes Time Tracking wont pop up 

### Steps to reproduce the behavior:

* Close an Ticket
* Answer a Ticket

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-01-21 10:31
Please share your time accounting configuration and a more detailed step by step description on what you're doing and what you're expecting.

This sounds rather like a technical question though.

**Comment by fleverest** [comment] 2020-01-22 05:19
If you wish for time accounting to request input after **every** update on **all** tickets, make sure you have nothing in the selector configuration.

This is the default setting:
![image](https://user-images.githubusercontent.com/41366210/72867247-662b6300-3d32-11ea-986d-04dca165c377.png)
This only works for Open tickets, so if you have this then because you set the ticket to 'Closed' it will not prompt you.

If you really want time accounting for **every** ticket, just hit remove on that selector option and then save. The selector will pop up again after saving (probably an error), but it will still work as if it wasn't.

**Comment by unclesam87** [comment] 2020-01-22 14:29
When i delete the selector, it will show up again - and when i select everything i still wont get asked for every ticket at every time.

**Comment by fleverest** [comment] 2020-01-22 16:21
Delete it and select save, it will show up again but it will still work the same as you would like it to

**Comment by MrGeneration** [comment] 2020-01-27 15:55
Sorry but this is rather a technical question which is why I'm closing this issue.
If you have technical questions, please go to https://community.zammad.org 

If you believe this is an mistake please open a thread at the community and we'll re open this issue as soon as we're sure if it is a bug.

**Closed as completed by MrGeneration** 2020-01-27 15:55 UTC
Labels: question

**Comment by unclesam87** [comment] 2020-01-27 15:57
As it wont work the way fleverest described i would still guess it is an bug! 

I can delete it or selecte all and it still wont show up the right way

**Comment by MrGeneration** [comment] 2020-01-27 16:01
I cannot reproduce the behaviour your describing. Please open a thread over at the community, we'll fiddle things out there. Reference this issue to help getting through better.
