### ISSUE TITLE
New object tree always selects the highest number of options available.

### ISSUE THREAD

**Issue by doludizgin** [zammad/zammad#1775] opened 2018-01-24 13:38 UTC
### Infos:

* Used Zammad version:2.2.x
* Installation method (source, package, ..): deb
* Operating system: ubuntu 16.04
* Database + version:
* Elasticsearch version:
* Browser + version:Chrome

### Expected behavior:

* Created a new object tree select with children.

We have 2 locations - 4 floors - classrooms.

First select location, then floor ,the classroom.

### Actual behavior:

Select location, floor, classroom selection always gives the highest floor (highest number) available.

http://www.giphy.com/gifs/26CaMg5Yp7X9vNdWU

### Steps to reproduce the behavior:

https://imgur.com/a/G7FUV

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by moellert** [comment] 2018-02-06 13:18
I can confirm this behavior, but "always selects the highest number of options available" I think is not right it should be "always selects the last entry"

**Comment by thorsteneckel** [comment] 2018-02-21 14:43
This is a duplicate of #1686 - but I love your gif <3 Thanks for that!

**Comment by thorsteneckel** [comment] 2018-02-21 14:44
Oh, there is even an older issue #1660.

**Closed by thorsteneckel** 2018-02-21 14:43 UTC
