### ISSUE TITLE
Firefox: intl.accept_languages

### ISSUE THREAD

**Issue by Vanion-de** [zammad/zammad#2799] opened 2019-11-06 16:33 UTC
### Infos:

* Used Zammad version: several instances I didn't set up (I'm a user here)
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:
Firefox 70.0.1 64bit

### Expected behavior:
Before logging in the login page should greet me in the language I set as preference in the local variable intl.accept_languages. The page should take into account the order of languages I have chosen by displaying the first available language. In my case intl.accept_languages is set to "en, en-US, de, ja, cy" so I would expect a greeting in English.
![ZammadI18N](https://user-images.githubusercontent.com/9775567/68317451-6dd85580-00bb-11ea-88db-a483f5417c4f.png)

### Actual behavior:
The page greets in Japanese.

### Steps to reproduce the behavior:

- Use Firefox 70.0.x
- change intl.accept_languages in about:config to "en, en-US, de, ja, cy"
- Go to the zammat start page with a freshly started browser (just logging out of zammad is not enough, since it seems, after loggin in (and after logging out) it uses the locale in your account settings.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-11-06 16:56
This is a duplicate of https://github.com/zammad/zammad/issues/2505

**Closed as completed by MrGeneration** 2019-11-06 16:56 UTC
Labels: duplicate
