### ISSUE TITLE
Allow to paste links into article editor

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#464] opened 2016-11-25 11:11 UTC
`App.Utils.htmlCleanup()` removes all anchor (`<a>`) tags from html that gets pasted into the editor. 

We often copy/paste text containing links (like: "Please see the [documentation](https://docs.zammad.org/en/latest/) for details.") into answers. Those links now get stripped off. Any reason for this limitation?

There's a shortcut to remove links (ctrl+alt+x), but how could hyperlinks ever make it into the editor? 

It would also be helpful being able to create hyperlinks within the editor.

**Comment by MrGeneration** [comment] 2020-01-14 22:01
Sorry, but I can't reproduce this.
Can you verify that this still is an issue?

I've tested this on 3.2 and it seemed to be fixed indirectly. :-X

![issue464](https://user-images.githubusercontent.com/6549061/72386471-bea2a500-3721-11ea-901b-9ccc7aca2a90.gif)

**Comment by ggmanugg** [comment] 2020-01-21 14:56
@MrGeneration 
Is there a shortcode to create a hyperlink like there can be removed with shift ctrl x

**Comment by MrGeneration** [comment] 2020-01-21 15:03
@ggmanugg Please don't hijack issues.
The better place for technical questions is the Community: https://community.zammad.org

But, to make it short: No there is not.


---


Edit: As there has been no further feedback on this issue I suspect that this has been solved and thus am closing this.

**Closed** 2020-01-21 15:03 UTC
Labels: can't reproduce
