### ISSUE TITLE
macro which create's a note, seems to normalize the HTML

### ISSUE THREAD

**Issue by olafbuitelaar** [zammad/zammad#3430] opened 2021-02-25 17:47 UTC
### Infos:

* Used Zammad version: 3.6.50
* Installation method (source, package, ..): docker
* Operating system: centos 7/docker
* Database + version: pgsql 13.2
* Elasticsearch version: 7.10.1
* Browser + version: chrome 88.0.4324.182

### Expected behavior:

* create a macro which create's a note

### Actual behavior:

* the note is created but contains html

### Steps to reproduce the behavior:

* macro configured as;

![image](https://user-images.githubusercontent.com/12065895/109194489-bed0f900-7799-11eb-8cc8-c9c9b920776c.png)

* note is created as;
![image](https://user-images.githubusercontent.com/12065895/109194559-d60fe680-7799-11eb-94eb-e684194f0f98.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-02-25 17:52
Duplicate of #2980
Please search for the issue first.

**Closed as completed by MrGeneration** 2021-02-25 17:52 UTC
Labels: duplicate

**Comment by olafbuitelaar** [comment] 2021-02-25 17:56
sorry i did search, but probably wrong keywords
