### ISSUE TITLE
Emails don't process: wrong argument type Date (expected Date) (TypeError)

### ISSUE THREAD

**Issue by dr808** [zammad/zammad#2688] opened 2019-08-01 22:21 UTC
### Infos:

* Used Zammad version: 3.1.0 & 3.2.0 (tried both)
* Installation method (source, package, ..): source
* Operating system: Ubuntu 18.04 LTS
* Database + version: Postgres 9.6
* Elasticsearch version: 7.2.1
* Browser + version: Firefox Nightly

### Expected behavior:

* Email to be processed

### Actual behavior:

* Emails never process. If I run,
```rails r 'Channel::EmailParser.process_unprocessable_mails'``` 
then all emails quickly get processed.

As a work around, I wrote this script which runs the above rails command whenever 
"Can't process email" is printed in the logs. I just don't understand why the running the command is necessary and works every time.

```zammad-email-fixer.sh:```
```
#!/bin/bash

tail -f /opt/zammad/log/production.log | while read -r LINE

do
  if grep -Eiq "Can't process email" <(echo "$LINE"); then
    /opt/zammad/bin/rails r 'Channel::EmailParser.process_unprocessable_mails'
  fi
done
```

### Steps to reproduce the behavior:

* Send email to associated email address

Yes I'm sure this is a bug and no feature request or a general question.

Finally, I searched the issues and although I found similar issues, none that are related to this specific error message: ```wrong argument type Date (expected Date) (TypeError)```

```production.log:```
```
I, [2019-08-01T03:38:11.433801 #6474-47100211094980]  INFO -- : Scheduler running...
I, [2019-08-01T03:38:11.447724 #6474-47100211094980]  INFO -- : Running job thread for 'Check streams for Channel' (Channel.stream) status is: sleep
I, [2019-08-01T03:38:11.448073 #6474-47100211094980]  INFO -- : Running job thread for 'Generate Session data' (Sessions.jobs) status is: sleep
I, [2019-08-01T03:38:11.448117 #6474-47100211094980]  INFO -- : Running job thread for 'Import OTRS diff load' (Import::OTRS.diff_worker) status is: sleep
I, [2019-08-01T03:38:11.448153 #6474-47100211094980]  INFO -- : Running job thread for 'Check Channels' (Channel.fetch) status is: sleep
I, [2019-08-01T03:38:11.448234 #6474-47100211094980]  INFO -- : Running job thread for 'Process escalation tickets' (Ticket.process_escalation) status is: sleep
I, [2019-08-01T03:38:11.448460 #6474-47100211094980]  INFO -- : Running job thread for 'Execute jobs' (Job.run) status is: sleep
I, [2019-08-01T03:38:29.381599 #6465-47023237492900]  INFO -- : Started GET "/api/v1/monitoring/health_check?_=1564627711423" for 98.184.222.72 at 2019-08-01 03:38:29 +0000
I, [2019-08-01T03:38:29.388755 #6465-47023237492900]  INFO -- : Processing by MonitoringController#health_check as JSON
I, [2019-08-01T03:38:29.389059 #6465-47023237492900]  INFO -- :   Parameters: {"_"=>"1564627711423"}
I, [2019-08-01T03:38:29.407419 #6465-47023237492900]  INFO -- : Completed 200 OK in 18ms (Views: 0.5ms | ActiveRecord: 6.5ms)
I, [2019-08-01T03:38:31.236385 #6474-47100294620460]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2019-08-01T03:38:31.239353 #6474-47100294620460]  INFO -- : fetching imap (imap.gmail.com/email@domainusedbyme.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=false)
I, [2019-08-01T03:38:33.310570 #6474-47100294620460]  INFO -- :  - no message
I, [2019-08-01T03:38:33.310709 #6474-47100294620460]  INFO -- : done
I, [2019-08-01T03:38:59.338397 #6474-47100291569840]  INFO -- : execute Job.run (try_count 0)...
I, [2019-08-01T03:39:03.333714 #6474-47100294620460]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2019-08-01T03:39:03.336682 #6474-47100294620460]  INFO -- : fetching imap (imap.gmail.com/email@domainusedbyme.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=false)
I, [2019-08-01T03:39:04.292914 #6465-47023237489000]  INFO -- : Started GET "/api/v1/monitoring/health_check?_=1564627711424" for 98.184.222.72 at 2019-08-01 03:39:04 +0000
I, [2019-08-01T03:39:04.300411 #6465-47023237489000]  INFO -- : Processing by MonitoringController#health_check as JSON
I, [2019-08-01T03:39:04.300734 #6465-47023237489000]  INFO -- :   Parameters: {"_"=>"1564627711424"}
I, [2019-08-01T03:39:04.327454 #6465-47023237489000]  INFO -- : Completed 200 OK in 27ms (Views: 0.4ms | ActiveRecord: 13.8ms)
I, [2019-08-01T03:39:05.369918 #6474-47100294620460]  INFO -- :  - no message
I, [2019-08-01T03:39:05.370043 #6474-47100294620460]  INFO -- : done
I, [2019-08-01T03:39:10.850362 #6474-69983707203960]  INFO -- : execute Import::OTRS.diff_worker (try_count 0)...
I, [2019-08-01T03:39:11.449044 #6474-47100211094980]  INFO -- : Scheduler running...
I, [2019-08-01T03:39:11.464301 #6474-47100211094980]  INFO -- : Running job thread for 'Check streams for Channel' (Channel.stream) status is: sleep
I, [2019-08-01T03:39:11.464613 #6474-47100211094980]  INFO -- : Running job thread for 'Generate Session data' (Sessions.jobs) status is: sleep
I, [2019-08-01T03:39:11.464770 #6474-47100211094980]  INFO -- : Running job thread for 'Check Channels' (Channel.fetch) status is: sleep
I, [2019-08-01T03:39:11.464917 #6474-47100211094980]  INFO -- : Running job thread for 'Import OTRS diff load' (Import::OTRS.diff_worker) status is: sleep
I, [2019-08-01T03:39:11.465209 #6474-47100211094980]  INFO -- : Running job thread for 'Process escalation tickets' (Ticket.process_escalation) status is: sleep
I, [2019-08-01T03:39:11.465916 #6474-47100211094980]  INFO -- : Running job thread for 'Execute jobs' (Job.run) status is: sleep
I, [2019-08-01T03:39:35.400657 #6474-47100294620460]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2019-08-01T03:39:35.403546 #6474-47100294620460]  INFO -- : fetching imap (imap.gmail.com/email@domainusedbyme.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=false)
I, [2019-08-01T03:39:36.290551 #6474-47100294620460]  INFO -- :  - message 1/1
E, [2019-08-01T03:39:36.874842 #6474-47100294620460] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/180d82d2c7d7b0fdd5e05670e7319f2c.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2019-08-01T03:39:36.874915 #6474-47100294620460] ERROR -- : wrong argument type Date (expected Date) (TypeError)
/opt/zammad/.rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/fields/received_field.rb:56:in `zone'
/opt/zammad/.rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/fields/received_field.rb:56:in `formatted_date'
/opt/zammad/.rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/fields/received_field.rb:71:in `decoded'
/opt/zammad/.rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/field.rb:239:in `method_missing'
/opt/zammad/app/models/channel/email_parser.rb:502:in `rescue in block in message_header_hash'
/opt/zammad/app/models/channel/email_parser.rb:493:in `block in message_header_hash'
/opt/zammad/app/models/channel/email_parser.rb:492:in `map'
/opt/zammad/app/models/channel/email_parser.rb:492:in `message_header_hash'
/opt/zammad/app/models/channel/email_parser.rb:81:in `parse'
/opt/zammad/app/models/channel/email_parser.rb:139:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:115:in `block in process'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:114:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:254:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:211:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:211:in `fetch'
/opt/zammad/app/models/channel.rb:56:in `fetch'
/opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:286:in `eval'
/opt/zammad/app/models/scheduler.rb:286:in `_start_job'
/opt/zammad/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:237:in `loop'
/opt/zammad/app/models/scheduler.rb:237:in `block in start_job'
/opt/zammad/.rvm/gems/ruby-2.5.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2019-08-01T03:39:37.473005 #6474-47100294620460]  INFO -- : done

```

**Comment by MrGeneration** [comment] 2019-08-09 08:55
Could you please provide a sample mail that helps us to reproduce and understand this issue?
If the mail is too sensitive for public, you can also send it as attachment via mail: support [at] zammad [dot] com .

Please reference this issue if doing so. :-)

Bests

**Comment by dr808** [comment] 2019-08-12 23:00
I emailed a new email to the account and CC'd zammad support. Additionally, here are the related logs and healthcheck outputs:

Prior to sending message:
```
{
    "healthy": true,
    "message": "success",
    "token": "{redacted}"
}
```
Immediately after sending email:
```
{
    "actions": [],
    "healthy": false,
    "issues": [
        "unprocessable mails: 1"
    ],
    "message": "unprocessable mails: 1",
    "token": "{redacted}"
}
```

production.log
```
I, [2019-08-12T22:46:55.586907 #2313-70286099820720]  INFO -- : fetching imap (imap.gmail.com/email@domainusedbyme.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=false)
I, [2019-08-12T22:46:56.112848 #2313-70286099820720]  INFO -- :  - no message
I, [2019-08-12T22:46:56.112949 #2313-70286099820720]  INFO -- : done
I, [2019-08-12T22:47:26.137718 #2313-70286099820720]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2019-08-12T22:47:26.141783 #2313-70286099820720]  INFO -- : fetching imap (imap.gmail.com/email@domainusedbyme.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=false)
I, [2019-08-12T22:47:26.532434 #2313-70286099820720]  INFO -- :  - message 1/1
E, [2019-08-12T22:47:27.007292 #2313-70286099820720] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/3708941e4e58cd157af918c89c046e0c.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2019-08-12T22:47:27.007359 #2313-70286099820720] ERROR -- : wrong argument type Date (expected Date) (TypeError)
/opt/zammad/.rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/fields/received_field.rb:56:in `zone'
/opt/zammad/.rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/fields/received_field.rb:56:in `formatted_date'
/opt/zammad/.rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/fields/received_field.rb:71:in `decoded'
/opt/zammad/.rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/field.rb:239:in `method_missing'
/opt/zammad/app/models/channel/email_parser.rb:502:in `rescue in block in message_header_hash'
/opt/zammad/app/models/channel/email_parser.rb:493:in `block in message_header_hash'
/opt/zammad/app/models/channel/email_parser.rb:492:in `map'
/opt/zammad/app/models/channel/email_parser.rb:492:in `message_header_hash'
/opt/zammad/app/models/channel/email_parser.rb:81:in `parse'
/opt/zammad/app/models/channel/email_parser.rb:139:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:115:in `block in process'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:114:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:254:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:211:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:211:in `fetch'
/opt/zammad/app/models/channel.rb:56:in `fetch'
/opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:286:in `eval'
/opt/zammad/app/models/scheduler.rb:286:in `_start_job'
/opt/zammad/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:237:in `loop'
/opt/zammad/app/models/scheduler.rb:237:in `block in start_job'
/opt/zammad/.rvm/gems/ruby-2.5.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2019-08-12T22:47:28.529780 #2313-70286099820720]  INFO -- : done
I, [2019-08-12T22:47:32.451125 #2313-47072313927100]  INFO -- : Scheduler running...
I, [2019-08-12T22:47:32.464945 #2313-47072313927100]  INFO -- : Running job thread for 'Check streams for Channel' (Channel.stream) status is: sleep
I, [2019-08-12T22:47:32.465050 #2313-47072313927100]  INFO -- : Running job thread for 'Generate Session data' (Sessions.jobs) status is: sleep
I, [2019-08-12T22:47:32.465148 #2313-47072313927100]  INFO -- : Running job thread for 'Process escalation tickets' (Ticket.process_escalation) status is: sleep
I, [2019-08-12T22:47:32.465184 #2313-47072313927100]  INFO -- : Running job thread for 'Import OTRS diff load' (Import::OTRS.diff_worker) status is: sleep
I, [2019-08-12T22:47:32.465219 #2313-47072313927100]  INFO -- : Running job thread for 'Check Channels' (Channel.fetch) status is: sleep
I, [2019-08-12T22:47:32.465484 #2313-47072313927100]  INFO -- : Running job thread for 'Execute jobs' (Job.run) status is: sleep
I, [2019-08-12T22:47:58.553249 #2313-70286099820720]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2019-08-12T22:47:58.556750 #2313-70286099820720]  INFO -- : fetching imap (imap.gmail.com/email@domainusedbyme.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=false)
I, [2019-08-12T22:47:59.469136 #2313-70286099820720]  INFO -- :  - no message
I, [2019-08-12T22:47:59.469222 #2313-70286099820720]  INFO -- : done
I, [2019-08-12T22:48:04.803917 #2304-47235170423960]  INFO -- : Started GET "/api/v1/monitoring/health_check?token=sf7w3Zcivaruaf3BwJqSsl-Yzh8msrk_VuP0b7m6kxp5Ni3wzih7LQ" for 98.184.222.72 at 2019-08-12 22:48:04 +0000
I, [2019-08-12T22:48:04.811781 #2304-47235170423960]  INFO -- : Processing by MonitoringController#health_check as */*
I, [2019-08-12T22:48:04.811925 #2304-47235170423960]  INFO -- :   Parameters: {"token"=>"sf7w3Zcivaruaf3BwJqSsl-Yzh8msrk_VuP0b7m6kxp5Ni3wzih7LQ"}
I, [2019-08-12T22:48:04.836337 #2304-47235170423960]  INFO -- : Completed 200 OK in 24ms (Views: 0.7ms | ActiveRecord: 11.5ms)
I, [2019-08-12T22:48:29.494697 #2313-70286099820720]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2019-08-12T22:48:29.498747 #2313-70286099820720]  INFO -- : fetching imap (imap.gmail.com/email@domainusedbyme.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=false)
I, [2019-08-12T22:48:30.015635 #2313-70286099820720]  INFO -- :  - no message
I, [2019-08-12T22:48:30.015722 #2313-70286099820720]  INFO -- : done
I, [2019-08-12T22:48:32.466129 #2313-47072313927100]  INFO -- : Scheduler running...
I, [2019-08-12T22:48:32.480476 #2313-47072313927100]  INFO -- : Running job thread for 'Check streams for Channel' (Channel.stream) status is: sleep
I, [2019-08-12T22:48:32.480579 #2313-47072313927100]  INFO -- : Running job thread for 'Generate Session data' (Sessions.jobs) status is: sleep
I, [2019-08-12T22:48:32.480671 #2313-47072313927100]  INFO -- : Running job thread for 'Process escalation tickets' (Ticket.process_escalation) status is: sleep
I, [2019-08-12T22:48:32.480707 #2313-47072313927100]  INFO -- : Running job thread for 'Import OTRS diff load' (Import::OTRS.diff_worker) status is: sleep
I, [2019-08-12T22:48:32.480796 #2313-47072313927100]  INFO -- : Running job thread for 'Check Channels' (Channel.fetch) status is: sleep
I, [2019-08-12T22:48:32.480977 #2313-47072313927100]  INFO -- : Running job thread for 'Execute jobs' (Job.run) status is: sleep
I, [2019-08-12T22:48:33.562726 #2313-47072398055360]  INFO -- : execute Ticket.process_escalation (try_count 0)...
```

After running ```/opt/zammad/bin/rails r 'Channel::EmailParser.process_unprocessable_mails'```
```
{
    "healthy": true,
    "message": "success",
    "token": "{redacted}"
}
```

Logs for the above command:
```
I, [2019-08-12T22:50:05.226803 #2313-47072381414040]  INFO -- : execute Job.run (try_count 0)...
I, [2019-08-12T22:50:07.614193 #15089-47394707842500]  INFO -- : Setting.set('models_searchable', ["Organization", "User", "Chat::Session", "KnowledgeBase::Answer::Translation", "Ticket"])
I, [2019-08-12T22:50:09.944256 #15089-47394707842500]  INFO -- : Process email with msgid '<CAFr=R+xXGPTMc0cOW706KKjsQRoJLUpRiM=z-pffube=KLROCA@mail.gmail.com>'
I, [2019-08-12T22:50:10.081135 #15089-47394707842500]  INFO -- : Enqueued SearchIndexJob (Job ID: dada62d2-5175-42a4-b56e-48b11428a880) to DelayedJob(default) with arguments: "User", 21
I, [2019-08-12T22:50:11.114052 #15089-47394707842500]  INFO -- : Fetched image for '{support [at] zammad [dot] com}', http code: 200
I, [2019-08-12T22:50:11.297600 #15089-47394707842500]  INFO -- : Enqueued SearchIndexJob (Job ID: c7966918-41cf-4003-9d03-bb2a9815d300) to DelayedJob(default) with arguments: "User", 21
I, [2019-08-12T22:50:11.318458 #15089-47394707842500]  INFO -- : set_attributes_by_x_headers header x-zammad-ticket-customer_id found. Assign customer_id=21
I, [2019-08-12T22:50:11.366076 #15089-47394707842500]  INFO -- : Enqueued SearchIndexJob (Job ID: e41f6512-eda5-47cd-b927-46adb2196ed5) to DelayedJob(default) with arguments: "Ticket", 75
I, [2019-08-12T22:50:11.374815 #15089-47394707842500]  INFO -- : Enqueued SearchIndexJob (Job ID: 5764b7ff-69da-45eb-b5db-6ec5d2ffa7a1) to DelayedJob(default) with arguments: "User", 21
I, [2019-08-12T22:50:11.415966 #15089-47394707842500]  INFO -- : set_attributes_by_x_headers header x-zammad-article-sender found Agent
I, [2019-08-12T22:50:11.416096 #15089-47394707842500]  INFO -- : set_attributes_by_x_headers found Ticket::Article::Sender lookup for 'Agent'
I, [2019-08-12T22:50:11.422635 #15089-47394707842500]  INFO -- : set_attributes_by_x_headers assign Ticket::Article sender_id=1
I, [2019-08-12T22:50:11.422902 #15089-47394707842500]  INFO -- : set_attributes_by_x_headers header x-zammad-article-preferences found. Assign preferences={"send-auto-response"=>true, "is-auto-response"=>false}
I, [2019-08-12T22:50:11.520349 #15089-47394707842500]  INFO -- : Enqueued SearchIndexJob (Job ID: 75ff2ab3-d05e-4a8b-92b2-80f0cec6b8ea) to DelayedJob(default) with arguments: "Ticket", 75
I, [2019-08-12T22:50:11.528111 #15089-47394707842500]  INFO -- : Enqueued SearchIndexJob (Job ID: ccfe61dd-a1ce-4836-a2c1-c859f9b2776b) to DelayedJob(default) with arguments: "User", 21
I, [2019-08-12T22:50:11.600945 #15089-47394707842500]  INFO -- : Enqueued TicketUserTicketCounterJob (Job ID: fc07ee57-a2cc-4577-98f4-b0791db9cac4) to DelayedJob(default) with arguments: 21, 4
I, [2019-08-12T22:50:14.407889 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:14+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [dada62d2-5175-42a4-b56e-48b11428a880] from DelayedJob(default) with arguments: ["User", 21] (id=6521) (queue=default) RUNNING
I, [2019-08-12T22:50:14.434178 #2313-47072398430100]  INFO -- : Performing SearchIndexJob (Job ID: dada62d2-5175-42a4-b56e-48b11428a880) from DelayedJob(default) with arguments: "User", 21
I, [2019-08-12T22:50:14.466402 #2313-47072398430100]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production_user/_doc/21?pipeline=zammad261767263482" \
I, [2019-08-12T22:50:14.484234 #2313-47072398430100]  INFO -- : # 201
I, [2019-08-12T22:50:14.484438 #2313-47072398430100]  INFO -- : Performed SearchIndexJob (Job ID: dada62d2-5175-42a4-b56e-48b11428a880) from DelayedJob(default) in 50.09ms
I, [2019-08-12T22:50:14.489134 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:14+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [dada62d2-5175-42a4-b56e-48b11428a880] from DelayedJob(default) with arguments: ["User", 21] (id=6521) (queue=default) COMPLETED after 0.0811
I, [2019-08-12T22:50:14.493656 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:14+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [c7966918-41cf-4003-9d03-bb2a9815d300] from DelayedJob(default) with arguments: ["User", 21] (id=6522) (queue=default) RUNNING
I, [2019-08-12T22:50:14.517844 #2313-47072398430100]  INFO -- : Performing SearchIndexJob (Job ID: c7966918-41cf-4003-9d03-bb2a9815d300) from DelayedJob(default) with arguments: "User", 21
I, [2019-08-12T22:50:14.527092 #2313-47072398430100]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production_user/_doc/21?pipeline=zammad261767263482" \
I, [2019-08-12T22:50:14.535862 #2313-47072398430100]  INFO -- : # 200
I, [2019-08-12T22:50:14.536062 #2313-47072398430100]  INFO -- : Performed SearchIndexJob (Job ID: c7966918-41cf-4003-9d03-bb2a9815d300) from DelayedJob(default) in 18.05ms
I, [2019-08-12T22:50:14.540592 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:14+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [c7966918-41cf-4003-9d03-bb2a9815d300] from DelayedJob(default) with arguments: ["User", 21] (id=6522) (queue=default) COMPLETED after 0.0467
I, [2019-08-12T22:50:14.545144 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:14+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [e41f6512-eda5-47cd-b927-46adb2196ed5] from DelayedJob(default) with arguments: ["Ticket", 75] (id=6523) (queue=default) RUNNING
I, [2019-08-12T22:50:14.568067 #2313-47072398430100]  INFO -- : Performing SearchIndexJob (Job ID: e41f6512-eda5-47cd-b927-46adb2196ed5) from DelayedJob(default) with arguments: "Ticket", 75
I, [2019-08-12T22:50:14.613128 #2313-47072398430100]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production_ticket/_doc/75?pipeline=zammad261767263482" \
I, [2019-08-12T22:50:14.929124 #2313-47072398430100]  INFO -- : # 201
I, [2019-08-12T22:50:14.929326 #2313-47072398430100]  INFO -- : Performed SearchIndexJob (Job ID: e41f6512-eda5-47cd-b927-46adb2196ed5) from DelayedJob(default) in 361.1ms
I, [2019-08-12T22:50:14.934007 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:14+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [e41f6512-eda5-47cd-b927-46adb2196ed5] from DelayedJob(default) with arguments: ["Ticket", 75] (id=6523) (queue=default) COMPLETED after 0.3887
I, [2019-08-12T22:50:14.938250 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:14+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [5764b7ff-69da-45eb-b5db-6ec5d2ffa7a1] from DelayedJob(default) with arguments: ["User", 21] (id=6524) (queue=default) RUNNING
I, [2019-08-12T22:50:14.983266 #2313-47072398430100]  INFO -- : Performing SearchIndexJob (Job ID: 5764b7ff-69da-45eb-b5db-6ec5d2ffa7a1) from DelayedJob(default) with arguments: "User", 21
I, [2019-08-12T22:50:15.000279 #2313-47072398430100]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production_user/_doc/21?pipeline=zammad261767263482" \
I, [2019-08-12T22:50:15.012150 #2313-47072398430100]  INFO -- : # 200
I, [2019-08-12T22:50:15.012347 #2313-47072398430100]  INFO -- : Performed SearchIndexJob (Job ID: 5764b7ff-69da-45eb-b5db-6ec5d2ffa7a1) from DelayedJob(default) in 28.92ms
I, [2019-08-12T22:50:15.016922 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:15+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [5764b7ff-69da-45eb-b5db-6ec5d2ffa7a1] from DelayedJob(default) with arguments: ["User", 21] (id=6524) (queue=default) COMPLETED after 0.0785
I, [2019-08-12T22:50:15.021922 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:15+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [75ff2ab3-d05e-4a8b-92b2-80f0cec6b8ea] from DelayedJob(default) with arguments: ["Ticket", 75] (id=6525) (queue=default) RUNNING
I, [2019-08-12T22:50:15.044888 #2313-47072398430100]  INFO -- : Performing SearchIndexJob (Job ID: 75ff2ab3-d05e-4a8b-92b2-80f0cec6b8ea) from DelayedJob(default) with arguments: "Ticket", 75
I, [2019-08-12T22:50:15.081123 #2313-47072398430100]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production_ticket/_doc/75?pipeline=zammad261767263482" \
I, [2019-08-12T22:50:15.099905 #2313-47072398430100]  INFO -- : # 200
I, [2019-08-12T22:50:15.100098 #2313-47072398430100]  INFO -- : Performed SearchIndexJob (Job ID: 75ff2ab3-d05e-4a8b-92b2-80f0cec6b8ea) from DelayedJob(default) in 55.05ms
I, [2019-08-12T22:50:15.104444 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:15+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [75ff2ab3-d05e-4a8b-92b2-80f0cec6b8ea] from DelayedJob(default) with arguments: ["Ticket", 75] (id=6525) (queue=default) COMPLETED after 0.0824
I, [2019-08-12T22:50:15.108522 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:15+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [ccfe61dd-a1ce-4836-a2c1-c859f9b2776b] from DelayedJob(default) with arguments: ["User", 21] (id=6526) (queue=default) RUNNING
I, [2019-08-12T22:50:15.131667 #2313-47072398430100]  INFO -- : Performing SearchIndexJob (Job ID: ccfe61dd-a1ce-4836-a2c1-c859f9b2776b) from DelayedJob(default) with arguments: "User", 21
I, [2019-08-12T22:50:15.140385 #2313-47072398430100]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production_user/_doc/21?pipeline=zammad261767263482" \
I, [2019-08-12T22:50:15.148802 #2313-47072398430100]  INFO -- : # 200
I, [2019-08-12T22:50:15.148984 #2313-47072398430100]  INFO -- : Performed SearchIndexJob (Job ID: ccfe61dd-a1ce-4836-a2c1-c859f9b2776b) from DelayedJob(default) in 17.15ms
I, [2019-08-12T22:50:15.153358 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:15+0000: [Worker(host:zammad pid:2313)] Job SearchIndexJob [ccfe61dd-a1ce-4836-a2c1-c859f9b2776b] from DelayedJob(default) with arguments: ["User", 21] (id=6526) (queue=default) COMPLETED after 0.0447
I, [2019-08-12T22:50:15.157759 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:15+0000: [Worker(host:zammad pid:2313)] Job Transaction::BackgroundJob (id=6527) RUNNING
I, [2019-08-12T22:50:15.189496 #2313-47072398430100]  INFO -- : 2019-08-12T22:50:15+0000: [Worker(host:zammad pid:2313)] Job Transaction::BackgroundJob (id=6527) COMPLETED after 0.0315
```

**Comment by MrGeneration** [comment] 2019-08-13 09:36
Sorry, but we can't reproduce this issue. 
The E-Mail you send was processed without any issues (and is clean).
This seems to be a local installation issue which we can't cover.

Therefore I'll close this issue.

If possible, you should use package installations for productive environments to ensure Zammads working proberbly. If you have any further questions regarding this, please refer to the community: https://community.zammad.org

**Closed as completed by MrGeneration** 2019-08-13 09:36 UTC
Labels: can't reproduce
