### ISSUE TITLE
Error when changing passwords for users without email

### ISSUE THREAD

**Issue by cYzzie** [zammad/zammad#2904] opened 2020-01-23 14:11 UTC
### Infos:

* Used Zammad version: This is Zammad version 3.2.x
* Installation method (source, package, ..): unknown
* Operating system:   Debian 3.16.76-1
* Database + version: PeronaDB 5.7
* Elasticsearch version: unknown
* Browser + version: firefox 72.0.1

### Expected behavior:

Password is changed without errors

### Actual behavior:

Password is changed but an error is shown:
 {"error":"Can't use Channel::Driver::Smtp: #\u003cArgumentError: SMTP To address may not be blank: []\u003e"}

### Steps to reproduce the behavior:

Create a user without an email and change his password as the user itself

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-01-23 14:30
Yep, kinda duplicate of: https://github.com/zammad/zammad/issues/2778
But as this issue describes the cause better, we'll use this one.

Thanks for letting us know! :)

**Comment by martini** [comment] 2020-01-31 11:15
> Create a user without an email and change his password as the user itself

> Yes I'm sure this is a bug and no feature request or a general question.

@cYzzie I have a question because I was not able to reproduce this issue by following your steps.

What URL did you use to change the users password?

**Comment by martini** [comment] 2020-01-31 11:26
@cYzzie Now I was able to reproduce. Please ignore my question.

**Comment by martini** [comment] 2020-01-31 11:38
Note, it also happens in background jobs for sending new device notifications if current session user has no email address:

```
E, [2020-01-30T15:45:35.349191 #23730-83416860] ERROR -- : Error performing UserDeviceLogJob (Job ID: 258f4f9d-102b-4105-800b-500b212ee068) from DelayedJob(default) in 91.46ms: RuntimeError (Can't use Channel::Driver::Sendmail: #<ArgumentError: SMTP To address may not be blank: []>):
/XXX/app/models/channel.rb:268:in `rescue in deliver'
/XXX/app/models/channel.rb:254:in `deliver'
/XXX/lib/notification_factory/mailer.rb:142:in `send'
/XXX/lib/notification_factory/mailer.rb:195:in `notification'
/XXX/app/models/user_device.rb:207:in `notification_send'
/XXX/app/models/user_device.rb:135:in `add'
/XXX/app/jobs/user_device_log_job.rb:3:in `perform'
```

**Closed as completed** 2020-02-19 14:58 UTC
Labels: bug, channel, verified
