### ISSUE TITLE
Unprocessable mail - Invalid header name syntax - index can not be built / elasticsearch crashes

### ISSUE THREAD

**Issue by domipoppe** [zammad/zammad#4499] opened 2023-02-17 15:14 UTC
### Used Zammad Version

5.3.1-1675949277.e156cd3e.focal 

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 20.04.5 LTS
- Database + version: PostgreSQL 12.13
- Elasticsearch version: 7.17.9
- Browser + version: Firefox 110.0 (64-Bit)

### Actual behaviour

Important part:
```
"ERROR: #<NoMethodError: undefined method `match?' for nil:NilClass>"
Ignoring unparsable header "\xEF\xBB\xBFFrom: Vergleichs Guru  <kundenservice@vergleichs-guru.com>": invalid header name syntax: "\xEF\xBB\xBFFrom"
```

Here the CLI error when I try to rebuild the index:
[error-index.txt](https://github.com/zammad/zammad/files/10768116/error-index.txt)

The mail:
[4fee281bb273a6ff5c8a9a7a6db89e31.txt](https://github.com/zammad/zammad/files/10768162/4fee281bb273a6ff5c8a9a7a6db89e31.txt)

### Expected behaviour

The mail is being processed or not but the index is built without crashing elasticsearch.

### Steps to reproduce the behaviour

Use the e-mail above

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by YetAnotherGerrit** [comment] 2023-02-17 15:42
\xEF\xBB\xBF are the BOM-markers of UTF8-BOM:
https://en.wikipedia.org/wiki/Byte_order_mark

Can you check the locale of your system?
https://docs.zammad.org/en/latest/install/package.html#ensure-correct-locale

**Comment by domipoppe** [comment] 2023-02-17 17:22
@YetAnotherGerrit 

Hey, I've just checked it:
LANG=en_US.UTF-8

I've also regenerated the locales with `locale-gen en_US.UTF-8` just to be sure - and restarted elastic & did start the searchindex build command. I still get the issue. The mails are in German language, could that be an issue?

Regards.

**Comment by t-shehab** [comment] 2023-04-21 13:22
Hey @domipoppe,

We are unable to reproduce the behaviour you're describing. While it is true that the email you're referencing cannot be imported by Zammad, this in no way crashes elasticsearch in our test-instances. Nor does it prevent the search index from being built or rebuilt.

### The reason the email cannot be imported is the following:

If you open the email you provided in a text editor that will show unicode characters (I used neovim), you will see unicode character "U+FEFF" (ZERO WIDTH NO-BREAK SPACE) immediately before the FROM header of the email. This breaks the accepted syntax of the FROM header, which leads to Zammad not importing the email. This is expected.

 Usually, mailservers should recognize broken mails like this beforehand. Why this didn't happen here, I cannot tell you.

The fact that elasticsearch crashes on your system at a similar time could be mere coincidence.

I will therefore close this issue.

**Closed as completed by t-shehab** 2023-04-21 13:22 UTC
Labels: can't reproduce
