### ISSUE TITLE
Inline translation not working in Microsoft Edge

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4708] opened 2023-07-06 06:23 UTC
### Used Zammad Version

6.0

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 11
- Database + version:  postgresql-13
- Elasticsearch version: 7.17.11
- Browser + version: Microsoft Edge 114.0.1823.67

### Actual behaviour

When trying to access the inline translation a new browser tab is opened.

### Expected behaviour

Inline translation works with the shortcut that is listed within Zammad.

### Steps to reproduce the behaviour

Use Microsoft Edge and try to use the inline translation.

### Support Ticket

Ticket#10127299, Ticket#10128509, Ticket#10128996, Ticket#10128997, Ticket#10131676, Ticket#10132647, Ticket#10132660, Ticket#10132661

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment] 2023-07-06 06:25
IMO its a duplicate of https://github.com/zammad/zammad/issues/656

-> We need to find shortcuts which work on all os & browsers

**Comment by YetAnotherGerrit** [comment] 2023-07-06 06:37
They do not need to be the same for all browsers in my opinion. They aren't the same for all OSes. We should not wait for an enhancement like in the linked issue, to fix this bug.

**Comment by martini** [comment] 2023-07-06 10:16
> They do not need to be the same for all browsers in my opinion. They aren't the same for all OSes. We should not wait for an enhancement like in the linked issue, to fix this bug.

1) Additional information: IMO on Microsoft Edge, `ctrl+shift+t` will be catched from browser/os. IMO it's not possible to overwrite this within Zammad.

2) Question: I did not get the idea how to fix it (only by finding combinations which works overall).  -> Is your proposal to find combinations which works on browsers/os couples and to just have different shortcuts on different browsers/os couples?

**Comment by YetAnotherGerrit** [comment] 2023-07-06 10:23
In my opinion, we should not try to overwrite browser shortcuts but find shortcuts that don't collide with the existing browser shortcuts.

From my perspective, it is fine, that we don't have the same shortcuts for all browsers. So it can be ctrl+shift+t in Firefox and e.g. alt+shift+t in Chrome/Edge; or something totally different.

So to fix this bug, we should use a shortcut in Chromium-based browsers that is not already used by Chromium-based browsers.

**Comment by forreggbor** [comment] 2023-09-07 06:28
IMO using different shortcuts makes the users confused. Using the same shortcut is more logic. I use different browsers and personally I prefer to remember only one shortcut.
Actually CTRL+SHIFT+T opens the last closed tab on Chromium based browsers and in Firefox as well.

**Comment by Mirtaaa** [comment] 2024-02-05 08:28
Will be solved with the following issue: https://github.com/orgs/zammad/projects/4/views/18?pane=issue&itemId=41231220

**Closed as completed by Mirtaaa** 2024-02-05 08:28 UTC
Labels: bug, translation, verified, prioritised by payment, frontend
