### ISSUE TITLE
custom domain for knowledge base not working

### ISSUE THREAD

**Issue by beatkind** [zammad/zammad#2759] opened 2019-10-01 09:42 UTC
### Infos:

* Used Zammad version: 3.1.0-1569535934
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.6 LTS - 4.4.0-161-generic
* Database + version: Postgresql 9.5.19
* Elasticsearch version: 5.6.16
* Browser + version: Chrome 77.0.3865.90

### Expected behavior:

* The public knowledge base should be reached by the custom domain and the links to articles should be working correctly

### Actual behavior:

* the public knowledge base can be reached by the custom domain but the symlinks to articels are not updated, they have *custom domain*/help

### Steps to reproduce the behavior:

* Set a custom domain for the knowledge base in the settings and publish the knowledge base

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-10-01 09:47
This is a duplicate of issue:
https://github.com/zammad/zammad/issues/2627

The above issue also holds information that might help you in fiddling around this issue.
Closing now.

**Closed as completed by MrGeneration** 2019-10-01 09:47 UTC
Labels: duplicate
