### ISSUE TITLE
Autocomplete agent/customer adding mail-note in ticket

### ISSUE THREAD

**Issue by donbertl** [zammad/zammad#1544] opened 2017-10-18 12:12 UTC
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...) Debian Jessie .deb-Package
* Operating system: Windows 8.1
* Browser + version: IE 11 / Firefox 50.x

### Expected behavior:

* As soon as you tip in the "to"-field autocomplete should happen like in creating a new ticket and adding a customer

### Actual behavior:

* nothing happens

### Steps to reproduce the behavior:

* add note to existing ticket and change symbol to mail
* write in new field "to"
![zammad-ticket-note](https://user-images.githubusercontent.com/32896262/31717879-07a2a690-b40e-11e7-869d-60bb35d1dc26.jpg)

Thanks
Robert

**Comment by thorsteneckel** [comment] 2017-10-18 12:14
Duplicate of #338

**Closed by thorsteneckel** 2017-10-18 12:14 UTC
