### ISSUE TITLE
There's no refresh on overviews if tickets escalate.

### ISSUE THREAD

**Issue by Franselbaer** [zammad/zammad#2077] opened 2018-06-14 09:00 UTC
### Infos:

* Used Zammad version: 2.4.x is shown on version page
* Installation method (source, package, ..): Docker via docker-compose.yml out of repo
* Operating system: Ubuntu
* Database + version: That what came with the docker-compose.yml
* Elasticsearch version: That what came with the docker-compose.yml
* Browser + version: Chrome 66.0.3359.181

### Expected behavior:

* Overview collumn should refresh its data frequently (setupable).

### Actual behavior:

* Overview column does not update its content in some cases. Especially when a ticket escalates I get an info popup but the overview column still shows "escalated 0" even if i click around. Only if I reload the whole page the column is updated.

### Steps to reproduce the behavior:

* Just let a ticket automatically escalate and klick around in ticketsystem without reloading the whole page.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-06-14 09:04
Hi @Franselbaer - could you please verify first that the error still occurs in the latest version of Zammad 2.5 ?

**Comment by Franselbaer** [comment] 2018-06-14 10:26
Okay.

* Initiated a `git pull && docker-compose pull && docker-compose down && docker-compose up -d`.
* Now it is version 2.5.x.
* Creating a ticket...

**Comment by Franselbaer** [comment] 2018-06-14 10:31
* Ticket arrived in system. Waiting for auto-escalation.
![bildschirmfoto 2018-06-14 um 12 30 40](https://user-images.githubusercontent.com/11044625/41407163-e515150e-6fce-11e8-9663-928179d5c178.png)

**Comment by thorsteneckel** [comment] 2018-06-14 10:34
Hi @Franselbaer thanks for your frequent updates. Please note that each comment will send an email to everybody who's watching this repository - currently 107 people. Would be great to get one summary at the end of your trial 👍

**Comment by Franselbaer** [comment] 2018-06-15 06:41
# Outcome brief
Since I updated to 2.5.x I did some tests. But it seems tickets do not escalate anymore.
# What I did:
* Setup first response SLA to 00:05
* Created a ticket
* Waited...
# Result
* Ticket is now 16 minutes old.
* No popup
* Escalated Overview still 0
* If I open the ticket it does not has this red "escalated since xy minutes" text
* Even if I reload the whole page
![bildschirmfoto 2018-06-15 um 08 38 57](https://user-images.githubusercontent.com/11044625/41453860-99d2c876-7077-11e8-8368-c6de30393721.png)
# Related Logs
The scheduler for ticket escalation seems to be running.
``` 
zammad-scheduler_1      | I, [2018-06-15T08:36:40.855226 #1]  INFO -- : Scheduler running...
zammad-scheduler_1      | I, [2018-06-15T08:36:40.862129 #1]  INFO -- : Running job thread for 'Check Channels' (Channel.fetch) status is: sleep
zammad-scheduler_1      | I, [2018-06-15T08:36:40.863011 #1]  INFO -- : Running job thread for 'Process escalation tickets' (Ticket.process_escalation) status is: sleep
zammad-scheduler_1      | I, [2018-06-15T08:36:40.863111 #1]  INFO -- : Running job thread for 'Check streams for Channel' (Channel.stream) status is: sleep
zammad-scheduler_1      | I, [2018-06-15T08:36:40.863235 #1]  INFO -- : Running job thread for 'Generate Session data' (Sessions.jobs) status is: sleep
zammad-scheduler_1      | I, [2018-06-15T08:36:40.863611 #1]  INFO -- : Running job thread for 'Import OTRS diff load' (Import::OTRS.diff_worker) status is: sleep
zammad-scheduler_1      | I, [2018-06-15T08:36:40.864850 #1]  INFO -- : Running job thread for 'Execute jobs' (Job.run) status is: sleep
zammad-scheduler_1      | I, [2018-06-15T08:36:50.888844 #1]  INFO -- : execute Channel.fetch (try_count 0)...
zammad-scheduler_1      | I, [2018-06-15T08:36:50.891862 #1]  INFO -- : fetching pop3 (172.16.100.5/support port=110,ssl=false)
zammad-scheduler_1      | I, [2018-06-15T08:36:51.592015 #1]  INFO -- :  - no message
zammad-scheduler_1      | I, [2018-06-15T08:36:51.592125 #1]  INFO -- : done
```

**Comment by Franselbaer** [comment] 2018-06-15 07:18
# Some more outcome
* I played around a bit and it seems I had a broken calendar.
* After a while i created a new calendar and set it as default.
* Then the scheduler became active.
* Now the ticket shows the "no response after xy hours" SLA escalation
starting in 11 Minutes
* Got a popup 
* Ticket went red
* Escalated Overview still 0

![zammad_helpdesk_-_offen](https://user-images.githubusercontent.com/11044625/41455312-f7f91888-707c-11e8-9885-cccbfc47bb6b.png)

**Comment by thorsteneckel** [comment] 2018-08-20 14:32
Hi @Franselbaer - we're unable to reproduce this in the latest `stable` branch:
![escalation_overview](https://user-images.githubusercontent.com/3873515/44346498-5f8e2180-a496-11e8-93b1-224c50a6b7a6.gif)

Could you please re-try it in your Zammad (after updating it to at least 2.6)? If you're still able to reproduce it please create a [free online instance](https://www.zammad.com/getting-started) and try to reproduce it there, too. If you're able to reproduce it please post the name of the instance and the steps you performed to reproduce it here. Closing now.

**Closed as completed by thorsteneckel** 2018-08-20 14:32 UTC
Labels: can't reproduce
