### ISSUE TITLE
When opening overview configuration via "options"-button more than one modal opens up

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5243] opened 2024-06-27 08:06 UTC
### Used Zammad Version

6.4.0-alpha-1719464747.79d51814.bookworm
6.4.0-alpha-1719381239.b73cd499.bookworm

### Environment

- Installation method: unknown
- Operating system (if you're unsure: `cat /etc/os-release` ): unknown
- Database + version:  PSQL
- Elasticsearch version: unknown
- Browser + version: MS Edge

### Actual behaviour

When clicking the "options" button in the #ticket/view itself, several modal dialogs pop up at the same time for several overviews. The original overview is also not visible in the background anymore:

![image](https://github.com/zammad/zammad/assets/97293098/78903973-db08-40df-a4ee-b474e2dcc0e9)

### Expected behaviour

When clicking the "options" button on the #ticket/view the modal to configure that overview pops up as usual.

### Steps to reproduce the behaviour

Have the `admin.overviews` permission and edit an overview not from the admin interface, but from the overview itself. Click around in the overviews a bit, then click the "options" button. Maybe try several times. But at one point it happens.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YetAnotherGerrit** [comment] 2024-07-02 10:19
The bug has now arrived in stable!

**Comment by rolfschmidt** [comment] 2024-07-02 10:39
This should be fixed since yesterday, please verify with latest stable. Regression fix: https://github.com/zammad/zammad/commit/80954e2ca9dd056d34bc6961a7045128854615f5

Please reopen, if the issue still exists for you after the update.

**Closed as completed** 2024-07-03 07:39 UTC
Labels: bug, waiting for feedback, overviews, verified
