### ISSUE TITLE
Zammad deletes HTML encoded spaces from URL

### ISSUE THREAD

**Issue by deadda7a** [zammad/zammad#1714] opened 2017-12-14 10:11 UTC
### Infos:

* Used Zammad version: 2.2.0-1513237090.47a1bb76.xe
* Installation method (source, package, ..): deb
* Operating system: Ubuntu 16.04.3
* Database + version: 
* Elasticsearch version: 5.6.5
* Browser + version: Google Chrome 63.0.3239.84 on Fedora 27, Google Chrome on Windows & Mac OS X, Safari on Mac OS X, Firefox on Windows

### Expected behavior:

* Insert the URL http://scs.at/news-detail/SCS%20VIP%20Lounge in a Ticket (No, we cannot fix their CMS to not serve URLs without spaces - sadly.)
* Click on the URL
![1](https://user-images.githubusercontent.com/10240838/33986926-6bf6481c-e0bf-11e7-9030-9eb132b381b2.png)
* The webpage opens

### Actual behavior:

* Insert the URL in a Ticket
* Click on the URL
* The Link is the URL without the spaces (neither encoded nor non-encoded spaces)
![2](https://user-images.githubusercontent.com/10240838/33986952-80b6a616-e0bf-11e7-8166-28d7a003c1a2.png)

### Steps to reproduce the behavior:

* See "Actual behavior"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment] 2017-12-14 13:21
Hi @deadda7a 
this works just fine. We testet several URLs using spaces and other URL encoded characters. 

![helpdesk](https://user-images.githubusercontent.com/804939/33994207-e2209c8a-e0d9-11e7-8206-818eab0e0cd7.png)

Maybe your link "source" is an issue. We had problems when pasting from excel / word with "non-visible" characters, which then will be kicked by Zammad.

Regards

**Comment by deadda7a** [comment] 2017-12-14 13:24
That is very strange. I tried different sources - the address bar of the Browser, Plan Text Emails and LibreOffice.
And it only affects spaces, other characters will get decoded in the URL.

**Comment by thorsteneckel** [comment] 2018-05-09 18:29
Hi @deadda7a - can you still reproduce this in the latest version of Zammad? If so, please retry on a free https://zammad.com/getting-started instance and post us the name. Thanks!

**Comment by deadda7a** [comment] 2018-05-14 14:33
Hi!
This is still an issue. Sorry for the delayed answer, but I don't work at the company this bug first happened anymore so I had to ask my ex-colleagues.
I spun up a test instance: https://test-orga-for-github.zammad.com/#ticket/zoom/2

**Comment by thorsteneckel** [comment] 2018-05-17 08:31
Hi @deadda7a - Thanks a lot for providing the test instance! I was able to reproduce the error and we will now start digging deeper. I already deleted the instance since it's not needed anymore. We'll let you know about any updates.

**Comment by thorsteneckel** [comment] 2018-05-17 08:38
@deadda7a this is kind of embarrassing but actually I wasn't able to reproduce it 🤦‍♂️ I just copied your broken link... Since I was so eager cleaning up I now have no access to the instance anymore... Could you please create another instance and use this link here: `http://scs.at/news-detail/SCS%20VIP%20Lounge`. Thanks!

**Comment by deadda7a** [comment] 2018-05-17 08:45
Ahahaha!
I tried it with your Link and it works but why?
I tried copying the link to the terminal before opening this issue so it would not have any weird html formatting and just be plain text, like your link.

https://test-orga-for-github1.zammad.com/#ticket/zoom/2

**Comment by thorsteneckel** [comment] 2018-05-17 09:05
Thanks - Ok now I got it! I can reproduce this in stable. The good news is: This is already fixed in develop. But I don't know which commit fixed it 🤓 However, I'll mark it as fixed.

The difference between my link and the terminal/editor/etc. source is that the later are already detected as links by the OS. My link is marked as plain text. Actually I don't know why the terminal and editor detect these as links.

I'll remove the online instance now... :neckbeard:

**Closed by thorsteneckel** 2018-05-17 09:05 UTC
Labels: bug, frontend, needs verification, waiting for feedback
