### ISSUE TITLE
Inline-Translation in Google Chrome (Win) is not working

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#1766] opened 2018-01-22 15:26 UTC
### Infos:

* Used Zammad version: 2.2.0
* Installation method (source, package, ..): package
* Operating system: openSUSE 42.3
* Database + version: PostgreSQL 9.6-1.1
* Elasticsearch version: 5.6.6
* Browser + version: Google Chrome 63.0.3239.132 (Win)

### Expected behavior:

* Press SHIFT+CTRL+t to enable inline translation
* Inline Translation will get activated (and blocks are marked so you can start translating)

### Actual behavior:

* SHIFT+CTRL+t opens a new recent closed Tab

### Steps to reproduce the behavior:

* Open Chrome
* open some random Tabs (like youtube.com and google.com) and a Tab with Zammad
* Close the random Tabs
* Login into Zammad
* Press SHIFT + CTRL + T

### Further Notes

This is actual a correct behaviour of Google Chrome, strangely Firefox (57.0.4) should do the same but does not at my end. The Shortcut should be changed.

**This does only happen if I don't open/close any other Tabs on Chrome - this Shortcut functions in case I have a stand alone windows (e.g. Private Browsing)**

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment] 2018-01-22 16:03
@MrGeneration Have you tried Ctrl+Alt+T instead of "Shift"? As that is the way to enable inline translation.

**Comment by MrGeneration** [comment] 2018-01-22 16:15
@muhammadn  Hey just tried and does not work (on Firefox and Chrome). My Zammad-Installation tells me "shift ctrl t Aktivieren/deaktivieren von Inline-Übersetzungen".

![image](https://user-images.githubusercontent.com/6549061/35230984-df20573c-ff97-11e7-9245-e8d45ada64dd.png)

**Comment by thorsteneckel** [comment] 2018-03-01 10:43
This is actually a duplicate of #656. Closing therefore.

**Closed by thorsteneckel** 2018-03-01 10:43 UTC
