### ISSUE TITLE
SMTP-Attachments missing when using the API under high load

### ISSUE THREAD

**Issue by kevin-olbrich** [zammad/zammad#2991] opened 2020-03-26 15:26 UTC
### Infos:

* Used Zammad version: 3.3.0 (1584681054.9aad793a.centos7)
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: PG 9.2.24 (2.el7_7)
* Elasticsearch version: 7.6.1
* Browser + version: API
* Ticket#1086521

### Expected behavior:

* E-Mail should be delivered with attachment.

### Actual behavior:

Under high load (300 new tickets, one after another [blocking task, non async]) when using the API, some generated emails lack their attachments when they are sent using SMTP. Inside Zammad all attachments are available. When forwarding them from inside the GUI they are correctly attached.

I tried using "zammad config:set WEB_CONCURRENCY=10" and "zammad config:set WEB_CONCURRENCY=1" - no difference. [PG max connections adjusted to 2000].

Issue was not present with "zammad config:set WEB_CONCURRENCY=1" and Zammad 3.2.0. Some time ago, < 3.x I had the same issue.

I use local delivery. Zammad can simply drop the message to local postfix and it will take care of transport.

### Steps to reproduce the behavior:

* Send lots of API requests one after another (short text, pdf attachment 200kb). Some of them will lack attachments when the customer receives it (which I can confirm when looking at mail journal).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-03-26 15:59
Can you please also let us know what your system configuration looks like? Especially crucial here is:

* storage type (HDD/SSD)
* number of cores and their base clock
* memory assigned to the machine

--- 

A sample payload that holds redacted information would be amazing too.
This will help us greatly to understand your case.

Please also attach your production-log of the moment you're hammering Zammad with requests.

Also, please ensure that your local MTA doesn't loose the attachment (I don't want to blame it, but if you already had this issue and it "magically comes back" it sounds a bit odd. :x

**Comment by kevin-olbrich** [comment] 2020-03-26 16:15
Machine runs all flash (ceph ontop of DC NVMe's), with 10G RAM and four cores (2,13GHz).
Spectre / Meltdown etc. protections are disabled both on the VM and the hypervisor.

We only have high load once per month (invoices). Last month we had Zammad 3.2.0, which I upgraded last week.

With normal load this week (max 10 requests, v3.3.0) I did not notice this issue.
This was the first mass sending after the upgrade.

I've checked postfix logs. It tells me, the mail was successfully delivered with 3250 bytes, which means, no attachment. So far no error in the logs.

I checked the prod log, especially the ticket id. For example there is this:
```
I, [2020-03-26T15:44:01.995353 #2092-70019916534020]  INFO -- : Started POST "/api/v1/tickets/" for 185.118.X.X at 2020-03-26 15:44:01 +0100
I, [2020-03-26T15:44:02.007484 #2092-70019916534020]  INFO -- : Processing by TicketsController#create as JSON
I, [2020-03-26T15:44:02.007763 #2092-70019916534020]  INFO -- :   Parameters: {"title"=>"Rechnung 60023370 - Example Company", "group"=>10, "state_id"=>4, "owner_id"=>6, "priority_id"=>3, "customer_id"=>"guess:confidential@example.com", "article"=>{"subject"=>"Rechnung 60023370 - Example Company", "body"=>"[FILTERED]", "type"=>"note", "internal"=>false}, "note"=>"Rechnung 60023370 - Example Company"}
I, [2020-03-26T15:44:02.053730 #1206-47151775402560]  INFO -- : Performed TicketArticleCommunicateEmailJob (Job ID: 4d14352f-84fd-42f3-b48d-6fe49f83d9aa) from DelayedJob(default) in 686.02ms

[...]

I, [2020-03-26T15:44:03.511339 #2092-47448730488880]  INFO -- : Started POST "/api/v1/ticket_articles/" for 185.118.X.X at 2020-03-26 15:44:03 +0100
I, [2020-03-26T15:44:03.520104 #2092-47448730488880]  INFO -- : Processing by TicketArticlesController#create as JSON
I, [2020-03-26T15:44:03.520261 #2092-47448730488880]  INFO -- :   Parameters: {"ticket_id"=>30247, "to"=>"confidential@example.com", "subject"=>"Rechnung 60023370 - Example Company", "body"=>"[FILTERED]", "content_type"=>"text/plain", "type"=>"email", "internal"=>false, "attachments"=>[{"filename"=>"X_Rechnung_60023370.pdf", "data"=>"[FILTERED]", "mime-type"=>"application/pdf"}]}


```

**Comment by kevin-olbrich** [comment] 2020-03-27 17:20
I've just met the same problem again. Yesterday I set "WEB_CONCURRENCY=1", today I restarted the whole VM. New mass mailing, 1-2/10 attachments are missing.

**Comment by kevin-olbrich** [comment] 2020-03-28 10:17
The logs do not contain anything interesting.
I will try to migrate our setup to Debian Buster (was a long time todo) on an even faster machine.

**Comment by kevin-olbrich** [comment] 2020-03-30 15:06
Ok, OS has been changed to Debian Buster with PG 11 vs. 9.
Also, local IO performance is much much higher than before.

Still the same issue. Just had to send an email with four parts (4 zip files). First is missing attachment.

**Comment by kevin-olbrich** [comment] 2020-04-27 12:11
Another month, another try. If I delay each submission by 1s, less attachments are missing (1 or 2 per 100). The VM itself is not under high load. I suspect, a higher delay will bring this down to even less missing attachments.

I temporary made sure the connection is not re-used by exit'ing each loop and run it in bash using while true. Each submission (creating ticket, creating article with attachment type mail) is using a new connection.

**Comment by thorsteneckel** [comment] 2020-04-27 12:14
Hey @kevin-olbrich ! Can you reproduce this on one of our [free hosted instances](https://zammad.com/getting-started)?

**Comment by kevin-olbrich** [comment] 2021-05-04 11:25
This is still broken in "4.0.0-1619855763.0df0f9d4.buster".
I'm currently spinning up a test instance.

This is becomming an issue for us, as the traffic is increasing.

**Comment by MrGeneration** [comment] 2021-05-04 11:31
We're currently investigating this topic but can't tell much new stuff yet.
However, we currently don't expect load situations going on.

**Comment by kevin-olbrich** [comment] 2021-05-04 11:47
https://github-issue-2991.zammad.com/

![image](https://user-images.githubusercontent.com/503085/116998043-ef736880-acdd-11eb-8d17-2d79d7248695.png)

Under heavy load it happens a lot, **under low load it still happens but less frequent**.
For example, my first try against the hosted instance already lost it's attachment...
A new instance should not have much load.

You can find that example in Ticket#94003:

![image](https://user-images.githubusercontent.com/503085/116998377-6c9edd80-acde-11eb-83d3-02637ae2887d.png)

![image](https://user-images.githubusercontent.com/503085/116998435-7fb1ad80-acde-11eb-8328-508da9e4414f.png)

Please let me know if I can help or test to get this resolved. This is an emberassing issue for us. I would try to fix it myself if I would understand ruby. Looks like a race condition...

**Comment by kevin-olbrich** [comment] 2021-05-04 11:57
Quick Benchmark: 3 missing attachment in 23 sent total.

**Comment by rolfschmidt** [comment] 2021-06-08 09:09
@kevin-olbrich can you share your script which you used to reproduce to the problem on our hosted instances?

**Comment by thorsteneckel** [comment] 2021-06-08 13:30
Hi @kevin-olbrich  - @rolfschmidt was able to reproduce the error. We're working on a fix now 👍

**Closed as completed** 2021-06-11 14:51 UTC
Labels: bug, verified, prioritised by payment
