### ISSUE TITLE
Multiple email addresses/contacts

### ISSUE THREAD

**Issue by MichaelHierweck** [zammad/zammad#272] opened 2016-10-22 09:52 UTC
How to deal with customers that use multiple email addresses (same person)?
How to deal with larger organizations (customers) that have multiple contacts (persons)?
- It should be possible to assign multiple email addresses to a customer.
- It should be possible to merge and reassign tickets automatically when two customers have been created that appear to be the same customer.

**Comment by singular-error** [comment] 2016-10-23 15:23
In fact, this is quite interesting! As zammad is aimed to be multi-channel, it even could be that a customer as _no_ email adress, but just one or more telephone-numbers (telephone ticket, what'sup) or other personal IDs (threema, twitter).
So i'd like to have zammad with 
- none to some email-adresses
- none to some telephone-numers
- none to some other IDs
Like the contacts on my android-phone :)
It just has to be unique and mergeable.

The reduction of an user to just_one_ email is quite too simple nowadays, isn't it?

**Comment by MichaelHierweck** [comment] 2016-10-23 15:29
I would like to see (customers/partners) organizations at the top level and contacts (persons) on the next level that can have any number of email addresses, phone numbers, social media accounts and so on.

Sometimes our contacts - such as consultants - work for multiple customers though...

**Comment by thorsteneckel** [comment] 2017-05-28 15:46
Sorry for the delay, but this is actually a duplicate of #613 (which was created later but is our leading issue for this topic).

**Closed** 2017-05-28 15:49 UTC
Labels: duplicate
