### ISSUE TITLE
Trigger Behaviour Issues

### ISSUE THREAD

**Issue by intl808** [zammad/zammad#2472] opened 2019-02-12 23:56 UTC
### Infos:

* Used Zammad version: 2.8.x
* Installation method (source, package, ..): DEB for ubuntu
* Operating system: Ubuntu 18.04.01 LTS
* Database + version: PostgreSQL 10.6
* Elasticsearch version: 5.6.14
* Browser + version: Chrome 71.0.3578.98 x64

### Expected behavior:

* Create a ticket update notification trigger that is internal - email only to agents.
* Create a ticket update notification trigger that is public - email to customer (+ agents).

### Actual behavior:

* working from within zammad console

* When both triggers are active, updating the ticket with an internal note sends a notification email to both customer and agents.

* When the external (public) trigger is set to inactive, updating the ticket with an internal note works as intended and sends an email notification email to only agents.

* Once the external (public) trigger is again active, updating the ticket with an internal note sends an email notification to the customer as well as the agents.

### Steps to reproduce the behavior:

* Create a trigger: action IS updated, state IS NOT closed, visibility IS internal

* Create a trigger: action IS updated, state IS NOT closed, visibility IS public

* Have also tried variations - state IS merged, new, open, etc., visibility IS NOT internal, etc.

* Regardless of variation, when both triggers are active, internal notes are also sent to the customer.

Yes I'm sure this is a bug and no feature request or a general question.

![zammad external trigger](https://user-images.githubusercontent.com/47579798/52675566-96875080-2f6a-11e9-8d2f-40addd4d4ba3.jpeg)
![zammad internal trigger](https://user-images.githubusercontent.com/47579798/52675567-96875080-2f6a-11e9-9247-ad908eb705b2.jpeg)
[production.log](https://github.com/zammad/zammad/files/2858191/production.log)

**Comment by tmswr** [comment] 2019-04-11 15:07
To add to this, we had a very similar trigger for updating Customers on note updates. The trigger would update customers when Agents added a note, but not when a customer updated one. I updated our email accounts yesterday, and after changing them the customer gets note notifications both for Agents and themselves (the customer).

**Comment by MrGeneration** [comment] 2019-04-11 15:15
Please note that customers posting "notes" within the webapp is not a note, but "web".
I currently don't think that this is related to the bug above and would like to ask you to consult our community (https://community.zammad.org) if my comment doesn't help you at all. 

This way we can also find the cause without creating too much noise on Github. :-)

**Comment by niddu85** [comment] 2019-12-20 10:59
Good afternoon,
i have the same situation above; is there any way to do not notify customers for "internal" updates but only agents?

my triggers configuration is mostly the same as mentioned by intl808 and the "public" trigger sends email to customer even if an agent publishes an "internal" note

**Comment by MrGeneration** [comment] 2019-12-20 11:07
> i have the same situation above; is there any way to do not notify customers for "internal" updates but only agents?

@niddu85 sorry but that's mainly a technical question. Please don't hijack Github issues for that.
It would be amazing if you'd post your technical question on the Zammad Community which is perfect for this need: https://community.zammad.org

Thank you! :)

**Comment by mantas** [comment] 2020-08-26 09:32
@MrGeneration as per your note on #3071, should this issue be closed as well?
You said it’s now fixed if I read it correctly :)

**Comment by MrGeneration** [comment] 2020-08-26 13:22
Yes, you're right!
Closing as we believe that this has been fixed with Zammad 3.4.

**Closed as completed by MrGeneration** 2020-08-26 13:22 UTC
Labels: bug, trigger, verified
