### ISSUE TITLE
Possibility to disable the classic password login

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4225] opened 2022-08-24 06:54 UTC
### Infos:

* Used Zammad version: 5.2
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#10110866

### Expected behavior:

* It should be possible as an admin to disable the classic password login. 
* An admin, agent, and customer can not log in with username and password if the classic login with username and password is disabled.
* As a fallback an admin can send himself an emergency link through a new interface to get an email for a classic password login (similar to the password reset functionality).
* Only an admin user should be able to change the password on the profile page.

### Actual behavior:

* Currently it's not possible to disable the classic password login for the situation that only a Third-party login is used.
* An admin, agent, and customer can change the password in his profile.

### Clarification:

- [x] When the classic password login is disabled, should also the signup and password reset be disabled?

**Comment by mantas** [comment] 2022-08-25 08:53
Looks like this will cover https://github.com/zammad/zammad/issues/3715 as well?

**Comment by dbielke1986** [comment] 2022-08-26 11:43
This is already a pull request [#4147 ](https://github.com/zammad/zammad/pull/4147)

**Comment by MrGeneration** [comment] 2022-08-26 13:31
@mantas nope not covered by this one. That's a different request.

The mentioned PR is not feature complete. Possibly Tobias will handle this missing part, but I can't tell.


> When the classic password login is disabled, should also the signup and password reset be disabled?

These are independent options. At least for signing up this might be unexpected behavior and confusing to users because you could link your account after signing up. If this is not good enough it needs PM clarification.

**Comment by tschaefer** [comment] 2022-08-26 13:40
The mentioned PR #4147 will be part of the solution and I agree to @MrGeneration #3715 is a diffrent story.

**Closed as completed** 2022-09-02 21:03 UTC
Labels: enhancement, authentication, verified

**Comment by raffaeler** [comment] 2023-06-21 14:24
Is there an API to toggle the "Password Login"?

**Comment by MrGeneration** [comment] 2023-06-21 14:28
Please don't hijack github issues for your technical questions, you can consult the community for technical questions: https://community.zammad.org
