### ISSUE TITLE
Ticket doesn't re-open on new facebook comments

### ISSUE THREAD

**Issue by chrisblech** [zammad/zammad#1851] opened 2018-02-24 11:27 UTC
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): deb package
* Operating system: Debian 9.3
* Database + version: bundeled
* Elasticsearch version: 5.6
* Browser + version: Chrome 63.0.3239.108

### Expected behavior:

* on every new (customer) comment to a FB page post (=follow-up), ticket should changes from state "closed" to "open" and shows up again in overview "all_open"

### Actual behavior:

* on follow-up, zammad appends the new comment text to the ticket, generates notification, but ticket state stays "closed"

### Steps to reproduce the behavior:

* create FB page post
* FB user comments (-> zammad creates ticket)
* change ticket state to "closed" (-> ticket disappears in overview)
* another FB user comments (-> ticket state stays "closed", so it doesn't re-appear in overview)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by NeverMin** [comment] 2018-02-26 14:54
Hi @chrisblech , thank you for your report, but I can't reproduce your issue, can you help me check my step:
![1851](https://user-images.githubusercontent.com/2797432/36676774-85c6832a-1b47-11e8-81c6-bc616c46dbdd.gif)

**Comment by chrisblech** [comment] 2018-02-26 19:52
Thank you for checking this issue. You take the same steps as me. I can also see the notification appear at the zammad logo, but in my installation, the ticket doesn't re-opens (= re-appear in overview). 
When I bring up the ticket manually (i.e. by clicking on the notification), I can see the new comment ("reopen ticket" in your example), but the tickets state is still "geschlossen" (="closed" - see below).

When starting with zammad, I migrated from OTRS, so my installation has customized ticket states. Maybe this can cause that issue ?

```json
[
    {
        "id": 1,
        "name": "neu",
        "state_type_id": 1,
        "next_state_id": null,
        "ignore_escalation": false,
        "default_create": true,
        "default_follow_up": false,
        "note": "New ticket created by customer.",
        "active": true,
        "updated_by_id": 3,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2018-02-21T10:59:07.828Z"
    },
    {
        "id": 2,
        "name": "geschlossen",
        "state_type_id": 5,
        "next_state_id": null,
        "ignore_escalation": false,
        "default_create": false,
        "default_follow_up": false,
        "note": "Ticket is closed successful.",
        "active": true,
        "updated_by_id": 3,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2018-02-21T10:58:57.645Z"
    },
    {
        "id": 3,
        "state_type_id": 5,
        "name": "closed unsuccessful",
        "next_state_id": null,
        "ignore_escalation": true,
        "default_create": false,
        "default_follow_up": false,
        "note": "Ticket is closed unsuccessful.",
        "active": false,
        "updated_by_id": 3,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2018-02-21T10:50:29.318Z"
    },
    {
        "id": 4,
        "name": "offen",
        "state_type_id": 2,
        "next_state_id": null,
        "ignore_escalation": true,
        "default_create": false,
        "default_follow_up": true,
        "note": "Open tickets.",
        "active": true,
        "updated_by_id": 3,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2018-02-21T10:58:40.697Z"
    },
    {
        "id": 5,
        "state_type_id": 7,
        "name": "removed",
        "next_state_id": null,
        "ignore_escalation": true,
        "default_create": false,
        "default_follow_up": false,
        "note": "Customer removed ticket.",
        "active": true,
        "updated_by_id": 1,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2013-05-28T22:13:45.000Z"
    },
    {
        "id": 6,
        "active": false,
        "name": "pending reminder",
        "state_type_id": 3,
        "next_state_id": null,
        "ignore_escalation": true,
        "default_create": false,
        "default_follow_up": false,
        "note": "Ticket is pending for agent reminder.",
        "updated_by_id": 3,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2018-02-21T10:58:10.346Z"
    },
    {
        "id": 7,
        "state_type_id": 4,
        "name": "Wiedervorlage",
        "next_state_id": 4,
        "ignore_escalation": true,
        "default_create": false,
        "default_follow_up": false,
        "note": "Ticket is pending for automatic close.",
        "active": true,
        "updated_by_id": 3,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2018-02-21T10:56:22.678Z"
    },
    {
        "id": 8,
        "state_type_id": 4,
        "name": "pending auto close-",
        "next_state_id": null,
        "ignore_escalation": false,
        "default_create": false,
        "default_follow_up": false,
        "note": "Ticket is pending for automatic close.",
        "active": false,
        "updated_by_id": 3,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2018-02-21T10:54:26.083Z"
    },
    {
        "id": 9,
        "state_type_id": 6,
        "name": "merged",
        "next_state_id": null,
        "ignore_escalation": false,
        "default_create": false,
        "default_follow_up": false,
        "note": "State for merged tickets.",
        "active": true,
        "updated_by_id": 1,
        "created_by_id": 1,
        "created_at": "2013-05-28T22:13:45.000Z",
        "updated_at": "2013-05-28T22:13:45.000Z"
    }
]
```

**Comment by NeverMin** [comment] 2018-02-27 14:11
I check the code:
https://github.com/zammad/zammad/blob/develop/lib/facebook.rb#L343

I think your State is good, and I changed my State from `open` to `offen`:
`Ticket::State.find_by(id: 2).update!(name: 'offen')`
```
Here is my offen state:
{
    "id":2,
    "state_type_id":2,
    "name":"offen",
    "next_state_id":null,
    "ignore_escalation":false,
    "default_create":false,
    "default_follow_up":true,
    "note":null,
    "active":true,
    "updated_by_id":1,
    "created_by_id":1,
    "created_at":"2017-09-29T15:36:12.000Z",
    "updated_at":"2018-02-27T11:41:36.823Z"
}
```

Then comment in FB, I got this history log(reopen is work):
```
xxx - 2 hours 13 minutes ago

    updated Ticket state from 'closed' to 'offen'
    created Article
    updated Ticket last_contact_customer_at from '2018-02-26 13:46:41 UTC' to '2018-02-27 11:49:39 UTC'
    updated Ticket last_contact_at from '2018-02-26 13:47:17 UTC' to '2018-02-27 11:49:39 UTC'
```

Can you show me your history log?

**Comment by chrisblech** [comment] 2018-02-27 16:41
May it be a problem that I also renamed "closed" to "geschlossen" ?

In https://github.com/zammad/zammad/blob/develop/lib/facebook.rb#L348 , the `name: closed` is hardcoded, instead of perhaps `state_type_id: 5` . It doesn't seems to cause this issue (just a guess - I'm not good in ruby), but maybe this can cause other problems, when user renames states?

**Comment by MrGeneration** [comment] 2018-02-28 11:14
This may be a duplicate post, as I have the same problem for some time now.
As far as I can see on my installation "geschlossen" / "closed" is not being renamed but just translated.

#1777

**Comment by MrGeneration** [comment] 2018-12-24 11:00
Closing, Duplicate of https://github.com/zammad/zammad/issues/1777

**Closed by MrGeneration** 2018-12-24 11:00 UTC
Labels: duplicate
