### ISSUE TITLE
builder.rb:52:in `block in fetch_value': can't modify frozen Hash: {} (FrozenError)

### ISSUE THREAD

**Issue by GhaziTriki** [zammad/zammad#5313] opened 2024-08-24 15:16 UTC
### Used Zammad Version

6.3.1-1724487911.187a1021.noble

### Environment

- Installation method: package
- Operating system: ubuntu 24.04
- Database + version:postgresql 16.3
- Elasticsearch version: 

### Actual behaviour

During the update process I see the following error logs

```logs
# Updating translations...

/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.8.4/lib/active_model/attribute_set/builder.rb:52:in `block in fetch_value': can't modify frozen Hash: {} (FrozenError)

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.8.4/lib/active_model/attribute_set/builder.rb:46:in `fetch'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.8.4/lib/active_model/attribute_set/builder.rb:46:in `fetch_value'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/composite_primary_keys-14.0.9/lib/composite_primary_keys/attribute_methods/read.rb:25:in `_read_attribute'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.8.4/lib/active_model/attribute_methods.rb:271:in `source'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/core_ext/enumerable.rb:111:in `block in index_by'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation/delegation.rb:88:in `each'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation/delegation.rb:88:in `each'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/core_ext/enumerable.rb:111:in `index_by'

	from /opt/zammad/app/models/translation/synchronizes_from_po.rb:61:in `sync_locale_from_po'

	from /opt/zammad/app/models/translation/synchronizes_from_po.rb:54:in `block (2 levels) in sync'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:209:in `transaction'

	from /opt/zammad/app/models/translation/synchronizes_from_po.rb:53:in `block in sync'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation/delegation.rb:88:in `each'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation/delegation.rb:88:in `each'

	from /opt/zammad/app/models/translation/synchronizes_from_po.rb:52:in `sync'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/commands/runner/runner_command.rb:46:in `<main>'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/commands/runner/runner_command.rb:46:in `eval'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/commands/runner/runner_command.rb:46:in `perform'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/command/base.rb:87:in `perform'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/command.rb:48:in `invoke'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.4/lib/rails/commands.rb:18:in `<main>'

	from <internal:/opt/zammad/vendor/ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'

	from <internal:/opt/zammad/vendor/ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'

	from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'

	from /opt/zammad/bin/rails:5:in `<main>'

# No custom packages detected...

```

### Expected behaviour

Should see no error during update.

### Steps to reproduce the behaviour

`sudo apt dist-upgrade`

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment] 2024-08-27 07:24
There is a known problem with updating everything at the same time. I think if e.g. Postgres and zammad are updated at the same it can lead to issues.

What happens if you update the zammad package only and then later the rest?

`apt install zammad`

might be related to: https://community.zammad.org/t/apt-get-dist-upgrade-y-can-break-your-zammad-install/15344

**Comment by rolfschmidt** [comment] 2024-08-27 07:27
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer to the Zammad community over at: https://community.zammad.org/ .

In case this turns out to be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
If you're a paying customer already, please consult your Zammad support for assistance! :-)

**Comment by rolfschmidt** [comment] 2024-08-28 07:07
https://community.zammad.org/t/apt-get-dist-upgrade-y-can-break-your-zammad-install/15344/2

**Comment by GhaziTriki** [comment] 2024-08-29 11:35
Thanks for the tip  @rolfschmidt. I tried `sudo apt install --reinstall zammad` and I got the same error. That command should install zammad only. Did I miss something internal to that command that affect zammad install? I will of course try `apt install zammad` in a few days.

**Comment by mantas** [comment] 2024-08-29 11:50
@GhaziTriki did you modify any translations? Either via UI, via console or directly in database translations table?

**Comment by rolfschmidt** [comment] 2024-08-29 11:50
> Thanks for the tip @rolfschmidt. I tried `sudo apt install --reinstall zammad` and I got the same error. That command should install zammad only. Did I miss something internal to that command that affect zammad install? I will of course try `apt install zammad` in a few days.

1. You could try to run the postinstall.sh again, is it the same error?

`root> /opt/zammad/contrib/packager.io/postinstall.sh`

2. The error seems to come from the translations. They will be synced with every update so you could also try to open the rails console and drop them, but only if you have no custom translations.

Before that it might make sense to save them and share them here, so we maybe it is possible to reproduce it with your translation list:

```
root> zammad run rails c
rails> File.write('/tmp/translations.json', Translation.all.to_json)
rails> File.write('/tmp/locales.json', Locale.all.to_json)
```

Afterwards you could try to delete them:

```
root> zammad run rails c
rails> Translation.delete_all
rails> Locale.delete_all
root> /opt/zammad/contrib/packager.io/postinstall.sh
```

**Comment by GhaziTriki** [comment] 2024-08-29 12:05
This is coming from our staging server. In this server we didn't update any translation so far.

`/opt/zammad/contrib/packager.io/postinstall.sh` went well and a `--reinstall` printed a long trace attached to this ticket.

[MobaXterm_ZammadDEV-67.222.155.35devops_20240829_130304.docx](https://github.com/user-attachments/files/16798676/MobaXterm_ZammadDEV-67.222.155.35devops_20240829_130304.docx)

Quick question, do `redis` have something to do with translations? I need to mention that I found redis dump corrupt today and I had to delete the dump file then restart redis.

**Comment by MrGeneration** [comment] 2024-08-29 12:08
@GhaziTriki can you please use images instead of proprietary office formats?

**Comment by GhaziTriki** [comment] 2024-08-29 12:11
@MrGeneration is an open format fine (odt)? The logs contains 198 pages, it would be hard to put all it together into a single image.

**Comment by MrGeneration** [comment] 2024-08-29 12:13
`.txt` or `.log`? :)

**Comment by GhaziTriki** [comment] 2024-08-29 12:22
Possible with messy characters I think. Let's git it a try.

[MobaXterm_ZammadDEV-67.222.155.35devops_20240829_130304.txt](https://github.com/user-attachments/files/16798896/MobaXterm_ZammadDEV-67.222.155.35devops_20240829_130304.txt)

**Comment by mgruner** [comment] 2024-09-19 05:04
@GhaziTriki thank you very much for providing your logs. Unfortunately we were not able to isolate a possbile cause or somehow reproduce this problem on one of our systems. Therefore I will have to close this report until there is more information that would allow us to reproduce and fix the issue. 

Thank you for your understanding and please feel free to add more info here, so that we could revisit the case.

**Closed as not planned by mgruner** 2024-09-19 05:04 UTC
Labels: question

**Comment by GhaziTriki** [comment] 2024-09-19 07:20
Hi @mgruner, can you try stopping redis then running an update? I think it is the issue. There is a warning when PostgreSQL cannot be reached during install and we should cover redis scenario the same way.

**Comment by mgruner** [comment] 2024-09-19 12:33
@GhaziTriki I'm not sure how this would work, because without a redis connection the Rails stack will not even start:

```
% rails r Translation.sync
There was an error trying to connect to Redis via redis://localhost:6379.
Please provide a Redis instance at localhost:6379 or set REDIS_URL to point to a different location.
#<Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)>
```

How did you do that?
