### ISSUE TITLE
inserting a link in triggers does not work

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1547] opened 2017-10-18 12:47 UTC
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

* should be able to insert links into content of a mail notification trigger
* should be able to edit it

### Actual behavior:

* existing links are blue but no possibility to edit them
* no possibility to insert URLs that get transformed into links
(only possibility is via developer tools of used browser)

**Comment by passboltUser** [comment] 2018-01-23 09:15
I agree. Sometimes if link is cut and pasted again, it isn't blue anymore and pressing space or enter unfortunately doesn't make it blue. An edit menu or at least a shortcut to make a URL blue/clickable would be good.
I see here https://github.com/zammad/zammad/issues/656#issuecomment-292858006 a "Removes any hyperlink", so something like: ~"Adds/converts to a clickable hyperlink" would be good.

**Comment by thorsteneckel** [comment] 2018-03-01 09:44
This is actually a duplicate of #464

**Closed by thorsteneckel** 2018-03-01 09:44 UTC
