### ISSUE TITLE
Wrong quoting of $ (dollar) parameter in URLs/Links

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#3125] opened 2020-07-22 11:56 UTC
### Infos:

* Used Zammad version: 3.4.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version:
  - Chrome Version 83.0.4103.97 (Official Build) (64-bit)
  - Firefox Version 77.0.1 (64-Bit)

Ticket#: 1067660

### Expected behavior:

* URLs containing a parameter value containing a `$` (dollar sign) should pass the `$` as a parameter value to the receiving server.

### Actual behavior:

* URLs containing a parameter value containing a `$` (dollar sign) actually pass the encoded version of the `$` (`%24`) as a parameter value to the receiving server.

### Steps to reproduce the behavior:

* Save an URL in an Article containing a `$` (dollar sign), e.g. `http://localhost?cmd=123$4`
* Click the URL in the browser
* See the URL in the browser bar: `http://localhost?cmd=123%244`

### Background information:

Zammad uses [Nokogiri](https://github.com/sparklemotion/nokogiri) for handling HTML. Nokogiri utilises [Libxml2](http://xmlsoft.org/) for parsing and generating HTML. `Libxml2` implements [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt). According to `RFC 3986` the `$` is a "sub delimiter" (see `2.2.  Reserved Characters` in the RFC) that requires special handling. `Libxml2` does this [special handling](https://gitlab.gnome.org/GNOME/libxml2/-/blob/681f094e5bd1d0f6b38b27701d0d1bf1ca7a9a26/uri.c#L113). However, other "sub delimiters" get handled in a different way:

```ruby
[1] pry(main)> doc = Nokogiri::HTML('<a href="http://localhost?cmd=@/:=?;#%&,+<>[]&a=b&b=[]">123</a>')
[2] pry(main)> doc.to_s
=> "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">\n<html><body><a href=\"http://localhost?cmd=@/:=?;#%&amp;,+&lt;&gt;%5B%5D&amp;a=b&amp;b=%5B%5D\">123</a></body></html>\n"
```

There is also [a patch for `Libxml2` that is shipped with nokogiri which applies some unknown special handling on other chars](https://github.com/sparklemotion/nokogiri/blob/8f16736502888ab8a594e7f3179fcbd32e7e9280/patches/libxml2/0001-Revert-Do-not-URI-escape-in-server-side-includes.patch#L64).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment] 2022-10-14 09:08
Closing as this seems to be not a bug after further investigation. The `$` is URL-encoded, but that shouldn't break the link if all is good on the other side.

**Closed as completed** 2023-05-03 09:28 UTC
Labels: works as designed / wontfix
