### ISSUE TITLE
Update from version 2.6.0 to 2.7.0 fails

### ISSUE THREAD

**Issue by MarvinKlar** [zammad/zammad#2221] opened 2018-09-03 11:37 UTC
### Infos:

* Used Zammad version: 2.6.0
* Installation method (source, package, ..): source
* Operating system: Debian GNU/Linux 9 (stretch)
* Database + version:  MariaDB 10.2.6
* Elasticsearch version: 5.6.10 from 2018-06-06T15:48:34.860Z
* Browser + version: doesn't matter

### Expected behavior:

* Command `rake db:migrate` should work

### Actual behavior:

* Error `Duplicate column name 'queue': ALTER TABLE `cti_logs` ADD `queue` varchar(250)` occours

### Steps to reproduce the behavior:

* install version 2.6.0 and update. It will fail at the command `rake db:migrate` 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MarvinKlar** [comment] 2018-09-03 12:35
Deleting the row fixed the error.

I also had to do this for the following rows:
Duplicate column name 'initialized_at': ALTER TABLE `cti_logs` ADD `initialized_at` varchar(250)
Duplicate column name 'duration_waiting_time': ALTER TABLE `cti_logs` ADD `duration_waiting_time` int
Duplicate column name 'duration_talking_time': ALTER TABLE `cti_logs` ADD `duration_talking_time` int

But then I got the following error:
Invalid default value for 'start_at': ALTER TABLE `cti_logs` CHANGE `start` `start_at` timestamp(3) DEFAULT NULL

**Comment by thorsteneckel** [comment] 2018-09-03 16:07
Hi Marvin. I'm pretty sure this is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

However, it looks like something went wrong while you ran the migration the first time. Then you ran it a second time and the columns were already there. 

The second error you mentioned looks like a duplicate of #2183. This should be resolved with these two fixes:

https://github.com/zammad/zammad/commit/c6e6423dd0de5fad3c198a159c39c0d7758ebb93
https://github.com/zammad/zammad/commit/c6e6423dd0de5fad3c198a159c39c0d7758ebb93

Make sure you have these changes in your local code base.

Closing now.

**Closed as completed by thorsteneckel** 2018-09-03 16:07 UTC

**Comment by MarvinKlar** [comment] 2018-09-04 07:02
Thank you very much four your help here https://github.com/zammad/zammad/issues/2183
The migration https://github.com/zammad/zammad/issues/2183#issuecomment-413451598 worked like a charm and ran without an error!

Have a great day!
