### ISSUE TITLE
Email address displayed incorrectly

### ISSUE THREAD

**Issue by krayevidi** [zammad/zammad#3179] opened 2020-09-02 15:30 UTC
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): Source
* Operating system: Ubuntu
* Database + version: Postgres 9.6
* Elasticsearch version: 5.6
* Browser + version: Firefox 80

### Expected behavior:

* IDNA decoded email should be shown on user profile page.

### Actual behavior:

* IDNA encoded display value is shown on user profile page.

### Steps to reproduce the behavior:

* set üser@exämple.com value to user email address via user edit form in the UI, save it, open profile page, e.g. https://your.domain/#user/profile/<your_id>.
see attached screenshot

![image](https://user-images.githubusercontent.com/5553206/92003471-5b619380-ed41-11ea-8311-f0e36e04c2fb.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Dennis1993** [comment] 2020-09-02 16:39
Google: IDN Domain. Thats the international domain name of the domain because an umlauts is in the name

**Comment by MrGeneration** [comment] 2020-09-02 16:47
This is a duplicate of
* https://github.com/zammad/zammad/issues/2401
* https://github.com/zammad/zammad/issues/2402

**Closed as completed by MrGeneration** 2020-09-02 16:47 UTC
Labels: duplicate
