### ISSUE TITLE
Translation missing for link-template example

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4393] opened 2022-11-25 06:59 UTC
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#10115195

### Expected behaviour:

* When I add attributes via the object manager I see a translation of the example.

### Actual behaviour:

* When I add attributes via the object manager I don't see a translation of the example.
![grafik](https://user-images.githubusercontent.com/97293098/203920378-1b431097-3802-427e-8cb7-bf75342bdb83.png)

### Steps to reproduce the behaviour:

* Create an attribute in the object manager in a language other than English.

Yes, I'm sure this is a bug, not a feature request or a general question.

**Comment by dvuckovic** [comment] 2022-12-07 12:41
I was unable to reproduce this in Zammad 5.3.0 (stable), the placeholder string is correctly marked as translatable AND also translated into German language:

<img width="604" alt="Screenshot 2022-12-07 at 12 36 17" src="https://user-images.githubusercontent.com/6049445/206181051-0bfae10e-697a-439b-b036-7a45cbd7b308.png">

The screenshot above was made in the **New Attribute > Text field** dialog.

If the report was done with a pre-release version of 5.3, it could be the translation sync just didn't happen by that time. As you know, the translations are done by the community via Weblate instance and synced with the codebase just prior to the release.

Feel free to re-open this issue with more information.

**Closed as completed by dvuckovic** 2022-12-07 12:41 UTC
Labels: bug, verified, prioritised by payment, localization
