### ISSUE TITLE
Twitter Integration failed "Unable to register webhook"

### ISSUE THREAD

**Issue by ElektronikerDev** [zammad/zammad#3859] opened 2021-11-20 10:06 UTC
Hey, 

When trying to use the twitter integration, I get the following error: 
**"Unable to register webhook: Unable to connect during CRC GET request. Already 1 webhooks registered. Maybe you need to delete one first.**".

Thanks for the help in advance.

Now to the specs:

### Infos:

* Used Zammad version: 5.0.2
* Installation method (source, package, ..): source
* Operating system: Debian 10
* Database + version: latest
* Elasticsearch version: latest
* Browser: Brave

### Expected behavior:

According to the documentation, which doesn't quite match the current Twitter Developer Interface, I did all the steps like this.

I created a fresh app, enabled 3-legged OAuth and entered the keys in Zammad.
In the Twitter "Dev Environments" tab, I created a label and deposited the app.

### Actual behavior:

I get the following GUI error:
![image](https://user-images.githubusercontent.com/30439300/142721966-bd316b85-5efb-4989-b190-97ccba044346.png)

This is the associated log:
#/var/log/zammad/production.log

``E, [2021-11-20T09:52:41.346987 #11252-193300] ERROR -- : Unable to register webhook: Unable to connect during CRC GET request. Already 1 webhooks registered. Maybe you need to delete one first. (RuntimeError)
lib/twitter_sync.rb:953:in `rescue in webhook_register'
lib/twitter_sync.rb:944:in `webhook_register'
lib/external_credential/twitter.rb:196:in `register_webhook'
lib/external_credential/twitter.rb:6:in `app_verify'
app/models/external_credential.rb:11:in `app_verify'
app/controllers/external_credentials_controller.rb:27:in `app_verify'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2021-11-20T09:52:41.355299 #11252-193300]  INFO -- : Completed 200 OK in 984ms (Views: 0.5ms | ActiveRecord: 9.0ms | Allocations: 19561)
root@servidesk:~#``

Haste version: https://haste.devstorage.eu/nxSZv6CwMV

However, there is no other webhook created in Twitter:
![image](https://user-images.githubusercontent.com/30439300/142722045-35c3c60e-00d7-4e27-8b3a-5a00d5cd4dde.png)

Twitter App Settings:

![image](https://user-images.githubusercontent.com/30439300/142722507-f9e9a469-638d-4e6d-a85c-0ccce7a52a56.png)

### Steps to reproduce the behavior:

It is a fresh installation with mail server setup (Mailcow on a external server). Nothing else has been done yet.
I used this Documentation for the installation: https://docs.zammad.org/en/latest/install/package.html

**Comment by errooorr** [comment] 2022-09-01 14:40
tg twit - unable webhook (((((

**Comment by t-shehab** [comment] 2023-05-11 08:58
Unable to reproduce at the moment. Closing for now.

**Closed as completed by t-shehab** 2023-05-11 08:58 UTC
Labels: can't reproduce
