### ISSUE TITLE
Knowledge Bases answer appears in search result even if category permissions are set to none

### ISSUE THREAD

**Issue by andrea-monti** [zammad/zammad#4078] opened 2022-05-04 14:57 UTC
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): Source
* Operating system: CentOS Linux release 7.6.1810 (Core)
* Database + version: postgresql 9.6
* Elasticsearch version: 7.9.1
* Browser + version: doesn't matter

### Expected behavior:

* I expect that If i set a knowledge base category permission to "none" for a the default role "agent" and the answers visibility to "internal", the knowledge base answers that belongs to that category will be hidden from the knowledge base in-ticket search function "??" from the Agent prospective.

### Actual behavior:

* The answer is still visible in the in-ticket search function "??''.

### Steps to reproduce the behavior:

* As an Admin
* Set Agent role permissions for the knowledge base to "reader"

![image](https://user-images.githubusercontent.com/104498720/165536683-bddcfac6-ec94-4704-98fb-11b0b5879965.png)

* Set category permission for the role Agent to "None" 

![2categPerm](https://user-images.githubusercontent.com/104498720/166696896-84170b67-4307-4072-855e-308250981a7d.PNG)

* Set the answer visibility to "Internal"

![2visibilitySetting](https://user-images.githubusercontent.com/104498720/166697581-c2db3ce5-70f0-4d2b-986c-9b0f365508f5.PNG)

* Switch to an user with the Agent role. 
* Create a new ticket.
* In the text area use the search function with the shortcut "??".
* Search for the answer that should be hidden.

![2ticket](https://user-images.githubusercontent.com/104498720/166698530-cdd69ee8-6b19-489c-ae46-47a4c5665703.png)

* the hidden answer is still visibile.

* log [dev.log](https://github.com/zammad/zammad/files/8621021/dev.log)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-05-04 15:02
Duplicate of #4069

**Closed as completed by MrGeneration** 2022-05-04 15:02 UTC
Labels: duplicate
