### ISSUE TITLE
Mails with inline PNG attachments are not processed

### ISSUE THREAD

**Issue by divdax** [zammad/zammad#2447] opened 2019-01-24 14:51 UTC
### Infos:

* Used Zammad version: Version 2.8.x
* Operating system: Ubuntu 14
* Database + version: MySQL 5.7
* Elasticsearch version: -
* Browser + version: Chrome Version 71.0.3578.98

### Expected behavior:

Zammad should import new mails from mailserver.

### Actual behavior:

Zammad don't import mails with png inline attachments.

**Comment by MrGeneration** [comment] 2019-01-24 15:50
Please fill in the missing information, especially used Browser.
Otherwise we can't reproduce this and have to close the issue without further investigation. :(

**Comment by divdax** [comment] 2019-01-24 15:53
I'm using latest Chrome

Am Do., 24. Jan. 2019, 16:50 hat Mr.Generation <notifications@github.com>
geschrieben:

**Comment by MrGeneration** [comment] 2019-01-25 11:14
Sorry, I can't reproduce this, please provide a sample.

![image](https://user-images.githubusercontent.com/6549061/51742666-bed20c80-209a-11e9-8f16-f884e2197dcf.png)

**Comment by MrGeneration** [comment] 2019-02-04 17:53
As I can't reproduce this and am missing feedback, I'm closing this issue for now.
If you feel this is wrong and have a working way to reproduce this, I'll happily reopen this.

**Closed as completed by MrGeneration** 2019-02-04 17:53 UTC
Labels: can't reproduce
