### ISSUE TITLE
Exchange Feature - URL?

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#1406] opened 2017-09-12 06:07 UTC
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: DEB
* Operating system: Ubuntu 16.04
* Browser + version: Chrome latest

### Expected behavior:
* Exchange Configuration should have a URL for the Exchange??

### Actual behavior:
* No URL. -> Autoconfiguration not available so Feature does not work..

Best Regards,
David

**Comment by martini** [comment] 2017-09-12 06:11
Hi @ThePatzen 

what means "No URL. -> Autoconfiguration not available so Feature does not work." ?

Did you test the exchange integration?

 -Martin

**Comment by thorsteneckel** [comment] 2017-09-12 06:46
@ThePatzen - The Exchange integration performs an auto discovery attempt via a special Exchange mechanism based on the email address domain. If this fails (which shouldn't) Zammad requests you to enter the URL manually. So what happens after you insert your mail and password?

**Comment by ThePatzen** [comment] 2017-09-12 09:08
Hi!
I get the following Error:
![image](https://user-images.githubusercontent.com/4540135/30317554-af850e46-97aa-11e7-8e7f-2578ad8a8547.png)

**Comment by thorsteneckel** [comment] 2017-09-12 09:10
Could you please provide your `log/production.log` file so we can reason about the issue? You can send it to support@zammad.com and refer to this issue.

**Comment by ThePatzen** [comment] 2017-09-12 09:18
Hi Thorsten,

Done!

(Ticket#108430)

Best Regards!

**Comment by thorsteneckel** [comment] 2017-09-12 09:54
Thanks for providing the information we needed. This is fixed with the commits above and ready to install in ~30 minutes from now via a regular package update of the stable or develop branch. 

The issue was caused by a error in checking the result of the Exchange auto discovery try. The handling is now properly implemented. Feedback is welcome 🚀

**Closed by thorsteneckel** 2017-09-12 09:54 UTC
Labels: bug, integration, needs verification
