### ISSUE TITLE
Archived otrs tickets won't get imported

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad#1855] opened 2018-03-05 07:10 UTC
### Infos:

* Used Zammad version: 2.3.0
* Installation method (source, package, ..): source
* Operating system: Debian9
* Database + version: MariaDB 10.1.26
* Elasticsearch version: n/a
* Browser + version: console

### Expected behavior:

* import all tickets.

### Actual behavior:

* archived otrs tickets won't get imported.

### Steps to reproduce the behavior:

* archive tickets in otrs
* run `Import::OTRS.start`
* restore tickets from archived
* run `Import::OTRS.diff_worker`

### Additional Information:
* otrs 5.0.12 (MySQL 5.5)
* Znuny4OTRS-ZammadMigrator 5.0.1

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by pc-coholic** [comment] 2018-09-04 10:34
I believe, that this has been fixed by now (at least with the OTRS6-Migrator). I just imported all my OTRS-tickets into a test-instance of Zammad and everything seems to be here - including archived items.

**Comment by thorsteneckel** [comment] 2018-09-17 12:31
Hi @pc-coholic - thanks for the heads up. That was my impression in the first place (because there is no logic to exclude archived tickets). Thanks for confirming it. Feel free to provide further information on how to reproduce it. I'll close this issue in the meantime.

**Closed by thorsteneckel** 2018-09-17 12:31 UTC
Labels: enhancement, import
