### ISSUE TITLE
Users can be created without a primary organization but with secondary organizations

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4579] opened 2023-04-18 13:31 UTC
### Used Zammad Version

5.4

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): unknown
- Database + version:  postgresql
- Elasticsearch version: 7.17
- Browser + version: any

### Actual behaviour

It is possible to update users to set them in a state where users have no primary but secondary organizations.
It is not possible to create users with no primary but secondary organizations.

### Expected behaviour

There should be no users who have only secondary organizations, but no primary ones.

<details closed>
<summary>Old issue</summary>

### Actual behaviour

When having users with no primary organisation, but only secondary organisations, LDAP sync fails:

![grafik](https://user-images.githubusercontent.com/97293098/232792732-3fe45886-9889-48a8-9faa-b05df0304fdc.png)

### Expected behaviour

Being able to sync, when not using primary organisations.

### Steps to reproduce the behaviour

Sync a user into Zammad using LDAP. Assign this user a secondary organisation, but no primary organisation.

</details>

### Steps to reproduce

- Create a new user without any organization.
- Edit the user and add only one/some secondary organizations (saving is working fine).
- Try to edit again and see an error message that it can not be saved without a primary one ( ´Secondary organizations are only allowed when the primary organization is given.`)

### Support Ticket

Ticket#10123103

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment] 2023-04-18 18:31
@YetAnotherGerrit I think in general it's working by design, that it should not be possible to use secondary organizations without a primary organization.

I see here more of a bug that it's currently possible to save secondary organizations without a primary organization. This is also only possible the first time when you use the field, afterwards you are not able to change the user with the edit action.

**Comment by YetAnotherGerrit** [comment] 2023-04-20 06:42
When people start using secondary organisations, I actually warn them about using primary organisations at all. With the current implementation of secondary organisations, it's a huge data privacy risk to combine that with primary organisations.

**Comment by MrGeneration** [comment] 2023-04-20 14:33
> When people start using secondary organisations, I actually warn them about using primary organisations at all. With the current implementation of secondary organisations, it's a huge data privacy risk to combine that with primary organisations.

Sounds like something the documentation should mention when you see it as such a big wave. Or it needs general improvement...

I mean secondary organizations always are a potential data leak risk if you don't know what you're doing so...
Maybe I'm not understanding the issue you're talking about here.

Another possible option would be to no longer default to an organization sharing (which I suggested years ago)

**Comment by YetAnotherGerrit** [comment] 2023-04-28 07:16
The risk is that all customer tickets are changed if you change a customer's organisation. This is only true for the primary organisation. This means, if you change a customer's organisation to a shared organisation, all their tickets (even years old) are suddenly visible to their (new) colleagues. That's why I suggest using secondary organisations if you don't want this to happen.

**Comment by dominikklein** [comment] 2023-05-03 17:46
This sounds like, there is a general problem that needs to be discussed, it's maybe also an identification that this specific shared organization topic is more important.

About this issue here, I would suggest closing it and fixing the problem that a user can be created/updated without having a primary organization but a secondary organization.
@rolfschmidt What do you think?

**Comment by rolfschmidt** [comment] 2023-05-05 08:52
## Meeting 2023-05-05 (@t-shehab , @rolfschmidt , @martini )

@YetAnotherGerrit This issue need to split up into 2 issues:

- 1 bug issue: It should not be possible to create users without primary organizations but secondary. We need the steps to reproduce this. I will rename this issue now, please provide us steps how this is possible.
- 1 enhancement issue: Add support for secondary organizations without primary organizations. This is currently not supported and not expected. If you want this behaviour then it is a enhancement request.

**Comment by dominikklein** [comment] 2023-05-08 08:30
> 1 bug issue: It should not be possible to create users without primary organizations but secondary. We need the steps to reproduce this. I will rename this issue now, please provide us steps how this is possible.

Added steps to reproduce.

**Comment by KoJie** [comment] 2023-05-25 13:14
I'm trying to bring some clarity here, because at least I felt that I lost track of the situation here.

After consulting @YetAnotherGerrit I heard that his original problem, that he needed the scenario to create user without primary organization will be obsolet when working on: https://github.com/zammad/coordination-private-features/issues/60

That means there is still one inconsistent behavior: you cannot create a user without primary organization, but you can edit an existing user, delete primary organization and save it.
I think the behavior was changed in between, because of the different descriptions in this issue. After testing it on a 6.0 and 6.1 testversion, I am sure that this behavior is correct right now and thus I changed the title and the original issue description, to prevent confusion.

**Closed as completed** 2023-06-22 09:34 UTC
Labels: bug, verified, prioritised by payment, organization, user
