### ISSUE TITLE
Fields From and To are interpreted in articles from operators

### ISSUE THREAD

**Issue by Madko** [zammad/zammad#3178] opened 2020-09-02 10:03 UTC
### Infos:

* Used Zammad version: 3.4.0-1596534174.0b324922.bionic
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04 LTS
* Database + version: postgresql-10                          10.12-0ubuntu0.18.04.1
* Elasticsearch version: elasticsearch                          7.8.1
* Browser + version: Firefox ESR Windows

### Expected behavior:

* When an operator copy/paste text from a mail body, fields like from and to should not be interpreted. So when can have the actual operator as the creator of the new note/article, and not the client from the from field

### Actual behavior:

* If you paste text containing a from and/or to fields, it is interpreted by zammad as the actual sender and recipient of the message. It results as a note type "Web".

### Steps to reproduce the behavior:

* create a new reponse to the client
* change type to mail
* add the recipient address
* copy/paste a forwarded message from thunderbird. The rich editor seems to understand it's a mail, with a response. It adds indentation. Maybe only occurs with Windows

Will try to add screen captures

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Madko** [comment] 2020-09-02 10:13
Capture of the editor: http://www.linuxed.net/wp-content/uploads/captures/zammad/bug-github-zammad-3178-capture01.png
Result, the message is seems from the customer: http://www.linuxed.net/wp-content/uploads/captures/zammad/bug-github-zammad-3178-capture02.png

**Comment by MrGeneration** [comment] 2020-09-02 10:22
Sorry but this sounds like a rather technical question or I do not understand the issue you're trying to describe.
As far as I'm aware Zammad does not interpret copied content.

If this is a technical question or enhancement request, please consult the Community (https://community.zammad.org) instead.

If you still believe that above is a bug, it would be great if you could add a screencast (video form) which may help to understand better what you're talking about. If you're not using a vanilla installation, please also try to reproduce this in a free hosted setup instance to double check. ( https://zammad.com/getting-started )

**Comment by Madko** [comment] 2020-09-02 11:46
Hi thank you for your response. Yes of course it's a bug. Have you seen capture 2 ? How a message from an operator (as shown in capture 01) can be seen as a message from the customer (cf capture 02)?

**Comment by Madko** [comment] 2020-09-02 11:58
Messages are in french, the important part is the "De: blurred email address" (De means From) and "A: blurred email address" (A means To). Sorry if I was not clear.
The operator has been replaced by the From blurred email address, which occurs to be the customer of this ticket. It ends with an Article in the ticket shown as being sent by the customer, instead of the operator.
History of this ticket has no error, it shows that it is actually the operator that did this answer, not the customer. I can add a capture of the history if needed.

ps: I'm trying to reproduce it on zammad.com free instance. But I need to find a Windows PC...

**Comment by Madko** [comment] 2020-09-02 12:31
This new capture might be more understandable:
http://www.linuxed.net/wp-content/uploads/captures/zammad/bug-github-zammad-3178-capture03.png.png

How a message from an operator can be seen as from the customer ?

**Comment by Madko** [comment] 2020-09-02 12:35
capture 04 is from the history of the same ticket. As the same date "Mercredi 9:56" (Wednesday 9:56 AM) you can see that this is the operator Sophie that added this answer shown in capture 03, not Véronique (which is a customer).

http://www.linuxed.net/wp-content/uploads/captures/zammad/bug-github-zammad-3178-capture04.png

**Comment by MrGeneration** [comment] 2020-09-02 12:36
OH that's what you're talking about.
So you're in a new ticket dialogue followed by a reply by mail.

Then this indeed is a bug, but a duplicate of https://github.com/zammad/zammad/issues/2922 which is why I'm closing this issue. :) Sorry for the confusion.

**Closed as completed by MrGeneration** 2020-09-02 12:36 UTC
Labels: duplicate
