### ISSUE TITLE
Missing error message on link ticket

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2557] opened 2019-05-02 06:01 UTC
### Infos:

* Used Zammad version: develop
* Installation method (source, package, ..): source
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.6
* Elasticsearch version: n.a.
* Browser + version: Chrome, FF, both latest

### Expected behavior:

* When linking a ticket with a wrong input an error message / hint should be displayed.

### Actual behavior:

* After entering an ticket number, e.g. after the ticket number was copy into the clipboard with the shortcut, nothing happens when the form is submitted.

### Steps to reproduce the behavior:

* Open a ticket
* Copt the current object number to clipboard (Ctrl + Alt + .)
* Open another ticket
* Add a link
* Use the clipboard content as input
* Press submit

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-05-02 07:51
There's an error message, but it's hidden underneath the merge dialog.
Also, this message should be permanent until leaving this dialog:

![image](https://user-images.githubusercontent.com/6549061/57062229-d9320c80-6cbf-11e9-9647-669507d84160.png)

**Comment by rkaldung** [comment] 2019-05-02 08:36
I checked again and can confirm there is a message (No such object) which disappears after a few seconds. Same behaviour in the merge dialogue? And what is a master ticket?

**Comment by MrGeneration** [comment] 2021-06-22 07:37
As requested by bola:
No I can no longer reproduce this. The toast message by now appears above modals like it should. 
Seems to be magically fixed by another commit.

**Closed as completed** 2021-06-22 20:53 UTC
Labels: can't reproduce
