### ISSUE TITLE
Cannot reset password if name or surname has numer or .(dot)

### ISSUE THREAD

**Issue by GretaD** [zammad/zammad#4144] opened 2022-06-24 09:30 UTC
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* When i click reset password, i receive the email to reset my password

### Actual behavior:

* When i click reset password the submit button disables and nothing happens

### Steps to reproduce the behavior:

* Open your zammand system (mine is support@nextcloud.com)
* Click reset password
* Add your email that has numbers and dot in it, which means that on your system your name or surname will have number and dot
* Click submit
When i remove the number and dot from name and surname, the email is sent correctly.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-06-24 09:33
Please open a support case with us - if you can, the rough time you've tried would help me for verification of the issue a lot.

**Comment by mantas** [comment] 2022-06-24 10:35
@MrGeneration this may be related to the new email verification gem. Feel free to assign it to me if you can verify it.

**Comment by GretaD** [comment] 2022-06-24 12:31
> 

most probably i can, but i dont know how to open a support case. I tried like 5 minutes before opening this issue.

**Comment by MrGeneration** [comment] 2022-06-24 12:42
>  most probably i can, but i dont know how to open a support case. I tried like 5 minutes before opening this issue.


If you're really an agent of above mentioned Zammad instance ask your instance administrator if in doubt.
If above instance is just "any instance" you've picked don't mind me.

**Comment by MrGeneration** [comment] 2022-06-29 12:09
I'm unable to reproduce this issue with the provided information.

If your problem persists and you do not have support, please refer the Zammad community over at: https://community.zammad.org .

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Closed as completed by MrGeneration** 2022-06-29 12:09 UTC
Labels: can't reproduce

**Comment by GretaD** [comment] 2022-06-29 12:12
thanks for checkig
