### ISSUE TITLE
LDAP Integration eDirectoy doesn't find user entries/attributes

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1088] opened 2017-05-15 12:18 UTC
Hello,

first of all, you did a great work with zammad!
Second, I'm pretty new to this topic, so please pardon me, if I should mix up some stuff or have do question twice.
Here are some informations to our implementation of Zammad:
### Infos:

* Used Zammad version:  cat /opt/zammad/VERSION 1.5.x
* Used Zammad installation source: (source, package, ...) Ubuntu DEB
* Operating system:  cat /proc/version Linux version 4.4.0-75-generic (buildd@lgw01-21) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) # 96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017
* Browser + version:  Firefox 53.0.2

### Expected behavior:

We have some trouble integrationing our eDirectory LDAP.
If I use the zammad webinterface I get the following error: 
"Unable to retrive user information, please check your bind user permissions."

Here is the production.log to this:
```
I, [2017-05-15T14:09:21.918775 #26205]  INFO -- : Started POST "/api/v1/integration/ldap/bind" for 127.0.0.1 at 2017-05-15 14:09:21 +0200
I, [2017-05-15T14:09:21.920928 #26205]  INFO -- : Processing by Integration::LdapController#bind as JSON
I, [2017-05-15T14:09:21.921144 #26205]  INFO -- :   Parameters: {"base_dn"=>"o=bug", "bind_user"=>"cn=zamauth,o=bug", "bind_pw"=>"[FILTERED]", "host_url"=>"ldaps://xxx.xxx.xxxx.xxx", "ssl_verify"=>true, "ldap"=>{"base_dn"=>"o=xxx", "bind_user"=>"cn=xxxxxxx,o=xxxx", "bind_pw"=>"[FILTERED]", "host_url"=>"ldaps://xxx.xxx.xxx.xxx", "ssl_verify"=>true}}
I, [2017-05-15T14:09:22.956962 #26205]  INFO -- : Started GET "/api/v1/http_logs/ldap?limit=50&_=1494848821608" for 127.0.0.1 at 2017-05-15 14:09:22 +0200
I, [2017-05-15T14:09:22.959023 #26205]  INFO -- : Processing by HttpLogsController#index as JSON
I, [2017-05-15T14:09:22.959104 #26205]  INFO -- :   Parameters: {"limit"=>"50", "_"=>"1494848821608", "facility"=>"ldap", "http_log"=>{}}
I, [2017-05-15T14:09:22.989769 #26205]  INFO -- : Completed 200 OK in 31ms (Views: 19.5ms | ActiveRecord: 3.2ms)
I, [2017-05-15T14:09:23.098331 #26205]  INFO -- : Started GET "/api/v1/integration/ldap/job_start?_=1494848821609" for 127.0.0.1 at 2017-05-15 14:09:23 +0200
I, [2017-05-15T14:09:23.104774 #26205]  INFO -- : Processing by Integration::LdapController#job_start_index as JSON
I, [2017-05-15T14:09:23.104977 #26205]  INFO -- :   Parameters: {"_"=>"1494848821609", "ldap"=>{}}
I, [2017-05-15T14:09:23.117086 #26205]  INFO -- : Completed 200 OK in 12ms (Views: 0.2ms | ActiveRecord: 3.2ms)
I, [2017-05-15T14:09:23.145780 #26205]  INFO -- : Completed 200 OK in 1225ms (Views: 2.6ms | ActiveRecord: 3.9ms)
```
On the other hand, if I use the Zammad’s Rails console to setup the ldap config like in #981 zammad can kind a sync with our eDir:

```
Last sync
05/15/2017 13:54 - 05/15/2017 13:55
    LDAP user to Zammad user (901/901):
        Users: 0 created, 0 updated, 0 untouched, 901 skipped, 0 failed 
```

The problem now is, I'm still not able to use a eDir user for logging and I can't do an attribute mapping via webinterface.

**Comment by thorsteneckel** [comment] 2017-05-15 13:36
Hi @MamoulianDelacroix - Thanks ☺️

Zammad wasn't able to get any user attributes from your eDirectory. What would be the user or group filters/objects you would use generally?

Could you please use the [Zammad Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console) and execute (via copy/paste) the following commands at once with your changed credentials and stuff:

```ruby
params = {
  "base_dn"    => "o=bug",
  "bind_user"  => "cn=zamauth,o=bug",
  "bind_pw"    => "[FILTERED]",
  "host_url"   => "ldaps://xxx.xxx.xxxx.xxx",
  "ssl_verify" => true,
}

ldap  = ::Ldap.new(params)
user  = ::Ldap::User.new(params, ldap: ldap)
group = ::Ldap::Group.new(params, ldap: ldap)
p user
p group
```

Please paste the output here.

**Comment by MamoulianDelacroix** [comment] 2017-05-15 14:55
Hi @thorsteneckel ,
thank you for you very quick response.
I think I now have a hint what cases the problem here.

irb(main):053:0> ldap  = ::Ldap.new(params)
Deprecation warning: Net::LDAP::ConnectionRefused will be deprecated. Use Errno::ECONNREFUSED instead.
```
Exceptions::UnprocessableEntity: Can't connect to '' on port '389', Connection refused - connect(2) for 127.0.0.1:389
        from /opt/zammad/lib/ldap.rb:140:in `rescue in binded_connection'
        from /opt/zammad/lib/ldap.rb:128:in `binded_connection'
        from /opt/zammad/lib/ldap.rb:122:in `connect'
        from /opt/zammad/lib/ldap.rb:38:in `initialize'
        from (irb):53:in `new'
        from (irb):53
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'
```
Our eDir onyl response to port 636. Sadly I can't get ruby to use the port 636. I've already tried the follwing:
```
irb(main):018:0> params = {
irb(main):019:1*   "base_dn"    => "o=bug",
irb(main):020:1*   "bind_user"  => "cn=zamauth,o=bug",
irb(main):021:1*   "bind_pw"    => "xxxxxxx",
irb(main):022:1*   "host_url"   => "ldaps://xx.xxx.xxx.xxx:636",
irb(main):023:1*   "ssl_verify" => true,
irb(main):024:1* }
=> {"base_dn"=>"o=bug", "bind_user"=>"cn=zamauth,o=bug", "bind_pw"=>"xxxxxxxx", "host_url"=>"ldaps://xxx.xxx.xxx.xxx:636", "ssl_verify"=>true}
irb(main):025:0> ldap  = ::Ldap.new(params)
Deprecation warning: Net::LDAP::ConnectionRefused will be deprecated. Use Errno::ECONNREFUSED instead.
Exceptions::UnprocessableEntity: Can't connect to '' on port '389', Connection refused - connect(2) for 127.0.0.1:389
```
and 
```
irb(main):045:1*   "base_dn"    => "o=bug",
irb(main):046:1*   "bind_user"  => "cn=zamauth,o=bug",
irb(main):047:1*   "bind_pw"    => "xxxxx",
irb(main):048:1*   "host_url"   => "ldaps://xxx.xxx.xxx.xxx",
irb(main):049:1*   "ssl_verify" => true,
irb(main):050:1*   "port"         => "636",
irb(main):051:1*   "encryption"   => "simple_tls",
irb(main):052:1* }
=> {"base_dn"=>"o=bug", "bind_user"=>"cn=zamauth,o=bug", "bind_pw"=>"xxxxx", "host_url"=>"ldaps://xxx.xxx.xxx.xxx", "ssl_verify"=>true, "port"=>"636", "encryption"=>"simple_tls"}
irb(main):053:0> ldap  = ::Ldap.new(params)
Deprecation warning: Net::LDAP::ConnectionRefused will be deprecated. Use Errno::ECONNREFUSED instead.
Exceptions::UnprocessableEntity: Can't connect to '' on port '389', Connection refused - connect(2) for 127.0.0.1:389
```

**Comment by thorsteneckel** [comment] 2017-05-15 16:00
Hi @MamoulianDelacroix - sorry, I made a copy paste error. The right params (keys) should look like:

```
params = {
  base_dn:    "o=bug",
  bind_user:  "cn=zamauth,o=bug",
  bind_pw:    "[FILTERED]",
  host_url:   "ldaps://xxx.xxx.xxxx.xxx",
  ssl_verify: true,
}
```

JFI: Zammad will use port `636` by default for LDAPS connections 🤓

**Comment by MamoulianDelacroix** [comment] 2017-05-16 05:58
Now, everything looks a bit different :-)
```
irb(main):008:0> ldap  = ::Ldap.new(params)
=> #<Ldap:0x0055e76782b118 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxx", :host_url=>"ldaps://xxxxxxxxx", :ssl_verify=>true}, @host="xxxxxxxxx", @port=636, @ssl=true, @host_url="ldaps://xxxxxxxxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="xxxxxxxxx", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e76782ac40 @host="xxxxxxxxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e7678206f0 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>
```
```
irb(main):009:0> user  = ::Ldap::User.new(params, ldap: ldap)
=> #<Ldap::User:0x0055e7677d5330 @ldap=#<Ldap:0x0055e76782b118 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxx", :host_url=>"ldaps://xxxxxxxxx", :ssl_verify=>true}, @host="xxxxxxxxx", @port=636, @ssl=true, @host_url="ldaps://xxxxxxxxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="xxxxxxxxx", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e76782ac40 @host="xxxxxxxxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e7678206f0 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>, @uid_attribute=nil, @filter=nil>
```
```
irb(main):010:0> group = ::Ldap::Group.new(params, ldap: ldap)
=> #<Ldap::Group:0x0055e7677b1200 @ldap=#<Ldap:0x0055e76782b118 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxx", :host_url=>"ldaps://xxxxxxxxx", :ssl_verify=>true}, @host="xxxxxxxxx", @port=636, @ssl=true, @host_url="ldaps://xxxxxxxxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="xxxxxxxxx", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e76782ac40 @host="xxxxxxxxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e7678206f0 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>, @uid_attribute=nil, @filter=nil>
```
```
irb(main):011:0> p user
#<Ldap::User:0x0055e7677d5330 @ldap=#<Ldap:0x0055e76782b118 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxx", :host_url=>"ldaps://xxxxxxxxx", :ssl_verify=>true}, @host="xxxxxxxxx", @port=636, @ssl=true, @host_url="ldaps://xxxxxxxxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="xxxxxxxxx", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e76782ac40 @host="xxxxxxxxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e7678206f0 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>, @uid_attribute=nil, @filter=nil>
=> #<Ldap::User:0x0055e7677d5330 @ldap=#<Ldap:0x0055e76782b118 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxx", :host_url=>"ldaps://xxxxxxxxx", :ssl_verify=>true}, @host="xxxxxxxxx", @port=636, @ssl=true, @host_url="ldaps://xxxxxxxxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="xxxxxxxxx", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e76782ac40 @host="xxxxxxxxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e7678206f0 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>, @uid_attribute=nil, @filter=nil>
```
```
irb(main):012:0> p group
#<Ldap::Group:0x0055e7677b1200 @ldap=#<Ldap:0x0055e76782b118 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxx", :host_url=>"ldaps://xxxxxxxxx", :ssl_verify=>true}, @host="xxxxxxxxx", @port=636, @ssl=true, @host_url="ldaps://xxxxxxxxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="xxxxxxxxx", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e76782ac40 @host="xxxxxxxxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e7678206f0 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>, @uid_attribute=nil, @filter=nil>
=> #<Ldap::Group:0x0055e7677b1200 @ldap=#<Ldap:0x0055e76782b118 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxx", :host_url=>"ldaps://xxxxxxxxx", :ssl_verify=>true}, @host="xxxxxxxxx", @port=636, @ssl=true, @host_url="ldaps://xxxxxxxxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="xxxxxxxxx", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e76782ac40 @host="xxxxxxxxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e7678206f0 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>, @uid_attribute=nil, @filter=nil>
irb(main):013:0>
```

**Comment by thorsteneckel** [comment] 2017-05-16 06:52
Nice! Looks good to me. What are the results of these lines?

```ruby
params = {
  base_dn:    "o=bug",
  bind_user:  "cn=zamauth,o=bug",
  bind_pw:    "[FILTERED]",
  host_url:   "ldaps://xxx.xxx.xxxx.xxx",
  ssl_verify: true,
}

ldap  = ::Ldap.new(params)
user  = ::Ldap::User.new(params, ldap: ldap)
group = ::Ldap::Group.new(params, ldap: ldap)

# newly added commands:
user.filter
user.attributes
user.uid_attribute

group.filter
group.list
group.uid_attribute
```

**Comment by MamoulianDelacroix** [comment] 2017-05-16 06:56
```
irb(main):014:0* user.filter
=> "(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))"
```

```
irb(main):015:0> user.attributes
=> {}
```

```
irb(main):016:0> user.uid_attribute
=> nil
```

```
irb(main):017:0> group.filter
=> "(objectClass=group)"
```

```
irb(main):018:0> group.list

=> a pretty hughe list of all our groups :-)

```
irb(main):019:0> group.uid_attribute
=> "dn"
```

**Comment by thorsteneckel** [comment] 2017-05-16 07:06
Wow, that was fast! New round - since the output is a mixture of strange and good:

```ruby
params = {
  base_dn:    "o=bug",
  bind_user:  "cn=zamauth,o=bug",
  bind_pw:    "[FILTERED]",
  host_url:   "ldaps://xxx.xxx.xxxx.xxx",
  ssl_verify: true,
}

ldap  = ::Ldap.new(params)

ldap.search('(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))') do |entry|
  attribute_names = entry.attribute_names
  p "attribute_names = #{attribute_names}"

  attribute_names.each do |attribute|
    p "#{attribute} = #{entry[attribute].inspect}"
  end

  p "------------------------------------"
end
```

**Comment by MamoulianDelacroix** [comment] 2017-05-16 07:30
```
irb(main):020:0> ldap  = ::Ldap.new(params)
=> #<Ldap:0x0055e766f65f88 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxxxx", :host_url=>"ldaps://xxx.xxx.xxx.xxx", :ssl_verify=>true}, @host="xxx.xxx.xxx.xxx", @port=636, @ssl=true, @host_url="ldaps://xxx.xxx.xxx.xxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="full176necessary", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e766f65ba0 @host="xxx.xxx.xxx.xxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e766f52348 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>
```
A colleague of mine gava me a friendly reminder, that we have a Novell eDirectory instaed of a Microsoft Acitve Directoy, so I switched the value "samaccount" to "cn".  lo and behold I get some values back instead of just false with "samaccount" :-)
```
ldap.search('(&(objectClass=user)(cn=*)(!(cn=*$)))') do |entry|
  attribute_names = entry.attribute_names
  p "attribute_names = #{attribute_names}"

  attribute_names.each do |attribute|
    p "#{attribute} = #{entry[attribute].inspect}"
  end

  p "------------------------------------"
end
```
exemplary one entry 
```
"attribute_names = [:dn, :mail, :uid, :givenname, :sn, :objectclass, :emailaddress, :groupmembership, :description, :cn]"
"dn = [\"cn=zogaj_f,ou=sps-hn,ou=sgr,o=bug\"]"
"mail = [\"zogaj.f@xxxxxx-xxxxxxxxxx.xx\", \"xxxxx_xxx@xxxx-xxxxxx.xxx\"]"
"uid = [\"xxxxx_x\"]"
"givenname = [\"xxxxx\"]"
"sn = [\"xxxxxx\"]"
"objectclass = [\"inetOrgPerson\", \"organizationalPerson\", \"Person\", \"ndsLoginProperties\", \"Top\"]"
"emailaddress = [\"7#xxxxx.x@xxxxxxxx-xxxxxxx.xx\"]"
"groupmembership = [\"cn=SPSHNALLUSERS,ou=xxx-hn,ou=xxx,o=bug\", \"cn=SURFER,ou=xxx,o=bug\", \"cn=xxxx-QM,ou=xxxx,o=bug\", \"cn=xxx-xx-xxx,ou=xxx-hn,ou=xxx,o=bug\"]"
"description = [\"eMail+Surfen\"]"
"cn = [\"xxxx_xx\"]"
"------------------------------------"
=> true
```

**Comment by thorsteneckel** [comment] 2017-05-16 07:51
It's strange that you get false with `samaccount` but Zammad detects this as a valid filter 🤔 Zammad behaves as follows:

- [go through a list of possible filters](https://github.com/zammad/zammad/blob/c9b2255e4fab7ab714e002db19e6248450bda8b1/lib/ldap/user.rb#L165)
- [check each for entries](https://github.com/zammad/zammad/blob/c9b2255e4fab7ab714e002db19e6248450bda8b1/lib/ldap/filter_lookup.rb#L14)
- [return first with found entries](https://github.com/zammad/zammad/blob/c9b2255e4fab7ab714e002db19e6248450bda8b1/lib/ldap/filter_lookup.rb#L15)

That means that Zammad should have found at least one entry with the `samaccount` filter.

And another try:

```ruby

params = {
  base_dn:    "o=bug",
  bind_user:  "cn=zamauth,o=bug",
  bind_pw:    "[FILTERED]",
  host_url:   "ldaps://xxx.xxx.xxxx.xxx",
  ssl_verify: true,
}

ldap  = ::Ldap.new(params)

count = 0
ldap.search('(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))') do |_entry|
  count += 1
end

entries = ldap.entries?('(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))')

p "count = #{count}"
p "entries = #{entries}"
```

Greetings to your colleague btw 👋

**Comment by MamoulianDelacroix** [comment] 2017-05-16 07:55
```
irb(main):052:0> ldap  = ::Ldap.new(params)
=> #<Ldap:0x0055e767840270 @config={:base_dn=>"o=bug", :bind_user=>"cn=zamauth,o=bug", :bind_pw=>"xxxxxxxxxx", :host_url=>"ldaps://xxxxxxxxxx", :ssl_verify=>true}, @host="xxxxxxxxxx", @port=636, @ssl=true, @host_url="ldaps://xxxxxxxxxx", @protocol=:ldaps, @encryption={:method=>:simple_tls, :tls_options=>{}}, @bind_user="cn=zamauth,o=bug", @bind_pw="xxxxxxxxxx", @base_dn="o=bug", @connection=#<Net::LDAP:0x0055e767837c10 @host="xxxxxxxxxx", @port=636, @hosts=nil, @verbose=false, @auth={:method=>:simple, :username=>"cn=zamauth,o=bug", :password=>"*******"}, @base="dc=com", @force_no_page=false, @encryption={:method=>:simple_tls, :tls_options=>{}}, @connect_timeout=nil, @instrumentation_service=nil, @open_connection=nil, @result=#<Net::LDAP::PDU:0x0055e76782b4d8 @message_id=1, @app_tag=1, @ldap_controls=[], @ldap_result={:resultCode=>0, :matchedDN=>"", :errorMessage=>""}>>>
irb(main):053:0> count = 0
=> 0
```
```
irb(main):054:0> ldap.search('(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))') do |_entry|
irb(main):055:1*   count += 1
irb(main):056:1> end
=> false
```
```
irb(main):057:0> entries = ldap.entries?('(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))')
=> true
```
```
irb(main):058:0>
irb(main):059:0* p "count = #{count}"
"count = 0"
=> "count = 0"
```
```
irb(main):060:0> p "entries = #{entries}"
"entries = true"
=> "entries = true"
```

**Comment by thorsteneckel** [comment] 2017-05-16 07:57
There is the issue :) I'll try to reproduce it in our test environment and come back to you. Thanks so far for your help!

**Comment by MamoulianDelacroix** [comment] 2017-05-16 08:13
Cool, thanks.
*crossing fingers*

**Comment by thorsteneckel** [comment] 2017-05-16 09:17
Bad news - I couldn't reproduce this with our test LDAP server. However I think I have a more robust solution I need you to test for me 🤓 

Please create a new file called `ldap_test.rb` in your Zammad root directory.

Copy/paste the following code into that new file and update your LDAP credentials (as usual ;):

```ruby
params = {
  base_dn:    "o=bug",
  bind_user:  "cn=zamauth,o=bug",
  bind_pw:    "[FILTERED]",
  host_url:   "ldaps://xxx.xxx.xxxx.xxx",
  ssl_verify: true,
}

class Ldap
  def entries?(*args)
    found = false
    search(*args) do |_entry|
      found = true
      break
    end
    found
  end
end

ldap  = ::Ldap.new(params)
user  = ::Ldap::User.new(params, ldap: ldap)
group = ::Ldap::Group.new(params, ldap: ldap)

p "user.filter = #{user.filter.inspect}"
p "user.attributes = #{user.attributes.inspect}"
p "user.uid_attribute = #{user.uid_attribute.inspect}"

p "group.filter = #{group.filter.inspect}"
p "group.list = #{group.list.inspect}"
p "group.uid_attribute = #{group.uid_attribute.inspect}"
```

Execute the file with `zammad run rails r ldap_test.rb` and post the output here. Thanks!

**Comment by MamoulianDelacroix** [comment] 2017-05-16 09:37
Here is the output. It looks kind a good :-)
```
"user.filter = \"(objectClass=user)\""
"user.attributes = {:dn=>\"dn (e. g. cn=admin,o=bug)\", :loginshell=>\"loginshell (e. g. /bin/bash)\", :homedirectory=>\"homedirectory (e. g. /home/admin)\", :gidnumber=>\"gidnumber (e. g. 616)\", :uidnumber=>\"uidnumber (e. g. 600)\", :uid=>\"uid (e. g. admin)\", :messageserver=>\"messageserver (e. g. cn=GWS01CL2,o=bug)\", :sn=>\"sn (e. g. admin)\", :groupmembership=>\"groupmembership (e. g. cn=admin,ou=Tomcat-Roles,o=bug)\", :cn=>\"cn (e. g. admin)\", :description=>\"description (e. g. NFAU Admin User Object)\", :mail=>\"mail (e. g. baehr@dsb.net)\", :givenname=>\"givenname (e. g. Joerg)\", :networkaddress=>\"networkaddress (e. g. 9#\\u0000\\u0000?\\u0014\\u0006~)\", :emailaddress=>\"emailaddress (e. g. 7#baehr@dsb.net)\", :masvauthorizedrange=>\"masvauthorizedrange (e. g. \\u0000\\u0000\\u0000\\u0000\\u0001\\b\\n2\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000????????\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0001\\b\\n2\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000????????\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000)\", :masvdefaultrange=>\"masvdefaultrange (e. g. \\u0000\\u0000\\u0000\\u0000\\u0001\\b\\n2\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000????????\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0001\\b\\n2\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000????????\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000)\", :sasdefaultloginsequence=>\"sasdefaultloginsequence (e. g. <no default>)\"}"
"user.uid_attribute = \"uid\""
"group.filter = \"(objectClass=group)\""
"group.list = {\"cn=apchadmn-administrators,o=bug\"=>\"cn=apchadmn-administrators,o=bug\", and a lot of more groups :-)
```

**Comment by thorsteneckel** [comment] 2017-05-16 09:48
Sweet! Fix incoming 🛬

**Comment by thorsteneckel** [comment] 2017-05-16 10:22
Fixed with the commits above. The new code should look familiar to you ;) Please wait ~45 minutes before updating to the newest version of Zammad 1.5 which will include the fix. Thanks for your support finding this. Closing now. Feedback is appreciated.

**Closed by thorsteneckel** 2017-05-16 10:22 UTC
Labels: bug

**Comment by MamoulianDelacroix** [comment] 2017-05-16 13:15
Great thing!
It's working now!
Thank you very munch :-)

**Comment by thorsteneckel** [comment] 2017-05-16 13:16
Thanks for the feedback. Glad I could help!
