### ISSUE TITLE
LDAP without anonymous bind is not possible

### ISSUE THREAD

**Issue by rmalchow** [zammad/zammad#3289] opened 2020-11-18 11:20 UTC
### Infos:

* Used Zammad version: "latest" as of today (should be zammad-3.6.0-1)
* Installation method (source, package, ..): docker compose
* Operating system: host is on fedora, docker 19.03 
* Database + version: pgsql, as per docker compose /w version "-latest"
* Elasticsearch version: as per docker compose /w version "-latest"
* Browser + version: as per docker compose /w version "-latest"

this has been reported before, but i still consider this a bug. i am trying to set up LDAP in zammad with anonymous bind disabled on the ldap server. my reasoning is that it is simply a matter of asking for bind user credentials one step earlier - but the result is that it breaks the entire LDAP integration. 

expection LDAP servers to allow anonymous binds is also not a reasonable assumption.

### Expected behavior:
* if anonymous bind fails with authentication exception (>>>error 49), ask for credentials

### Actual behavior:
* error message "cannot bind, error 49", wizard essentially breaks

### Steps to reproduce the behavior:
* set up zammad as per docker compose instructions, then go to integrations -> LDAP -> configure and enter URL of an LDAP server that does not allow anonymous bind.

**Comment by MrGeneration** [comment] 2020-11-18 11:24
I failed to find the issue you're talking about.
This is in my opinion a feature request and not a bug.

In todays world I personally wouldn't use anonymous binds in LDAP context at all.
If this is a feature request (or enhancement), please post that request on the community.

**Comment by tilllt** [comment] 2020-11-18 12:26
How to get to the Problem:
- Start LDAP integration configuration
- Enter address of LDAP server with "Anonymous Bind" disabled

In Zammad 3.5 / Docker, Anonymous Bind disabled, you will receive this message:
`Can't connect to 'ldap.example.de' on port '636', Can't bind to 'ldap.n0ne.de', 49, Invalid Credentials`

In Zammad 3.5 / Docker, Anonymous Bind enabled, you will receive this dialog:
![Screenshot_23](https://user-images.githubusercontent.com/1854364/99530359-7be4d580-29a1-11eb-8054-25c858639930.jpg)

So maybe its a UI misunderstanding, but to me it looks as if you ONLY can get to the LDAP Configuration Wizard if Anonymous Bind is enabled. The problem is that you especially need to specity your credentials if Anonymous Bind is DISABLED, but there you cannot enter them.

**Comment by MrGeneration** [comment] 2020-11-18 12:28
Sorry, but this seems to be a technical question.
Like really it is, just correct the ``Base DN``  to yours and fill in Bind user and password.

---

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by tilllt** [comment] 2020-11-18 12:29
The point being (again) 

1.  you cannot enter a base DN without the wizard.
2. The wizard only pops up when Anonymous Bind is enabled in your LDAP server

**Comment by rmalchow** [comment] 2020-11-18 15:06
so, here's the sequence:

ldap://192.168.71.220:390 

is an apache ds with anonymous bind disabled. i have gitlab, nextcloud, and various other services authenticate against it just fine. but those all allow entering bind user credentials _before_ trying it. i would be ok if zammad would try without, then ask for credentials if that fails. but the fact that in this scenario basically stops here and doesnt let me enter creds is, i think, a bug. also, i wonder why the documentation shows the available root DSEs ... if there isnt any anonymous bind, this also shouldnt be possible.

![Screenshot from 2020-11-18 15 59 23](https://user-images.githubusercontent.com/4213287/99546868-2d423600-29b7-11eb-9c04-01aaf15bc72f.png)
![Screenshot from 2020-11-18 15 59 37](https://user-images.githubusercontent.com/4213287/99546875-2fa49000-29b7-11eb-9a9f-7bcb14cb5095.png)

**Comment by rmalchow** [comment] 2020-11-18 17:21
... don't get me wrong, it is possible that somewhere there is a big misunderstanding somewhere. but if that is the case, then maybe there is an opportunity to improve the documentation?

**Comment by MrGeneration** [comment] 2020-11-18 17:37
Please wait for the verification process on our end.
This may take time. With voer 2000 stars this repo causes a lot of notifications for everyone watching.

**Comment by dominikklein** [comment] 2023-05-02 18:31
Duplicate of https://github.com/zammad/zammad/issues/4471

**Closed as completed by dominikklein** 2023-05-02 18:31 UTC
Labels: duplicate
