### ISSUE TITLE
multiple outbound email appearance

### ISSUE THREAD

**Issue by MuadDib01** [zammad/zammad#1342] opened 2017-08-13 14:32 UTC
After resetting the database by following commands a second entry of outbound email appeared in the UI and the old settings remained. Both entries share the same settings.

commands:

zammad run rake db:drop
zammad run rake db:create
zammad run rake db:migrate
zammad run rake db:seed

### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: package DEB
* Operating system:  Ubuntu 16.04
* Browser + version: all

### Expected behavior:

* single outbound email entry

### Actual behavior:

* multiple outbound email entries

### Steps to reproduce the behavior:

commands used:

zammad run rake db:drop
zammad run rake db:create
zammad run rake db:migrate
zammad run rake db:seed

In UI setup outbound email account

**Comment by hanneshal** [comment] 2017-08-13 21:06
Hi @MuadDib01,

can you provide a screenshot for this, so that we are talking about the same. 
I never saw such behaviour in Zammd, and I use rake db:drop ... a lot. 

Possible causes:
- browser cache
- problem in the seed file of your version or modified seed file
- the db is not completely dropped, caused by an issue 
- you dropped the wrong db ;) (unlikely)

Is there any output when you ran rake db:drop and can you provide this?

regards

**Comment by MuadDib01** [comment] 2017-08-14 18:10
Hello  hanneshal,

we have tested it with different browsers. Unfortunately I didn't pay too much attention but I couldn't see an error after the commands have been applied.

Is it possible to delete the object via cli?

**Comment by hanneshal** [comment] 2017-08-15 09:34
@MuadDib01 I still don't know what object we are talking about. Thats why I asked for a screenshot ;) 

Maybe it is possible via CLI but in the first place I need to know what about we are talking 👓

**Comment by MuadDib01** [comment] 2017-08-15 09:57
@hanneshal I have uploaded a screenshot to clearify the issue.

![smtp_duplicate](https://user-images.githubusercontent.com/30979774/29311117-cec834fa-81b0-11e7-8add-35e47548aedf.png)

**Comment by thorsteneckel** [comment] 2018-01-03 08:30
Hi @MuadDib01 - Is this issue still relevant?

**Comment by thorsteneckel** [comment] 2018-01-25 16:54
Closing due to missing feedback.

**Closed by thorsteneckel** 2018-01-25 16:54 UTC
Labels: wontfix
