### ISSUE TITLE
Problem overviews on mobile devices

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#2226] opened 2018-09-06 12:25 UTC
* Used Zammad version: 2.6
* Installation method (source, package, ..): packages
* Operating system: Ubuntu 18.04
* Database + version: PostgreSQL 10.5
* Elasticsearch version: elasticsearch 5.6.11
* Browser + version: current Chrome-Version

👋 Hihi everyone,
I hope you all had greate summer-vacations 😄 

Today I wanted to use our zammad on my android-smartphone (Huwai P8 Lite 2017) and sadly I had to discover, that I can't use the overviews. I was able to switch to the menu point overviews and the first 3 overviews were useable, but as soon as I had to use the dropdown menu to extend my view to the other overviews, they weren't clickable. Like here in the image:
![screenshot_20180906-141153](https://user-images.githubusercontent.com/4436931/45157032-34b70380-b1e0-11e8-8b61-be36afc08f63.jpg)

I also did test it from an Samsung S7 and S9 on all three device I wasn't able to select any point of these dropdown menu.

Am I doing something wrong or did I missing something? 🤔 

Greetings

**Comment by MrGeneration** [comment] 2018-09-06 12:35
Zammad currently does not support Mobile Views - we have that on our roadmap, but I don't think we'll manage to change that too soon. Help is apprieciated if someone wants to help here.

I will close this issue, as it's duplicate of existing tickets to keep our list as clean as possible.
Sorry about the trouble you encountered.

duplicate of #223

**Closed as completed by MrGeneration** 2018-09-06 12:35 UTC
Labels: duplicate

**Comment by martini** [comment] 2018-11-13 09:32
Update: This is actually a but and it's not about general mobile UI for mobiles. Good now, this is fixed in develop https://github.com/zammad/zammad/issues/2330 and soon in stable too.
