### ISSUE TITLE
heavy system load causes users a unable to login

### ISSUE THREAD

**Issue by SGVubmluZ0cK** [zammad/zammad#1036] opened 2017-05-04 07:53 UTC
### Infos:

* Zammad version: 1.5
* Zammad installed from deb-package
* Operating system: Ubuntu Server 16.04
* Browser + version: Firefox 53
* 4 CPU
* 6 GB RAM

### Expected behavior:

* the system keeps accessible  

### Actual behavior:

* logged in users are experiening very long response times 
* not logged in users can't login
* zammad (3 ruby processes) consumed 90 % ram in less than 2 hours after reboot

**tail of the production.log**
```
E, [2017-05-04T09:29:05.532997 #941] ERROR -- : error in reading/parsing session file '/opt/zammad/tmp/websocket_production/3350648049/session', remove session.
E, [2017-05-04T09:29:07.362104 #2992] ERROR -- : thread_client 2629113818 exited with error #<PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections
E, [2017-05-04T09:29:17.449715 #2992] ERROR -- : thread_client 2629113818 exited with error #<PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections
E, [2017-05-04T09:29:27.470713 #2992] ERROR -- : thread_client 2629113818 exited with error #<PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections
E, [2017-05-04T09:29:37.556426 #2992] ERROR -- : thread_client 2629113818 exited with error #<PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections
E, [2017-05-04T09:29:47.575789 #2992] ERROR -- : thread_client 2629113818 exited with error #<PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections
E, [2017-05-04T09:29:48.936485 #941] ERROR -- : error in reading/parsing session file '/opt/zammad/tmp/websocket_production/2629113818/session', remove session.
E, [2017-05-04T09:29:50.149821 #2992] ERROR -- : thread_client 5798829686 exited with error #<PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections
E, [2017-05-04T09:29:57.695778 #941] ERROR -- : error in reading/parsing session file '/opt/zammad/tmp/websocket_production/5798829686/session', remove session.
E, [2017-05-04T09:30:25.646395 #941] ERROR -- : error in reading/parsing session file '/opt/zammad/tmp/websocket_production/1620960942/session', remove session.
E, [2017-05-04T09:30:27.021616 #941] ERROR -- : error in reading/parsing session file '/opt/zammad/tmp/websocket_production/4435044124/session', remove session.
```

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment] 2017-05-04 09:31
Looks like your DB is under heavy load or configured to allow to less connections. Could you please provide an anonymized output of the following query:
`SELECT * FROM pg_stat_activity;`

**Comment by SGVubmluZ0cK** [comment] 2017-05-04 09:44
**The query ouput (SELECT * FROM pg_stat_activity;)**
  datid | datname | pid  | usesysid | usename  |      application_name      | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | waiting |        state        | backend_xid | backend_xmin |                                                                                            query
-------+---------+------+----------+----------+----------------------------+-------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+---------+---------------------+-------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 16384 | zammad  | 6005 |       10 | postgres | psql                       |             |                 |          -1 | 2017-05-04 11:35:10.792078+02 | 2017-05-04 11:41:52.469224+02 | 2017-05-04 11:41:52.469224+02 | 2017-05-04 11:41:52.469225+02 | f       | active              |             |      1235378 | SELECT * FROM pg_stat_activity;
 16384 | zammad  | 6006 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:17.609655+02 |                               | 2017-05-04 11:41:52.456824+02 | 2017-05-04 11:41:52.456856+02 | f       | idle                |             |              | SELECT "organizations".id FROM "organizations" INNER JOIN "organizations_users" ON "organizations"."id" = "organizations_users"."organization_id" WHERE "organizations_users"."user_id" = $1
 16384 | zammad  | 6007 |    16385 | zammad   | script/websocket-server.rb |             |                 |          -1 | 2017-05-04 11:35:17.609875+02 |                               | 2017-05-04 11:35:19.377289+02 | 2017-05-04 11:35:19.377326+02 | f       | idle                |             |              | SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT 1
 16384 | zammad  | 6450 |    16385 | zammad   | script/scheduler.rb        |             |                 |          -1 | 2017-05-04 11:41:06.596742+02 |                               | 2017-05-04 11:41:06.606003+02 | 2017-05-04 11:41:06.60616+02  | f       | idle                |             |              | SELECT "schedulers".* FROM "schedulers" WHERE (active = 't')  ORDER BY prio ASC
 16384 | zammad  | 6382 |    16385 | zammad   | script/scheduler.rb        |             |                 |          -1 | 2017-05-04 11:39:36.591145+02 |                               | 2017-05-04 11:39:36.604448+02 | 2017-05-04 11:39:36.605185+02 | f       | idle                |             |              | COMMIT
 16384 | zammad  | 6025 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:24.791395+02 |                               | 2017-05-04 11:41:52.463543+02 | 2017-05-04 11:41:52.463576+02 | f       | idle                |             |              | SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1
 16384 | zammad  | 6026 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:24.847302+02 |                               | 2017-05-04 11:41:52.41784+02  | 2017-05-04 11:41:52.417857+02 | f       | idle                |             |              | SELECT "authorizations".id FROM "authorizations" WHERE "authorizations"."user_id" = $1
 16384 | zammad  | 6027 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:25.06028+02  |                               | 2017-05-04 11:41:52.468567+02 | 2017-05-04 11:41:52.468602+02 | f       | idle                |             |              | SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1
 16384 | zammad  | 6028 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:25.141042+02 |                               | 2017-05-04 11:41:52.385097+02 | 2017-05-04 11:41:52.385154+02 | f       | idle                |             |              | SELECT  "tickets".* FROM "tickets" WHERE "tickets"."id" = $1 LIMIT 1
 16384 | zammad  | 6030 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:25.597798+02 |                               | 2017-05-04 11:41:50.993531+02 | 2017-05-04 11:41:50.993564+02 | f       | idle                |             |              | COMMIT
 16384 | zammad  | 6032 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:25.913477+02 |                               | 2017-05-04 11:41:52.407232+02 | 2017-05-04 11:41:52.407278+02 | f       | idle                |             |              | SELECT "organizations".id FROM "organizations" INNER JOIN "organizations_users" ON "organizations"."id" = "organizations_users"."organization_id" WHERE "organizations_users"."user_id" = $1
 16384 | zammad  | 6034 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:26.446424+02 |                               | 2017-05-04 11:41:44.104333+02 | 2017-05-04 11:41:44.104371+02 | f       | idle                |             |              | SELECT  "sessions".* FROM "sessions" WHERE "sessions"."session_id" = $1  ORDER BY "sessions"."id" ASC LIMIT 1
 16384 | zammad  | 6036 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:26.623251+02 |                               | 2017-05-04 11:41:52.469478+02 | 2017-05-04 11:41:52.469491+02 | f       | idle                |             |              | SELECT "authorizations".id FROM "authorizations" WHERE "authorizations"."user_id" = $1
 16384 | zammad  | 6038 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:26.833354+02 |                               | 2017-05-04 11:41:52.279838+02 | 2017-05-04 11:41:52.279866+02 | f       | idle                |             |              | COMMIT
 16384 | zammad  | 6040 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:29.199387+02 |                               | 2017-05-04 11:41:52.460484+02 | 2017-05-04 11:41:52.460514+02 | f       | idle                |             |              | SELECT "organizations".id FROM "organizations" INNER JOIN "organizations_users" ON "organizations"."id" = "organizations_users"."organization_id" WHERE "organizations_users"."user_id" = $1
 16384 | zammad  | 6385 |    16385 | zammad   | script/scheduler.rb        |             |                 |          -1 | 2017-05-04 11:39:36.616153+02 |                               | 2017-05-04 11:41:52.430544+02 | 2017-05-04 11:41:52.43056+02  | f       | idle                |             |              | SELECT "authorizations".id FROM "authorizations" WHERE "authorizations"."user_id" = $1
 16384 | zammad  | 6049 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:30.090172+02 |                               | 2017-05-04 11:41:52.464595+02 | 2017-05-04 11:41:52.464627+02 | f       | idle                |             |              | SELECT "authorizations".id FROM "authorizations" WHERE "authorizations"."user_id" = $1
 16384 | zammad  | 6052 |    16385 | zammad   | bin/rails                  |             |                 |          -1 | 2017-05-04 11:35:30.820403+02 |                               | 2017-05-04 11:41:49.71376+02  | 2017-05-04 11:41:49.714167+02 | f       | idle                |             |              | COMMIT

**Comment by thorsteneckel** [comment] 2017-05-04 11:59
Strange. Your error log prompts that there are no further connections to the DB are possible but the DB looks rather relaxed. There are no long running or any huge number of queries, just 17 regular low profile queries. 

What is the configured pool size in your `config/database.yml` for production?
Your PG database should have a connection limit of 100 connections per default. Could you validate that? It would be even better to increase the limit to 500 just to be sure.

This looks like the cause for your RAM issue since the ruby processes get called a lot and have to queue and wait for the database connection.

**Comment by martini** [comment] 2017-05-16 06:26
@SGVubmluZ0cK any feedback?

**Comment by thorsteneckel** [comment] 2017-05-16 07:56
This might have a relation to #1070 since @SGVubmluZ0cK also uses/used the LDAP import. Should be fixed with the latest version. Please reopen if issue still persists.

**Closed by thorsteneckel** 2017-05-16 07:56 UTC
Labels: question

**Comment by Wisou** [comment] 2017-10-26 10:18
Hello,

I have a same problem but i dont active LDAP.
I do query SELECT * FROM pg_stat_activity;
OUTPUT [select.txt](https://github.com/zammad/zammad/files/1417884/select.txt)

Can you help me ?

BR
