### ISSUE TITLE
Many unprocessable mails

### ISSUE THREAD

**Issue by hmolinab** [zammad/zammad#3771] opened 2021-09-27 19:59 UTC
### Infos:

* Used Zammad version: zammad-4.1.0-1630076259.40e648b8.centos7.x86_64
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: PostgreSQL 10.18
* Elasticsearch version: 7.14
* Browser + version: any
* Ticket#1093409, Ticket#1092454

### Expected behavior:

* Zammad should process all emails

### Actual behavior:

* Very often Zammad is leaving messages in / opt / zammad / tmp / unprocessable_mail / and writing to the log:
```
E, [2021-09-27T10: 32: 06.878336 # 10918-47176818643100] ERROR -: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/5690ceec2ce8f63d18903133cdb1e403.eml, please create an issue at https://github.com/zammad/zammad/issues
```

```
E, [2021-09-22T16:08:46.029798 #60940-69991961960700] ERROR -- : Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/3ae250a926e46df31919ea4851a61049.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2021-09-22T16:08:46.030001 #60940-69991961960700] ERROR -- : execution expired (Timeout::Error)
/opt/zammad/lib/sessions.rb:307:in `exist?'
/opt/zammad/lib/sessions.rb:307:in `send'
/opt/zammad/lib/sessions.rb:404:in `block in broadcast'
/opt/zammad/lib/sessions.rb:393:in `each'
/opt/zammad/lib/sessions.rb:393:in `broadcast'
```

### Steps to reproduce the behavior:

* Please, let me know how I send you the emails for your evaluation

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-09-27 20:34
Please provide your production log(s) to support [at] zammad [dot] com and reference this issue.

**Comment by hmolinab** [comment] 2021-09-27 21:42
Sent.

Thanks.

**Comment by MrGeneration** [comment] 2021-09-28 14:53
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by hmolinab** [comment] 2021-09-28 15:18
MrGeneration, I've followed the Zammad's log instructions:

```
please create an issue at https://github.com/zammad/zammad/issues
```

On the other hand, I have a lot of unprocessed mails, I see it as a bug, but I'm going to follow your instructions.

Thanks.

**Comment by rolfschmidt** [comment] 2021-09-28 15:27
Hi @hmolinab ,
can you check the size of the directory?

tmp/websocket_production

How big is it? Is your websocket server running properly and stable and does the websocket connection work if you open your inspector in the browser? Like this:

Open inspector (F12), go to network tab and restrict the view of the requests to "Websockets", then reload the page.

![grafik](https://user-images.githubusercontent.com/5445062/135117690-b46efaa1-80c0-40b9-90d2-596cd205a3e2.png)

**Comment by hmolinab** [comment] 2021-09-28 21:50
The tmp/websocket_production directory has 4G and the disk graph doesn't
show space problems.

The websocket looks fine:
[image: zammad.png]

**Comment by hmolinab** [comment] 2021-09-28 21:51
Hi Rolfschmidt,

The tmp/websocket_production directory has 4G and the disk graph doesn't show space problems.

The websocket looks fine:
![Uploading zammad.png…]()

**Comment by rolfschmidt** [comment] 2021-09-29 06:53
> Hi Rolfschmidt,
> 
> The tmp/websocket_production directory has 4G and the disk graph doesn't show space problems.
> 
> The websocket looks fine:
> Uploading zammad.png…

I think that is the issue. This directory should not be so big. Can you check if the Websocket server process is running on your system? There should be a `ruby script/websocket-server.rb` in your process list. Please answer my questions if you are using the websocket server properly it would be nice to know.

To fix this issue you can do the following steps:
- Stop your zammad services.
- Remove your websocket directory content `rm -Rf /opt/zammad/tmp/websocket_production/*`
- Start your zamamd services and make sure that the websocket server is running properly

Now unprocessable emails should be handled faster because there are no dead clients sessions anymore which are hopefully the reason for the timeout in your unprocessable emails.

**Comment by rolfschmidt** [comment] 2021-09-29 06:55
ups production environment not development. so `rm -Rf /opt/zammad/tmp/websocket_production/*`

**Comment by hmolinab** [comment] 2021-09-29 13:13
Hi Rolf,

Sorry, I didn't explain myself well. tmp/websocket_production has 4G to
grow.

The web socket is running properly:

$ ps xa|grep websocket
 3376 pts/0    S+     0:00 grep --color=auto websocket
29220 ?        Rsl   12:50 script/websocket-server.rb -b 127.0.0.1 -p 6042
start

All files inside of tmp/websocket_production are fresh:
$ ll /opt/zammad/tmp/websocket_production/
total 76
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369248249460
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369287760220
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369292488980
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369298555020
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369304806460
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369304882900
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369305243940
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369305249740
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369305742140
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369306229840
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369306313360
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369306336100
drwxr-xr-x  2 zammad zammad    20 sep 29 10:03 47369306564880
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369306617320
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369306723620
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369306908360
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369308364460
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369308539380
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369308576660
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369308673060
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369308868220
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369311237620
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369311637380
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369311734440
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369313690280
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369313770780
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369320908040
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369321236820
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369323493120
drwxr-xr-x  2 zammad zammad    20 sep 29 10:02 47369327270960
drwxr-xr-x. 2 zammad zammad 49152 sep 29 10:00 spool
drwxr-xr-x. 2 zammad zammad     6 sep 29 10:00 tmp

And it's the size:
$ du -sh /opt/zammad/tmp/websocket_production/
4,7M /opt/zammad/tmp/websocket_production/

And the unprocessable mails doesn't stop (I'm moving it to
/tmp/unprocessable_mail_tmp/):
$ ll /tmp/unprocessable_mail_tmp/
total 7360
-rw-r--r-- 1 zammad zammad    5292 sep 28 17:35
1cbfd4bf7f5377c056c4ce13f6eab619.eml
-rw-r--r-- 1 zammad zammad 1352039 sep 28 17:44
30068cecca35a72ba514b68df69dee27.eml
-rw-r--r-- 1 zammad zammad  228186 sep 28 16:58
35b7bfccce05047033cc0c1ca5b4f37b.eml
-rw-r--r-- 1 zammad zammad    4917 sep 28 17:32
3fb775506cbca86937c038f7ae0b513d.eml
-rw-r--r-- 1 zammad zammad   47036 sep 27 17:54
5fea686c96381a41ec1b74a88d5c8c9e.eml
-rw-r--r-- 1 zammad zammad   60347 sep 28 18:23
6204777767e8265dcde8b30e8a55b15b.eml
-rw-r--r-- 1 zammad zammad  199964 sep 28 13:26
6409c9518b8ad048e599ef20b1437d5e.eml
-rw-r--r-- 1 zammad zammad   62646 sep 28 14:25
6f4ba5c9a6cddd666782ed9f5c08995e.eml
-rw-r--r-- 1 zammad zammad   67010 sep 28 13:10
6fe8e9934082519b720086e5ef929e63.eml
-rw-r--r-- 1 zammad zammad   32753 sep 28 17:08
9470488d5936bcabd8c52e06e26afe5a.eml
-rw-r--r-- 1 zammad zammad    5179 sep 28 16:36
b0d2968bad267061498b3d2d5215fb30.eml
-rw-r--r-- 1 zammad zammad 2164368 sep 28 11:58
c216711f7291095166422682267b69a5.eml
-rw-r--r-- 1 zammad zammad 2467484 sep 27 18:12
c39fe4a19ea60250f2206e64024ca50e.eml
-rw-r--r-- 1 zammad zammad   70558 sep 28 14:52
c82f39d8b5c2294ddfe82c9330173223.eml
-rw-r--r-- 1 zammad zammad  128589 sep 28 17:19
c85d1fe79a9c7bc8e475896a52461fa9.eml
-rw-r--r-- 1 zammad zammad   47275 sep 28 16:39
d6d90dd85ab358e48c087d7348d86982.eml
-rw-r--r-- 1 zammad zammad  101046 sep 28 15:38
d9fba85f09d538d31e26becb08e0b309.eml
-rw-r--r-- 1 zammad zammad  115097 sep 28 16:54
dd9a12ebbad0cf53c9f86c1de62a6597.eml
-rw-r--r-- 1 zammad zammad   90639 sep 28 17:16
e520f780c2e5ca03e9e1afe822d574b5.eml
-rw-r--r-- 1 zammad zammad   44064 sep 28 15:46
f14df8dbcd9bdac60106275c83297ef3.eml
-rw-r--r-- 1 zammad zammad  194465 sep 27 17:35
f18ec72a38b71426ced61149ebbc65a2.eml

Thanks.

**Comment by t-shehab** [comment] 2023-05-11 09:06
Can't be reproduced at the moment. Closing for now.

**Closed as completed by t-shehab** 2023-05-11 09:06 UTC
Labels: can't reproduce
