### ISSUE TITLE
Emails stop working sporatically

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#751] opened 2017-02-09 12:48 UTC
### Infos:

* Used Zammad version: [1.1.0](https://github.com/zammad/zammad/tree/1.1.0) (docker)
* Operating system: Ubuntu 16.04
* Browser + version: Not a front-end issue

### Expected behavior:

* Emails sent to channel-linked accounts will open ticket
* Messages sent as emails will actually be sent

### Actual behavior:

* Usually all works fine, but at least once per week, all email traffic fails
* New tickets not opened
* In-app communications not sent
* Need to restart Zammad, at which point all emails are fetched, tickets created, and all messages from app are dispatched

### Steps to reproduce the behavior:

* We can't reproduce - this happens ~weekly, but no seeming pattern

**Comment by martini** [comment] 2017-02-09 15:00
Hi @abenrob 

thanks for feedback. Really strange, never have heard about this.

Question: Could it be, that a ruby file has changed in file system after starting Zammad?

 -Martin

**Comment by abenrob** [comment] 2017-02-09 15:21
@martini please let me know if you'd like me to send you the logfile (160mb)

**Comment by abenrob** [comment] 2017-02-09 15:28
We are deploying with docker, so the entire app is contained withing a container - nothing outside of the app should affect anything inside the app, aside from the configuration. We have updated the image several times, and restart it each week or so.

**Comment by monotek** [comment] 2017-02-09 15:41
Which docker repo do you use?

**Comment by gerbsen** [comment] 2017-02-09 15:53
We forked [1](https://github.com/celevra/zammad-docker) to here [2](https://github.com/route360/zammad-docker)

**Comment by monotek** [comment] 2017-02-09 15:56
You could also try our docker compose repo for production: https://github.com/zammad/zammad-docker-compose

**Comment by thorsteneckel** [comment] 2017-02-16 08:30
Hi @abenrob - could you please take a look at the linked issue and your log? Looks like it could be a duplicate 🤔

**Comment by thorsteneckel** [comment] 2018-01-03 08:50
We can't reproduce this issue and apparently it didn't happen anymore. Closing for now. Everybody feel free to provide further information on how to reproduce.

**Closed by thorsteneckel** 2018-01-03 08:50 UTC
Labels: can't reproduce, wontfix
