### ISSUE TITLE
Dashboard Status resets

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1587] opened 2017-10-26 14:23 UTC
Hi,
Im using version 1.5 and now I see after hundreds of created and solved tickets, dashboard is showing My handling time: 0 minutes and 0 of my tickets escalated., 0% have been reopened and everything else reseted.... It is very weird since there were many different values before. All other agents are experiencing the same thing in their own dashboard...

Best,

Zammad v1.5
Centos 7
Chrome & Firefox

**Comment by thorsteneckel** [comment] 2018-05-08 11:27
Hi @hamzehmohammadnia - It's been a while since you created this issue. In the meantime some things have changed - in the Zammad code and the form we report issues. Could you please do the following to help us address this issue:

- Verify that the issue still persists in the latest version of Zammad
- Create a new issue and fill out the issue template completely
- Provide a detailed step by step guide (with screenshots!) on how to reproduce this

Thanks for you support! I'm closing this now.

**Closed by thorsteneckel** 2018-05-08 11:27 UTC
