### ISSUE TITLE
Zendesk import: Error while importing ticket field with dash in name

### ISSUE THREAD

**Issue by giezi** [zammad/zammad#1095] opened 2017-05-16 14:08 UTC
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: docker-image
* Operating system: Linux
* Browser + version: Chrome 58

### Expected behaviour:

The Zendesk import should provide more detailed error information.

### Actual behaviour:

We tried to import our current zendesk system (tickets, user, organization) and the import fails with the following error message:

<img width="480" alt="zendesk-import" src="https://cloud.githubusercontent.com/assets/1326203/26110096/90548698-3a51-11e7-9b8b-381b0fed84f1.png">

In the production.log we see the following entry:

> I, [2017-05-16T12:19:58.077566 #888]  INFO -- :   Parameters: {"_"=>"1494936399333", "import_zendesk"=>{}}
> I, [2017-05-16T12:19:58.079609 #888]  INFO -- : Completed 200 OK in 2ms (Views: 0.2ms | ActiveRecord: 0.2ms)
> I, [2017-05-16T12:20:03.042901 #924]  INFO -- : Scheduler running...
> I, [2017-05-16T12:20:03.108024 #888]  INFO -- : Started GET "/api/v1/import/zendesk/import_status?_=1494936399334" for 94.247.222.34 at 2017-05-16 12:20:03 +0000
> I, [2017-05-16T12:20:03.111436 #888]  INFO -- : Processing by ImportZendeskController#import_status as JSON
> I, [2017-05-16T12:20:03.111546 #888]  INFO -- :   Parameters: {"_"=>"1494936399334", "import_zendesk"=>{}}
> I, [2017-05-16T12:20:03.114332 #888]  INFO -- : Completed 200 OK in 3ms (Views: 0.3ms | ActiveRecord: 0.4ms)
> I, [2017-05-16T12:20:07.492083 #888]  INFO -- : Completed 200 OK in 25030ms (Views: 0.3ms | ActiveRecord: 0.3ms)
> I, [2017-05-16T12:20:07.532770 #888]  INFO -- : Started POST "/api/v1/message_receive" for 94.247.222.34 at 2017-05-16 12:20:07 +0000
> I, [2017-05-16T12:20:07.536511 #888]  INFO -- : Processing by LongPollingController#message_receive as JSON
> I, [2017-05-16T12:20:07.536623 #888]  INFO -- :   Parameters: {"client_id"=>"112932444", "long_polling"=>{"client_id"=>"112932444"}}
> I, [2017-05-16T12:20:08.148199 #888]  INFO -- : Started GET "/api/v1/import/zendesk/import_status?_=1494936399335" for 94.247.222.34 at 2017-05-16 12:20:08 +0000
> I, [2017-05-16T12:20:08.151288 #888]  INFO -- : Processing by ImportZendeskController#import_status as JSON
> I, [2017-05-16T12:20:08.151343 #888]  INFO -- :   Parameters: {"_"=>"1494936399335", "import_zendesk"=>{}}
> I, [2017-05-16T12:20:08.153665 #888]  INFO -- : Completed 200 OK in 2ms (Views: 0.3ms | ActiveRecord: 0.3ms)
> E, [2017-05-16T12:20:08.384250 #924] ERROR -- : Only letters from a-z, numbers from 0-9, and _ are allowed (RuntimeError)
> /opt/zammad/app/models/object_manager/attribute.rb:680:in `check_name'
> /opt/zammad/app/models/object_manager/attribute.rb:276:in `add'
> /opt/zammad/lib/import/zendesk/object_attribute.rb:20:in `add'
> /opt/zammad/lib/import/zendesk/object_attribute.rb:10:in `initialize'
> /opt/zammad/lib/import/zendesk/object_field.rb:27:in `new'
> /opt/zammad/lib/import/zendesk/object_field.rb:27:in `import'
> /opt/zammad/lib/import/zendesk/object_field.rb:9:in `initialize'
> /opt/zammad/lib/import/base_factory.rb:37:in `new'
> /opt/zammad/lib/import/base_factory.rb:37:in `create_instance'
> /opt/zammad/lib/import/base_factory.rb:11:in `block in import_action'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:349:in `block in _all'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:457:in `each'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:457:in `public_send'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:457:in `array_method'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:298:in `method_missing'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:342:in `_all'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:216:in `all!'
> /opt/zammad/lib/import/zendesk/base_factory.rb:12:in `import_loop'
> /opt/zammad/lib/import/base_factory.rb:9:in `import_action'
> /opt/zammad/lib/import/zendesk.rb:27:in `start'
> /opt/zammad/lib/import/zendesk/async.rb:30:in `start_bg'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/performable_method.rb:26:in `perform'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:84:in `block in invoke_job'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:81:in `invoke_job'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:230:in `block (2 levels) in run'
> /usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
> /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:230:in `block in run'
> /usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:229:in `run'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:306:in `block in reserve_and_run_one_job'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:306:in `reserve_and_run_one_job'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:213:in `block in work_off'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:212:in `times'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:212:in `work_off'
> /opt/zammad/app/models/scheduler.rb:239:in `block (3 levels) in worker'
> /usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
> /opt/zammad/app/models/scheduler.rb:237:in `block (2 levels) in worker'
> /opt/zammad/app/models/scheduler.rb:233:in `loop'
> /opt/zammad/app/models/scheduler.rb:233:in `block in worker'
> I, [2017-05-16T12:20:08.386721 #924]  INFO -- : 2017-05-16T12:20:08+0000: [Worker(host:node44739-zammad.alp1.ae.flow.ch pid:924)] Job Module#start_bg (id=6) COMPLETED after 627.4244
> I, [2017-05-16T12:20:08.389117 #924]  INFO -- : 2017-05-16T12:20:08+0000: [Worker(host:node44739-zammad.alp1.ae.flow.ch pid:924)] Job BackgroundJobSearchIndex (id=7) RUNNING
> I, [2017-05-16T12:20:08.409371 #924]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production/Organization/2" \
> I, [2017-05-16T12:20:08.803148 #924]  INFO -- : # 201
> I, [2017-05-16T12:20:08.813595 #924]  INFO -- : 2017-05-16T12:20:08+0000: [Worker(host:node44739-zammad.alp1.ae.flow.ch pid:924)] Job BackgroundJobSearchIndex (id=7) COMPLETED after 0.4244
> I, [2017-05-16T12:20:08.823884 #924]  INFO -- : 2017-05-16T12:20:08+0000: [Worker(host:node44739-zammad.alp1.ae.flow.ch pid:924)] Job BackgroundJobSearchIndex (id=8) RUNNING
> I, [2017-05-16T12:20:08.837191 #924]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production/Organization/3" \
> I, [2017-05-16T12:20:08.976799 #924]  INFO -- : # 201
> I, [2017-05-16T12:20:08.979308 #924]  INFO -- : 2017-05-16T12:20:08+0000: [Worker(host:node44739-zammad.alp1.ae.flow.ch pid:924)] Job BackgroundJobSearchIndex (id=8) COMPLETED after 0.1553
> I, [2017-05-16T12:20:08.981950 #924]  INFO -- : 2017-05-16T12:20:08+0000: [Worker(host:node44739-zammad.alp1.ae.flow.ch pid:924)] Job BackgroundJobSearchIndex (id=9) RUNNING
> I, [2017-05-16T12:20:08.984633 #924]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production/Organization/4" \
> I, [2017-05-16T12:20:09.137521 #924]  INFO -- : # 201
> I, [2017-05-16T12:20:09.141465 #924]  INFO -- : 2017-05-16T12:20:09+0000: [Worker(host:node44739-zammad.alp1.ae.flow.ch pid:924)] Job BackgroundJobSearchIndex (id=9) COMPLETED after 0.1594
> I, [2017-05-16T12:20:09.144066 #924]  INFO -- : 2017-05-16T12:20:09+0000: [Worker(host:node44739-zammad.alp1.ae.flow.ch pid:924)] Job BackgroundJobSearchIndex (id=10) RUNNING
> I, [2017-05-16T12:20:09.149948 #924]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production/Organization/5" \

How we can identify the affected Zendesk user?

### Steps to reproduce the behaviors:

Start import wizard.

Many thanks and best regards
Reto

**Comment by martini** [comment] 2017-05-29 08:11
Hi @giezi 

thank for feedback. Can you tell use what custom fields for users and tickets you have created in Zendesk (the list of the names are important)?

@thorsteneckel it seems that there is a Zendesk field which contains invalid chars for Zammad attributes.

 -Martin

**Comment by giezi** [comment] 2017-05-29 11:52
Hi Martin

Many thanks for your response.
We have no custom-fields for users defined, only one custom field "Priority - Simple" for the tickets:

<img width="1602" alt="screen shot 2017-05-29 at 13 47 28" src="https://cloud.githubusercontent.com/assets/1326203/26548685/aede1bfa-4475-11e7-9d23-3177d4b2781e.png">

Which provides the following values:

<img width="1026" alt="screen shot 2017-05-29 at 13 47 50" src="https://cloud.githubusercontent.com/assets/1326203/26548693/bb4a4436-4475-11e7-86a2-c2b073a000cf.png">

The import is working about a few minutes, which indicates that there are no issues with custom fields. It fails to import the 2899 user. I suspect some invalid chars in a username. Or what do you think about?

Best regards
Reto

**Comment by thorsteneckel** [comment] 2017-05-29 13:56
Thanks a lot @giezi !

JFI: The error is thrown here: 
https://github.com/zammad/zammad/blob/a306078ebb8a6fc17ab014c63c51bf57ad5b1573/lib/import/zendesk.rb#L27

So you are right. It is the Ticket attribute. I'll write a test to reproduce and fix it. I'll be back 🤖

**Comment by thorsteneckel** [comment] 2017-05-30 16:35
The issue is fixed with the commits above. Thanks for reporting this! We made the field naming logic more robust and added more detailed error messages for those cases. I hope we don't need them 🤓 

You can update your package to the latest version in ~45 minutes from now. Would be great to get some feedback.

**Closed by thorsteneckel** 2017-05-30 16:35 UTC
Labels: bug, import

**Comment by giezi** [comment] 2017-05-31 09:00
Many thanks @thorsteneckel for the fix - it looks better, but it fails now at the following step:

<img width="480" alt="screen shot 2017-05-31 at 10 59 32" src="https://cloud.githubusercontent.com/assets/1326203/26624164/586b3f42-45f0-11e7-9740-264aa395cef2.png">

Do you need any more information to troubleshoot the issue?

Thanks!
Reto

**Comment by thorsteneckel** [comment] 2017-05-31 09:05
Hi @giezi - Thanks for your fast feedback! This looks like a new issue to me. There seems to be a (new?) Zendesk object attribute called `Basic Priority` which is not covered by our import (yet). Could you please create a new issue with this nice screenshot and add the output of your `log/production.log` file and a screenshot of the configuration in Zendesk of your fields like you did above? Would be a great help! I'll have a look at it then. Thanks!

**Comment by giezi** [comment] 2017-05-31 09:11
Hi @thorsteneckel Sure - I've opened a new issue: https://github.com/zammad/zammad/issues/1153
Many thanks for your effort :)
