### ISSUE TITLE
Pull CC'd recipients from users database

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1828] opened 2018-02-13 11:00 UTC
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): 
* Operating system: CentOS 7
* Database + version: Potgres
* Elasticsearch version: 5.6
* Browser + version: several

### Suggested behavior:

* Pull email addresses of additional recipients that are added to CC for the ticket.

### Actual behavior:

* Email addresses must be entered manually, even when there are records for the complete recipient details at the Zammad database.

### Steps to reproduce the behavior:

* Press "reply" at the ticket interface and start typing the email address you want to add to the ticket recipient.

Yes I'm sure this is feature request.

**Comment by thorsteneckel** [comment] 2018-03-01 10:58
Actually this is duplicate of #338 . For the record: We recognizeI your expressed emotion about this. 👍

**Closed by thorsteneckel** 2018-03-01 10:58 UTC
