### ISSUE TITLE
No option to open attachment in Internet Explorer

### ISSUE THREAD

**Issue by flo0162** [zammad/zammad#2690] opened 2019-08-05 13:59 UTC
### Infos:

* Used Zammad version: 3.1.0-1564403976.b2f434c5.bionic
* Installation method (source, package, ..): DEB package
* Operating system: Ubuntu 18.04.2
* Database + version: PostgreSQL 10.9
* Elasticsearch version: 5.6.16
* Browser + version: Internet Explorer 11

### Expected behavior:

When opening an attachment, there has to be two options:
- open
- save

### Actual behavior:

In Firefox, everything is fine. In Internet Explorer 11, there is no option to open the attachments, since a few Zammad versions. You can only save them to your local drive and then open it (![zammad](https://user-images.githubusercontent.com/52698736/62469987-ad7c6200-b799-11e9-802e-d2b8af6e0a4e.png))

### Steps to reproduce the behavior:

Open Internet Explorer, login to Zammad, take a ticket with attachment and click on that attachment.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2019-08-05 14:05
Hey @flo0162 - thanks for raising the awareness. Unfortunately this is not a bug of Zammad but a limitation of the (Internet Explorer) browser itself. Therefore I'm closing this issue because we don't have any influence on it.

**Closed as completed by thorsteneckel** 2019-08-05 14:05 UTC
Labels: works as designed / wontfix, third party issue
