### ISSUE TITLE
E-Mail (Eingang): undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by as-wallpen** [zammad/zammad#3493] opened 2021-04-03 10:35 UTC
### Infos:

* Used Zammad version: 4.0.0
* Installation method (source, package, ..): Debian Package
* Operating system: Ubuntu 20.04
* Database + version: 
* Elasticsearch version: 6.8.15
* Browser + version: Firefox 87.0

### Expected behavior:

Create an Email account to read incoming tickets

### Actual behavior:

Runnuing into the error Message "undefined method `[]' for nil:NilClass" 

### Steps to reproduce the behavior:

*
![Unbenannt](https://user-images.githubusercontent.com/34537235/113476033-ff96ee80-9478-11eb-854b-4339409eb3a4.PNG)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment] 2021-04-03 11:19
@as-wallpen could you post `production.log` with lines related to this error? Please make sure to remove sensitive data from it before posting it publicly.

**Comment by as-wallpen** [comment] 2021-04-05 10:07
I, [2021-04-05T12:02:52.798013 #2344-70334218258100]  INFO -- : Started POST "/api/v1/channels_email_inbound" for x.x.x.x at 2021-04-05 12:02:52 +0200
I, [2021-04-05T12:02:52.806925 #2344-70334218258100]  INFO -- : Processing by ChannelsEmailController#inbound as JSON
I, [2021-04-05T12:02:52.807072 #2344-70334218258100]  INFO -- :   Parameters: {"adapter"=>"imap", "options"=>{"host"=>"xxx.xxx.com", "user"=>"xxx@xxx.com", "password"=>"[FILTERED]", "ssl"=>false, "port"=>"143", "folder"=>"", "keep_on_server"=>false}, "channel_id"=>3}
I, [2021-04-05T12:02:52.819842 #2344-70334218258100]  INFO -- : Enqueued UserDeviceLogJob (Job ID: c1214f2a-ce05-407a-99b8-db88217113fc) to DelayedJob(default) with arguments: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0", "93.206.30.86", 3, "1854385796", "session"
I, [2021-04-05T12:02:52.827553 #2344-70334218258100]  INFO -- : fetching imap (xxx.xxx.com/xxx@xxx.com port=143,ssl=false,starttls=false,folder=INBOX,keep_on_server=false,auth_type=LOGIN)
I, [2021-04-05T12:02:53.093127 #2344-70334218258100]  INFO -- : Completed 200 OK in 286ms (Views: 0.5ms | ActiveRecord: 10.1ms)
I, [2021-04-05T12:02:55.628815 #1075-47013881030640]  INFO -- : 2021-04-05T12:02:55+0200: [Worker(host:xxx pid:1075)] Job UserDeviceLogJob [c1214f2a-ce05-407a-99b8-db88217113fc] from DelayedJob(default) with arguments: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0", "x.x.x.x", 3, "1854385796", "session"] (id=1045647) (queue=default) RUNNING
I, [2021-04-05T12:02:55.662004 #1075-47013881030640]  INFO -- : Performing UserDeviceLogJob (Job ID: c1214f2a-ce05-407a-99b8-db88217113fc) from DelayedJob(default) with arguments: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0", "x.x.x.x", 3, "1854385796", "session"
I, [2021-04-05T12:02:55.671357 #1075-47013881030640]  INFO -- : Performed UserDeviceLogJob (Job ID: c1214f2a-ce05-407a-99b8-db88217113fc) from DelayedJob(default) in 9.27ms
I, [2021-04-05T12:02:55.673446 #1075-47013881030640]  INFO -- : 2021-04-05T12:02:55+0200: [Worker(host:xxx pid:1075)] Job UserDeviceLogJob [c1214f2a-ce05-407a-99b8-db88217113fc] from DelayedJob(default) with arguments: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0", "93.206.30.86", 3, "1854385796", "session"] (id=1045647) (queue=default) COMPLETED after 0.0445
I, [2021-04-05T12:02:57.644755 #2344-47253326627160]  INFO -- : Started GET "/api/v1/channels_email?_=1617616317971" for x.x.x.x at 2021-04-05 12:02:57 +0200
I, [2021-04-05T12:02:57.653931 #2344-47253326627160]  INFO -- : Processing by ChannelsEmailController#index as JSON
I, [2021-04-05T12:02:57.654040 #2344-47253326627160]  INFO -- :   Parameters: {"_"=>"1617616317971"}
I, [2021-04-05T12:02:57.696543 #2344-47253326627160]  INFO -- : Completed 200 OK in 42ms (Views: 5.4ms | ActiveRecord: 8.2ms)
I, [2021-04-05T12:03:08.589088 #2344-70334218258100]  INFO -- : Started GET "/api/v1/channels_email?_=1617616317972" for x.x.x.x at 2021-04-05 12:03:08 +0200
I, [2021-04-05T12:03:08.594701 #2344-70334218258100]  INFO -- : Processing by ChannelsEmailController#index as JSON
I, [2021-04-05T12:03:08.594772 #2344-70334218258100]  INFO -- :   Parameters: {"_"=>"1617616317972"}
I, [2021-04-05T12:03:08.780580 #2344-70334218258100]  INFO -- : Completed 200 OK in 186ms (Views: 4.9ms | ActiveRecord: 8.2ms)

**Comment by as-wallpen** [comment] 2021-04-05 10:10
It´s weird... I see no issues here, but still get the error message, no matter if I use IMAP with SSL on Port 993 or without on Port 143. Also changing the other options make no difference. BTW: Our mailserver is the latest IceWarp release and generally works very well....

**Comment by MrGeneration** [comment] 2021-06-28 10:37
Duplicate of #3048

**Closed as completed by MrGeneration** 2021-06-28 10:37 UTC
Labels: duplicate
