### ISSUE TITLE
Can't use Filter Tags contains one not spam in Report Profiles

### ISSUE THREAD

**Issue by chesty** [zammad/zammad#2080] opened 2018-06-14 23:29 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): zammad-docker-compose

### Expected behavior:

* shows all tickets that aren't tagged as spam

### Actual behavior:

* get the follow error in a pop up box {"error":"unknown operator 'contains one not' for ticket.tags"}

### Steps to reproduce the behavior:

* add to the Filter of a Report Profile Tags  contains one not  spam

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-06-15 06:34
Hi @chesty - this is a duplicate of #1847 and #1720 - Short summary: We only have basic reports for now but for advanced reporting we will be using Grafana.

**Closed as completed by thorsteneckel** 2018-06-15 06:34 UTC
Labels: duplicate

**Comment by chesty** [comment] 2018-06-15 06:36
sorry for the dup, I forgot to search. I'll search next time. cheers, love your work.
