### ISSUE TITLE
Can't create email-account with local MTA as outgoing server 

### ISSUE THREAD

**Issue by MatthiasWiesner** [zammad/zammad#1852] opened 2018-02-26 10:06 UTC
### Infos:

* Used Zammad version: 2.3.0-1519371734.f7fb992f.xenial
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.4 LTS (Xenial Xerus)
* Database + version: Postgresql 9.4+165+deb8u3
* Elasticsearch version: 5.6.8
* Browser + version: Google Chrome 64.0.3282.167 (Offizieller Build) (64-Bit)

### Expected behavior:

* Created email account with Pop3 (incoming) and Local MTA (outgoing)

### Actual behavior:

* Creation process stops with a javascript error:
~~~
application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:27 Uncaught TypeError: Cannot read property 'password' of undefined
    at i.probleOutbound (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:27)
    at i.probleOutbound (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:26)
    at HTMLFormElement.<anonymous> (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:8)
    at HTMLDivElement.dispatch (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:2)
    at HTMLDivElement.m.handle (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:2)
~~~

### Steps to reproduce the behavior:

* Click new email-account
* Fill out the modal dialog fields with valid data
* Switch to expert mode, to set pop3 method, port and ssl
* Click next to verify connection and define outgoing email settings
* Switch to "Local MTA (Sendmail/Postfix/Exim/...) .."
* Click next
  * Here the process stops with javascript error message

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MatthiasWiesner** [comment] 2018-02-26 11:27
Since I *really* needed this email-account, I just created the account this way:
In "Configure outgoing email"
* Choose SMTP
* In Chrome Developer Mode: Copy the passwords input field html
* Switch back to Sendmail
* In Chrome Developer Mode: Paste the passwords input field html just above the methods select box (cannot remember which css class or element id)
* Click next - now there is a password (complete unnecessary)
OK, that worked, but **THIS IS INSANE**

**Comment by thorsteneckel** [comment] 2018-03-01 11:02
Hi @MatthiasWiesner - can you still reproduce this issue since your other (very similar) wasn't reproducible anymore?

**Comment by MatthiasWiesner** [comment] 2018-03-01 15:40
Unfortunately yes, I just removed the Email configuration only to reproduce the error and I still got the error again.

The other issue probably had to do with the elasticsearch settings. The elasticsearch settings (no localhost endpoint) were overwritten after the package upgrade. When I corrected these settings, the issue resolved (but this issue still remain).

**Comment by thorsteneckel** [comment] 2018-03-01 15:44
Damn that's really not the experience we want you to have. Can you please provide the file `public/assets/application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js`? Would be great to get a visual impression on how your form looks when you have the issue. A screenshot, if possible, would be a great help.

**Comment by MatthiasWiesner** [comment] 2018-03-01 15:57
Sure...
The javascript file (renamed to .txt)
[application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js.txt](https://github.com/zammad/zammad/files/1771799/application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js.txt)

The screenshot directly after the POP3-ssl settings were verified, with SMTP preselected:
![bildschirmfoto 2018-03-01 um 16 48 47](https://user-images.githubusercontent.com/871238/36854363-1b7e304a-1d71-11e8-881f-54fd0c2f799e.png)

The screenshot as I tried to switch to Local MTA:
![bildschirmfoto 2018-03-01 um 16 49 30](https://user-images.githubusercontent.com/871238/36854474-6321948c-1d71-11e8-8aa4-0e27269d0be7.png)

I hope it can help you (my guess, the js want to validate the form and expect a password field, which is not provided for Local MTA)

**Comment by thorsteneckel** [comment] 2018-03-01 16:15
Thanks! Actually that helped a lot. This only occurs when changing from a SMTP server to a Local MTA. Direct Local MTA configuration is not affected and therefore we were not able to reproduce it. Now that we can a fix is on it's way. Actually the fix is already running in our CI environment and will be ready soon 🚀 I'll let you know.

**Comment by MatthiasWiesner** [comment] 2018-03-01 16:19
Thank you! *really fast*  :-)

**Comment by thorsteneckel** [comment] 2018-03-01 19:27
This is fixed with the two commits above for `develop` and `stable`. The new packages will be ready in ~30 minutes from now 👍 Thanks a lot for your support. Closing now.

**Closed by thorsteneckel** 2018-03-01 19:27 UTC
Labels: admin area, bug, channel, verified
