### ISSUE TITLE
Add "received ticket merge" as an action condition for triggers

### ISSUE THREAD

**Issue by SummerStorm** [zammad/zammad#2467] opened 2019-02-08 11:55 UTC
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

This is a new feature request.

### Current behavior:
1. Ticket 1 is `closed` and ticket 2 is `open`.
2. Ticket 2 is merged into ticket 1, Ticket 2's new status is `merged`.
3. Ticket 1 is still closed, and thus has low visibility and is easy to loose track of. This is an inconvenience. Ideally we want Ticket 1 reopened upon the merge, and perhaps assigned to an agent for follow up.

### Desired functionality:
The ability to create triggers where the condition action is "received ticket merge". For example:

![asdasdasdadadad](https://user-images.githubusercontent.com/7030950/52476838-e2d53800-2bda-11e9-96ac-05820452ed16.png)

### Desired behavior with the new functionality:
0. Create a trigger where the condition action is "received ticket merge", the change to execute is "set state to open" and “assign to an agent”. 
1. Ticket 1 is `closed` and ticket 2 is `open`.
2. Ticket 2 is merged into ticket 1, Ticket 2's new status is `merged`.
3. The trigger is activated and Ticket 1's status is set to `open` and assigned to an agent.

This issue affects internal tickets #1037697 and  #1024937.

**Comment by MrGeneration** [comment] 2022-01-05 13:08
This has gotten a technical duplicate of #3105.
It was solved with Zammad 5.0 via https://github.com/zammad/zammad/commit/c8e2c7473caa8f2abac7d382301be7d55a574d56.

This issue seemed to have slipped, sorry for that.

**Closed as completed by MrGeneration** 2022-01-05 13:08 UTC
Labels: duplicate
