### ISSUE TITLE
Attribute order

### ISSUE THREAD

**Issue by rush42** [zammad/zammad#732] opened 2017-02-05 12:21 UTC
### Infos:

* Used Zammad version: 1.1.1-1483606242.9b40d24.xenial
* Operating system: Ubuntu 16.04
* Browser + version: Google Chrome 56.0.2924.87 (64-bit)
* T#1076062

### Expected behavior:

* Change attribute order via drag-and-drop or something similar
* don't force "default" attributes on a specific position

### Actual behavior:

* When adding new attributes to objects they list up "randomly" and there is no way to control their order.

### Steps to reproduce the behavior:

* Adding the possibility to change attribute order via drag-and-drop

**Comment by MrGeneration** [comment] 2021-06-04 11:42
Duplicate of #294

**Closed by MrGeneration** 2021-06-04 11:42 UTC
Labels: duplicate
