### ISSUE TITLE
Multiple Slack/Mattermost integrations/configurations

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#1311] opened 2017-07-31 18:32 UTC
Hi,

nachdem Zammad ja schon Slack-Integration bietet, würde ich mir das Gleiche für Mattermost wünschen (mattermost.org). MM ist quasi Slack in einer selbst gehosteten Version (Die freie Team-Edition reicht hier sogar schon aus, um Zammad zu integrieren).

Mattermost bietet alle Werkzeuge für eine solche Integration.

Die Kombi wäre der Hammer ;-))

**Comment by martini** [comment] 2017-07-31 18:34
Hi @jacotec 

Mattermost is compatible to Slack API. That means you already can use the Zammad Slack integration with Mattermost (we do it for our self). :)

 -Martin

**Comment by jacotec** [comment] 2017-07-31 18:36
Hi @martini,

I should have known that you love this kind of tools *g* ... Sounds great, I'll try that!

**Comment by jacotec** [comment] 2017-07-31 18:52
@martini: Works like a charm! Awesome!!!

I guess there is no chance to create multiple Slack integrations? So that different Zammad groups are routed to different Mattermost channels? ;-)

**Comment by martini** [comment] 2017-07-31 18:58
> I guess there is no chance to create multiple Slack integrations? So that different Zammad groups are routed to different Mattermost channels? ;-)

Currently only one config is possible.

**Comment by jacotec** [comment] 2017-07-31 19:11
How do we say: Was nicht ist, kann ja noch werden ;-))

**Comment by waja** [comment] 2018-03-08 00:39
> I guess there is no chance to create multiple Slack integrations? So that different Zammad groups are routed to different Mattermost channels? ;-)

There is #796 already

**Comment by RareshLuma** [comment] 2019-07-19 02:14
+1

**Comment by MrGeneration** [comment] 2019-07-19 07:06
Locking conversation as there hasn't been any new input apart from `+1`.
If you want to discuss this, please use our community for this and reference the issue. :-)

**Comment by thorsteneckel** [comment] 2020-07-29 13:12
Better late than never: Thanks @waja for pointing out that this is a duplicate of #796 (multiple Slack/Mattermost configurations). Mattermost is already possible because of the compatible API.

**Closed by thorsteneckel** 2020-07-29 13:12 UTC
Labels: enhancement, integration
