### ISSUE TITLE
Recommendation for Dashboard

### ISSUE THREAD

**Issue by jaeger13** [zammad/zammad#1420] opened 2017-09-14 16:09 UTC
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...): rpm
* Operating system: Centos 7
* Browser + version: doesn't matter

Hey,

today I installed the new version 2.0 for zammad and it looks great  :thumbsup: 

Since I'm the only one at the moment that takes care of our helpdesk, I would like to inform our other admins and agents about the changes in the new versions and other important stuff. 
I would be really cool if you could add a little square or something on the Dashboard for announcments and other stuff.

Also, it would be good if it is group specific since admins get different announcements the normal users.

Anyone else here that thinks that would be useful?

**Comment by NeverMin** [comment] 2017-09-14 19:48
Hi @jaeger13 , like `/#system/maintenance` ?

**Comment by jaeger13** [comment] 2017-09-15 06:19
Hey @NeverMin ,

yeah something like that. The problem is, that most of the users are always logged in so they don't see announcements since right now, maintenance texts are only visible on the log-in page. 

Notifications on the Dashboard would be awesome 👍

**Comment by thorsteneckel** [comment] 2020-07-29 14:12
This is actually a duplicate of #759 – therefore closing this one.

**Closed by thorsteneckel** 2020-07-29 14:12 UTC
Labels: dashboard, feature backlog
