### ISSUE TITLE
Changing limit for organisation note doesn't increase the 250 symbols limit

### ISSUE THREAD

**Issue by Sonit90** [zammad/zammad#1567] opened 2017-10-20 14:44 UTC
* Used Zammad version: 2.0.x
* Used Zammad installation source: (source, package, ...) package 
* Operating system: Ubuntu server 16 on server, Windows 7 on PC
* Browser + version: Chrome 62.0.3202.45

### Expected behavior:

I wanted to increase size of Organization note from 250 symbols to 2500. Changed the numbers in following files:
/opt/zammad/app/assets/javascripts/app/models/organization.coffee
/opt/zammad/app/assets/javascripts/app/controllers/widget/organization.coffee
/opt/zammad/app/assets/javascripts/app/controllers/organization_profile.coffee
And also changes the field size in database to 2500, rebuild all the rails assets  sudo zammad run rake assets:precompile and rebooted zammad system, but nothing changed. Popup windows doesn't let me to write more than 250 symbols, how can i overcome that behavior?
Thank you, Dmitriy.

**Comment by muhammadn** [comment] 2017-10-20 17:39
If you have done changing the "note" field size in "organizations" table  in the database to 2500, you also need to run the commands below in the admin (rails) [console](https://docs.zammad.org/en/latest/admin-console.html) to update the backend validation.

```
    object_id = ObjectLookup.by_name('Organization')
    attribute = ObjectManager::Attribute.find_by(object_lookup_id: object_id, name: 'note')
    attribute.data_option[:maxlength] = 2500
    attribute.save!
```

**Comment by Sonit90** [comment] 2017-10-20 20:07
Thank, it worked. And one more question: Is it possible to change max lengths values not using the console?

**Comment by muhammadn** [comment] 2017-10-21 12:14
@Sonit90 You need to do it only once since the backend validations (which restricts the characters) is configured within the database.

But it will be changed in later versions of zammad (the one in `develop` branch/version 2.1.x) where the limit will be set to 5000 characters.

**Comment by muhammadn** [comment] 2017-10-23 12:55
Hi @Sonit90 . if the problem is resolved is it okay for you to close it? Thanks!

**Comment by Sonit90** [comment] 2017-10-23 14:23
@muhammadn Sure, i am very thankfull for your help!

**Closed** 2017-10-23 14:44 UTC
