### ISSUE TITLE
Sending chat as mail

### ISSUE THREAD

**Issue by guidoesser** [zammad/zammad#444] opened 2016-11-18 13:27 UTC
Is it possible to send a chat by mail?

**Comment by monotek** [comment] 2016-11-18 15:29
Not now. But hopefully chats can be converted to tickets soon.

See: https://github.com/zammad/zammad/issues/422

**Comment by martini** [comment] 2016-11-22 10:16
@guidoesser "send a chat by mail" to customer or to agent?

**Comment by guidoesser** [comment] 2016-12-21 13:25
Sorry for the late answer. We are evaluating zammad for a university library. When a user/customer gets informations from a librarian/agent it would be useful to get the whole chat by mail.

**Comment by thorsteneckel** [comment] 2017-01-10 13:42
Duplicate of #422

**Closed by thorsteneckel** 2017-01-10 13:42 UTC
Labels: enhancement

**Comment by guidoesser** [comment] 2017-01-11 13:26
If I understand it correctly a customer would automatically get a mail with the chat content after he decides "convert chat to ticket". In my case it would be more clear to the customer to have two opportunities:
1. "convert chat to ticket" - resulting in a an open ticket and a mail to the customer
2. "send chat by mail" - resulting in a closed ticket and a mail to the customer
Second prevents agents from having to close already solved tickets.
