### ISSUE TITLE
"Unable to retrive group information, please check your bind user permissions."

### ISSUE THREAD

**Issue by lpar** [zammad/zammad#1602] opened 2017-11-01 17:22 UTC
### Infos:

* Used Zammad version: zammad-2.1.0-1509547748.62038447.centos7.x86_64
* Used Zammad installation source: stable RPM repo
* Operating system: CentOS 7
* Browser + version: Chrome Version 62.0.3202.75 (Official Build) (64-bit)

### Actual behavior:

* Logging in to set up LDAP, I now get past the initial stage of scanning for a user record, but it fails when looking for a group record.

Followup to issue #1422 so all other info (bind DN, base DN etc) is as per that ticket.

**Comment by thorsteneckel** [comment] 2017-11-02 17:23
Hi @lpar - nice to see you again ;) To get an orientation please run the ruby code as follows:

1.) Create a file called `debug_ldap.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_ldap.rb` or `rails r debug_ldap.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_ldap.rb` file

```ruby
bind_dn    = 'dn here'
bind_pw    = 'password here'
filter     = '(objectClass=person)'
host       = 'bluepages.ibm.com'
port       = 636
base_dn    = 'ou=bluepages,o=ibm.com'
ssl        = true
ssl_verify = true


require 'ldap'

params = {
  host:       host,
  port:       port,
  ssl:        ssl,
  ssl_verify: ssl_verify,
  base_dn:    base_dn,
  bind_user:  bind_dn,
  bind_pw:    bind_pw,
}

ldap  = ::Ldap.new(params)
group = ::Ldap::Group.new(params, ldap: ldap)

p group.filter
```

This reproduces the behavior of Zammad trying to find the filter for listing all available groups. [There is a list of default group filters](https://github.com/zammad/zammad/blob/757f0ac9bddaf348a6929bcf7d43d1180ea106f4/lib/ldap/group.rb#L115). If a filter returns some entries it will be used. I think none of the filters matches for you. If there is no output of the script: What would be the filter you would use to list all groups in your `bluepages.ibm.com` setup?

**Comment by lpar** [comment] 2017-11-02 21:54
It outputs `nil`.

Our groups are under a different base DN, `ou=memberlist,ou=ibmgroups,o=ibm.com`

For example, if I do:

```
ldap.search(:base => "ou=memberlist,ou=ibmgroups,o=ibm.com",
               :scope => Net::LDAP::SearchScope_SingleLevel,
               :filter => nil) do |entry|
                 pp entry
                 break
               end
```

I get

```
#<Net::LDAP::Entry:0x0055846991c830
 @myhash=
  {:dn=>["cn=admin,ou=memberlist,ou=ibmgroups,o=ibm.com"],
   :objectclass=>["groupOfUniqueNames", "top"],
   :o=>["ibm.com"],
   :cn=>["admin"],
   :ou=>["ibmgroups", "memberlist"],
   :uniquemember=>
    ["uid=REDACTED,c=us,ou=bluepages,o=ibm.com",
     "uid=REDACTED,c=us,ou=bluepages,o=ibm.com",
     "uid=REDACTED,c=us,ou=bluepages,o=ibm.com",
     "uid=REDACTED,c=us,ou=bluepages,o=ibm.com",
     "uid=REDACTED,c=us,ou=bluepages,o=ibm.com",
     "uid=REDACTED,c=us,ou=bluepages,o=ibm.com"]}>
```
where each `uniquemember` value is a DN of a user.

**Comment by thorsteneckel** [comment] 2017-11-03 14:11
Could you please replace `lib/ldap/group.rb` with [this file](https://github.com/zammad/zammad/files/1441277/group.rb.zip). Restart your Zammad services (Websocket, Scheduler and Application) afterwards. Then retry the import again via the admin interface. While doing so have a look at the `log/production.log` file and provide the generated, anonymized content in case of an error. 🤞

**Comment by lpar** [comment] 2017-11-03 15:28
I'm afraid I don't get anything useful in the production.log:

```
I, [2017-11-03T11:20:16.655036 #517]  INFO -- : Started POST "/api/v1/integration/ldap/bind" for 9.80.198.211 at 2017-11-03 11:20:16 -0400
I, [2017-11-03T11:20:16.667944 #517]  INFO -- : Processing by Integration::LdapController#bind as JSON
I, [2017-11-03T11:20:16.668207 #517]  INFO -- :   Parameters: {"base_dn"=>"ou=bluepages,o=ibm.com", "bind_user"=>"uid=L13490897,c=us,ou=bluepages,o=ibm.com", "bind_pw"=>"[FILTERED]", "host_url"=>"ldaps://bluepages.ibm.com/", "ssl_verify"=>true}
I, [2017-11-03T11:20:17.019961 #519]  INFO -- : 2017-11-03T11:20:17-0400: [Worker(host:techelp.dfw.ibm.com pid:519)] Job Observer::UserDeviceLogJob (id=403) RUNNING
I, [2017-11-03T11:20:18.968583 #519]  INFO -- : 2017-11-03T11:20:18-0400: [Worker(host:techelp.dfw.ibm.com pid:519)] Job Observer::UserDeviceLogJob (id=403) COMPLETED after 1.9482
I, [2017-11-03T11:20:20.876715 #519]  INFO -- : Scheduler running...
```

**Comment by thorsteneckel** [comment] 2017-11-06 10:31
What happened in the admin interface?

**Comment by lpar** [comment] 2017-11-06 17:59
The same "Unable to retrive group information, please check your bind user permissions" error message.

**Comment by thorsteneckel** [comment] 2018-01-09 14:00
Hi @lpar - we did some changes regarding the LDAP groups via issue #1664 which might affect your issue, too. Could you please check if your issue still persists in the latest version of the develop branch? Thanks!

**Comment by lpar** [comment] 2018-01-19 21:03
No improvement. "Unable to retrive group information, please check your bind user permissions."

**Comment by AchuM** [comment] 2018-02-06 14:16
I had this issue before and I fix it by including the default OpenLDAP `objectclass`.

After upgrading to 2.3 the group file was restored back and experienced the same issue. 

So under `/opt/zammad/lib/ldap/group.rb`  on line 115  it should be something like this to get ride of this problem: 

` @filter ||= lookup_filter(['(objectClass= organizationalUnit)', '(objectClass=group)', '(objectClass=posixgroup)', '(objectClass=organization)', '(ou=memberlist,ou=ibmgroups,o=ibm.com)'])  
`

**Comment by lpar** [comment] 2018-02-06 20:10
That does indeed get me past the error!

**Comment by thorsteneckel** [comment] 2018-02-12 17:01
Great @AchuM - thank you very much for your input! We will refactor the group filter detection very soon to chose the correct one. We will use the filter with the most entries found. That should work. Any feedback is appreciated.

**Comment by lpar** [comment] 2018-02-12 21:02
So what is the next thing Zammad does? Because once I get past the error that it locks up performing some sort of processing. I think it might be trying to iterate through entries, which isn't going to work well because there are over 386,000 of them.

**Comment by thorsteneckel** [comment] 2018-02-13 07:56
Could you post a screenshot of the dialog. I'm lost trace where we are currently.

**Comment by lpar** [comment] 2018-02-13 18:00
I get a dialog asking for LDAP sync mappings, so I provide some:

![zam1_opt](https://user-images.githubusercontent.com/857035/36165452-3abc5c2a-10b5-11e8-84b6-c66f9f9d4406.png)

At the bottom of that dialog I click Continue. It says analyzing structure briefly, then presents a dialog saying it's counting entries, which may take a while:

![zam2_opt](https://user-images.githubusercontent.com/857035/36165512-6548bb78-10b5-11e8-9bb4-614be03bc0b3.png)

Since I haven't asked it to do any mapping between LDAP groups and Zammad roles, the only thing I can think of is that it's counting the users. If that's the case, it's not going to go well.

**Comment by thorsteneckel** [comment] 2018-04-08 15:29
Hi @lpar - We have done some performance improvements in the LDAP sync which reduce the overall runtime by up to 30%. However, sorry to say but 386.000 entries is still not a use case we aim to cover. Just out of curiosity: Why do you need all these users in your Zammad?

**Comment by lpar** [comment] 2018-04-08 18:06
I don't need all of those users. What I need is some way to have directory information populated for the ones who actually use Zammad, and to have them able to log in with their enterprise credentials. The OAuth2 authentication seems to be buggy and ignores some fields, so I was hoping the LDAP integration might fill out the missing information, or even allow for authentication via LDAP.

**Comment by lpar** [comment] 2018-04-09 01:57
Would it be possible to sync from LDAP only for accounts which are created on the fly via (say) OAuth2 login or some other method? That would avoid the initial long sync and avoid having tens of thousands of unnecessary accounts in the database — which is a liability given GDPR.

**Comment by thorsteneckel** [comment] 2018-04-09 06:59
There are two possible LDAP integrations in general: Bulk sync or on the fly. We already had experience with on the fly syncs before designing Zammads LDAP integration and decided against it because of the negative side effects it brings with it. To avoid unnecessary accounts in the database a proper LDAP filter should be used.
So the OAuth2 way would be preferable for your use case I guess then. We will have a look at the issue 👍 I'm closing here now since we can't go further from here. Correct me if I'm wrong. Thanks for your great support getting this far.

**Closed by thorsteneckel** 2018-04-09 06:59 UTC
Labels: LDAP, bug, integration, verified
