### ISSUE TITLE
Bulk-Action: Not possible to change owner

### ISSUE THREAD

**Issue by mschiff** [zammad/zammad#1864] opened 2018-03-07 10:05 UTC
### Infos:

* Used Zammad version: 2.3.0
* Installation method (source, package, ..): source (git)
* Operating system: Gentoo Linux
* Database + version: PostgreSQL 10.1
* Elasticsearch version: 5.6.5
* Browser + version: Firefox 52.6

### Expected behavior:

* In bulk action, when selecting multiple tickets the bottom bar show otems to bulk change ticket data. It should be possible to change the owner of all seleted tickets with the owner menu and by selecting the new owner from a list.

### Actual behavior:

* the owner menu list is empty, just shows "-" while all other menus have correct data in their lists

### Steps to reproduce the behavior:

* in a list of tickets, select some
* try to update the owner of all tickets: does not work because the owner list is empty

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment] 2018-03-07 10:06
Hi @mschiff 

is the owner selection available after you selected a group?

 -Martin

**Comment by mschiff** [comment] 2018-03-07 20:48
Hi @martini ,

indeed! I just figured this out an hour ago or so ;)

So this is *at least* a usability bug. I would expect the owner list to be prefilled with the possible owners of the current group (assuming alle selected tickets have the same group) or a subset of possible owners if tickets from different groups have been selected.

**Comment by martini** [comment] 2018-04-27 09:28
Hi @mschiff 

the problem is, that the possible owners depending on the group permissions. So we can't profile the owner list until the group is selected.

Feedback is welcome!

 -Martin

**Comment by thorsteneckel** [comment] 2018-05-09 18:34
Closing now since it works as designed.

**Comment by mschiff** [comment] 2018-05-09 20:33
@martini I think usability of this is not very good. To me it looked broken when I tried to use this. Why not build a list of possible owners from the list of selected tickets? The list should contain all agents that have access to all selected tickets.
I am sure this would increas usability a lot.

**Comment by MrGeneration** [comment] 2018-05-10 14:10
This was also mentioned in community as Feature request:

https://community.zammad.org/t/change-the-way-mass-changes-work/526 

:)

**Comment by thorsteneckel** [comment] 2018-07-16 16:49
@SummerStorm - can you please verify if this is still open if @mantas fixed it with [his changes](https://github.com/zammad/zammad/commit/9cdb0d5ce4e61eb8220000ff506fbde9747852e0) for issue #2088 . Thanks!

**Comment by SummerStorm** [comment] 2018-08-03 13:13
@thorsteneckel This usability issue is still present on the latest develop (9b495847d as of writing). I'll produce a fix for it.

**Closed** 2018-08-22 00:59 UTC
Labels: UX/UI, bug, frontend, verified
