### ISSUE TITLE
Internet Explorer 11 and lower - no paste from Clipboard possible

### ISSUE THREAD

**Issue by hagen3000** [zammad/zammad#990] opened 2017-04-25 11:09 UTC
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: package 1.5.0-1493027881.6460222.xenial
* Operating system: Ubuntu Server 16.04
* Browser + version: Internet Explorer 11

In Internet Explorer, it is not possible to insert text or images into a ticket from the clipboard. The problem already existed in Zammad 1.4.x.

**Comment by Jonske** [comment] 2017-05-22 06:09
Same here. Would be nice if this gets fixed in the next version.

**Comment by martini** [comment] 2017-05-22 10:18
Hi,

I tried to reproduce it, but without success.

Any more information about this issue available? Step by step description how to reproduce it?

Any hints in the browser console log?
 -Martin

I guess it's related to #801

**Comment by Jonske** [comment] 2017-05-22 10:27
We use Internet Explorer 11 Version 11.0.10240.17394 in our company. If a user creates and ticket and wants to copy/paste for example a text from a document or website into the "text" field, nothing happens.
It works on Mozilla Firefox though.

**Comment by hagen3000** [comment] 2017-05-22 11:27
I found this error in the console. This occurs when I insert text from the clipboard.

![grafik](https://cloud.githubusercontent.com/assets/7038961/26305996/e892ee90-3ef1-11e7-967b-cd04f16360c7.png)

**Comment by martini** [comment] 2017-05-22 16:46
I found some interesting issues and workarounds for that. But I'm not able to reproduce it.

I did the changes on https://issue990.zammad.com -> Can you login with

issue990 at zammad dot com : issue990

And check if paste in on IE is working there?

If not, console output would be good again.

 -Martin

**Comment by hagen3000** [comment] 2017-05-22 17:43
Hi @martini 

I get this error now if I want to paste into the text field.

![grafik](https://cloud.githubusercontent.com/assets/7038961/26321352/c6714da4-3f26-11e7-895d-54403646b602.png)

![grafik](https://cloud.githubusercontent.com/assets/7038961/26321278/75a47cb6-3f26-11e7-85c5-96ac6197a6d3.png)

**Comment by martini** [comment] 2017-05-22 17:46
Can you tell me, which OS version do you use?

**Comment by hagen3000** [comment] 2017-05-22 17:47
![grafik](https://cloud.githubusercontent.com/assets/7038961/26321535/67b668fc-3f27-11e7-8892-c24ddcdd32ed.png)

**Comment by martini** [comment] 2017-05-22 19:48
@hagen3000 thanks for feedback. Can your try again at issue990 dot zammad dot com? Thanks!

**Comment by hagen3000** [comment] 2017-05-22 20:56
Inserting text works without errors :)

Inserting images from the clipboard does not seem supported by IE.

![grafik](https://cloud.githubusercontent.com/assets/7038961/26328047/d0c1665c-3f41-11e7-8435-c7e481d19c17.png)

**Comment by martini** [comment] 2017-05-22 20:58
> Inserting images from the clipboard does not seem supported by IE.

It's supported by IE edge. If you have one by hand, feedback would be nice! Thanks a lot!

**Comment by hagen3000** [comment] 2017-05-22 21:02
Yes with Edge I can insert pictures :)

![grafik](https://cloud.githubusercontent.com/assets/7038961/26328215/6057a75e-3f42-11e7-8740-2090669e27c7.png)

**Comment by martini** [comment] 2017-05-22 21:03
Thanks for feedback. We work on the regular fix now...

**Comment by hagen3000** [comment] 2017-05-22 21:10
I can insert the image but I can not save the ticket. The image disappears. (Edge)

![grafik](https://cloud.githubusercontent.com/assets/7038961/26328489/88cd322a-3f43-11e7-9a03-b2a5f5cd735c.png)

**Comment by martini** [comment] 2017-05-23 09:27
Hi @hagen3000 

the not staved image is a different issue which is not IE releated (if you add one word it will be saved correctly).

Unfortunately IE 11 and lower is not supporting images or richtest to paste. :(

Anyway. Cut and paste of normal text works now (also in stable branch).

Go go Edge, we like you as new standard browser! 🥇 

 -Martin

**Closed** 2017-05-23 09:27 UTC
Labels: bug

**Comment by hagen3000** [comment] 2017-07-11 08:34
Unfortunately, text modules do not work ("::"). Is this also a limitation of Internet Explorer?

Zammad 1.5.0-1499180355.a85c1f0.xenial

**Comment by martini** [comment] 2017-07-20 15:27
@hagen3000 

> Unfortunately, text modules do not work ("::"). Is this also a limitation of Internet Explorer?

It's only with IE11. It's fixed in stable now (https://github.com/zammad/zammad/commit/74a20be60ddb5de0ad52ffd81d9bfffe9813a2d1).

 -Martin

**Comment by MNobis** [comment] 2017-12-06 12:07
Hi @martini 

We discoverd this exact problem right now with zammad 2.1.0-1512038077.2f8acf4f.xenial 

* Used Zammad version: 2.1.0-1512038077.2f8acf4f.xenial 
* Used Zammad installation source: (source, package, ...) deb
* Operating system: Ubuntu 16.04 LTS
* Browser + version:  IE at least Version 11.726.15063.0 Update Version: 11.0.48 (KB4047206)

We got the same result in the Console as Hagen did. We want to insert Text or Pictures there appears a "Sorry, can't insert markup because browser is not supporting it." message. Text can be inserted without any problem, pictures from clipboard not.

Pictures can also be pasted with the latest Versions of Chrome, FireFox and Edge.
