### ISSUE TITLE
REST Client Trigger

### ISSUE THREAD

**Issue by RosenbeF** [zammad/zammad#1130] opened 2017-05-24 09:06 UTC
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Docker

Triggers currently allow to change ticket states or to send E-Mails.
My goal is to trigger an external application (via REST) to add information to new tickets using the Zammad API. I'd rather not poll constantly for new tickets. So a REST-based trigger (i.e. a REST client) would be perfect for this use case.

Zammad does **not** need to evaluate the server response (yet).

### Expected behavior:

* Trigger option *Notfication -> REST Client*
* Specify REST resource URL to call
* Specify HTTP method (GET/PUT/POST)
* Specify fields to send (ticket id, customer, tags, ...)
* Format: JSON (optionally XML)

**Comment by thorsteneckel** [comment] 2017-05-28 15:36
@martini is this a duplicate of #290 ?

**Comment by thorsteneckel** [comment] 2018-05-22 09:38
This should be done via webhooks and is therefore a duplicate.

**Closed by thorsteneckel** 2018-05-22 09:38 UTC
Labels: feature backlog
