### ISSUE TITLE
Send new ticket via Telegram and Trigger notification via Telegram

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#1371] opened 2017-08-24 20:18 UTC
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: package
* Operating system: Debian Jessie
* Browser + version: Firefox 55.0.2

### Expected behavior:
Send new ticket via Telegram and send Trigger notification via Telegram
* 

### Actual behavior:
I can not find an option to send new tickets via Telegram. Also, I can not find an option to send trigger notifications via telegram.
* 

### Steps to reproduce the behavior:
Create new ticket and change Trigger notification 
*

**Comment by hanneshal** [comment] 2017-08-25 06:40
Thats right. Right now both functions are not implemented.

**Comment by Guglio95** [comment] 2018-02-09 16:21
Hi, actually in Zammad 2.3.x (via official docker-compose) I still cannot find " an option to send trigger notifications via telegram.".
In triggers i can only find "Notify > Email" 
Thankyou.

**Comment by martini** [comment] 2018-02-09 16:25
Hi @Guglio95 I can't find it too. Did you implement it?

**Comment by thorsteneckel** [comment] 2018-05-17 11:30
Dear @3ruce ,

first of all, many thanks for your participation on the Zammad open source project.

Not usual as with proprietary software, we finance Zammad through service. So it's less money we have at our disposal to push Zammad.

If you would like to support Zammad, you can do so via Zammad Support: https://zammad.com/pricing#selfhosted

For all issues it is generally important that we tag an issue as soon as it is included in a release. This means that manual enquiry only minimizes the available resources but not the speed of implementation.

Thank you for your understanding.

**Comment by thorsteneckel** [comment] 2020-07-29 13:36
This is actually a duplicate of #793 – Therefore closing now.

**Closed by thorsteneckel** 2020-07-29 13:36 UTC
Labels: feature backlog, integration, telegram
