### ISSUE TITLE
Dark mode quick switch does not reflect auto setting

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#4380] opened 2022-11-22 06:12 UTC
### Infos:

* Used Zammad version: 5.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version:v
* Elasticsearch version any:
* Browser + version: any

### Expected behavior:

* Dark mode quick switch reflects that „sync with computer“ option is selected

### Actual behavior:

* Dark mode quick switch shows mode currently in use. Clicking it overrides „sync with computer“

### Steps to reproduce the behavior:

* Go to Profile -> Appearance and select „sync with computer“
* Switch OS/Browser to Dark mode
* Dark mode quick switch shows this is dark mode. Clicking it changes Appearance setting.

### Possible solutions

* Disable quick switch when „sync with computer“ is selected
* Or add 3rd state to quick switch.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment] 2022-11-23 07:56
Looks to me more like an enhancement or?

Because when you use the quick fix you actively decided to no longer use the current synced state from the computer.
So the current behaviour sounds fine to me in the end.

**Comment by mantas** [comment] 2022-11-23 10:57
It seems ambiguous implementation of an existing feature. But yes, it's not a technical bug.

a) Let's say you click twice. Do you return back to original state (= auto)? Or save the state that was automatically picked in the first place? Now it does the later, but I'd expect former.

b) if you turn on „sync with computer“, this widget keeps showing current state. Which feels like the appearance option wasn't saved.

**Comment by MrGeneration** [comment] 2022-11-23 14:47
> b) if you turn on „sync with computer“, this widget keeps showing current state. Which feels like the appearance option wasn't saved.

duplicate of #4365 ...

**Comment by mrflix** [comment] 2023-03-20 08:50
@MrGeneration this is not a duplicate of #4365. That ticket is about a bug in the "sync with computer" mode and this ticket is about the quick switch in the user menu.

@mantas it's intended behavior that the quick switch and the shortcut overwrite "sync with computer". And switching back and forth between dark and light mode won't bring you back to "sync with computer". While the dark-mode toggle could be replaced by [segment controls](https://developer.apple.com/design/human-interface-guidelines/components/selection-and-input/segmented-controls) with three states: Theme "dark", "light" and "auto", the shortcut can't have three states. I think it's clean that the shortcut and the quick toggle have the same behavior.

I would close this feature request.

**Comment by mantas** [comment] 2023-03-20 09:23
@mrflix then at least it should be shown as disabled / non active / whatever while „sync with computer“ is on.

I do not agree that it's clear :)

**Comment by mrflix** [comment] 2023-03-20 10:14
Yeah it's not 100% clear but clear enough from my point of view. It's also easy to go into your settings to check the real state when you're not sure. I think it's fine that the quick toggle shows the currently detected mode when it's on sync mode.

**Comment by mantas** [comment] 2023-03-20 10:27
The problem is that it doesn't show currently detected mode. It acts as override that turns off the auto mode :)

**Comment by mrflix** [comment] 2023-03-20 10:32
It's intended to show the currently detected mode and to override the auto mode once interacted (same as with the `d` shortcut).

**Comment by mantas** [comment] 2023-03-20 10:34
IMO that's issue-by-design...

**Comment by dominikklein** [comment] 2024-04-08 10:19
Is fixed in the new desktop-view with a new toggle button which holds three states.

**Closed as completed by dominikklein** 2024-04-08 10:19 UTC
Labels: enhancement, verified, dark mode, wontfix in old desktop-app
