### ISSUE TITLE
Change gitlab server, Problem with linked Accounts

### ISSUE THREAD

**Issue by cyberrranger** [zammad/zammad#2732] opened 2019-09-06 15:06 UTC
If i change the gitlab server in "Third-party Applications" with a new list of users and with new ids, i have a problem with existing accounts

### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): docker
* Operating system: current
* Database + version: current
* Elasticsearch version: current
* Browser + version: all

### Steps to reproduce the behavior:

old github server
user:
1 -> USER A
2-> USER B
3 -> USER C

new github server
user:
1 -> USER A
2-> USER C
3 -> USER D

now with the new server, if **"USER C"** use login with gitlab. this user is NOW **"USER B"** on zammad.

or can i remove all linked accounts on all users?

**Comment by MrGeneration** [comment] 2019-09-06 15:13
Sorry but I believe that this is a technical question and not a bug.
Github is the wrong place for technical questions, please use the Community for such things: https://community.zammad.org

I also have no answer for this question at the moment, we'll fiddle around that at the Community.

Closing now.

**Closed as completed by MrGeneration** 2019-09-06 15:13 UTC
Labels: question
