### ISSUE TITLE
password reset message template failure

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#538] opened 2016-12-13 11:00 UTC
When a user resets their password, they receive an email confirming this action.
It looks like this:

![zammad_password_reset](https://cloud.githubusercontent.com/assets/3422185/21137792/81991208-c12b-11e6-95db-16bd52dc9cce.png)

Which is not correct. The *product_name* is set for out system.

**Comment by abenrob** [comment] 2016-12-13 11:08
cc @gerbsen

**Comment by martini** [comment] 2016-12-13 11:10
Thanks! It's a duplicate of #468 - it's already fixed. :)

**Comment by abenrob** [comment] 2016-12-13 11:11
Great - Thanks!

**Closed** 2016-12-13 11:10 UTC
Labels: duplicate

**Comment by martini** [comment] 2016-12-13 11:13
JFI: If you use the Zammad Packages (RPM or DEB), just update the package. After a bugfix a new release is build automatically.
