### ISSUE TITLE
Remove all Users from Overview does not work

### ISSUE THREAD

**Issue by maege** [zammad/zammad#944] opened 2017-04-12 12:54 UTC
### Infos:

* Used Zammad version: 1.4.x latest deb
* Operating system: Debian
* Browser + version: Chrome / Firefox

### Expected behavior:

* You can remove all Users from the List "Verfügbar für Benutzer" in the overview.

### Actual behavior:

* If you remove all Users from the Overview and Save the Changes. The Users are still selected.

### Steps to reproduce the behavior:

1. Create a overview or edit an existing overview and add some users in the "Verfügbar für Benutzer" and save.
2. Edit the overview and delete all users from the "Verfügbar für Benutzer" list and save.
3. Go again to the overview editing option and you will see that the users are still in the list.

**Comment by maege** [comment] 2017-05-02 14:29
The Problem still exists in 1.5.x and 1.6.x (dev)
https://www.youtube.com/watch?v=E5-rOdONZR8

**Comment by fthommen** [comment] 2017-05-17 08:26
More specific: You can remove all users **but** the last one from "Available for Users".  The issue should probably be renamed to "Cannot remove last user from Overview" or similar

**Comment by rolfschmidt** [comment] 2017-05-26 08:42
Hi @maege and @fthommen,
could you please check if the bug still exists ? I was not able to reproduce the error on https://zammad.com/getting-started.

- Rolf

**Comment by martini** [comment] 2017-05-26 08:42
@rolfschmidt The bug still exists.

**Comment by martini** [comment] 2017-05-26 08:48
@rolfschmidt sorry for confusing. With current stable it's working for me too (on FF & Chrome). 

@maege A short feedback would be fine!

**Comment by rolfschmidt** [comment] 2017-05-26 08:57
@martini und me found a way to reproduce it: It only occurs if the list of available users is empty after assigning users.

**Comment by martini** [comment] 2017-05-26 09:00
Wuha. Next update. I can reproduce if if you select all users on left side.

**Comment by rolfschmidt** [comment] 2017-05-29 12:19
Hi,
this bug should be fixed now in develop branch and will be released with version 2.0.0.

Rolf

**Closed by rolfschmidt** 2017-05-29 12:19 UTC
Labels: bug, UX/UI
