### ISSUE TITLE
Zammad interprets new line with spacing as end of Header

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2356] opened 2018-11-15 17:01 UTC
### Infos:

* Used Zammad version: 2.7
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a 
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* When having a new line with spacing in between the E-Mail header, Zammad will gladly import and intepret the E-Mail correctly without any trouble.

### Actual behavior:

* When having a new line with spacing in between the E-Mail header, Zammad will import the E-Mail without error message, but beginning with the new line with spacing in between, it will begin to paste the rest of the header inside the article body. This causes Zammad to show e.g. base64 content without intepreting it, causing attachments to not being attached.

### Steps to reproduce the behavior:

* Generate a E-Mail with headers (importing a eml-file that is prepared via IMAP is enough)
* Let Zammad import the E-Mail and take a look onto the result

```
X-MS-Has-Attach: yes
X-MS-TNEF-Correlator:
authentication-results: spf=none (sender IP is ) smtp.mailfrom=XXXX@XXXXXX;
 
x-ms-exchange-messagesentrepresentingtype: 1
x-originating-ip: [X.X.X.X]
x-ms-publictraffictype: Email
```

![image](https://user-images.githubusercontent.com/6549061/48604362-e8273b80-e979-11e8-8788-f7bb9a927eb4.png)

This issue has been found by **chesty** from our community: https://community.zammad.org/t/broken-email-headers/1536

Yes I'm sure this is a bug and no feature request or a general question.

For Devs: Sample file can be found within Ticket#1030792 - I also can supply a generic one.

**Comment by thorsteneckel** [comment] 2018-11-16 07:46
Hi guys. The mail parsing is done by a third party library named the "[mail](https://github.com/mikel/mail)" gem. However, it behaves correctly since spaces in headers are not allowed. As chesty already stated this is caused by a buggy mailserver which needs to get fixed. We faced this issue only twice over the last 16 years so the priority is pretty low for this. If this change we will surly take action. Closing now.

**Closed as completed by thorsteneckel** 2018-11-16 07:46 UTC
Labels: works as designed / wontfix, third party issue
