### ISSUE TITLE
LDAP agent group users also exist in LDAP customer groups; failure

### ISSUE THREAD

**Issue by pneumatic** [zammad/zammad#2540] opened 2019-04-08 13:51 UTC
* Used Zammad version: 2.9.x (from the 'Version' tab, I can't get the zammad cmdline to produce a proper version number)
* Installation method (source, package, ..): DEB (from latest stable)
* Operating system: Ubuntu 18.04
* Database + version: psql (PostgreSQL) 10.7 (Ubuntu 10.7-0ubuntu0.18.04.1)
* Elasticsearch version: Version: 5.6.16, Build: 3a740d1/2019-03-13T15:33:36.565Z, JVM: 1.8.0_191
* Browser + version: Chrome latest

### Expected behavior:
Map bulk LDAP groups (e.g. "Staff All") to Zammad customer roles.  Then map help desk agents (who exist in the bulk staff groups) into Zammad roles.  Additionally, mutual exclusivity exists between the 'customer' and 'agent' roles.  In my particular environment where multiple departments will be leveraging Zammad for workflow, it is probable that Zammad 'agents' from one department may be 'customers' of another set of 'agents' (e.g. the IT agents may submit a request to the mail room or HR).

### Actual behavior:
If the agent mapping is done at the bottom of the LDAP config, the 'customer' role prevails and everyone is a customer.  If the agent mapping is done at the top of the LDAP config, then the users in the agent group fail upon sync.  I've tried to 'promote' individuals from the Zammad users once the bulk customer mapping has been performed.  While this is tedious with the number of agents that we have, I thought that it could be a workaround for now.  But the LDAP sync overwrites those promotions and everyone is back to customer.

### Steps to reproduce the behavior:
Simply map a bulk user group into customers and then attempt to promote some of those users to agents with either another LDAP mapping or Zammad "promotion".

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by pneumatic** [comment] 2019-04-08 14:10
Additionally, once a particular LDAP group has failed, it will always fail.  In lieu of a known method for resetting the Zammad user database, I have been resorting to VM snapshots in troubleshooting this issue.  It would be nice to be able to have a purge function for the Zammad user db.

**Comment by Kquinn** [comment] 2019-05-24 23:45
I am not sure if the dev team needs to verify, but I have independently encountered, tested, and reproduced this in a lab environment.  Screenshots of the lab are attached in a zip archive.
[Zammad_LDAP.zip](https://github.com/zammad/zammad/files/3218688/Zammad_LDAP.zip)

The data that comes back from the user_roles function in /lib/ldap/group.rb appears to return proper data:
I, [2019-05-24T15:58:11.091326 #9000-47153109045540]  INFO -- : thread#-: group.rb user_roles mapping: {"cn=administrator 2,ou=zammad lab,dc=lab,dc=local"=>[1, 2, 3], "cn=administrator 1,ou=zammad lab,dc=lab,dc=local"=>[1, 2, 3], "cn=agent 3,ou=zammad lab,dc=lab,dc=local"=>[2, 3], "cn=agent 2,ou=zammad lab,dc=lab,dc=local"=>[2, 3], "cn=agent 1,ou=zammad lab,dc=lab,dc=local"=>[2, 3], "cn=end user 5,ou=zammad lab,dc=lab,dc=local"=>[3], "cn=end user 4,ou=zammad lab,dc=lab,dc=local"=>[3], "cn=end user 3,ou=zammad lab,dc=lab,dc=local"=>[3], "cn=end user 2,ou=zammad lab,dc=lab,dc=local"=>[3], "cn=end user 1,ou=zammad lab,dc=lab,dc=local"=>[3]})

But I also see this in the log immediately following:
E, [2019-05-24T15:58:11.384452 #9000-47153109045540] ERROR -- : Role Customer conflicts with Agent (RuntimeError)

@pneumatic 
It appears that the failure is occurring because of a raised exception (app/models/user.rb:1050):
`    raise "Role #{role.name} conflicts with #{local_role.name}"`
Commenting this line in a lab environment allows admins, agents, and customers get created. This should not be commented in production. See next posts for future solution(s).

**Comment by thorsteneckel** [comment] 2019-05-25 13:43
Hey @Kquinn - thanks for your post and kudos for digging in. Unfortunately I have to tell you that this is a bad idea and will eventually lead to unexpected behavior. Zammad currently doesn't support to have users in the customer and agent role at the same time. The removed line is a safety mechanism until we add support for this functionality to protect from errors all over the application.
Good news is that we prioritized this functionality and will implement it soon. I can't tell you yet when exactly but let you know as soon as we can.

**Comment by Kquinn** [comment] 2019-05-25 13:57
Thanks for the reply @thorsteneckel 
I did not mean for that change to be put into production, my post is meant to be about my lab environment only, and I just wanted to point out the location where the failure happens in code. I will edit my previous post to make that clear.

I assumed that the current functionality was intentional, because I see the work done to keep these roles separate. It is encouraging to hear that it is a work in progress. In the mean time, do you think the problem @pneumatic and I are experiencing could be solved by checking and removing the Customer role when a user is assigned to Customer+Agent or Customer+Agent+Admin instead of raising an exception?

**Comment by MrGeneration** [comment] 2019-05-25 14:27
I think that it will not be needed to give an agent customer rights. Maybe I don't get the use case to mixup user groups in that way (please correct me if I'm wrong).

I think that this works as designed and, when time comes, will be adressed by this issue: https://github.com/zammad/zammad/issues/967

Yes, this will still not allow you  to assign an agent the customer role at the same time. Maybe it's just me seeing this as a configuration issue (no offense!).

**Comment by Kquinn** [comment] 2019-05-25 15:24
@MrGeneration  - You are correct. There is no need to give Customer rights to an Agent. That is why my proposed solution above was to remove the Customer role for users who are in multiple synchronized groups instead of raising an exception.

#967 looks useful, but I do not think it is the same issue.

No offense taken, I appreciate your perspective on this, but I also would not consider it a configuration issue.

I believe this problem exists because the way Admin/Agent/Customer roles are designed do not align with best practices for Microsoft Active Directory (AD) Groups. Most AD configurations have one top-level group "All Users", which literally contains every user including those who would be assigned to roles of Customer, Agent, or Admin. There are also subgroups such as "IT Department", which may hold users who may have Agent or Admin roles. There are often further subgroups such as "IT Managers", which may hold only users with the Admin role. This type of structure is necessary for assigning permissions and is sometimes also used to create and maintain email communication groups. When we synchronize users into Zammad, we want to use our existing structure.

You can see the example in my lab in image Zammad_ActiveDirectoryConfig.PNG attached to my first post in this issue.

**Comment by thorsteneckel** [comment] 2020-07-30 07:17
#967 is currently under active development and will be released with the upcoming version 3.5 of Zammad. This will enable Users to be Agent and Customer at the same time and therefore resolve the underlying issue here. I'm therefore closing it as a duplicate of #967 – in the broader sense. Thanks for your patience.

**Closed as completed by thorsteneckel** 2020-07-30 07:17 UTC
Labels: duplicate
