### ISSUE TITLE
URL containing  + symbols are mangled upon click to open

### ISSUE THREAD

**Issue by casusbelli** [zammad/zammad#2364] opened 2018-11-21 09:08 UTC
### Infos:

* Used Zammad version: 2.5 (but i did not find this issue in the change log)
* Installation method (source, package, ..): not relevant
* Operating system: not relevant
* Database + version: not relevant
* Elasticsearch version: not relevant
* Browser + version: Google Chrome Version 70.0.3538.77 (Offizieller Build) (64-Bit)

### Expected behavior:

* Adding an URL containing a '+' symbol to a tickets messages should allow to click and open this URL. My example is: https://bugs.launchpad.net/nova/+bug/1737131

### Actual behavior:

* upon clicking the URL it is opened but the '+' symbol in that URL is converted to %20 and the new view therefore fails to open the URL. Example result is: https://bugs.launchpad.net/nova/%20bug/1737131

(note: I'd expect this to be encoded as %2B if encoding is required).

### Steps to reproduce the behavior:

1.   Add the example URL to a ticket message in Zammad
2.  Update the ticket
3.  Click the URL

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2018-11-21 14:42
This is a duplicate of #2283

**Closed as completed by MrGeneration** 2018-11-21 14:42 UTC
Labels: duplicate
