### ISSUE TITLE
email address mandatory

### ISSUE THREAD

**Issue by rfool** [zammad/zammad#860] opened 2017-03-19 08:47 UTC
Hi,

when creating a new customer, an email address is required. Seems plausible, but in practice there are situations where I may want to create a ticket and a new customer without knowing an email address yet.

But Zammad requires the email address, and I, the user, got totally stuck in that situation.

As you can see in the screenshot, the UI blocks me from pushing on. It outbrakes me on one of its inner core dialogs. And I would probably have switched back to paper and pencil in that situation ;-)

BTW: maybe some of the other fields should also not be mandatory, e.g. the first name.

![zammad-new-ticket-new-user](https://cloud.githubusercontent.com/assets/5239047/24079475/39791546-0c89-11e7-8a39-31608e1fd779.png)

**Comment by thorsteneckel** [comment] 2017-03-19 12:23
This is often requested duplicate of #613 - which is on our priority list.

**Closed by thorsteneckel** 2017-03-19 12:23 UTC
