### ISSUE TITLE
Customer overview doesn't load on change

### ISSUE THREAD

**Issue by delphi-sucks** [zammad/zammad#3479] opened 2021-03-29 07:36 UTC
### Infos:

* Used Zammad version: 4.0.0
* Installation method (source, package, ..): package 4.0.0-1616833066.ac840931.xenial
* Operating system: Ubuntu 16.04.7 LTS
* Database + version: MySQL 5.7.33
* Elasticsearch version: 7.12.0
* Browser + version: Vivaldi 3.7.2218.49, Microsoft Edge 89.0.774.63
* Ticket#1085588, #1085380, #1086549

[production.log](https://github.com/zammad/zammad/files/6220040/production.log)

A completely fresh install was used to reproduce this bug, but also exists in an existing installation upgraded from 3.6.

### Expected behavior:

When changing the overview the ticketlist should change to the selected ticket-overview.

### Actual behavior:

When changing the overview the ticket-list disappears and leaves a grey empty space.
Refreshing the page is needed to get the view.

### Steps to reproduce the behavior:

1. Login as customer with multiple views
2. have at least one ticket
3. try changing between the views
=> ticketlist disappears and stays grey

![20210329 092424 - CEjp87Rq3P](https://user-images.githubusercontent.com/17913239/112801877-b6f2c600-9071-11eb-918f-7811bd776d16.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-03-29 08:21
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by delphi-sucks** [comment] 2021-03-29 08:45
**I'm sorry, but how and where is this a technical question?**

This is a bug which occured with the update from 3.6.0 to 4.0.0.
If I setup a system with 3.6.0 it works.
I Just setup another system with Debian 10, Nginx, MariaDB and Zammad 4.0.0 and was able to reproduce it on the spot.

I can only repeat what is said in the first post; This is not a question but an existing bug.

**Comment by MrGeneration** [comment] 2021-03-29 12:39
Just for you I've invested another 30 minutes to be extra sure.

> This is a bug which occured with the update from 3.6.0 to 4.0.0.
This is not a bug.
Both, postgresql and mysql installations do work on my machine™.
I tested this twice (today in the morning and just now).

I even had a from scratch installation during my second try.
I also used and tested M$ Edge. It's working just fine.

The only difference between my Debian 10 and yours is that I cannot install MariaDB 5.x - I only have v10 available.
This is why I expect this to be a technical question.

I followed the documentation, please double check that you run all these steps and consult the community.
   * https://docs.zammad.org/en/latest/prerequisites/software.html#database-server
   * https://docs.zammad.org/en/latest/install/package.html
   * -OR- https://docs.zammad.org/en/latest/install/source.html

If we can't reproduce an issue, it's either a race condition or (more likely) not a bug. ;-(

```
root@issue3479:~# apt-cache policy zammad
zammad:
  Installed: 4.0.0-1616833066.ac840931.buster
  Candidate: 4.0.0-1616833066.ac840931.buster
  Version table:
 *** 4.0.0-1616833066.ac840931.buster 500
[...]
 ```

**Comment by MrGeneration** [comment] 2021-04-06 10:44
I reopened this over favor of #3497 to keep the original finder. Sorry for the trouble.

**Comment by rolfschmidt** [comment] 2021-04-28 12:36
Hi @delphi-sucks ,
thank you very much for your report. I was able to reproduce it and will fix it asap.

**Comment by thorsteneckel** [comment] 2021-04-29 10:17
Fixed in develop! @rolfschmidt would you mind creating the backport to stable?

**Comment by rolfschmidt** [comment] 2021-04-29 10:18
@thorsteneckel ok

**Comment by rolfschmidt** [comment] 2021-04-30 06:31
should be fixed in stable also now ;-)

**Closed as completed by rolfschmidt** 2021-04-30 06:31 UTC
Labels: bug, UX/UI, overviews, verified, prioritised by payment
