### ISSUE TITLE
Search is limited to 50 results 

### ISSUE THREAD

**Issue by Darko2906** [zammad/zammad#2142] opened 2018-07-24 09:22 UTC
### Infos:

* Used Zammad version: 2.5.x
* Installation method (source, package, ..): docker-compose
* Operating system: ubuntu
* Database + version: postgres 9.6.9
* Elasticsearch version: 5.6.9
* Browser + version: Version 67.0.3396.99
* Ticket-ID: #1059560, #1060685, #1082736, #1083185, #1085156, #1086717, #10101683, #10119165, #10141878, #10142762, #10145404, #10145536, #10154197, #10155118, #10155419, #10158099, #10159686, #10160700, #10162411

### Expected behavior:

* Show pagination in search results. 

### Actual behavior:

* Search is limited to 50 results.

### Steps to reproduce the behavior:

* Start a search. ;)

Yes I'm sure this is a bug and no feature request or a general question.

Related Tickets: #1744 and #1951

**Comment by thorsteneckel** [comment] 2018-07-24 09:30
Hi @Darko2906 - as you mentioned correctly this was already addressed and fixed in the two related issues. I assume you are talking about a different (part of the) functionality then? It's not clear from your `Expected behavior` / `Actual behavior`. Please provide more context / information so we can reason about your request.

**Comment by Darko2906** [comment] 2018-07-24 10:02
Hi @thorsteneckel. The problem is, that pagination does not work for me, My search results are always capped at 50 entrys. As I read in the tickets, with version 2.5.x there should be a offset pagination. 

For example:

I have 100k+ Tickets in Zammad and searched for "y". My result is still 50 Tickets without pagination:

![pic1](https://user-images.githubusercontent.com/40241484/43131190-b826326a-8f38-11e8-9ff9-75bc5f91e506.PNG)

Thanks in advance

**Comment by thorsteneckel** [comment] 2018-07-24 11:42
Hi @Darko2906 - thanks for clarification. I think this is a valid use case. We can keep the issue. However, the priority of this is rather low for now since 100k tickets is pretty impressive but remains an edge case for now. We are still busy building the functionalities that cover the needs of the broad user base.

If you are interested in prioritizing this feel free to contact our support team for our commercial services.

**Comment by Stoef23** [comment] 2019-03-12 09:50
I have installed Zammad 2.9.0 with also over 100k tickets and the search function is still limited to 50 and no pagination. It's useless like this. Are there any plans to fix this?

**Comment by MrGeneration** [comment] 2019-03-12 10:01
We currently have no roadmap on this. We will update this issue as soon as we're working on this / having plans. Sorry about that.

**Comment by thorsteneckel** [comment] 2019-03-12 10:05
Hi @Stoef23 - wow, 100k tickets is quite nice. Reads like you're using/evaluating Zammad in a professional enterprise environment. We'd love to improve your/the situation! However, as you already wrote this affects only larger setups. We're currently focusing on functionalities from which the broad user base profits most. If you're interested in getting this functionality forward please make sure to check out our [commercial services](https://zammad.com/pricing) - which include feature/bug prioritization and custom development.
Otherwise we have to ask you to be patient and have an eye on our [current short term roadmap](https://github.com/zammad/zammad/milestones).

**Comment by Stoef23** [comment] 2019-03-12 10:46
I did install Zammad 2.9 and tested a migration from OTRS. That's why i had so many tickets from the beginning. All worked fine, but the search function seemed to be buggy. Thank you for letting me know.

**Comment by Darko2906** [comment] 2019-03-12 12:04
> I did install Zammad 2.9 and tested a migration from OTRS. That's why i had so many tickets from the beginning. All worked fine, but the search function seemed to be buggy. Thank you for letting me know.

Hi @Stoef23 - We came from the same point. We also migrated 100k+ from OTRS and have 160k Tickets in Zammad now.

Our agents work around this issue with the advanced search. For us it works well so far. Maybe it´ll help you to:

https://user-docs.zammad.org/en/latest/advanced/search.html

**Comment by InsaneSplash** [comment] 2019-09-12 07:36
I seem to still be having this issue even with the latest version of zammad. I checked the above code and it is set to show 200 per page, however there is no pagination and is limited to 50?

![image](https://user-images.githubusercontent.com/16985649/64763690-d2a28400-d540-11e9-9940-9e67693310a1.png)

**Comment by MrGeneration** [comment] 2019-09-13 17:52
Just for reference: This is what InsaneSplash is talking about:
https://github.com/zammad/zammad/issues/1744#issuecomment-383822443

However, as this is rather a technical question, we should the discussion to the Community: https://community.zammad.org

I'm therefor limitting the conversation to contributors only. Sorry.

**Comment by dominikklein** [comment] 2024-12-04 14:50
Closed because of https://github.com/zammad/zammad/issues/5384

**Closed as completed by dominikklein** 2024-12-04 14:50 UTC
Labels: enhancement, verified, hardcoded limit
