### ISSUE TITLE
Changing customer of a ticket not affecting mail address of notifications

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1830] opened 2018-02-13 11:40 UTC
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..):
* Operating system: CentOS 7
* Database + version: postgres
* Elasticsearch version: 5.6
* Browser + version: variuos

### Expected behavior:

* Changing the customer that the ticket is owned by should change the email address that the agent reply will be sent to.
For example, if i have an answering service that answers my business calls and send the content of the call as text to the ticketing system, the owner of the ticket (the customer) at Zammad will be the company that provides the answering services for me and not the final user that needs help.
If i am changing the customer to the correct user, Zammad should send my reply to the new user and to the original one that opened the ticket.

### Actual behavior:

* Changing customer for a ticket does not change the address of the recipient that should receive answers from Zammad.

### Steps to reproduce the behavior:

* Change the customer of a ticket and press "reply" - the address that shows at the replt field is the original address and not the one of the designated customer.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment] 2018-03-07 15:54
I understood what your issue is. The difference is, that Zammad uses reply recipients based on article recipients list where you reply on.

The reason is, Zammad can manage the communication with the customer and e. g. an external supplier in one ticket.

**Comment by MrGeneration** [comment] 2019-03-07 13:46
Heya,

sorry for the huuugeee delay on this.
This works as designed, you'd want to change your trigger.

Basically you need to decide if your trigger wants to inform the ticket customer or the sender of the last article. Customer will be the customer you set (this will be different when on initial ticket creation, as Zammad will set the correct customer here according to the last article sender). Last article sender will always be the one that wrote.

I hope that helps.

Trigger:
![image](https://user-images.githubusercontent.com/6549061/53960826-8c7aec80-40e7-11e9-91f1-2712cd7c0a1e.png)

Result: 
![image](https://user-images.githubusercontent.com/6549061/53960805-7ec56700-40e7-11e9-968a-bdf03b680b90.png)

I'll be closing this issue.

**Closed by MrGeneration** 2019-03-07 13:46 UTC
Labels: works as designed / wontfix
