### ISSUE TITLE
Known devices can't be deleted from list under Profile->Devices

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2939] opened 2020-02-20 08:02 UTC
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version:
* Elasticsearch version:
* Browser + version: 

### Expected behavior:

* When clicking on the delete button you can remove devices from the known devices list.

### Actual behavior:

* The button has not effect:
![image](https://user-images.githubusercontent.com/44224243/74912762-9ad91b80-53bf-11ea-83cc-9d3bf63f7a9a.png)

### Steps to reproduce the behavior:

* Log in from multiple devices.
* Get email notification that a new log in from new device is detected.
* Try to delete an older entry

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2020-02-20 08:11
Hi @SEGGER-NV - this is actually a duplicate of #2781 which was just [fixed yesterday](https://github.com/zammad/zammad/commit/c7ab3e1fe2238299e9bd5f59a9669387fd782a0f) via #2935 thanks to @bolah2009 <3 It will be released with Zammad 3.3 - probably next week 🚀

**Closed as completed by thorsteneckel** 2020-02-20 08:11 UTC
Labels: duplicate

**Comment by SEGGER-NV** [comment] 2020-02-20 08:19
Ah sorry, for some reason I got no "similar threads" dropdown while creating a thread in github. Weird.
Can be ignored then.
