### ISSUE TITLE
Deep link to overviews doesn’t work with version 6

### ISSUE THREAD

**Issue by cwrm** [zammad/zammad#4722] opened 2023-07-17 16:21 UTC
### Used Zammad Version

6.0.0

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian buster (
- Database + version:   mariadb 10.3
- Elasticsearch version: 7.17.10
- Browser + version: tested with firefox, chrome and safari

### Actual behaviour

Hi,

a link to the ticket overviews (e.g. https://zammad.host.tld/#ticket/view) loads an empty page if the user is not logged in. With version  5.4.0 installed, user are redirected to login page.

### Expected behaviour

Users should be redirected to the login page.

### Steps to reproduce the behaviour

 Log out, replace `/#login` with `/#ticket/view` in the address bar and hit enter.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2023-07-18 05:18
Duplicate of https://github.com/zammad/zammad/issues/4664. Closing.

**Closed as not planned by fliebe92** 2023-07-18 05:18 UTC
Labels: duplicate
