### ISSUE TITLE
Emails contains "strange" content which is not viewable if email is opened in other email client.

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3768] opened 2021-09-27 08:03 UTC
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* show emails in Zammad like in other email clients

### Actual behavior:

* Zammad shows content of `<script type="application/ld+json">` tags

### Steps to reproduce the behavior:

* process html email with following content:

```
<script type="application/ld+json">{"@context":"http://schema.org","typ=
e":"EmailMessage","description":"Anfrage betrachten","potentialAction":{"@t=
ype":"ViewAction","target":"https://example.com/servicedesk/cu=
stomer/portal/25/TBG-1910?token=sometoken","name":"Anfrage betrachten"},"publisher=
":{"@type":"Organization","name":"Example","url":"https://www.example.com" }} </script>
```

**Comment by thorsteneckel** [comment] 2021-09-28 08:27
Duplicate of #3365

**Closed as completed by thorsteneckel** 2021-09-28 08:27 UTC
Labels: duplicate
