### ISSUE TITLE
{"error":"Role Customer conflicts with Admin"}

### ISSUE THREAD

**Issue by PatrickGoenner** [zammad/zammad#1509] opened 2017-10-05 08:48 UTC
Good morning,

we have updated Zammad to version 2.0.x.

Now, when an agent wants to create a new ticket, a window with StatusCode: 500 {"error":"Role Customer conflicts with Admin"} is popping up. How must the role Agent be modified or have I also enter all Agents to Admin?

Cheers
Patrick

**Comment by muhammadn** [comment] 2017-10-05 11:54
This means that you cannot have both Customer and Admin roles at the same time. 

If you want to correct this problem by restricting the user as a customer, follow the steps below.

before you start, you need to go to the console and set it. To go to the console, you can read here:
[https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console
)
```
u = User.find_by(email: 'yourcustomer@yourcustomer.com)
u.roles = Role.where(name: 'Customer'')
u.save!
```

**Comment by PatrickGoenner** [comment] 2017-10-05 12:09
After I have set "Aktiv bei Neuanmeldung" to "no" on both roles, Agent and Customer, everything works fine again, without warnings. So restrictings are not nessecary.

**Comment by muhammadn** [comment] 2017-10-05 12:57
Should be only be one role, either agent or customer if you need it. You can't have both and i believe this is a bug.

**Comment by hanneshal** [comment] 2017-10-06 10:21
See also:
https://github.com/zammad/zammad/issues/1488

**Comment by muhammadn** [comment] 2017-10-08 11:14
I have found the bug, though i had looked at it at the lower model layer.

The problem is that the roles are inserted (saved) when we call `u.role = Role.where(name: ['Agent', 'Customer']` and the error for roles only happens when we do `u.save!` which is after that. The example of the bug is in the code block below.

I will add some code to do a check on this when calling the `Role` model in has_and_belongs_to_many's before_add callback.

```
 2.4.1 :001 > u = User.find_by(email: 'test1@test.com')
  User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "test1@test.com"], ["LIMIT", 1]]
 => #<User id: 4, organization_id: nil, login: "test1@test.com", firstname: "Test1", lastname: "Test", email: "test1@test.com", image: nil, image_source: nil, web: "", password: "$argon2i$v=19$m=65536,t=2,p=1$tXl9UzCC5+p0VSD4+k2v...", phone: "", fax: "", mobile: "", department: "", street: "", zip: "", city: "", country: "", address: "", vip: false, verified: false, active: true, note: "", last_login: "2017-10-07 13:39:15", source: nil, login_failed: 0, out_of_office: false, out_of_office_start_at: nil, out_of_office_end_at: nil, out_of_office_replacement_id: nil, preferences: {"notification_config"=>{"matrix"=>{"create"=>{"criteria"=>{"owned_by_me"=>true, "owned_by_nobody"=>true, "no"=>false}, "channel"=>{"email"=>true, "online"=>true}}, "update"=>{"criteria"=>{"owned_by_me"=>true, "owned_by_nobody"=>true, "no"=>false}, "channel"=>{"email"=>true, "online"=>true}}, "reminder_reached"=>{"criteria"=>{"owned_by_me"=>true, "owned_by_nobody"=>false, "no"=>false}, "channel"=>{"email"=>true, "online"=>true}}, "escalation"=>{"criteria"=>{"owned_by_me"=>true, "owned_by_nobody"=>false, "no"=>false}, "channel"=>{"email"=>true, "online"=>true}}}}, "intro"=>true}, updated_by_id: 3, created_by_id: 3, created_at: "2017-10-07 12:44:55", updated_at: "2017-10-07 13:41:03"> 
2.4.1 :002 > u.roles = Role.where(name: ['Agent', 'Customer'])
  Role Load (0.9ms)  SELECT "roles".* FROM "roles" WHERE "roles"."name" IN ('Agent', 'Customer')
  Role Load (0.4ms)  SELECT "roles".* FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1  [["user_id", 4]]
   (0.1ms)  BEGIN
  SQL (0.6ms)  INSERT INTO "roles_users" ("user_id", "role_id") VALUES ($1, $2)  [["user_id", 4], ["role_id", 3]]
  Permission Load (0.4ms)  SELECT "permissions".* FROM "permissions" INNER JOIN "permissions_roles" ON "permissions"."id" = "permissions_roles"."permission_id" WHERE "permissions_roles"."role_id" = $1  [["role_id", 3]]
   (1.4ms)  COMMIT
 => #<ActiveRecord::Relation [#<Role id: 2, name: "Agent", preferences: {"not"=>["Customer"]}, default_at_signup: false, active: true, note: "To work on Tickets.", updated_by_id: 1, created_by_id: 1, created_at: "2017-10-07 12:35:32", updated_at: "2017-10-07 12:35:32">, #<Role id: 3, name: "Customer", preferences: {"not"=>["Agent", "Admin"]}, default_at_signup: true, active: true, note: "People who create Tickets ask for help.", updated_by_id: 1, created_by_id: 1, created_at: "2017-10-07 12:35:32", updated_at: "2017-10-07 12:35:32">]> 

2.4.1 :003 > u.save!
   (0.2ms)  BEGIN
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."login" = $1 LIMIT $2  [["login", "test1@test.com"], ["LIMIT", 1]]
  Permission Load (0.4ms)  SELECT "permissions".* FROM "permissions" INNER JOIN "permissions_roles" ON "permissions"."id" = "permissions_roles"."permission_id" WHERE "permissions_roles"."role_id" = $1  [["role_id", 2]]
  Role Load (0.3ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Role Load (0.4ms)  SELECT "roles".* FROM "roles" WHERE (LOWER(name) = LOWER('Customer'))
   (0.2ms)  ROLLBACK
RuntimeError: Role Agent conflicts with Customer
	from app/models/user.rb:977:in `block (2 levels) in validate_roles'
	from app/models/user.rb:972:in `each'
	from app/models/user.rb:972:in `block in validate_roles'
	from app/models/user.rb:968:in `each'
	from app/models/user.rb:968:in `validate_roles'
	from (irb):3

```

**Comment by martini** [comment] 2017-10-08 11:28
@PatrickGoenner @muhammadn 

That's correct. Per default Zammad do not support customer and admin (or agent). For security reasons only customer or agent/admin is allowed.

What is the use case where you want to to have a customer as system admin?

**Comment by muhammadn** [comment] 2017-10-08 12:19
@martini actually the logic is the same but the problem was that there was no validation at the backend. (only frontend)

This is the logic i have.
Can:
Agent only
Agent + Admin
Customer only

Cannot:
Customer + Admin
Agent + Customer

**Comment by muhammadn** [comment] 2017-10-09 11:21
Should i remove the old `role_validations` code which seems redundant in validating roles?

**Comment by thorsteneckel** [comment] 2017-10-25 09:04
This is fixed with the commit above thanks to the great contribution of @muhammadn . It's available in the current development release and will be part of the next Zammad release in the next couple of days. Closing now. Feedback would be great.

**Closed by thorsteneckel** 2017-10-25 09:04 UTC
Labels: bug, verified
