### ISSUE TITLE
Macro note with variables do not replace variable with content (issue #2716)

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#3283] opened 2020-11-16 17:22 UTC
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): package
* Operating system: Centos 7
* Database + version: Postgresql 9.2.24
* Elasticsearch version: 5.6.16
* Browser + version: Gooele chrome last

A bug not resolved https://github.com/zammad/zammad/issues/2716
It returns variables + HTML tags

![image](https://user-images.githubusercontent.com/11810187/99285779-a9fed400-2840-11eb-9c5f-01146d23f473.png)
![image](https://user-images.githubusercontent.com/11810187/99285809-b2efa580-2840-11eb-81ac-b5f2754c5134.png)

### Expected behavior:

*

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by YosefAdPro** [comment] 2020-11-16 17:25
Sorry, in my case it's a macro and not a trigger

**Comment by MrGeneration** [comment] 2020-11-16 17:59
Duplicate of #2980

**Closed as completed by MrGeneration** 2020-11-16 17:59 UTC
Labels: duplicate
