### ISSUE TITLE
Quote the message from the customer and ticket history in the outgoing mail

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1099] opened 2017-05-16 18:51 UTC
Hello, 

how can the previous conversation be quoted by the customer? 
Can the complete ticket history be added to the outgoing mail?

**Comment by monotek** [comment] 2017-05-16 22:07
How should that work? 
It totally depends on the mailclient of the customer.

**Comment by babakkazemi** [comment] 2017-05-17 05:10
@monotek I think he means how to do it in zammad web interface. @Linus2017 just highlight the part you want to quote, then click reply.

**Comment by martini** [comment] 2017-05-29 08:13
It's currently only supported to quote related parts of customers message, see https://github.com/zammad/zammad/issues/571#issuecomment-269484660

Duplicate of https://github.com/zammad/zammad/issues/571

**Closed** 2017-05-29 08:13 UTC
Labels: duplicate
