### ISSUE TITLE
Online notifications not being send for old users

### ISSUE THREAD

**Issue by ToolingModus** [zammad/zammad#5043] opened 2024-02-06 11:18 UTC
### Used Zammad Version

6.2.0

### Environment

- Installation method: zammad-docker-compose
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 11 on container host system
- Database + version:  postgresql 15.3-alpine
- Elasticsearch version: 8.8.0
- Browser + version: edge 121.0.2277.106

### Actual behaviour

We have 3 agents in our Zammad system.
2 agents have been present for multiple years already. The third agents has only recently been created.

The 2 old agents do not receive online notifications for new tickets. The third new agent does receive these online notifications for new tickets.
Updates on existing tickets do result in online notifications for all users. All users have notifications for new tickets enabled in their profile settings. We have also tried the option "reset to default settings" for the notification settings and then enabling the notification for new tickets once again. The issue was still present.

I have recently upgraded from zammad 5.4.1 -> 6.0.0 -> 6.2.0. This issue however occurred on version 5.4.1 already and is still present in 6.2.0.
Could there maybe be some kind of issue with a database record for the old users?

This is the history for a new ticket where you can see that a notification is only send for the third new user:
![image](https://github.com/zammad/zammad/assets/117843575/cd05479a-52aa-424b-91e5-11b490c7b4e4)

### Expected behaviour

All agents receive a notification for new tickets.

### Steps to reproduce the behaviour

unkown.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment] 2024-02-06 11:19
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Bozo0511** [comment] 2024-04-11 12:18
@ToolingModus with the description provided I could not reproduce the issue.

If you could provide detailed Information of the User Attributes and the notification settings for each user?
Or if you could provide step-by-step instructions on how to recreate the issue?

**Comment by mgruner** [comment] 2024-09-12 12:43
I'll close this issue now, please feel free to add more information.

**Closed as not planned by mgruner** 2024-09-12 12:43 UTC
Labels: waiting for feedback, needs verification
