### ISSUE TITLE
ERROR: Can't process email

### ISSUE THREAD

**Issue by Apokalypser** [zammad/zammad#2250] opened 2018-09-23 16:17 UTC
### Infos:

* Used Zammad version: 2.6.0
* Installation method (source, package, ..): source
* Operating system: Debian 8
* Database + version: MySQL 5.6.35
* Browser + version: Any

### Expected behavior:

* Parse mail to ticket

### Actual behavior:

* No ticket created

log/production.log has no lines in the minute the system received the mail.

tmp/758e9b85e701f3922cad5f05cc4081e3.eml:
[758e9b85e701f3922cad5f05cc4081e3.eml.zip](https://github.com/zammad/zammad/files/2408889/758e9b85e701f3922cad5f05cc4081e3.eml.zip)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-09-24 06:46
Hi @Apokalypser - thanks for providing the email. I just imported it on lastest `develop` and `stable` without any issues. Let me know if the issue still persists for you when running `cat /path/to/758e9b85e701f3922cad5f05cc4081e3.eml | rails r 'Channel::Driver::MailStdin.new'` after updating to latest `stable`. If so, please check the log file and provide the relevant block including the backtrace. Closing now.

**Comment by lobiman** [comment] 2019-01-24 11:35
Hi,

I've the same issue.

Infos:
Used Zammad version: 2.8.0
Installation method (source, package, ..): source
Browser + version: Any
Expected behavior:
Parse mail to ticket
Actual behavior:
No ticket created

I've updated zammad in December, where can I see if there is a newer version?

[unprocessable_mail.txt](https://github.com/zammad/zammad/files/2791481/unprocessable_mail.txt)
[production.txt](https://github.com/zammad/zammad/files/2791482/production.txt)

I've replaced Domain with TLD and Names with Name.

**Comment by thorsteneckel** [comment] 2019-01-24 11:52
Hi @lobiman - I can import the provided mail without an error in the latest `develop` and `stable` version.  Please update your system accordingly and try again.
In addition to that please don't recycle closed issues but create a new one if it's actually a technical issue. If you have any (technical) questions please use the [community board](http://community.zammad.org/) because we only track technical issues on the issue tracker. Thanks for your understanding!

**Closed as completed by thorsteneckel** 2019-01-24 11:52 UTC
Labels: can't reproduce
