### ISSUE TITLE
Typing the text attribute in the ticket changes the displayed name of the ticket in the activity stream

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4329] opened 2022-10-28 11:43 UTC
Used Zammad version: 5.3.0
Installation method (source, package, ..): any
Operating system: any
Database + version: any
Elasticsearch version: any
Browser + version: MS Edge, Version 108.0.1462.46 (Official Build) (64-bit)
Ticket: #10117327

### Expected behavior:

* When an agent types in the data in the text field attribute, "XY has updated ticket xx with an article" is displayed in the activity stream. 

### Actual behavior:

* When an agent types in the data in the text field attribute, the activity stream displays "XY updated ticket title", but instead of the ticket title, anything you type in the text field attribute is displayed in the activity stream in effectively replacing the ticket title in the stream. Initially, only the name of the newest article is replaced with the entered text, after reloading the page, all other entries in the activity stream, except the first one, are replaced as well.
When data is typed in the mandatory field attribute, "XY has updated ticket xx with an item" will be replaced in the notifications with the word(s) previously typed in the mandatory field.

### Steps to reproduce the behavior:

* create a mandatory text field with the name `name` as a ticket attribute --> create a ticket --> enter some information in the text field --> refresh the page and look up the activity stream and the notifications bar. Only the original entry about the created title will be displayed with the title, every other entry will be displayed updated with the latest information typed in the mandatory text field.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Suhopoljac** [comment] 2022-11-21 11:03
The reported behavior can no longer be reproduced, labels have been removed.

**Comment by Suhopoljac** [comment] 2022-12-14 10:44
Additional information posted, issue reopened.

**Comment by mantas** [comment] 2023-01-10 14:31
Closing as not reproducible anymore.

**Comment by MrGeneration** [comment] 2023-01-17 12:28
It would be great if @Suhopoljac could either provide even more info or help @mantas to reproduce this.
This is the third time we're touching this issue and it slowly gets uncormfatable.

**Comment by mantas** [comment] 2023-01-17 12:31
@MrGeneration I was finally able to reproduce thanks to help from @Suhopoljac . Third time is a charm!

**Comment by dvuckovic** [comment] 2023-01-27 11:20
Reopening due to regression https://github.com/zammad/zammad/issues/4475

**Closed as completed** 2023-02-22 11:33 UTC
Labels: bug, verified, prioritised by payment
