### ISSUE TITLE
Forwarding: only email text but customer email address, date and time are missing.

### ISSUE THREAD

**Issue by ghitamati** [zammad/zammad#2815] opened 2019-11-19 17:06 UTC
### Infos:

* Used Zammad version: 3.x
* Installation method (source, package, ..): source
* Operating system: linux centos 7
* Database + version: ---
* Elasticsearch version: ---
* Browser + version: Chrome + Firefox 
* Ticket-ID: #1070545 

### Expected behavior:

When forwarding a message in addition to the text of the original e-mail address, it is also necessary to indicate the customer's e-mail address and the date of receipt of the e-mail

### Actual behavior:

When forwarding a message only the text appears in the forwarded email but not the cuatomer 
 email address and the date of the email.

### Steps to reproduce the behavior:

- Create an e-mail
- Send the email to Zammad in order to generate a ticket
- Forward the email in Zammad ticket view
--> In the body of the e-mail the customer email address and the date of original mail are missing

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-11-19 17:14
Please note that this is not a bug, but currently working as designed.
However, I'll keep it as enhancement.

Please refrain from posting feature requests to this repository and use the Community for this. :-)

**Comment by lpysj** [comment] 2020-01-28 08:50
This is something I came here for. We are currently also expecting that the customers e-mail address etc. is visible in the forwarded e-mail but it's not.

Would be a very nice feature to have.

**Comment by MrGeneration** [comment] 2020-06-22 11:20
Closing this issue in favor of https://github.com/zammad/zammad/issues/3091 as it has gotten a ton of discussion and specification over there.

To keep overview, I'll be closing this issue as duplicate, even though it has been first.
We'll update issue 3091 accordingly if anything moves!

**Closed as completed by MrGeneration** 2020-06-22 11:20 UTC
Labels: duplicate
