### ISSUE TITLE
SLES12 SP1: No post install is executed (contrib/packager.io/postinstall.sh)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#474] opened 2016-11-29 14:55 UTC
After installing zammad no post install is executed (contrib/packager.io/postinstall.sh).

```
linux-urt1:~ #  sudo zypper install zammad
Building repository 'nginx' cache ....................................................................................................................................[done]
Building repository 'zammad' cache ...................................................................................................................................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides postgresql93 needed by zammad-1.2.0-1480430025.7d771bd.sles12.x86_64
 Solution 1: do not install zammad-1.2.0-1480430025.7d771bd.sles12.x86_64
 Solution 2: break zammad-1.2.0-1480430025.7d771bd.sles12.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): 2
Resolving dependencies...
Resolving package dependencies...

The following 7 NEW packages are going to be installed:
  libmysqlclient18 libpq5 nginx postgresql-init postgresql94 postgresql94-server zammad

The following 2 packages are not supported by their vendor:
  nginx zammad

7 new packages to install.
Overall download size: 73.0 MiB. Already cached: 0 B. After the operation, additional 241.1 MiB will be used.
Continue? [y/n/? shows all options] (y): 
Retrieving package postgresql-init-9.4-17.8.1.noarch                                                                                   (1/7),  11.0 KiB (  7.5 KiB unpacked)
Retrieving package libmysqlclient18-10.0.21-1.17.x86_64                                                                                (2/7), 556.9 KiB (  3.3 MiB unpacked)
Retrieving package libpq5-9.4.5-4.1.x86_64                                                                                             (3/7), 157.6 KiB (464.6 KiB unpacked)
Retrieving package postgresql94-9.4.5-4.5.x86_64                                                                                       (4/7),   1.1 MiB (  4.2 MiB unpacked)
Retrieving package postgresql94-server-9.4.5-4.5.x86_64                                                                                (5/7),   3.4 MiB ( 16.6 MiB unpacked)
Retrieving package nginx-1.10.2-1.sles12.ngx.x86_64                                                                                    (6/7), 569.7 KiB (  2.1 MiB unpacked)
Retrieving: nginx-1.10.2-1.sles12.ngx.x86_64.rpm ........................................................................................................[done (69.9 KiB/s)]
Retrieving package zammad-1.2.0-1480430025.7d771bd.sles12.x86_64                                                                       (7/7),  67.2 MiB (214.4 MiB unpacked)
Retrieving: zammad-1.2.0-1480430025.7d771bd.sles12.x86_64.rpm ..........................................................................................[done (285.7 KiB/s)]
Checking for file conflicts: .........................................................................................................................................[done]
(1/7) Installing: postgresql-init-9.4-17.8.1 .........................................................................................................................[done]
Additional rpm output:
Updating /etc/sysconfig/postgresql...


(2/7) Installing: libmysqlclient18-10.0.21-1.17 ......................................................................................................................[done]
(3/7) Installing: libpq5-9.4.5-4.1 ...................................................................................................................................[done]
(4/7) Installing: postgresql94-9.4.5-4.5 .............................................................................................................................[done]
(5/7) Installing: postgresql94-server-9.4.5-4.5 ......................................................................................................................[done]
(6/7) Installing: nginx-1.10.2-1.sles12.ngx ..........................................................................................................................[done]
Additional rpm output:
warning: /var/cache/zypp/packages/nginx/x86_64/RPMS/nginx-1.10.2-1.sles12.ngx.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 7bd9bf62: NOKEY
----------------------------------------------------------------------

Thanks for using nginx!

Please find the official documentation for nginx here:
* http://nginx.org/en/docs/

Commercial subscriptions for nginx are available on:
* http://nginx.com/products/

----------------------------------------------------------------------


(7/7) Installing: zammad-1.2.0-1480430025.7d771bd.sles12 .............................................................................................................[done]
Additional rpm output:
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.


linux-urt1:~ # 
```

After executing "/opt/zammad/contrib/packager.io/postinstall.sh" manually it works fine.

I thing the post install is not executed because of "useradd: warning: the home directory already exists.  Not copying any file from skel directory into it.".

@monotek What do you think? packager.io issue?

**Comment by monotek** [comment] 2016-11-29 15:44
So you already had an zammad user before installing zammad rpm package?
If so, its imho ok to abort.

**Comment by monotek** [comment] 2016-12-07 16:39
Was not able to reproduce on SLES 12 SP2. 
Was maybe also related to "set -e" in postinstall.sh?
Closing.

**Closed by monotek** 2016-12-07 16:39 UTC
