### ISSUE TITLE
The chat box doesn't work when using a TCP port other than 80 and docker Zammad

### ISSUE THREAD

**Issue by egorky** [zammad/zammad#3025] opened 2020-04-17 18:43 UTC
### Infos:

* Used Zammad version:3.3.0-23 & 3.3.0-19
* Installation method (source, package, ..): Docker
* Operating system (of the host): centos 7.7.1908
* Database + version: The one that comes in the docker image: psql (PostgreSQL) 9.6.17
* Elasticsearch version: The one that comes in the docker image: 7.6.1
* Browser + version: Google Chrome Version 80.0.3987.163 & MS Edge Version 81.0.416.53 (Official build) (64-bit)

### Expected behavior:

A chat box sould appear whenever I copy the code to a website.

### Actual behavior:

This is a fresh install. No chat box appears when the zammad server is running in a port other than 80. In my case, given that I am using the offical docker images and the original port is in use, I changed to 8070. 
Zammad identifies correctly the address and the port and suggest to me the code I have to paste:
![image](https://user-images.githubusercontent.com/54412925/79600898-8a86a980-80ad-11ea-8987-cb41a369500d.png)

But, when I paste the script into the page of the site I'm hoping to serve, the script tries to pull the rest of the script through port 80, but that port is not the right one, it should be 8070.

![image](https://user-images.githubusercontent.com/54412925/79600645-1cda7d80-80ad-11ea-8dc3-6583947a51c2.png)

To try to solve it , I used the host option inside the script...
```
<script src="http://1xx.xxx.xxx.227:8070/assets/chat/chat.min.js"></script>
<script>
$(function() {
  new ZammadChat({
    background: '#0077d7',
    fontSize: '12px',
    chatId: 1,
    show: false,
    host: 'http://1xx.xxx.xxx.227:8070'
  });
});
```
... Zammad doesn't replace the http with ws.

![image](https://user-images.githubusercontent.com/54412925/79601337-4516ac00-80ae-11ea-9b71-f2f0bf1f6cd6.png)

### Steps to reproduce the behavior:
Install Zammad via docker:

```[root@mx ~]# git clone https://github.com/zammad/zammad-docker-compose.git
[root@mx ~]# sysctl -w vm.max_map_count=262144
[root@mx ~]# cd zammad-docker-compose/
```
We edit the enviroment file
```
[root@mx zammad-docker-compose]# vi .env
# don't forget to add the minus before the version
# example: VERSION=-2.9.0-1
IMAGE_REPO=zammad/zammad-docker-compose
VERSION=-3.3.0-23
RESTART=always
```
And change the port
```
[root@mx zammad-docker-compose]# vi  docker-compose.override.yml
version: '2'
services:

  zammad-nginx:
    ports:
      - "8070:80"
```
Finally, we start the containers:
```
[root@mx ~]# cd ..
[root@mx ~]# docker-compose up -d
[root@mx ~]# docker ps
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS                  NAMES
15a1b3d9d571        zammad/zammad-docker-compose:zammad-3.3.0-23                 "/docker-entrypoint.…"   49 minutes ago      Up 49 minutes       0.0.0.0:8070->80/tcp   zammad-docker-compose_zammad-nginx_1
ac7a02817449        zammad/zammad-docker-compose:zammad-3.3.0-23                 "/docker-entrypoint.…"   49 minutes ago      Up 49 minutes                              zammad-docker-compose_zammad-scheduler_1
fda5a4858f42        zammad/zammad-docker-compose:zammad-3.3.0-23                 "/docker-entrypoint.…"   49 minutes ago      Up 49 minutes                              zammad-docker-compose_zammad-websocket_1
eb6eeaefd471        zammad/zammad-docker-compose:zammad-postgresql-3.3.0-23      "/usr/local/bin/back…"   49 minutes ago      Up 49 minutes       5432/tcp               zammad-docker-compose_zammad-backup_1
bae53eaab72d        zammad/zammad-docker-compose:zammad-3.3.0-23                 "/docker-entrypoint.…"   49 minutes ago      Up 49 minutes                              zammad-docker-compose_zammad-railsserver_1
62d1d828e2d9        memcached:1.5.22-alpine                                      "docker-entrypoint.s…"   49 minutes ago      Up 49 minutes       11211/tcp              zammad-docker-compose_zammad-memcached_1
b6b91ab2e5f8        zammad/zammad-docker-compose:zammad-elasticsearch-3.3.0-23   "/usr/local/bin/dock…"   49 minutes ago      Up 49 minutes       9200/tcp, 9300/tcp     zammad-docker-compose_zammad-elasticsearch_1
3d6c7e85cd32        zammad/zammad-docker-compose:zammad-postgresql-3.3.0-23      "docker-entrypoint.s…"   49 minutes ago      Up 49 minutes       5432/tcp               zammad-docker-compose_zammad-postgresql_1
```
We access the web site and create the admin user and access the application. Everything will work fine, except the chat. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-04-17 18:54
Sorry but this sounds like a rather technical question.
Please consult the community forum for technical questions - this repository is the wrong place. https://community.zammad.org


The reason for your issues already lives within your developer console.

"URL's scheme must either be ws or wss. http is not allowed"

Closing.

**Closed as completed by MrGeneration** 2020-04-17 18:54 UTC
Labels: question

**Comment by egorky** [comment] 2020-04-17 20:06
> Sorry but this sounds like a rather technical question.
> Please consult the community forum for technical questions - this repository is the wrong place. https://community.zammad.org
> 
> The reason for your issues already lives within your developer console.
> 
> "URL's scheme must either be ws or wss. http is not allowed"
> 
> Closing.

Thanks for the fast reply, @MrGeneration . So this should be an error in the documentation instead, the documentation clearly states that I don't have to use that "host" option if the URL is declared through the script tag in the HTML :
![image](https://user-images.githubusercontent.com/54412925/79607484-e1de4700-80b8-11ea-993e-975cab0f0f35.png)

In my case I do declare the URL in the HTML code:
```
<script src="http://1xx.xxx.xxx.227:8070/assets/chat/chat.min.js"></script>
```
But the auto-detect function doesn't understand the concept of ports because it tries to use the 80.

On the other hand, the same documentation doesn't make clear the format of the URL. When I use the format you suggested
```
<script>
$(function() {
  new ZammadChat({
    background: '#0066d7',
    fontSize: '12px',
    chatId: 1,
    show: true,
    host: 'ws://1xx.xxx.xxx.227:8070'
  });
});
</script>
```
I still get an error

![image](https://user-images.githubusercontent.com/54412925/79607959-c889ca80-80b9-11ea-83ab-d61c04546217.png)

Are you sure this is a technical question?

**Comment by MrGeneration** [comment] 2020-04-17 21:32
Yes I am sure that this is a technical question you could solve as this is not a bug.

**Comment by egorky** [comment] 2020-04-18 00:45
> Yes I am sure that this is a technical question you could solve as this is not a bug.

ok, thanks a lot!
