### ISSUE TITLE
OTRS Import fails

### ISSUE THREAD

**Issue by MrDigit** [zammad/zammad#368] opened 2016-11-06 19:00 UTC
Hello,

I've installed zammad with a MySQL database, Znuny ZammadMigrator, started zammad and selected OTRS migration from a OTRS 5.0.13 instance.
Unfortunately the migration process does not complete. I've tried that multiple times, it randomly stucks at different times when importing.

Migration screen says:
25/25 Base Objects
5/1475 Users
214/5066 Tickets

I've checked production.log of that time when it starts going crazy, but could not find any errors. I've attached a snippet of the log.

Any ideas why the process doesn't finish ?

Best regards
  MrDigit

**Comment by MrDigit** [comment] 2016-11-06 19:27
Sorry, my fault. Obviously the machine hat too little memory and OOM killer stopped importing the tickets.

Issue can be closed :)

**Comment by martini** [comment] 2016-11-06 19:27
@MrDigit Thanks for feedback! Feedback about the import would be nice too!

**Comment by MrDigit** [comment] 2016-11-06 20:38
Hello,

of course, here some feedback:

- Import quite memory consuming :)
- After Import login with former OTRS login not working, after "Forgot Password" created new password and login was successful
- On OTRS ~40 tickets were open, some thousand were "closed successful". In Zammad ALL tickets were shown as open until I corrected the "status" filter in the settings

The following topic is a problem I could not solve:

- It seems that the customer information is lost in all tickets. After import all tickets have "OTRS admin" (the admin user of the imported OTRS system) as customer and not to the creator of the ticket. In OTRS every ticket had the E-Mail sender as customer.

Best regards
  MrDigit

**Comment by thorsteneckel** [comment] 2016-11-07 10:12
HI @MrDigit - thanks for the feedback! I have the import topic on my list for this week and will take a look at it.

**Comment by thorsteneckel** [comment] 2016-11-11 16:25
Hi @MrDigit - sadly we had a more urgent bug crashing the application which was a higher priority. I didn't manage to go into more detail on this one here. I'll have a look next week. One question: On which system is the import memory consuming? OTRS or Zammad? Or both 😱 
May it be possible get remove access (via Teamviewer or so) to your system to take a look to increase the speed on getting into this?

**Comment by octomike** [comment] 2016-11-15 20:40
I just tested this a little with Version `1.1.0-1479124849.8be9ce5.xenial`, importing from OTRS 5.0.13.

Things I noticed:

+ GUI Import won't accept the import link
+ Rails console import did things, but **failed** to set `system_init_done` Setting to `true`
+ login with imported credentials did not work, I had to set the password with the rails shell
+ even then, sometimes, I got "Object already exists" errors after login
+ tickets (lot's of them) show up in the "Open" Tab, although their state is "closed (un)succesful"

**Comment by MrDigit** [comment] 2016-11-15 22:40
Hi,
the import consumed >1 GB on the OTRS side and >2 GB RAM on the zammad side.

But, as I've written, the bigger problem is that the customer users were not imported, only the agent users. And now all tickets appear to be from the admin OTRS user.

@octomike I think it should be possible to have a remote session . It is also possible, if you have that, to run a debug version or similiar..

**Comment by thorsteneckel** [comment] 2016-11-16 09:46
Hi @octomike - do I get you right that you got the import link after installing the OTRS import package and pasted it to the Zammad migration wizard (GUI) which showed that it's not valid? That should not happen! 
Could you please also tell me how you started the import from the rails console so I can go and reproduce it?

@MrDigit - thanks for the feedback! We'll take a look about the memory footprint of the import. It depends on the data transfered how much memory is used since we cache some objects for later usage. I'll have a look how we can reduce this.
Concerning the not imported users: I'm on it! I found the lines and I'm working on a fix right now.

After that I'll take a look at the closed tickets in the "open" tab and let you know.

About the login issue you both described: It's not possible for us to import the passwords out of OTRS. Which is good because otherwise they won't be secure. Therefore each user has to reset the password on first login via email. After that the Zammad password is created and bot OTRS and Zammad passwords are safe.

**Comment by octomike** [comment] 2016-11-16 10:12
> Hi @octomike - do I get you right that you got the import link after installing the OTRS import package > and pasted it to the Zammad migration wizard (GUI) which showed that it's not valid? That should not > happen!

Yes, I pasted the URL produced by the OTRS package to the the zammad input field and expected a "Next" button to magically appear, which didn't happen. That was after I ran a manual import in the rails console.

> Could you please also tell me how you started the import from the rails console so I can go and reproduce it?

Sure:

As root in bash:
```
systemctl stop zammad.service
```

As zammad in bash:
```
cd /opt/zammad/
export GEM_HOME=$PWD/vendor/bundle/ruby/2.3.0
RAILS_ENV=production ./bin/rails c
```

In the rails console (as stated in the [doc](https://zammad.org/documentation/migration/otrs))
```
Setting.set('import_otrs_endpoint', 'http://xxx/otrs/public.pl?Action=ZammadMigrator')
Setting.set('import_otrs_endpoint_key', 'xxx')
Setting.set('import_mode', true)
Import::OTRS.start
# wait ~10min
Setting.set('import_mode', false)
exit
```

As root in bash:
```
systemctl start zammad.service
```

**Comment by octomike** [comment] 2016-11-16 10:16
@thorsteneckel 
> About the login issue you both described: It's not possible for us to import the passwords out of OTRS. Which is good because otherwise they won't be secure. Therefore each user has to reset the password on first login via email. After that the Zammad password is created and bot OTRS and Zammad passwords are safe.

Well technically you could have just imported the hashes, no?

But I understand that you may want to save the passwords with a new hash/salt. A note in the documentation, or even better at the login prompt after an unsuccessful authentication attempt of an imported user, would be useful.

**Comment by thorsteneckel** [comment] 2016-11-17 16:42
Hi there - I just want to give you an update. We are currently refactoring the OTRS import backend which takes some time. There are 1700 lines of code changed which should improve the testing capabilities and therefore the speed of providing fixes a lot. Stay tuned! :shipit:

**Comment by octomike** [comment] 2016-11-17 17:16
Cool, thank you for the update! :+1:

**Comment by svengit** [comment] 2016-11-25 17:45
Hey, 
I am not sure if this is the right place, but since it seems that you are working on this and will check back here, I'll shot anyways:

- GUI Import won't accept the import link
- import fails on tickets with empty title. On our installation there was exactly one of those dating back to 2007 which had the id 1 and was 'Welcome to OTRS'. Had to delete that from OTRS and restart the 60 Min import
- Rails console is spammed by 
`Setting.get('import_mode') # from cache`
, which I got rid of by doing 
`ActiveRecord::Base.logger.level = 1`
before starting the import
- import also imports stuff like the host name, which makes no sense at all
- almost all tickets belong to "nicole.braun@zammad.org "
- login does not work, but I get messages about failed LDAP Auth in the console
- I now have 18k open tickets, which makes the interface freeze when displaying...
- some other minor issues

**Comment by thorsteneckel** [comment] 2016-11-30 15:06
Hi there!

We are through some big changes at least ` 133 changed files with 5,611 additions and 1,562 deletions.` The main objective was making the backend more testable which we achieved with more than 140 additional tests!

Additionally we managed to fixed some of the reported issues:

- [X] Lost customer information in tickets (@MrDigit, @svengit)
- [X] Passwords are not imported (@MrDigit, @octomike, @svengit)
- [X] Import fails on tickets with empty title (@svengit)
- [X] FQDN should not get imported (@svengit)
- [X] Rails console is spammed by `Setting.get('import_mode') # from cache*` (@svengit)
- [ ] GUI Import won't accept the import link (@octomike, @svengit)
- [ ] Closed tickets are imported as "Open" (@MrDigit, @octomike, @svengit)
- [ ] Memory consuming (OTRS >1 GB - Zammad >2 GB) (@MrDigit)

@octomike:
> Rails console import did things, but failed to set system_init_done Setting to true

Thanks! I've updated the doc: https://github.com/zammad/zammad-documentation/commit/7f6e5e58665a7cb3b831d70b9044b7aee6b043f9

> But I understand that you may want to save the passwords with a new hash/salt. A note in the documentation, or even better at the login prompt after an unsuccessful authentication attempt of an imported user, would be useful.

This should be possible with the next release of Zammad if your are importing from OTRS >= 3.3 and don't have changed the password encryption type to non SHA2.

@svengit

> login does not work, but I get messages about failed LDAP Auth in the console

Yeah that is not in the scope of the OTRS import but a general issue with the LDAP auth backend which is currently in active development. If we are done with it the message will disappear. We are on it 🤓 

@MrDigit, @octomike, @svengit
Regarding the issues with closed tickets as open and the GUI not accepting the import link:

It would be great to get these links and the `log/production.log` file from your system. Even better would be a remote session where I can take a look at it. Would be much appreciated! Feel free to leave ma a mail with the information to `support@zammad.com`.

The memory consumption needs more research. Currently I'm not sure if we can and should reduce the load.

Feedback is welcome. Thanks!

**Comment by svengit** [comment] 2016-12-01 10:44
Hey Thorsten,
just to clarify: The migrator migrates the login mechanism (LDAP-Auth), but the later does not work yet, so the user gets logged out, right? 

Regarding the import link: for some odd reason it gets accepted now. I changed nothing, just dropped the db, did 
`rake db:create && rake db:migrate && rake db:seed`
and this time it worked. I am confused.

Thanks for your effords

**Comment by thorsteneckel** [comment] 2016-12-01 13:13
Hi Sven,

thanks for your feedback! No worries - if the link issue occurs again just let me know. Preferably via a mail to support@zammad.com 👍 

Regarding the LDAP: Yes. Since the LDAP authentication is under active development and not completed yet we _currently_ can't use it to authenticate users via LDAP. Currently the information gets transferred from LDAP -> OTRS -> Zammad -> DB.

JFI: OTRS syncs the basic customer user information from the LDAP to OTRS in order to keep ID relations safe etc.
The OTRS Zammad import imports only customers which have at least one associated Ticket. We do this because there is no list function for customer users in OTRS. This is because of the possibility of different customer user backends which might not provide a list function like e.g. a webservice or LDAP in the OTRS standard.

**Comment by thorsteneckel** [comment] 2016-12-07 08:36
Hi there,

regarding these three issues:

- [ ] GUI Import won't accept the import link (@octomike, @svengit)
- [ ] Closed tickets are imported as "Open" (@MrDigit, @octomike, @svengit)
- [ ] Memory consuming (OTRS >1 GB - Zammad >2 GB) (@MrDigit)

I wasn't able to reproduce any 😞  could you please provide me with some information how to reproduce it? Would a remote session be possible? Feel free to drop me a mail at support@zammad.com

@octomike 
`even then, sometimes, I got "Object already exists" errors after login` should be fixed with:
https://github.com/zammad/zammad/commit/27457f5c3900784756eabcc9b591cac358367a4e

**Comment by thorsteneckel** [comment] 2016-12-19 10:31
Since there are any responses yet I'll close this issue. Feel free to open new ones if necessary. 💯

**Closed by thorsteneckel** 2016-12-19 10:31 UTC
Labels: bug, import
