### ISSUE TITLE
External Data Sources Not Loading when Creating New Ticket - Works After Ticket Created & in Preview

### ISSUE THREAD

**Issue by kylebial0** [zammad/zammad#5296] opened 2024-08-09 16:30 UTC
### Used Zammad Version

6.3.1-1722001598.ce363b96.jammy

### Environment

- Installation method: Community
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 22.04
- Database + version:  Postgresql 14.12
- Elasticsearch version: 7.17.22
- Browser + version: Edge 127.0.2651.86

### Actual behaviour

When I create an external data object, it works properly in the object manager preview and on already created tickets. 

However, if I am filling in a ticket, the external data object does not appear to search. 
![image](https://github.com/user-attachments/assets/5fbd35f5-e98a-4a8b-b8af-df18b4a0b5e4)
_Example search in object preview_

![image](https://github.com/user-attachments/assets/f47827db-b69b-4f48-b6e7-fc3134123fa3)
_DevTools Network Error_

![image](https://github.com/user-attachments/assets/1a84caf8-d605-4a36-a9ae-75d57235565d)
_DevTools Console Error_

![image](https://github.com/user-attachments/assets/55b47678-4b6e-4df4-89b1-715a9ef4bcc0)
_Once the ticket is generated, the external data object works as expected_

`I, [2024-08-09T15:46:29.311053#1368356-3984000]  INFO -- : Completed 422 Unprocessable Entity in 92ms (Views: 0.1ms | ActiveRecord: 6.4ms | Allocations: 9985)
I, [2024-08-09T15:46:29.379448#1368356-3698120]  INFO -- : Started GET "/api/v1/external_data_source/Ticket/test_unit_type?query=%20%20%20%20%20%20%20&limit=40&search_context%5Bcustomer_id%5D=4&_=1723217758376" for 199.10.6.18 at 2024-08-09 15:46:29 +0000
I, [2024-08-09T15:46:29.383992#1368356-3698120]  INFO -- : Processing by ExternalDataSourceController#fetch as JSON
I, [2024-08-09T15:46:29.384048#1368356-3698120]  INFO -- :   Parameters: {"query"=>"       ", "limit"=>"40", "search_context"=>{"customer_id"=>"4"}, "_"=>"1723217758376", "object"=>"Ticket", "attribute"=>"test_unit_type"}
E, [2024-08-09T15:46:29.439197#1368356-3698120] ERROR -- : Cannot process external data source Ticket.test_unit_type. See HTTPLog for details. (Exceptions::UnprocessableEntity)
app/services/service/external_data_source/search.rb:9:in `rescue in execute'
app/services/service/external_data_source/search.rb:4:in `execute'
app/controllers/external_data_source_controller.rb:7:in `fetch'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'`
_Production log_

### Expected behaviour

When a new ticket is being created, the external data object API call should work as expected

### Steps to reproduce the behaviour

1. Create External Data Object field for ticket
2. Star to create a new ticket
3. Enter is field data that will be used for the external data object
4. "prompt" the external data object field to do the api call - no API call made and errors received in console and network

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2024-08-14 09:25
Hi @kylebial0. Sorry, I cannot reproduce the issue you've mentioned. Please see the attached GIF.

![2024-08-14 11 23 19](https://github.com/user-attachments/assets/d3c735cf-3121-4b85-8e90-9da498fa8ba8)

Could you please add more information here, maybe posting the complete configuration of the field you've used?

**Comment by fliebe92** [comment] 2024-08-26 06:48
No feedback, closing for now.

**Closed as not planned by fliebe92** 2024-08-26 06:48 UTC
Labels: waiting for feedback, needs verification
