### ISSUE TITLE
Expand sipgate.io integration call log display from 60 to 300 call entrys

### ISSUE THREAD

**Issue by Vogelkoje** [zammad/zammad#3051] opened 2020-05-13 13:46 UTC
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1075464 (1078096)

### Desired behavior:

* Have over 300 incoming and outgoing calls
* You will see the last 300 incoming and outgoing calls

### Actual behavior:

* The sipgate.io integration listed only the last 60 entrys, in the Zammad call log

### Steps to reproduce the behavior:

* Set up the sipgate.io integration
* Have over 60 incoming and outgoing calls
* You will see the last 60 incoming and outgoing calls

### Usecase:

* Users need this to be able to call customers back over a longer period of time.

**Comment by MrGeneration** [comment] 2020-07-27 13:17
Some follow up on this topic:
When we discussed this internal it showed that this is not as trivial as it seems.

While the customer affected mostly has this issue during break times, a time based limit wouldn't solve this entirely (e.g. for weekends). A bare raise of the number of call assets may have negative effects in terms of performance. Other users with low call traffic may want to keep the number of assets low. Having a caller log for like the last 2 months wouldn't be helpful.

We'll update this issue accordingly if anything moves.

**Comment by MrGeneration** [comment] 2021-06-17 12:28
This indirectly has gotten a duplicate of #3550 which did introduce a setting that allows to use up to 300 call entries.

**Closed as completed by MrGeneration** 2021-06-17 12:28 UTC
Labels: duplicate
