### ISSUE TITLE
Wrong (non-numerical) sorting of ticket numbers in "#" column in overviews

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1182] opened 2017-06-09 19:56 UTC
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: DEB
* Operating system: LInux (Debian 8)
* Browser + version: not relevant

### Expected behavior:

When clicking on the "#" header in ticket overviews, the issues are sorted numerically

### Actual behavior:

When clicking on the "#" header in ticket overviews, the issues are sorted in string order

![zammad_ticketsort](https://user-images.githubusercontent.com/279232/26992312-61302fdc-4d5e-11e7-9203-c0f8effdd7bb.png)

**Comment by togiberlin** [comment] 2017-10-10 00:50
- [x] Verified on Zammad version 1.5-stable:
<img width="446" alt="v1_5" src="https://user-images.githubusercontent.com/13764830/31364244-ce6d98c2-ad63-11e7-91ae-d30487762e97.png">
- [x] Also verified on Zammad version 2.0-stable:
<img width="296" alt="v2_0" src="https://user-images.githubusercontent.com/13764830/31364245-ce7568fe-ad63-11e7-8505-e79ce145c180.png">

**Comment by togiberlin** [comment] 2017-10-10 10:14
## Explanation
This is not a bug.
The field 'Title' is of type string. The expected use is to insert sentences and words into the field 'Title'. Not numbers. If you sort an array of type String, this is completely normal and the expected behavior. Let's see this example in Python:
<img width="750" alt="screen shot 2017-10-10 at 11 56 44" src="https://user-images.githubusercontent.com/13764830/31381151-0372c934-adb4-11e7-82dc-8cb50b6a81b4.png">

And this example in Java:
<img width="1028" alt="screen shot 2017-10-10 at 12 07 56" src="https://user-images.githubusercontent.com/13764830/31381154-0a2cbd7a-adb4-11e7-9179-e565726a836e.png">

Sorting an array of type string and array of type integer are two different things, which can't be mixed.

You could implement something like natural sort, but it would be slow - it's not really worth it.
[Stackoverflow: Natural Sort](https://stackoverflow.com/questions/15478954/sort-array-elements-string-with-numbers-natural-sort)

## Recommendation
@martini This is not a bug, but correct behavior. I recommend to close this ticket.

**Comment by fthommen** [comment] 2017-10-10 17:47
@togiberlin added misleading screenshots.  Please refer **to my screenshots in the original post** which refer to the "#" column - which contains the ticket IDs (=numbers) - and not the "Title" column.

**Comment by togiberlin** [comment] 2017-10-10 18:16
It seems that the Zammad app treats all columns as string, regardless of content.

Inside ```app/assets/javascripts/app/controllers/_application_controller_table.coffee:420```, I would probably solve it by:

- Add an if-condition for the ```#``` column
- Then by converting all elements of the array from string to integer before sorting. In JS, you would usually use something like the ```parseInt();``` method. The Underscore.js method ```_.sortBy();``` should sort now correctly.

**Comment by hmasila** [comment] 2017-10-26 17:32
@fthommen If you still need help with this I will be happy to help

**Comment by fthommen** [comment] 2017-10-26 17:41
@hmasila: Thanks for your offer, but I just need it to be fixed in zammad :-)

**Comment by hmasila** [comment] 2017-10-26 17:46
Noted @fthommen

**Comment by SummerStorm** [comment] 2018-08-22 07:52
Hi there, thanks for the bug report. While the current behavior is not ideal, we cannot parse the ticket number as an integer because the ticket number is not always numeric (Zammad handles non-numeric tickets numbers e.g. from imported sources or own created ticket number generators).

This issue is closed.

**Closed by SummerStorm** 2018-08-22 07:52 UTC
Labels: bug, frontend, overviews, verified

**Comment by fthommen** [comment] 2018-08-22 11:23
I don't agree.  It's just a bug and it makes this sorting completely useless. Zammad knows of what type the counter is (it is configurable) and should sort according to the selected type.  I don't know about imported sources (don't know how this works) but in the case of own created ticket number generators, the implementer would have to provide an appropriate sort routine.  The fallback could still be text-sorting but whenever the the counter type is defined I can't see any reason, why there should not be a correct sorting.  Please reopen this as a bug.

**Comment by martini** [comment] 2018-08-22 11:51
@fthommen thanks for feedback. I'm a technician so I guess my opinion is a little bit focused on data structure (because the database field ist text so the sorting is SQL and elasticsearch is also text).

Question: So you expect that the ticket number is a integer value per default (not text)?

Just a notice: Per default the ticket number has a length of 5 spaces. So you will have additional spaces very infrequently (only from xx999 to xx1000 or from xx9999 to xx10000). Of cause you can change the default min. length via admin interface.

Thanks for feedback!

**Comment by fthommen** [comment] 2018-08-26 16:53
well, I don't have an expectation about the _default_ data type, but when I configure the ticket ID to be a number - which I can do - then I expect Zammad to sort accordingly.  The same applies when I configure the ticket ID to be a date.  If the format is unknown or text, then sorting in text order is ok ("fallback").

Not using those feature I can't comment on imported source and custom ticket number generators.  But I assume that there is also a way to define the type of the ticket ID field or to provide a custom sort function through some hook?  If not -> fallback (text)

Regarding the length of the number: Does that matter?  Our IDs started at 421 and in the meantime reached 422496.  It's still a number ;-) (or did I miss the point?)

**Comment by robertlemke** [comment] 2020-09-29 08:33
For the records, I just stumbled over this behavior in Zammad 3.4.x and was about to file a bug report until I discovered that there was one already. I don't think that this is critical, but it is, at least, confusing.

<img width="151" alt="image" src="https://user-images.githubusercontent.com/95582/94533127-12690600-023f-11eb-8373-09875aa188d5.png">

**Comment by fthommen** [comment] 2020-09-29 08:44
Right, but the development team sees this as a feature, not a bug...

**Comment by MrGeneration** [comment] 2020-09-29 09:06
@fthommen & @robertlemke I think the same way you do. This is unexpected.
This may feel a bit edgy because this kind of big number jump mostly won't appear visible in most situations.

Anyway, I think the overview should sort as a human would expect it, not like the machine does.
Please feel free create a new bug report for this, because this one was solved, even though I'm not sure if it really was or closed by accident.

Paying customers please drop me a mail to support [at] zammad [dot] com so I can note the ticket numbers and adjust the tag for later notificationZ. :)

**Comment by robertlemke** [comment] 2020-09-29 09:21
> Paying customers please drop me a mail to support [at] zammad [dot] com so I can note the ticket numbers and adjust the tag for later notificationZ. :)

:) This was in no way meant to be demanding – I'm just used to report ideas and findings, so I thought I'd contribute my 2 cents here …

**Comment by MrGeneration** [comment] 2020-09-29 09:25
@robertlemke worry not, did not feeling that way. I do agree with you.
