### ISSUE TITLE
Objects can't be made invisble anymore

### ISSUE THREAD

**Issue by moellert** [zammad/zammad#1886] opened 2018-03-21 12:14 UTC
### Infos:

* Used Zammad version: 2.3.0-1519728122.5aa751ef.centos7
* Installation method (source, package, ..): package
* Operating system: CentOS7
* Database + version: Postges 9.2.23-3.el7_4
* Elasticsearch version: 5.6.6-1
* Browser + version: latest versions of Firefox and Chromium on Ubuntu 16.04

### Expected behavior:

* I can uncheck every checkbox of an object and it will be invisible in the UI.

### Actual behavior:

* When I uncheck all checkboxes and save the object one checkbox gets checked again and the object is visible when I look at a ticket/user/organisation/group.

### Steps to reproduce the behavior:

- Create a new object
- Uncheck every checkbox and save
- See if the object gets invisble

I think there was a similar issue with the checkboxes for the rights an agent has.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-03-21 12:57
This is a duplicate of #1488 and is fixed in Zammad 2.4 🚀

**Closed by thorsteneckel** 2018-03-21 12:57 UTC
