### ISSUE TITLE
OTRS import breaks a lot of assumptions in Zammad

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#689] opened 2017-01-30 21:27 UTC
Hi,

first of all, thank you for building Zammad. Coming from OTRS, the user interface is a total relief, even if there are some features still missing. 

We started using Zammad by importing a lot of data from OTRS using the provided importer. This broke **a lot** of things in Zammad and I want to share some of them.

* OTRS priorities got imported 1:1 into Zammad, but are different from Zammad's defaults. Therefore, no tickets could be created via email because [email_parser.rb:509](https://github.com/zammad/zammad/blob/e42042cc1c650244dc864dc04ef089d70a7665b7/app/models/channel/email_parser.rb#L509) only works with Zammad's defaults: ``Ticket::Priority.find_by(name: '2 normal').id``

* The OTRS root user gets imported 1:1 into Zammad with the default login name ``root@localhost``. However, Zammad in [ticket.rb:323](https://github.com/zammad/zammad/blob/develop/app/models/ticket.rb#L323) looks for ``User.find_by(login: '-').id`` which does not exist. Thus, merging tickets did not work.

* OTRS custom states got imported 1:1 into Zammad, but the Zammad interface only allowed to select *some* of them in the interface and the state types ("pending", "closed", ...) got mixed up in the UI. I did not debug this.

I'm sure there is more of them but those are the one I ran into and I remember. I could fix all of them by converting the data directly in the database, but the experience moving from OTRS to Zammad was not really smooth this way.

Thanks,
Raphael

**Comment by thorsteneckel** [comment] 2017-01-31 08:05
HI @raphaelm - thanks for the comprehensive feedback. I'll look into it and let your know. If there are any other thinks that won't work out for you just let me know.

**Comment by martini** [comment] 2017-01-31 08:07
@raphaelm Thanks for feedback!
@thorsteneckel let's discuss this, I have prepared something.

**Comment by thorsteneckel** [comment] 2017-02-13 09:03
Hi @raphaelm - sorry for the delay! Can you please tell me which Zammad Version you have used? I have troubles reproducing your third point in the latest Zammad version since there is a mapping in place here:

https://github.com/zammad/zammad/blob/e8e332e2e3f42fe4f6600c00fbb93b2bf1cfc321/lib/import/otrs/state.rb#L54

Would be great to get this solid into the upcoming release tomorrow.

**Comment by raphaelm** [comment] 2017-02-13 09:47
My import was done using the debian package ``zammad:amd64 (1.2.0-1484665143.8dde0f2.jessie)``.

IIRC, the types looked correct in the database, but the interface was still buggy. I wasn't able to fix it any other way than by changing the states to Zammad's defaults and adjust all tickets to that manually via SQL.

I *suspect* that the import is correct, but the state IDs are hardcoded elsewere in the code?

**Comment by thorsteneckel** [comment] 2017-02-14 10:58
Hi @raphaelm - thanks for the hint. We found the cause for this. So all of the three issues are fixed now with the commits above. Thanks for reporting it. Would be great to get some feedback.

**Closed by thorsteneckel** 2017-02-14 10:58 UTC
Labels: bug, import

**Comment by raphaelm** [comment] 2017-02-14 11:14
> Would be great to get some feedback.

Will be hard, I'm not going to import again ;)
