### ISSUE TITLE
Missing translation of "Enter note or"

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2958] opened 2020-03-06 11:02 UTC
### Infos:

* Used Zammad version: 3.3 
* hosted
* Browser + version: chrome (80.0.3987.122)
* T#1070183, T#1069989

### Expected behavior:

* The text inside the note-field of an existing ticket ("Enter note or") should be translated in my preferred language, that I set up in my user-profile.

### Actual behavior:

* "Enter note or" is always displayed in English, regardless of the language selected in the profile. E.G. in german:
![image](https://user-images.githubusercontent.com/22768032/76077175-82145c80-5fa0-11ea-9870-4b370c967e0d.png)
* I can't translate this string within the admin-interface

### Steps to reproduce the behavior:

* select any other language than english in your user-settings via profile --> language
* have a look into the note-field of an existing ticket

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-10-07 08:54
I'm sorry, but I can no longer reproduce this.
It seems like this was magically self healed or solved by another issue.

Verified on Zammad 3.5

![image](https://user-images.githubusercontent.com/6549061/95309473-79b03700-088b-11eb-8712-cc417a7cae5d.png)

**Comment by MrGeneration** [comment] 2020-10-07 09:00
This is / was a duplicate of issue #2860 and seemed to indirectly got fixed by a1f2346a24c745ac53ff188fe5e26f16ddfd9483

If not, above issue just was a missing translation within the system that "magically" appeared without any further hints and traces.

**Closed as completed by MrGeneration** 2020-10-07 09:00 UTC
Labels: bug, UX/UI, verified, prioritised by payment, localization
