### ISSUE TITLE
Text Module Overview not loading

### ISSUE THREAD

**Issue by ahantschel** [zammad/zammad#1650] opened 2017-11-15 19:10 UTC
### Infos:

* Used Zammad version: 2.1 (zammad-2.1.0-1510748077.44070687.centos7.x86_64)
* Used Zammad installation source: (source, package, ...) YUM Repo
* Operating system: CentOS 7
* Browser + version: Firefox, Chrome, newest Versions
* Database: PostgreSQL 10.1 on remote host

### Expected behavior:

* Load the Text Modules Overview in Admin Area, existing Modules should be displayed.

### Actual behavior:

* No Text Modules are Displayed in the Settings. New Module can be created and are displayed until reloading the Page. Logs showing 401.
[zammad_text_modules.txt](https://github.com/zammad/zammad/files/1476009/zammad_text_modules.txt)

**Comment by hanneshal** [comment] 2017-11-15 19:58
```
I, [2017-11-15T19:59:48.869169 #8192]  INFO -- : Started POST "/api/v1/text_modules" for 127.0.0.1 at 2017-11-15 19:59:48 +0100
I, [2017-11-15T19:59:48.878170 #8192]  INFO -- : Processing by TextModulesController#create as JSON
I, [2017-11-15T19:59:48.878232 #8192]  INFO -- :   Parameters: {"name"=>"test3", "keywords"=>"", "content"=>"test", "active"=>true, "id"=>"c-0"}
I, [2017-11-15T19:59:48.897799 #8192]  INFO -- : Completed 201 Created in 19ms (Views: 0.3ms | ActiveRecord: 7.1ms)
I, [2017-11-15T19:59:49.240741 #8192]  INFO -- : Started GET "/api/v1/text_modules/?full=true&_=1510739687927" for 127.0.0.1 at 2017-11-15 19:59:49 +0100
I, [2017-11-15T19:59:49.248632 #8192]  INFO -- : Processing by TextModulesController#index as JSON
I, [2017-11-15T19:59:49.248793 #8192]  INFO -- :   Parameters: {"full"=>"true", "_"=>"1510739687927"}
I, [2017-11-15T19:59:49.319651 #8192]  INFO -- : Started GET "/api/v1/text_modules/?full=true&_=1510771932240" for 127.0.0.1 at 2017-11-15 19:59:49 +0100
I, [2017-11-15T19:59:49.325573 #8192]  INFO -- : Processing by TextModulesController#index as JSON
I, [2017-11-15T19:59:49.325636 #8192]  INFO -- :   Parameters: {"full"=>"true", "_"=>"1510771932240"}
I, [2017-11-15T19:59:49.334907 #8192]  INFO -- : Completed 401 Unauthorized in 9ms (Views: 0.1ms | ActiveRecord: 3.1ms)
I, [2017-11-15T19:59:49.387561 #8192]  INFO -- : Completed 200 OK in 139ms (Views: 41.1ms | ActiveRecord: 3.8ms)
I, [2017-11-15T19:59:49.912385 #8189]  INFO -- : Scheduler running...

```

**Comment by hanneshal** [comment] 2017-11-15 19:59
Could you please check your role permissions. There is a separate point for text modules. 

Regards

**Comment by ahantschel** [comment] 2017-11-15 20:12
Ich checked it with our admin role.
Today, I did a yum update to the package noted above, I'm not 100% sure but i think it was working  before...

**Comment by ahantschel** [comment] 2017-11-15 20:26
![screenshot_20171115-212246](https://user-images.githubusercontent.com/4534911/32858301-5ef04256-ca4b-11e7-947d-45060ab11ead.jpg)

When creating a new Module it is displayed until reload

**Comment by hanneshal** [comment] 2017-11-15 22:36
Strange. 401 means: you are not allowed. Please double check your permissions. No matter what user you are using. 

I can't reproduce this in any browser I have access to. Either on dev or master (2.1/2.2)
Chrome & Safari on Mac and even Edge works fine.

Can you give us a screenshot of your browser DEV Console. 
- Please clear it
- create the new textmodule
- refresh

Please provide the console and the network output.

**Comment by ahantschel** [comment] 2017-11-16 11:12
I just tested it with a normal (agent) user and just gave him the privilege admin---> text_module and it works. 
But I still get displayed nothing with the "normal" admin user, which should have access to everything in the settings (checkbox admin - admin interface selected).

**Comment by thorsteneckel** [comment] 2018-03-01 10:26
Hi @ahantschel - Sorry for the delay. We are still not able to reproduce this. Could you please update to the latest version of Zammad and try if it might got fixed in the meantime. If not please create an instance over at https://zammad.com and post the URL here so we can reproduce it. Thanks!

**Closed by thorsteneckel** 2018-03-01 10:26 UTC
Labels: waiting for feedback
