### ISSUE TITLE
Unable to translate

### ISSUE THREAD

**Issue by madd86** [zammad/zammad#710] opened 2017-02-01 16:07 UTC
My language is 48% translated. I'm trying to add the untranslated bits in.

I go to Settings->System->Translation and then enter the missing translated fields and click "Create"

However, it disappears and I don't know whether it created or not. I tried to push translation it says thanks and nothing happens.

The text remains untranslated. Is there a file I can just edit and get it done with it?

zammad/config/translations tried editing the yml files but it didn't change on the site.

**Comment by madd86** [comment] 2017-02-01 19:28
Been trying to translate directly from the database (table translations) what a pain! Sometimes it works sometimes it doesn't.

I don't understand what makes it refresh the values after I translated there.

**Comment by petervanbeugen** [comment] 2017-02-01 21:47
see: Can't update translations via translation table #659

**Comment by martini** [comment] 2017-02-01 22:29
Hi @madd86 

thanks for your bug report. It's a duplicate of #659 which is fixed now.

You should be able to translate via Settings->System->Translation. After adding some translated words you can use it right now on your local installation. Also after adding some words the blue button on the right top appears where you can submit your changes (thanks for that). 

 -Martin

**Comment by martini** [comment] 2017-02-01 22:58
PS: On every bugfix a new RPM package is build. So you can update your RPM installation. Feedback would be great!

**Closed by martini** 2017-02-01 22:58 UTC
Labels: duplicate
