### ISSUE TITLE
Tag filter in trigger is beeing ignored

### ISSUE THREAD

**Issue by alex-LE** [zammad/zammad#2308] opened 2018-10-23 13:50 UTC
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): Dockerhub, hosted trial instance (pls-helpdesk.zammad.com), package (all 3 tested)
* Operating system: Ubuntu 18.04
* Database + version:
* Elasticsearch version:
* Browser + version: Firefox 62

### Expected behavior:

* When adding a condition to the autoreply trigger that one tag should not be present, it should not send a auto reply.

### Actual behavior:

* The tag filter is ignored, the autoreply is beeing sent.

### Steps to reproduce the behavior:

* Modifiy trigger to ignore a tag, create a ticket via the API "as a customer".

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment] 2018-10-26 10:31
Hi @alex-LE 
can you please post a screenshot of your trigger configuration. This would help.

Thank you

**Comment by alex-LE** [comment] 2018-11-07 12:13
sure, here:

![grafik](https://user-images.githubusercontent.com/1616675/48131036-ec26cf80-e28e-11e8-833a-ac9a82c56154.png)

We are now creating the tickets via the api as closed and reopen them afterwards. This works for now.

**Comment by alex-LE** [comment] 2018-11-14 08:23
@hanneshal is that ok?

**Comment by MrGeneration** [comment] 2019-02-04 19:04
I can't reproduce this, it works as expected on my end. I used the following code:

```
{
    "group_id": 1,
    "priority_id": 3,
    "state_id": 2,
    "organization_id": 2,
    "title": "Some API-Test",
    "owner_id": 3,
    "customer_id": 6,
    "note": null,
    "first_response_at": null,
    "first_response_escalation_at": "2019-01-31T10:50:28.000Z",
    "first_response_in_min": null,
    "first_response_diff_in_min": null,
    "close_at": null,
    "close_escalation_at": "2019-02-06T10:50:28.000Z",
    "close_in_min": null,
    "close_diff_in_min": null,
    "update_escalation_at": "2019-02-01T11:20:28.000Z",
    "update_in_min": null,
    "update_diff_in_min": null,
    "last_contact_at": "2019-01-14T15:50:28.000Z",
    "last_contact_agent_at": null,
    "last_contact_customer_at": "2019-01-14T15:50:28.000Z",
    "last_owner_update_at": null,
    "create_article_type_id": 5,
    "create_article_sender_id": 2,
    "article_count": 1,
    "escalation_at": "2019-01-31T10:50:28.000Z",
    "pending_time": null,
    "type": "email",
    "time_unit": null,
    "preferences": {
        "escalation_calculation": {
            "first_response_at": null,
            "last_update_at": "2019-01-14T15:50:28.000Z",
            "close_at": null,
            "sla_id": 1,
            "sla_updated_at": "2019-01-15T08:30:55.830Z",
            "calendar_id": 1,
            "calendar_updated_at": "2019-01-17T10:53:45.906Z",
            "escalation_disabled": false
        }
    },
    "updated_by_id": 3,
    "created_by_id": 3,
    "created_at": "2019-01-14T15:50:28.000Z",
    "updated_at": "2019-01-18T17:49:29.928Z",
	"tags": "gets,ignored,anyway,noreply",
	"article": {
        "type_id": 1,
        "sender_id": 2,
        "from": "LeTest <alias@secret.tld>",
        "to": "Users",
        "cc": null,
        "subject": null,
        "reply_to": null,
        "message_id": null,
        "message_id_md5": null,
        "in_reply_to": null,
        "content_type": "text/html",
        "references": null,
        "body": "Some amazing test!",
        "internal": false,
        "preferences": {},
        "updated_by_id": 3,
        "created_by_id": 3,
        "origin_by_id": 5,
        "created_at": "2019-01-14T15:51:50.000Z",
        "updated_at": "2019-01-14T15:51:50.341Z",
        "attachments": [],
        "type": "email",
        "sender": "Customer",
        "created_by": "alias@secret.tld",
        "updated_by": "alias@secret.tld",
        "origin_by": "test2@test.com"
    }
}
```

Could you please take a look if you can still reproduce this?

**Comment by MrGeneration** [comment] 2019-02-11 09:35
I'll be closing this issue for now.
If you feel this is a mistake and the error still persists, please let us know here and provide the payload you used.

Otherwise we're not able to reproduce this.

**Closed as completed by MrGeneration** 2019-02-11 09:35 UTC
Labels: can't reproduce
