### ISSUE TITLE
Authentication via Generic OAuth2 - Unprocessable Entity

### ISSUE THREAD

**Issue by fsforna** [zammad/zammad#2944] opened 2020-03-02 11:04 UTC
### Infos:

* Used Zammad version: 3.2 community
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.2.24
* Elasticsearch version: 7.3.0
* Browser + version: Chrome 80.0.3987.122 

### Expected behavior:

* OAuth2 SSO working by using Keycloak 4.7.0.Final Identity Provider.

### Actual behavior:

* Zammad redirects to page

422: The change you wanted was rejected.
Message from oauth2: invalid_credentials

ERROR: Unprocessable Entity

I, [2020-03-02T11:39:09.799420 #21339-47105256767520]  INFO -- : Started POST "/auth/oauth2" for 10.159.30.112 at 2020-03-02 11:39:09 +0100
I, [2020-03-02T11:39:12.374903 #21339-47105256677760]  INFO -- : Started GET "/auth/oauth2/callback?state=67e50412bc77eb33b948bb8b71348ce72cbb37217bcd2b1a&session_state=d35eb831-e9ec-49b3-a2d0-ccf4159c1584&code=[FILTERED]" for 10.159.30.112 at 2020-03-02 11:39:12 +0100
I, [2020-03-02T11:39:12.452731 #21339-47105256767520]  INFO -- : Started GET "/auth/failure?message=invalid_credentials&origin=https%3A%2F%2FOUR_SITE%2F&strategy=oauth2" for XXXXXX at 2020-03-02 11:39:12 +0100
I, [2020-03-02T11:39:12.459206 #21339-47105256767520]  INFO -- : Processing by SessionsController#failure_omniauth as HTML
I, [2020-03-02T11:39:12.459278 #21339-47105256767520]  INFO -- :   Parameters: {"message"=>"invalid_credentials", "origin"=>"https://OUR_SITE/", "strategy"=>"oauth2"}
E, [2020-03-02T11:39:12.459715 #21339-47105256767520] ERROR -- : Message from oauth2: invalid_credentials (Exceptions::UnprocessableEntity)
/opt/zammad/app/controllers/sessions_controller.rb:95:in `failure_omniauth'

....................................

I, [2020-03-02T11:39:12.461431 #21339-47105256767520]  INFO -- : Completed 422 Unprocessable Entity in 2ms (Views: 1.1ms | ActiveRecord: 0.0ms)

### Steps to reproduce the behavior:

* Enable "Authentication via Generic OAuth2" security
* Fill Oauth2 form with required data

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-03-02 11:57
indirect duplicate of:
* https://github.com/zammad/zammad/issues/1431
* https://github.com/zammad/zammad/issues/868

Please note that this smells a bit of a technical question as well, the better place for those kind of questions would be the Community: http://community.zammad.org


Also, right now oAuth2 (generic) is broken in Zammad and more over not really support as we had to learn there's no such thing like "generic oAuth". 

Right now indications in that direction are a bit thin - I've been running a bigger search on our resources - our community gives the following addition information on the state of generic oAuth:

* https://community.zammad.org/t/scope-field-on-oauth2-generic-setup/3288
* https://community.zammad.org/t/nextcloud-as-oauth2-provider-not-working-minimum-one-identifier-login-firstname-lastname-phone-or-email-for-user-is-required/3737/4?u=mrgeneration
* (indirectly) https://community.zammad.org/t/issue-with-generic-oauth/1653

--- 

I've removed the duplicate flag for now, as I couldn't find direct duplicates. Issue here is that we proberbly won't address this issue because we're thinking of removing this functionality. (It simply provides more issues than use).

@thorsteneckel could you please have a look and decide on how to tag and continue on this? :)

**Comment by thorsteneckel** [comment] 2020-03-02 13:02
You are right @MrGeneration.

We should remove the generic OAuth2 provider because it's technically not possible to use it. Every OAuth2 provider needs some custom code to work properly. This can't be done in the current form. It causes much confusion and questions here on GitHub and in the Community. @MrGeneration can you please create a dedicated issue for for removing it? @mantas and his skills would be a perfect fit here 💪

**Comment by MrGeneration** [comment] 2020-03-05 11:03
I've created issue 2951 for removal. I'll thus close this ticket as a duplicate.

Sorry for the confusion from our end!

**Closed as completed by MrGeneration** 2020-03-05 11:03 UTC
Labels: duplicate
