### ISSUE TITLE
Org-Assignment by Domains does not work with LDAP

### ISSUE THREAD

**Issue by kevin-olbrich** [zammad/zammad#2681] opened 2019-07-24 12:15 UTC
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: PostgreSQL
* Elasticsearch version: 7.2, latest
* Browser + version: -

### Expected behavior:

* User that sync from LDAP should still assign Org-rules based on domains.

### Actual behavior:

* Users are sychronized but the organisation assignment based on mail domain does not take place. If the Org uses shared access to all tickets, they will only see their own.

### Steps to reproduce the behavior:

* Sync with ActiveDirectory using the included module and create an Org assignment based on domain. Then activate shared access to all tickets. The users will not be able to see other tickets.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2019-07-24 12:19
Hi @kevin-olbrich - nice to hear from you again. This is (technically) a duplicate of #1512. Therefore I'll close this issue. Thanks anyway for reporting it!

**Closed as completed by thorsteneckel** 2019-07-24 12:19 UTC
Labels: duplicate

**Comment by kevin-olbrich** [comment] 2019-07-24 13:03
> Hi @kevin-olbrich - nice to hear from you again. This is (technically) a duplicate of #1512. Therefore I'll close this issue. Thanks anyway for reporting it!

Thank you very much. I will try to set up a resync on my own.
Wehre did you hear from me in the past? :-)

**Comment by thorsteneckel** [comment] 2019-07-24 13:07
It's been a while and we didn't correspond directly but your engagement in https://github.com/zammad/zammad/pull/2404 left a good impression. I'm really enjoying constructive comments like this 👍 looking forward to hear from you again. If I can support you on your re-sync in any way feel free to reach out via DM in the [community board](http://community.zammad.org/).

**Comment by kevin-olbrich** [comment] 2019-07-24 13:18
Oh! Thank you very much for the good feedback! :-)

We are using Zammad for everything that leaves our office (offers, sales, support, accounting, monitoring, etc.). We also use the API for E-Invoices to streamline customer responses.
We like Zammad (especially me) and it helped us building a living CRM which would be very costly with less integration.
So far, we had no critical issues since the introduction of Zammad (first public release). Otherwise I would have opened more issues :-)

Thanks for this great software!
