### ISSUE TITLE
Mails cannot be processed if the special character "+" appears at the beginning of the sender address

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4624] opened 2023-05-25 09:24 UTC
### Used Zammad Version

5.4.1

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Mail addresses with the special character "+" at the beginning cannot be processed correctly by Zammad. The mails end up in unprocessable_mails on the system.

### Expected behaviour

Mails can be processed if the special character "+" appears at the beginning of the sender. 

https://www.rfc-editor.org/rfc/rfc3696#section-3

### Steps to reproduce the behaviour

Send a mail with a "+" at the beginning of your Mail Adress to the ticket system

entries from the production log

I, [2023-05-25T10:55:30.537567#755097-112860]  INFO -- : Process email with msgid '<4515FE76-FBBF-45FD-A341-39EC68B0CD00@XXX.de>'
E, [2023-05-25T10:55:30.552751#755097-112860] ERROR -- : can't run postmaster pre filter 0015_postmaster_filter_identify_sender: Channel::Filter::IdentifySender
E, [2023-05-25T10:55:30.552832#755097-112860] ERROR -- : #<ActiveRecord::RecordInvalid: Validation failed: Invalid email '+markus@XXX.de'>
E, [2023-05-25T10:55:30.553082#755097-112860] ERROR -- : Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/ba1e9811aa3a382a5ad72adda3c96631.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2023-05-25T10:55:30.553110#755097-112860] ERROR -- : Validation failed: Invalid email '+markus@XXX.de' (ActiveRecord::RecordInvalid)

### Support Ticket

Ticket#10128855

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2023-06-01 20:36
Duplicate of https://github.com/zammad/zammad/issues/4304.

**Closed as completed** 2023-06-01 20:36 UTC
Labels: duplicate
