### ISSUE TITLE
Freshdesk migration failed after a certain time

### ISSUE THREAD

**Issue by itsupply25** [zammad/zammad#4919] opened 2023-11-07 17:20 UTC
Hello, the problem still exists. If I try to migrate freshdesk system at the begining, the migration task crashes after a certain time. 
![06-11-_2023_11-45-36](https://github.com/zammad/zammad/assets/62522718/8039973c-83df-4ad0-942d-4a7d370064ae)

We have app. 40000 Tickets to migrate. If this migration task is not working, it make no sense for us to switch to zammad, even with paid plan. Is it possible to implement a retry button that proceeds if an error occurs and rememers the last successfully importet ticket? Would be great to have a working freshdesk migration procedure. 

The process improved since last year. But it still does not work without any problems.

_Originally posted by @itsupply25 in https://github.com/zammad/zammad/issues/4350#issuecomment-1794546343_

**Comment by dominikklein** [comment] 2023-11-07 20:14
Duplicate of #4350

**Closed as completed by dominikklein** 2023-11-07 20:14 UTC
Labels: duplicate
