### ISSUE TITLE
Customer's overviews need page reload after switching

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3497] opened 2021-04-06 10:11 UTC
### Infos:

* Used Zammad version: 4.0.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Tested with Firefox  87.0 and Chromium 89.0.4389.114 (Official Build)
~~* Ticket#1085588, #1085380~~

### Expected behavior:

* A customer's overviews should be displayed normally upon switching from one overview to another. 

### Actual behavior:

* After switching to a different overview, the page needs to be reloaded to display the tickets in the overview. 

https://user-images.githubusercontent.com/69846837/113694509-26029700-96d0-11eb-910a-4a83a8e1e369.mp4

### Steps to reproduce the behavior:

* Login as a customer. 
* Select the overviews tab. 
* Switch from one overview to another

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-04-06 10:42
Duplicate of #3479

**Closed as completed by MrGeneration** 2021-04-06 10:42 UTC
Labels: duplicate
