### ISSUE TITLE
Add custom link to the login page

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3875] opened 2021-12-01 16:20 UTC
### Infos:

* Used Zammad version: 5.0
* Installation method (source, package, ..): any 
* Operating system: any 
* Database + version: any 
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1096500

### Desired behavior:

It should be possible to add 2-3 custom links to the login page.

For example: To provide a link to ones "Data Privacy Policy", for compliance with GDPR or an imprint.

A footer would be the perfect place for these links.

### Actual behavior:

No custom link can be added to the login page. 

### Steps to reproduce the behavior:

Open your favorite Zammads login page in your favorite browser.

**Comment by malteschmitz** [comment] 2022-07-26 13:06
To me this looks like a duplicate of #3130

**Comment by MrGeneration** [comment] 2022-07-26 13:19
Yes and no. This issue actually has slightly more relevance for other parts. I'm thus closing issue #3130 in favor for this issue. Other than this, sharp eye.

**Closed as completed** 2022-09-01 12:23 UTC
Labels: enhancement, proposal, prioritised by payment
