### ISSUE TITLE
Missing translation in time accounting

### ISSUE THREAD

**Issue by Newan** [zammad/zammad#2056] opened 2018-06-07 08:19 UTC
### Infos:

* Used Zammad version: 2.5!
* Installation method (source, package, ..): deb
* Operating system: ubuntu 16.04
* Database + version: postgres
* Elasticsearch version: n/a
* Browser + version: chrome

### Expected behavior:

* German translation in Placeholder and typo in german translation see screenshot

### Actual behavior:

* the placeholder are not translated:
![image](https://user-images.githubusercontent.com/3693094/41087068-fff2d03e-6a3b-11e8-9d49-3a0309b237a6.png)
 typo in another tranlation:
![image](https://user-images.githubusercontent.com/3693094/41087164-39a7271c-6a3c-11e8-963c-0055b5cb8dfb.png)

### Steps to reproduce the behavior:

* show in webinterface by default

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-06-14 13:05
You can correct and provide the text via the blue "Push my changes" button that appears at the top of the page after you made your changes. We will apply and roll them out 👍

**Comment by Newan** [comment] 2018-06-14 13:14
ok the second translation i pushed but for "Please enter your time which you want to account" is missing in the translation section!

**Comment by thorsteneckel** [comment] 2018-06-14 13:20
The list oft translatable strings is generated dynamically. This means only elements that have been shown are able to get translated. So just trigger the timeaccounting modal popup and visit the admin translation section again and the `Please enter your time which you want to account.` string will be in the list, too.

**Comment by Newan** [comment] 2018-06-14 13:28
That's exactly my approach when creating this issues. First, I had the screenshot of time accounting and then go in the admin interface to make the second screen. no string found!

just tried again

**Comment by thorsteneckel** [comment] 2018-06-14 14:02
It's actually a bug! I can reproduce it as follows:

- Activate Timeaccounting
- Open "Admin -> Translation" interface
- Note that `Please enter your time which you want to account.` is not in the list of not translated strings (Todo) (**ok**)
- Go to Ticket Zoom view and cause Timeaccounting modal to open
- Re-open "Admin -> Translation" interface
- Note that `Please enter your time which you want to account.` is not in the list of not translated strings (Todo) (**wrong**)

In the latest step the string `Please enter your time which you want to account.` is in the [`@stringsNotTranslated` variable](https://github.com/zammad/zammad/blob/8af6e2b9ebd97954adfe05006b6ca7ab35e935db/app/assets/javascripts/app/controllers/translation.coffee#L252) but doesn't get rendered 🤔 I don't know why and have to dig deeper.

Reopening. Thanks for pointing it out.

**Comment by rlue** [comment] 2018-08-14 05:45
Very strange—I followed all of your steps, @thorsteneckel, and at first, I didn't see an entry for the placeholder text. But then, I clicked through the Time Accounting modal (just one step, and received some kind of invalid input error), and the voilà, there it was!

![2056_1](https://user-images.githubusercontent.com/12194123/44073753-103469f0-9fc8-11e8-917a-7a81f8d987cc.png)

It definitely works — I can enter a translation:

![2056_2](https://user-images.githubusercontent.com/12194123/44073761-17fd5566-9fc8-11e8-8207-e39947f5eff7.png)

and it will appear in the modal:

![2056_3](https://user-images.githubusercontent.com/12194123/44073764-1e5ccc7a-9fc8-11e8-92c4-f809b450621c.png)

FWIW, I'm on the latest `develop` branch, though, which is currently 2.7 (though not much has changed since the 2.6 release).

Thorsten, could I trouble you to confirm that it's broken again? If it's not, and everything's fine in 2.6, can we close this issue, or shall we commit to backporting a fix to 2.5?

**Comment by rlue** [comment] 2018-08-14 10:35
@Newan, after discussing this with Thorsten a little further, it appears that the missing translation _does_ get added to the list, but you can't see it because the list needs to be refreshed first.

We do consider this a bug, and are working on a fix to make sure the list is automatically refreshed in the future, but in the meantime, you should be able to do the following as a workaround:

1. Update a ticket to activate the time accounting (Zeiterfassung) modal,
2. Go back to the admin panel,
3. Visit an admin panel **other than Translations** (_e.g.,_ Objekte / the object manager),
4. Click back into the Translations admin panel.

Thanks for your patience while we work this out!

**Comment by rlue** [comment] 2018-08-22 10:46
Fixed by b035cfe

**Closed as completed by rlue** 2018-08-22 10:46 UTC
Labels: bug, admin area, verified, frontend, localization
