### ISSUE TITLE
Zammad Chat widget not working with jquery 3

### ISSUE THREAD

**Issue by MANFahrer-GF** [zammad/zammad#1220] opened 2017-06-30 19:58 UTC
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: CentOS 7
* Operating system: CentOS 7
* Browser + version: Chrome 

### Expected behavior:

* 

### Actual behavior:

* 

### Steps to reproduce the behavior:

* 

Hallo mein Problem ist hier zu finden 
https://community.woltlab.com/thread/260476-einbindung-eines-scriptes-jquery-zammad-chat/

Zugang zum System kann bereitgestellt werden.

**Comment by MANFahrer-GF** [comment] 2017-07-01 18:44
`chat debug || lang: de
chat.min.js:1 chat debug || load css from 'https://support.virtual-transport-group.de/assets/chat/chat.css'
chat.min.js:1 io debug || Connecting to wss://support.virtual-transport-group.de/ws
chat.min.js:1 io debug || onOpen Event {isTrusted: true, type: "open", target: WebSocket, currentTarget: WebSocket, eventPhase: 2…}
chat.min.js:1 chat notice || Translation needed for 'Scrolle nach unten um neue Nachrichten zu sehen'
chat.min.js:1 chat debug || widget rendered
chat.min.js:1 idleTimeout debug || Start timeout in 6 minutes
chat.min.js:1 io debug || send chat_status_customer Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", url: "https://www.virtual-transport-group.de/wcf/", chat_id: 1}
chat.min.js:1 io debug || onMessage [{"event":"chat_status_customer","data":{"state":"reconnect","session":[{"id":5,"chat_session_id":12,"content":"Hallo","created_by_id":3,"created_at":"2017-07-01T18:38:10.579Z","updated_at":"2017-07-01T18:38:10.579Z"}],"agent":{"name":"Thomas Kant","avatar":null}}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_status_customer", data: Object}
chat.min.js:1 chat debug || old messages [Object]
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 idleTimeout debug || Stop timeout of 6 minutes
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 chat debug || open widget
chat.min.js:1 idleTimeout debug || Stop timeout of 6 minutes
chat.min.js:1 io debug || send ping Object {}
chat.min.js:1 io debug || onMessage [{"event":"pong"}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "pong"}
chat.min.js:1 inactiveTimeout debug || Timeout check for 8 minutes (left -449.996 sec.)
chat.min.js:1 io debug || send chat_session_typing Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", chat_id: 1}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 io debug || onMessage [{"event":"chat_session_typing","data":{"session_id":"94f2e1cba7232ac6f8dddfd10c95bc18","self_written":true}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_session_typing", data: Object}
chat.min.js:1 io debug || send chat_session_typing Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", chat_id: 1}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 io debug || onMessage [{"event":"chat_session_typing","data":{"session_id":"94f2e1cba7232ac6f8dddfd10c95bc18","self_written":true}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_session_typing", data: Object}
chat.min.js:1 io debug || send chat_session_typing Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", chat_id: 1}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 io debug || onMessage [{"event":"chat_session_typing","data":{"session_id":"94f2e1cba7232ac6f8dddfd10c95bc18","self_written":true}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_session_typing", data: Object}
chat.min.js:1 io debug || send chat_session_typing Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", chat_id: 1}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 io debug || onMessage [{"event":"chat_session_typing","data":{"session_id":"94f2e1cba7232ac6f8dddfd10c95bc18","self_written":true}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_session_typing", data: Object}
chat.min.js:1 io debug || send chat_session_typing Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", chat_id: 1}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 io debug || onMessage [{"event":"chat_session_typing","data":{"session_id":"94f2e1cba7232ac6f8dddfd10c95bc18","self_written":true}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_session_typing", data: Object}
chat.min.js:1 io debug || send chat_session_typing Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", chat_id: 1}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 io debug || onMessage [{"event":"chat_session_typing","data":{"session_id":"94f2e1cba7232ac6f8dddfd10c95bc18","self_written":true}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_session_typing", data: Object}
chat.min.js:1 io debug || send chat_session_typing Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", chat_id: 1}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 io debug || onMessage [{"event":"chat_session_typing","data":{"session_id":"94f2e1cba7232ac6f8dddfd10c95bc18","self_written":true}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_session_typing", data: Object}
chat.min.js:1 io debug || send ping Object {}
chat.min.js:1 io debug || onMessage [{"event":"pong"}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "pong"}
chat.min.js:1 io debug || send chat_session_typing Object {session_id: "94f2e1cba7232ac6f8dddfd10c95bc18", chat_id: 1}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 io debug || onMessage [{"event":"chat_session_typing","data":{"session_id":"94f2e1cba7232ac6f8dddfd10c95bc18","self_written":true}}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "chat_session_typing", data: Object}
chat.min.js:1 inactiveTimeout debug || Stop timeout of 8 minutes
chat.min.js:1 inactiveTimeout debug || Start timeout in 8 minutes
chat.min.js:1 Uncaught TypeError: this.el.find(...).size is not a function
    at i.sendMessage (chat.min.js:1)
    at i.onSubmit (chat.min.js:1)
    at HTMLFormElement.<anonymous> (chat.min.js:1)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.q.handle (jquery.min.js:3)
i.sendMessage @ chat.min.js:1
i.onSubmit @ chat.min.js:1
(anonymous) @ chat.min.js:1
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
chat.min.js:1 io debug || send ping Object {}
chat.min.js:1 io debug || onMessage [{"event":"pong"}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "pong"}
chat.min.js:1 inactiveTimeout debug || Timeout check for 8 minutes (left -449.272 sec.)
chat.min.js:1 io debug || send ping Object {}
chat.min.js:1 io debug || onMessage [{"event":"pong"}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "pong"}
chat.min.js:1 inactiveTimeout debug || Timeout check for 8 minutes (left -419.27 sec.)
chat.min.js:1 io debug || send ping Object {}
chat.min.js:1 io debug || onMessage [{"event":"pong"}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "pong"}
chat.min.js:1 inactiveTimeout debug || Timeout check for 8 minutes (left -389.274 sec.)
chat.min.js:1 io debug || send ping Object {}
chat.min.js:1 io debug || onMessage [{"event":"pong"}]
chat.min.js:1 chat debug || ws:onmessage Object {event: "pong"}
chat.min.js:1 inactiveTimeout debug || Timeout check for 8 minutes (left -359.273 sec.)`

**Comment by MANFahrer-GF** [comment] 2017-07-01 18:45
`Uncaught TypeError: this.el.find(...).size is not a function
    at i.sendMessage (chat.min.js:1)
    at i.onSubmit (chat.min.js:1)
    at HTMLFormElement.<anonymous> (chat.min.js:1)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.q.handle (jquery.min.js:3)
i.sendMessage @ chat.min.js:1
i.onSubmit @ chat.min.js:1
(anonymous) @ chat.min.js:1
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
`

**Comment by hanneshal** [comment] 2017-07-02 18:06
Hi,

also aktuell fehlt der Zugriff auf das Chat Script. 

https://support.virtual-transport-group.de/ -> ist nicht erreichbar, damit kann der Chat auch nicht geladen werden. 
Wenn das behoben ist und das Problem weiterhin besteht schauen wir weiter.

**Comment by MANFahrer-GF** [comment] 2017-07-02 18:18
Dazu muss ich im Chat online sein. Leider bin ich gerade nicht zu hause

Von meinem iPad gesendet

**Comment by MANFahrer-GF** [comment] 2017-07-02 18:51
Hallo, 

Danke schon mal für deine Hilfe. Ich hatte den Server heruntergefahren. Jetzt ist alles wieder online.

Gruß Thomas 

Von meinem iPad gesendet

**Comment by hanneshal** [comment] 2017-07-03 10:56
Confirmed:
issue is related to jQuery >= 3.x

created demo site and switched from 
https://code.jquery.com/jquery-2.1.4.min.js
to
https://code.jquery.com/jquery-3.2.1.min.js

Summary:
can't press send button when jquery >= 3.x is used

Log Message:
```
Uncaught TypeError: this.el.find(...).size is not a function
    at i.sendMessage (chat.min.js:1)
    at i.onSubmit (chat.min.js:1)
    at HTMLFormElement.<anonymous> (chat.min.js:1)
    at HTMLFormElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLFormElement.q.handle (jquery-3.2.1.min.js:3)
```

**Comment by MANFahrer-GF** [comment] 2017-07-03 19:10
How can I help?

**Comment by martini** [comment] 2017-07-04 15:24
Hi @MANFahrer-GF 

the issue is fixed in stable branch. Would be great if you could update Zammad and verify if it's working now for you. Thanks a lot!

PS: Please check that chat.js is not in browser cache. 

 -Martin

**Comment by MANFahrer-GF** [comment] 2017-07-04 16:25
Hallo, 
wo bekomme ich das Update. Bei zammad.org steht noch die Version 1.5 und mein reop sagt auch 
zammad-1.5.0-1499180355.a85c1f0.centos7.x86_64.rpm

**Comment by martini** [comment] 2017-07-04 16:27
Hi @MANFahrer-GF 

es werden bei jeden push in den stable Branch neue Pakete gebaut. Somit kannst Du bei CentOS "yum update zammad" machen.

Die genaue Anleitung gibt es hier: https://docs.zammad.org/en/latest/install-update.html#update-with-rpm

 -Martin

**Comment by MANFahrer-GF** [comment] 2017-07-04 17:21
geht jetzt Danke.

Das war sehr wichtig:  Please check that chat.js is not in browser cache.

**Closed** 2017-07-04 18:22 UTC
Labels: bug, chat

**Comment by martini** [comment] 2017-07-04 19:18
@MANFahrer-GF Thanks for feedback (@IltisFahrer-GF 🤠)
