### ISSUE TITLE
Tickets Search Controller returns wrong data for custom single select object

### ISSUE THREAD

**Issue by gxrsti** [zammad/zammad#5389] opened 2024-11-04 14:31 UTC
### Used Zammad Version

6.3.1

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Assign exampleid 7 to a random ticket.

When opening {url}/api/v1/tickets/search?query=exampleid:7&limit=3000&expand=true in the browser, the ticket is not returned.

If I query for exampleid 1, the endpoint returns the ticket I assigned to exampleid 7.

### Expected behaviour

Assign exampleid 7 to a random ticket.

When opening {url}/api/v1/tickets/search?query=exampleid:7&limit=3000&expand=true in the browser, I would expect the ticket to be returned.

### Steps to reproduce the behaviour

1. Create a new object called exampleid as a single select field and add some dummy values with the values 1 and 7.
2. Update the database and restart Zammad
3. Assign the exampleid 7 to a random ticket
4. Open {url}/api/v1/tickets/search?query=exampleid:7&limit=3000&expand=true in browser

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment] 2024-11-04 15:12
I was not able to reproduce this, sorry.

It does take a couple of seconds after a ticket update before the search result is returned the first time, but this is due to the async search index update on *any* ticket change.

You could check if you have any outstanding search index jobs, perhaps? You can infer this from [the Rails console](https://docs.zammad.org/en/latest/admin/console.html) output:

```
rails r "pp Delayed::Job.where('handler LIKE ?', '%job_class: SearchIndexJob%Ticket%- 1%')
```

Where `1` is the offending ticket ID.

It could happen your search index update is stuck for some reason, so the async job does not get executed.

You could also try to rebuild the complete index with `rails zammad:searchindex:rebuild` command, and see if it helps.

I will close this report for now due to missing reproduction, but feel free to reopen with more information.

**Closed as not planned by dvuckovic** 2024-11-04 15:12 UTC
Labels: search, can't reproduce
