### ISSUE TITLE
LDAP sync fails with undefined method `ord' for nil:NilClass

### ISSUE THREAD

**Issue by mpibpc-mroose** [zammad/zammad#3278] opened 2020-11-10 16:34 UTC
### Infos:

* Used Zammad version: 3.5.0-1603788665.5a776fce.bionic
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04
* Database + version: postgresql-10/bionic-updates,bionic-security,now 10.14-0ubuntu0.18.04.1
* Elasticsearch version: 7.9.3
* Browser + version: Vivaldi 3.4.2066.94 (Stable channel) (64-bit)

### Expected behavior:

* LDAP sync should not fail

### Actual behavior:

* LDAP sync fails with "undefined method `ord' for nil:NilClass"

### Steps to reproduce the behavior:

* start sync in my environment
* Frontend shows 

```
An error occurred: undefined method `ord' for nil:NilClass
LDAP user to Zammad user (126/1582):
Users: 0 created, 0 updated, 126 untouched, 0 skipped, 0 failed, 0 deactivated
LDAP groups to Zammad roles assignments:
Customer: 0 created, 0 updated, 126 untouched, 0 failed, 0 deactivated
```
In the debug log I see the following extended error message:

```
E, [2020-11-10T17:18:15.923658 #8473-46971153766720] ERROR -- : ImportJob 'Import::Ldap' failed: undefined method `ord' for nil:NilClass
E, [2020-11-10T17:18:15.923691 #8473-46971153766720] ERROR -- : undefined method `ord' for nil:NilClass (NoMethodError)
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:77:in `getbyte'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ber/ber_parser.rb:169:in `read_ber'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:234:in `block in read'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/instrumentation.rb:19:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:233:in `read'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:201:in `queued_read'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:441:in `block (2 levels) in search'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:399:in `loop'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:399:in `block in search'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/instrumentation.rb:19:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/connection.rb:388:in `search'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:784:in `block (2 levels) in search'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:1303:in `use_connection'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:783:in `block in search'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap/instrumentation.rb:19:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/net-ldap-0.16.1/lib/net/ldap.rb:782:in `search'
/opt/zammad/lib/ldap.rb:72:in `search'
/opt/zammad/lib/sequencer/unit/import/ldap/users/sub_sequence.rb:15:in `process'
/opt/zammad/lib/sequencer/unit/base.rb:249:in `process'
/opt/zammad/lib/sequencer.rb:77:in `block (4 levels) in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:76:in `block (3 levels) in process'
/opt/zammad/lib/sequencer/state.rb:153:in `process'
/opt/zammad/lib/sequencer.rb:74:in `block (2 levels) in process'
/opt/zammad/lib/sequencer/units.rb:29:in `block in each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer.rb:72:in `each_with_index'
/opt/zammad/lib/sequencer.rb:72:in `block in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:70:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/import/mixin/sequence.rb:15:in `process'
/opt/zammad/lib/import/integration_base.rb:99:in `start'
/opt/zammad/app/models/import_job.rb:24:in `start'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/performable_method.rb:26:in `perform'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/backend/base.rb:78:in `invoke_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:230:in `block in run'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:229:in `run'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:213:in `block in work_off'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `times'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `work_off'
/opt/zammad/app/models/scheduler.rb:372:in `block (3 levels) in worker'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/opt/zammad/app/models/scheduler.rb:370:in `block (2 levels) in worker'
/opt/zammad/app/models/scheduler.rb:366:in `loop'
/opt/zammad/app/models/scheduler.rb:366:in `block in worker'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

I already increased the connetction timeout to `"connect_timeout"=>6000`

**Comment by mpibpc-mroose** [comment] 2020-11-11 07:44
I identified the root cause of the problem: it seems to be a kind of timeout thing. I use a haproxy in front of my domain controllers. The timeouts were maybe configured a bit slim. With a change in `haproxy.cfg` to:

```
timeout server        30s
timeout connect       10s
```
the sync is now successful. Maybe that as a hint for people encountering the same problems. I'm not sure if something like this could be catched in Zammad so that a more meaningfull error message could be supplied to the end user?

**Comment by MrGeneration** [comment] 2020-11-11 07:47
I think a dev has to decide on that.
Personally I'd say that if the sync runs into a timeout or connection reset during the try to talk to the ldap server, Zammad should provide a meaningful message.

**Comment by thorsteneckel** [comment] 2020-11-11 14:06
This is a duplicate of #2984 and #1862. Unfortunately we can't detect that this is a timeout error because it's handled inside of the LDAP ruby implementation. Closing now.

**Closed as completed by thorsteneckel** 2020-11-11 14:06 UTC
Labels: duplicate
