### ISSUE TITLE
Issue with Auto-Reply Trigger on Agent Email Follow-Ups

### ISSUE THREAD

**Issue by j0nf3n** [zammad/zammad#5278] opened 2024-07-22 09:50 UTC
### Used Zammad Version

6.3.1-1721369835.e7da6df9.bookworm

### Environment

- Installation method: package
- Operating system: debian 12.6
- Database + version:  postgresql 15.7
- Elasticsearch version: 7.10.2
- Browser + version: chrome 126.0.6478.182

### Actual behaviour

If an agent or customer sends an update to an already existing ticket via email, the "auto-reply (on follow-up of tickets)" trigger is activated and sends a notification email like "Thanks for updating the ticket..." to the sender of the last article on the ticket.

In the ticket history, you can see that the system notification was sent (which is expected), but it also sends the email from the trigger.

![image](https://github.com/user-attachments/assets/958adf45-feaf-4aae-8a7c-adb52e8879c1)

This is how the trigger is configured:

![image](https://github.com/user-attachments/assets/1f8177b0-74ee-4580-acde-2d620e715248)

This behavior affects all our agents.

### Expected behaviour

This trigger is only executed when a user with the cutomer role updates an existing ticket via email.

### Steps to reproduce the behaviour

1. Create a trigger configured as shown in the screenshot above.
2. Send an email from a Zammad agent who does not have the customer role to an existing ticket.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment] 2024-07-26 07:28
@j0nf3n Sorry, but I was not able to reproduce this.

For me, if the sender of an incoming email has a user account in Zammad with the Agent role assigned to it, the follow-up trigger does not run, just as expected. Even in case that user is marked as inactive in the system.

On the other hand, the follow-up trigger does run for a sender with the Customer role.

Perhaps you can review the role assignment of your agents, or report back with some additional information needed for reproduction. Thanks!

**Comment by j0nf3n** [comment] 2024-07-26 08:38
@dvuckovic Maybe I misunderstood the meaning of agent and customer as options for the sender condition. I thought it was the role assignment of the users, but I guess it's just about who is actually the customer or the agent of the corresponding ticket, which actually makes more sense. I must have mixed them up as they both have the same name. Sorry about that.
Guess the reason the follow-up trigger was run was because on some tickets, the customer and the agent were the same user.

After understanding this, I was wondering why when a new ticket is created via the email channel and I am automatically set as the customer of the ticket, the auto-reply trigger (on new tickets) is not executed for users with the Agent role, but only for users with the Customer role.

![image](https://github.com/user-attachments/assets/2d8bfb01-b186-4525-970a-13a9b2508e63)


Finally, it would be great if there was an option to have a condition for triggers based on the role of the sender. Maybe it already exists, but I haven't found it yet.

**Comment by dvuckovic** [comment] 2024-07-26 08:55
@j0nf3n Yes, I can confirm you are correct regarding the new ticket creation: even though the sender of the incoming email is set as the ticket customer, if that user has the Agent role, the auto-reply is not triggered for some reason.

To make matters worse, if an agent is assigned to an existing ticket as its customer, and then they send an email to the ticket, the follow-up auto-reply *is* triggered.

Currently, I have no explanation for this inconsistent behavior, nor what would be the expected one: what should win, ticket customer or the assigned role? But let me delve deeper and I'll have an answer for you soon.

Regarding your enhancement request (additional condition attribute for sender's role), I propose you submit it to our [Community forum](https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6/none), as per guidelines. But make sure to search for it first, there might be a similar request already present.

**Comment by dvuckovic** [comment] 2024-07-26 09:03
OK, good news: the auto-reply behavior is actually configurable, there is a setting that controls it.

Head on to **Admin > Channels > Email > Settings** and switch **Customer selection based on sender and receiver list** to _no_. Then the ticket customer should be set to the agent, and auto-reply should kick in as expected.

I will close this issue for now, but feel free to reopen it with more information.

**Closed as completed by dvuckovic** 2024-07-26 09:03 UTC
Labels: question, trigger

**Comment by icc-git** [comment] 2025-03-12 20:43
@dvuckovic can you clarify what is meant by "Then the ticket customer should be set to the agent"  
Is this a setting in the trigger?

**Comment by MrGeneration** [comment] 2025-03-12 20:45
Please use our community forum for technical questions, this repository is not suitable for this.
Thank you.

https://community.zammad.org
