### ISSUE TITLE
LDAP Integration won't sync the admin (Minimum one user needs to have admin permissions.)

### ISSUE THREAD

**Issue by MarvinKlar** [zammad/zammad#2336] opened 2018-11-07 08:53 UTC
### Infos:

* Used Zammad version: 2.7.0
* Installation method (source, package, ..): source
* Operating system: Debian
* Database + version: MariaDB
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* The LDAP synchronization should finish successfully

### Actual behavior:

* The LDAP synchronization fails with the following error: `An error occurred: Minimum one user needs to have admin permissions.`

### Steps to reproduce the behavior:

* Configure the LDAP integration as following:
Settings:
`UID | objectguid`
`User Filter | (&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))`
`GID | dn`
`Group Filter | (objectClass=group)`

Assignments:
User:
`givenname	firstname
sn	lastname
userprincipalname	login`

Roles:
 `cn=administratoren,cn=builtin,dc=my,dc=domain - Admin`
 `cn=agent,cn=zammad,dc=my,dc=domain - Agent`

When configuring this, the LDAP configuration already says(!): 
`Mit Ihre aktuellen Konfiguration werden sich folgende Änderungen ergeben:
LDAP Benutzer zu Zammad Benutzer (649):
Benutzer: 0 erstellt, 62 aktualisierte, 410 nicht verändert, 56 übersprungen, 121 fehlgeschlagen, 0 deaktiviert
LDAP Gruppen zu Zammad Rolle Zuweisung:
Agent: 0 erstellt, 0 aktualisierte, 14 nicht verändert, 0 fehlgeschlagen, 0 deaktiviert
Kunde: 0 erstellt, 62 aktualisierte, 394 nicht verändert, 0 fehlgeschlagen, 0 deaktiviert`

Which means, that the configuration won't sync the admin user! But, in our Active Directory is an admin, which matches the filter `(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))` and is in the group `cn=administratoren,cn=builtin,dc=my,dc=domain`!

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MarvinKlar** [comment] 2018-11-07 08:59
I tryed to add the filter `(!(userAccountControl:1.2.840.113556.1.4.803:=2))` to synchronize only active LDAP users. I don't know if the error is because of this, but even when I removed this filter the error continued to occour.

**Comment by thorsteneckel** [comment] 2018-11-07 09:02
Hi @MarvinKlar - this is a technical question and no bug. Please create a topic over at the [community board](http://community.zammad.org/) and mention me. I'll provide a debugging script where the root cause for this comes from. Closing this one now.

**Closed as completed by thorsteneckel** 2018-11-07 09:02 UTC
Labels: question

**Comment by MarvinKlar** [comment] 2018-11-07 09:24
Moved to https://community.zammad.org/t/ldap-integration-wont-sync-the-admin-minimum-one-user-needs-to-have-admin-permissions/1553
