### ISSUE TITLE
Custom select ticket object does not use the set default value

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#3081] opened 2020-06-12 07:50 UTC
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..):package
* Operating system: Debian9
* Database + version: -
* Elasticsearch version: -
* Browser + version: Firefox 77.0.1

### Expected behavior:

* When creating a ticket select object and crating e.g. 3 dropdown option only the 3 dropdown options should be available and and the set default value should be used when creating new tickets through all channel types.

### Actual behavior:

* When creating a ticket object as follows:
![image](https://user-images.githubusercontent.com/44224243/84476507-8b435280-ac8e-11ea-902a-f469b2eb76b5.png)

1. There will be 4 options as dropdown in all tickets:
![image](https://user-images.githubusercontent.com/44224243/84478828-3b668a80-ac92-11ea-935e-65a5e9dc262b.png)

2. The default value will only apply when creating tickets via the web interface.
Other channels line Email In and REST API will set "-" as the default option...

### Steps to reproduce the behavior:

* Create a ticket object as above.
* Create new ticket via the mentioned channels
*Even though the first option should be default, the "-" option is selected as default

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-06-12 07:55
This is a duplicate of https://github.com/zammad/zammad/issues/1653 which is why I'm closing this issue.
Thanks for your report though! :)

**Closed as completed by MrGeneration** 2020-06-12 07:55 UTC
Labels: duplicate
