### ISSUE TITLE
Configuring different SEND and RECEIVE E-Mails causes verification to fail

### ISSUE THREAD

**Issue by jantari** [zammad/zammad#2417] opened 2018-12-27 10:49 UTC
### Infos:

* Used Zammad version: 2.8.0-1545327715.c39804ac.xenial
* Installation method (source, package, ..): deb ackage
* Operating system: Ubuntu Server 16.04.5 LTS
* Database + version: PostgreSQL 9.5+173ubuntu0.2
* Elasticsearch version: 5.6.14
* Browser + version: Firefox 64.0 (64-bit) on Windows 10

### Expected behavior:

* When configuring different e-Mails for Zammad to send and receive from/on,
Zammad should be smart enough to watch the inbox of the RECEIVING e-Mail for
the test-Email it sent from the SENDING email-adress.

I believe currently (although didn't look at the code, just my educated guess)
Zammad monitors the inbox of the E-Mail Account entered as the SENDING
account for the Test/Verification E-Mails it sends and subsequently fails as they
never arrive.

### Actual behavior:

* When configuring different e-Mails for Zammad to send and receive from/on,
Zammad currently (although didn't look at the code, just my educated guess)
monitors the inbox of the E-Mail Account entered as the SENDING
account for the Test/Verification E-Mails it sends and subsequently fails as they
never arrive.

### Steps to reproduce the behavior:

* Go to the Zammad web interface and log in as an Admin
* Go to Settings -> Channels -> E-Mail
* Delete existing configuration
* Configure a new Sending and Receiving E-Mail address/account,
but use DIFFERENT e-Mails for sending and receiving.
* The verification at the end of the setup process will fail despite
both e-Mail accounts being set up correctly and each working fine
when set as BOTH sending and receiving, but mixing doesn't work

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-02-05 18:03
Sorry for taking so long.
Can you please explain your use case why you'd want to do that?

Because in my opinion it doesn't make any sense configuring an outgoing email address that if you reply on it, it will never find it's way into the original mailbox and thus Zammad won't be able to append it to the existing ticket.

That's more over a wrong usuage in my opinion. Still, I'll discuss this in our Team.
You might want to consider outgoing Channels only, as this will workaround that problem (still, I don't see the use case personally).

Link to workaround:
https://admin-docs.zammad.org/en/latest/channel-email/sendmail.html

**Comment by MrGeneration** [comment] 2019-02-19 12:10
I haven't received any feedback and have no system to reproduce this cleanly.
Thus I'm closing this issue.

If you're feeling this is a mistake, please provide a use case and clear instructions what to do (especially in terms on what mailing system is being used)

**Closed as completed by MrGeneration** 2019-02-19 12:10 UTC
Labels: works as designed / wontfix, can't reproduce
