### ISSUE TITLE
Job BackgroundJobSearchIndex > high CPU load

### ISSUE THREAD

**Issue by hagen3000** [zammad/zammad#1070] opened 2017-05-11 08:47 UTC
### Infos:

* Used Zammad version: 1.5.0-1494408244.52e954
* Used elasticsearch version: 5.4.0
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04
* Hypervisor: Hyper-V 2016
* CPU: 4 Cores
* RAM: 4-16 GB dynamic
* Imported LDAP-User : ~500
* Tickets < 100

After update my Zammad testsystem to Version 1.5.0-1494408244.52e954 from packages there is an high CPU load. Cause seems to be BackgroundJobSearchIndex. Together with the hourly LDAP synchronization, the system is very busy. Rebooting the processes or the server does not solve the problem. No one is working on the system.

![generateimage](https://cloud.githubusercontent.com/assets/7038961/25939982/ee832dc6-3634-11e7-9aca-f1e3d86f0a9c.png)

production.log
I, [2017-05-11T10:26:51.469932 #192752]  INFO -- : 2017-05-11T10:26:51+0200: [Worker(host:TICKET02 pid:192752)] Job BackgroundJobSearchIndex (id=1015107) RUNNING
I, [2017-05-11T10:26:51.473253 #192752]  INFO -- : # curl -X POST "http://127.0.0.1:9200/zammad_production/User/208" \
I, [2017-05-11T10:26:51.519042 #192752]  INFO -- : # 200
I, [2017-05-11T10:26:51.535326 #192752]  INFO -- : 2017-05-11T10:26:51+0200: [Worker(host:TICKET02 pid:192752)] Job BackgroundJobSearchIndex (id=1015107) COMPLETED after 0.0652
I, [2017-05-11T10:26:51.541639 #192752]  INFO -- : 2017-05-11T10:26:51+0200: [Worker(host:TICKET02 pid:192752)] Job BackgroundJobSearchIndex (id=1015108) RUNNING
I, [2017-05-11T10:26:51.547753 #192752]  INFO -- : # curl -X POST "http://127.0.0.1:9200/zammad_production/User/507" \
I, [2017-05-11T10:26:51.572893 #192752]  INFO -- : # 200
I, [2017-05-11T10:26:51.579618 #192752]  INFO -- : 2017-05-11T10:26:51+0200: [Worker(host:TICKET02 pid:192752)] Job BackgroundJobSearchIndex (id=1015108) COMPLETED after 0.0378
I, [2017-05-11T10:26:51.584327 #192752]  INFO -- : 2017-05-11T10:26:51+0200: [Worker(host:TICKET02 pid:192752)] Job BackgroundJobSearchIndex (id=1015109) RUNNING
I, [2017-05-11T10:26:51.596001 #192752]  INFO -- : # curl -X POST "http://127.0.0.1:9200/zammad_production/User/183" \
I, [2017-05-11T10:26:51.623412 #192752]  INFO -- : # 200
I, [2017-05-11T10:26:51.632283 #192752]  INFO -- : 2017-05-11T10:26:51+0200: [Worker(host:TICKET02 pid:192752)] Job BackgroundJobSearchIndex (id=1015109) COMPLETED after 0.0478
I, [2017-05-11T10:26:51.649265 #192752]  INFO -- : 2017-05-11T10:26:51+0200: [Worker(host:TICKET02 pid:192752)] Job BackgroundJobSearchIndex (id=1015110) RUNNING
I, [2017-05-11T10:26:51.662866 #192752]  INFO -- : # curl -X POST "http://127.0.0.1:9200/zammad_production/User/201" \
I, [2017-05-11T10:26:51.691830 #192752]  INFO -- : # 200
I, [2017-05-11T10:26:51.695367 #192752]  INFO -- : 2017-05-11T10:26:51+0200: [Worker(host:TICKET02 pid:192752)] Job BackgroundJobSearchIndex (id=1015110) COMPLETED after 0.045

**Comment by hagen3000** [comment] 2017-05-11 08:50
![grafik](https://cloud.githubusercontent.com/assets/7038961/25940785/90ce971c-3637-11e7-8561-03de38aa56d3.png)

**Comment by hagen3000** [comment] 2017-05-11 09:35
After another reboot the problem seems solved. I will observe the behavior.

**Comment by hagen3000** [comment] 2017-05-11 12:53
The problem occurs again after an LDAP sync. Endless BackgroundJobSearchIndex jobs in production.log.

**Comment by thorsteneckel** [comment] 2017-05-11 13:04
Hi @hagen3000 - thanks for the comprehensive investigation! Zammad reindexes the synced users to the ElasticSearch(ES) so they can be found via the search and stuff. However the system load is pretty high for piping this little amount of data from A to B. We'll try to reproduce this in our test environment.  Seems there is a memory leak somewhere while importing/filling the ES.

**Comment by thorsteneckel** [comment] 2017-05-12 09:23
Still investigating, current state (without BackgroundJobSearchIndex)

<img width="829" alt="bildschirmfoto 2017-05-12 um 10 39 42" src="https://cloud.githubusercontent.com/assets/3873515/25991943/616e3fa8-3705-11e7-8e5a-8510fe90724b.png">
<img width="676" alt="bildschirmfoto 2017-05-12 um 11 21 28" src="https://cloud.githubusercontent.com/assets/3873515/25991944/617191da-3705-11e7-9161-f193f9ac4abb.png">

**Comment by thorsteneckel** [comment] 2017-05-12 09:48
Still investigating. Current state (**with** BackgroundJobSearchIndex):
<img width="1079" alt="bildschirmfoto 2017-05-12 um 11 47 00" src="https://cloud.githubusercontent.com/assets/3873515/25993004/d48900ba-3708-11e7-80e9-65fa094d9739.png">

<img width="616" alt="bildschirmfoto 2017-05-12 um 11 48 03" src="https://cloud.githubusercontent.com/assets/3873515/25993030/e8221f44-3708-11e7-96a2-0b433161e192.png">

**Comment by thorsteneckel** [comment] 2017-05-12 10:50
Hi @hagen3000 - I want to give you a short update: One source of the performance leak is already fixed in the latest stable release of Zammad 1.5. Please update if possible. There is another issue where the BackgroundJobSearchIndex gets called but shouldn't. I'm looking into it.

PS:
While testing this under heavy load my 2016 MBP crashed and overheated 🚒 I think we should add a some throtteling. I'm looking into this as well  👀

**Comment by hagen3000** [comment] 2017-05-12 12:15
Hi @thorsteneckel 

The problem seems solved after further server reboot and changes to the ldap config (less users are synchronized 524->403). I will test the new zammad update as soon as possible.

![generateimage](https://cloud.githubusercontent.com/assets/7038961/25996852/963db132-3719-11e7-887b-ebba3e520ff0.png)
![grafik](https://cloud.githubusercontent.com/assets/7038961/25997363/fdc1c558-371b-11e7-91c9-bca85534e71e.png)

**Comment by hagen3000** [comment] 2017-05-12 12:46
If it helps I would like to share the log files. Is there a mail address for this?

**Comment by thorsteneckel** [comment] 2017-05-12 15:48
Hi @hagen3000 - sorry for the high ping! With your input I found the cause for this and fixed it. It's currently in our CI environment and will be released shortly. The commit will be linked to this issue afterwards.

This was caused by a wrong change detection of changed attributes/associations. Changes to the roles were detected which was wrong. The wrong detected changes triggered following actions to notify clients and the ES about those. That's why your change to the "Don't synchronize" was so effective 👍 

In my tests the load dropped significantly and the throughput went up. An update of >8k users without any changes took only 2 minutes 😻 The load is still on 100% for the one Zammad Scheduler / ruby process but that's ok since we want the sync to be fast 🚗 
If there are any future load problems with a high CPU load (over a long time) we may introduce some throtteling. However this is not planned.

Again: Thank you very much! ✌️ 

@all other users: Please create another issue if you have issues with a high load on LDAP sync runs since this here is definitely fixed ❌

**Closed by thorsteneckel** 2017-05-12 15:48 UTC
Labels: bug
