### ISSUE TITLE
Can't process email

### ISSUE THREAD

**Issue by Freev4lley** [zammad/zammad#695] opened 2017-01-31 14:13 UTC
After OTRS 5 Migration this error appears:

```
E, [2017-01-31T13:57:50.258699 #2947] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//adc5de4c7c7bb776c3b73cd4de310dc1.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2017-01-31T13:57:50.258952 #2947] ERROR -- : ERROR: #<NoMethodError: undefined method `id' for nil:NilClass>
E, [2017-01-31T13:57:50.259080 #2947] ERROR -- : ERROR: ["/opt/zammad/app/models/channel/email_parser.rb:518:in `block in _process'", "/opt/zammad/app/models/transaction.rb:12:in `block in execute'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'", "/opt/zammad/app/models/transaction.rb:10:in `execute'", "/opt/zammad/app/models/channel/email_parser.rb:446:in `_process'", "/opt/zammad/app/models/channel/email_parser.rb:389:in `process'", "/opt/zammad/app/models/channel/driver/imap.rb:194:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:90:in `eval'", "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:56:in `loop'", "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"]
```

No errors on migrition process...  What can i do?

### Infos:

* Used Zammad version: 1.2
* Operating system: centos 7 minimal
* Browser + version: Firefox 50.01

**Comment by thorsteneckel** [comment] 2017-01-31 14:21
Hi @Freev4lley - could you please drop us the file `/opt/zammad/tmp/unprocessable_mail//adc5de4c7c7bb776c3b73cd4de310dc1.eml` to support@zammad.com as described in the error message so we can try it on our test system?

**Comment by martini** [comment] 2017-01-31 14:30
@thorsteneckel seems to be a duplicate of #689 

app/models/channel/email_parser.rb:518:

          priority_id: Ticket::Priority.find_by(name: '2 normal').id,

**Comment by thorsteneckel** [comment] 2017-01-31 14:39
@martini is right. Closing for now. @Freev4lley please see/subscribe #689 for further information on progress.

**Comment by Freev4lley** [comment] 2017-01-31 14:40
Thanks for your support!! I have send the E-Mail.

**Closed by thorsteneckel** 2017-01-31 14:39 UTC
Labels: bug, channel
