### ISSUE TITLE
Report - Filtering for Tags does not work

### ISSUE THREAD

**Issue by mtrojacher** [zammad/zammad#1720] opened 2017-12-19 08:56 UTC
### Infos:

* Used Zammad version: zammad_2.2.0-1512636639
* Installation method (source, package, ..): Ubuntu Repository
* Operating system: Ubuntu 16.04.3
* Database + version: Postgres 9.5
* Elasticsearch version: 5.6.5
* Browser + version: all

### Expected behavior:

* Create a report filter searching for all tickets containing one specific tag

### Actual behavior:

* The filter can be created and the preview shows exactly the tickets that match, but in the report - view an error message appears:
error 500: {“error”:“unknown operator ‘contains one’”} (same error when selecting “contains all” in the report designer - obviously error then states “contains all” is an unknown operator)

### Steps to reproduce the behavior:

* Create a report filtering for a tag

Yes I'm sure this is a bug and no feature request or a general question. ✅ 

[See this post](https://community.zammad.org/t/reporting-error-while-filtering-for-tags/115) for more information

**Comment by mtrojacher** [comment] 2017-12-19 09:44
Here the relevant lines from the production.log:

> I, [2017-12-19T10:36:15.997801 #8893]  INFO -- : Started POST "/api/v1/reports/generate" for 127.0.0.1 at 2017-12-19 10:36:15 +0100
> I, [2017-12-19T10:36:16.008332 #8893]  INFO -- : Processing by ReportsController#generate as JSON
> I, [2017-12-19T10:36:16.008557 #8893]  INFO -- :   Parameters: {"metric"=>"count", "year"=>2017, "month"=>12, "week"=>51, "day"=>19, "timeRange"=>"year", "profiles"=>{"3"=>true}, "backends"=>{"count::created"=>true, "count::closed"=>true, "count::backlog"=>true, "create_channels::phone_in"=>true, "create_channels::phone_out"=>true, "create_channels::email_in"=>true, "create_channels::email_out"=>true, "create_channels::web_in"=>true, "create_channels::twitter_in"=>true, "create_channels::twitter_out"=>true, "communication::phone_in"=>true, "communication::phone_out"=>true, "communication::email_in"=>true, "communication::email_out"=>true, "communication::web_in"=>true, "communication::twitter_in"=>true, "communication::twitter_out"=>true}}
> E, [2017-12-19T10:36:16.030458 #8893] ERROR -- : unknown operator 'contains all' (RuntimeError)
> /opt/zammad/lib/search_index_backend.rb:464:in 'block in selector2query'
> /opt/zammad/lib/search_index_backend.rb:445:in 'each'
> /opt/zammad/lib/search_index_backend.rb:445:in 'selector2query'
> /opt/zammad/lib/search_index_backend.rb:405:in 'selectors'
> /opt/zammad/lib/report/ticket_generic_time.rb:37:in 'aggs'
> /opt/zammad/app/controllers/reports_controller.rb:36:in 'block in generate'
> /opt/zammad/app/controllers/reports_controller.rb:28:in 'each'
> /opt/zammad/app/controllers/reports_controller.rb:28:in 'generate'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in 'send_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:186:in 'process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:30:in 'process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:20:in 'block in process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in 'run_callbacks'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:19:in 'process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/rescue.rb:20:in 'process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:32:in 'block in process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in 'block in instrument'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in 'instrument'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in 'instrument'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:30:in 'process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/params_wrapper.rb:252:in 'process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/controller_runtime.rb:22:in 'process_action'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:124:in 'process'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/rendering.rb:30:in 'process'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal.rb:189:in 'dispatch'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal.rb:253:in 'dispatch'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:49:in 'dispatch'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:31:in 'serve'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:50:in 'block in serve'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in 'each'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in 'serve'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:834:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in 'call!'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/builder.rb:63:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in 'context'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/cookies.rb:613:in 'call'

> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:26:in 'block in call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in 'run_callbacks'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:24:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:59:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in 'call_app'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in 'block in call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in 'block in tagged'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:26:in 'tagged'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in 'tagged'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/static.rb:125:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:522:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in 'call'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:624:in 'handle_request'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:438:in 'process_client'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:302:in 'block in run'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in 'block in spawn_thread'
> /opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in 'block in create_with_logging_context'
> I, [2017-12-19T10:36:16.033666 #8893]  INFO -- : Completed 500 Internal Server Error in 25ms (Views: 0.3ms | ActiveRecord: 4.2ms)

**Comment by thorsteneckel** [comment] 2018-01-19 14:50
This is a duplicate of #1761 which describes the error in a more general way.

**Closed by thorsteneckel** 2018-01-19 14:50 UTC

**Comment by muhammadn** [comment] 2018-02-22 12:15
@jwronken Had a discussion earlier and that we concluded that we can only have basic reports for now but for advanced reporting we will be using Grafana.
