### ISSUE TITLE
create scheduled tickets 

### ISSUE THREAD

**Issue by gwingend** [zammad/zammad#1285] opened 2017-07-22 13:19 UTC
### Infos:

* Used Zammad version: 1.6.1
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:

It would be great if it would be possible to use the scheduler to create tickets.
Sometimes you have jobs that have to be done repeatable and these tasks could be supervised best by using the ticket system.
i.e. 
- create a ticket every night to control the backup.
- create a ticket every first monday of the month that the tapes in the library have to be changed
and so on.

### Actual behavior:

I have not found any way to create tickets by the scheduler.

### Steps to reproduce the behavior:

*

**Comment by hanneshal** [comment] 2017-07-23 14:01
Duplicate of: https://github.com/zammad/zammad/issues/1162

**Closed by hanneshal** 2017-07-23 14:01 UTC
Labels: feature
