### ISSUE TITLE
Add user via call log

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1440] opened 2017-09-18 09:31 UTC
### Infos:

* Used Zammad version: 2.0.x latest
* Used Zammad installation source: source
* Operating system: macOS
* Browser + version: Chrome

### Expected behavior:

An agent should be able to create new customers via the caller log. 

### Actual behavior:

A default role, which is not needed in this case, is missing. 

### Steps to reproduce the behavior:

* Create call event
* Click on the event
* Try to add customer
* Error occurs

**Comment by natseg** [comment] 2017-09-19 14:48
Hi,

Used Zammad version: 2.1.x latest
Used Zammad installation source: source
Operating system: macOS
Browser + version: Chrome

On latest version, was unable to reproduce.
![ticket_customer_creation](https://user-images.githubusercontent.com/6449818/30598548-e9230796-9d51-11e7-8df5-1561d9dc2f93.gif)

**Comment by thorsteneckel** [comment] 2017-09-19 16:11
Hi @natseg - @hanneshal is talking about the Caller Log which is a different feature from the Call Ticket. You can configure Zammad to be used with telephone software (CTI). Currently only Sipgate is supported. When configured Sipgate will send call events to an API endpoint. This looks like this:

<img width="1509" alt="bildschirmfoto 2017-09-19 um 18 10 35" src="https://user-images.githubusercontent.com/3873515/30602781-eceb5ab8-9d65-11e7-9940-674cf4322def.png">

**Comment by thorsteneckel** [comment] 2018-03-06 08:15
This was actually fixed with https://github.com/zammad/zammad/commit/afb78f2200728a4c7ea3767d5ad46a944a8a1944 . Will be available in the upcoming Zammad version 2.4 🚀

**Closed by thorsteneckel** 2018-03-06 08:15 UTC
Labels: bug, verified
