### ISSUE TITLE
Status Code: 500. {"error":"\"\\xC3\" from ASCII-8BIT to UTF-8"} when opening a ticket

### ISSUE THREAD

**Issue by be-pankwi** [zammad/zammad#1353] opened 2017-08-21 09:45 UTC
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: source
* Operating system: ubuntu 16.04
* Browser + version: Mozilla Firefox 54

### Actual behavior:

* When I try to open one of our old tickets, I get the following error: Status Code: 500. {"error":"\"\\xC3\" from ASCII-8BIT to UTF-8"}

I don't know, how long this problem already exists because at the time the ticket was created and we were working on it, the error did'nt occur. We installed zammad 1.2.0 at first and updated with every new release until 1.5.0.

Any idea how to solve the problem? Thanks

**Comment by hanneshal** [comment] 2017-08-25 07:20
Hi @be-pankwi ,

can you provide your production.log (around the time of the incident) and the type of database you are using?

This would be helpful. 

Did you imported any old tickets from OTRS/Zendesk? Do you create tickets via REST Interface?

regards

**Comment by be-pankwi** [comment] 2017-08-25 08:35
Hi @hanneshal,
when I try to open the ticket, I find the following in the production.log:

```
I, [2017-08-25T09:53:34.937149 #23450]  INFO -- : Started GET "/api/v1/tickets/554?all=true&_=1503647290237" for ::1 at 2017-08-25 09:53:34 +0200
I, [2017-08-25T09:53:34.937549 #23450]  INFO -- : Started POST "/api/v1/taskbar" for ::1 at 2017-08-25 09:53:34 +0200
I, [2017-08-25T09:53:34.940801 #23450]  INFO -- : Processing by TicketsController#show as JSON
I, [2017-08-25T09:53:34.941100 #23450]  INFO -- :   Parameters: {"all"=>"true", "_"=>"1503647290237", "id"=>"554", "ticket"=>{}}
I, [2017-08-25T09:53:34.943868 #23450]  INFO -- : Processing by TaskbarController#create as JSON
I, [2017-08-25T09:53:34.944956 #23450]  INFO -- :   Parameters: {"key"=>"Ticket-554", "client_id"=>123, "callback"=>"TicketZoom", "params"=>{"ticket_id"=>"554", "shown"=>true}, "prio"=>6, "notify"=>false, "active"=>true, "id"=>"c-17", "taskbar"=>{"id"=>"c-17", "client_id"=>123, "key"=>"Ticket-554", "callback"=>"TicketZoom", "params"=>{"ticket_id"=>"554", "shown"=>true}, "prio"=>6, "notify"=>false, "active"=>true}}
I, [2017-08-25T09:53:35.013777 #23450]  INFO -- : Completed 201 Created in 69ms (Views: 0.6ms | ActiveRecord: 13.6ms)
E, [2017-08-25T09:53:35.142408 #23450] ERROR -- : "\xC3" from ASCII-8BIT to UTF-8
I, [2017-08-25T09:53:35.143134 #23450]  INFO -- : Completed 500 Internal Server Error in 199ms (Views: 0.2ms | ActiveRecord: 55.5ms)
I, [2017-08-25T09:53:36.898416 #23450]  INFO -- : Started PUT "/api/v1/taskbar/4401" for ::1 at 2017-08-25 09:53:36 +0200
I, [2017-08-25T09:53:36.901754 #23450]  INFO -- : Processing by TaskbarController#update as JSON
I, [2017-08-25T09:53:36.901928 #23450]  INFO -- :   Parameters: {"key"=>"Ticket-589", "client_id"=>"123", "callback"=>"TicketZoom", "state"=>{"ticket"=>{}, "article"=>{}}, "params"=>{"ticket_id"=>"589", "init"=>true}, "prio"=>3, "notify"=>false, "active"=>false, "updated_at"=>"2017-08-23T12:48:21.756Z", "id"=>"4401", "taskbar"=>{"id"=>"4401", "client_id"=>"123", "key"=>"Ticket-589", "callback"=>"TicketZoom", "state"=>{"ticket"=>{}, "article"=>{}}, "params"=>{"ticket_id"=>"589", "init"=>true}, "prio"=>3, "notify"=>false, "active"=>false, "updated_at"=>"2017-08-23T12:48:21.756Z"}}
I, [2017-08-25T09:53:36.943400 #23450]  INFO -- : Completed 200 OK in 41ms (Views: 0.5ms | ActiveRecord: 5.2ms)
I, [2017-08-25T09:53:42.216533 #23468]  INFO -- : execute Channel.fetch (try_count 0)...

```

We didn't import any tickets from other systems and we don't create tickets via REST-interface. The database we use is mysql 5.7.

I also killed the zammad cache, but the problem still exists...

regards

**Comment by HLFH** [comment] 2017-08-29 15:46
@thorsteneckel Related to: https://github.com/zammad/zammad/issues/1349?

Fixed in master maybe. I have this issue with 1.6.2 that I don't have with Master.

**Comment by thorsteneckel** [comment] 2017-08-29 15:51
@HLFH - sadly no 😞 The other issue was caused by an attachment filename imported from OTRS. Would be interesting if @be-pankwi can confirm the fix with the master branch.

**Comment by thorsteneckel** [comment] 2017-08-29 16:17
JFI: Looks like it something wrong with your Ticket with the ID `554`. Strange thing is that there is no traceback in the log that would help to reason about the cause...

**Comment by be-pankwi** [comment] 2017-08-30 08:29
I found out how to reproduce this error:

1. create a new ticket
2. send a mail to somebody out of the ticket and put some text with characters like "ä ö ü" in the cc-field (no correct email address)

The article will be saved, then the error occurs and you will not be able to open the ticket again.
In our case one of our agents has put the title of the ticket by mistake in the cc-field.

Thanks

**Comment by thorsteneckel** [comment] 2017-08-30 08:41
Hi @be-pankwi - kudos for making the effort to digging into it and finding the cause 💪 but as @HLFH stated I'm not able to reproduce it with the latest master version. This bug may already be fixed. Would be great if you could verify it in the latest version at some point.

**Comment by be-pankwi** [comment] 2017-08-30 08:48
Hi @thorsteneckel,

today is my last day before my holiday, so I don't want to make big changes in our productive system. I'll be back in 2 weeks, then I'll try to reproduce it in the latest version.

regards

**Comment by thorsteneckel** [comment] 2017-08-30 08:50
Have a great and relaxing holiday 🍹

**Comment by be-pankwi** [comment] 2017-09-28 06:03
Hi @thorsteneckel,

I have set up a copy of our productive system and updated it to 2.0. I'm still not able to open the old broken ticket, but I also can't reproduce the error in a new ticket, so I think you can close this issue.

Thanks for your help.

**Comment by thorsteneckel** [comment] 2017-10-04 08:36
Thanks for the feedback. Closing.

**Closed by thorsteneckel** 2017-10-04 08:36 UTC
Labels: wontfix
