### ISSUE TITLE
Unable to change elasticsearch index

### ISSUE THREAD

**Issue by MarvinKlar** [zammad/zammad#2094] opened 2018-06-22 14:13 UTC
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): source
* Operating system: Debian GNU/Linux 9
* Database + version: mysql  Ver 15.1 Distrib 10.2.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* Elasticsearch version: I tried the latest and 5.6.8
* Browser + version: Chrome 67.0.3396.87

### Expected behavior:

* The command `rails r "Setting.set('es_index', 'Zammad_Custom')"` should change the elasticsearch index from the default index `zammad` to `Zammad_Custom`.

### Actual behavior:

* But when I change the elasticsearch index with the command above i get this error when I try to view the reports through the zammad website: `{"error":"Unable to process GET request to elasticsearch URL 'http://127.0.0.1:9200/Zammad_Custom_production/Ticket/_search'. Check the response and payload for detailed information: \n\nResponse:\n#\u003cUserAgent::Result:0x00007fdad01f7810 @success=false, @body=nil, @data=nil, @code=\"404\", @content_type=nil, @error=\"No such file http://127.0.0.1:9200/Zammad_Custom_production/Ticket/_search, 404!\"\u003e\n\nPayload:\n{:query=\u003e{:bool=\u003e{:must=\u003e[{:range=\u003e{\"created_at\"=\u003e{:from=\u003e\"2018-01-01\", :to=\u003e\"2018-12-31\"}}}], :must_not=\u003e[{:term=\u003e{\"state\"=\u003e\"merged\"}}]}}, :size=\u003e0, :aggs=\u003e{:time_buckets=\u003e{:date_histogram=\u003e{:field=\u003e\"created_at\", :interval=\u003e\"month\"}}}}\n\nPayload size: 0M"}`

* And when I try to rebuild the searchindex with the command `rake searchindex:rebuild --trace` I get the following output:
`** Invoke searchindex:rebuild (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchindex:rebuild
** Execute searchindex:drop
drop indexes...done
** Execute searchindex:drop_pipeline
delete pipeline (pipeline)... done
** Execute searchindex:create
create indexes...rake aborted!
Unable to process PUT request to elasticsearch URL 'http://127.0.0.1:9200/Zammad_Custom_production'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x000055cdd52235f0 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">

Payload:
{:mappings=>{:Ticket=>{:_source=>{:excludes=>["article.attachment"]}}}}

Payload size: 0M
/opt/CMS/zammad/lib/search_index_backend.rb:182:in `index'
/opt/CMS/zammad/lib/tasks/search_index_es.rake:57:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/opt/CMS/zammad/lib/tasks/search_index_es.rake:166:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.4.4/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => searchindex:rebuild`

* And the elasticsearch log shows the following:
`[2018-06-22T16:10:16,425][INFO ][o.e.n.Node               ] [1GAnPW3] stopping ...
[2018-06-22T16:10:16,478][INFO ][o.e.n.Node               ] [1GAnPW3] stopped
[2018-06-22T16:10:16,479][INFO ][o.e.n.Node               ] [1GAnPW3] closing ...
[2018-06-22T16:10:16,496][INFO ][o.e.n.Node               ] [1GAnPW3] closed
[2018-06-22T16:10:20,157][INFO ][o.e.n.Node               ] [] initializing ...
[2018-06-22T16:10:20,324][INFO ][o.e.e.NodeEnvironment    ] [1GAnPW3] using [1] data paths, mounts [[/ (/dev/sda2)]], net usable_space [109gb], net total_space [120gb], spins? [possibly], types [ext4]
[2018-06-22T16:10:20,325][INFO ][o.e.e.NodeEnvironment    ] [1GAnPW3] heap size [1.9gb], compressed ordinary object pointers [true]
[2018-06-22T16:10:20,348][INFO ][o.e.n.Node               ] node name [1GAnPW3] derived from node ID [1GAnPW3bSXu5lXVQVKGNmg]; set [node.name] to override
[2018-06-22T16:10:20,349][INFO ][o.e.n.Node               ] version[5.6.8], pid[1248], build[688ecce/2018-02-16T16:46:30.010Z], OS[Linux/4.9.0-6-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_171/25.171-b11]
[2018-06-22T16:10:20,349][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2018-06-22T16:10:21,887][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [aggs-matrix-stats]
[2018-06-22T16:10:21,887][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [ingest-common]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [lang-expression]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [lang-groovy]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [lang-mustache]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [lang-painless]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [parent-join]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [percolator]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [reindex]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [transport-netty3]
[2018-06-22T16:10:21,888][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded module [transport-netty4]
[2018-06-22T16:10:21,889][INFO ][o.e.p.PluginsService     ] [1GAnPW3] loaded plugin [ingest-attachment]
[2018-06-22T16:10:24,397][INFO ][o.e.d.DiscoveryModule    ] [1GAnPW3] using discovery type [zen]
[2018-06-22T16:10:25,271][INFO ][o.e.n.Node               ] initialized
[2018-06-22T16:10:25,271][INFO ][o.e.n.Node               ] [1GAnPW3] starting ...
[2018-06-22T16:10:25,509][INFO ][o.e.t.TransportService   ] [1GAnPW3] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-06-22T16:10:28,634][INFO ][o.e.c.s.ClusterService   ] [1GAnPW3] new_master {1GAnPW3}{1GAnPW3bSXu5lXVQVKGNmg}{0eLjUicvQ3ybFTvgfw6XEw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2018-06-22T16:10:28,736][INFO ][o.e.h.n.Netty4HttpServerTransport] [1GAnPW3] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2018-06-22T16:10:28,736][INFO ][o.e.n.Node               ] [1GAnPW3] started
[2018-06-22T16:10:29,075][INFO ][o.e.g.GatewayService     ] [1GAnPW3] recovered [1] indices into cluster_state
[2018-06-22T16:10:29,525][INFO ][o.e.c.r.a.AllocationService] [1GAnPW3] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[zammad_production][4]] ...]).
`

Here it saies `zammad_production`. So I guess that the index doesn't get created correctly?

### Steps to reproduce the behavior:

* Install Zammad with elasticsearch and try to change the index.

Yes I'm sure this is a bug and no feature request or a general question.

How can I fix this? Or am I doing something wrong?

**Comment by thorsteneckel** [comment] 2018-06-22 17:48
Hi @MarvinKlar - Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

The cause for this is that ES indexes have to be all lowercased. I currently can't find the documentation for that but you can google `elasticsearch index name must be lowercase` and you will be find plenty of other information.
However, to make reasoning about ES errors easier I'll add the response body of the request to the log over the next days 👍

**Closed as completed by thorsteneckel** 2018-06-22 17:48 UTC
Labels: question
