### ISSUE TITLE
Office 365 Authentication Error

### ISSUE THREAD

**Issue by michaelsudnik** [zammad/zammad#3074] opened 2020-06-05 09:05 UTC
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): Ubuntu via DEB
* Operating system: Ubuntu via DEB
* Database + version: PostgreSQL
* Elasticsearch version: 7.x
* Browser + version: Chome Version 83.0.4103.97 (Official Build) (64-bit)

### Expected behavior:

We have tried to enable the Office 365 Authentication and have set the relevant App Id and App Secret values.

We were expecting to enable the authentication and then be able to login with Office 365 or link a profile to Office 365.

### Actual behavior:

When we click the Office 365 button on the login screen we see the following:
![image](https://user-images.githubusercontent.com/59759409/83855874-9fc49f80-a710-11ea-8d5b-c909760f8fec.png)

There are 2 problems:
1. The error page is not rendering correctly with placeholders not being populated
2. We do not know why we are seeing this error page

The image is from an incognito session and we were not presented with any login pages - the page displayed immediately.

If we also go to a user profile we also see the same error page.

[production_snippet.log](https://github.com/zammad/zammad/files/4735013/production_snippet.log)

### Steps to reproduce the behavior:

1. Enable the Office 365 Auth
2. Set the App Id
3. Set the Secret Id
4. Try to login with Office 365

Yes I'm sure this is a bug and not a feature request or general question.

**Comment by MrGeneration** [comment] 2020-06-05 09:15
Sorry, but this sounds like a technical question or duplicate of 
* https://github.com/zammad/zammad/issues/2743 
* https://github.com/zammad/zammad/issues/2617
to me.

Please ensure this is not a technical question - if it is kindly post it on the community: https://community.zammad.org .
If you'd prefer commercial grade support, you can also have a look at our support contracts if interested: https://zammad.com/pricing#selfhosted

For now I'll be closing this.

**Comment by michaelsudnik** [comment] 2020-06-05 09:19
@MrGeneration - but #2743 is closed (which this looks similar to) and there is definitely a bug in that the Zammad generated web page is not displaying its content correctly. I am also confident that I have configured the azure back end correctly and it is not working. You can see the exact problem by navigating to the URL in the screenshot and clicking Office 365... it definitely should not be doing what its doing and is a bug... The log file is also reporting a fatal error: 

I, [2020-06-05T08:56:00.260467 #34626-47257433615180]  INFO -- : Started POST "/auth/microsoft_office365" for ###.###.###.### at 2020-06-05 08:56:00 +0000
I, [2020-06-05T08:56:00.264859 #34626-47257433615180]  INFO -- : (microsoft_office365) Request phase initiated.
F, [2020-06-05T08:56:00.266115 #34626-47257433615180] FATAL -- :   
F, [2020-06-05T08:56:00.266159 #34626-47257433615180] FATAL -- : ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
F, [2020-06-05T08:56:00.266175 #34626-47257433615180] FATAL -- :   
F, [2020-06-05T08:56:00.266204 #34626-47257433615180] FATAL -- : vendor/bundle/ruby/2.5.0/gems/omniauth-rails_csrf_protection-0.1.2/lib/omniauth/rails_csrf_protection/token_verifier.rb:34:in `call'

**Comment by michaelsudnik** [comment] 2020-06-05 09:20
We are definitely going to be purchasing a support contract, but first want to evaluate that the features we require are available.

**Comment by michaelsudnik** [comment] 2020-06-05 10:00
I just had a look at #2743 and it does appear to be an issue with Chrome weirdly. When I test it with Edge I can get it to work fine.

**Comment by michaelsudnik** [comment] 2020-06-05 10:08
Just some additional notes about the configuration steps I went through.

I found that, although I had installed an SSL certificate and was doing redirects to https in the Nginx config, I had not set the HTTP type in the System settings to be https. That fixed an issue that Office 365 was reporting (using Edge) saying that the redirect URL was not correct.

I also had to set the Azure App Registration - Support account type to be: "Accounts in any organizational directory (Any Azure AD directory - Multitenant)".

It then worked in Edge - but not yet in Chrome. While using Chrome it does not seem to "touch" any of the Office 365 infrastructure.

**Comment by joenilson** [comment] 2021-06-30 04:49
Hi, i'm facing the same issue but with Zammad 4.1 installed in ubuntu 18.04 with apache and behind Azure FrontDoor, i was blaming Frontdoor, but i can login with an Office365 user with single password authentication, but when i try to login with a user with 2FA i get the error, i was getting the message like this issue and now after applying the apache headers for https i'm getting the 422 Unprocessable Entity error only with the Office365 account with 2FA enabled.

**Comment by MrGeneration** [comment] 2021-06-30 08:50
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*


----


Please use the secret **VALUE** not ID. 
Documentation updates will follow as soon as it has gone through QA.

**Closed as completed by MrGeneration** 2021-06-30 08:50 UTC
Labels: question, can't reproduce
