### ISSUE TITLE
Call http request in a trigger

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1138] opened 2017-05-26 12:19 UTC
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Package
* Operating system: CentOS
* Browser + version: 

### Expected behavior:
Would be nice if be able to Call custom http request in a trigger with dynamic zammad tokens.
In this way many integration could be done easily, For example send a SMS to client when a new ticket create (Send SMS via HTTP) , etc ...

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment] 2018-05-13 09:54
Duplicate of #290.

**Closed by thorsteneckel** 2018-05-13 09:54 UTC
