### ISSUE TITLE
JS error on creating new customer

### ISSUE THREAD

**Issue by chrisblech** [zammad/zammad#1813] opened 2018-02-07 23:00 UTC
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): package (Zammad DEB repo)
* Operating system: Debian 9.3
* Database + version: PostgreSQL 9.6.6
* Elasticsearch version: 5.6.7
* Browser + version: Chrome 63.0.3239.108

### Expected behavior:

* Agent can create new customer

### Actual behavior:

* Agent can't create new customers !
* Button [Submit] in Dialog "New: User" does nothing, JS Console says:

Uncaught TypeError: Cannot read property 'id' of null
    at i.onSubmit (application-d633a6e7bd093fa6e5f64c37fa24e44e29386da511b4475025e01b267c061cd3.js:65)
    at i.onSubmit (application-d633a6e7bd093fa6e5f64c37fa24e44e29386da511b4475025e01b267c061cd3.js:65)
    at i.submit (application-d633a6e7bd093fa6e5f64c37fa24e44e29386da511b4475025e01b267c061cd3.js:24)
    at i.submit (application-d633a6e7bd093fa6e5f64c37fa24e44e29386da511b4475025e01b267c061cd3.js:23)
    at HTMLButtonElement.<anonymous> (application-d633a6e7bd093fa6e5f64c37fa24e44e29386da511b4475025e01b267c061cd3.js:8)
    at HTMLDivElement.dispatch (application-d633a6e7bd093fa6e5f64c37fa24e44e29386da511b4475025e01b267c061cd3.js:2)
    at HTMLDivElement.m.handle (application-d633a6e7bd093fa6e5f64c37fa24e44e29386da511b4475025e01b267c061cd3.js:2)

### Steps to reproduce the behavior:

* Agent clicks on [+] and [New Ticket]
* Click input "Customer"
* click "+ add new customer"
* enter Name
* click [Submit]
* nothing happens: dialog stays open

Yes I'm sure this is a bug and no feature request or a general question.

Additional Info: We added a custom field for users: "Org-Kürzel / ov / input"

**Comment by AchMol** [comment] 2018-02-08 09:24
Yes, we can confirm this bug. We got stuck by this one too, today...

**Comment by martini** [comment] 2018-02-08 12:56
Hi, thanks for reporting. I tried to reproduce it. But on my side it works fine. 

Can somebody reproduce it on an online instant at https://zammad.com/getting-started ?

Thanks for feedback!

**Comment by AchMol** [comment] 2018-02-08 13:25
Some more info as an addition:
When an admin role user creates a new customer everything is working fine. But when an agent role user tries this the error appears and nothing is happening. This might be your problem to reproduce.

But the forms are different. The agent form for creating a new customer doesn't have the both password fields.

**Comment by martini** [comment] 2018-02-08 13:31
Thanks for feedback. I tested it with the admin user and with an user only with agent permissions too. Both was working fine.

**Comment by AchMol** [comment] 2018-02-08 14:02
Hmm, I tried on " https://zammad.com/getting-started " and it worked there as expected...

But our agents still can't create a new customer because of this error:

![zammad1](https://user-images.githubusercontent.com/36261044/35976640-0b2cd76e-0ce1-11e8-8da4-efe393aa3179.png)

**Comment by martini** [comment] 2018-02-08 14:04
Wonderful! Please give me the instant name and it will be fixed ASAP. 😻

**Comment by martini** [comment] 2018-02-08 14:05
Or did you mean on your local instant it's still not working? Remote login possible?

**Comment by AchMol** [comment] 2018-02-08 14:08
Yes, sorry, I can just reproduce the error on our system.
If it would help I could create an account for you but I have to send you a client certificate per personal mail.

**Comment by martini** [comment] 2018-02-08 14:10
Sounds great, support at zammad dot com - thanks!

**Comment by chrisblech** [comment] 2018-02-08 14:36
I just created an account for this mail address here, so you can test. feel free to simulate or create any user.
https://support.hiorg-server.de
thx 4 your help

**Comment by martini** [comment] 2018-02-08 20:45
@chrisblech thanks for the login, I just found what the problem is. 

Problem: You renamed the default role "Customer". -> As workaround you can rename it back to Customer.

In the meantime a bugfix will be prepared.

**Comment by AchMol** [comment] 2018-02-09 07:38
Yep, this was the same cause in our case. We renamed it "Kunde". Thank you for the very fast help...

**Comment by martini** [comment] 2018-02-09 16:02
It's fixed in stable develop. Please update you Zammad package. Feedback is welcome! 😁

**Closed by martini** 2018-02-09 16:03 UTC
Labels: bug, verified
