### ISSUE TITLE
Problem while updating to 2.6: Mysql2::Error: Invalid default value for 'start_at'

### ISSUE THREAD

**Issue by altzone** [zammad/zammad#2183] opened 2018-08-11 11:20 UTC
* Used Zammad version: 2.6.0-1533865382.bb08ba03.xenial
* Installation method (source, package, ..): package 
* Operating system: Ubuntu 16.04.5 LTS
* Database + version: 5.7.23-0ubuntu0.16.04.1
* Elasticsearch version: 5.6.10
* Browser + version: Chrome 68.0.3440.84

### Expected behavior:

* Running update

### Actual behavior:

* error in 

```
-- rename_column(:cti_logs, :start, :start_at)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Invalid default value for 'start_at': ALTER TABLE `cti_logs` CHANGE `start` `start_at` timestamp(3) DEFAULT NULL
```

### Steps to reproduce the behavior:

* I can not reproduce the error because apt upgrade considers that the update worked correctly

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by altzone** [comment] 2018-08-11 11:27
The error is due to MySQL 5.7 sql-mode setting

  NO_ZERO_DATE, and NO_ZERO_IN_DATE

the solution would be to disable these two modes in the MySQL configuration
or to put the date field with a default of "2000-01-01 00:00:00"

How can I run the update a second time?
thank you very much

**Comment by pgodzwa** [comment] 2018-08-13 05:48
Same issue here.

**Comment by MrGeneration** [comment] 2018-08-13 07:17
Just to make sure and my verification work easier here:
Are you using MySQL or MariaDB?

**Comment by pgodzwa** [comment] 2018-08-13 08:28
MySQL here.

**Comment by altzone** [comment] 2018-08-13 08:29
Hello,
I’m using mysql 5.7 
If you want more information, dont hesitate ask me.

**Comment by thorsteneckel** [comment] 2018-08-14 08:09
This is really strange because the DB column will just get renamed. We don't change the default value at all. There are multiple other columns with a NULL Date default value.

You can re-run failed/remaining migrations via `rake db:migrate`.

Do you have performed a DB update in the meantime?

To be honest I think this is an issue we can't fix in the scope of Zammad. It's more a technical question caused by your setup. Technical questions ca be discussed in the [community board](http://community.zammad.org/). We'll give our best to help you but the `NO_ZERO_DATE, and NO_ZERO_IN_DATE` MySQL config hint from @altzone sounds pretty reasonable to me. However, I'll close this issue now.

**Comment by thorsteneckel** [comment] 2018-08-15 08:22
We found a way to work around this MySQL error from our scope. Fix is on the way 🚀

**Comment by thorsteneckel** [comment] 2018-08-15 19:47
Fixed with the two commit above in latest `stable` and `develop`. Packages should be ready in ~30 minutes from now. You can re-run the migration via `rake db:migrate` or `zammad run rake db:migrate` – depending on your installation source. Feedback would be great! Closing now. 🚀

**Comment by pgodzwa** [comment] 2018-08-16 05:58
@thorsteneckel now when I update, i get this error:
Mysql2::Error: Duplicate column name 'queue':

**Comment by thorsteneckel** [comment] 2018-08-16 06:50
Hi @sheLbyPL - thanks for the feedback! It looks like that MySQL won't allow running the table changes in a transaction which means that they were not reverted on the previous failure and the DB is now in a state "in between". However, could you please replace the file `db/migrate/20180809000001_cti_generic_api.rb` with the following content and retry:

```ruby
class CtiGenericApi < ActiveRecord::Migration[5.1]
  def up

    # return if it's a new setup
    return if !Setting.find_by(name: 'system_init_done')

    Setting.create_if_not_exists(
      title: 'cti integration',
      name: 'cti_integration',
      area: 'Integration::Switch',
      description: 'Defines if generic CTI is enabled or not.',
      options: {
        form: [
          {
            display: '',
            null: true,
            name: 'cti_integration',
            tag: 'boolean',
            options: {
              true  => 'yes',
              false => 'no',
            },
          },
        ],
      },
      state: false,
      preferences: {
        prio: 1,
        trigger: ['menu:render', 'cti:reload'],
        authentication: true,
        permission: ['admin.integration'],
      },
      frontend: true
    )
    Setting.create_if_not_exists(
      title: 'cti config',
      name: 'cti_config',
      area: 'Integration::Cti',
      description: 'Defines the cti config.',
      options: {},
      state: { 'outbound' => { 'routing_table' => [], 'default_caller_id' => '' }, 'inbound' => { 'block_caller_ids' => [] } },
      preferences: {
        prio: 2,
        permission: ['admin.integration'],
      },
      frontend: false,
    )
    Setting.create_if_not_exists(
      title: 'CTI Token',
      name: 'cti_token',
      area: 'Integration::Cti',
      description: 'Token for cti.',
      options: {
        form: [
          {
            display: '',
            null: false,
            name: 'cti_token',
            tag: 'input',
          },
        ],
      },
      state: SecureRandom.urlsafe_base64(20),
      preferences: {
        permission: ['admin.integration'],
      },
      frontend: false
    )

    add_column :cti_logs, :queue, :string, limit: 250, null: true          if !column_exists?(:cti_logs, :queue)
    add_column :cti_logs, :initialized_at, :string, limit: 250, null: true if !column_exists?(:cti_logs, :initialized_at)
    add_column :cti_logs, :duration_waiting_time, :integer, null: true     if !column_exists?(:cti_logs, :duration_waiting_time)
    add_column :cti_logs, :duration_talking_time, :integer, null: true     if !column_exists?(:cti_logs, :duration_talking_time)

    # fixes issue #2183 - Mysql2::Error: Invalid default value for 'start_at'
    if ActiveRecord::Base.connection_config[:adapter] == 'mysql2'
      change_column_default :cti_logs, :start, '0000-00-00 00:00:00'
      change_column_default :cti_logs, :end, '0000-00-00 00:00:00'
    end

    rename_column :cti_logs, :start, :start_at
    rename_column :cti_logs, :end, :end_at

  end
end
```

This checks if the columns already exist and skips the creation. Thanks!

**Comment by pgodzwa** [comment] 2018-08-16 07:18
@thorsteneckel 

done, now I get this error:

`== 20180809000001 CtiGenericApi: migrating ====================================
-- column_exists?(:cti_logs, :queue)
   -> 0.0008s
-- column_exists?(:cti_logs, :initialized_at)
   -> 0.0007s
-- column_exists?(:cti_logs, :duration_waiting_time)
   -> 0.0007s
-- column_exists?(:cti_logs, :duration_talking_time)
   -> 0.0007s
-- change_column_default(:cti_logs, :start, "0000-00-00 00:00:00")
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Invalid default value for `'start':`

**Comment by thorsteneckel** [comment] 2018-08-16 07:25
Could you please try the following and post the output here:

```ruby
class CtiGenericApi < ActiveRecord::Migration[5.1]
  def up

    # return if it's a new setup
    return if !Setting.find_by(name: 'system_init_done')

    Setting.create_if_not_exists(
      title: 'cti integration',
      name: 'cti_integration',
      area: 'Integration::Switch',
      description: 'Defines if generic CTI is enabled or not.',
      options: {
        form: [
          {
            display: '',
            null: true,
            name: 'cti_integration',
            tag: 'boolean',
            options: {
              true  => 'yes',
              false => 'no',
            },
          },
        ],
      },
      state: false,
      preferences: {
        prio: 1,
        trigger: ['menu:render', 'cti:reload'],
        authentication: true,
        permission: ['admin.integration'],
      },
      frontend: true
    )
    Setting.create_if_not_exists(
      title: 'cti config',
      name: 'cti_config',
      area: 'Integration::Cti',
      description: 'Defines the cti config.',
      options: {},
      state: { 'outbound' => { 'routing_table' => [], 'default_caller_id' => '' }, 'inbound' => { 'block_caller_ids' => [] } },
      preferences: {
        prio: 2,
        permission: ['admin.integration'],
      },
      frontend: false,
    )
    Setting.create_if_not_exists(
      title: 'CTI Token',
      name: 'cti_token',
      area: 'Integration::Cti',
      description: 'Token for cti.',
      options: {
        form: [
          {
            display: '',
            null: false,
            name: 'cti_token',
            tag: 'input',
          },
        ],
      },
      state: SecureRandom.urlsafe_base64(20),
      preferences: {
        permission: ['admin.integration'],
      },
      frontend: false
    )

    add_column :cti_logs, :queue, :string, limit: 250, null: true          if !column_exists?(:cti_logs, :queue)
    add_column :cti_logs, :initialized_at, :string, limit: 250, null: true if !column_exists?(:cti_logs, :initialized_at)
    add_column :cti_logs, :duration_waiting_time, :integer, null: true     if !column_exists?(:cti_logs, :duration_waiting_time)
    add_column :cti_logs, :duration_talking_time, :integer, null: true     if !column_exists?(:cti_logs, :duration_talking_time)

    p execute("SELECT @@sql_mode").first.first
    p execute("SELECT @@GLOBAL.sql_mode").first.first
    p execute("SELECT @@SESSION.sql_mode").first.first
    execute("SET sql_mode = ''")

    # fixes issue #2183 - Mysql2::Error: Invalid default value for 'start_at'
    if ActiveRecord::Base.connection_config[:adapter] == 'mysql2'
      change_column_default :cti_logs, :start, '0000-00-00 00:00:00'
      change_column_default :cti_logs, :end, '0000-00-00 00:00:00'
    end

    rename_column :cti_logs, :start, :start_at
    rename_column :cti_logs, :end, :end_at

  end
end
```

**Comment by pgodzwa** [comment] 2018-08-16 07:30
Seems to be fine now.

`== 20180809000001 CtiGenericApi: migrating ====================================
-- column_exists?(:cti_logs, :queue)
   -> 0.0008s
-- column_exists?(:cti_logs, :initialized_at)
   -> 0.0008s
-- column_exists?(:cti_logs, :duration_waiting_time)
   -> 0.0009s
-- column_exists?(:cti_logs, :duration_talking_time)
   -> 0.0008s
-- execute("SELECT @@sql_mode")
   -> 0.0002s
"ONLY_FULL_GROUP_BY,NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
-- execute("SELECT @@GLOBAL.sql_mode")
   -> 0.0002s
"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
-- execute("SELECT @@SESSION.sql_mode")
   -> 0.0002s
"ONLY_FULL_GROUP_BY,NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
-- execute("SET sql_mode = ''")
   -> 0.0002s
-- change_column_default(:cti_logs, :start, "0000-00-00 00:00:00")
   -> 0.0651s
-- change_column_default(:cti_logs, :end, "0000-00-00 00:00:00")
   -> 0.0335s
-- rename_column(:cti_logs, :start, :start_at)
   -> 0.0084s
-- rename_column(:cti_logs, :end, :end_at)
   -> 0.0055s
== 20180809000001 CtiGenericApi: migrated (0.1211s) ===========================

`

**Comment by thorsteneckel** [comment] 2018-08-16 07:31
Sweet! It worked 🚀I'll update the file. Your Zammad is now ready to run. Thanks a lot for your support 👍

**Comment by thorsteneckel** [comment] 2018-08-16 07:35
Fixed with the commits above in `stable` and `develop`. Packages are ready in ~30 minutes from now. This fix now supports migrations that are "half way executed" (columns already created) and MySQL servers configured in strict mode (which is now disabled for altering the name of the columns). Thanks a lot @sheLbyPL !

EDIT:
You can re-run the migration via `rake db:migrate` or `zammad run rake db:migrate` – depending on your installation source.

**Closed as completed by thorsteneckel** 2018-08-16 07:35 UTC
Labels: bug, verified, migration / update
