### ISSUE TITLE
Update notifications are sent even without changes on the ticket 

### ISSUE THREAD

**Issue by SamirMasato** [zammad/zammad#4474] opened 2023-01-26 09:08 UTC
### Used Zammad Version

5.3.0

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 20.04
- Database + version: postgresql 9.3
- Elasticsearch version: 7.17
- Browser + version: any

### Actual behaviour

When the update button in the ticket overview is pressed, even without any changes on the ticket, an update notification is sent to all the agents that have visibility on that ticket. 
Zammad also considers some attributes of the ticket as modified and in the notification email they appear as changes but without any value as modified field. 
I report a screenshot of the email notification, these 2 changes don't provide any information regarding a change.

![image](https://user-images.githubusercontent.com/80540377/214793341-2378e468-382d-4849-9bca-d15ce54121ab.png)

### Expected behaviour

If no changes are made, I would expect not to receive a notification email or at least a notification email without a list of modified attributes.

### Steps to reproduce the behaviour

Update a ticket without any changes on the ticket itself

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by rolfschmidt** [comment] 2023-01-26 11:37
@SamirMasato without further information we will not be able to fix or reproduce this. With the provided steps we can not reproduce the issue. Can you maybe also share a screenshot of the ticket history where the error occurred? Maybe it shows some helpful information.

Alternatively, feel free to create a test instance on: https://zammad.com/en/getting-started 
and reproduce the issue there. Then we can look at the hosted system and analyze the issue.

**Comment by SamirMasato** [comment] 2023-01-26 14:14
@rolfschmidt thank you for the reply. I apologize for not being more specific in my previous description, after more analysis I noticed that the attributes involved in the changes are custom one. The steps to reproduce the case are:
- Create a ticket at time X
- Create a custom attribute at time X + 1 (visible to the ticket) 
- Update the ticket

The ticket recognizes the new field as a change even if there's no value associated to it, so in the update notification email it is considered as a change with no value.

**Comment by fliebe92** [comment] 2023-01-30 08:19
Hey @SamirMasato, thanks for your effort to help us reproduce it, unfortunately, we are still not able to succeed.

Could you please use https://zammad.com/en/getting-started and create a system for us that shows the issue you reported? This would be awesome! We highly appreciate your help. 🙏 

Thanks a lot!

**Comment by fliebe92** [comment] 2023-02-09 15:36
Hey @SamirMasato, for the moment, due to missing information, I am going to close this issue. Feel free to re-open it with more information, we are happy to help if we are able to reproduce it.

Thanks 👍

**Closed as completed by fliebe92** 2023-02-09 15:36 UTC
Labels: waiting for feedback, can't reproduce

**Comment by nicoaffolter** [comment] 2023-07-14 09:52
Hi together,

we got the same issue on our zammad instance. 
zammad updates tickets on its own as long as the status is set to "new". i receive update notifications until i set the status to "open" for example

this happens with every ticket that comes in. 

The whole thing happened this morning for the first time without us changing anything in the config.

**Comment by MrGeneration** [comment] 2023-07-14 09:53
> zammad updates tickets on its own as long as the status is set to "new". i receive update notifications until i set the status to "open" for example

Smells like pending reminde reached reminders. If so this is not a bug.

**Comment by nicoaffolter** [comment] 2023-07-14 10:02
![grafik](https://github.com/zammad/zammad/assets/91869517/2623d82c-eebd-4260-bb8e-f554b63e98ed)

as you can see on the screenshot, zammad updates the ticket without making any change.

i get hundreds of notifications for a ticket in 5 minutes. seems like the whole thing is stuck in a loop

**Comment by MrGeneration** [comment] 2023-07-14 10:04
Sorry, but this is a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
