### ISSUE TITLE
Zammad doesn't like cyrillic aliases

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3941] opened 2022-02-01 13:48 UTC
### Infos:

* Used Zammad version: stable/5.0.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Verified on Opera v83 (Chromium based)
* Ticket: #10100757 

### Expected behavior:

Zammad accepts by RFC valid email aliases.

### Actual behavior:

Zammad does not support all RFC valid aliases.
Like those containing cyrillic names.

Processing emails causes:
```
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/416161d5732d97e0ec8eb4314fcd5750.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<Exceptions::UnprocessableEntity: Invalid email 'viktorpoblккeссdyi@example.com'>"
Traceback (most recent call last):
        62: from bin/rails:9:in `<main>'
        61: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        60: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        59: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        58: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        57: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        56: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands.rb:18:in `<main>'
        55: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/command.rb:46:in `invoke'
        54: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/command/base.rb:69:in `perform'
        53: from /usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        52: from /usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        51: from /usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        50: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `perform'
        49: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `eval'
        48: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
        47: from /opt/zammad/app/models/channel/email_parser.rb:504:in `process_unprocessable_mails'
        46: from /opt/zammad/app/models/channel/email_parser.rb:504:in `glob'
        45: from /opt/zammad/app/models/channel/email_parser.rb:505:in `block in process_unprocessable_mails'
        44: from /opt/zammad/app/models/channel/email_parser.rb:119:in `process'
        43: from /usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
        42: from /usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
        41: from /usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
        40: from /usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
        39: from /usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
        38: from /opt/zammad/app/models/channel/email_parser.rb:120:in `block in process'
        37: from /opt/zammad/app/models/channel/email_parser.rb:156:in `_process'
        36: from /opt/zammad/app/models/channel/email_parser.rb:156:in `each'
        35: from /opt/zammad/app/models/channel/email_parser.rb:159:in `block in _process'
        34: from /opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
        33: from /opt/zammad/app/models/channel/filter/identify_sender.rb:157:in `user_create'
        32: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/persistence.rb:55:in `create!'
        31: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/suppressor.rb:48:in `save!'
        30: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:318:in `save!'
        29: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
        28: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:212:in `transaction'
        27: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
        26: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
        25: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        24: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        23: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        22: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        21: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
        20: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
        19: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
        18: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
        17: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:318:in `block in save!'
        16: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/validations.rb:53:in `save!'
        15: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/validations.rb:84:in `perform_validations'
        14: from /usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/validations.rb:68:in `valid?'
        13: from /usr/local/rvm/gems/ruby-2.7.4/gems/activemodel-6.0.4.4/lib/active_model/validations.rb:337:in `valid?'
        12: from /usr/local/rvm/gems/ruby-2.7.4/gems/activemodel-6.0.4.4/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
        11: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
        10: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:134:in `run_callbacks'
         9: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
         8: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:513:in `each'
         7: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
         6: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:201:in `block in halting'
         5: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:604:in `block in default_terminator'
         4: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:604:in `catch'
         3: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
         2: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
         1: from /usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/opt/zammad/app/models/user.rb:908:in `check_email': Invalid email 'viktorpoblккeссdyi@exmaple.com' (Exceptions::UnprocessableEntity)
        19: from bin/rails:9:in `<main>'
        18: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        17: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        16: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        15: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        14: from /usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        13: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands.rb:18:in `<main>'
        12: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/command.rb:46:in `invoke'
        11: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/command/base.rb:69:in `perform'
        10: from /usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
         9: from /usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         8: from /usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         7: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `perform'
         6: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `eval'
         5: from /usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
         4: from /opt/zammad/app/models/channel/email_parser.rb:504:in `process_unprocessable_mails'
         3: from /opt/zammad/app/models/channel/email_parser.rb:504:in `glob'
         2: from /opt/zammad/app/models/channel/email_parser.rb:505:in `block in process_unprocessable_mails'
         1: from /opt/zammad/app/models/channel/email_parser.rb:117:in `process'
/opt/zammad/app/models/channel/email_parser.rb:135:in `rescue in process': #<Exceptions::UnprocessableEntity: Invalid email 'viktorpoblккeссdyi@example.com'> (RuntimeError)
/opt/zammad/app/models/user.rb:908:in `check_email'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:604:in `catch'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:201:in `block in halting'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:513:in `each'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:134:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/usr/local/rvm/gems/ruby-2.7.4/gems/activemodel-6.0.4.4/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/usr/local/rvm/gems/ruby-2.7.4/gems/activemodel-6.0.4.4/lib/active_model/validations.rb:337:in `valid?'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/validations.rb:68:in `valid?'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/validations.rb:84:in `perform_validations'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/validations.rb:53:in `save!'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:318:in `block in save!'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/transactions.rb:318:in `save!'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4.4/lib/active_record/persistence.rb:55:in `create!'
/opt/zammad/app/models/channel/filter/identify_sender.rb:157:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
/opt/zammad/app/models/channel/email_parser.rb:159:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:156:in `each'
/opt/zammad/app/models/channel/email_parser.rb:156:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:120:in `block in process'
/usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
/usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:119:in `process'
/opt/zammad/app/models/channel/email_parser.rb:505:in `block in process_unprocessable_mails'
/opt/zammad/app/models/channel/email_parser.rb:504:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:504:in `process_unprocessable_mails'
/usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
/usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `eval'
/usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:45:in `perform'
/usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/command/base.rb:69:in `perform'
/usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/command.rb:46:in `invoke'
/usr/local/rvm/gems/ruby-2.7.4/gems/railties-6.0.4.4/lib/rails/commands.rb:18:in `<main>'
/usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.7.4/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
```

While trying to add a user to double tab it's also the user creation affected, my browser stepped in and complained instead of Zammad... :-D
![image](https://user-images.githubusercontent.com/6549061/151952188-fd79e1f8-0b71-4eca-9571-8c4997cb67c5.png)

### Steps to reproduce the behavior:

* have a mail with cyrillic mail address in the from header.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-02-01 13:48
Please close as `works as designed / wontfix` in case the aliases really aren't allowed and thus Zammad acts correctly.

**Comment by mantas** [comment] 2022-09-28 13:15
Looks like this is already fixed with https://github.com/zammad/zammad/commit/8780373fdd978cd5d43f76709dcc20445cc3fab3

```ruby
[4] pry(main)> EmailAddressValidation.new('viktorpoblккeссdyi@example.com').valid?
=> true
```

Closing as duplicate of #4151

**Closed as completed by mantas** 2022-09-28 13:15 UTC
Labels: bug, duplicate, verified, prioritised by payment, mail processing
