### ISSUE TITLE
Sorting and name of role out of style

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4614] opened 2023-05-16 19:18 UTC
### Used Zammad Version

5.4.1

### Environment

- Installation method: Package
- Operating system: Ubuntu 20.04
- Database + version: Postgresql 9.3
- Elasticsearch version: 7.17
- Browser + version: 113

### Actual behaviour

We use Zammad with many departments in our company and created some roles. Now we see this (is not a big problem but a design issue I think which can be optimized).

- Sorting of roles are not logical
- many roles are in the horizontal line and breaks UI if you have to many roles created

![image](https://github.com/zammad/zammad/assets/1473674/0c5dc337-edc6-4a26-a37a-b0c5d2f0e8b3)

### Expected behaviour

- Sorting roles by A-Z
- If we have X roles created the menu should be a drop down or so?

### Steps to reproduce the behaviour

- create many roles
- the the user overview

Thank you very much!

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by JennyZammad** [comment] 2023-06-02 08:55
Hi @Dennis1993 
thank you for reporting this bug. We totally agree, that if you are able to create multiple roles, they should be displayed correctly. 
The sorting depends on the time of creation. all newly created roles are always appended at the end of the list.

best regards :)

**Comment by fliebe92** [comment] 2023-06-16 12:12
Duplicate of https://github.com/zammad/zammad/issues/4406, closing.

**Closed as completed by fliebe92** 2023-06-16 12:12 UTC
Labels: duplicate
