### ISSUE TITLE
 Korean input problem

### ISSUE THREAD

**Issue by elcidme** [zammad/zammad#4447] opened 2022-12-23 09:11 UTC
### Used Zammad Version

5.3

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): centos 7.8
- Database + version:  postgresql 14.5
- Elasticsearch version:  7.17
- Browser + version: Microsoft Edge 108, chrome 108
- 

### Actual behaviour

::(text module), @@(Inserts a mention for a user), ?? ( Inserts knowledge base answer) When searching, Korean is not searched.

### Expected behaviour

::(text module), @@(Inserts a mention for a user), ?? ( Inserts knowledge base answer) No problem in English when searching

### Steps to reproduce the behaviour

![image](https://user-images.githubusercontent.com/73980525/209306735-08e492f4-c8bd-4606-ae82-e373c6235cbe.png)

When checking the log, the value entered as below is recorded twice.
The same problem occurs from zammad 5.2 to 5.3 versions.

I, [2022-12-23T18:06:30.291977 #637-112080]  INFO -- : Processing by UsersController#search as JSON
I, [2022-12-23T18:06:30.292074 #637-112080]  INFO -- :   Parameters: {"limit"=>"10", "query"=>"ㄱ기김김ㅈ저정정ㅇ유윤", "role_ids"=>["2", "4"], "group_ids"=>{"4"=>"read"}, "full"=>"true", "_"=>"1671786101440"}
I, [2022-12-23T18:06:30.324510 #637-112080]  INFO -- : Completed 200 OK in 32ms (Views: 0.3ms | ActiveRecord: 7.0ms | Allocations: 9531)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment] 2023-01-10 09:48
Hello @elcidme,

thanks for your report, I tried to reproduce the problem but for me, it's working as expected with Korean characters.

Maybe you can give a more detailed step to step reproduction. For example, what kind of user you are creating which would you expect to be found? Maybe the user has not the correct group permissions?

Best regards,
Dominik

**Comment by elcidme** [comment] 2023-01-11 03:40
@dominikklein Thank you for showing interest in this problem. Please kindly understand that I have limited proficiency in English, so I am using a translator

The Korean language search function does not experience any problems unlike other search functions and search is performed normally
![image](https://user-images.githubusercontent.com/73980525/211712391-b7ff97c8-5744-4343-b49c-196dc7f5f89d.png)


I, [2023-01-11T12:30:53.324594 #56515-669860]  INFO -- :   Parameters: {"term"=>"김정윤"}

In the log, it can be seen that the parameters are completed as normal words and the search is performed, as shown in the screenshot, the search is also working normally


In the case of searching using ": :, @@, ??" , Korean language search is not working.

![image](https://user-images.githubusercontent.com/73980525/211712404-f3f04fb8-40d4-4180-a716-cb0ad5ac612c.png)

I, [2023-01-11T12:34:19.495055 #56515-1587840]  INFO -- :   Parameters: {"limit"=>"10", "query"=>"ㄱ기김김ㅈ저정정ㅇ유윤윤", "role_ids"=>["2", "4"], "group_ids"=>{"4"=>"read"}, "full"=>"true", "_"=>"1673407538675"}

**Comment by mantas** [comment] 2023-01-12 08:14
Hi @elcidme 

Do I understand correctly that in inline search with `::,@@,??` it sends wrong query to the server? In your screenshot `No results found` covers the query that you typed in the field..

**Comment by mgruner** [comment] 2024-03-19 12:54
Hello @elcidme, I just tried to reproduce this without success. I tweaked a Selenium test to simulate your korean input, and it worked well both with text modules (::) as well as user (@@) searches. Therefore I assume the issue is no longer relevant or has been fixed in the meantime. Would you be so kind to try it again with the latest version of Zammad and let us know? Thank you!

**Closed as not planned by mgruner** 2024-03-19 12:54 UTC
Labels: bug, ticket, verified, text modules, localization

**Comment by supplicate0514** [comment] 2025-07-08 12:00
I’ve encountered the same issue, and I can confirm that it is related to non-English languages, such as Chinese.

For example, when I try to input the word “測試” (which means “test”), I need to type the phonetic symbols “ㄘㄜˋ ㄕˋ” in order to convert it into the Chinese characters “測試.”

In the browser’s network tab, I can see that the API call is:
```
http://<ip>/api/v1/knowledge_bases/search  
{"query":"??ㄘㄘ測測測測","flavor":"agent","index":"KnowledgeBase::Answer::Translation","url_type":"agent","highlight_enabled":false,"include_locale":true}
```
This shows that the system is listening to the input in real time, which leads to this issue.

zammad version : 6.5.0
