### ISSUE TITLE
New translations are not returned by API after syncing

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#4015] opened 2022-03-16 15:52 UTC
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* After translations are synced, they're available in frontend

### Actual behavior:

* After translations are synced, API does not return new translations

### Steps to reproduce the behavior:

* Add translations to PO file(s)
* Run `Translation.sync` to load them
* Check `/api/v1/translations/lang/locale`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment] 2022-05-10 12:43
Seems to be a duplicate of #4016, closing.

**Closed as completed by mgruner** 2022-05-10 12:43 UTC
Labels: bug, verified
