### ISSUE TITLE
Zammad Redundancy with 2 Servers

### ISSUE THREAD

**Issue by ninees92** [zammad/zammad#668] opened 2017-01-24 09:19 UTC
Hi there,

I just have a question and can't find any info to the above:

I want to/did install 2 Zammad Servers that should work redundand. So if one server fails, the other one takes over the tasks and settings. Is there some way to implement this in my Zammad System or do I need to secure them by making snapshots or something? 

I found a way to connect them, but they work as two seperate systems, getting the same tickets...

Very thankful for any advice!

**Comment by jannheider** [comment] 2017-02-14 15:48
I think this is not really related to zammad.
To make Zammad redundant with two servers you could make this with Heartbeat and DRDB, but this is an advanced topic and i would suggest that only if you know those technologies.

**Comment by monotek** [comment] 2017-02-14 17:17
https://github.com/zammad/zammad/issues/416

**Comment by thorsteneckel** [comment] 2019-08-16 14:40
As @monotek already stated this is a duplicate of #416. If you still have questions please refer to the [community board](http://community.zammad.org/). Closing now.

**Closed by thorsteneckel** 2019-08-16 14:40 UTC
Labels: question
