### ISSUE TITLE
"Required" dates aren't actually required

### ISSUE THREAD

**Issue by HappyTepid** [zammad/zammad#1599] opened 2017-10-31 15:50 UTC
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: Zammad.org Ubuntu instructions
* Operating system: 16.04.3 LTS
* Browser + version: Chrome latest

### Expected behavior:

* It should not be possible to open a ticket if a required date field is not populated.

### Actual behavior:

* Customer can leave date field empty and submit a ticket successfully. 

### Steps to reproduce the behavior:

* Go to Admin -> Objects -> Ticket -> New Attribute
* Select "Date" as Format
* Make the attribute required for customer
* Update DB
* Login as customer and open a ticket without populating the date field

**Comment by thorsteneckel** [comment] 2017-11-01 09:09
Duplicate of #1259.

**Closed by thorsteneckel** 2017-11-01 09:09 UTC
