### ISSUE TITLE
UnprocessableEntity: Invalid email 'herzlicheglückwünsche@local'

### ISSUE THREAD

**Issue by drbw** [zammad/zammad#3303] opened 2020-11-26 16:04 UTC
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): Docker
* Operating system: CentOS
* Database + version: Postgres 9.6
* Elasticsearch version: 7.9.3
* Browser + version: Firefox 82
* Ticket: #1086130 

### Expected behavior:

* Mails with invalid addresses are either blacklisted or sanitized
* There is an accessible way to clear such object from the queue manually

### Actual behavior:

* Mail stays in queue as unprocessable
* I'm not aware of a way to remove it from the unprocessable mails

### Steps to reproduce the behavior:

* Looks like you only have to send a mail from 'herzlicheglückwünsche@local'

### Notes

* It's just spam and thus inconsequential but it could be handled better

### Logs

This is from retrying the unprocessable mails:

```
/opt/zammad/app/models/channel/email_parser.rb:133:in `rescue in process': #<Exceptions::UnprocessableEntity: Invalid email 'herzlicheglückwünsche@local'> (RuntimeError)
I, [2020-11-26T15:57:11.198863 #27827-47174494910820]  INFO -- : Setting.set('models_searchable', ["User", "Ticket", "KnowledgeBase::Answer::Translation", "Organization", "Chat::Session"])
/opt/zammad/app/models/user.rb:919:in `check_email'
I, [2020-11-26T15:57:12.474640 #27827-47174494910820]  INFO -- : Process email with msgid '<83388123-5914@mx5.example.de>'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
E, [2020-11-26T15:57:12.540140 #27827-47174494910820] ERROR -- : can't run postmaster pre filter 0015_postmaster_filter_identify_sender: Channel::Filter::IdentifySender
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
E, [2020-11-26T15:57:12.540199 #27827-47174494910820] ERROR -- : #<Exceptions::UnprocessableEntity: Invalid email 'herzlicheglückwünsche@local'>
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/78907167e988d3026f485e63983b1a68.eml, please create an issue at https://github.com/zammad/zammad/issues"
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `catch'
"ERROR: #<Exceptions::UnprocessableEntity: Invalid email 'herzlicheglückwünsche@local'>"
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
/usr/local/bundle/gems/activemodel-5.2.4.4/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
/usr/local/bundle/gems/activemodel-5.2.4.4/lib/active_model/validations.rb:339:in `valid?'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:67:in `valid?'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:84:in `perform_validations'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:52:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `block in save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:53:in `create!'
/opt/zammad/app/models/channel/filter/identify_sender.rb:160:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:56:in `run'
/opt/zammad/app/models/channel/email_parser.rb:152:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:149:in `each'
/opt/zammad/app/models/channel/email_parser.rb:149:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:118:in `block in process'
/usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:117:in `process'
/opt/zammad/app/models/channel/email_parser.rb:482:in `block in process_unprocessable_mails'
/opt/zammad/app/models/channel/email_parser.rb:481:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:481:in `process_unprocessable_mails'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `eval'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `perform'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:9:in `<main>'
	from /opt/zammad/app/models/channel/email_parser.rb:115:in `process'
	from /opt/zammad/app/models/channel/email_parser.rb:482:in `block in process_unprocessable_mails'
	from /opt/zammad/app/models/channel/email_parser.rb:481:in `glob'
	from /opt/zammad/app/models/channel/email_parser.rb:481:in `process_unprocessable_mails'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `eval'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `perform'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
	from bin/rails:9:in `<main>'
/opt/zammad/app/models/user.rb:919:in `check_email': Invalid email 'herzlicheglückwünsche@local' (Exceptions::UnprocessableEntity)
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `catch'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `block in default_terminator'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:199:in `block in halting'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
	from /usr/local/bundle/gems/activemodel-5.2.4.4/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
	from /usr/local/bundle/gems/activemodel-5.2.4.4/lib/active_model/validations.rb:339:in `valid?'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:67:in `valid?'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:84:in `perform_validations'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:52:in `save!'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `block in save!'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
	from /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `save!'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/suppressor.rb:48:in `save!'
	from /usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:53:in `create!'
	from /opt/zammad/app/models/channel/filter/identify_sender.rb:160:in `user_create'
	from /opt/zammad/app/models/channel/filter/identify_sender.rb:56:in `run'
	from /opt/zammad/app/models/channel/email_parser.rb:152:in `block in _process'
	from /opt/zammad/app/models/channel/email_parser.rb:149:in `each'
	from /opt/zammad/app/models/channel/email_parser.rb:149:in `_process'
	from /opt/zammad/app/models/channel/email_parser.rb:118:in `block in process'
	from /usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
	from /usr/local/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
	from /opt/zammad/app/models/channel/email_parser.rb:117:in `process'
	from /opt/zammad/app/models/channel/email_parser.rb:482:in `block in process_unprocessable_mails'
	from /opt/zammad/app/models/channel/email_parser.rb:481:in `glob'
	from /opt/zammad/app/models/channel/email_parser.rb:481:in `process_unprocessable_mails'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `eval'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `perform'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
	from bin/rails:9:in `<main>'
E, [2020-11-26T15:57:12.541781 #27827-47174494910820] ERROR -- : Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/78907167e988d3026f485e63983b1a68.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2020-11-26T15:57:12.541836 #27827-47174494910820] ERROR -- : Invalid email 'herzlicheglückwünsche@local' (Exceptions::UnprocessableEntity)
/opt/zammad/app/models/user.rb:919:in `check_email'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `catch'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
/usr/local/bundle/gems/activemodel-5.2.4.4/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
/usr/local/bundle/gems/activemodel-5.2.4.4/lib/active_model/validations.rb:339:in `valid?'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:67:in `valid?'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:84:in `perform_validations'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:52:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `block in save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:53:in `create!'
/opt/zammad/app/models/channel/filter/identify_sender.rb:160:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:56:in `run'
/opt/zammad/app/models/channel/email_parser.rb:152:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:149:in `each'
/opt/zammad/app/models/channel/email_parser.rb:149:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:118:in `block in process'
/usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:117:in `process'
/opt/zammad/app/models/channel/email_parser.rb:482:in `block in process_unprocessable_mails'
/opt/zammad/app/models/channel/email_parser.rb:481:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:481:in `process_unprocessable_mails'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `eval'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/runner/runner_command.rb:41:in `perform'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:9:in `<main>'
Failed: NonZeroResultCode: [ssh-exec] Result code: 1
```

Source:

```
Return-Path: <>
Received: from mx5.example.de (192.168.10.24 [192.168.10.24])
        by webmail.example.de (12.3.0 build 3 RHEL7 x64) with ESMTP (SSL) id 202011261532363791
        for <order@example.de>; Thu, 26 Nov 2020 15:32:36 +0100
X-Filtered: header-modified
Message-ID: <83388123-5914@mx5.example.de>
Received: from eastus.cloudapp.azure.com ([52.224.53.45])       by mx5.example.de
        with ESMTP      for order@example.de;        Thu, 26 Nov 2020 15:32:34 +0100
Date: Thu, 26 Nov 2020 14:22:46 +0100
Mime-Version: 1.0
To: HerzlicheGlückwünsche
From: =?UTF-8?b?SGVyemxpY2hlR2zDvGNrd8O8bnNjaGU=?= <HerzlicheGlückwünsche>
Subject: ◔͜͡◔Wir haben eine Überraschung für GMX-Kunden◔͜͡◔
Content-Type: text/html; charset="UTF-8"
X-Spam-Status: No, hits=2.89 required=6.20 tests=URIBL_BLOCKED=0.00,MIME_HTML_ONLY=0.10,HTML_MIME_NO_HTML_TAG=0.64,HTML_MESSAGE=0.00,HTML_IMAGE_ONLY_04=0.34,URI_NOVOWEL=0.50,MSGID_FROM_MTA_HEADER=0.00,TO_MALFORMED=0.10,SUBJ_ILLEGAL_CHARS=1.10,SUBJECT_NEEDS_ENCODING=0.10
        version=3.3.2
X-Spam-Level: **
X-Spam-Checker-Version: SpamAssassin 3.3.2 (1.1) on webmail.example.de
X-CTCH: RefID="str=0001.0A090212.5FBFB8A9.0061,ss=3,sh,re=0.000,recu=0.000,reip=0.000,cl=3,cld=1,fgs=0"; Spam="Bulk"; VOD="Unknown"

<p><a href="https://x3.cx/sAqIt#PNuzKVnxWfLMXoVYfWJR"><img style="display: block; margin-left: auto; margin-right: auto;" src="https://PNuzKVnxWfLMXoVYfWJR.imgur.com/SK0X2H4.jpg" alt="" /></a></p>
<p style="text-align: center;"><a href="https://x3.cx/ajX77#69131223791654646318""><img src="https://PNuzKVnxWfLMXoVYfWJR.imgur.com/szXsQHN.jpg" alt="" /></a></p>
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-11-26 16:14
This may indirectly be relevant to:
* https://github.com/zammad/zammad/issues/2402
* https://github.com/zammad/zammad/issues/2401

Right now I'm not sure if this is really bug.
Technical the alias is incorrect - thus it's unprocessible.

We're not responsible for filtering spam (that's the MTAs job :-) ) and automatic sanitation.. well.. not too sure.
The issue here is that we can't just drop those mails, because I've also seen real customers producing above situations already.

**Comment by drbw** [comment] 2020-11-26 16:24
Why is the alias incorrect?

https://tools.ietf.org/html/rfc6531
   9.   The reverse-path and forward-path of the SMTP MAIL and RCPT
        commands are extended to allow Unicode characters encoded in
        UTF-8 in mailbox names (addresses).

The address as a whole is incorrect AFAIK since it doesn't contain a domain name but Zammad does compensate for that by adding @local.

**Comment by MrGeneration** [comment] 2020-12-07 11:04
Ufffff nevermind me. 
Anyway...
> https://tools.ietf.org/html/rfc6531
> 9. The reverse-path and forward-path of the SMTP MAIL and RCPT
> commands are extended to allow Unicode characters encoded in
> UTF-8 in mailbox names (addresses).

`From: =?UTF-8?b?SGVyemxpY2hlR2zDvGNrd8O8bnNjaGU=?= <HerzlicheGlückwünsche>`

While your display name is encoded correctly, the alias within the brackets contains umlauts. These are only available / support by supporting mtas (I found this information here: https://stackoverflow.com/questions/15121359/are-international-characters-e-g-umlaut-characters-valid-in-the-local-part-of )

Here's the RFC link:
https://tools.ietf.org/html/rfc5336#section-3.2

----

Now to the issue itself.
Trying to reprocess unprocessible mails is handled here: https://github.com/zammad/zammad/issues/1970#issuecomment-387786505
However, in your case (because it's just spam too) it's save to remove the eml file from your temporary directory. (`tmp/unprocessible_mail/`).

I do agree that Zammad *should not* add `@local` parts.
If this is mandatory, Zammad should learn to set them on the right part correctly and allow `@local` if needed.

Currently I'm not sure how and if local only aliases should work and be supported.
I know too little for these use cases to provide a good solution that works in general.

**Comment by drbw** [comment] 2020-12-07 11:16
Wait, removing the file is enough? That's a bit... surprising, but great to know, thanks! Finally back to 'healthy' status now. As for the handling of mails like this, there's probably no clear-cut answer on how to do so "properly". At least you're now aware of a specific error case - the interpretation is up to you.

**Comment by MrGeneration** [comment] 2020-12-07 11:20
> Wait, removing the file is enough?

It's a temporary directory, removing it will cause Zammad to re-add directories whenever needed. It won't nuke the instance as such.

**Comment by MrGeneration** [comment] 2022-01-17 15:49
```
...
#<Exceptions::UnprocessableEntity: Invalid email 'löschen@domain.tld'>
...
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_355a7ffe95" on table "users")
DETAIL:  Key (id)=(132) is still referenced from table "users".
```

This issue also draws data privacy functions being useless in case a user that created or updated an user with said email address is referenced. This was possible in earlier Zammad days (at least for user creation by agents / admins) and may indirectly backfire on existing instances.

**Comment by mantas** [comment] 2022-09-28 13:17
Looks like this is already fixed with https://github.com/zammad/zammad/commit/8780373fdd978cd5d43f76709dcc20445cc3fab3

```ruby
[3] pry(main)> EmailAddressValidation.new('löschen@domain.tld').valid?
=> true
[4] pry(main)> EmailAddressValidation.new('herzlicheglückwünsche@local').valid?
=> true
```

Closing as duplicate of https://github.com/zammad/zammad/issues/4151

**Closed as completed by mantas** 2022-09-28 13:17 UTC
Labels: bug, duplicate, channel, verified, prioritised by payment
