### ISSUE TITLE
Can't update zammad anymore

### ISSUE THREAD

**Issue by Hirbod** [zammad/zammad#1308] opened 2017-07-28 01:05 UTC
Did you guys change something? It stopped working since 3 days

W: Fehlschlag beim Holen von https://deb.packager.io/gh/zammad/zammad/dists/jessie/stable/binary-amd64/Packages  Hash-Summe stimmt nicht überein

E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

Also tried with "apt upgrade --fix-broken"

**Comment by jaykijay** [comment] 2017-07-28 06:30
Hi, this is a duplicate of #1294 which is solved.

**Comment by martini** [comment] 2017-07-28 07:21
Hi @Hirbod 

thanks for feedback. As @jaykijay wrote, it's already known. You need to update the Zammad repo file.

We also added the information to https://zammad.org and to the docs https://docs.zammad.org/en/latest/appendix-repo-file.html

Any feedback is welcome!

 -Martin

**Closed** 2017-07-28 07:23 UTC
Labels: documentation
