### ISSUE TITLE
Changing organisation of user does not change their tickets

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4706] opened 2023-07-04 17:05 UTC
### Used Zammad Version

6.0

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 11
- Database + version:  postgresql
- Elasticsearch version: 7.17.11
- Browser + version: any

### Actual behaviour

When changing the organisation of a user, the tickets do not change.

### Expected behaviour

When changing the organisation of a user, the tickets will follow that change.

### Steps to reproduce the behaviour

Install Zammad from the package with the latest stable branch. Create a second organisation, and change the user "Nicole Braun" to another organisation. Check the "Welcome to Zammad"-ticket, it is still assigned to the "Zammad Foundation"-organisation.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment] 2023-07-12 13:04
@YetAnotherGerrit I'm not able to reproduce the problem on a stable installation. 

Maybe it was a different situation. Can you give me some more information otherwise I would close the issue.

**Comment by t-shehab** [comment] 2023-07-13 14:42
@YetAnotherGerrit,

I can confirm that this is not reproducible following your steps to reproduce. If I do exactly what you describe, Nicole's ticket changes organizations just fine.

**Closed as not planned** 2023-08-03 06:40 UTC
Labels: can't reproduce
