### ISSUE TITLE
Wrong dates on synced calendars

### ISSUE THREAD

**Issue by edneymatias** [zammad/zammad#2229] opened 2018-09-07 21:19 UTC
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: PostgreSQL 9.6.10
* Elasticsearch version: 5.6.11
* Browser + version: Chrome 68.0.3440.106 (Official version) 64 bits

### Expected behavior:

* To sync regional holiday calendar with correct holiday dates. 

### Actual behavior:

* Holidays are 1 day ahead of actual date. Today is Independence day in Brazil, 09/07/2018. Synced calendar is telling me this holiday was yesterday. It also shows me Christmas at 12/24/2018 and new year's day at 12/31/2018, for example.

![image](https://user-images.githubusercontent.com/22533602/45242748-97cf9580-b2c7-11e8-9698-ec8e0d7a51a1.png)

### Steps to reproduce the behavior:

* Add a new calendar using Google Calendar. I tried with Brazil, Argentina and United States, all presented the same issue. Then I checked if Google Calendar for Brazil holidays was correct using this source https://calendar.google.com/calendar/ical/pt.brazilian%23holiday%40group.v.calendar.google.com/public/basic.ics and a third part application. Everything was presented in the correct date. For example, Christmas is correctly listed:

```
DTSTART;VALUE=DATE:20181225
DTEND;VALUE=DATE:20181226
DTSTAMP:20180907T210214Z
UID:20181225_60o30chncko30c1g60o30dr568@google.com
CLASS:PUBLIC
CREATED:20140109T111906Z
DESCRIPTION:
LAST-MODIFIED:20140109T111906Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Natal
TRANSP:TRANSPARENT
END:VEVENT
```

I also checked my server timezone, but it also is correct.

```bash
odontolifeodontologia@ajuda-1:~$ sudo timedatectl
      Local time: Fri 2018-09-07 17:55:46 -03
  Universal time: Fri 2018-09-07 20:55:46 UTC
        RTC time: Fri 2018-09-07 20:55:46
       Time zone: America/Sao_Paulo (-03, -0300)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
odontolifeodontologia@ajuda-1:~$ 
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2018-09-14 08:35
Hi,

I tried to reproduce this bug and cannot.
I chose Brazil as calendar and chose a second calender with the source you provided. I checked on most of the entries and they are 100% identical.

Christmas eve is, at least in Germany, at the 24th of December.
Zammad shows all entries correct. Your problem is that your instance shows the dates **one day behind**.

I tried this at a hosted and my pivate instance. Both instances are up to date.

**Comment by edneymatias** [comment] 2018-09-14 12:05
Hi!

Zammad is showing me Christmas Eve at 23th and Christmas at 24th of December. New year's day is listed at 31th of December. 

I also tried to manually add dates to a new calendar. I entered 12/25/2018 and Zammad stored 12/24/2018.

When I pick today, for example:

![image](https://user-images.githubusercontent.com/22533602/45549249-8f161c80-b7fd-11e8-9d48-b8cedc31793f.png)

... and hit add

![image](https://user-images.githubusercontent.com/22533602/45549265-9f2dfc00-b7fd-11e8-90b4-826f6f09e15c.png)


I'm running my installation on a Google Cloud instance.

Thank you for your insights.

**Comment by thorsteneckel** [comment] 2018-09-19 09:13
Hi @edneymatias - Thanks for the comprehensive writeup. I'm pretty sure this has something to do with using a Google Cloud instance for hosting. We can't give support for that. Please try the same with one of our [free (trial) hosted instances](https://www.zammad.com/getting-started). Please let us know the name of the instance if you can reproduce the issue there. Otherwise it's a support case for our [commercial service](https://www.zammad.com/pricing#selfhosted) or you can head over to the [community board](http://community.zammad.org/) and get help from the great people over there (including some of the Zammad staff). Closing now.

**Comment by edneymatias** [comment] 2018-09-19 12:30
Hi there! 

I just tried on a hosted instance just to get the same results. I just started an instance and with default setup went straight into the calendar section. I tried to add a holiday to a new calendar:

![image](https://user-images.githubusercontent.com/22533602/45753154-4344e800-bbee-11e8-8401-5ee77e3f6c6c.png)

...hit add

![image](https://user-images.githubusercontent.com/22533602/45753175-5657b800-bbee-11e8-8054-1bdc694a7177.png)

Instance name is ajudalife.

Thank you!

**Comment by thorsteneckel** [comment] 2018-09-19 12:31
Thanks for your fast reply! We'll have a look 👍

**Comment by rlue** [comment] 2018-10-22 09:36
@edneymatias, thanks so much for your patience. I'm trying to get to the bottom of this problem, but I need your help to reproduce the issue.

It's very strange, but I can't reproduce it either. Here are the steps I took:

1. Register a new instance on https://www.zammad.com/getting-started
2. Go to the "Calendars" admin settings panel
3. Click "New Calendar"
4. Fill in the new calendar form:
   * Pick any name.
   * Set time zone to **Sao Paulo**.
   * Select "Subscribe to iCalendar feed": https://calendar.google.com/calendar/ical/pt.brazilian%23holiday%40group.v.calendar.google.com/public/basic.ics
5. Hit "Submit"

This is the calendar I got:

![screenshot_20181022_170700](https://user-images.githubusercontent.com/12194123/47285448-8b0bc480-d61d-11e8-9335-6041aec8020a.png)

(You may notice that I also tried changing the language to Brazilian Portuguese, just to eliminate any other variables.)

If you followed the exact same steps, I can only imagine two possible differences:

1. ~~You're accessing Zammad from an IP in Brazil, whereas I'm accessing Zammad from an IP in Taiwan. Maybe (just maybe) there's some logic in Zammad that tries to adjust the date according to your local timezone, and it guesses your local timezone according to either IP geolocation or some browser user-agent data?~~

   **EDIT:** I just tried Steps 3–5 again on a VPN from Brazil, and it's still working normally. Here's a screenshot indicating that the VPN was working:

   ![screenshot_20181022_175311](https://user-images.githubusercontent.com/12194123/47287115-b72a4400-d623-11e8-8e3f-2278aeee91b5.png)

2. The issue was somehow related to Daylight Savings Time, and now that DST has passed, the problem is no longer reproducible. (I'm thinking this is probably not the case, since @MrGeneration was also unable to reproduce the problem.)

Do you see any other differences between your test case and mine?

**Comment by thorsteneckel** [comment] 2018-10-22 10:45
Hi @edneymatias - in addition to what @rlue wrote in his last comment: Could you please check if the time zone related issues in [this list](https://github.com/zammad/zammad/issues/assigned/mantas) apply to your system, too?

**Comment by edneymatias** [comment] 2018-10-23 11:54
Hi @rlue!

I tested again on my instance and also created a new instance on https://www.zammad.com/getting-started. The results are the same. What makes me think mybe it's related to my desktop or browser.

Right now, my timezone is set to Brasilia time which an alias for Sao Paulo and clock is set to automatic update:

![image](https://user-images.githubusercontent.com/22533602/47357936-a36ff380-d69e-11e8-8da3-452dbbe54c93.png)

The instance on zammad.com is https://lifeajuda.zammad.com/, feel free to access it. This is the test calendar as I see it:

![image](https://user-images.githubusercontent.com/22533602/47357994-d2866500-d69e-11e8-822f-57d511840568.png)

I checked my country and I'm in Brazil:

![image](https://user-images.githubusercontent.com/22533602/47358054-03669a00-d69f-11e8-8acc-c03362415ce7.png)

I recorded adding daters manually. The results were equal on my instance as well on zammad.com instance. You can see it here https://edneymatias.tinytake.com/sf/MzAyMjQ3M185MDYxODk0.

@thorsteneckel about the issues list:

- https://github.com/zammad/zammad/issues/2274 - confirmed
- https://github.com/zammad/zammad/issues/2169 - confirmed. Here's a print of the e-mail I received:

![image](https://user-images.githubusercontent.com/22533602/47358547-5db42a80-d6a0-11e8-8b54-551d828a0fb6.png)

My instance is set to pt-br:

![image](https://user-images.githubusercontent.com/22533602/47358717-f6e34100-d6a0-11e8-9200-f2ea472150b4.png)

- https://github.com/zammad/zammad/issues/2089 - can't test
- https://github.com/zammad/zammad/issues/2085 - can't test
- https://github.com/zammad/zammad/issues/1589 - can't test
- https://github.com/zammad/zammad/issues/457 - confirmed. I registered this on the community https://community.zammad.org/t/different-server-and-rails-timezone/1443. I don't now all the implications of what i did but I can correctly schedule jobs now. This didn't solve other time related problems.

- https://github.com/zammad/zammad/issues/366 - it's not related but I can confirm it would be great!

I think tha's it.

If you need, you can ask.

Matias

**Comment by rlue** [comment] 2018-10-24 02:35
> The instance on zammad.com is https://lifeajuda.zammad.com/, feel free to access it.

Actually, this is a really smart way to diagnose what's going on – to see whether it's a display issue or whether the wrong dates are actually being saved to the database during import.

Can you give me a username and password for your lifeajuda public instance? You can also try logging into _my_ public instance:

<dl>
<dt>URL</dt>
<dd>https://lgcwyanp.zammad.com</dd>
<dt>Username</dt>
<dd>lgcwyanp@sharklasers.com</dd>
<dt>Password</dt>
<dd>edneymatias</dd>
</dl>

Here's a screenshot of the correct dates showing on this instance.

![screenshot_20181024_102512](https://user-images.githubusercontent.com/12194123/47402265-47c56900-d777-11e8-9e08-a9f3ba1b6524.png)

Which dates do you see when you log in – the right ones, or the wrong ones? If you're seeing the right dates, then that means there's something wrong with the calendar import process. If you're seeing the wrong ones, then there's something wrong with the display logic.

---

Another way to diagnose the same issue would be to check the output of the following command on your local installation (assuming that your broken calendar is named "Brazil":

```
$ zammad rails runner "pp Calendar.find_by(name: 'Brazil').public_holidays"
{"2017-10-28"=>
  {"active"=>true,
   "summary"=>"Dia do Servidor Público",
   "feed"=>"cfdb13e01d7dfa470973071f496d265e"},
  ... }
```

You should see a list of entries like the one above. If the dates are incorrect here, then we've got an import problem; if they're correct here but incorrect in the browser, then it's a display problem.

**Comment by edneymatias** [comment] 2018-10-24 11:35
hi @rlue 

Here is the credentials:

login: matias@odontolifeodontologia.com.br
password: rlue

This is how I see the holydays in your instance:

![image](https://user-images.githubusercontent.com/22533602/47427354-725af600-d766-11e8-9715-20febfd33c08.png)

They are wrong!

This is some entries from the command ```zammad run rails r  "pp Calendar.find_by(name: 'Brasil/Paraná').public_holidays"```

```
 "2019-12-24"=>
  {"active"=>true,
   "summary"=>"Christmas Eve (from 2pm)",
   "feed"=>"b507ea2e6441246fcc7f51d2d7550484"},
 "2019-12-25"=>
  {"active"=>true,
   "summary"=>"Christmas Day",
   "feed"=>"b507ea2e6441246fcc7f51d2d7550484"},
 "2019-12-31"=>
  {"active"=>true,
   "summary"=>"New Year's Eve (from 2pm)",
   "feed"=>"b507ea2e6441246fcc7f51d2d7550484"}}
```

As you guessed they are correct! So we got a display problem!

**Comment by thorsteneckel** [comment] 2018-10-24 12:05
Hi @edneymatias and @rlue - thanks a lot for figuring things out. This is actually a duplicate/side effect of the other issues that @edneymatias verified earlier. @mantas has already spend some time working on the underlying issue so I assigned this one to him and he will fix them all in one go 💪

**Comment by kwoodVisions** [comment] 2018-11-28 21:52
Any updates on when this will be listed as "In Progress"?

**Comment by thorsteneckel** [comment] 2018-11-29 07:38
Hi @kwoodVisions - our focus is currently on the knowledge base. It's done when it's done

**Comment by kwoodVisions** [comment] 2018-11-29 18:00
That's fine - thank you for the response.  I'll post some updates for the knowledge base in regards to spelling/corrections in the documentation and will add what I can to help enhance it.

So far, great software - I may end up digging into the code to see if I can offer any assistance there.

**Comment by kwoodVisions** [comment] 2018-11-30 21:31
I'm interested in looking at the code for this page and how I can help improve it.  I'm assuming it's the javascript that's the issue, or perhaps more specifically the coffeescript.

Besides calendar.coffee, are there any other files you can point me to that may deal with the calendars so I can review to further investigate this issue?

**Comment by davidcmoody** [comment] 2019-07-05 16:34
I have the same issue happening, an America/New_York timezone and all the dates shown are 1 day prior to the actual holiday.

**Comment by mantas** [comment] 2019-07-05 16:35
@davidcmoody fix is coming soon. Either in next or next-next release.

**Closed as completed** 2019-10-21 11:04 UTC
Labels: bug, verified, frontend
