### ISSUE TITLE
Can't save Organization name

### ISSUE THREAD

**Issue by pyrog** [zammad/zammad#3340] opened 2020-12-17 13:12 UTC
### Infos:

* Used Zammad version: https://osm-fr.zammad.com
* Browser + version: Safari

### Expected behavior:

* Add the Organization to a user profile

### Actual behavior:

* The value is not saved

### Steps to reproduce the behavior:

* Edit i.e. https://osm-fr.zammad.com/#user/profile/19
* Add Organization
* Press Submit
* Reopen this user profile, the Organization is empty

See better? description https://github.com/zammad/zammad/issues/3340#issuecomment-747478022

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-12-17 13:15
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by pyrog** [comment] 2020-12-17 14:01
Sorry Marcel, could you reopen it : the first part is a real bug 😉 

It is **not possible to save the Organization name**.

**Comment by MrGeneration** [comment] 2020-12-17 14:07
Please edit the article to describe "the real bug" and also provide a screencast so we can understand better.
I'm still sure that this is a technical question though.

**Comment by mantas** [comment] 2020-12-17 14:09
@MrGeneration I was able to reproduce "the real bug". I'm not sure if this is a bug or just misleading UX though. User edit form has auto-complete field to pick an existing organization. But it looks like some users expect to create new organizations in here.

**Comment by pyrog** [comment] 2020-12-17 14:09
Done. I keep the following of the issue here 😉 

### Additional request:

Firstname and Lastname are mandatory but in practice I want to send an email to the contact address of the company.
contact@sauvetoncommerce.fr in this case.

So I don't want to fill these 2 fields.

Also, usually the user/company is new, so **I would like to create it automatically** when adding a new email in the customer field (similar to creating automatically a customer by sending a email to zammad).

Currently, I must select "Create a new customer" in the list, but I can't save it because the first and last names are empty.

**Comment by pyrog** [comment] 2020-12-17 14:11
> I'm not sure if this is a bug or just misleading UX though.

In the user point of view, this is the same thing 😉

**Comment by mantas** [comment] 2020-12-17 14:12
@pyrog although this is purely a question, I'll answer here. When creating a new ticket, you can just write `email@example.org` in the customer field and create the ticket. A new empty user (with email only) will be created.

**Comment by pyrog** [comment] 2020-12-17 14:15
Thank you @mantas 😃. I tested this case before writing this issue but I didn't succeed.

I will retry later.

**Comment by MrGeneration** [comment] 2020-12-17 14:31
Can we please stop mixing things and issues? This is getting messy and will cause only half of issues to be fullfilled.
I'm afraid that this has happened in the past.

This is still a technical question which is why I'll be closing this issue, sorry.
You have to create the organization before hand. If it does exist you'll have to actively select it and submit after that.

That's, at least right now, a design decision that may not be straight forward.

**Closed as completed by MrGeneration** 2020-12-17 14:31 UTC
Labels: question

**Comment by pyrog** [comment] 2020-12-17 14:40
@MrGeneration this is a bug ! (not fixed yet)
Mantas as reproduced it 😉 

1. Open https://osm-fr.zammad.com/#user/profile/19
2. Menu **Action** -> **Edit**
3. Field Organisation : I type "Sauve ton commerce"
4. Press button **Submit**

Result : the organization field is empty 😞

**Comment by MrGeneration** [comment] 2020-12-17 14:41
* Field Organisation : I type "Sauve ton commerce"
* Press button Submit

You skipped the "select organization Zammad provides for selection" part.
This is a technical question and normal behavior as of now.

The same will happen within the LDAP integration if you select e.g. roles or groups. 
This is a design decision.

**Comment by pyrog** [comment] 2020-12-17 14:53
> You skipped the "select organization Zammad provides for selection" part.

Probably, but I got no warning.

> This is a technical question and normal behavior as of now.

Sorry, it's not "normal".

If I create a new ticket and add a new customer, the list display in green "Create a new customer":
<img width="50%" alt="Create a new customer" src="https://user-images.githubusercontent.com/2158081/102502476-efe8cb00-407e-11eb-9369-56554d6b38ab.png">

So, when typing a new organization, it should also display in green "Create a new organization", don't it ?

But, I'am agree now, it seem to be a UX **issue** 😃

**Comment by MrGeneration** [comment] 2020-12-17 14:57
Yes and no.
The reason why Zammad doesn't provide the "new organization" dialogue is because this is not available to normal agents.

This adds extra complexity.
In my opinion this is a feature request, not a bug.

**Comment by pyrog** [comment] 2020-12-17 15:05
Feature request or bug ? 
The eternal question in development. I ear this 30 years ago 😄

When a customer send a email to create a ticket, **Zammad is excellent** 😃 
It create a new ticket and a new customer.

But when a new ticket is created "internally" for a new customer/organization, something is missing 🤔

**Comment by MrGeneration** [comment] 2020-12-17 15:09
> But when a new ticket is created "internally" for a new customer/organization, something is missing 🤔

I do get get your point, but I'm afraid this is how it is right now.
As this is not something that "broke" and was working before, this is a feature / functionality that would have to be added. This is why it's an feature request / enhancement. We don't use github for feature requests any longer. This is because we also have to measure on how needed a feature that's requested really is. I hope that you can understand that.

As I mentioned, this is a permission question - have a look at `admin.organization`.
(That's the technical question part)
https://admin-docs.zammad.org/en/latest/manage/roles/admin-permissions.html

**Comment by pyrog** [comment] 2020-12-17 15:25
> As I mentioned, this is a permission question 

In the preset case, I'am an administrator and the UX design is not homogenous and clear.
(I repeat, the list should display in green "Create a new customer")

The choice to limit Organization creation to admins only is discutable (and will be in a feature request).
The choice to have user name mandatory is discutable too. (This could be set in settings)
