### ISSUE TITLE
Customer role ticket submission all groups blank

### ISSUE THREAD

**Issue by akaheidy** [zammad/zammad#4981] opened 2023-12-13 11:36 UTC
### Used Zammad Version

6.2.0-1702303938.81e0c1fd.jammy

### Environment

- Installation method: Source
- Operating system: Ubuntu 22.03
- Database + version:  postgresql 14
- Elasticsearch version: 7.17.15
- Browser + version: All browser affected

### Actual behaviour

After an update I did yesterday (just a normal apt update / apt upgrade) when a customer try to open a ticket with the web page it has problem selecting a ticket group. I tried to run "zammad run rails r “Setting.set(‘customer_ticket_create_group_ids’, )” after seeing a github thread but it didn’t solve the question.
Here a link of a ticket of an user in zammad community: https://community.zammad.org/t/customer-role-ticket-submission-all-groups-invisible/12826/4
Here is a screenshot:
![Error](https://github.com/zammad/zammad/assets/152916641/82a2f9a0-d2bd-4318-ac72-ac81887290c1)

### Expected behaviour

Let customer choose in wich group open a ticket

### Steps to reproduce the behaviour

Update zammad to the latest version

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by pmalsenz** [comment] 2023-12-13 12:29
Same problem here. Only difference is the server OS.

Our servers (1x Zammad App, 1x PostgreSQL, 1x Elasticsearch CE) are running with Debian 11.

It has been posted in the community forum too [(Customer role ticket submission all groups invisible)](https://community.zammad.org/t/customer-role-ticket-submission-all-groups-invisible/12826)

**Comment by fliebe92** [comment] 2023-12-13 12:31
Hey @akaheidy and thanks for your report. Could you please add proper steps how to reproduce the reported behavior? Thanks a lot.

**Comment by akaheidy** [comment] 2023-12-13 13:13
Hey @fliebe92 thank you for your comment.
I don't really know what are the proper steps to reproduce the issue. But I can try to be more specific:
- Yesterday I decide to update my linux vm using "sudo apt update" and after "sudo apt upgrade"
- I saw that it downloaded also an update for zammad so I was more than happy to get the last update. Just to be clear I already had the 6.2.0 version but with a different numbers after the "-"
- Once updated all I tried to open a new ticket with a customer account I have to make tests and when I try to select a group where I can open a ticket it gives me the drop down menu blank (as in the screenshot)
- Than I tried different browser also clearing the cache but it didn't change
- Since I have many groups i tried to lower the numbers of groups you select with the web interface but nothing changed.
- I also tried to run the command I specified because I saw an issue solved with it here in github

I hope I have been clear enough, if I wasn't feel free to ask
I also apologize for my english since it isn't my first language :)

**Comment by plrlp-pmueller** [comment] 2023-12-13 13:20
As already mentioned here [Customer role ticket submission all groups invisible](https://community.zammad.org/t/customer-role-ticket-submission-all-groups-invisible/12826) , we're having the same problem.

Only difference is the server OS. We're running our three servers with Debian 11 (1x Zammad App, 1x PostgreSQL, 1x Elasticsearch).

Steps for our setup to reproduce the behaviour:

1. Login as user with the customer role
2. Create a new ticket via web form (by clicking on the green plus symbol in the lower left)
![image](https://github.com/zammad/zammad/assets/38287391/15258529-8e6a-4f75-bdba-aa9412ab3394)

3. Select a group for the ticket, before/after entering a title and body (doesn't matter to reproduce this problem)

It's possible to select one of the emtpy group entries. After entering a title I can submit the ticket to the hopefully ;-) correct group.

**Comment by plrlp-pmueller** [comment] 2023-12-13 14:01
Just've seen, that the version mentioned by @akaheidy is a more recent one than our installed Zammad version.
We're still on Zammad **_6.2.0-1702037528.0cb24140.bullseye_**

**Comment by akaheidy** [comment] 2023-12-20 09:00
Good morning, today I did a sudo update && upgrade and i saw that zammad downloaded a new version the **6.2.0-1702975436.87754a02.jammy**. Unfortunately this didn't solve the issue :(

**Comment by dvuckovic** [comment] 2023-12-21 13:27
Confirmed, the issue is present on fresh systems as well, provided the initial route is `/#customer_ticket_new`. Changing the route to this from another masks the issue, and any subsequent form changes (i.e. change of the priority) will "fix" the group list.

The issue stems from incomplete assets data for group objects (more specifically, attribute `name_last` is missing). Fix is incoming!

**Closed as completed** 2023-12-21 14:24 UTC
Labels: bug, verified, ticket: create

**Comment by dvuckovic** [comment] 2023-12-21 15:27
@akaheidy Perhaps you can try upgrading to **6.2.0-1703171501.0e7f99e1.jammy** and report if it now works for you.

@plrlp-pmueller Similarly, please try with **6.2.0-1703171501.0e7f99e1.bullseye** and report back.

Thank you!

**Comment by ssiersdorfer** [comment] 2023-12-22 06:54
With the latest Update i installed this Morning it's working again.

**Comment by akaheidy** [comment] 2023-12-22 08:44
Just updated, now it works perfectly!
Thank you!
