### ISSUE TITLE
Factual Macro title shown in ticket update dropdown

### ISSUE THREAD

**Issue by delphi-sucks** [zammad/zammad#3266] opened 2020-11-05 08:27 UTC
### Infos:

* Used Zammad version: 3.5.0-1603788665.5a776fce.xenial
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.7 LTS
* Database + version: MySQL 5.7.32-0ubuntu0.16.04.1
* Elasticsearch version: 7.9.2
* Browser + version: Vivaldi 3.4.2066.90

### Expected behavior:

When dragging a ticket to the upper screen for macro execution, the macros are translated to the current used language.

### Actual behavior:

The macros aren't translated.

### Steps to reproduce the behavior:

1. Use a language other than english (which has the macros translated)
2. Drag a ticket in the overview to the top for macro execution
![image](https://user-images.githubusercontent.com/17913239/98216039-d49b8380-1f48-11eb-91ce-dad1a29d5fda.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment] 2020-11-05 09:20
Hi @delphi-sucks ,

Those are names of macros as set in database. You can rename them in Settings > Macros. Unfortunately there's no way to set different names in different UI languages.

Closing since this is not a bug and works as intended.

**Comment by delphi-sucks** [comment] 2020-11-05 09:30
Hi @mantas,

your statement is in contradiction to the current behaviour in a ticket:
![image](https://user-images.githubusercontent.com/17913239/98222513-37911880-1f51-11eb-968d-00bd5f15cfa0.png)

Here you can see, that the macros do get translated to different UI languages.
So either you are right and it is wrong that the macros do get translated in the ticket or it is a bug, that macros don't geht translated in the drag&drop action.
Either way, currently there are two different ways of displaying the macro-names, which is wrong.

**Comment by mantas** [comment] 2020-11-05 09:32
Hi @delphi-sucks ,

Interesting finding! I was sure it's not translated elsewhere. I totally agree it has to consistent.

**Closed as completed** 2020-11-09 10:36 UTC
Labels: bug, UX/UI, verified
