### ISSUE TITLE
Macros sorted differently after update to 3.3.x

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2993] opened 2020-03-27 15:49 UTC
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* After updating Zammad the macro order is not changed.

### Actual behavior:

* Macro order is changed.
![image](https://user-images.githubusercontent.com/44224243/77773927-94873080-704a-11ea-9a87-92d08106d378.png)

* Should be and was in the defined order:
![image](https://user-images.githubusercontent.com/44224243/77774079-c8625600-704a-11ea-9115-5adad76889ec.png)

It is not a horrible but but it screws with my muscle memory as I am now closing tickets left and right instead of assigning them to me :/

### Steps to reproduce the behavior:

* Update Zammad from 3.0.x to 3.3.x with macros already active

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment] 2020-03-27 16:08
Hi @SEGGER-NV,

Thank you for reporting this. This is... an interesting issue :)

Note to self: commit that introduced this change https://github.com/zammad/zammad/commit/feac4bb938082511716d5eac1fe9d3eff60d1aa1#diff-569f1d8466b8413253825f028414f3fbR44

**Comment by SEGGER-NV** [comment] 2020-03-30 07:28
Yeah it is odd indeed. I first thought I was going mad by clicking the wrong macro all the time.
Any idea for a workaround? Can the order somehow be impacted, even if it means to adjust the naming scheme slightly?

**Comment by MrGeneration** [comment] 2020-03-30 07:35
Sorry but I do believe that this is a duplicate of https://github.com/zammad/zammad/issues/2698 and thus should have affected you starting with Zammad 3.1 as far as I'm aware.

Mantas might correct me here and reopen the issue, if it's technically not connected. Up to now you currently cannot change the Macro order sadly. :(

**Closed as completed by MrGeneration** 2020-03-30 07:35 UTC
Labels: duplicate

**Comment by mantas** [comment] 2020-03-30 07:51
@SEGGER-NV , currently order is Z-A by name. Quick workaround would be to add descending prefixes 9/8/7 or C/B/A.

@MrGeneration looks like it's same issue. And that older one has more details as well as lists more affected places.
