### ISSUE TITLE
Freshdesk import interrupted

### ISSUE THREAD

**Issue by mvbonin-CORE** [zammad/zammad#5090] opened 2024-03-18 08:10 UTC
### Used Zammad Version

6.2

### Environment

- Installation method: docker-compose
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu server 22.04.4
- Database + version: postgres:15.3-alpine
- Elasticsearch version: bitnami/elasticsearch:8.8.0
- Browser + version: Chrome 122

### Actual behaviour

We have used Freshdesk for years and have quite a big set of data there. Now we want to import it to Zammad.

I tried importing by using console and the frontend. Both failed.

When using the frontend it runs for some time but when doing the tickets, after some time I get the Error:

![image](https://github.com/zammad/zammad/assets/163826276/53daf209-b975-4a1e-a022-0c2a9998b388)

Somehow the background worker process doesn't run anymore. I tried updating to the latest Image but the error persists.

When using the console, after some Time I get the Error:

undefined local variable or method `e' for Sequencer::Unit::Import::Freshdesk::Request:Class\n\n rescue e\n ^

### Expected behaviour

I expect the Import to take its time but finish at some point. 
If a background-worker-process crashes, it should just restart and pick up, where it left..

### Steps to reproduce the behaviour

Install version 6.2 with docker-compose
Start the freshdesk Import of a big freshdesk instance.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2024-03-18 08:59
Hi @mvbonin-CORE. Do you have some logs with a complete traceback? This might be helpful for us. Thx!

**Comment by mvbonin-CORE** [comment] 2024-03-18 10:20
This is the only log i found for now.
If you need another one, I'm happy to provide it too.

I think a lot of this is just my browser connecting.
At the beginning before the import was started, I had to put the details in twice or so.

docker logs -f NAME

[zammadlog.log](https://github.com/zammad/zammad/files/14634630/zammadlog.log)

**Comment by fliebe92** [comment] 2024-03-18 10:23
Thanks for the file, but there's no information about the error.

**Comment by mvbonin-CORE** [comment] 2024-03-18 10:39
Which file/log would you need?

**Comment by fliebe92** [comment] 2024-03-18 10:41
Interesting might be the log of `zammad-scheduler`.

**Comment by dominikklein** [comment] 2024-03-21 08:28
>  If a background-worker-process crashes, it should just restart and pick up, where it left.

Currently, the import can not be restarted/continued. This is by design because of some limitations in the implementation (with the console it should be possible to start an important again, but it will start from the beginning).

Is it directly failing when tickets are started or after some time? Normally we have no problems with the imports, also with more data. From how much data are we talking?

**Comment by mvbonin-CORE** [comment] 2024-03-22 11:12
> Interesting might be the log of `zammad-scheduler`.

The log of that is really long and I had to delete some warnings (String too long...) because they contained data from our tickets.

https://public.ridecoremedia.com/s/Nr46TS87LNsfmEX

How many there are is hard to say. On "All Tickets" from all time, freshdesk shows about 40.000 but there is an archive that should be imported too and doesn't show the count.

I think there should be about 418.000 Tickets, as the Ticket id is incremental and our newest ticket has an ID in that range.

The Import starts and imports as it should. For the first few thousand Tickets it seems to work. Takes some time but this is ok. 
Then after a while it just seems to stop working and we get the red error message.

**Comment by dominikklein** [comment] 2024-03-25 18:17
Difficult to say, because there is not really something visible in the log.

But normally when the import runs in a an error the error is also visible in the frontend.

So it seems to be the background worker is stopping at some point.

**Comment by mvbonin-CORE** [comment] 2024-04-02 13:34
Seems like it! I didn't find something either.
Right now I am trying with a different machine but also docker-compose. We'll see how it goes.

**Comment by mgruner** [comment] 2024-09-12 12:44
I'll close this report now, as we are unable to reproduce it. Please feel free to add more information.

**Closed as not planned by mgruner** 2024-09-12 12:44 UTC
Labels: waiting for feedback, needs verification
