### ISSUE TITLE
Editing JS .jst.eco files doesn't change anything

### ISSUE THREAD

**Issue by optiroot** [zammad/zammad#1163] opened 2017-06-03 10:27 UTC
### Infos:

* Used Zammad version: 1.4.0, commit 6bc9c00a
* Used Zammad installation source: RPM package
* Operating system: CentOS 7
* Browser + version:  Chrome Canary 61.0.3118.3

### Expected behavior:

* Edits made in .jst.eco files in `/app/assets/javascripts/app/views/` after precompile assets should appear

### Actual behavior:

* Nothing happens

If I want to edit a .jst.eco files (for example the login page) and I edit it, anything changes. I tried even doing `zammad run rake assets:precompile` but nothing changed. I cleared Rails cache too...
This isn't about the browser, I tried with 3 different browsers (one mobile) and on which of them in incognito mode too. 
I did even `zammad run rake assets:clean` and `zammad run rake assets:clobber` and the cached files in public disappeared (obviously). At the same time I can't run anymore `zammad run rake assets:precompile`, because it said that there was missing files in /public... obviously. So, I don't understand what is the command to let Zammad generate files from Javascript templates, sincerely. I thought it had to be `assets:precompile`.

Thank you for any help.

**Comment by hanneshal** [comment] 2017-06-04 14:40
Can you please append the complete message you get from running rake assets:precompile
This would help

**Comment by martini** [comment] 2017-06-04 15:31
Just a hint: alos restart the rails application server after recompiling.

**Comment by optiroot** [comment] 2017-06-06 16:23
Hello, thank you for you answers.

Sorry but two days ago I managed to delete that server and created a new Droplet (I'm using DO). I installed like the last time Zammad and it works perfectly.
Now I tried to edit:
https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/views/login.jst.eco#L18
below line 18 I added `<p>Test</p>`. 
I ran `zammad run rake assets:precompile` and nothing changed. So I ran `systemctl restart zammad` and nothing changed. I don't get any errors now, but... nothing changes. 
When I ran assets:precompile appeared a list of file with them directories, but I forgot to save the list to post it here, sorry.
Actually, after the zammad restart, if I run `zammad run rake assets:precompile` it hangs for some seconds then appears `Killed` in the command line. And of course, the login page doesn't change. Am I doing something wrong?

Maybe @martini didn't meant to do `systemctl restart zammad`? Or I need to restart the rails server in another way? If yes, which?

Thanks.

**Comment by thorsteneckel** [comment] 2017-06-06 17:57
Just a offtopic question: How are you using DigitalOcean? We have some issues with Argon2 over there: #966

**Comment by optiroot** [comment] 2017-06-06 18:47
I see... 
Maybe it could be related? I didn't have any problem anyway if the system was left like how you install it. It is that I ran so much commands that it started to get crazy...

What do you mean? I have a Frankfurt droplet with CENTOS 7 with 1Gb ram and 30gb disk

I think that I could give a try on aws or linode or something other... 
Will let you know later or tomorrow (even if it's me that is making some mistakes trying to edit js files... Maybe a missed clear cache? I don't know). 

Thanks

**Comment by optiroot** [comment] 2017-06-07 15:17
Tried using AWS EC2, same result. I changed lines in login.jst.eco like I said in my previous post and ran `zammad run rake assets:precompile` and then `systemctl restart zammad`. Nothing changed... 

When I ran the precompile command I had this output:
```
I, [2017-06-07T15:10:29.203998 #10662]  INFO -- : Writing /opt/zammad/public/assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css
I, [2017-06-07T15:10:29.204536 #10662]  INFO -- : Writing /opt/zammad/public/assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css.gz
I, [2017-06-07T15:10:29.208561 #10662]  INFO -- : Writing /opt/zammad/public/assets/print-57d400c28213ca8fb1fc899cd1f3cd91ec5073d4947e60b0b37f2dc2c9937140.css
I, [2017-06-07T15:10:29.208700 #10662]  INFO -- : Writing /opt/zammad/public/assets/print-57d400c28213ca8fb1fc899cd1f3cd91ec5073d4947e60b0b37f2dc2c9937140.css.gz
Killed
```

After this, nothing. Anything changed. Still used the RPM package with CentOS 7 but with AWS. Tried too on Google Cloud Platform always with CentOS 7, but same problem...

Tried doing too `zammad run rake tmp:cache:clear` and `zammad run rake assets:clean`... restarted Zammad then... nothing changed.
I think I'm missing some commands, sincerely. Because it's pretty impossibile that anything changes...

**Comment by hanneshal** [comment] 2017-06-30 10:30
Hi there,

I tried to reproduce the issue with no luck:

1. Created an image on DigitalOcean (CentoOS latest 7.3)
2. Installed Zammad via RPM
```
sudo yum -y install epel-release
sudo rpm --import https://rpm.packager.io/key
echo "[zammad]
name=Repository for zammad/zammad application.
baseurl=https://rpm.packager.io/gh/zammad/zammad/centos7/stable
enabled=1" | sudo tee /etc/yum.repos.d/zammad.repo
sudo yum -y install zammad
```

Performed the basic setup in the web frontend so I could login and switched back to the shell. 

Then i modified the login file at:
```
vi /opt/zammad/app/assets/javascripts/app/views/login.jst.eco
```
![1__root_centos-2gb-fra1-01____ssh_](https://user-images.githubusercontent.com/804939/27731952-84e17102-5d8f-11e7-935f-6413e13b79aa.jpg)

```
zammad run rake assets:precompile
systemctl restart zammad
```

And got this result:
![zammad_helpdesk_-_sign_in](https://user-images.githubusercontent.com/804939/27731972-a2171eb6-5d8f-11e7-9393-2a0807102d89.jpg)

I will close this issue here, because it is not related to the Zammad code(in my opinion).
 
Note:
I have disabled browser caching for this test, maybe this is the issue in your case. 

![chrome](https://user-images.githubusercontent.com/804939/27732022-da1731b6-5d8f-11e7-86c4-e4c399796b17.jpg)

**Closed by hanneshal** 2017-06-30 10:30 UTC
Labels: documentation

**Comment by Xeno22** [comment] 2019-03-29 08:34
Never ever run `zammad run rake assets:clobber` ...
It removes the whole public/assets directory and rake is not able to restore the files (since there are no copies left).

I had the same issue today on my ubuntu dev server:
I tried to set the default ticket type to email since the default note type is a bit strange and I was not able to recompile the assets. So I did a clobber - which removed all assets, also the shipped ones like fonts and images - but there is no command to restore the files.
The only way to get it running again is to restore the assets directory from the deb file and run precompile again.

Maybe move the compiled assets to public/assets/cache and let clobber just remove that directory?
