### ISSUE TITLE
Email signature logo not possible.

### ISSUE THREAD

**Issue by JW-Joey** [zammad/zammad#2512] opened 2019-03-11 10:46 UTC
* Used Zammad version: 2.8.X
* Installation method: Package
* Operating system: Debian 
* Database + version: MariaDB - 10.1.37
* Elasticsearch version: X
* Browser + version: Mozilla Firefox

### Expected behavior:

Logo in email signature.

### Actual behavior:

Cant place a logo in the email signature

### Steps to reproduce the behavior:

Try and place a logo in the email signature.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-03-11 10:57
Sorry but I can't reproduce this.
Copying images into the signature works like a charm. (Chrome and Firefox in current versions).

Please provide a detailed list on how to reproduce this - I'll close this for now.

**Closed as completed by MrGeneration** 2019-03-11 10:57 UTC
Labels: can't reproduce

**Comment by JW-Joey** [comment] 2019-03-11 11:36
Managed to copy the image into the signature, Now running into the problem of it not staying there once i press save. 


> Sorry but I can't reproduce this.
> Copying images into the signature works like a charm. (Chrome and Firefox in current versions).
> 
> Please provide a detailed list on how to reproduce this - I'll close this for now.

Seems it was browser related, Still having the issue above however.

**Comment by MrGeneration** [comment] 2019-03-11 11:42
I can not reproduce that.
For technical assistance, please refer our Community (https://community.zammad.org) - our Issue-Tracker is the wrong place for this!

I have tested this with a current Firefox.
