### ISSUE TITLE
Ticket injected via API no longer sent by customer in 6.0

### ISSUE THREAD

**Issue by ariep** [zammad/zammad#4647] opened 2023-06-08 11:03 UTC
### Used Zammad Version

6.0

### Environment

- Installation method: apt package
- Operating system: debian 11
- Database + version:  postgresql 13.11
- Elasticsearch version: 7.17.10
- Browser + version: curl 7.81 :D

### Actual behaviour

* The initial article in the new ticket, created via API, is formally sent by the user doing the API call.
* I assume because that's not the customer that the ticket belongs to, in particular, there is no "reply" button on the ticket.

log excerpt:
```
I, [2023-06-08T10:54:10.471659#653979-169280]  INFO -- : Started POST "/api/v1/tickets" for 45.83.234.139 at 2023-06-08 10:54:10 +0000
I, [2023-06-08T10:54:10.475698#653979-169280]  INFO -- : Processing by TicketsController#create as */*
I, [2023-06-08T10:54:10.475803#653979-169280]  INFO -- :   Parameters: {"title"=>"Titel 2", "group_id"=>57, "customer_id"=>"guess:REDACTED", "article"=>{"type"=>"web", "internal"=>false, "sender"=>"Customer
", "subject"=>"Arie test 2", "body"=>"[FILTERED]"}}
I, [2023-06-08T10:54:10.817364#653952-112060]  INFO -- : 2023-06-08T10:54:10+0000: [Worker(host:REDACTED pid:653952)] Job TransactionJob [84f911f9-bf9c-4aed-87db-3b0ee6a1f0e9] from DelayedJob(defa
ult) with arguments: [{"object"=>"Ticket", "object_id"=>801319, "user_id"=>31920, "created_at"=>{"_aj_serialized"=>"ActiveJob::Serializers::TimeWithZoneSerializer", "value"=>"2023-06-08T10:54:10.701578177Z"}, "t
ype"=>"create", "changes"=>{"last_contact_at"=>[nil, {"_aj_serialized"=>"ActiveJob::Serializers::TimeWithZoneSerializer", "value"=>"2023-06-08T10:54:10.642000000Z"}], "last_contact_customer_at"=>[nil, {"_aj_seri
alized"=>"ActiveJob::Serializers::TimeWithZoneSerializer", "value"=>"2023-06-08T10:54:10.642000000Z"}], "_aj_symbol_keys"=>[]}, "article_id"=>1336222, "_aj_symbol_keys"=>["object", "object_id", "user_id", "creat
ed_at", "type", "changes", "article_id"]}, {"interface_handle"=>"application_server", "_aj_symbol_keys"=>["interface_handle"]}] (id=2644656) (queue=default) RUNNING
I, [2023-06-08T10:54:10.917565#653979-169280]  INFO -- : Completed 201 Created in 442ms (Views: 0.6ms | ActiveRecord: 201.2ms | Allocations: 104049)
```

### Expected behaviour

* The initial article in the new ticket, created via API, is formally sent by the customer.
* There is a "reply" button which will send an email to the customer's address.

I expect this behaviour because we set `"sender": "Customer"` for the article.

This expected behaviour is also what happened until very recently, probably before we upgraded Zammad to 6.0. We did not change anything about the software doing the Zammad API call, and I confirmed the behaviour using manual `curl`, see below.

### Steps to reproduce the behaviour

* Create a role that grants access to `ticket.agent`, furthermore grant `create` and `change` permissions to the group that is used within the `curl` request.
* Assign this role to a user.
* Create an API token for this user.
* Create a ticket via the API as follows:
```
#!/bin/bash
url="https://your.zammad.instance/api/v1/tickets"
token=$(get your token)
body='{"title": "Test title", "group_id": 123, "customer_id": "guess:customer@example.com", "article": {"type": "web", "internal": false, "sender": "Customer", "subject": "Test subject", "body": "Test body."}}'
curl -i -X POST -H "Content-type: application/json" -H "Authorization: Token token=$token" "$url" -d "$body"
echo
```
* Observe that the ticket is created and associated with the `customer@example.com` customer, but the initial article seems to be sent by the user owning the API token, not the customer.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2023-06-08 11:11
Hey @ariep,

thanks for your report. Unfortunately, it's working as expected, see the following screenshot:

![image](https://github.com/zammad/zammad/assets/8327427/bc940ed2-af0c-4b83-ad6e-b82703940f4b)

The reply button is shown and can be used to answer to `customer@example.com` mail address.

Please provide more information to be able to reproduce the issue. Maybe you can also try to register a trial instance of Zammad (https://zammad.com/en/getting-started) and use it for your test.

Thanks! 😎

**Comment by ariep** [comment] 2023-06-08 12:22
Hi @fliebe92 , thanks for the extremely quick response!

* I learned from a colleague that they can see the reply button also for these tickets, so probably the fact that I can't is a permission issue. That colleague still suffers from this issue, because when they click reply, the "to" field is empty, so they have to copy-paste the email address of the customer before being able to send.
* I see from your screenshot that you indeed do not have this issue, even disregarding the reply button, because judging by the initials/avatar to the right of the article, the article is sent by the customer in your case, unlike our case where the avatar shows the user (dedicated api/machine user) that did the api call.

So thanks for your attempt to reproduce. I'm not sure how to continue from here. Thanks for the suggestion of the trial instance; maybe we'll try that but I expect that'll take some time to set up. To be continued.

**Comment by fliebe92** [comment] 2023-06-08 12:38
Hey @ariep,

you're welcome! 😄 

I would suggest closing this issue for now and maybe you can use the [Zammad community](https://community.zammad.org/). Just describe the issue there and I hope that some people will help to figure out what's going on in your system.

Thanks a lot for your efforts so far!

**Comment by ariep** [comment] 2023-06-08 12:46
Oh wow setting up a trial instance turns out to be extremely easy, well done!

The good news (well, for me anyway) is that I can reproduce the issue there. I've created https://issue-4647.zammad.com/#ticket/zoom/2 via a curl call like the one I mentioned (only changing content and details like domain, group id, etc.).
* It appears to be sent by the "cosmos" user (the dedicated api user), not by the "customer" of that ticket.
* When clicking reply the "to" gets set to the cosmos user's email address, which is wrong and dangerous (that email will not be read in a production setting so the reply would get lost).

Feel free to use whatever super powers you may have to enter this trial instance, check out the ticket I created, and/or create more tickets in the same way to reproduce. If you don't have access, please contact me privately on the email address I used to register the trial instance and we can set you up together.

If you want, I can try to write down exactly what "provisioning" steps I took on the trial instance, creating users/roles/settings. But I didn't do much: basically just creating this separate "cosmos" user with a role that gives ticket agent permission (and token preference for creating a token).

**Comment by ariep** [comment] 2023-06-08 12:53
@fliebe92 I hope that this warrants re-opening the issue. Please let me know if you think otherwise.

**Comment by fliebe92** [comment] 2023-06-08 13:08
@ariep Due to a public holiday in Germany, my current possibilities to access the trial you've created (thanks!) are somehow limited. I will continue checking the reported behavior tomorrow and keep you posted.

**Comment by fliebe92** [comment] 2023-06-08 18:51
@ariep I was able to reproduce it, but I need to check it locally and debug it a little bit.

It depends on the role you created, especially the given permissions to the group. The issue is only there if `read` is not granted... very strange.

**Comment by fliebe92** [comment] 2023-06-09 06:30
Regression of 9f670d26aa9c69f272051fe29672437661512042.

**Comment by fliebe92** [comment] 2023-06-09 06:31
The `from` attribute for the created article is using the wrong data.

**Closed as completed** 2023-06-09 19:35 UTC
Labels: bug, blocker, API, ticket, verified, permission

**Comment by fliebe92** [comment] 2023-06-09 19:36
Hey @ariep,

just a short follow-up:  We fixed this issue today. By tomorrow (latest), there will be a new package version of Zammad that contains this fix.

Enjoy your weekend 😎
