### ISSUE TITLE
Add Organization mapping/adding to LDAP and Exchange sync

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2515] opened 2019-03-18 16:45 UTC
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Current function
Currently it's not possible to synchronize or map organizations with users by using ldap or exchange, as long as you don't use domain based organizations (and the user is created new)

### Desired function
Zammad being able to add new organizations during ldap and exchange synchronization or at least a possibility to map users to existing organizations during synch.

### Goal
This will reduce maintenance tasks, as Zammad will map organizations to users automatically. Especially if your company grows bigger, it might be difficult to keep those information clean and complete.

**Comment by thorsteneckel** [comment] 2020-07-30 06:50
This is actually a duplicate of #1327 which describes multiple use cases/ways of implementations. Therefore I'll close this issue.

**Closed as completed by thorsteneckel** 2020-07-30 06:50 UTC
Labels: duplicate
