### ISSUE TITLE
Unable to add time account in New Mobile View

### ISSUE THREAD

**Issue by technoicon** [zammad/zammad#4711] opened 2023-07-11 04:43 UTC
### Used Zammad Version

6.0.0-32

### Environment

- Installation method: Docker
- Operating system: Ubuntu 18.04
- Database + version:  postgresql 15.1
- Elasticsearch version: 8.5
- Browser + version: Chrome Mobile?

New Mobile view for Android.

### Actual behaviour

When entering notes on a ticket, the time accounting doesn't pop up even though it's enabled in the settings.

### Expected behaviour

Be able to enter time when updating a ticket on mobile view.

### Steps to reproduce the behaviour

just update a note in a ticket using a mobile browswer.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2023-07-11 05:14
Hi @technoicon,

please have a look at the documentation: https://user-docs.zammad.org/en/latest/extras/mobile-view.html#limitations

It's currently a missing feature, not a bug. Therefore I'm going to close this issue here for now.

**Closed as not planned by fliebe92** 2023-07-11 05:14 UTC
Labels: works as designed / wontfix
