### ISSUE TITLE
Can't install Zammad on Debian 9

### ISSUE THREAD

**Issue by MrWeezle** [zammad/zammad#1306] opened 2017-07-27 15:15 UTC
Hi, I'm having problems installing Zammad 1.5.0 on Debian 9.

When I want to install Zammad with 
`sudo apt-get install zammad`

i get the following error:
`bundler: failed to load command: rake (/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake`

I also tried an install from source and I had to do a lot of additional work which was not described in the instruction (a lot of bundle updates, gem installs, installing ruby-dev,...). After those steps it kept failing at `rake db:migrate` saying `uninitialized constant rack::livereload`

Does someone have a solution getting Zammad running with Debian 9 ?

**Comment by thorsteneckel** [comment] 2017-07-27 15:27
Hi @MrWeezle - It's a duplicate of #1295. Debian 9 is currently not supported.

**Closed by thorsteneckel** 2017-07-27 15:27 UTC

**Comment by monotek** [comment] 2017-10-03 14:30
Still waiting that its activated in packager.io.

You can follow this bug to get updates: crohr/pkgr#128
