### ISSUE TITLE
No Mail-Icon or reply/forward-button after ticket-merging

### ISSUE THREAD

**Issue by danielduchon** [zammad/zammad#2207] opened 2018-08-23 06:32 UTC
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): deb
* Operating system: ubuntu 16.04
* Database + version: postgres (PostgreSQL) 9.5.14
* Elasticsearch version: 5.6.10
* Browser + version: Safari 11.1.2 (13605.3.8)

### Expected behavior:

* Two Tickets were created by E-Mailchannel (Sent from external to support address and converted to tickets.) On each Ticket I can reply to the sender by pressing the reply-button or send a mail to a third party by selecting the mail-icon next to the new-comment-field.
After merging these two tickets, I should be also able to reply on one of those mails by pressing the reply-button or send new mails.

### Actual behavior:

* after merging the tickets, I don't have a reply-button and no mail-icon at the new-comment section. I have to split the ticket, answer the customer or send a new mail and then merge the ticket back to the parent. after the customer answered to my mail, the mail-icon and reply/forward-button reappear.

### Steps to reproduce the behavior:

* send two mails to your ticket system, merge them and try to reply or send a mail.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-08-23 08:22
Hi @danielduchon ,

we're not able to reproduce this. I even made a GIF 🤓 :
![reply](https://user-images.githubusercontent.com/3873515/44512965-6a2a0000-a6bc-11e8-9fd3-52f90614d6cd.gif)

Please let me know where I go wrong. Do your Groups have emails configured? You can try to reproduce it on one of our [free online instances](https://www.zammad.com/getting-started) and let us know which one it is.

Closing now as not reproducible. Feel free to provide further information.

**Closed as completed by thorsteneckel** 2018-08-23 08:22 UTC
Labels: can't reproduce

**Comment by danielduchon** [comment] 2018-08-23 12:08
@thorsteneckel what the h... . I did a server restart and now everything is working. Sorry. for the work... by the way: how do you do these fancy GIFs?

**Comment by thorsteneckel** [comment] 2018-08-23 12:15
Thanks for the feedback. No problem. It would be a great help if you could create a topic over at the 
 [community board](http://community.zammad.org/) first. Otherwise more than 100 people get one email for each comment / closing action etc. If we're sure that's an actual issue we can still migrate it over to the issue tracker. That works pretty well so far.

Regarding the GIF: I use [LICEcap](https://www.cockos.com/licecap/) which is open source 😍
