### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by ToubieObie** [zammad/zammad#1641] opened 2017-11-14 14:45 UTC
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: deb
* Operating system: debian 8
* Browser + version: not relevant

### Expected behavior:

* It would be nice to have a mobile version of zammad

### Actual behavior:

* not available

### Steps to reproduce the behavior:

* /

**Comment by thorsteneckel** [comment] 2017-11-14 14:45
Duplicate of #223

**Closed by thorsteneckel** 2017-11-14 14:45 UTC

**Comment by julianmatz** [comment] 2019-06-01 19:25
With regards to #223 : I perfectly understand the noise problem, but I wanted to let you know, I don't think it's possible to upvote on locked threads.

**Comment by MrGeneration** [comment] 2019-06-01 23:43
Locking, sorry but this doesn't help at all.
Again: We have it on our list.
