### ISSUE TITLE
Inconsistency handling alias in mail channel

### ISSUE THREAD

**Issue by sandrodz** [zammad/zammad#1584] opened 2017-10-25 07:04 UTC
* In mail channel settings I can add alias to the main channel mail.
* I can create groups based on alias (dropdown I can see alias mail).
* On mail channel settings alias cannot have its own destination.

What is the point of allowing group creation based on alias mail if it cannot be set as a destination group?

**Comment by thorsteneckel** [comment] 2018-05-08 11:26
Hi @sandrodz - It's been a while since you created this issue. In the meantime some things have changed - in the Zammad code and the form we report issues. Could you please do the following to help us address this issue:

- Verify that the issue still persists in the latest version of Zammad
- Create a new issue and fill out the issue template completely
- Provide a detailed step by step guide (with screenshots!) on how to reproduce this

Thanks for you support! I'm closing this now.

**Closed by thorsteneckel** 2018-05-08 11:26 UTC
