### ISSUE TITLE
Reminder to press "Add" when adding a new group to a user

### ISSUE THREAD

**Issue by MoritzKlasen** [zammad/zammad#5284] opened 2024-07-31 11:38 UTC
### Used Zammad Version

6.3.1.92fb5d7c5.saas

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Several customers frequently forget to press the "Add" button when they want to add a new group to a user. This oversight leads to incomplete configurations and requires additional support interventions.

### Expected behaviour

Implement a small warning or reminder message that appears if the "Add" button is not pressed when a new group is selected. This message should serve as a gentle reminder to ensure the action is completed before proceeding.

### Steps to reproduce the behaviour

"Admin Settings" -> "Manage" -> "Users" ->
Select User
Grant Permissions
Add to Group (but DO NOT press "add")
Submit Changes

Select the same user again -> No group there because the user forgot to press "add".

In the ticket below you can understand the Problem maybe better
 |
 |
\|/

### Support Ticket

Ticket#10158928

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dvuckovic** [comment] 2024-08-02 10:58
Thanks for the report!

This is indeed a UX issue, and I agree that usage is not optimal. However, superfluous warnings are not a good approach: UI should be intuitive enough that such alerts are not needed even in the first place.

We aim to address this during our Desktop Rewrite project, since the issue is not present only in the Group Permissions field but others as well. By reimplementing form fields from scratch, we can base them on a new set of UI principles which we follow consinstently.

Here is a preview of how a similar field would behave in the new app: instead of having a dedicated "empty" row, the workflow will start by creating a new entry in the table. Then, any changes made to the row would be submitted along with the form.

![Image](https://github.com/user-attachments/assets/d599c047-c0aa-464d-8cbd-3e14ae40e683)

I will close this issue for now, but feel free to reopen with more information.

**Comment by ivan-abrash** [comment] 2024-08-05 10:24
Agree that this isn't a bug, it's a bad UX, and that desktop rewrite solution Dusan elaborated fixes it. 
Considering this makes many support tickets which support team already knows answer for, just wanted to suggest from my side as well we should resolve this with some as quick as possible workaround in the desktop app as well, by adding a message on pressing submit when that field row is "dirty" that will be ignored if +ADD button isn't pressed. If you decide to prioritise this @Mirtaaa @martini please let me know to design this alert, confirmation dialog that makes user confirm the addition of the "dirty" row or ignore it.

**Comment by dvuckovic** [comment] 2024-08-05 13:02
Instead of a confirmation dialog/modal, we should leverage the inline validation mechanism that all Zammad forms already support. For sure, this is a bit more difficult to implement in such complex fields like the **Group permissions**, but should be possible.

Something along the following lines:

<img width="957" alt="Screenshot 2024-08-05 at 13 53 37" src="https://github.com/user-attachments/assets/25a91f69-2592-4407-9c1a-ea025af20a6a">

The error message would show up when the user tries to submit the form with a partially composed entry. They can then rectify their mistake (either by adding the entry to the table, or clearing the fields), and try to resubmit the form without any data loss.

If we decide to do this now for the legacy desktop app, it needs to be said we have a couple (?) more places where similar behavior is exhibited. For example, in object attribute modal dialog, when select entries are defined:

<img width="600" alt="Screenshot 2024-08-05 at 13 55 06" src="https://github.com/user-attachments/assets/cf5ce2bd-c730-4807-8fed-e64a899892d1">

IMO, there is no point in addressing only a single type of field, and we should apply this consistently across the complete app. This is why I tried to recommend we do it as part of the Desktop Rewrite project, since it gives us a bit more control over all field types.

But, if there is a decision to do this earlier, I guess we could spend some time, identify all possible places in the legacy app and then tackle it.

**Comment by YetAnotherGerrit** [comment] 2024-08-06 12:44
I agree with @dvuckovic that this is solved by the ReWrite and it can wait. There are tons of more urgent and even easier to fix issues.

**Comment by MrGeneration** [comment] 2024-08-06 13:34
I disagree.
Right now you can unexpectedly close configuration dialogues. E.g. also if you press in the background of the modal popped up. This can cause very frustrating situations if you're accidentally clicking next to the modal to scroll for example. Or you just don't hit the right place. This is far more than just "the add button" part.

**Comment by dvuckovic** [comment] 2024-08-06 13:40
That's a different problem, related to the "dirty" state of the modal form. As far as I know, modal forms currently do not support additional confirmation when abandoning their changed state. This mechanism is reserved to proper screens.

**Comment by dvuckovic** [comment] 2024-08-09 13:18
After additional discussion, it was agreed not to try to fix this for the legacy desktop app, as it was already addressed by the redesign of the field for the new desktop view.

There might be further redesigns of the new field to align it with other similar controls in the system, though, so stay tuned!

**Closed as completed by dvuckovic** 2024-08-09 13:18 UTC
Labels: UX/UI, verified, prioritised by payment

**Comment by MrCybertux** [comment] 2026-05-06 16:23
It can happen that users assume Zammad is broken because the config is not saved, and it is not apparent to all people, that they have to use this button.
I just added a relevant case.
