### ISSUE TITLE
cannot create ticket as agent after update

### ISSUE THREAD

**Issue by Shoprunners** [zammad/zammad#2120] opened 2018-07-09 17:14 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): package
* Operating system: ubuntu 16.04.4
* Database + version:
* Elasticsearch version: 5.6.9
* Browser + version: chrome  67.0.3396.99

### Expected behavior:

Create a ticket via backend,

### Actual behavior:

Ticket will not be created, javascript error will be thrown

### Steps to reproduce the behavior:

I updated from 2.4 to zammad 2.5
This changed: there is no more choice of "incoming / outgoing call, email..." when creating a ticket.
If I press "+"  to create a ticket and fill in all required data and press "Erstellen"/"Create" a javascript error is thrown
```
application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:35 Uncaught TypeError: Cannot read property 'sender' of undefined
    at i.submit (application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:35)
    at i.submit (application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:34)
    at HTMLFormElement.<anonymous> (application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:8)
    at HTMLDivElement.dispatch (application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:2)
    at HTMLDivElement.m.handle (application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:2)
i.submit @ application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:35
(anonymous) @ application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:34
(anonymous) @ application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:8
dispatch @ application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:2
m.handle @ application-0b436ff922275ac6278664cf5493fcd6ff9b680a4dc2dfff21bc10bcf03cbf67.js:2
```

and nothing happens. Customers can create tickets without a problem.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-07-09 18:27
Hi @Shoprunners - this is probably a duplicate of #2106. Please do as described [here](https://github.com/zammad/zammad/issues/2106#issuecomment-401262710).

**Closed as completed by thorsteneckel** 2018-07-09 18:27 UTC
Labels: duplicate

**Comment by Shoprunners** [comment] 2018-07-09 18:43
Sorry, I didn't see the other ticket but your description how to fix it worked perfectly.
