### ISSUE TITLE
Regression: New ticket objects lead to "discard changes" notification

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#3078] opened 2020-06-10 14:24 UTC
### Infos:

* Used Zammad version: Latest
* Installation method (source, package, ..): Whatever your trial webhost uses
* Operating system: Whatever your trial webhost uses
* Database + version: Whatever your trial webhost uses
* Elasticsearch version: Whatever your trial webhost uses
* Browser + version: Firefox latest stable

### Expected behavior:

* When adding new ticket objects to zammad the changes should be applied as set in the option without creating new notifications when closing existing ticket tabs.
Which should be fixed according to these:
https://github.com/zammad/zammad/issues/2042
https://github.com/zammad/zammad/issues/2288

### Actual behavior:

* Discard changes notification will pop up everytime for existing tickets if they are closed from the tab list. Also the general "discard unsaved changes" button shows no effect whatsoever.
Only new tickets created after the new ticket object work as expected.

### Steps to reproduce the behavior:

* See trial installation at https://objecttest.zammad.com for reference.

Is there a workaround for this other than updating all old tickets manually?

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-06-10 14:34
Thanks for your report, however: This is a duplicate of:
https://github.com/zammad/zammad/issues/3035

I'll therefor be closing this issue. :)
I'm afraid there's currently no workaround for this issue except for updating all tickets to value x, I'm sorry.

**Closed as completed by MrGeneration** 2020-06-10 14:34 UTC
Labels: duplicate

**Comment by SEGGER-NV** [comment] 2020-06-10 14:45
Oh sorry I overlooked that. To bad there is no sleek workaround for this :(
Could you add the following to the other issue as well?
"Also the general "discard unsaved changes" button shows no effect whatsoever."

It is a bit unintuitive if that button has no effect all of a sudden.

**Comment by MrGeneration** [comment] 2020-06-10 15:20
@SEGGER-NV can you please double check if "Discard changes" button does nothing upon pressing?
I tested that and it works - at least on my end. 

if it is an issue, then that's clearly not what should happen. If it's still happening for you and maybe browser related, a new issue would be a good way! 🙌 

I personally think that the issue with the discard button is technically a different issue than the object handling, which is why I believe it should be an independend issue. I hope you understand that view. :)
