### ISSUE TITLE
Not authorized error using Im X-On-Behalf-Of

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3468] opened 2021-03-24 18:25 UTC
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
*  Ticket #1085175

### Expected behavior:

* Using the Zammad API an authorization via token should work when using "X-On-Behalf-Of".

### Actual behavior:

* What works: Using password authentication, e.g.: 
 
`curl -u chris@chrispresso.com:XXXX -H "Content-Type: application/json" -H "X-On-Behalf-Of: 11" -X POST -d '{"title":"Help me!","group": "Sales","article":{"subject":"some subject","body":"some message","type":"note","internal":false},"customer":"olivia@example.com","note": "some note"}' http://localhost:3000/api/v1/tickets`

* What doesn't: Using a generated token,e.g.: 

`curl -H "Authorization: Token token=XXXX" -H "Content-Type: application/json" -H "X-On-Behalf-Of: 11" -X POST -d '{"title":"Help me!","group": "Sales","article":{"subject":"some subject","body":"some message","type":"note","internal":false},"customer":"olivia@example.com","note": "some note"}' http://localhost:3000/api/v1/tickets`

* Error shown: `{"error":"Not authorized","error_human":"Not authorized"}`

### Steps to reproduce the behavior:

* Make a request on behalf of a different user via API, e.g.: 
 
`curl -H "Authorization: Token token=XXXX" -H "Content-Type: application/json" -H "X-On-Behalf-Of: 11" -X POST -d '{"title":"Help me!","group": "Sales","article":{"subject":"some subject","body":"some message","type":"note","internal":false},"customer":"olivia@example.com","note": "some note"}' http://localhost:3000/api/v1/tickets`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-03-24 18:32
I'm sorry, I can't reproduce this on a current develop 4.0

**Comment by thorsteneckel** [comment] 2021-03-24 18:36
Hi @cautopartes - after some issues with this functionality in the past we've build up a pretty decent test coverage for many different use cases. This one doesn't look any special to me. I guess that there is a permission issue. Can you double check that the permissions required for creating tickets in the group match up with those that the corresponding requesting / behalf of user?

**Comment by martini** [comment] 2021-03-24 20:03
@thorsteneckel I tested it in my local system. Using user&pw I can create the ticket. By using the token I can't.

Here more information:

The user/agent:

```
User.find(3).permissions.pluck(:name)
 "report",
 "admin",
 "user_preferences",
 "knowledge_base.reader",
 "cti.agent",
 "chat.agent",
 "ticket.agent",
 "user_preferences"]
```

The Token:
```
Token.last.preferences
=>  {"permission"=>["admin.user", "ticket.agent"]}
```

The customer user which is used for in behalf of:

```
User.last.permissions.pluck(:name)
=> ["ticket.customer",
 "user_preferences.avatar",
 "user_preferences.linked_accounts",
 "user_preferences.language",
 "user_preferences.password"]
```

The traceback:

```
I, [2021-03-24T18:53:46.545341 #15646-70228722621740]  INFO -- : Started POST "/api/v1/tickets" for 127.0.0.1 at 2021-03-24 18:53:46 +0100
I, [2021-03-24T18:53:48.535767 #15646-70228722621740]  INFO -- : Processing by TicketsController#create as */*
I, [2021-03-24T18:53:48.535832 #15646-70228722621740]  INFO -- :   Parameters: {"title"=>"Help me!", "group"=>"Sales", "article" =>{"subject"=>"some subject", "body"=>"[FILTERED]", "type"=>"note", "internal"=>false}, "customer"=>"olivia@example.com", "note" =>"some note"}
I, [2021-03-24T18:53:48.716399 #15646-70228722621740]  INFO -- : not allowed to create? this #<Ticket id: nil, group_id: 1, priority_id: nil, state_id: nil, organization_id: nil, number: nil, title: "Help me!", owner_id: nil, customer_id: 11, note: "some note", first_response_at: nil, first_response_escalation_at: nil, first_response_in_min: nil, first_response_diff_in_min: nil, close_at: nil, close_escalation_at: nil, close_in_min: nil, close_diff_in_min: nil, update_escalation_at: nil, update_in_min: nil, update_diff_in_min: nil, last_contact_at: nil, last_contact_agent_at: nil, last_contact_customer_at: nil, last_owner_update_at: nil, create_article_type_id: nil, create_article_sender_id: nil, article_count: nil, escalation_at: nil, pending_time: nil, type: nil, time_unit: nil, preferences: {}, updated_by_id: nil, created_by_id: nil, created_at: nil, updated_at: nil> (Pundit::NotAuthorizedError)
/home/me/.rvm/gems/ruby-2.6.6/gems/pundit-2.0.1/lib/pundit.rb:221:in `authorize'
/home/me/src/zammad/app/controllers/application_controller/authorizes.rb:8:in `authorize!'
/home/me/src/zammad/app/controllers/tickets_controller.rb:146:in `create'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/abstract_controller/base.rb:194:in `process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/me/src/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:18:in `block (4 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:180:in `subscribed'
/home/me/src/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:17:in `block (3 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:180:in `subscribed'
/home/me/src/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:16:in `block (2 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/me/src/zammad/app/controllers/application_controller/handles_transitions.rb:14:in `handle_transaction'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `block in instrument'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `instrument'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/abstract_controller/base.rb:134:in `process'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionview-5.2.4.5/lib/action_view/rendering.rb:32:in `process'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal.rb:191:in `dispatch'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal.rb:252:in `dispatch'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/journey/router.rb:35:in `each'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/journey/router.rb:35:in `serve'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/routing/route_set.rb:840:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:420:in `call_app!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-saml-1.10.1/lib/omniauth/strategies/saml.rb:89:in `other_phase'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:190:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/me/.rvm/gems/ruby-2.6.6/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:559:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/railties-5.2.4.5/lib/rails/rack/logger.rb:38:in `call_app'
/home/me/.rvm/gems/ruby-2.6.6/gems/railties-5.2.4.5/lib/rails/rack/logger.rb:26:in `block in call'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/me/.rvm/gems/ruby-2.6.6/gems/railties-5.2.4.5/lib/rails/rack/logger.rb:26:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/static.rb:127:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/railties-5.2.4.5/lib/rails/engine.rb:524:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
/home/me/.rvm/gems/ruby-2.6.6/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
/home/me/.rvm/gems/ruby-2.6.6/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
/home/me/.rvm/gems/ruby-2.6.6/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
/home/me/.rvm/gems/ruby-2.6.6/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/home/me/.rvm/gems/ruby-2.6.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2021-03-24T18:53:48.716502 #15646-70228722621740]  INFO -- : Not authorized (Exceptions::Forbidden)
I, [2021-03-24T18:53:48.717027 #15646-70228722621740]  INFO -- : Completed 403 Forbidden in 181ms (Views: 0.2ms | ActiveRecord: 39.3ms)
```

**Comment by martini** [comment] 2021-03-24 20:45
IMO the issue is here: https://github.com/zammad/zammad/blob/develop/lib/user_context.rb#L21

It seems that the origin agent token permissions are checked and not the permissions for the customer user it self which is used in behalf.

https://github.com/zammad/zammad/commit/5dde117a145f44b1fb582d9edd266519fd17b4b1

**Comment by thorsteneckel** [comment] 2021-03-24 22:10
Looks like a duplicate of https://github.com/zammad/zammad/issues/3327#issuecomment-765287635 to me. Can you please double check?

**Comment by martini** [comment] 2021-03-24 23:22
> Looks like a duplicate of #3327 (comment) to me. Can you please double check?

Yes. It looks like it is the same. But currently is looks wrong to me, that the permissions of the admin user which is performing the behalf of user is taken/checked. With user+password it works without assigning extra permissions.

**Closed as completed** 2021-04-01 15:15 UTC
Labels: API, ticket, authentication, verified, prioritised by payment
