### ISSUE TITLE
Error page displays markup

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#992] opened 2017-04-25 12:43 UTC
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: deb
* Operating system: ubuntu:16.04
* Browser + version: FF 52.0.2

### Expected behavior:

* Error 500 message should never display markup

### Actual behavior:

![grafik](https://cloud.githubusercontent.com/assets/4621219/25385303/e87aa3dc-29c3-11e7-9942-324de8d1efa1.png)

### Steps to reproduce the behavior:

* This error page came up out of the blue with these lines in the log:
```
Can't write cache Setting::ChangeId: #<Errno::EACCES: Permission denied @ rb_file_s_rename - (/opt/zammad/tmp/cache_file_store_production/Setting%3A%3AChangeId20170425-23340-z3mphv, /opt/zammad/tmp/cache_file_store_production/704/120/Setting%3A%3AChangeId)> 
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/file_store.rb:91:in `delete': Permission denied @ unlink_internal - /opt/zammad/tmp/cache_file_store_production/704/120/Setting%3A%3AChangeId (Errno::EACCES) 
from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/file_store.rb:91:in `delete_entry' 
```
It turned out that `tmp/cache_file_store_production/704` belonged to `root`, while everything else in this directory belongs to `zammad`. `chown -R zammad:zammad tmp/cache_file_store_production/704` helped. 

This happened ~24 hours after upgrading from 1.4.0 to 1.5.0. Even though it would be great to find out why this error occurred at all, I'm posting this issue primarily because of the mis-formatted error page, as I had seen it in other situations before.

**Suggestion:** 

Even without understanding why/how this could happen, you could block the symptom of markup being displayed:

In `zammad/public/500.html`, change this line
```
<body <% if @traceback %>class="error-message"<% end %>>
```
to 
```
<% if @traceback %>
<body class="error-message">
<% else %>
<body>
<% end %>
```

**Comment by olivergrahl** [comment] 2017-12-11 07:40
Ran into exactly the same issue after upgrading from 2.1.0 to 2.2.0. Again ~24hrs after upgrading.

**Comment by thorsteneckel** [comment] 2018-01-03 08:34
Hi @mrflix - I think you said you fixed this (on your local branch), right?

**Comment by thorsteneckel** [comment] 2018-04-22 16:44
Can't reproduce (anymore?):

![localhost_3000_](https://user-images.githubusercontent.com/3873515/39097490-256f2bda-465d-11e8-9c91-f1cbe9ceea7f.png)

Please provide a detailed step by step guide on how to reproduce. Closing now.

**Closed by thorsteneckel** 2018-04-22 16:44 UTC
Labels: UX/UI, bug, needs verification
