### ISSUE TITLE
Users missing, appear when searching on organization

### ISSUE THREAD

**Issue by ThomHordijk** [zammad/zammad#2775] opened 2019-10-14 14:03 UTC
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: windows
* Database + version: unkown
* Elasticsearch version: unkown
* Browser + version: mozzila firefox 69.0.3

### Expected behavior:

* I expect to find all the users, customers, when opening admin --> users and selecting customers

### Actual behavior:

* Some customers are only shown when searching the respective organization, this seems to happen across all organizations.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-10-14 14:27
This is a duplicate of issue https://github.com/zammad/zammad/issues/2214

Please note that Zammad currently limits the number of users to 30.
They can still be found via search function, this is to save data usuage and system ressources.

Closing now.

**Closed as completed by MrGeneration** 2019-10-14 14:27 UTC
Labels: duplicate, question
