### ISSUE TITLE
unprocessable mails - zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'

### ISSUE THREAD

**Issue by jvkroeger** [zammad/zammad#4584] opened 2023-04-19 12:04 UTC
### Used Zammad Version

5.4.1-1681508050.43f0c68b.focal

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): 20.04.6 LTS (Focal Fossa)
- Database + version:  psql (12.14 (Ubuntu 12.14-0ubuntu0.20.04.1))
- Elasticsearch version: [e.g. 7.17]
- Browser + version: 

### Actual behaviour

Mails cannot be processed several times a day

### Expected behaviour

Mails should be processed

### Steps to reproduce the behaviour

Healthcheck report unprocessable mails.

When I call
```
zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'
```

I get:
```
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/34617edf5478f869e4066f7402ec3c5e.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ArgumentError: string length (181) exceeds the limit 128>"
/opt/zammad/app/models/channel/email_parser.rb:138:in `rescue in process': #<ArgumentError: string length (181) exceeds the limit 128> (RuntimeError)
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:17:in `parse'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:17:in `normalize_datetime'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:31:in `initialize'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_field.rb:12:in `new'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_field.rb:12:in `parse'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field.rb:265:in `parse_field'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field.rb:254:in `create_field'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field.rb:187:in `field'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field.rb:233:in `method_missing'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field_list.rb:23:in `add_field'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:100:in `block in fields='
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:98:in `each'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:98:in `fields='
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:228:in `split_header'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:56:in `initialize'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:429:in `new'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:429:in `header='
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:1981:in `parse_message'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:2119:in `init_with_string'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:135:in `initialize'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/mail.rb:51:in `new'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/mail.rb:51:in `new'
/opt/zammad/app/models/channel/email_parser.rb:82:in `parse'
/opt/zammad/app/models/channel/email_parser.rb:144:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:123:in `block in process'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `block in catch'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:198:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:122:in `process'
/opt/zammad/app/models/channel/email_parser.rb:509:in `block in process_unprocessable_mails'
<internal:dir>:220:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:508:in `process_unprocessable_mails'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/zammad/bin/rails:5:in `<main>'
	from /opt/zammad/app/models/channel/email_parser.rb:120:in `process'
	from /opt/zammad/app/models/channel/email_parser.rb:509:in `block in process_unprocessable_mails'
	from <internal:dir>:220:in `glob'
	from /opt/zammad/app/models/channel/email_parser.rb:508:in `process_unprocessable_mails'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/zammad/bin/rails:5:in `<main>'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:17:in `parse': string length (181) exceeds the limit 128 (ArgumentError)
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:17:in `normalize_datetime'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:31:in `initialize'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_field.rb:12:in `new'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/fields/common_field.rb:12:in `parse'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field.rb:265:in `parse_field'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field.rb:254:in `create_field'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field.rb:187:in `field'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field.rb:233:in `method_missing'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/field_list.rb:23:in `add_field'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:100:in `block in fields='
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:98:in `each'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:98:in `fields='
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:228:in `split_header'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/header.rb:56:in `initialize'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:429:in `new'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:429:in `header='
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:1981:in `parse_message'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:2119:in `init_with_string'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:135:in `initialize'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/mail.rb:51:in `new'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/mail-2.8.1/lib/mail/mail.rb:51:in `new'
	from /opt/zammad/app/models/channel/email_parser.rb:82:in `parse'
	from /opt/zammad/app/models/channel/email_parser.rb:144:in `_process'
	from /opt/zammad/app/models/channel/email_parser.rb:123:in `block in process'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `block in catch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:198:in `timeout'
	from /opt/zammad/app/models/channel/email_parser.rb:122:in `process'
	from /opt/zammad/app/models/channel/email_parser.rb:509:in `block in process_unprocessable_mails'
	from <internal:dir>:220:in `glob'
	from /opt/zammad/app/models/channel/email_parser.rb:508:in `process_unprocessable_mails'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/zammad/bin/rails:5:in `<main>'
```

Hint: The email contains an error by our Amavis:

```
X-Amavis-Alert: BAD HEADER SECTION, Duplicate header field: "Date"
```

and indeed there are two Date fields:

```
Date: Wed, 19 Apr 2023 13:41:01 +0200Received: from m241-41.mailgun.net (m241-41.mailgun.net [159.112.241.41])
        by in45.mail.ovh.net (Postfix) with ESMTPS id 4PgzCH5GFlz279jM6
        for <....@.....de>; Tue, 21 Mar 2023 17:30:35 +0000 (UTC)
.....
Date: Sat, 1 Apr 2050 13:51:46 +0000
```

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment] 2023-04-19 12:09
Duplicate of #4567

**Closed as completed by MrGeneration** 2023-04-19 12:09 UTC
Labels: duplicate
