### ISSUE TITLE
Ticket zoom sidebar leaks subjects of confidential tickets

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2757] opened 2019-09-26 13:40 UTC
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 9
* Database + version: PostgreSQL 9.6.15
* Elasticsearch version: 5.6.14
* Browser + version: Chrome 77

### Expected behavior:

* The customer panel in the ticket view sidebar should only list open/closed tickets of this customer where the current agent has at the very least overview permissions for these tickets.

### Actual behavior:

* The customer panel in the ticket view sidebar lists tickets that the agent has no access to, not even overview permissions. This causes Zammad to leak the subjects of possibly confidential tickets to agents who don't have access to these tickets.

### Steps to reproduce the behavior:

* Have a customer that has two open tickets: one in a group where your agent has read permissions (or more), and another in a group where your agent doesn't have any permissions.
* Open the ticket you are allowed to read.
* Switch the ticket view sidebar to Customer.
* Note that the sidebar will show "open (2)", and list both the ticket you are allowed to read, and the one you are not allowed to read. While you cannot actually read the confidential ticket (it'll say "Opps.. I'm sorry, but you have insufficient rights to open this Ticket."), you can read its subject.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-10-04 15:45
Thanks for your contribution, I agree that we should not show information the agent -normally- is not allowed to view.

**Comment by mantas** [comment] 2021-09-20 10:34
Looks like this will be fixed in upcoming release with the following commit

https://github.com/zammad/zammad/commit/d2efdb547d0e5a526f20fe1609680f152da3fb6f

@thorsteneckel or can you still reproduce this?

**Comment by thorsteneckel** [comment] 2021-09-20 10:52
I haven't had the chance to do so. I just added it to the Workflow. If it can't be reproduced we can close the issue, remove all labels, add the "can't reproduce" label and add the issue link as a comment to that commit 👍

**Comment by mantas** [comment] 2021-09-20 19:20
Can confirm that ticket subjects are no longer leaked. But counter is still wrong and accounts for all customer's tickets.

![Screenshot 2021-09-20 at 20 42 04](https://user-images.githubusercontent.com/36944/134060394-1b9d2b5f-ee24-42de-bb1e-ca09281307e8.png)

**Comment by martinvonwittich** [comment] 2021-09-20 20:24
> Can confirm that ticket subjects are no longer leaked. But counter is still wrong and accounts for all customer's tickets.

Hmm, but that might actually be useful. If you're looking for a specific ticket that you know exists, but that's actually not accessible to you (maybe someone moved it into a different group that you don't have access to), then the ability to at least determine that there are additional tickets that you can't see might be helpful. An explicit hint like "<number> tickets you aren't allowed to view" below the list might clarify the difference.

To be clear though, I'm not saying that agents should be able to see the amount of inaccessible tickets, I just wanted to point out that it might have its uses :)

**Comment by mantas** [comment] 2021-09-21 13:53
Ticket subjects will be no longer leaked in the next release thanks to commit bellow. Closing this issue now. Customer tickets count will be addressed in a separate issue.

https://github.com/zammad/zammad/commit/d2efdb547d0e5a526f20fe1609680f152da3fb6f

**Closed as completed by mantas** 2021-09-21 13:53 UTC
