### ISSUE TITLE
Report Profile "Owner" is "current user" -> StatusCode: 500

### ISSUE THREAD

**Issue by stefanhirt** [zammad/zammad#507] opened 2016-12-05 09:49 UTC
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1041524

### Expected behavior:

* It should be possible to have a report for Tickets of the current user.

### Actual behavior:

* If I generate a custom Report Profile and filter for "Owner" is "current user" selecting this profile results in "StatusCode: 500"
```
ERROR -- : Unable to process GET request to elasticsearch URL 'http://127.0.0.1:9200/zammad_production/Ticket/_search'. Check the response and payload for detailed information: 

Response:
#<UserAgent::Result:0x00007fde9603e518 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"failed to create query: {\\n  \\\"bool\\\" : {\\n    \\\"must\\\" : [\\n      {\\n        \\\"term\\\" : {\\n          \\\"owner_id\\\" : {\\n            \\\"value\\\" : \\\"\\\",\\n            \\\"boost\\\" : 1.0\\n          }\\n        }\\n      },\\n      {\\n        \\\"range\\\" : {\\n          \\\"created_at\\\" : {\\n            \\\"from\\\" : null,\\n            \\\"to\\\" : null,\\n            \\\"include_lower\\\" : true,\\n            \\\"include_upper\\\" : true,\\n            \\\"boost\\\" : 1.0\\n          }\\n        }\\n      }\\n    ],\\n    \\\"must_not\\\" : [\\n      {\\n        \\\"term\\\" : {\\n          \\\"state\\\" : {\\n            \\\"value\\\" : \\\"merged\\\",\\n            \\\"boost\\\" : 1.0\\n          }\\n        }\\n      }\\n    ],\\n    \\\"disable_coord\\\" : false,\\n    \\\"adjust_pure_negative\\\" : true,\\n    \\\"boost\\\" : 1.0\\n  }\\n}\",\"index_uuid\":\"gyDrqn0qSD6b-V4ZW5CJOQ\",\"index\":\"zammad_production\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"zammad_production\",\"node\":\"S4u0RgjwT9aOCuov3qZGfw\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"failed to create query: {\\n  \\\"bool\\\" : {\\n    \\\"must\\\" : [\\n      {\\n        \\\"term\\\" : {\\n          \\\"owner_id\\\" : {\\n            \\\"value\\\" : \\\"\\\",\\n            \\\"boost\\\" : 1.0\\n          }\\n        }\\n      },\\n      {\\n        \\\"range\\\" : {\\n          \\\"created_at\\\" : {\\n            \\\"from\\\" : null,\\n            \\\"to\\\" : null,\\n            \\\"include_lower\\\" : true,\\n            \\\"include_upper\\\" : true,\\n            \\\"boost\\\" : 1.0\\n          }\\n        }\\n      }\\n    ],\\n    \\\"must_not\\\" : [\\n      {\\n        \\\"term\\\" : {\\n          \\\"state\\\" : {\\n            \\\"value\\\" : \\\"merged\\\",\\n            \\\"boost\\\" : 1.0\\n          }\\n        }\\n      }\\n    ],\\n    \\\"disable_coord\\\" : false,\\n    \\\"adjust_pure_negative\\\" : true,\\n    \\\"boost\\\" : 1.0\\n  }\\n}\",\"index_uuid\":\"gyDrqn0qSD6b-V4ZW5CJOQ\",\"index\":\"zammad_production\",\"caused_by\":{\"type\":\"number_format_exception\",\"reason\":\"empty String\"}}}]},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">

Payload:
{:query=>{:bool=>{:must=>[{:term=>{"owner_id"=>""}}, {:range=>{"created_at"=>{:from=>"2019-01-01", :to=>"2019-12-31"}}}], :must_not=>[{:term=>{"state"=>"merged"}}]}}, :size=>0, :aggs=>{:time_buckets=>{:date_histogram=>{:field=>"created_at", :interval=>"month"}}}}
```

### Steps to reproduce the behavior:

* Create reporting profile
![custom_report](https://cloud.githubusercontent.com/assets/14818988/20880360/06fb7666-bad8-11e6-9f21-56b3f1d8d5d6.png)

* Open Reporting profile in Reporting view
![image](https://user-images.githubusercontent.com/3873515/56350946-488e0380-61cc-11e9-882c-476bede144ec.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2016-12-06 15:05
Hi @stefanhirt - could you please provide your the `log/production.log` file? This might help us to come closer to the issue. Thanks!

**Comment by stefanhirt** [comment] 2016-12-07 07:58
Hi @thorsteneckel 
there you go:
[production.log.zip](https://github.com/zammad/zammad/files/635992/production.log.zip)

**Comment by patrickkeller** [comment] 2017-03-01 12:16
The same problem occurs also when we try to filter by groups

**Comment by martini** [comment] 2017-05-16 08:50
Sorry for the long delay. In the meantime we fixed several bugs filter/ticket selector. I can't reproduce this problem on Zammad 1.5 anymore.

If you still have problems, let me know. Thanks a lot!

**Comment by passboltUser** [comment] 2017-07-11 08:00
This fixed it for my https://github.com/zammad/zammad/issues/1242: https://github.com/zammad/zammad/issues/1189#issuecomment-309499186

**Comment by thorsteneckel** [comment] 2019-04-18 09:19
This issue is actually not fixed. The following diff shows how the `current_user` should get passed to the `SearchIndexBackend.selectors` method:

```diff
diff --git a/app/controllers/reports_controller.rb b/app/controllers/reports_controller.rb
index 23b6612a7..725dfca8d 100644
--- a/app/controllers/reports_controller.rb
+++ b/app/controllers/reports_controller.rb
@@ -39,6 +39,7 @@ class ReportsController < ApplicationController
         params:          backend[:params],
         timezone:        get_params[:timezone],
         timezone_offset: get_params[:timezone_offset],
+        current_user:    current_user
       )
     end
 
@@ -81,6 +82,7 @@ class ReportsController < ApplicationController
         sheet:           params[:sheet],
         timezone:        get_params[:timezone],
         timezone_offset: get_params[:timezone_offset],
+        current_user:    current_user
       )
 
       result = { count: 0, ticket_ids: [] } if result.nil?
diff --git a/lib/report/ticket_generic_time.rb b/lib/report/ticket_generic_time.rb
index 3b87b66f0..40ae5f2bf 100644
--- a/lib/report/ticket_generic_time.rb
+++ b/lib/report/ticket_generic_time.rb
@@ -45,7 +45,7 @@ returns
     end
     selector.merge!(without_merged_tickets) # do not show merged tickets in reports
 
-    result_es = SearchIndexBackend.selectors(['Ticket'], selector, {}, aggs_interval)
+    result_es = SearchIndexBackend.selectors(['Ticket'], selector, {current_user: params[:current_user]}, aggs_interval)
     if params[:interval] == 'month'
       stop_interval = 12
     elsif params[:interval] == 'week'
@@ -166,7 +166,7 @@ returns
     end
     selector.merge!(without_merged_tickets) # do not show merged tickets in reports
 
-    result = SearchIndexBackend.selectors(['Ticket'], selector, { limit: limit }, aggs_interval)
+    result = SearchIndexBackend.selectors(['Ticket'], selector, { limit: limit, current_user: params[:current_user] }, aggs_interval)
     return result if params[:sheet].present?
 
     assets = {}
```

However, the `current_user` still has to get converted to `current_user_id` in the [`SearchIndexBackend.selector2query`](https://github.com/zammad/zammad/blob/7919f341ff10ce42e9739552661bc81034c4c7ec/lib/search_index_backend.rb#L557) method as it is done in the `Ticket.selector2sql` method:

https://github.com/zammad/zammad/blob/7919f341ff10ce42e9739552661bc81034c4c7ec/app/models/ticket.rb#L508-L513

**Comment by MrGeneration** [comment] 2019-06-26 13:53
I'm closing this issue in favor for https://github.com/zammad/zammad/issues/2517 as duplicate.

**Closed by MrGeneration** 2019-06-26 13:53 UTC
Labels: bug, prioritized by payment, reporting, verified
