### ISSUE TITLE
Under certain circumstances text before a quicktext gets deleted if quicktext is not available.

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2711] opened 2019-08-20 09:04 UTC
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: -
* Elasticsearch version: -
* Browser + version: Firefox latest

### Expected behavior:

* When writing Text then using quicktext none of the already written text should be removed if the quicktext macro is not available

### Actual behavior:

* The text before the quicktext gets removed partially. We assume it is because the editor thinks that part of the text before the :: is part of the incorrect macro.
The following gif shows how the macro text is usually removed:
![quicktext_rm](https://user-images.githubusercontent.com/44224243/63333389-aa58a880-c339-11e9-96c5-5cade1bb5c57.gif)

Not sure if this behaviour is intended or not but it can happen for text before the :: as well which is not great especially when complete sentences disappear which can't be recovered with Ctrl + Z

### Steps to reproduce the behavior:

* Unfortunately the issue was not yet 100% reproducible. We have only seen it occasionally on different machines with different browsers even (Firefox/Chrome). We will see if we can provide a better reproducer. Eventually the information currently given is already enough for you to get an idea where things might go wrong.
There have also been instances where a correct macro was typed and selected and after pressing enter the whole typed out text after :: disappeared. But not sure if this is also related to this issue.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-08-20 09:11
Sorry but I believe that this works as designed.

Reason for this:
The reason is, that when pressing `::` you're actually inside the text module dialogue.
If you watch your screencast closely, Zammad delivers text modules for a moment - as you continue to type, the dialogue vanishes (because there are no values left).

If you press enter now, you're telling Zammad to insert the text module (which is empty in this case), which it does (your written text is gone).

Workaround:
You can workaround this with pressing your escape-button.
As a tip: I'd do this when you still see the text module dialogue, because you'll make sure that you're no longer in that dialogue for sure.




### What we should do
We should enhance the text module dialogue to show something like "no text modules found" so it's clearer that the dialogue is still active.

**Comment by SEGGER-NV** [comment] 2019-08-20 12:13
I see thank you for clarification. 
Still the bug remains that not only the text after the :: is removed after pressing enter but actual body text that should not be removed. Worst part is that CTRL+Z does not work so actual written text is lost.
I will make a video should I come across it again.

Another issue I saw today with quicktext is as follows:
![quicktext_empty](https://user-images.githubusercontent.com/44224243/63346105-9a9a8d80-c354-11e9-928c-04655e1e85f7.gif)

Simply open a new text filed, type :: and remove it with backspace. Now the cursor will be out of bounds of the text window. It is probably only cosmetic but looks weird.

**Comment by MrGeneration** [comment] 2019-08-20 12:34
Hey,

please create an own issue for your comment (https://github.com/zammad/zammad/issues/2711#issuecomment-522986208).

I could verify this (and will mark it accordingly after you created it).
This also affects Google Chrome, but way less than Firefox. Also, this only seems to affect the ticket creation process.

**Comment by MrGeneration** [comment] 2021-08-30 08:56
This issue may have been fixed by https://github.com/zammad/zammad/issues/2886

**Comment by dominikklein** [comment] 2021-09-28 12:07
I can not reproduce the problem, so i think it should be fixed together with #2886.

**Closed as completed by dominikklein** 2021-09-28 12:07 UTC
Labels: enhancement, UX/UI, verified
