### ISSUE TITLE
Spam tag Macro does not tag correctly

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#442] opened 2016-11-18 11:45 UTC
I'm using this Macro to tag spam messages:

![image](https://cloud.githubusercontent.com/assets/3321655/20429024/788e8696-ad8c-11e6-865a-69d074f98584.png)

But the tagging does not work in most cases:

![image](https://cloud.githubusercontent.com/assets/3321655/20429091/ce1818d4-ad8c-11e6-916f-9e0ba8358099.png)

**Comment by monotek** [comment] 2016-11-18 23:49
Its also not possible to change the note from "example macro" to something else.
After saving a change it becomes "example macro" again.

**Comment by jacotec** [comment] 2016-11-19 17:22
@monotek Yap:

![zammad1](https://cloud.githubusercontent.com/assets/3321655/20457152/1f0a0dee-ae85-11e6-8b41-68d769545087.jpg)

**Comment by martini** [comment] 2016-11-30 22:38
@monotek Thanks, updating notes is fixed now.

@jacotec If "new tags" are disabled in admin interface and the "spam" tag was not used before, Zammad will not add the "spam" tag because it's a new tag. 

 -=> Should we change the behaviour to also allow adding tags define in triggers which not already exist?

**Comment by monotek** [comment] 2016-11-30 22:42
Maybe show an Error Message when creating non existend tag in triggers?

**Comment by muhammadn** [comment] 2018-02-06 14:29
@martini should we change to add the tags for old tickets as well?

**Comment by muhammadn** [comment] 2018-03-16 08:42
@jacotec I think what you want is to add a "trigger" when it is on a specific status and owner to set the tag to 'spam' for example.

Here is my example trigger:
<img width="741" alt="screen shot 2018-03-16 at 4 39 57 pm" src="https://user-images.githubusercontent.com/3349747/37511198-ee6d0436-2938-11e8-8d95-4503a94ef7cb.png">

This will set the tag to 'spamtag' when the ticket state is new or open.

**Comment by muhammadn** [comment] 2018-03-19 07:42
duplicate of #777

**Closed by muhammadn** 2018-03-19 07:42 UTC
Labels: admin area, bug, duplicate, ticket, verified
