### ISSUE TITLE
Trigger does not work correctly if type is used in special condition

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#3071] opened 2020-06-04 17:14 UTC
# Infos:

* Used Zammad version: 3.3

### Scenario

Two triggers:

A) 

CONDITIONS FOR EFFECTED OBJECTS:
Action = created
Type = web

EXECUTE CHANGES ON OBJECTS
Email: Public, Customer
Text: Ticket was created, here the T-number for reference...

B)

CONDITIONS FOR EFFECTED OBJECTS:
Action = created
Type = email

EXECUTE CHANGES ON OBJECTS
Email: Public, Customer
Text: You cannot open a ticket via email. Please use the web instead...

### Expected behaviour:

If someone uses the web client to create a ticket trigger A fires
If someone writes us an email to create a ticket trigger B fires

### Actual behaviour:

If someone uses the web first trigger A and B fires

### Suspicion:

If trigger A fires he created a new article of type email. Zammad seems to check trigger async. So when trigger B checks if his conditions match he can see the new article from trigger A already and thinks the ticket was created by email.

**Comment by MrGeneration** [comment] 2020-06-04 17:22
Sorry, but I can't reproduce this.
I created the following triggers:

![image](https://user-images.githubusercontent.com/6549061/83790432-79fbb400-a698-11ea-9130-1aa85bad17ef.png)


![image](https://user-images.githubusercontent.com/6549061/83790400-6f411f00-a698-11ea-8d5d-d3d32e2ef30c.png)

Then I login as customer and create a ticket. This is the result:
![image](https://user-images.githubusercontent.com/6549061/83790520-a0215400-a698-11ea-80c4-7f80d77fb496.png)


Only Trigger A fires - as expected.
I'm sorry, but I can't reproduce this ticket and suspect that there's something else going on. 

I thus am closing this issue.

**Comment by hiaz** [comment] 2020-06-04 17:55
@MrGeneration Are you sure that you are using a test env with multiple threads like WEB_CONCURRENCY="4" because only then processing triggers can be async I guess?

**Comment by MrGeneration** [comment] 2020-06-04 18:10
Yes I'm absolutely sure.

I double checked not being on develop, I'm on stable.
I also, just for you, ensures/enforced puma (web_concurrency) to move from "auto" to "4".

No change in my answer and inability to reproduce the issue you've described.
If you want you can double check this by spinning up a free trial instance on our hosted setup and try to reproduce it there.

Edit: As far as I'm aware working on triggers per ticket is not async - this shouldn't matter how many pumas are running.

**Comment by hiaz** [comment] 2020-06-05 07:46
@MrGeneration Thank you for trying to reproduce this issue. I will try to find a way to reproduce it in a "fresh" system.

**Comment by hiaz** [comment] 2020-06-05 10:02
I could not reproduce it on a fresh system but I think I have more details now:

As I found in the code zammad has the concept if recursive triggers which is default since version 3.0.

```
Execute trigger (05: auto reply on new phone and web tickets DE/1) for this object (Ticket:32232/Loop:1)
Execute trigger (20: Last contact customer/15) for this object (Ticket:32232/Loop:1)
Execute trigger (01: no new tickets via email DE/31) for this object (Ticket:32232/Loop:2)
```

Trigger 05 adds an outgoing email article. Then in loop 2 zammad still handles this ticket as created but sees the last article of type "email" now. Which leads to trigger 01 in loop 2.

I then just did:

```
zammad run rails r "Setting.set('ticket_trigger_recursive', false)"
``` 

Which leads to:

```
Execute trigger (05: auto reply on new phone and web tickets DE/1) for this object (Ticket:32234/Loop:1)
Execute trigger (20: Last contact customer/15) for this object (Ticket:32234/Loop:1)
Do not execute recursive triggers per default until Zammad 3.0. With Zammad 3.0 and higher the following trigger is executed '01: no new tickets via email DE' on Ticket:32234. Please review your current triggers and change them if needed.
```

This fixed the problem for me because I do not need any recursive trigger but I still think the behaviour is wrong and loop 2 should have a look at the first article and not the latest one in this case.

**Comment by mantas** [comment] 2020-06-05 10:13
Hey @hiaz ,

Could you check out `develop` branch and test your workflow w/ recursive trigger on soon-to-be-released 3.4?

I've a feeling this is related to https://github.com/zammad/zammad/issues/2923 may have been fixed already.

**Comment by MrGeneration** [comment] 2020-06-05 10:16
@mantas I'll handle this as part of the verification process for you, no problem!

**Comment by MrGeneration** [comment] 2020-08-26 09:03
Ugh sorry for the delay from my end.
This issue is a duplicate of issue #2472 which is why I'll be closing this issue.

@mantas it seems in Zammad 3.4 stable issue #2472 is fixed.

**Closed as completed by MrGeneration** 2020-08-26 09:03 UTC
Labels: duplicate
