### ISSUE TITLE
pending reached while tab is open won't close without asking you to discard changes

### ISSUE THREAD

**Issue by chesty** [zammad/zammad#2078] opened 2018-06-14 10:35 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): zammad-docker-compse

### Expected behavior:

* tab closes when you click the x

### Actual behavior:

* a box pops up asking you to cancel or discard changes

### Steps to reproduce the behavior:

* create a ticket, open it, don't make any changes other than set a pending reminder 5 minutes into the future. Leave the tab open. After the pending reminder executes try to close the tab by clicking the x

I'm not sure this is a bug, but it does confuse the agents and they are scared to click discard changes.

**Comment by chesty** [comment] 2018-06-15 05:11
I just tested this again and couldn't reproduce it. New theory is (and I don't even know if this is how zammad works) the delayed_job queue was backed up so the job to update the browser to switchthe ticket state to open hadn't reached the browser yet, so the browser was still showing the ticket in pending reminder.

**Comment by Newan** [comment] 2018-06-15 06:02
i can reproduce this bug:

* send an email
* open this ticket
* status is new but other state have same problem:
![image](https://user-images.githubusercontent.com/3693094/41452433-4e4260ce-7072-11e8-878d-3b21e31dde69.png)
* make NO changes
* **Close with the X in the left menu, important!**

![image](https://user-images.githubusercontent.com/3693094/41452416-3f280814-7072-11e8-93eb-6d9c535ed16e.png)

**Comment by thorsteneckel** [comment] 2018-06-15 06:41
I can't reproduce it that way @Newan - is there a Trigger in place? Does the state change if you reload the page? Is your websocket server running?

**Comment by Newan** [comment] 2018-06-15 06:46
i found it. we have the ITIL filed active:

![image](https://user-images.githubusercontent.com/3693094/41454118-84376db8-7078-11e8-8588-adce2b3fca44.png)

and this field is set on new issues to incedent

**Comment by thorsteneckel** [comment] 2018-06-15 06:56
Via a trigger? Please describe step by step what's going on so we can reason about it. Thanks!

**Comment by Newan** [comment] 2018-06-15 07:05
No, no trigger. steps are the same as upper this comment

we have the ITIL default Object active:

![image](https://user-images.githubusercontent.com/3693094/41454787-0d9f594c-707b-11e8-90d0-db980431de53.png)
This set the default value, and i think this is the change how wants to save

**Comment by chesty** [comment] 2018-06-15 07:08
is that related to https://github.com/zammad/zammad/issues/2042?

**Comment by thorsteneckel** [comment] 2018-06-15 07:10
Can someone of you please try to reproduce it in an [online instance](https://zammad.com/getting-started) and post the link?

**Comment by Newan** [comment] 2018-06-15 07:21
https://newan2.zammad.com/#ticket/zoom/1

**Comment by thorsteneckel** [comment] 2018-06-15 08:12
Agreed. Can be reproduced. It's strongly related to #2042 or even a duplicate, description of #2042 is not detailed enough. That's why I will keep this open.
A short summary what's going on/wrong:
The issue here is that the field is not required but doesn't provide a selection of no value. Which leads to the automatic selection of the first entry in the list of values. When closing the tab the selected value is recognized as a change which is causing the modal to show up. This is a bug.

**Comment by dominikklein** [comment] 2023-02-08 17:06
Can no longer reproduce the problem.

**Closed as completed by dominikklein** 2023-02-08 17:06 UTC
Labels: bug, verified, frontend, object manager attribute
