### ISSUE TITLE
HtmlSanitizer.cleanup timeout: Message cannot be displayed due to HTML processing issues

### ISSUE THREAD

**Issue by sts** [zammad/zammad#3742] opened 2021-09-16 10:11 UTC
### Infos:

* Used Zammad version: 4.1.0-1626440352.831837d2.buster
* Installation method (source, package, ..): package
* Operating system: Debian 10.10
* Database + version: Postgresql 12.7
* Elasticsearch version: 7.10.2
* Browser + version: Chrome 93

### Expected behavior:

* E-mails are parsed from IMAP and rendered in ticket

### Actual behavior:

* E-mail gets parsed from IMAP and are shown as: "This message cannot be displayed due to HTML processing issues. Download the raw message below and open it via an Email client if you still wish to view it." in the ticket view.
* The error log includes, errors such as:

```
ERROR -- : Could not process string via HtmlSanitizer.cleanup in 20 seconds. Current state: <div>
ERROR -- : Could not process string via HtmlSanitizer.cleanup in 20 seconds. Current state: <div dir="ltr">
ERROR -- : Could not process string via HtmlSanitizer.cleanup in 20 seconds. Current state: <p>Hi Antoine,</p>
```

### Steps to reproduce the behavior:

* Send larger e-mail conversations to zammad

Yes I'm sure this is a bug and no feature request or a general question.

It looks like the PROCESSING_TIMEOUT is hardcoded to 20 seconds. We don't process a large amount of e-mails so we would be ok if this takes longer than 20 seconds, but the e-mail would still be rendered in the ticket view.

```ruby
# lib/html_sanitizer.rb
class HtmlSanitizer
  LINKABLE_URL_SCHEMES = URI.scheme_list.keys.map(&:downcase) - ['mailto'] + ['tel']
  PROCESSING_TIMEOUT = 20
  UNPROCESSABLE_HTML_MSG = 'This message cannot be displayed due to HTML processing issues. Download the raw message below and open it via an Email client if you still wish to view it.'.freeze

  #.....

  def self.strict(string, external = false, timeout: true)
    Timeout.timeout(timeout ? PROCESSING_TIMEOUT : nil) do
        # do sanitization
    rescue Timeout::Error
      Rails.logger.error "Could not process string via HtmlSanitizer.strict in #{PROCESSING_TIMEOUT} seconds. Current state: #{string}"
      UNPROCESSABLE_HTML_MSG
  end
```

**Comment by sts** [comment] 2021-09-20 10:21
Patching the PROCESSING_TIMEOUT to a higher value in code has resolved the issue for us.

**Comment by MrGeneration** [comment] 2021-09-20 10:26
Without the original mail causing issue we can't help further. 
The timeout limit is not update save and has been brought in for very good and specific reasons.

We should thus address the root cause and not simply bump up limits.

**Comment by mgruner** [comment] 2021-09-24 07:33
@MrGeneration what would you suggest? This serves as a safety net against DOS via mails causing excessively long processing in our sanitizer. The original mail might show this behaviour or not, depending on hardware and load on the system.
We saw this timeout triggering in the CI even for extremely short mails, caused by system overload.

**Comment by sts** [comment] 2021-09-28 22:05
@MrGeneration I totally understand your point here, but under no circumstances I could share e-mails containing proprietary information. Also it wouldn't make sense to provide a modified e-mail; which makes it quite hard to help the Zammad project improve the Sanitizer.

I think to get valuable feedback here, it would need instructions on how to debug the class, people would need to wait until parsing issues occur again, or even be able to re-run it against an e-mail which was already delivered. Altogether it sounds pretty grievous to debug.

Having the hardcoded 20s limit also doesn't quite reduce the risk of rendering the system unavailable by an external attacker, as malformed mails could be easily generated and be sent a zammad system.

**Comment by MrGeneration** [comment] 2021-09-29 07:24
> I totally understand your point here, but under no circumstances I could share e-mails containing proprietary information

I can understand that as well

> Also it wouldn't make sense to provide a modified e-mail; which makes it quite hard to help the Zammad project improve the Sanitizer.

And I also agree on this point.
I'm afraid we can't further address this if we don't have original emails at this point that cover the case.

> Having the hardcoded 20s limit also doesn't quite reduce the risk of rendering the system unavailable by an external attacker, as malformed mails could be easily generated and be sent a zammad system

You may have slightly misunderstood the reaosns.
Earlier we had issues were customers would receive heavy mails with thousands of URLs inside.

The sanitizer would take far more than 30 minutes on processing this one mail.
This caused a huge drawback on all other delayed tasks of Zammad and effectively resulted in the customer(s) not being able to work.

----

Sorry, that's as detailed I get. I'll be closing this issue as unprocessible for now.
If you change your mind, send a mail to support [at] zammad [dot] com and reference this issue.

**Closed as completed by MrGeneration** 2021-09-29 07:24 UTC
Labels: can't reproduce
