### ISSUE TITLE
Dots in column to select an computer from idoit

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3172] opened 2020-08-30 09:40 UTC
### Infos:

* Used Zammad version: 3.4.x
* Installation method (source, package, ..): source
* Operating system: Ubuntu 18
* Database + version: MariaDB
* Elasticsearch version:
* Browser + version: Microsoft Edge

### Expected behavior:
No dots in column
*

### Actual behavior:
If I create a ticket and select a computer from my connected i-doit (v1.15 PRO) in the column are shown two dots. I thinks thats wrong, because I don't know for what it is
![image](https://user-images.githubusercontent.com/1473674/91656016-889a1180-eab5-11ea-8189-d25b63e9d348.png)

*

### Steps to reproduce the behavior:
create a ticket and select an item
*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by bolah2009** [comment] 2021-02-11 17:42
Created a PR that fixed this issue in #3406. It seems to be a duplicate of #3262

**Comment by MrGeneration** [comment] 2021-02-12 13:45
I do agree, this is technically the older issue, I'll still close it in favor for the other issue because it evolved further.
Thank you for taking the time to report this issue!

Duplicate of #3262

**Closed as completed by MrGeneration** 2021-02-12 13:45 UTC
Labels: duplicate
