### ISSUE TITLE
Fieldset behavior Firefox 86

### ISSUE THREAD

**Issue by AdamC1228** [zammad/zammad#3426] opened 2021-02-24 15:24 UTC
### Infos:

* Used Zammad version: 3.6.0 (1614149546.5c1934b4.centos7)
* Installation method (source, package, ..): Package
* Operating system: CentOS
* Database + version: Postgresql 9.2.24
* Elasticsearch version: 7.11.1
* Browser + version: Firefox 86.0 Windows 10

### Expected behavior:

* Fieldset elements such as the Sidebar Drop downs and Text input forms on the New Ticket pages should be the width of the parent element.

![expected_behavior](https://user-images.githubusercontent.com/13957003/109023048-6fe86e00-768a-11eb-8cb9-e3177d1b908f.PNG)

### Actual behavior:

* Fieldset elements are auto shrinking to be the minimum width similar to a flexbox-shrink. 

![Actual Behavior](https://user-images.githubusercontent.com/13957003/109023045-6fe86e00-768a-11eb-855d-96995d8334d4.PNG)

### Steps to reproduce the behavior:

* Update Firefox to firefox 86.0 on Windows. 
* Linux not tested. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-02-24 15:26
Duplicate of #3420

**Closed as completed by MrGeneration** 2021-02-24 15:26 UTC
Labels: duplicate
