### ISSUE TITLE
Deleting objects being used within SLAs shouldn't be possible

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2717] opened 2019-08-22 16:25 UTC
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Support-Ticket: #1052208 
* Might overlap with the following issue (in QA which is why I did not extend it): #2560 2560

### Expected behavior:

Deletion of objects that are used within any SLA is not possible.

### Actual behavior:

Deleting an object being used by any SLA is possible and will break the SLA. Within the backend, "SLA" will keep loading forever.
Only adding back the same attribute name will help.

### Steps to reproduce the behavior:

* create any custom object you like (I used select)
* create a SLA that uses your new fancy object
* delete your object
* try to edit your SLA settings
* finally add your object back to be able to edit your SLA settings

### Screencast:
![deleting-objects-assigned-to-sla](https://user-images.githubusercontent.com/6549061/63532117-40432d80-c50a-11e9-8a44-f404b868ea54.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2019-09-02 11:32
This is a duplicate of #2560. Closing now.

**Closed as completed by thorsteneckel** 2019-09-02 11:32 UTC
Labels: duplicate
