### ISSUE TITLE
Custom field not triggering for specific select item

### ISSUE THREAD

**Issue by 33Fraise33** [zammad/zammad#5408] opened 2024-11-12 13:36 UTC
### Used Zammad Version

6.3.1

### Environment

- Installation method: docker
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12
- Database + version:  postgres 15.8
- Elasticsearch version: 8.15.2
- Browser + version: Chrome 130.0

### Actual behaviour

- Creating a workflow with creationg and edit mask both enabled with condition set to: 
  -> custom_select_field <is, is not, is set, changed to> <item(s)>
- This does not trigger. 
- Setting this to "has changed" does trigger but is unwanted. 

### Expected behaviour

- matching with "is" or "changed to" should work for manually created select objects
- this limits custom flows a lot. mathing on groups work, but as soon as you want to match on a custom type for a group you can not unhide fields specific for that custom type anymore. 

### Steps to reproduce the behaviour

- Create a select object with 2 options, set as shown or not shown
- Create another object (can be text or something else) set as not shown
- update database
- create workflow: 
![Image](https://github.com/user-attachments/assets/ee99f969-95d5-4dc8-b3d3-9525e77dcb37)

This seems similar to: #4752 which has been closed for not able to reproduce. 

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by 33Fraise33** [comment] 2024-11-12 13:37
I have played with select key and display (making sure they are exactly the same for example) but this does not help.

**Comment by MrGeneration** [comment] 2024-11-12 13:38
> 6.3.1

Please update to ensure that this is not already working in a stable Zammad instance. Thank you

**Comment by JonasGe** [comment] 2024-11-12 14:10
We are experiencing the same issue on 6.4.0-1731400652.be4ce4cb.jammy

Custom object (single select) does not seem to trigger workflow when a value is selected.

Other (older?) custom selects are able to trigger the workflow.

We have also tried, same as @33Fraise33 , to match keys/values, lowercase, no numbers, less entries etc but this doesn't seem to have any effect.

**Comment by 33Fraise33** [comment] 2024-11-13 10:22
For me this is now working in 6.4, not sure why it is not working for @JonasGe

**Comment by rolfschmidt** [comment] 2024-11-14 09:34
Hey @33Fraise33 and @JonasGe ,

I can't reproduce the issue with your steps. Maybe your configuration is more complex or the root of the issue is somewhere else. Also, the #4752 is very different to this, I see no relation yet.

Without a support contract it is very hard to help out here. I can offer you a debug account for testing so we could try to reproduce it on our hosted instances.

Feel free to register and ping me via ticket so I can increase your permissions.

https://issue5408.zammad.com/#signup

I also tested your steps, but for me it looks fine.

https://github.com/user-attachments/assets/7f7f9931-2044-4702-80fe-875f241dbc3e

**Comment by JonasGe** [comment] 2024-11-14 13:01
I found the cause of our issue: a space behind the keys in the object. Probably due to copy/pasting the keys from somewhere else.
So while it's completely our own fault and easily fixable, would it be possible to trim these inputs in a future update?

**Comment by 33Fraise33** [comment] 2024-11-14 13:04
For us the fix was just updating, we had the issue with multiple single select objects, updating to 6.4 resolved it (from 6.3.1). 

Good to hear you also resolved it.

**Comment by fliebe92** [comment] 2024-11-14 13:33
Hi @33Fraise33, hi @JonasGe. Glad to hear that you were able to resolve it, and now it's working fine. Closing for now. :)

**Closed as completed by fliebe92** 2024-11-14 13:33 UTC
Labels: question, waiting for feedback
