### ISSUE TITLE
EMails cannot be imported from imap

### ISSUE THREAD

**Issue by forgeOneHQ** [zammad/zammad#2415] opened 2018-12-21 14:28 UTC
Infos:

    Used Zammad version: 2.8
    Installation method (source, package, ..): package
    Operating system: Ubuntu Server 16.04 LTS
    Database + version: 10.0.36-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04
    Elasticsearch version: 5.6.9
    Browser + version: any

Error:
Channel: Email::Account in Can't use Channel::Driver::Imap: #<Net::IMAP::ResponseParse

Log:
[2018-12-21T13:33:13.719440 #1027-70334085745740] ERROR -- : Can't use Channel::Driver::Imap: #<Net::IMAP::ResponseParseError: unexpected token LPAR (expected QUOTED or LITERAL)>
E, [2018-12-21T13:33:13.719634 #1027-70334085745740] ERROR -- : ["/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:3421:in `parse_error'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:3273:in `match'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:3205:in `string'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:3186:in `nstring'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:3144:in `address'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:3116:in `address_list'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:2344:in `envelope'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:2325:in `envelope_data'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:2300:in `msg_att'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:2280:in `numeric_response'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:2222:in `response_untagged'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:2198:in `response'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:2124:in `parse'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:1219:in `get_response'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/imap.rb:1127:in `receive_responses'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0
/net/imap.rb:1109:in `block in initialize'", "/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"]

I think the issue is coming up since zammad version 2.8.X

The mails are related from plesk, which use < ! - as example in the mail as subject and content.

As soon as I delete those e-mails and send a usual one without those symbols, emails are imported.
![mailexample](https://user-images.githubusercontent.com/15981620/50347191-0661f780-0535-11e9-814b-49326fc32bd4.jpg)

To say, with 2.7.X I didn't have that troubles.

Yours faithfully,
Mathias

**Comment by MrGeneration** [comment] 2018-12-21 14:31
Please use the provided issue template and fill in the missing information.

**Comment by forgeOneHQ** [comment] 2018-12-21 14:42
@MrGeneration I checked one from your previous tickets, working now? Or where can I get it?

**Comment by MrGeneration** [comment] 2018-12-21 14:57
Hey,

thanks for the reply, in your case, please supply/edit the following information:

```
Installation method (source, package, ..): 
Database + version: 
Elasticsearch version: 
```

**Comment by forgeOneHQ** [comment] 2018-12-21 15:06
@MrGeneration  thanks, updated! :)

**Comment by martini** [comment] 2018-12-21 15:25
Just a quick note from my side. @talheim-it can you add this email which is not processable to this issue? 

And:

1) For me it looks that the mail header is broken. And the IMAP server delivers non parsable content.

2) The error comes from `Net::IMAP::ResponseParseError` which is a ruby gem (no Zammad code). This gem is the same version as it was in Zammad 2.7. So it should work/not work as it was in Zammad 2.7.

**Comment by forgeOneHQ** [comment] 2018-12-21 15:56
@martini ,

I only have this issue with directly plesk mails.

A bit curious.

I got an e-mail from zammad directly I answered to check.

I can also send you an example if you want.

Just do not want to publish here.

Yours faithfully,
Mathias

**Comment by MrGeneration** [comment] 2018-12-21 16:12
I am sorry.

We can't reproduce this issues, all header seem to be fine.
We suspect an issue with your E-Mail-Server. As suggested by E-Mail, you could try another IMAP-Server for verification regarding this case.

I'll close this issue for now, if you however are able to consistly reproduce this, we'll appriciate any information on how to reproduce this, I'll check again in this case.

**Closed as completed by MrGeneration** 2018-12-21 16:12 UTC
Labels: can't reproduce, mail processing
