### ISSUE TITLE
New client acces E-Mails for each REST-Request

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1313] opened 2017-08-01 10:23 UTC
Hello, hello 😄 

I have the problem, everytime I make a request out of a script, I get an e-mail saying that I login in from a new device.
I've seen your post https://github.com/zammad/zammad/issues/1208 to that.
Sadly the update didn't fixed the problem at my server. I just installed the newest 1.5.x Version from the repository.

Greetings

**Comment by martini** [comment] 2017-08-01 11:27
Hi @MamoulianDelacroix 

what version exactly have you installed? (also restarted the processes)

Can you reproduce it on a https://zammad.com/getting-started instance? I can't reproduce it anymore. We also wrote a bundle of unit tests for it. 

Thanks!
 -Martin

**Comment by MamoulianDelacroix** [comment] 2017-08-01 11:52
Ok, nevermind.
I restarted everything on the server, except the linux itself, which I did now.
And now the problem is gone. 🎉 
Sorry for upseting the apple cart and thanks a lot for your help as always !😄

**Comment by MamoulianDelacroix** [comment] 2017-08-01 12:29
I'm sooooo sorry 😞 
The problem is back.
Our zammad is doing some strange things right now.
Where can I get the correct an full version number?
In /opt/zammad/VERSION stands only 1.5.x
I'm trying to reproduce the problem right now with a test instance.

**Comment by martini** [comment] 2017-08-01 12:31
> Where can I get the correct an full version number?

It's the version of your installed package (we build on every bugfix). 

On centos e. g. `rpm -qi zammad`

**Comment by martini** [comment] 2017-08-01 12:32
If you have remote login, just let me know for fast support. And what the problem is. support at zammad dot com

**Comment by MamoulianDelacroix** [comment] 2017-08-01 12:33
It is version 1.5.0-1501408728.d0ac4461.xenial
No sorry, right now there is no remote login possible. The server is in our dmz and right now only accessable internal.

**Comment by martini** [comment] 2017-08-01 12:35
In case... let me know what your issue is... an send it to support at...

**Comment by MamoulianDelacroix** [comment] 2017-08-01 13:06
so I was able to reproduce the problem in one of your test instances.
But I also send you an e-mail with all informations.

**Comment by martini** [comment] 2017-08-01 13:37
@MamoulianDelacroix issue #1208 is fixed in develop/master for next release. But not in 1.5 (the change was too big).

In case - you can disable the whole device logging by removing user_preferences.device permission for agent+admin roles:

```
rails c

admin = Role.find_by(name: 'Admin')
admin.permission_revoke('user_preferences')
admin.permission_grant('user_preferences.password')
admin.permission_grant('user_preferences.notifications')
admin.permission_grant('user_preferences.access_token')
admin.permission_grant('user_preferences.language')
admin.permission_grant('user_preferences.linked_accounts')
admin.permission_grant('user_preferences.avatar')
admin.permission_grant('user_preferences.calendar')

agent = Role.find_by(name: 'Agent')
agent.permission_revoke('user_preferences')
agent.permission_grant('user_preferences.password')
agent.permission_grant('user_preferences.notifications')
agent.permission_grant('user_preferences.access_token')
agent.permission_grant('user_preferences.language')
agent.permission_grant('user_preferences.linked_accounts')
agent.permission_grant('user_preferences.avatar')
agent.permission_grant('user_preferences.calendar')
```

 -Martin

**Comment by martini** [comment] 2017-08-01 13:47
To complete this issue. After upgrading to Zammad 2.0 you should restore the permission for the roles  with the following:

```
rails c

admin = Role.find_by(name: 'Admin')
admin.permission_grant('user_preferences')
admin.permission_revoke('user_preferences.password')
admin.permission_revoke('user_preferences.notifications')
admin.permission_revoke('user_preferences.access_token')
admin.permission_revoke('user_preferences.language')
admin.permission_revoke('user_preferences.linked_accounts')
admin.permission_revoke('user_preferences.avatar')
admin.permission_revoke('user_preferences.calendar')

agent = Role.find_by(name: 'Agent')
agent.permission_grant('user_preferences')
agent.permission_revoke('user_preferences.password')
agent.permission_revoke('user_preferences.notifications')
agent.permission_revoke('user_preferences.access_token')
agent.permission_revoke('user_preferences.language')
agent.permission_revoke('user_preferences.linked_accounts')
agent.permission_revoke('user_preferences.avatar')
agent.permission_revoke('user_preferences.calendar')
```

**Closed by martini** 2017-08-01 13:47 UTC
Labels: question

**Comment by MamoulianDelacroix** [comment] 2017-08-01 13:48
@martini thanks a lot! Great job! 
That solved my problem.
🎉
