### ISSUE TITLE
Default not set for 'select' objects

### ISSUE THREAD

**Issue by chessmango** [zammad/zammad#2506] opened 2019-03-05 08:54 UTC
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: PostgreSQL 9.5.14
* Elasticsearch version: 5.6.15
* Browser + version: Chrome 72, Firefox 65 

### Expected behavior:

When using 'select' format for a ticket object, setting the default key sets this for tickets created from any channels.

### Actual behavior:

Seemingly as of 2.9 (issue wasn't present beforehand), tickets created manually from Zammad do keep the default key as set here, but other channels seem not to. In my case I only use the email channel, but any tickets created this way have a blank '-' set instead of the default.

### Steps to reproduce the behavior:

Create ticket via channel other than web UI (email in this case) - ensure there's a 'select' object for tickets that has a default set.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-03-05 14:52
This is a duplicate of https://github.com/zammad/zammad/issues/1653

**Closed as completed by MrGeneration** 2019-03-05 14:52 UTC
Labels: duplicate, needs verification
