### ISSUE TITLE
relative date-setting for macros

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#1199] opened 2017-06-23 10:01 UTC
Zammad version 1.5.x

### Actual behavior:
If a macro is created with the status "pending reminder", the "pending till" field can only be set to an absolute value - that is, a concrete date + time.

### Expected behavior:
A relative setting of the date, e.g. "3 days"

T#105398

**Comment by thorsteneckel** [comment] 2017-06-23 10:03
Duplicate of #864.

**Closed by thorsteneckel** 2017-06-23 10:03 UTC
