### ISSUE TITLE
Rescan LDAP/AD Users for organisation assignment

### ISSUE THREAD

**Issue by ToubieObie** [zammad/zammad#1622] opened 2017-11-08 12:09 UTC
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: DEB
* Operating system: debian 8 64-bit
* Browser + version: Firefox 56.0.2

### Expected behavior:

* It would verry nice if you add a "rescan" function that the Organisations become automatic assigned based on the E-Mail Adress.

### Actual behavior:

* Assigmend is only gona happen on new users

### Steps to reproduce the behavior:

* Install Zammad ;)

**Comment by tdavison1** [comment] 2017-11-09 10:56
I have a very similar question as I occasionally have users change job (therefore they change group in AD, maybe from agent -> user) however we have to update Zammad manually to reflect this change.

**Comment by thorsteneckel** [comment] 2017-11-10 12:10
Hi @tdavison1 - I don't see the relation to this issue. Zammad should detect changes on the users Group relation and reflect them back on the Zammad user on the next run. If this is not the case this is a bug and should be addressed in a new issue.

**Comment by thorsteneckel** [comment] 2018-04-23 18:09
This is a duplicate of #1512

**Closed by thorsteneckel** 2018-04-23 18:09 UTC
