### ISSUE TITLE
Order of new created object attributes are unordered

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3799] opened 2021-10-11 06:57 UTC
### Infos:

* Used Zammad version: 5.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* have new object attributes the same order as created (or even better, allow to set position via UI)

### Actual behavior:

* new object attributes are unsorted (backend is always assigning the same position)

### Steps to reproduce the behavior:

* create fiel b_test, a_test and verify thew order of the attributes

**Comment by thorsteneckel** [comment] 2021-10-11 07:21
Duplicate of #294

**Closed as completed by thorsteneckel** 2021-10-11 07:21 UTC
Labels: duplicate
