### ISSUE TITLE
pending ticket create new ticket number

### ISSUE THREAD

**Issue by visdim** [zammad/zammad#734] opened 2017-02-05 16:33 UTC
Hi,

if I set a ticket to pending and customer write a new ticket (with ticketnumber in subject), than a new ticket is created instead sorting the new reply from customer to existing ticket which is in email subject.

is this a feature or a Bug or have I not seen any setting?

* Used Zammad version: 1.2.0

**Comment by martini** [comment] 2017-02-05 16:36
Hi @visdim 

this sounds link an bug. But it's working fine for me (follow up of pending tickets is sorted to existing ticket and state is changing from "pending reminder" to "open"). Can you setup a system from https://zammad.com/getting-started and show me how to reproduce if?

 -Martin

**Comment by visdim** [comment] 2017-02-05 16:42
sorry, just tested following:
- deleted customers reply
- changed status of ticket to open
- copied mail from second mailaccount which collect mail-copies

and again a new ticket has been created.

Sorry, my theory was wrong, seems something todo with customers email,
looks like customer has changed his mail client to his mobile phone, could this maybe the reason why a new ticket is created?

**Comment by martini** [comment] 2017-02-05 16:45
As long the Ticket# is in subject, any email will be an follow up.

Is the Ticket# in the customer reply?

**Comment by visdim** [comment] 2017-02-05 16:46
yes, it is in the subject.
what else maybe could produce the issue, not tested yet, is, that I insert a non public reply inside the ticket

**Comment by visdim** [comment] 2017-02-05 16:51
hmm, tested again after deleted the internat comment, same result, new ticket was opened.
I mailed you the mail which makes trouble as attachement, maybe you can find something there...

**Comment by martini** [comment] 2017-02-05 16:53
An example in a Zammad instant would be great to find the reason. Can you create a new instant or can I have access to an existing one?

**Comment by martini** [comment] 2017-02-06 11:20
@visdim Can you also send me the first email answer of the customer as source email (like the one from yesterday)?

**Comment by martini** [comment] 2017-02-06 11:26
@visdim And the console output of the following would be nice!

`zammad run rails r "p Setting.get('ticket_hook')"`

**Comment by visiondimension** [comment] 2017-02-06 11:34
[root@Zammad-VM conf.d]# zammad run rails r "p Setting.get('ticket_hook')"
"VD-Ticket#"
[root@Zammad-VM conf.d]#

**Comment by visiondimension** [comment] 2017-02-06 11:35
customer mail sent to support@....

**Comment by martini** [comment] 2017-02-06 11:41
Thanks a lot. One more output:

`zammad run rails r "p Group.find_by(name: 'Users').follow_up_possible"`

**Comment by visiondimension** [comment] 2017-02-06 11:43
[root@Zammad-VM conf.d]# zammad run rails r "p Group.find_by(name: 'Users').follow_up_possible"
"yes"
[root@Zammad-VM conf.d]#

**Comment by rolfschmidt** [comment] 2018-02-06 14:53
Hi @visdim ,
i'm sorry, it is not possible for us to reproduce the problem by now. Could you please create a free test instance on https://zammad.com/getting-started to reproduce the bug there?

Then we could have a try to debug the problem there. Else i see no way how we could solve this problem.

If you have any questions regarding the test instance, feel free to ask.

Best regards,
Rolf

**Comment by thorsteneckel** [comment] 2018-02-12 17:05
Since this issue had its first birthday last week I'm happy to close it 🍰 Feel free to reopen with detailed instructions on how to reproduce or provide a free hosted instance where we can reproduce it. Thanks!

**Closed by thorsteneckel** 2018-02-12 17:05 UTC
Labels: question
