### ISSUE TITLE
change role name Customer to different, Agent can not add a new customer via web

### ISSUE THREAD

**Issue by MBekspert** [zammad/zammad#1609] opened 2017-11-03 14:30 UTC
### Infos:

* Used Zammad version: 2.1.0-15095477
* Used Zammad installation source: package
* Operating system: Debian 9.2 (4.9.0-4-amd64)
* Browser + version: Firefox 56.0.1

### Expected behavior:

* user have role Agent, on New Ticket, Create new Customer, fill in all fields, press 'Create', system create new user with role customer (this role is default at singup)

### Actual behavior:

* pressing 'Create' does nothing

### Steps to reproduce the behavior:

* in GUI, Roles Management, Role Customer, edit. Change Name* : 'Customer' to something else, eg 'Klient' (Polish translation ;) )

**Comment by MrGeneration** [comment] 2018-12-24 10:43
Hey,

thanks for your post.
I can't reproduce this on a current Zammad installation, could you please check if it still persists and if so give me an detailed instruction how to do so?

I changed "Customer" => "Strange PPL" - reloaded the WebApp and tried to create a new Customer without choosing any roles. I also tried this as normal agent, still works?

**Comment by MrGeneration** [comment] 2019-01-25 12:13
We've received no further feedback and thus can't verify this as a bug.
Closing now.

**Closed by MrGeneration** 2019-01-25 12:13 UTC
Labels: can't reproduce
