### ISSUE TITLE
strange behaivor by failed ldap sync

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#2093] opened 2018-06-22 09:13 UTC
### Infos:
* Used Zammad version: 2.5
* Installation method (source, package, ..): package
* Operating system: Ubungu 18.04
* Database + version: psql (PostgreSQL) 10.4 
* Elasticsearch version: 5.6.10

Our LDAP-integraion fails to sync some useraccount.
Everytime it fails these users are set to active = false in zammad.
But the most strangley thing about it is, that in that users history is written down that an random agent has changed that attribute.

**Comment by thorsteneckel** [comment] 2018-06-22 09:18
Hi @MamoulianDelacroix - Do you know the cause why it fails to sync those accounts? What's written in the logs? Is it always the case?

Do you mean random random or always the same agent?

Zammad deactivates all users that were synced once from the LDAP and are not included in the current sync. This covers failing users (in some cases, depending on when the error happens).

**Comment by MamoulianDelacroix** [comment] 2018-06-22 09:42
Hi @thorsteneckel 

> Do you know the cause why it fails to sync those accounts? What's written in the logs? Is it always the case?

That I'm still investigating. So far I'm looking for a useable debug log.

> Do you mean random random or always the same agent?
Until now I didn't found any specific pattern which agent he picks. But during my tests today he always used my user. In the past there are other agents recorded too. Something like this:
User A:
07.06.18 07:50 agent a changed active to false from true
User B:
07.06.18 07:50 agent c changed active to false from true

**Comment by thorsteneckel** [comment] 2018-06-22 10:49
I can provide a script which will print out every detail on what's happening into a separate log file.

Regarding the changing user: We'll try to reproduce this. Are these automatically started imports or were they started via the admin interface button?

**Comment by MamoulianDelacroix** [comment] 2018-06-22 11:33
> I can provide a script which will print out every detail on what's happening into a separate log file.

That would be awesome

> Regarding the changing user: We'll try to reproduce this. Are these automatically started imports or were they started via the admin interface button?

Both. Today I startet some import jobs manually. In the past, were this happend

> User A:
07.06.18 07:50 agent a changed active to false from true
User B:
07.06.18 07:50 agent c changed active to false from true

These was a automatically import job.

**Comment by MamoulianDelacroix** [comment] 2018-06-22 13:59
In addition, I just run the follwoing command on the zammad ruby shell:
``User.where(active: '0').update(active: '1')
``
This worked as charm, all users are back active, but the strange behavoir strikes one more time:

> User A:
22.06.18 15:55 agent a changed active to false from true
User B:
22.06.18 15:55 agent c changed active to false from true
User C:
22.06.18 15:55 agent d changed active to false from true

**Comment by thorsteneckel** [comment] 2018-06-22 18:08
And here comes the debug script. Please be aware of that it may take some time to run in because of the extensive logging. To run it please do the following:

1.) Create a file called `debug_issue.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_issue.rb` or `rails r debug_issue.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_issue.rb` file

```ruby
# redirect app logging
Rails.logger = Logger.new('debug.log').tap do |logger|
  logger.level = :debug
end
ActiveRecord::Base.logger = Rails.logger.clone


ImportJob.create(name: 'Import::Ldap', payload: {}).start


require 'mixin/rails_logger'

module Mixin
  module RailsLogger
    def self.logger
      @logger ||= Logger.new(log_to).tap do |logger|
        logger.level = :debug
      end
    end

    def self.log_to
      'debug_issue.log'
    end
  end
end

import_job = ImportJob.create(name: 'Import::Ldap')

result = Sequencer.process('Import::Ldap::Users',
                           parameters: {
                             import_job: import_job
                           })

import_job.save!

Rails.logger.info JSON.pretty_generate(import_job.reload.attributes)
```

**Comment by MamoulianDelacroix** [comment] 2018-06-26 07:55
@thorsteneckel 
I wrote you an email to support@zammad.com with the debug logs.

**Comment by thorsteneckel** [comment] 2018-07-04 07:33
Hi @MamoulianDelacroix - as discussed via the Ticket #1021818 this is caused by the fact that there is no DN <-> Zammad Role mapping entry for those users and that [users without a mapping entry should get skipped (existing users will get deactivated)](https://github.com/zammad/zammad/blob/5bbff1076412c4e7c4a1f09b13fa7cb1bdcfa114/lib/sequencer/unit/import/ldap/user/attributes/role_ids/unassigned.rb#L30). This can only get resolved by providing a mapping entry since the LDAP is the leading source of truth if configured (with a mapping).

Regarding the wrong user author of the active attribute change you described earlier: I created the issue #2111 for that and we will resolve it.

Additionally I found another issue (which is only technical) and created issue #2110 for that.

I'll close this issue now. We can discuss it further via the support ticket. Thanks for helping figuring things out 👍

**Closed as completed by thorsteneckel** 2018-07-04 07:33 UTC
Labels: question
