### ISSUE TITLE
translation-error in subcategories

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2689] opened 2019-08-02 13:51 UTC
### Infos:

* hosted Version: 3.1.x
* Browser + version:  Chrome (75.0.3770.100) and Safari (Version 12.1.1)

### Expected behavior:

* When displaying an article in a subcategory, all categories above it should be listed in the same language.

### Actual behavior:

* In the public area, the subcategory directly above is not translated:

![image](https://user-images.githubusercontent.com/22768032/62374215-bf60c980-b53b-11e9-8144-5ff4d6208f41.png)

![image](https://user-images.githubusercontent.com/22768032/62374239-d0a9d600-b53b-11e9-97f2-8447fe2cdbf3.png)

It seems the missing translation only affects the previous category. All others will be translated correctly.
![image](https://user-images.githubusercontent.com/22768032/62374612-a573b680-b53c-11e9-97fc-745c1388df1d.png)

In the Zammad UI, the translation works as intended:

![image](https://user-images.githubusercontent.com/22768032/62374434-401fc580-b53c-11e9-97d8-789e465b8c75.png)

### Steps to reproduce the behavior:

* Create at least 2 subcategories
* Translate all categories into another language
* go to the public interface, select the second foreign language and select the 2nd subcategory

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment] 2019-12-27 14:12
@KoJie looks like it was solved at some point. I cannot reproduce it anymore. Could confirm if it works fine now?

**Comment by KoJie** [comment] 2019-12-27 15:35
This is correct, I can confirm that. 
I can no longer reproduce the translation error 👍

**Comment by mantas** [comment] 2020-01-07 06:26
Good to hear. Closing as no longer relevant then.

**Closed as completed by mantas** 2020-01-07 06:26 UTC
Labels: can't reproduce
