### ISSUE TITLE
Zammad restore fails on CentOS

### ISSUE THREAD

**Issue by mrcschilling** [zammad/zammad#1363] opened 2017-08-24 09:25 UTC
### Infos:

* Used Zammad version: latest stable 1.5
* Used Zammad installation source: (source, package, ...) centos yum package
* Operating system: centos7
* Browser + version: not important

the zammad_restore.sh script uses the gzip -k flag, which is not supported in standard centos 7 gzip version, because of that the database is not restored.

edit -----
the problem is caused by zammad/contrib/backup/functions
function restore_zammad()
lines 158 and 161

the gzip -k flag seems to be platform dependant

**Comment by hanneshal** [comment] 2017-08-24 15:16
Duplicate of issue #1312

**Closed by hanneshal** 2017-08-24 15:16 UTC
Labels: duplicate
