### ISSUE TITLE
Notification Settings not available if only working with roles

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad#2676] opened 2019-07-18 11:54 UTC
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): Web
* Operating system: -
* Database + version: -
* Elasticsearch version: -
* Browser + version: Chrome, latest

### Expected behavior:

* If a user is an agent of a certain role and has READ access to a specific group he should be able set the option to receive notifications in for this group or not

### Actual behavior:

* If working exclusively with roles, agents cannot set their groups for which they want to receive notifications for

### Steps to reproduce the behavior:

* see screenshot:

![image](https://user-images.githubusercontent.com/3634653/61455350-8c2b1180-a963-11e9-9c22-0c2358540d17.png)

**Comment by MrGeneration** [comment] 2019-07-18 16:34
Sorry, but I believe that this is rather a technical question than a real bug.

Before I get to why, a small hint: Since some Zammad-Versions it's no longer supported to have a tik in "read, write, change, overview and full" - it should be "read, write, change and overview" or "full" (because full is exactly that plus some topping). You proberbly wanna fix that.

Now to the reason I believe this is not a bug:
If you only have read rights, Zammad will **not** send any notifications to your agent. That's why it's perfectly fine to not give the agent the option to exclude this.

Above also applies if you enable read, write and change - Zammad will still not send any notifications to the user. Also, the overviews will not show anything as well.

Even overview right does not change this.

**Partial Edit:**
I've been testing above with user based rights and can't verify that this feature only works on roles. :-X
My guess here is the no longer supported form of user rights ticket.
#--

You need the full right to receive notifications. This works as designed. :-)

For the next time, please post technical questions over at our community (https://community.zammad.org) or drop us a mail **if you're a hosted or service contract customer**.

Please also post feature request on our community, Github is not the right place for this. :)

Still, thanks for your time and write up!

Closing now.

**Closed as completed by MrGeneration** 2019-07-18 16:34 UTC
Labels: question
