### ISSUE TITLE
Duplicate Ticket Entry by Notification Master on Reply

### ISSUE THREAD

**Issue by chriskyndrid** [zammad/zammad#2898] opened 2020-01-17 21:44 UTC
### Infos:

* Used Zammad version:zammad-3.1.0
* Installation method (source, package, ..):zammad-3.1.0-1572420711.b7bfdcd4.centos7.x86_64
* Operating system:zammad-3.1.0-1572420711.b7bfdcd4.centos7.x86_64
* Database + version: Consistent with RPM package for version in question
* Elasticsearch version: elasticsearch-7.4.2-1.x86_64
* Browser + version: Chrome

### Expected behavior:

Replying to a ticket causes a single entry for the reply in the ticketing window.

### Actual behavior:

Entry is duplicated by notification master after Agent replies to the inquiry.. 
![Issue Picture](https://user-images.githubusercontent.com/34988129/72648223-5fb27b00-392f-11ea-923a-b5688bb99482.png)

### Steps to reproduce the behavior:

Today we had a need adjust the password associated with the Zammad mailbox being used for support ticketing. Initially we failed to enter the proper password. We then corrected the error and set the new password. At some point later, the Notification Master picked up the test Zammad tickets and closed them

From that point forward we've been receiving inline entries in tickets from the Notification master. It's not entirely clear to me whether or not you can duplicate the behavior simply by following the aforementioned, as we do not have a dev server to test against. This, however, was the sequence of events that lead to this issue. 

At this point, I've attempted to rebuild the Zammad cache, restart zammad, and rebuild the elastic search cache to no avail. I've also tried altering the user account associated with the E-Mail Address the notification master uses, along with removing and readding the acceptable e-mail addreses Agents can use, again to no avail. I cannot determine why Zammad is no longer suppressing these entries. I suspect it has something to do with some flag associated with the notification master and it's relationship to an actual e-mail account in the customer list??? 

Any thoughts on the matter are appreciated. 

Chris

**Comment by MrGeneration** [comment] 2020-01-17 22:13
Sorry but this is rather a technical question.
You seem to have a mail address in your recipient list (incoming) that is associated to an mail alias of one of your Zammad mailboxes.

As Zammad doesn't seem to know that it it's its address, it does reply to that mail which causes you to reply to your ticket system (beside of  the customer).

Please consult the Community for further technical questions, this is not a bug.
Configure your aliases in zammad to solve this issue.

Closing now.

**Closed as completed by MrGeneration** 2020-01-17 22:13 UTC
Labels: question

**Comment by chriskyndrid** [comment] 2020-01-17 22:14
What would cause this to magically start happening after the adjust to the password this morning? We haven’t changed any other configuration detail. 

Chris

**Comment by chriskyndrid** [comment] 2020-01-17 22:19
If this is associated with an alias as you suggest, than it was the automated dispatch email that Zammad sends to verify outgoing email that would have caused the creation of a corresponding account. Prior to the adjustment to the credentials of the email server we did not have an issue, and the issue began I immediately after. That doesn’t seem like desired behavior.

Chris

**Comment by MrGeneration** [comment] 2020-01-17 22:32
Please use the community at https://community.zammad.org

If this "magically" appeared, either your mail you received or the way your agent worked changed.
Github is the wrong place for technical questions.

**Comment by chriskyndrid** [comment] 2020-01-17 22:52
Neither of those conditions is true as you describe, both remained the same. There are two emails boxes associated with a single mail server that feed the same ticketing system, which remained the same prior and post modification of the credentials. That’s what happened.

This may not make sense to you, but It’s what took place. I’ve been writing software for twenty years and I learned a long time ago not to draw any concrete assumptions about what is or isn’t the case when users report problems with my code. It’s not possible for me derive every permutation of every potential outcome and problem scenario, even when I’m an authority(the principle author) on the software. So I resolved to simply listen and take a practical approach to investigation. Maybe this is some edge scenario where some unexpected behavior did occur that you didn’t anticipate. Maybe it’s some serendipitous situation where some random chance correlation occurred externally that drove it independent of your code. That said, to simply dismiss it as some configuration issue on the user side, when no other causative basis exists and your user has clearly stated no other change was deliberately made isn’t a good practice.

I realize you’re doing this for free. I also realize you have a commercial element, and we could potentially be a commercial customer at some point. I appreciate your community based efforts, but I don’t think it’s good practice to be dismissive of scenarios folks report, even if you don’t believe they could having anything to do with your code. 

Lastly, with respect to your comments on GitHub and technical issues, I’m not sure I follow. I assume you’re referring to support related inquiries whereby a determination is made that it isn’t a software issue. It’s fine for you to suggest GitHub should be focused more on development related items, but while getting to the root of those issues you’re going to travel through a lot of support related inquires, and that happens all the time. GitHub is a strong community in that regard and stating empirically it’s not a place for technical questions I don’t think is accurate.

Thanks again for your time and efforts with Zammad.

Chris

**Comment by thorsteneckel** [comment] 2020-01-18 11:50
Hey Chris,

thanks for your kind words. I respect your experience and effort in writing things down. However, @MrGeneration is one of the most experienced Zammad administrators out there with a deep technical knowledge. Additionally I second his assessment of the situation. So our position won't change.

To give you some background information: If it's not immediately clear that an issue is a bug and/or we can't reproduce the described behavior we move the discussion to the community. This allows us to go into the details and play Question-Answer ping pong without distracting the maintainers and the other > 100 watchers of this repository. You surely will know from your experience how hard it is to focus when there's an email dropping in every 2 minutes that needs to be evaluated for relevance.
Fun fact: More than 99% of technical questions never come back as an actual issue. Actually there are more issues created from fruitful discussions that have started over at the community. I think this is just great.

I hope this makes things clearer. If not please create a thread over in the community and refer to me and I'm happy to elaborate our approach of maintaining OSS in great detail.

@MrGeneration and all the other great folks over at the community will find your post and help you to get to the root cause of it. If it's actually a bug we'll fix it. It's that easy.

Closing and locking now.
