### ISSUE TITLE
When ticket created via Telegram, default reply should be Telegram

### ISSUE THREAD

**Issue by Frankkkkk** [zammad/zammad#2891] opened 2020-01-14 20:34 UTC
### Infos:

* Used Zammad version: Latest one from zammad-docker-compose
* Installation method (source, package, ..): docker-compose
* Operating system: docker

### Expected behavior:

When a new ticket is created with a alternative channel (i.e. Telegram, Twitter, ...), then the default reply type should be of the same channel, and not "note".

Indeed, "lambda users" won't get the difference and reply with a note 

### Actual behavior:

* The default reply is a note

### Steps to reproduce the behavior:

* Add a Telegram bot and send a message to it
* Reply to the ticket from the web UI
* See that the default reply is a note and not a Telegram message

**Comment by MrGeneration** [comment] 2020-01-14 21:54
Thanks for your report.
This is rather a duplicate of:
https://github.com/zammad/zammad/issues/372

Closing.

**Closed as completed by MrGeneration** 2020-01-14 21:54 UTC
Labels: duplicate
