### ISSUE TITLE
LDAP and Domain based assignment

### ISSUE THREAD

**Issue by Newan** [zammad/zammad#2149] opened 2018-07-27 08:30 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): deb
* Operating system: ubuntu 16.04
* Database + version: postgres
* Elasticsearch version: n/a
* Browser + version: chrome

### Expected behavior:

* A organization has a domain and Domain based assignment as true. A user are modified or sync over ldap with an email address of this domain / orga.
the user is assignment to this orga.

### Actual behavior:

* A organization has a domain and Domain based assignment as true. A user are modified or sync over ldap with an email address of this domain / orga.
the user is not assignment to this orga, he has no orga. it is not possible to assigment ldap user to an fix orga?

### Steps to reproduce the behavior:

* create organization
* domain based assignment to true
* set domainname
* ldap user create with an email of this domain
* sync ldap

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-07-27 08:35
Hi @Newan - this is a duplicate of #1327.

**Closed as completed by thorsteneckel** 2018-07-27 08:35 UTC
Labels: duplicate
