### ISSUE TITLE
Auto assignment changes owner

### ISSUE THREAD

**Issue by juergenp83** [zammad/zammad#3156] opened 2020-08-19 10:37 UTC
### Infos:

* Used Zammad version: **3.4.x**
* Installation method (source, package, ..): deb package
* Operating system: ubuntu 18.04
* Database + version: mysql
* Elasticsearch version: 7.8
* Browser + version: multiple browsers and versions
* Ticket: #1078761

### Expected behavior:

* Once an agent is assigned as ticket owner, no other agent can get auto assigned as owner

![auto-assign-settings](https://user-images.githubusercontent.com/7965076/90623818-50721380-e217-11ea-98f0-b0e08917d83a.png)

### Actual behavior:

* "First" agent opens ticket, gets auto assigned as owner - next agent opens ticket within the next few seconds (up to maybe 5 seconds), auto assignment fires again and changes the ticket owner

![auto-assign-tickets](https://user-images.githubusercontent.com/7965076/90622511-7a2a3b00-e215-11ea-9523-93d08112582e.png)

### Steps to reproduce the behavior:

* see "actual behavior"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-08-19 10:39
@thorsteneckel I think that this is rather a race condition and due to "performance" impacts that this may happen from time to time. I mean, the database has to be updated first, possibly is not yet because the UI couldn't submit the data yet (but already shows the to be data).

What do you think?

**Comment by juergenp83** [comment] 2020-08-19 10:46
I already removed all issues which may impact the GUI performance (very large Overviews - the largest currently shows 80 tickets), reduced open tabs - the ladies used to keep closed tickets open in a tab ...

The server itself has a very low workload (under 10 % cpu usage on average and around 30% memory)

**Comment by thorsteneckel** [comment] 2020-08-19 13:44
Hi @juergenp83 - thanks for reporting. From my understanding that sounds like a race condition, as @MrGeneration already suspected. Would be great if you could share the (redacted) part of the `log/production.log` file that contains both requests (you described).

If it's a race condition as we suspect:
Our current architecture won't allow us to fix this issue as far as I can see. However, we will address this when we get there. Therefore we should keep the issue open.

**Comment by juergenp83** [comment] 2020-08-19 14:31
That's what I was a little afraid of.

There are a *lot* of hits (300+) regarding this ticket in two log files having 200.000+ lines. I have no idea what else maybe is related to the ticket. Unfortunately I was not able to identify the two specific requests.

Is there a simple and GDPR-save way (a public link to the full logs including employee names an mail adresses is not so cool) how to send you the log files?

@thorsteneckel @MrGeneration thank you both for the quick replies and congrats to the whole team for a great piece of software!

**Comment by MrGeneration** [comment] 2020-08-19 14:54
You can send a mail to support [at] zammad [dot] com and reference Thorsten or Me (Marcel).
Please don't forget to reference this issue so we know where to put it to ;)

If you can't provide the attachment (because it's too big) or you don't have a save way to provide the file via download link, we can also provide a upload link if needed.

**Comment by juergenp83** [comment] 2020-08-20 05:09
done, thank you!

**Comment by MrGeneration** [comment] 2020-08-20 10:32
I extracted the relevant lines / calls and redacted your internal IP. As it's the same IP, I guess that it still are different clients.

You can see very good that at least two agents were racing for that ticket. The access difference is about two seconds:
```
I, [2020-08-19T05:59:07.389831 #7489-70115918739900]  INFO -- : Started GET "/api/v1/tickets/15089?all=true&_=1597813693054" for 666.666.666.666 at 2020-08-19 05:59:07 +0000
I, [2020-08-19T05:59:09.670681 #7489-47034440724720]  INFO -- : Started GET "/api/v1/tickets/15089?full=true&_=1597813693058" for 666.666.666.666 at 2020-08-19 05:59:09 +0000
I, [2020-08-19T05:59:10.067336 #7489-47034441762620]  INFO -- : Started GET "/api/v1/tickets/15089?all=true&_=1597813693060" for 666.666.666.666 at 2020-08-19 05:59:10 +0000
I, [2020-08-19T06:00:15.830419 #7489-47034429492380]  INFO -- : Started GET "/api/v1/tickets/15089?all=true&_=1597815689760" for 666.666.666.666 at 2020-08-19 06:00:15 +0000
I, [2020-08-19T06:00:20.141884 #7489-47034426701180]  INFO -- : Started GET "/api/v1/tickets/15089?full=true&_=1597813693068" for 666.666.666.666 at 2020-08-19 06:00:20 +0000
I, [2020-08-19T06:00:20.528054 #7489-47034441913400]  INFO -- : Started GET "/api/v1/tickets/15089?all=true&_=1597815689766" for 666.666.666.666 at 2020-08-19 06:00:20 +0000
I, [2020-08-19T06:00:20.545499 #7489-47034386678820]  INFO -- : Started GET "/api/v1/tickets/15089?all=true&_=1597813693071" for 666.666.666.666 at 2020-08-19 06:00:20 +0000
```

What's interesting that there are only two fitting PUTs (which most likely is because only two clients tried to set the owner at that time). The first PUT was logged about 1s before the second client fetched the data. So this really may be due to the application at that moment still having old information.

```
I, [2020-08-19T05:59:08.598092 #7489-70115914651780]  INFO -- : Started PUT "/api/v1/tickets/15089" for 666.666.666.666 at 2020-08-19 05:59:08 +0000
I, [2020-08-19T06:00:18.804652 #7489-47034428436860]  INFO -- : Started PUT "/api/v1/tickets/15089" for 666.666.666.666 at 2020-08-19 06:00:18 +0000
```

Edit: You can find the full log if required on above mentioned ticket (first article).

**Comment by juergenp83** [comment] 2020-08-21 10:44
Thanks for the good explanation.
But shouldn't there be a server-side mechanism which keeps the second client from setting "his" owner on the ticket in the database?

Just asking because you set the _frontend / JS app_ label.

**Comment by thorsteneckel** [comment] 2020-08-21 14:06
Hi @juergenp83 - sure, no problem. I try to elaborate: The implementation takes only place in the frontend. So the backend / API only gets the request to update the Owner of the Ticket but isn't/can't be aware of the origin of the request. That's why we have to resolve the issue in the frontend.

**Comment by fliebe92** [comment] 2023-06-08 12:34
Hey @juergenp83,

I was stumbling upon this issue and tried to reproduce it using Zammad 6.0.0 - with no luck. Even using two `curl` requests with two different users is not overwriting each other. So, after the first request is done with the first user, the second request does not assign the second user as the new owner, which is fine. This means that the reported behavior should be fixed.

If you still encounter any problems here, feel free to comment with some new information here.

**Closed as completed by fliebe92** 2023-06-08 12:34 UTC
Labels: bug, verified, frontend, :construction: refactoring :construction:
