### ISSUE TITLE
Ticket reply in zammad goes to customer, not sender of last article since 2.4.0

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1929] opened 2018-04-06 11:24 UTC
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): packager.io deb
* Operating system: debian 8.10
* Database + version: postgresql 9.4
* Elasticsearch version: 5.6.8
* Browser + version: any

### Expected behavior:

* replying to an article uses sender of article as recipient, not customer assigned

### Actual behavior:

* replying to an article always uses customer assigned as recipient

**Comment by martini** [comment] 2018-04-06 11:25
@babakkazemi can you attach screenshots from this article with expanded header/footer. I can't reproduce it. Thanks!

**Comment by babakkazemi** [comment] 2018-04-06 11:31
@martini just found out more - this happens only when you want to reply to an article that was merged into another ticket.

**Comment by martini** [comment] 2018-04-06 11:35
Thanks for feedback. I description how to reproduce to on an test system of zammad.com would be nice! 😻

**Comment by babakkazemi** [comment] 2018-04-06 11:48
Create a ticket (#1) with customer a
do some conversation
receive an email from customer b into zammad which creates a new ticket (#2)
merge #2 into #1
reply to the article that was created by merging
reply goes to customer a, not customer b

**Comment by muhammadn** [comment] 2018-04-11 10:08
@babakkazemi I was able to reproduce it but if you merge ticket 2 **into** ticket 1, which actually means getting ticket 1 as the new merged ticket. Reply would be based on ticket 1 (customer a), which should be the case. 

Unless you merge ticket2 **into** ticket 1 which all replies will be based on ticket 2 details.

**Comment by thorsteneckel** [comment] 2018-05-09 18:35
Seems to be clarified since no feedback was provided. Closing for now.

**Closed by thorsteneckel** 2018-05-09 18:35 UTC
Labels: needs verification, waiting for feedback
