### ISSUE TITLE
Drop down empty in ticket issued by agent

### ISSUE THREAD

**Issue by mbaydoun** [zammad/zammad#5007] opened 2024-01-15 18:18 UTC
### Used Zammad Version

6.2

### Environment

- Installation method: package
- Operating system : Ubuntu 20.0.4
- Elasticsearch version: 7.17
- Browser + version: latest version of chrome

### Actual behaviour

When an " Agent " issues a new ticket, after filling in title and customer, tries to fill " group " from the drop down menu, but the drop down comes emtpy.

PS: the " group " drop down in a new ticket works fine for tickets issued by " Customer " role.

### Expected behaviour

Agent should be able to pick the group from the drop down menu in a new ticket, OR, this attribute should not be " required ".

### Steps to reproduce the behaviour

-Create user with agent role
- create new ticket
- start filling the ticket until you reach " Group "
- try picking a group from drop down menu.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2024-03-01 16:47
Hi @mbaydoun. Thanks for your report. However, I cannot reproduce it. For me, it works fine. Are you sure that the agent that was used to issue the ticket has at least permissions for one group?

**Comment by mgruner** [comment] 2024-09-12 12:47
No feedback, closing. Feel free to provide more information.

**Closed as not planned by mgruner** 2024-09-12 12:47 UTC
Labels: waiting for feedback, needs verification
