### ISSUE TITLE
Labor Tracking per Ticket

### ISSUE THREAD

**Issue by bchynds** [zammad/zammad#853] opened 2017-03-17 13:48 UTC
A feature that we frequently use in Spiceworks is labor tracking for individual tickets, so we can invoice them later when needed.  Is this something that Zammad can handle or be extended to include?

**Comment by martini** [comment] 2017-03-22 15:26
Hi @bchynds 

for me it's not clear what "labor ticketing" means. You want to create something like a "own watched" ticket list?

 -Martin

**Comment by bchynds** [comment] 2017-03-22 15:48
Hi @martini 
Labor as in hours spent.  For example, if a ticket requires an onsite visit (or any other billable time), we manually add the time spent to the corresponding ticket, which is then pulled via a report each month and billed.

**Comment by thorsteneckel** [comment] 2019-06-13 11:20
This is a duplicate of #373 - which is already [implemented](https://github.com/zammad/zammad/commit/ad5312809150ddbaa7be84e0fae4afcca390e666#diff-b6e5ef72936f1793f8b0c02ed24c90af). Closing now.

**Closed by thorsteneckel** 2019-06-13 11:20 UTC
Labels: feature backlog
