### ISSUE TITLE
Images embedded in Knowledge Base answers do not get copied into tickets correctly

### ISSUE THREAD

**Issue by arstehn** [zammad/zammad#3024] opened 2020-04-17 11:33 UTC
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04.4
* Database + version: MySQL (Marina DB 10.3.11)
* Elasticsearch version: 7.6.2
* Browser + version: Current Google Chrome & Current Firefox

### Expected behavior:

- When inserting an answer from the knowledge base into a ticket by using "??" all images inserted into the knowledge base answer should get inserted as well

### Actual behavior:

- Images do not get inserted correctly and just leave a placeholder where they are supposed to be (see attached image)

![Step1](https://user-images.githubusercontent.com/63852131/79564798-9d9a7900-80af-11ea-8e6f-83b4e983eef5.PNG)
![step2](https://user-images.githubusercontent.com/63852131/79564802-9e330f80-80af-11ea-8ea8-c0cd7000a1f6.PNG)

### Steps to reproduce the behavior:

- Create an answer in the knowledge base
- Insert an image into the answer via the "Image" Button
- Save and publish the answer
- Insert the knowledge base answer when creating a new article for a ticket by using "??"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment] 2020-04-17 11:38
Closing as duplicate of https://github.com/zammad/zammad/issues/2644

**Closed as completed by mantas** 2020-04-17 11:38 UTC
Labels: duplicate

**Comment by arstehn** [comment] 2020-04-17 12:02
While this issue is similar to #2644 it is not the same.
In the video in #2644 you can see the issue I described work correctly as my issue lies with images being inserted into the answer itself, not being uploaded as attachments.

**Comment by MrGeneration** [comment] 2020-04-17 12:09
Sounds like a similare issue to the one we had on the Zammad community earlier this month:
https://community.zammad.org/t/images-broken-when-adding-knowledgebase-articles-to-tickets/4341

I couldn't reproduce it.
Please check if it fits and provide at least developer console output.

Right now this is, even if it's different, absolutely not reproducable with the provided information. I'm sorry.

**Comment by mantas** [comment] 2020-04-17 13:12
@arstehn I'm working on a fix for #2644. That fix will solve both file and inline attachments. Issue description may be ambiguous though. Sorry for the confusion.

@MrGeneration I can reproduce this issue as well as confirm that #2644 fix solves it. Let me know if you want more details

@thorsteneckel ping on that merge request stuck in QA for a long time :)

**Comment by arstehn** [comment] 2020-04-17 13:17
No problem and thank you for your quick reply, that's great news

**Comment by ryno83** [comment] 2020-04-22 14:24
Hi,
Is there a way to make it work again in version 3.3.0 ? A kind of workaround ?

Thank you

**Comment by MrGeneration** [comment] 2020-04-22 14:50
This is a closed issue, please do not hijack closed issues.
While you could backport these changes, I wouldn't suggest to do so, so no, no workaround. 🤷‍♀️

**Comment by thorsteneckel** [comment] 2020-04-23 08:11
Hi @ryno83 - Zammad 3.4 is just around the corner (sorry, no concrete date, ETA is in about 2-3 weeks) and therefore we don't want to backport this. It's a rather big change from the codes perspective.
