### ISSUE TITLE
No name suggestions after update to v3.1

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#2772] opened 2019-10-10 14:38 UTC
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): DEB
* Operating system: Ubuntu 9

### Expected behavior:
When i reply or forward an email and start to type in a name in the "to" or "cc" field, name suggestions appears.

### Actual behavior:
After Update to v3.1 the name suggestions doesn't appear.
If  i create a new ticket, the name suggestion in the "customer" field is working, but not in the "cc" field.

**Comment by MrGeneration** [comment] 2019-10-10 14:43
Sorry but I believe that this is rather a technical question than a bug.
Ensure that your elasticsearch is up and running. If it isn't start it and reindex your system.

Right now I can't reproduce this, sometimes the update process stops elasticsearch.
If this isn't the case, please provide log files and maybe even the console output from your update if possible.

Closing for now.

( Please note that the Community is the better place for technical questions: https://community.zammad.org )

**Closed as completed by MrGeneration** 2019-10-10 14:43 UTC
Labels: question
