### ISSUE TITLE
no transfer of ticket information after ticket split

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#1921] opened 2018-04-04 13:15 UTC
### Infos:

* Used Zammad version: 2.4.x
* hosted Version
* Browser + version: Chrome Version 65.0.3325.181

### Expected behavior:

* when splitting off articles, all ticket information and attachments should be taken over and displayed in the ticket creation screen.

### Actual behavior:

* when articles are split off, no ticket information is transferred. The attachments are not displayed in the ticket creation screen, but are transferred. This is only visible in the article after the new ticket has been created.

### Steps to reproduce the behavior:

1.) press "split" in an existing article
--> you get to a blank ticket creation screen

2.) press "split" in an existing article with attachment
- you get into a blank ticket creation mask (no attachments visible)
- after filling in all information press "create
- the attachment of the original mail is included in the new article

**Comment by thorsteneckel** [comment] 2018-04-04 13:49
As discussed: This is a duplicate of #1913 . Closing now.

**Closed by thorsteneckel** 2018-04-04 13:49 UTC
