### ISSUE TITLE
Duplicated text when using / with @

### ISSUE THREAD

**Issue by Madko** [zammad/zammad#4083] opened 2022-05-12 12:03 UTC
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): package
* Operating system: ubuntu 18.04 LTS
* Database + version: postgres 10
* Elasticsearch version: 7.8
* Browser + version: Firefox 100

### Expected behavior:

* when copying text like “[email@domain.com](mailto:email@domain.com)/[email@domain.com](mailto:email@domain.com)” from a text editor (like gedit) in the textfield for a new ticket, the text should be “email@domain.com/email@domain.com”

### Actual behavior:

* when pasting the text, “[email@domain.com](mailto:email@domain.com)/[email@domain.com](mailto:email@domain.com)” becomes “email@domain.com/email@domain.com/email@domain.com”

### Steps to reproduce the behavior:

* open a text editor
* type `email@domain.com/email@domain.com`
* select this text
* ctrl+c
* in zammad, create a new ticket
* in the body/text part, ctrl+v

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-05-12 12:10
This only happens if you paste the HTML content as unformatted. At least in my environment.

Please mark your community thread accordingly to ensure nobody has duplicate time wastes. Thank you.

**Comment by Madko** [comment] 2022-05-12 12:37
Hi, what do you mean by "HTML content ?"

community thread is https://community.zammad.org/t/duplicated-text-when-using-with/9209

**Comment by MrGeneration** [comment] 2022-05-12 12:38
This is HTML content:

> “[email@domain.com](mailto:email@domain.com)/[email@domain.com](mailto:email@domain.com)”

If you paste that, you'll paste HTML content. For this reason most browsers allow unformatted pasting.
For further technical questions please consult the community.

**Comment by Madko** [comment] 2022-05-12 12:44
sorry if it was not clear, it's github that format this to HTML. I use plain text from a text editor (like gedit, vi etc).

**Comment by MrGeneration** [comment] 2022-05-12 12:51
Well then I'll have to close this as can't reproduce.
Even though I can reproduce the HTML way.

**Comment by Madko** [comment] 2022-05-12 12:57
sorry what ? I can reproduce it with zammad free trial

**Comment by MrGeneration** [comment] 2022-05-12 13:17
Final clarification:
The issue appears on Firefox only if you copy & paste unformatted strings like `email@domain.com/email@domain.com`.
Doing the same does not happen on other browsers.

Other browsers (chromium based) however will show the same behavior if you copy a HTML version of above string and paste it as unformatted string. So it indirectly affects all platforms.

**Comment by mantas** [comment] 2022-11-17 15:41
I can't reproduce this anymore. Including on Firefox. Can you guys still reproduce it?

**Comment by MrGeneration** [comment] 2022-11-17 15:50
@cautopartes please re-verify.

**Comment by cautopartes** [comment] 2022-11-22 15:36
Can not reproduce/verify on: 
* Firefox 106.0.5 (64-bit) 
* Vivialdi 5.5.2805.44 
* Opera 92.0.4561.43 
* Chromium 107.0.5304.110

**Comment by MrGeneration** [comment] 2022-11-22 15:52
So we can close it then...

**Closed as completed** 2022-11-22 15:53 UTC
Labels: can't reproduce
