### ISSUE TITLE
After Update to 2.0 - Ticket: History, Merge, Change Costumer -> No function

### ISSUE THREAD

**Issue by Johannes-GitHub** [zammad/zammad#1408] opened 2017-09-12 14:19 UTC
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...) package
* Operating system: Ubuntu 16.04 LTE
* Browser + version: Chrome latest

After Update to 2.0 - Ticket: History, Merge, Change Costumer -> No function

If we open a Ticket and want to view, history, merge or change the costumer (in the right upper corner) nothing happens. 

Checked with Firefox too. 

Some one has the same issue? 

Thanks a lot
Best regards
Johannes

![image](https://user-images.githubusercontent.com/24590878/30330571-bad5d1b0-97d5-11e7-8fd4-048539045a25.png)

**Comment by martini** [comment] 2017-09-12 14:25
Hi @Johannes-GitHub thanks. It's a duplicate of https://github.com/zammad/zammad/issues/1398 (browser with touch events are affected). Fix is in QA right now. Will be shipped ASAP.

**Closed** 2017-09-12 14:26 UTC
Labels: duplicate
