### ISSUE TITLE
LDAP import error: undefined method `result_code' for nil:NilClass

### ISSUE THREAD

**Issue by larrybg** [zammad/zammad#2630] opened 2019-06-26 16:53 UTC
### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: 
* Elasticsearch version: 5.6.16
* Browser + version: Chrome 75.0.3770.100

### Expected behavior:
Working LDAP integration. The application connects to the LDAP server and imports users from specified LDAP groups
*

### Actual behavior:
LDAP configuration is failing with error: "Unsupported object type: id=0" or another - "undefined method `result_code' for nil:NilClass"
*

### Steps to reproduce the behavior:
Connect to LDAP. Specify user mapping from the dropdowns. Add LDAP groups and assign Roles from the dropdowns. Select not to sync users without LDAP groups and click next.
After a few minutes of calculating users error will be shown"Unsupported object type: id=0".

If I manually specify my LDAP group ( it doesn't show in the dropdown for some reason) I'll receive another error: "undefined method `result_code' for nil:NilClass"
*

Yes I'm sure this is a bug and no feature request or a general question.

[production.log.zip](https://github.com/zammad/zammad/files/3331125/production.log.zip)

**Comment by MrGeneration** [comment] 2019-06-27 07:41
Hey,

hate to tell you, but this is not a Bug, but a feature. 🗡
Specifying manual groups does not work, if you can't find your groups, ensure that the search filter you're using is correct and working (e.g. with an LDAP Browser).

This is a technical question, which is why I'll close this issue now.
If you need further help, you're welcome to take a look at our community: https://community.zammad.org

We also have commercial services ( https://zammad.com/pricing#selfhosted ) in case this is more interesting for you.

Bests

**Closed as completed by MrGeneration** 2019-06-27 07:41 UTC
Labels: question
