### ISSUE TITLE
DynamicFields imported from OTRS are mandatory, hidden and stop input forms from submitting

### ISSUE THREAD

**Issue by mz67122** [zammad/zammad#1175] opened 2017-06-09 07:51 UTC
### Infos:

* Used Zammad version: 1.4
* Used Zammad installation source: package
* Operating system: CentOS 7
* Browser + version: Firefox
* OTRS 5
* Znuny4OTRS-ZammadMigrator 1.2.1 with Repo 5.0.23

 

### Expected behavior:

* Data migration to Zammad

### Actual behavior:

* Error
* execute Import::OTRS.diff_worker (try_count 5) exited with error #<NoMethodError: undefined method `[]' for nil:NilClass>

### Steps to reproduce the behavior:

* Start OTRS to Zammad Migration process

[production.docx](https://github.com/zammad/zammad/files/1063321/production.docx)

**Comment by thorsteneckel** [comment] 2017-06-09 07:52
Hi @mz67122  please update to the latest version of Zammad and try again. There were a lot of fixes for the OTRS import in the meantime which might solve your issue. If not please leave feedback and an updated production log. Thanks! 🚀

**Comment by mz67122** [comment] 2017-06-09 12:19
Hi,

I did the update to version 1.5, but the issue is there again. I can't get any more 
detailed information with this production log.

[production.txt](https://github.com/zammad/zammad/files/1063996/production.txt)

**Comment by thorsteneckel** [comment] 2017-06-09 12:21
Thanks! Could you please provide your `log/scheduler_err.log` file too? Seems the error should be there.

**Comment by thorsteneckel** [comment] 2017-06-28 08:46
Hi @mz67122 - sorry for the delay! I created a debug script for your case to get some more information about the error. Please do the following and update the URL and key if needed:

1.) Create a file called `issue_1175.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via zammad run rails r `issue_1175.rb` or rails r `issue_1175.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `issue_1175.rb` file

```ruby
key = 'VoRG3O09PORabUkqy3AybSNUiDv1UswtOXvbgjPZ'
url = 'http://10.49.41.143'

Setting.set('import_otrs_endpoint', "#{url}/otrs/public.pl?Action=ZammadMigrator")
Setting.set('import_otrs_endpoint_key', key)
Setting.set('import_mode', true)
Setting.set('system_init_done', false)
Import::OTRS.start
```

**Comment by mz67122** [comment] 2017-07-05 09:43
Hello, here is the output file
[output.txt](https://github.com/zammad/zammad/files/1124181/output.txt)

**Comment by thorsteneckel** [comment] 2017-07-05 11:25
Hi @mz67122 - thanks for the feedback. I think I found the cause. Could you please try it again with the following script:

```ruby
key = 'VoRG3O09PORabUkqy3AybSNUiDv1UswtOXvbgjPZ'
url = 'http://10.49.41.143'

module Import
  module OTRS
    class User
      def groups_from_otrs_group(role_object, group)
        result = []
        return result if role_object['GroupIDs'].blank?
        permissions = role_object['GroupIDs'][ group['ID'] ]

        return result if !permissions

        if group['Name'] == 'admin' && permissions.include?('rw')
          result.push 'Admin'
        end

        return result if group['Name'] !~ /^(stats|report)/
        return result if !( permissions.include?('ro') || permissions.include?('rw') )

        result.push 'Report'
        result
      end
    end
  end
end

Setting.set('import_otrs_endpoint', "#{url}/otrs/public.pl?Action=ZammadMigrator")
Setting.set('import_otrs_endpoint_key', key)
Setting.set('import_mode', true)
Setting.set('system_init_done', false)
Import::OTRS.start
```

**Comment by mz67122** [comment] 2017-07-05 12:33
Thank you for the mail. This is the output:
[output.txt](https://github.com/zammad/zammad/files/1124607/output.txt)

**Comment by thorsteneckel** [comment] 2017-07-05 12:38
Hi @mz67122 - sorry I made a mistake and forgot two relevant lines. Could you please take the updated version from above and restart the script? Thanks!

**Comment by mz67122** [comment] 2017-07-05 12:48
Here is the new file:
[output.txt](https://github.com/zammad/zammad/files/1124664/output.txt)

**Comment by thorsteneckel** [comment] 2017-07-05 13:04
You are fast - I like that 🤓 Next try - we are getting closer:

```ruby
require 'import/otrs'
require 'import/otrs/user'

key = 'VoRG3O09PORabUkqy3AybSNUiDv1UswtOXvbgjPZ'
url = 'http://10.49.41.143'

module Import
  module OTRS
    class User
      def groups_from_otrs_group(role_object, group)
        result = []
        return result if !role_object.key?('GroupIDs')
        return result if role_object['GroupIDs'].blank?
        permissions = role_object['GroupIDs'][ group['ID'] ]

        return result if !permissions

        if group['Name'] == 'admin' && permissions.include?('rw')
          result.push 'Admin'
        end

        return result if group['Name'] !~ /^(stats|report)/
        return result if !( permissions.include?('ro') || permissions.include?('rw') )

        result.push 'Report'
        result
      end
    end
  end
end

Setting.set('import_otrs_endpoint', "#{url}/otrs/public.pl?Action=ZammadMigrator")
Setting.set('import_otrs_endpoint_key', key)
Setting.set('import_mode', true)
Setting.set('system_init_done', false)

Import::OTRS.start
```

**Comment by mz67122** [comment] 2017-07-05 13:39
Here is the output:
[output.txt](https://github.com/zammad/zammad/files/1124806/output.txt)

**Comment by thorsteneckel** [comment] 2017-07-05 13:45
I did a minor change to the code above, could you please retry with the changed version? Thanks for your support.

**Comment by mz67122** [comment] 2017-07-05 14:20
Hello, this version did run a longer time without any output

**Comment by thorsteneckel** [comment] 2017-07-05 14:22
Great! That means there were any errors. You should now be able to start your Zammad and login via any of the OTRS credentials. Can you confirm this?

**Comment by mz67122** [comment] 2017-07-05 14:33
I tried it, but there is only the website "localhost:3000/#import/otrs" available

**Comment by thorsteneckel** [comment] 2017-07-13 17:01
Hi @mz67122  - any updates so far?

**Comment by mz67122** [comment] 2017-07-14 07:44
Hi....thank you and sorry for the delay, had some other priorities the last days. The Import was successful. There are two things to say. The first thing is that I lost my OTRS administrator rights, so I had to make this with the rails console => ok now. The second problem now is, that I cannot create new Tickets. I dont't know why.

**Comment by mz67122** [comment] 2017-07-20 09:34
Hello....I can not create new Tickets? What could be the reason for that?

**Comment by thorsteneckel** [comment] 2017-07-20 09:53
Hi @mz67122 - I'm currently working on another task but will come back to your previous feedback asap. Thanks for that!

Can you explain what's the issue when trying to create new ticket? A step by step guide would be great. If there is an error shown in the interface please provide the `log/production.log` file. If there is nothing happing in the browser please activate your browser (JavaScript) console and look out for errors. 

Thanks!

**Comment by mz67122** [comment] 2017-07-21 08:14
Hello, the production.log seems to be ok. Just messages concerning mail fetching. But there are some errors in the browser console. See appended screenshot.
![browser_error](https://user-images.githubusercontent.com/26767672/28454937-50229a30-6dfd-11e7-84ba-7d077cb29ce1.png)

**Comment by thorsteneckel** [comment] 2017-07-21 08:20
We had this issue somewhere but I can't find it right now. Can you please go to your ObjectManager settings and change the configuration of the ObjectManager Attributes that start with `ITSM` to be either visible or not required for the Ticket create view? I think this is the problem. We should fix this that this constellation of being required but not visible is not valid. Feedback would be great.

**Comment by mz67122** [comment] 2017-07-21 08:51
OK...That's it...It works now, thank you

**Comment by thorsteneckel** [comment] 2017-08-22 08:32
Hi @mz67122 - I want to provide a sustainable solution for this issue. Could you please help me with it by providing me your DynamicField configuration export. It won't contain any User or Ticket data but just the configuration of the fields. To do so please call your Zammad Migrator URL of your OTRS directly via:

`http://yourdomain.tld/otrs/public.pl?Action=ZammadMigrator;Subaction=Export;Object=DynamicField;Key=*InserYourKeyHere*`

You just have to change your domain and the API key. The API Key can be found in the SysConfig `ZammadMigrator::API::Key` of your OTRS.

Please send it to `support@zammad.com` and refer to this issue and me. Thanks a lot for your support 🚀

**Comment by mz67122** [comment] 2017-08-22 09:26
Hi, this is your file:
[dyn_field_export.txt](https://github.com/zammad/zammad/files/1241495/dyn_field_export.txt)

**Comment by thorsteneckel** [comment] 2017-08-23 12:27
Thanks to your file I was able to reproduce the issue. Working on a fix now.

**Comment by thorsteneckel** [comment] 2017-08-23 14:45
This is fixed with the commits above. DynamicFields now get imported as not mandatory since the are configured per view in OTRS. The get automatically added to all display but no edit views. The administrator has to decide per field for which views it should be enabled. The mandatory state can get changed in the same change action.

**Closed by thorsteneckel** 2017-08-23 14:45 UTC
Labels: bug, import, verified
