### ISSUE TITLE
Custome object - can’t update database

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#2827] opened 2019-12-04 14:46 UTC
If you try to create or modify a custome object and have some silly / wrong configuration, something like this:
![grafik](https://user-images.githubusercontent.com/4436931/70152214-1b378c80-16ad-11ea-87be-4ad58583564a.png)
You can’t make an database update. It simple does nothing in the webfront.
If you watch close the log file, you can find something like this:

E, [2019-12-04T14:33:42.208565 #19364-47005678008820] ERROR -- : PG::StringDataRightTruncation: ERROR: value too long for type character varying(20)

Cheers.

**Comment by MrGeneration** [comment] 2020-02-05 13:19
Hey,

sorry but we're not able to reproduce your described issue.
Please update your initial article with our issue template (see the end of my article) to help us further, if this issue still persists.

Please also add a detailed reproduction description.
We've been updating/creating tickets, updating/creating objects without success.

Thanks!


----

Template:

```
### Infos:

* Used Zammad version:
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:


### Expected behavior:

*


### Actual behavior:

*


### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

```
```

**Comment by martini** [comment] 2020-02-05 14:00
Note:

> E, [2019-12-04T14:33:42.208565 #19364-47005678008820] ERROR -- : PG::StringDataRightTruncation: ERROR: value too long for type character varying(20)

This looks a little bit strange. The data for the field is stored in table `object_manager_attributes` which has no varchar with 20 at all.

**Comment by MamoulianDelacroix** [comment] 2020-02-07 10:26
The "problem" is, that I configureda MAXLENGTH of 20 characters and I put morgen than 20 characters in the LINK-TEMPLATE field. As long as there were more than 20 characters. Which is totally correct, but I didn't get any detailed error messages at the webfront.  Only in the log-files I found out why.
A small hint in the webfront would be nice, that the "20" characters were exceeded.

**Comment by MrGeneration** [comment] 2020-05-07 14:17
This issue seems by now to be solved.
At least I still can't reproduce it on my environments.

As this also hasn't received any updates or further information, I'll therefor close this issue.

**Closed as completed by MrGeneration** 2020-05-07 14:17 UTC
Labels: can't reproduce, missing issue template
