### ISSUE TITLE
Trigger ignoring tag condition

### ISSUE THREAD

**Issue by svnr-dvnkln** [zammad/zammad#1683] opened 2017-11-30 07:56 UTC
### Infos:

* Used Zammad version: 2.2.x
* Used Zammad installation source: deb 9 repo
* Operating system: deb 9
 * Browser + version: all (really)

### Expected behavior:

Configuring a trigger to send a mail to the customer when the owner has changed EXCEPT when a certain tag (let's call it "nosendmail") is set, will only send the mail to the customer if the defined tag is not set.

### Actual behavior:

The mail is sent even when the tag is set.

### Steps to reproduce the behavior:

* Set the following trigger:

**Condition:**
```
Owner - has changed
Tags - contains one not - "nosendmail"
```

**Execute:**
```
Send mail to Customer
```

* Add the tag "nosendmail" to a ticket

* Change the owner

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment] 2018-01-16 09:14
@svnr-dvnkln the problem is now fixed and will be in our next release (2.3.x) 🚀

**Closed by muhammadn** 2018-01-16 09:14 UTC

**Comment by alex-LE** [comment] 2018-10-23 12:18
We have the same issue with Zammad 2.6.x.

**Comment by NiTRoeSE** [comment] 2018-10-23 12:35
I have also the same problem with Zammad 2.6.x.
Zammad ignores a "noreply" tag at a trigger for autoreply

**Comment by thorsteneckel** [comment] 2018-10-23 12:40
Hi guys - could you please verify this on one of our free hosted instances over at https://www.zammad.com/getting-started  and tell us the instance name? If you can reproduce it please create a new issue 👍

**Comment by alex-LE** [comment] 2018-10-23 12:56
We are using the self hosted version (Community Edition).
