### ISSUE TITLE
Inline images being stripped

### ISSUE THREAD

**Issue by kendinitto** [zammad/zammad#2153] opened 2018-07-27 20:30 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): YUM
* Operating system: Centos 7
* Database + version:  PostgreSQL PostgreSQL 9.2.23
* Elasticsearch version: 5.6.10
* Browser + version: Chrome Version 67.0.3396.99 

### Expected behavior:

Inline images that are pasted into a text module or email response or already in an incoming ticket email should not be stripped out

### Actual behavior:

Inline images that are pasted into a text module or email response or already in an incoming ticket are being stripped out

### Steps to reproduce the behavior:

I just installed the latest stable version of Zammad (2.5) in Centos 7 via YUM. After setting it up and testing it I notice If I send a ticket into the system via email any inline images that were in the email are getting stripped out. Regardless of if the images are part of a signature or just copied and pasted in, they get stripped. If I view the source with google inspector I can see the image tags are completely gone.

If I paste an image into a text module or email response it gets stripped out as soon as I click the update button.

I have read other posts that indicate that inline images are supposed to work, so this seems like a bug to me. I do not see any reference to any setting that allows or disables inline images.

Also, although not a bug I thought I would mention It would also be nice if when opening an attachment I could click on it and it would open an appropriate software to view vs just downloading it. Most other ticketing systems I have used do this such as Teamwork Desk.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-07-28 07:15
Hi @kendinitto - I somehow believe that this is a duplicate of #1917 / #2097 / #1123 and we already fixed it with this commit. However, could you please verify that it's still broken in latest `develop`?
If so, please provide a sample mail. You download the raw file via this link in the ticket zoom view:

<img width="354" alt="screen shot 2018-07-18 at 12 53 28" src="https://user-images.githubusercontent.com/110226/42877421-d5794356-8a89-11e8-94ca-50ed677f28f6.png">

And please let us know how to reproduce this exactly. Like a step by step / click by click description.

**Comment by kendinitto** [comment] 2018-07-28 20:41
Ya I am attaching the raw version of the ticket. 

All I did was send a new ticket into the system via email. I did a cntl-c and cntrl-v copy / paste of the www.google.com homepage logo into the ticket.

In the raw file it has the image tag, but in the Zammad ticket interface it is not there, stripped out.

[ticket-76026-48.zip](https://github.com/zammad/zammad/files/2238283/ticket-76026-48.zip)

**Comment by kendinitto** [comment] 2018-07-28 20:42
Regarding the version, it says:
Version
This is Zammad version 2.5.x

I installed it via YUM in centos a couple of days ago.

**Comment by thorsteneckel** [comment] 2018-07-30 06:47
This either works (and was fixed by one of the linked issues above) or is a duplicate of #1917 (last part) as it can be seen here:
![works](https://user-images.githubusercontent.com/3873515/43381480-166b2416-93d5-11e8-92de-0675c94d1bc5.gif)
 
Closing now.

**Closed as completed by thorsteneckel** 2018-07-30 06:47 UTC
Labels: duplicate
