### ISSUE TITLE
Broken pipe @ io_write - <STDOUT>

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#280] opened 2016-10-24 09:06 UTC
While starting the [zammad vagrant box](https://github.com/zammad/vagrant) the following error occurs while running through getting started:

![bildschirmfoto 2016-10-24 um 11 03 38](https://cloud.githubusercontent.com/assets/3873515/19639647/9544e972-99d9-11e6-93e4-e7942d8e5684.png)

Which is caused by this line:
https://github.com/zammad/zammad/blob/81b48a2ef4bc691e247076d8826cebaf26e18ea0/lib/sessions/event/base.rb#L105

Stracktrace (from log):

```
E, [2016-10-24T08:37:47.473550 #12661] ERROR -- : ["/opt/zammad/lib/sessions/event/base.rb:105:in `write'
/opt/zammad/lib/sessions/event/base.rb:105:in `puts'
/opt/zammad/lib/sessions/event/base.rb:105:in `puts'
/opt/zammad/lib/sessions/event/base.rb:105:in `log'
/opt/zammad/lib/sessions/event/spool.rb:10:in `run'
/opt/zammad/lib/sessions/event.rb:14:in `run'
/opt/zammad/app/controllers/long_polling_controller.rb:32:in `message_send'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller base.rb:198:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abs
tract_controller/callbacks.rb:20:in `block in process_action'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/active
support-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbac

```

**Comment by monotek** [comment] 2016-12-20 18:58
Can't reproduce anymore in current vagrant file with develop package.
Closing.

**Closed by monotek** 2016-12-20 18:58 UTC
Labels: bug
