### ISSUE TITLE
Exchange import fails if folder names can't be converted to Unicode

### ISSUE THREAD

**Issue by PhilippRedel** [zammad/zammad#2152] opened 2018-07-27 17:11 UTC
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: MySQL | 5.7.12-0ubuntu1.1
* Browser + version: Google Chrome 68 | Mozilla Firefox 61.0.1
* Exchange 2010

### Expected behavior:

* Exhcange Integration should work as expected.

### Actual behavior:

* The Exchange Integration stops with the error: "\xC3" from ASCII-8BIT to UTF-8

![exchange](https://user-images.githubusercontent.com/16289288/43335627-f563bc94-91cf-11e8-9fa5-e46863538c6c.png)
![exchange2](https://user-images.githubusercontent.com/16289288/43335843-38776472-91d0-11e8-9701-7d0ebbdf17f6.png)

### Steps to reproduce the behavior:

* Setup Zammad from ubuntu Packages -> Admin -> System -> Integrations -> Exchange
* Add Exchange Credentials and wait until the error occures

### Production.log

```
E, [2018-07-27T18:43:20.937169 #527] ERROR -- : "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/core_ext/object/json.rb:36:in `encode'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/core_ext/object/json.rb:36:in `to_json'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/core_ext/object/json.rb:36:in `to_json'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/json/encoding.rb:55:in `to_json'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/common.rb:224:in `generate'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/common.rb:224:in `generate'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/json/encoding.rb:100:in `stringify'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/json/encoding.rb:33:in `encode'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/json/encoding.rb:20:in `encode'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/core_ext/object/json.rb:39:in `to_json'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/renderers.rb:156:in `block in <module:Renderers>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/renderers.rb:149:in `block in _render_to_body_with_renderer'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/set.rb:324:in `each_key'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/set.rb:324:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/renderers.rb:145:in `_render_to_body_with_renderer'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/abstract_controller/rendering.rb:24:in `render'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/rendering.rb:36:in `render'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:43:in `render'
/opt/zammad/app/controllers/concerns/integration/import_job_base.rb:47:in `rescue in answer_with'
/opt/zammad/app/controllers/concerns/integration/import_job_base.rb:42:in `answer_with'
/opt/zammad/app/controllers/integration/exchange_controller.rb:28:in `folders'
```

**Comment by thorsteneckel** [comment] 2018-07-27 17:14
Hi @PhilippRedel  - thanks for filling an issue. This is actually a duplicate of #2140. Seems like there is an issue affecting LDAP and Exchange integration. However, we will address it in the older issue. Closing now.

**Comment by rlue** [comment] 2018-08-06 11:12
@PhilippRedel Upon further investigation, it looks like the aforementioned issue #2140 is related but not identical. 

We've been digging into this issue and are pretty confident we understand what's going on, but we need to ask for your help again to be completely certain.

#### Help us: Confirm the cause of the bug

Try the following line in your terminal, in the Zammad directory. Be sure to replace the `<PLACEHOLDERS>` with your Exchange server credentials. If our suspicions are correct, then it should fail (_i.e.,_ raise an error and show a traceback):

    $ rails c
    >> connection = Viewpoint::EWSClient.new(endpoint: '<ENDPOINT>', user: '<USER>', password: '<PASSWORD>')
    >> folders = Import::Exchange::Folder.new(connection)
    >> folders.id_folder_map.transform_values { |folder| folders.display_path(folder) }.to_json

If you saw a traceback for the same `Encoding::UndefinedConversionError` that you got in the initial bug report, then great — the problem is (probably) where we thought it was! If not, please let us know so that we can continue to investigate.

#### Help you: A temporary fix

If you're willing to get your hands dirty, here are a couple changes that should fix the problem:

```ruby
# lib/import/exchange/folder.rb

# on line 57, change
"#{parent_folder_path} -> #{display_name}"
# to
"#{parent_folder_path} -> #{display_name}".utf8_encode(fallback: :read_as_sanitized_binary)

# and on line 59, change
folder.display_name
# to
folder.display_name.utf8_encode(fallback: :read_as_sanitized_binary)
```

Restart Zammad and run through the Exchange wizard again. If you try this and it _doesn't_ work, please let us know as well.

**Comment by PhilippRedel** [comment] 2018-08-10 21:39
@rlue Im sorry for the late reply.

If i tried to run the first command, i ran into an error. I needed to change the command to 
`connection = Viewpoint::EWSClient.new('******************', '************', '**********')`
After changin this and executing the other commands i got an ErrorAccessDenied message. So i tried to connect with other usernames and passwords and every time got the same error although the credentials are working perfectly if i try them elsewhere.

Then i changed the code as you said: 
![zammad_file_change](https://user-images.githubusercontent.com/16289288/43982492-6e2f2344-9cf6-11e8-94ab-9e96ae94e12e.png)

And tried the integration again but i ran in the same error again:
![zammad_file_change_not_worked](https://user-images.githubusercontent.com/16289288/43982513-83637814-9cf6-11e8-83f4-3eeed43cf679.png)

**Comment by rlue** [comment] 2018-08-13 06:08
> I needed to change the command to
> `connection = Viewpoint::EWSClient.new('******************', '************', '**********')`

Yes, absolutely my mistake — I was getting Viewpoint's API mixed up with the API for one of Zammad's internal classes. Good call.

> And tried the integration again but i ran in the same error again...

Yep, also a big oversight on my part. I can't be 100% sure, but I'm pretty confident that you just need to add one more call to `#utf8_encode` on line 49:

```ruby
display_name = folder.display_name.utf8_encode(fallback: :read_as_sanitized_binary)
```

**Comment by rlue** [comment] 2018-08-13 06:50
And assuming that works, what we'd really like is to be able to write a test to ensure that this problem doesn't crop up again. In order to do that, it'd really help to know exactly what folder name on your Exchange server is breaking this method.

To do that, please **remove** the changes that fixed this bug (_i.e.,_ the places where you added `.utf8_encode(fallback: ...)`), and then run the following commands in the Rails console:

```ruby
$ rails c

# should return a hash in the following format:
# { folders: { 1 => 'folder_name', 2 => 'folder_name', ... } }
>> response = Sequencer.process('Import::Exchange::AvailableFolders', parameters: { ews_config: { disable_ssl_verify: <true/false>, endpoint: <ENDPOINT>, user: <USER>, password: <PASSWORD> } })

# should return an array of hashes describing any invalid Exchange folder path names
>> bad_paths = response[:folders].values.reject { |path| path.encoding == Encoding::UTF_8 && path.valid_encoding? }.map { |path| { path: path, encoding: path.encoding, valid: path.valid_encoding? } }

# should create a file `bug_report_2152.yml` in the current working directory;
# please send this file to support@zammad.com and mention that it’s for Ryan.
>> File.write('bug_report_2152.yml', bad_paths.to_yaml)
```

**Closed as completed** 2018-08-23 08:56 UTC
Labels: bug, import, waiting for feedback, verified
