### ISSUE TITLE
Default ticket state for agent-created ticket

### ISSUE THREAD

**Issue by nublaii** [zammad/zammad#881] opened 2017-03-23 09:00 UTC
My installation is an import from OTRS.

I have all my old OTRS ticket states available, but when, as an agent, I create a new ticket the default preselected status is 'closed succesful'.

Is there a way to change the default for agent created tickets to be 'new'?

**Comment by thorsteneckel** [comment] 2017-04-08 10:39
Hi @nublaii - This is a duplicate of #890 . There is no solution ready yet but we are working on one. I hope to get it ready till the next release. Closing for now.

**Closed by thorsteneckel** 2017-04-08 10:39 UTC
Labels: bug

**Comment by felicitus** [comment] 2017-06-08 13:09
@thorsteneckel unfortunately your answer does not answer the original question. The other issue #890 is about importing things from OTRS, however, this is about if and how to define a default state for new tickets.

Is the default ticket state for new tickets hard-coded?

**Comment by thorsteneckel** [comment] 2017-06-08 13:49
Hi @felicitus - this topic is a bit complicated since we have to keep the IDs of OTRS for some reasons and update our local objects accordingly. This leads to the point where the OTRS state `closed successful` is the new Zammad state `open` since they both have the ID `2`.

However we changed this with the commits in the other issue to reset some state settings but it looks like this issue wasn't properly resolved.

Could you please confirm that you are using the latest version of Zammad 1.5? I'll reopen the issue and verify it in our test environment then. Thanks!

**Comment by felicitus** [comment] 2017-06-13 10:58
@thorsteneckel yes, I have version 1.5. Should I open a new issue for clarification or is it OK to append my information to this issue?

**Comment by thorsteneckel** [comment] 2017-06-13 11:00
Thanks! Would be great if you could create a new issue. It may there is a different cause.

**Comment by felicitus** [comment] 2017-06-13 11:15
Done ;)
