### ISSUE TITLE
reply all missing when Zammad email-in is in cc

### ISSUE THREAD

**Issue by maggusf** [zammad/zammad#2426] opened 2019-01-10 08:44 UTC
### Infos:

* Used Zammad version: 2.7
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: postgresql 9.2.23
* Elasticsearch version: 5.6.8-1
* Browser + version: safari 12.0.2
* Ticket-ID: #1047717, #10102970, #10183049

### Expected behavior:

* reply all should be visible if you have more than one uniq email address in email header and include every email address (including Zammad input adresses)

### Actual behavior:

* reply all is missing if you have another input email address (email-in channel) in cc and only 1 additional client/agent email in cc

### Steps to reproduce the behavior:

* send from agents mail account an email to Zammad email-in 1 and cc Zammad email-in 2 + additional agent - no reply all possible  (when adding another second agent mail address to cc field then he reply all is visible but will not include the other Zammad email input address) 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-01-10 08:50
Thanks for taking the time to fill out a github issue.

Please fill in the missing information for database, elasticsearch and browser version.
Also, right now I struggle in understanding the described steps to reproduce this issue. Maybe screenshots will help here.

**Comment by maggusf** [comment] 2019-01-10 09:06
updated description

and a more detailed reproduce process:
assuming 
peter@company is an agent
paul@company is an agent
julia@inc is an cusotmer
sales@company is an email input channel
marketing@company is an email input channel

peter@company emails 
to sales@store
cc marketing@store + julia@inc
--> no reply all in web

peter@company emails 
to sales@store
cc marketing@store + julia@inc + paul@company
--> reply all in web but marketing@store is not included in cc during reply all (Julia and Paul are included)

**Comment by ghost** [comment] 2019-01-22 15:07
I can confirm this issue. Same repro steps as @maggusf described. We are using Zammad Version 2.8

**Comment by maggusf** [comment] 2019-01-28 07:24
@MrGeneration 
two weeks without an update, any news so far?

**Comment by MrGeneration** [comment] 2019-01-28 13:13
**This partly works as designed:**
Zammad ignores it's own E-Mail-Addresses, because it normally doesn't make sense to write to your own system. Depending on your Mail-Server configuration (if you use several aliases with just one mailbox), you'll only receive one ticket. If you have several mailboxes, you'll receive two independent tickets which you can't reply to both (at the same time). This is by design, so it makes no sense to give the other group address within a CC.

We won't change that part.

**the Bug:**
I could verify the bug only for customer + group mail being within the CC. You're right, reply all is missing here.

**To the enhancement part:**
What we should do is to recognize that the same Mail has been sent to several group mails from Zammad and link those tickets with each other (should be able to disable that via GUI). This will help agents to be aware that there might be another department working on that too.

As both departmants might work on different parts of the mail, this should be a valid use case. I hope this helps.

Sorry for the category hick hack. 🗡

**Comment by maggusf** [comment] 2019-07-01 14:31
any update on this?

**Comment by MrGeneration** [comment] 2019-07-01 14:34
I'm limitting the conversation to contributors only.
Please don't get me wrong here, this is to keep the noise level on issues low and is nothing against you!

We currently have no updates on this, if the issue moves into the direction of solving, we'll post an update on this issue. Sorry for the wait, we currently experience quite some load.

Edit: Doh, sorry for the closing... wrong button.

**Comment by dominikklein** [comment] 2023-06-02 11:41
@maggusf I will close this issue for now, because like already mentioned, in general, the system addresses are not taken into consideration for the "reply all" functionality.
We also can not reproduce any situation, where it's not working when more than one none system address in the article exists.
When there is still a valid issue for you, except for the ignored system addresses, feel free to send some additional information for reproduction.

The enhancement idea should be handled in its own topic.

**Closed as completed by dominikklein** 2023-06-02 11:41 UTC
Labels: bug, verified, prioritised by payment, mail processing, ticket: actions
