### ISSUE TITLE
No line break adding Tags

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3388] opened 2021-01-29 12:46 UTC
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* T#1083174

### Expected behavior:

* Zammad should add a line break while adding tags in an overview or in the scheduler when the line reaches the border of the window. 

### Actual behavior:

* When multiple tags are added to an overview or in the scheduler, it can look like this: 

![image](https://user-images.githubusercontent.com/69846837/106276002-2184b280-6237-11eb-80cc-5e05e50b72f5.png)

* Tags breaking out of the window

### Steps to reproduce the behavior:

* Add many tags to the conditions for an overview or in the scheduler

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment] 2021-01-29 15:45
Duplicate of #2536

**Closed as completed by martini** 2021-01-29 15:45 UTC
Labels: duplicate
