### ISSUE TITLE
Customers names sometimes numbers

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4063] opened 2022-04-21 15:29 UTC
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04.3
* Database + version: newest
* Elasticsearch version: newest Form yesterday
* Browser + version: Microsoft Edge 100

### Expected behavior:
Name of customers are visible 

### Actual behavior:
Sometimes after work on my tickets and switch from one Ticket to another one the name of many customers are replaced by a number (I think the database ID or so?!)

![1EF7E260-68FC-47B5-AFBD-6370CCAFA8DD](https://user-images.githubusercontent.com/1473674/164492445-629ac929-2f80-447a-b43f-095ff5fe31ea.png)

### Steps to reproduce the behavior:
I can‘t reproduce it by an action. Yesterday I had this problem only one time. If I logout and login again, the names are shown and correct. Today I had the problem three times. Because this I updated Zammad yesterday to 5.1.1 form 5.1.0 and restarted the Server. The problem still exists. :(
I killed yesterday all sessions from any user.
My college has the same problem last week.
The server has no performance problems (active agents: 11, 2 customers at the Same time. Hardware: 4CPU with 16GB RAM and WEB_CONCURRENCY=4, 1GB Ramdisk (used 20% from that))

**Comment by MrGeneration** [comment] 2022-04-21 18:21
Duplicate of #4040

**Closed as completed by MrGeneration** 2022-04-21 18:21 UTC
Labels: duplicate
