### ISSUE TITLE
Stuck in session of a different user

### ISSUE THREAD

**Issue by backbord** [zammad/zammad#2567] opened 2019-05-09 09:48 UTC
### Infos:

* Used Zammad version: 2.9.0 (zammad.x86_64 2.9.0-1550130576.fe1640fd.centos7 @zammad)
* Installation method (source, package, ..): yum
* Operating system: CentOS 7
* Database + version: PostgreSQL
* Elasticsearch version:
* Browser + version: Chrome 74 under Windows 10

It's difficult for me to explain, but I'll try.

If there's something I can look in 8 GB of production.log for, I'll happily try, but I won't be able to attach the whole log.

### Expected behavior:

* Zammad sessions cannot be hijacked or reused by different users.

### Actual behavior:

* Zammad session token seems to have been reused for a session of a different user without being expired.

### Steps to reproduce the behavior:
I don't have a deterministic process to reproduce the behavior.
What I did was the following:

* Log in to Zammad in the browser on my Windows machine.
* Set my Windows Machine to Hibernate.
* Wait a day or so.
* Coworker X logs into Zammad.
* Wake my Windows Machine.
* Still in the existing browser session in Zammad, (as an admin) I tried to change some roles but was told that I did not have the permission. My profile pic indicated that it was still my session.
* Refresh the Zammad page in the browser to clear any caches.
* The profile now showed the pic of coworker X who's not an admin.
* Wait, that's not my session!
* Click on profile --> log (coworker X) out. Log back in.
* Now it's my account in a new session again.

Yes I'm sure this is a bug and no feature request or a general question.

Best regards,
Tim

PS: Thanks for such a great tool!

**Comment by MrGeneration** [comment] 2019-05-09 09:54
Thanks for your contribution.
Just to double check:

You're basically saying that you log in to Zammad, put it to sleep/hibernate and in the mean time a coworker logs in into Zammad at another machine. When getting your machine back online, you suddendly have the session details of your co worker as long as you don't log out?

Is this installation 100% original package or did you change *any* part of the source code of Zammad?

**Comment by backbord** [comment] 2019-05-09 14:14
Hi MrGeneration,
yes that's exactly the case.

We're using a SSO solution, so let me check with IT if any changes where done.

I'll get back to you shortly.

**Comment by backbord** [comment] 2019-05-09 14:25
So yeah, we're using Zammad behind an Apache that is configured to use SSO via Kerberos and pass the login on to Zammad.
For that to work, we added the following two lines at the beginning of function `create_sso` in file `/path/to/zammad/app/controllers/sessions_controller.rb` as proposed in https://github.com/zammad/zammad/issues/1192#issuecomment-353344234:
```ruby
# export required environment variables for sso
ENV['REMOTE_USER'] = request.env['REMOTE_USER']
ENV['HTTP_REMOTE_USER'] = request.env['HTTP_REMOTE_USER']
```

Maybe this isn't an issue with Zammad (in that case: sorry!).

Could you advise if this behaviour might come from Zammad?

Everything else is stock Zammad.

EDIT: Talked to IT again. My Windows machine was *not* using Kerberos SSO at all, I was logging in with username/password via the Zammad login screen. My coworker X was using Kerberos SSO.

Thanks for your time,
Tim

PS: The full function reads as follows.
```ruby
  def create_sso
 
    # export required environment variables for sso
    ENV['REMOTE_USER'] = request.env['REMOTE_USER']
    ENV['HTTP_REMOTE_USER'] = request.env['HTTP_REMOTE_USER']

    # in case, remove switched_from_user_id
    session[:switched_from_user_id] = nil

    user = User.sso(params)

    # Log the authorizing user in.
    if user

      # check maintenance mode
      if check_maintenance_only(user)
        redirect_to '/#'
        return
      end

      # set current session user
      current_user_set(user)

      # log new session
      user.activity_stream_log('session started', user.id, true)

      # remember last login date
      user.update_last_login
    end

    # redirect to app
    redirect_to '/#'
  end
```

**Comment by thorsteneckel** [comment] 2019-07-25 11:46
Hi @backbord - we were facing the same issue for one of our support customers. Since SSO is currently not officially supported but more of a beta functionality I'll close this issue as a duplicate of #1192. Unfortunately we need to change a few things for adding the SSO support but it will be done over the next weeks 👍 Stay tuned and subscribe to #1192

**Closed as completed by thorsteneckel** 2019-07-25 11:46 UTC
Labels: duplicate
