### ISSUE TITLE
How to delete all tickets?

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1536] opened 2017-10-13 12:26 UTC
### Infos:

* Used Zammad version: 2

### Expected behavior:

* I can understand that even a Zammad admin can't delete tickets because there is the server admin and there is the Zammad admin. But maybe the server admin could manually edit the database (like e.g. change from 0 to 1 in a column delete_tickets) to make the Zammad admin being able to delete tickets.

### Actual behavior:

* No possibility to delete a ticket.

### Steps to reproduce the behavior:

* Try to delete a ticket, even if you're admin.

I understand that because of revision-proof a ticket can normally not be deleted. But what about he above mentioned if the server admin (who has access anyway through console) makes a Zammad admin into a Zammad super admin (by like mentioned above e.g. changing a column-entry directly in the database) so that he can delete tickets now?

Meanwhile, how to delete all tickets through the console?

**Comment by thorsteneckel** [comment] 2017-10-13 12:31
Duplicate of #214 - Fixed with: https://github.com/zammad/zammad/issues/214#issuecomment-299422393

**Closed by thorsteneckel** 2017-10-13 12:31 UTC
