### ISSUE TITLE
It seems you're running an external Elasticsearch server on http://localhost:9200

### ISSUE THREAD

**Issue by kevin-olbrich** [zammad/zammad#2400] opened 2018-12-11 15:10 UTC
### Infos:

* Used Zammad version: 2.8.0 (just upgraded from 2.6.0)
* Installation method (source, package, ..): EL7 package
* Operating system: CentOS 7
* Database + version: PostgreSQL, latest from EPEL
* Elasticsearch version: 5.6.12 / 5.6.13
* Browser + version: -/-

### Expected behavior:

* Upgrade should succeed

### Actual behavior:

```
# Updating translations...
# Configuring Elasticsearch...
-> removing [ingest-attachment]...
-> Downloading ingest-attachment from elastic
[=================================================] 100%  
Exception in thread "main" java.lang.IllegalStateException: /usr/share/elasticsearch/lib/plugin-cli-5.6.13.jar requires Elasticsearch 5.6.13, your system: 5.6.12
        at org.elasticsearch.bootstrap.JarHell.checkManifest(JarHell.java:230)
        at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:183)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:558)
        at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:527)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

 It seems you're running an external Elasticsearch server on http://localhost:9200
Stopping local elasticsearch server...

 Please get sure to install the 'ingest-attachment' plugin on your Elasticsearch server by:
/usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment

After this you might need to rebuild the searchindex by:
zammad run rake searchindex:rebuild
# Starting Zammad
# Creating webserver bootstart
# Restarting webserver nginx

```

### Steps to reproduce the behavior:

* Not sure, happens for me on every update
Actualy it sounds like two bugs:
1) localhost ES is detected as external
2) ES plugin is pulled / upgraded with incompatible build

Most of the time my ES index is screwed up after the upgrade and needs to rebuild completely.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2018-12-13 09:22
Zammad should support localhost-URLs as well as just 127.0.0.1

https://github.com/zammad/zammad/blob/ad19b532a9c3759a686417a619bb461d67a68b9d/contrib/packager.io/functions#L251

**Comment by kevin-olbrich** [comment] 2018-12-13 10:05
https://github.com/zammad/zammad/pull/2404

**Comment by thorsteneckel** [comment] 2018-12-13 13:39
Reopening. The `ES plugin is pulled / upgraded with incompatible build` part of the issue is not addressed yet.

**Comment by monotek** [comment] 2018-12-13 14:26
I have to check if we can force plugin version to be same as elasticsearch version.
Problem is see is how to get the current elasticsearch version. Curl request would need Elasticsearch already running. Otherwise we have to check via APT or RPM. 

Not sure why this happens now. Imho we should have hit this problem earlier.

Currently i have no time to inverstigat further...

Upgrading Elasticsearch first should be a workaround for now.

**Comment by MrGeneration** [comment] 2019-07-11 21:32
Please also note that the service doesn't come back up during upgrade.

Edit with further information:
```
 It seems you're running an external Elasticsearch server on I, [2019-07-17T17:42:34.793127 #32148-47171792750080]  INFO -- : Setting.set('models_searchable', ["KnowledgeBase::Answer::Translation", "Chat::Session", "Organization", "Ticket", "User"])
http://localhost:9200
Stopping local elasticsearch server...

 Please get sure to install the 'ingest-attachment' plugin on your Elasticsearch server by:
/usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment
```

(Offending line: https://github.com/zammad/zammad/blob/develop/contrib/packager.io/functions#L251 )

**Comment by MrGeneration** [comment] 2019-11-19 11:56
As discussed in issue https://github.com/zammad/zammad/issues/2811 we should also simply not touch the local elasticsearch installation at all if we're sure we have an external elasticsearch server. :)

**Comment by MrGeneration** [comment] 2019-11-26 19:21
Good news. I found a solution for this issue - it actually also solves this ugly error message during installation (e.g. when no ES is configured yet, it is reproducable if you have a current Zammad without `es_url` being set or containing anything). 

```text
 It seems you're running an external Elasticsearch server on I, [2019-11-26T18:04:29.351662 #18712-47323604583920]  INFO -- : Setting.set('models_searchable', ["Ticket", "User", "Chat::Session", "Organization", "KnowledgeBase::Answer::Translation"])
Stopping local elasticsearch server...

 Please get sure to install the 'ingest-attachment' plugin on your Elasticsearch server by:
/usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment

After this you might need to rebuild the searchindex by:
zammad run rake searchindex:rebuild
I, [2019-11-26T18:04:39.057942 #18893-47102005822960]  INFO -- : Setting.set('models_searchable', ["Ticket", "User", "Chat::Session", "Organization", "KnowledgeBase::Answer::Translation"])
Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.

/opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41: syntax error, unexpected tCONSTANT, expecting ')'
...t('models_searchable', ["Ticket", "User", "Chat::Session", "...
...                         ^~~~~~
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41: syntax error, unexpected tCONSTANT, expecting end-of-input
...s_searchable', ["Ticket", "User", "Chat::Session", "Organiza...
...                           ^~~~
# (Re)building Elasticsearch searchindex...
```

Reason for the above is that Zammad / ruby returns more than one line which is being saved within the variable ``ES_CONNECTION``. Of course two lines is a bad idea (especially because the output on line 1 is kinda breaking things for us in that process). Solution for this is to only take the last line, because it should contain the value (or a blank line).

This enables us to check for ``http://localhost:9200`` and ``http://127.0.0.1:9200`` more realible.
Nice side effect: This also solves the false positive match of running an external elasticsearch server.

Also, to round this up, I insist on us stopping to stop Elasticsearch if  it is a remote system.
Reason for this: Normally ES would already be disabled and not running. Or, like in above case, we'd even break environments.

I think that's a good middle way. I'm preparing below code for spellcheck and PR on our internal GIT.



```bash
function setup_elasticsearch () {
  echo "# Configuring Elasticsearch..."

  ES_CONNECTION="$(zammad run rails r "puts Setting.get('es_url')"| tail -n 1 2>> /dev/null)"

  if [ -z "${ES_CONNECTION}" ]; then
    echo "-- Nevermind, no es_url is set, leaving Elasticsearch untouched ...!"
    echo "-- The above is all right if you don't want to use Elasticsearch (locally) - if this is not intended, consult https://docs.zammad.org !"
    return 0
  fi

  if [ -n "$(/usr/share/elasticsearch/bin/elasticsearch-plugin list | grep mapper-attachments)" ]; then
    REBUILD_ES_SEARCHINDEX="yes"

    echo "# Deleting old elasticsearch index..."
    zammad run rake searchindex:drop

    yes | /usr/share/elasticsearch/bin/elasticsearch-plugin -s remove mapper-attachments

  elif [ -n "$(/usr/share/elasticsearch/bin/elasticsearch-plugin list | grep ingest-attachment)" ]; then
    yes | /usr/share/elasticsearch/bin/elasticsearch-plugin -s remove ingest-attachment
  fi

  yes | /usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment

  if [ "${ES_CONNECTION}" == "http://127.0.0.1:9200" ] || [ "${ES_CONNECTION}" == "http://localhost:9200" ]; then
    ${INIT_CMD} restart elasticsearch
  else
    echo -e "\n It seems you're running an external Elasticsearch server on ${ES_CONNECTION}"
    echo -e "\n We'll not touch your Elasticsearch on the local and remote system."
    echo -e "\n Please get sure to install the 'ingest-attachment' plugin on your Elasticsearch server by:"
    echo -e "/usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment"
    echo -e "\nAfter this you might need to rebuild the searchindex by:"
    echo -e "zammad run rake searchindex:rebuild"
  fi
}
```

**Comment by thorsteneckel** [comment] 2019-11-27 07:16
Hi @MrGeneration - great catch! I'd like to more about the outputted lines you mentioned before jumping to a conclusion. What exactly are the lines stored in `ES_CONNECTION` that break the functionality?

**Comment by MrGeneration** [comment] 2019-11-27 08:08
Hey Thorsten,

sorry, long day yesterday. :-D

This is a two phased issue. Some parts only affect you if your Zammad is logging to STDOUT. 
Note: This is since Zammad 3.0 always the phase during installation, until we change it to log file at a certain point. I mean yes, moving it to somewhere else **sometimes** would help, but I've had different outputs on different systems...

Anyway, with STDOUT Zammad returns thre following (what we write to ``ES_CONNECTION``):
```
I, [2019-11-27T08:01:38.862476 #5467-47411347908080] INFO -- : Setting.set('models_searchable', ["Ticket", "User", "Chat::Session", "Organization", "KnowledgeBase::Answer::Translation"]) 
http://localhost:9200
```

While we'd expect the following only:
```
http://localhost:9200
```

These two lines cause different issues, one would be syntax errors (which was my planned homework in https://github.com/zammad/zammad/issues/2674 today) and the second one is the already mentioned
```
I, [2019-11-26T18:04:39.057942 #18893-47102005822960]  INFO -- : Setting.set('models_searchable', ["Ticket", "User", "Chat::Session", "Organization", "KnowledgeBase::Answer::Translation"])
Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.

/opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41: syntax error, unexpected tCONSTANT, expecting ')'
...t('models_searchable', ["Ticket", "User", "Chat::Session", "...
...                         ^~~~~~
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41: syntax error, unexpected tCONSTANT, expecting end-of-input
...s_searchable', ["Ticket", "User", "Chat::Session", "Organiza...
...  
```

I hope this helps more :)

**Comment by thorsteneckel** [comment] 2019-11-27 08:11
Ah! Great! So the root issue we should solve is to not print that first line 🤔 Otherwise we would have to adjust the script again if there is another log line printed in the future. We need a dev to have a look. I try to fit it in my schedule but can't guarantee.

**Comment by MrGeneration** [comment] 2019-11-27 08:16
> So the root issue we should solve is to not print that first line 🤔 Otherwise we would have to adjust the script again if there is another log line printed in the future

Yes and no.
This is why I added `| tail -n 1` to the fetch of the variable.

I expect Zammad to return one or two magic lines, that's fine for me, but what I really expect after is that the LAST line is the commands output. So technically the above solution "does not care about the name of lines" :->

**Closed as completed** 2019-11-27 09:23 UTC
Labels: bug, migration / update
