### ISSUE TITLE
Simple quote characters (`'`) not properly displayed

### ISSUE THREAD

**Issue by benrubson** [zammad/zammad#3733] opened 2021-09-10 12:07 UTC
Hi,

### Infos:

* Used Zammad version: 4.1.0-1631024881.3edca5e9.buster amd64
* Installation method (source, package, ..): package
* Operating system: Debian 10
* Database + version: mariadb-server 10.3.29-0+deb10u1 amd64
* Elasticsearch version: 7.14.1 amd64
* Browser + version: Safari, Firefox (lastest versions)

### Expected behavior:

* Simple quote characters (`'`) in Zammad strings are shown as simple quotes.

### Actual behavior:

* Some simple quotes (`'`) are shown as their HTML entity (`&#39;`).

![Screenshot 2021-09-10 at 10 50 52](https://user-images.githubusercontent.com/6764151/132850860-4fed75e0-b43f-4b28-8e48-20fd6ba485d6.png)
![Screenshot 2021-09-10 at 10 51 21](https://user-images.githubusercontent.com/6764151/132850867-44e7a552-dd5f-46d9-bfb9-a4a3224244ba.png)

### Steps to reproduce the behavior:

* Put simple quote character (`'`) in some translations, and browse Zammad interface to see whether they are properly displayed or not.

Many thanks 👍

**Comment by MrGeneration** [comment] 2021-09-10 12:11
Note sure if this will be fixed with 5.1 @mgruner ?

Context:
This is not always failing but seems to affect specific situations - e.g. within data privacy remove dialogue:
![image](https://user-images.githubusercontent.com/6549061/132851425-5781c9a2-dd61-4185-b831-ed8141cf1c2e.png)

Other places are fine:
![image](https://user-images.githubusercontent.com/6549061/132851444-6e5498d2-0bdd-4028-8b20-a7d9b6ee2c3b.png)

**Comment by mgruner** [comment] 2021-09-10 13:07
@MrGeneration I believe that this is not related to the changes that the weblate migration will bring, since they don't affect how translation data is handled inside of Zammad once it is imported to the database. As you indicated this is probably related to improper handling of the data in some parts of the front end.

**Comment by mantas** [comment] 2021-09-10 14:11
This usually happens if the string runs through HTML sanitizer twice. Usually it requires manually investigating every single case.

**Closed as completed** 2021-10-13 11:29 UTC
Labels: bug, verified, frontend

**Comment by benrubson** [comment] 2021-10-29 07:26
Hi,
Seems like https://github.com/zammad/zammad/commit/2bd4ceeedfb999d4e948b8aa8b91a759eb7a4c1b has not been backported into 5.0.2 ?
Could we then backport it to stable please ?
Thank you again 👍

**Comment by MrGeneration** [comment] 2021-10-30 09:56
Zammad 5.0.2 was a mery security release and thus does not contain any bug fixes. Sorry.
We're in general not providing any ETAs for bug fixes etc.

**Comment by benrubson** [comment] 2021-11-10 17:24
Hi,
Running `5.0.2-1636369479.cb3516e4` which includes the patch, and fixes the bug, at least in the 2 places mentioned in the first post above.
However seems like there are some places where bug still triggers :

![image](https://user-images.githubusercontent.com/6764151/141161716-5b1a209e-55aa-4669-8ee0-5772331a7cd6.png)

Could we then re-open this ?
Many thanks 👍

**Comment by MrGeneration** [comment] 2021-11-10 17:26
No that's a new issue please. You can mark the new issue as a regression of this issue for better overview.
