### ISSUE TITLE
Wrong customer avatar and popover information, on FB post comments

### ISSUE THREAD

**Issue by chrisblech** [zammad/zammad#1850] opened 2018-02-24 11:06 UTC
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): deb package
* Operating system: Debian 9.3
* Database + version: bundeled
* Elasticsearch version: 5.6
* Browser + version: Chrome 63.0.3239.108

### Expected behavior:

* On comments (/replies) to facebook page posts, zammad shows avatar next to the comment. This avatar should be corresponding to the comment author (=customer)

### Actual behavior:

* zammad shows sometimes the wrong avatar and mouseover (from one of the previous commenting FB user), next to comments from other FB users.

### Steps to reproduce the behavior:

* activate FB channel
* create a feed post on facebook page
* FB users A comments (-> zammad shows correct avatar, belonging to this user)
* FB user B comments (-> zammad shows correct avatar, belonging to this user)
* FB user "Ni Ck" comments (-> zammad shows correct avatar, belonging to this user)
* FB user "Al Boland" comments (-> zammad shows wrong avatar, belonging to user "Ni Ck")
* FB user "Bernhard Krämer" comments (-> zammad shows wrong avatar, belonging to user "Ni Ck")
* FB user "Jonas Tumbrinck" comments (-> zammad shows wrong avatar again. See screenshot)
* hover mouse over the last avatar: Information for user "Ni Ck" is shown

Yes I'm sure this is a bug and no feature request or a general question.

![image](https://user-images.githubusercontent.com/2414929/36629730-a20db970-195a-11e8-8ddb-855e33996aa6.png)
(Screenshot lacks the first comments, sorry)

**Comment by thorsteneckel** [comment] 2018-02-24 13:08
Hi @chrisblech - Thanks for reporting this. Looks like a duplicate of #1776 to me. Closing for now.

**Closed by thorsteneckel** 2018-02-24 13:08 UTC
