### ISSUE TITLE
Repositories broken

### ISSUE THREAD

**Issue by mahescho** [zammad/zammad#2795] opened 2019-11-01 07:09 UTC
The repositories are broken:

https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 9 Release
  404  Not Found

**Comment by MrGeneration** [comment] 2019-11-01 10:22
Seemed to be a temporary issue, as I can't reproduce it.
Therefore closing now.

If your issue still persists, ensure that if you're using any security appliances or proxies, these are not filtering away the above mentioned URL.

Also, if this still persists, please give us more context of what you've done so we can try to reproduce it. Please note that this repository is for Bugs only, this issue is very close to a technical question, which should life in the Community: https://community.zammad.org

Closing now.

**Closed as completed by MrGeneration** 2019-11-01 10:22 UTC
Labels: can't reproduce
