### ISSUE TITLE
group-by sorting wrong when paginating

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#3857] opened 2021-11-18 10:14 UTC
### Infos:

* Used Zammad version: 5.0.1
* Installation method (source, package, ..): source
* Operating system: Ubuntu 18.04.6 LTS
* Database + version: PSQL11
* Elasticsearch version: ES 7.6.1
* Browser + version: FF 94

### Expected behavior:

* When showing open and closed tickets, using `group-by` State - either up and down - it should work regardless of how many issues will be shown.

### Actual behavior:

* When showing open and closed tickets, using `group-by` State it works reliably for one page (read: no pagination) as expected. When seeing 14 pages (about 2000 tickets, 99% closed) the result is the following:

* Case 1
  * group-by: `State`
  * group-by-direction: `down`
  * Result: **`open` group is shown at the bottom of page 1**
* Case 2
  * group-by: `State`
  * group-by-direction: `up`
  * Result: **`open` group is shown at the bottom of page 14**

### Steps to reproduce the behavior:

* Have 2000+ tickets (possibly less, maybe only 2 pages of pagination is also broken)
* Have an overview which shows open + closed tickets
* `order-by`: Created, down, `group-by`: State, (down|up)

We upgraded from 4.3 to 5.0.1 yesterday and open tickets seem to be hidden at the end of page 1 currently. I have checked the `CHANGELOG.md` and found this issue (https://github.com/zammad/zammad/issues/3737) which seems related and which included this change (https://github.com/zammad/zammad/commit/c4ccbc46ff753d50f2405f7ca62e37201ee9ca5c). But what confuses me, is that it is in the `CHANGELOG.md` for `5.0.1`, but is tagged with `5.0.3`? 🤔

**Comment by t-shehab** [comment] 2023-05-11 08:54
Unable to reproduce at the moment. Closing for now.

**Closed as completed by t-shehab** 2023-05-11 08:54 UTC
Labels: can't reproduce
