### ISSUE TITLE
User Is Invisible after Invite

### ISSUE THREAD

**Issue by chriskyndrid** [zammad/zammad#2798] opened 2019-11-05 05:51 UTC
### Infos:

* Used Zammad version: zammad-3.1.0
* Installation method (source, package, ..): zammad-3.1.0-1572420711.b7bfdcd4.centos7.x86_64
* Operating system: CentOS 7
* Database + version: Latest
* Elasticsearch version: elasticsearch-7.4.2-1.x86_64
* Browser + version: Chrome

### Expected behavior:

All users are listed.

### Actual behavior:

Some users are missing and invisible but valid in the database and able to login.

### Steps to reproduce the behavior:

I did a fresh install of Zammad(and I'm a first time user). Then configured the system and was going through a number of pre-production tests. I encountered a situation where Settings -> Users will not list certain users that are active. I believe it may have to do with the specific process as follows, although I have not attempted to reproduce the issue. 

Note: I am a programmer, although I'm not a Ruby programmer. Most of my work these days is in Rust and TypeScript, with some C and PHP. 

1) Disable 'Security -> New User Accounts' and 'Security -> Lost Password'.
2) Navigate to 'First Steps' and 'Invite' and assign Administrative and Agent permissions to the user.
3) Issue the invitation. 

**First Issue:** Because 'Security -> Lost Password' is set to false, the recipient of the invitation will not be able to enter an initial password via the issued invitation URL. 

**Second Issue:** Upon re-enabling the 'Security -> Lost Password' feature, the user will be able to click the Invitation and will be presented with an enter password dialog. After entering the password, the User will be logged in. However, the user will effectively be 'invisible' to the System. By this I mean, the user will not be listed in the 'Settings -> Users' screen, nor will the user be seen on the 'Chat -> Available Agents' screen, and possibly other screens. 

This was the sequence of events I followed. I have not tested to see if the invitation function is non-functional in general, however, if that was the case, Issue One should still be corrected as I do not think that would be desired functionality in that scenario(as it is a different password management path than 'forgot password').  

Lastly, I dropped to a debug console and reviewed the JSON response to GET /users/search. As you'll notice in the JSON listed below, the user_ids: array, disagrees with the assets.Users array. I understand id 1 should be exempted, but it's not clear why id 10, in this scenario is as well. 

Scanning quickly at the records in Postgres, and being totally unfamiliar with the schema, it was not immediately clear that a flag/etc might not be set properly. I also browsed through the app/controllers/users_controller.rb, but it wasn't clear either what could be causing the issue(and I don't really know Ruby). I initially thought it might be an issue related to calling '.uniq' (E.G. 10 getting treated as 1 for some reason):

      render json: {
        assets:   assets,
        user_ids: user_ids.uniq,
      }

but altering this didn't impact anything. Additional information is as follows:

```
3:
accounts: {}
active: true
address: ""
authorization_ids: []
city: ""
country: ""
created_at: "2019-10-29T22:54:24.740Z"
created_by_id: 1
department: ""
email: "user_1@XXXX"
fax: ""
firstname: "User 1"
group_ids: {1: ["full"], 2: ["full"]}
id: 3
image: null
image_source: null
last_login: "2019-11-05T04:41:49.630Z"
lastname: "User 1"
login: "user_1@test.com"
login_failed: 0
mobile: ""
note: ""
organization_id: null
organization_ids: []
out_of_office: false
out_of_office_end_at: null
out_of_office_replacement_id: null
out_of_office_start_at: null
phone: ""
preferences: {notification_config: {matrix: {,…}}, locale: "en-us", intro: true,…}
role_ids: [1, 2]
source: null
street: ""
updated_at: "2019-11-05T04:41:49.634Z"
updated_by_id: 10
verified: false
vip: false
web: ""
zip: ""

10: 
accounts: {}
active: true
address: ""
authorization_ids: []
city: ""
country: ""
created_at: "2019-11-05T04:17:29.434Z"
created_by_id: 3
department: ""
email: "User_2@test.com"
fax: ""
firstname: "User 2"
group_ids: {1: ["full"], 2: ["full"]}
id: 10
image: null
image_source: null
last_login: "2019-11-05T04:34:40.745Z"
lastname: "User 2"
login: "User_2@test.com"
login_failed: 0
mobile: ""
note: ""
organization_id: null
organization_ids: []
out_of_office: false
out_of_office_end_at: null
out_of_office_replacement_id: null
out_of_office_start_at: null
phone: ""
preferences: {notification_config: {matrix: {,…}}, locale: "en-us", intro: true, chat: {active: {1: "on"}}}
role_ids: [1, 2]
source: null
street: ""
updated_at: "2019-11-05T04:58:07.492Z"
updated_by_id: 3
verified: false
vip: false
web: ""
zip: ""

user_ids: [3]
0: 3
```

If there is a way I can alter user id 10 in the database to correct that issue by hand, that would be great pending a fix/other.

Thanks,
Chris

**Comment by MrGeneration** [comment] 2019-11-05 09:40
Sorry but I do believe that this is a technical question rather than a bug.
Technical questions should better life at the Community: https://community.zammad.org


Just to double check and give you some background info on why what you're trying to do is not working as you expect:

### JSON / javascript console commands
You're checking the users via your developer console - that's great, but does never return the real datasets that are available entirely. Yes, Zammad does push tons of information to the WebApp, but only if the data does affect the user at any point (e.g. ticket in the overview, list of agents what so ever).

That's also the reason why you see a big gap within the User-IDs.
Better check on the rails console, as this will tell you exactly what's going on:

```
User.count
User.pluck(:id)
```

I've been testing your above statement and cannot reproduce this. The user is immediatly created upon invite. (Just wanted to make sure I'm not telling you some BS without knowing exactly :D)

### User list
The user list comes from Elasticsearch (if enabled).
Now there's two possible issues you're having:

* Your elasticsearch is too slow and still needs to index the new user OR
* You did not change the user view and expected the data to magically appear
  * Spoiler: It does not, if you reload the WebApp or change to e.g. Group and then back to Users, your user(s) should appear in the list. Please also note that this list is limited and will only show the most current users at some point.


### Security "Lost Password"
In my opinion this is not a bug.
If you decide to disable your password recovery for whatever reason, that's perfectly fine. You can always set a password to the user if needed.


---

If any of the above statement is wrong, please let me know.
If not, if you have further questions, please use our Community. :-)

Closing for now.

**Closed as completed by MrGeneration** 2019-11-05 09:40 UTC
Labels: question

**Comment by chriskyndrid** [comment] 2019-11-05 16:21
Hi,

Thank you for getting back to me. However, I do have a followup question as there are a couple of points with respect to your statements I'd like to unpack further. 

First, my contention isn't with the user being created. I can clearly see the record in Postgres, so the user IS created, however, the user is NOT visible in the UI of the WebApp. Navigating to the Configuration -> Users screen yields no results for the user in question(in my sample user 10).  This means no followup action, such as altering the users information can occur, despite the user having permissions to access the system and utilize it. However, I CAN see the users information in the assets.Users array of the JSON response, but the "user_ids" array(see above), is missing that users id(note it's only id 3, when it should be id's [3,10] I believe), which made me think that is why it wasn't showing up in the UI. Regardless, the user CANNOT be reviewed or altered in the UI despite the user existing. I really don't care about gaps, and actually, there aren't any gaps, I just pasted the relevant excerpts. All other "users" have show up properly when following the ticketing funnel/etc. 

Second, on the issue of the 'Lost Password'. I really can't get on board with the idea this is a desired feature the way you have it programmed. The act of issuing an invite implies the user must first set their own password as a function of the invite. It has nothing to do with a "Lost Password", it's entirely associated with inviting Users into the system. IMO that is a different pathway, as Lost Password, implies the user has "forgotten" their password and needs a reset. If a User is invited into the system, and this feature is set to true, it should still be possible for the INVITED user to set their own password and gain access to the system, again IMO. Otherwise, the system should refuse to issue the invite OR you should alter the body of the e-mail that is dispatched to indicate the user has been invited and their Administrator will provide them with an appropriate set of credentials. I agree, on this particular issue(issue 2 I'm reporting), this may be more a design flaw(again IMO) or area where Zammad could be more clear to the invited user about how they should approach it. Really, I think it should be possible for an invited User to still set their initial password regardless of this flag, as an appropriate elevated user is the one issuing the correspondence, and without this, you're requiring the administrator to communicate sensitive credentials in a likely(over the phone or e-mail, other) less secure fashion. 

Regardless, in my reported case, it's impossible for me to Administer or alter user id 10, in our installation of zammad despite the user existing. 

As far as elasticsearch is concerned, the machine running our test instance is an AWS c5.xlarge instance with an SSD volume attached. It should be plenty fast for elasticsearch. Is there are a command I can issue to force elasticsearch to rebuild the index? If so, can you send me the command and I'll test it and confirm whether or not that's the issue? Again, in my scenario I can see the data as the result to GET /users/search, but the user_ids: array and assets.Users list disagree on the member id's.

**Comment by chriskyndrid** [comment] 2019-11-05 16:38
Followup on on this, as far as the issue 1 reported is concerned, the problem IS with elasticsearch as you eluded to, thank you for the pointer on that:

[https://community.zammad.org/t/solved-elasticsearch-issue-after-reindex/1828/2](url)

Explains the issue. I did a 'yum update' at some point in the middle of all this, and apparently that broken the ingest-attachment(or rather removed it) in elasticsearch running:

> /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-attachment
> zammad run rake searchindex:rebuild
> 

was necessary to get things going again, and now the user is showing back up. 

I still think you should reconsider altering the Lost Password situation to either remove the link for the invited user to set their initial password regardless of this setting, or, if it's set to true, the body of the e-mail dispatched should be altered to remove the link(as it's not possible for the invited user to set their initial password with this set to true).

Thanks again.

Chris
