### ISSUE TITLE
Attachment order is wrong

### ISSUE THREAD

**Issue by darklightmoon** [zammad/zammad#3584] opened 2021-06-01 13:21 UTC
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): package
* Operating system: Windows 10
* Database + version:
* Elasticsearch version: 
* Browser + version: Firefox

### Expected behavior:

* chronological order

### Actual behavior:

* 
![grafik](https://user-images.githubusercontent.com/59093874/120330342-001efa80-c2ed-11eb-87a5-1c8ed97cadcc.png)

### Steps to reproduce the behavior:

* Add some attachments to your ticket

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-06-01 13:24
Is this happening to all of your tickets or are you e.g. merging two tickets before hand? 
How to reproduce this? I don't believe that only enabling the display of attachments via hidden setting is enough.

**Comment by darklightmoon** [comment] 2021-06-01 15:03
We activated this function just a few days ago, so i can reproduce it. I looked up a few tickets randomly and there is always a disorder.
These are tickets that are not merged.

We use this command:
zammad run rails c    
Setting.set('ui_ticket_zoom_sidebar_article_attachments', true)

Is there any configuration to do?
I cannot find any documentation about that. 

Thank you!

**Comment by darklightmoon** [comment] 2021-06-01 15:05
![grafik](https://user-images.githubusercontent.com/59093874/120346233-7b87a880-c2fb-11eb-8c6f-cdfaef9d8340.png)

**Comment by MrGeneration** [comment] 2021-06-01 15:07
Please wait for our verification process. 
Sorry, we won't answer technical questions here.

**Comment by wucherpfennig** [comment] 2021-06-14 19:13
We can confirm this behavior. Feature activation was done like stated by @darklightmoon 

![image](https://user-images.githubusercontent.com/3634653/121946497-48123880-cd55-11eb-9158-c8be8adf0f96.png)

**Comment by darklightmoon** [comment] 2021-06-29 10:03
Is it wrong here? Should i open an issue via Zammad Community?

**Comment by MrGeneration** [comment] 2021-06-29 10:12
**Note for developers**:
I had the mixed date order like shown above and complained about in 1 out of 10 tickets. 
Incorrect order ticket can be found in our support instance here: `1086552`

Beside of that incorrect order I've also seen inconsistency for general sorting order. Sometimes ASC, sometimes DESC by date. 
It's not caused by ticket links or merged, all affected tickets are not merged in my test cases.

**Closed as completed** 2021-06-30 07:16 UTC
Labels: bug, UX/UI, verified
