### ISSUE TITLE
Tag dropdown not showing when creating new SLA

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#2606] opened 2019-06-13 10:35 UTC
### Infos:

* Used Zammad version: 3.0.x 
* Installation method (source, package, ..): Docker
* Operating system: Ubuntu 18.04
* Database + version: 
* Elasticsearch version:
* Browser + version: FF 67.0.1 and Safari 12.1.1

### Expected behavior:

* When creating a *tag* condition in the SLA application tag dropdown should show 

### Actual behavior:

* Tag dropdown is not showing

### Steps to reproduce the behavior:

* Create some tags
* Create a new SLA
   * in the SLA selector choose *tag* and type something in the tag input field

Yes I'm sure this is a bug and no feature request or a general question.

I've tested in the online free trial and behaves the same.

https://www.youtube.com/watch?v=v90aC9SezJk

**Comment by MrGeneration** [comment] 2019-06-13 11:21
Note that this does affect any part within the backend (so also Overviews, Triggers, Schedulers, etc)

**Comment by maxxer** [comment] 2019-07-01 13:39
The same applies to the *New postmaster filter* dialog

**Comment by thorsteneckel** [comment] 2021-02-12 14:44
I think this is a duplicate of #2890 and already resolve since Zammad 3.3. Please let us know if the issue still persists.

**Closed as completed by thorsteneckel** 2021-02-12 14:44 UTC
Labels: duplicate
