### ISSUE TITLE
o365 auth profile issue

### ISSUE THREAD

**Issue by davkar3n** [zammad/zammad#3112] opened 2020-07-10 10:31 UTC
Hi There,

We are using o365 auth.
App registration is created and given this permission.
**User.Read.All**

![image](https://user-images.githubusercontent.com/26478599/87144940-97382980-c2b9-11ea-9beb-3a2f3392c06d.png)

after sign in using o365 phone number, Street name missing.

Also login name using objectID not user UPN.

![image](https://user-images.githubusercontent.com/26478599/87145173-fac25700-c2b9-11ea-906e-43d08aa970c9.png)

thanks

**Comment by MrGeneration** [comment] 2020-07-10 10:36
Sorry but this is rather a technical question instead of a bug or issue.
If you require technical help, please consult the Zammad community: https://community.zammad.org


If you require commercial grade technical support, you can also have a look at Zammad support contracts: https://zammad.com/pricing#selfhosted


Closing now.

**Closed as completed by MrGeneration** 2020-07-10 10:36 UTC
Labels: question, missing issue template

**Comment by davkar3n** [comment] 2020-07-10 19:49
This is bug!!!

**Comment by thorsteneckel** [comment] 2020-07-13 09:47
Hi @IamAliBaba - this is actually a duplicate of #868 which includes the request to support `Custom attribute mapping`. You can subscribe to this issue to get updates as soon as we start working on this. As @MrGeneration already stated: If you require commercial grade technical support or want to prioritize issues, you can also have a look at Zammad support contracts: https://zammad.com/pricing#selfhosted

Background:
That's because all the different OAuth2 providers (like O365 in this case) provide different attributes (with different names/keys). We're currently limiting this to the attributes that are a) mandatory in Zammad and b) we are sure to be present:

https://github.com/zammad/zammad/blob/5c5c69a7858f63dea4e6a0dd089b8380bbb9d4f3/app/models/user.rb#L345-L376
