### ISSUE TITLE
Chat widget throwing errors on send

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#461] opened 2016-11-24 15:35 UTC
When user clicks send in the chat widget, the following error is thrown:
`Uncaught TypeError: this.el.find('.zammad-chat-message--typing').size is not a function(…)` (chat.js:706)
Inspecting the page, there is no element with the aforementioned class. 
The chat widget displays messages from the agent, and the agent can see the connection request from the widget...

**Comment by abenrob** [comment] 2016-11-29 08:01
Any thought on this?

**Comment by martini** [comment] 2016-11-30 21:55
Hi @abenrob 

I can't reproduce it. Do you have an example page where I can test/see this behaviour?

 -Martin

**Comment by abenrob** [comment] 2016-12-13 10:49
I will try to get  a version you can preview in place, but for now, we are just disabling chat... Once past our next deploy, I'll look into putting this in place.

**Comment by martini** [comment] 2016-12-13 11:18
Nice! I close the issue for now, just reopen on feedback.

**Closed by martini** 2016-12-13 11:18 UTC
Labels: bug

**Comment by kennethlarsen** [comment] 2017-01-19 10:55
@martini I have the exact same issue and I suspect it's related to jQuery versions. On Zammad.org it's suggested to use 2.1.4. Is this really true? I get this error on 3.1.1.

**Comment by thelfensdrfer** [comment] 2017-02-15 10:02
Could this be reopened until the chat works with the current version?
