### ISSUE TITLE
Emoticon formatting via email channel

### ISSUE THREAD

**Issue by sheLbyPL** [zammad/zammad#1912] opened 2018-04-03 08:22 UTC
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: mysql
* Elasticsearch version: 5.6.8
* Browser + version: latest chrome

### Expected behavior:

* When user replies/writes ticket by the email from Outlook (didn't test from other mail providers), emote :-) or :) which in outlook is automatically converted to 
![image](https://user-images.githubusercontent.com/7706996/38237788-62d2d588-3728-11e8-8199-061af117c6e7.png)
on the website it should show the same emoticon (I mean its original text version so :-) or :) )

### Actual behavior:

* Emoticon is replaced by "J" character.

![image](https://user-images.githubusercontent.com/7706996/38238004-dbcae5c0-3728-11e8-9528-b6b1230e821e.png)

### Steps to reproduce the behavior:

* Send email from outlook with mentioned emoticons

Yes I'm sure this is a bug (minor, but still :P) and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-04-03 08:47
As far as I know this is [an issue in Outlook](http://www.businessinsider.de/microsoft-outlook-fixes-j-smiley-emoticon-emoji-bug-2017-5?r=US&IR=T) that Microsoft fixed in some versions. The cause is that Outlook converts the smiley into the "Windings"-Font which is not available on all systems. This causes converters to convert the smiley to a J.
So please make sure the sender of the mail uses the latest version of Outlook. If so please provide a RAW email so we can have a look if it's a Zammad issue. Thanks!

**Closed by thorsteneckel** 2018-04-03 08:47 UTC
