### ISSUE TITLE
From address displays encoding

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#612] opened 2017-01-12 17:20 UTC
### Infos:

* Used Zammad version: 1.1.1 (deb)
* Operating system: ubuntu:16.04
* Browser + version: FF 50.1.0

### Expected behavior:

* Articles received via email channel should display From without encoding

### Actual behavior:

* This:
![grafik](https://cloud.githubusercontent.com/assets/4621219/21900175/2e7e01a2-d8f3-11e6-963a-e700a057626f.png)

### Steps to reproduce the behavior:

* Send sample email from PHP using SwiftMailer:
```
$message = new Swift_Message();
$message
    ->setFrom(array('foo@boo.com' => 'Hans Müller'))
    ->setTo('foo@boo.com')
    ->setSubject('test')
    ->setBody('test')
;
SwiftMailSend($message);

```

**Comment by olivergrahl** [comment] 2017-01-12 17:25
Here's a possible [fix](https://github.com/olivergrahl/zammad/commit/12b1c6812c62d696152319718b6444aae62a2334), which works in my fork:

![grafik](https://cloud.githubusercontent.com/assets/4621219/21900521/6c0be38a-d8f4-11e6-8b77-61fdf527642f.png)

**Comment by olivergrahl** [comment] 2017-01-12 17:27
Basically, `email_parser_test.rb` should have cought this, so I'm not 100% sure I understand what I'm doing here, but it seems to work... ;-)

**Comment by muhammadn** [comment] 2018-01-04 11:55
@olivergrahl this is caused by your email name having a UTF-8 character so the email server probably encoded your name with **ü** and send it out. 

Normal email clients (Microsoft Outlook or Gmail web) won't have this problem as it is automatically decoded but Zammad doesn't decode it automatically. (that is why your fix works) 😀

Will write tests to check on UTF-8 characters in email from: (and to:) fields and see if the bug still exists in the current Zammad.

**Comment by muhammadn** [comment] 2018-01-05 16:48
@olivergrahl I have run tests against the `develop` branch of our Zammad code and the tests show that the encoding display on ticket is correct (i tested with **Müller** name) when using raw emails with encoded text so this is already fixed on the latest `develop` branch.

**Closed** 2018-01-05 16:56 UTC
Labels: can't reproduce, wontfix

**Comment by muhammadn** [comment] 2018-01-06 10:29
@olivergrahl 

JFI, we don't do PHP but i had sent out the test emails using PHP, as closest to your example code to test it out:

```
<?php
require_once 'vendor/autoload.php';

$transport = (new Swift_SmtpTransport('smtp.server.org', 587))
  ->setUsername('account@server.com')
  ->setPassword('12345')
;

$mailer = new Swift_Mailer($transport);

$message = new Swift_Message();
$message
    ->setFrom(array('foo@boo.com' => Hans Müller'))
    ->setTo('receiver@domain.com')
    ->setSubject('newsletter #3')
    ->setBody('message you with newsletter3')
;

// send 5 emails
for ($i = 0; $i < 5; $i++){
  $result = $mailer->send($message);
  echo ($result == 1) ? "Successful\n" : "Failed!\n";
}
```
