### ISSUE TITLE
Prevent removing admin permission from Admin Role

### ISSUE THREAD

**Issue by pgassmann** [zammad/zammad#4003] opened 2022-03-08 21:15 UTC
### Infos:

* Used Zammad version: [5.0.3-45 (latest)](https://hub.docker.com/layers/zammad/zammad-docker-compose/zammad-postgresql-5.0.3-45/images/sha256-d3455c67388764729365a151ccf099f3ab7da85d48c35cb19eabae691483699e?context=explore) 
* Installation method (source, package, ..): docker-compose `zammad/zammad-docker-compose:zammad-latest` 
* Operating system: Ubuntu 20.04
* Database + version: zammad/zammad-docker-compose:zammad-postgresql-latest
* Elasticsearch version: image: zammad/zammad-docker-compose:zammad-elasticsearch-latest
* Browser + version: Firefox 97

### Expected behavior:

* Admin Permission cannot be removed from Admin role

### Actual behavior:

* Admin role can be edited, checkbox for admin permission can be removed.
* Admin accidentially removed the permission

### Steps to reproduce the behavior:

* Go to Roles
* Edit Admin Role
* Remove admin Permission
* Submit
* Reload Page
* You are locked out from admin Settings.
![image](https://user-images.githubusercontent.com/460192/157325810-2d794025-74f7-4dff-a741-3711103254f9.png)

Yes I'm sure this is a bug and no feature request or a general question. There are related Admin lockout prevention bugs that were fixed:
* #1501
* #1563

### Workaround: Fix permission on the console

In case you accidentally removed the admin permission, you can readd the permission in the Rails console. 

in `rails c` (docker-compose: `docker-compose exec zammad-railsserver rails c`)

```
pp admin_role = Role.where(name: ['Admin']).first
pp admin_role.permissions
admin_role.permission_grant('admin')
```

**Comment by rolfschmidt** [comment] 2022-03-21 10:35
We have a check which makes it mandatory to have at least one admin in the system which does also show up in this case here:

![grafik](https://user-images.githubusercontent.com/5445062/159243608-4603f14a-b758-4650-8053-ad629785a7d4.png)

Atm you can kick yourself out if there are other admins in other roles and you unassign the admin role which is assigned to yourself (not very pretty though could improved as well).

@martini , @MrGeneration any ideas ? Should we disable to unassign admin roles which are matching to the current session user or is it enough protection?

**Comment by pgassmann** [comment] 2022-03-21 13:36
@rolfschmidt indeed, there is a lockout prevention in the permissions management. As it was not me editing the roles, I cannot tell any more what the exact situation was at that time and who would have had Admin permissions.

If it is not straightforward to prevent self-lockout I would not invest too much effort in this additional safety. There is still the option of the Console for such edge cases, which is now documented with this issue.

**Comment by MrGeneration** [comment] 2022-03-24 16:28
I believe it's difficult on a role level to implement a proper fix.
I'd argument that a administrator usually™️ should know what he's doing when he degrades a role.

However, I also understand that, especially on big installations, this may sometimes be difficult due to complexity.
Maybe the classic "Are you sure that you're sure?" approach might help.

As per:
When an administrator is removing admin permissions on a role level that matches his own permission set and thus would mean a permission degration we may want to warn before submitting.

As this seems to be working as designed right now, this technically is a enhancement request.
If we decide to not close it down at this point this is a PM decision to be made if core or not.

**Comment by YetAnotherGerrit** [comment] 2024-10-16 11:38
The role can also be renamed, other admin roles can/could be created. I don't see a benefit in adding a check "do not remove admin permission from a role called 'admin'", as there are use cases where you might want to limit this to system administrative permissions only.

I think the check mentioned by rolf is more than suitable. If someone runs into this issue anyway there is a great solution on the rails console available. Thank you for documenting it in this issue @pgassmann .

**Closed as not planned by YetAnotherGerrit** 2024-10-16 11:38 UTC
Labels: enhancement, admin area, verified
