### ISSUE TITLE
Autocomplete hangs on dot in the new user form

### ISSUE THREAD

**Issue by Newan** [zammad/zammad#2058] opened 2018-06-07 09:03 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): deb
* Operating system: Ubuntu 16.04
* Database + version: postgres
* Elasticsearch version: n/a
* Browser + version: chrome

### Expected behavior:

* Find organisations with dot in the name, on the "new user" form

### Actual behavior:

* if an organization has a dot in the name, the autocomplete doesn't find it, if the dot is entered

### Steps to reproduce the behavior:

- create an organization like "T.E.S.T Test, TestStandort"
 - go into the form from new user
 - search for "T", and the organization is hwoing:
![image](https://user-images.githubusercontent.com/3693094/41089361-f16e495c-6a41-11e8-8975-a9246739e021.png)
- type the dot in the field like:
![image](https://user-images.githubusercontent.com/3693094/41089402-04507dec-6a42-11e8-93c4-bb5a2be08839.png)
- no search result!

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SummerStorm** [comment] 2018-06-07 09:38
~~Hi there, thanks for the bug report. This issue has been fixed in~~ [2.6.0](https://github.com/zammad/zammad/releases/tag/2.6.0). 

~~Here's how it looks in 2.6.0 (search is now case-insensitive too):~~

![screenshot from 2018-06-07 17-28-41](https://user-images.githubusercontent.com/7030950/41091545-5cb8987a-6a79-11e8-8c69-e075d250bae3.png)

EDIT: Sorry, my bad. With Elasticsearch on I can reproduce this. I accidentally had Elasticsearch off.

**Comment by hanneshal** [comment] 2018-06-08 11:52
Note: will be fixed in 2.6.0
2.5. is the current stable release

**Comment by thorsteneckel** [comment] 2018-06-08 14:03
Since we released 2.5 only a few days ago I don't see the commit which fixes this. Can somebody link it here so we have a reference. After we have it the issue can be closed.

**Comment by SummerStorm** [comment] 2018-06-09 01:15
@thorsteneckel Sorry, my mistake. I had elasticsearch turned off in my instance, and this bug doesn't happen without elasticsearch. I forgot that the search behavior is different depending on whether elasticsearch is enabled or not.

**Comment by thorsteneckel** [comment] 2018-06-11 07:35
No worries - thanks for clarification @SummerStorm! So I think this is an issue with the general setup as you described and no bug. @Newan please verify that this affects the latest version of Zammad with all processes running and let us know if the issue still persists. In general of technical questions feel free to use our [community board](http://community.zammad.org/). I'm closing this issue now.

**Comment by Newan** [comment] 2018-06-11 07:44
I thin it is all running:


```
root@ticket01:/# systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-06-07 10:25:37 CEST; 3 days ago
     Docs: http://www.elastic.co
 Main PID: 4891 (java)
    Tasks: 46 (limit: 4915)
   CGroup: /system.slice/elasticsearch.service
           └─4891 /usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

root@ticket01:/# systemctl status zammad
● zammad.service
   Loaded: loaded (/etc/systemd/system/zammad.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-06-07 10:28:36 CEST; 3 days ago
 Main PID: 5116 (sleep)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/zammad.service
           └─5116 /bin/sleep infinity

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
root@ticket01:/#
```
Is there any zammad console function get this infos?

**Comment by thorsteneckel** [comment] 2018-06-11 07:51
Hi @Newan as stated in my previous comment we can't reproduce this issue in our instances and this has to be an issue on your side. You can either ask in the [community board](http://community.zammad.org/) or make use of our commercial service of https://zammad.com/ . Not usual as with proprietary software, we finance Zammad through service. So it's less money we have at our disposal to push Zammad. This means that working on single technical questions only minimizes the available resources and lowers the speed of implementation. Thanks for your understanding!

**Comment by Newan** [comment] 2018-06-11 07:55
I understand that, especially with the few resources. That's why I just tried to help.

which I do not understand:
> With Elasticsearch on I can reproduce this.
vs 
> can't reproduce this issue in our instances

i make an technical question in the board

**Comment by Newan** [comment] 2018-06-12 09:24
so i found it and i think that is an bug or misconfigure in zammad or Elasticsearch ist.

I **disable** Elasticsearch all runs fine. But then i have no Elasticsearch features

I searched with Elasticsearch on console and i see the problem. It is then the query ends with an dot and no wildcard is setting:

```
curl -XGET 'http://127.0.0.1:9200/zammad_production/Organization/_search?q=T.E.&pretty=true'
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

```
if i set an wildcard like this post:
https://stackoverflow.com/questions/29083366/elasticsearch-query-string-with-dot-point-at-the-end-i-e-foo

```
 curl -XGET 'http://127.0.0.1:9200/zammad_production/Organization/_search?q=T.E.*&pretty=true&analyze_wildcard=true'
{
  "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "zammad_production",
        "_type" : "Organization",
        "_id" : "514",
        "_score" : 1.0,
        "_source" : {
          "shared" : false,
          "note" : "",
          "customernr" : null,
          "domain_assignment" : false,
          "active" : true,
          "created_at" : "2018-06-07T08:51:50.093Z",
          "software_ansp_1" : null,
          "updated_at" : "2018-06-07T08:51:50.093Z",
          "domain" : "",
          "members" : [ ],
          "name" : "T.E.S.T Test, TestStandort",
          "updated_by_id" : 3,
          "id" : 514,
          "created_by_id" : 3
        }
      }
    ]
  }
}
```
or if the query has no dot like:

`curl -XGET 'http://127.0.0.1:9200/zammad_production/Organization/_search?q=TEST&pretty=true'`

ervery works fine too

**Comment by Newan** [comment] 2018-06-15 07:38
https://newan2.zammad.com

 same in your online instance !!

**Comment by thorsteneckel** [comment] 2018-06-15 08:19
You are right. I can confirm this. Organization name is `T.E.S.T TestOrga, Teststandort`. Going to Admin -> User and try to assign the Organization causes the following:

![org_select_bug](https://user-images.githubusercontent.com/3873515/41457811-28a90ba2-7085-11e8-84d2-bdb65c6978a9.gif)

The AJAX call to the backend is performed but doesn't return a value (as described in the previous comment).

This is a bug in the Elasticsearch integration and might be related to an issue with `::` in ObjectManager Attributes which can't be found either. Do you think this is the case @martini ?

**Closed as completed** 2018-07-03 07:24 UTC
Labels: bug, search, verified

**Comment by SummerStorm** [comment] 2018-10-12 14:54
Please note that starting with Zammad 2.7 the search behaviour will change slightly:

1. Any search query containing a `:` character will be considered a complex query and no wildcards will be appended at the end. Searching for `number:10` will only find tickets with that exact ticket number. `number:10*` will find tickets starting with 10.

2. Search queries without `:` will have the `*` wildcard appended at the end. Searching for `10` will yield all tickets starting with 10.
