### ISSUE TITLE
Exchange tokens are still updated with inactive exchange integration

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#5186] opened 2024-05-23 10:10 UTC
### Used Zammad Version

6.3.x.67d518eab.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

The scheduler task "Update exchange oauth 2 token." runs even with an exchange integration set to inactive. This causes monitoring errors as soon as the token configuration in question is no longer valid and throws permanent ugly errors in the moniroing:

Failed to run scheduled job 'Update exchange oauth 2 token.'. Cause: Failed to run ExternalCredential::Exchange.refresh_token after 11 tries.

This issue also causes the scheduler task to be set to inactive.

### Expected behaviour

When setting the exchange integration to inactive, configured exchange online tokens will no longer be refreshed in the background.

### Steps to reproduce the behaviour

- configure the exchange integration with exchange online
- set the integration to inactive after you verified its function
- revoke the token
- wait up to 15 minutes and check your monitoring incidents

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2024-05-29 08:18
Duplicate of https://github.com/zammad/zammad/issues/4961.

**Closed as not planned by fliebe92** 2024-05-29 08:18 UTC
Labels: duplicate
