### ISSUE TITLE
Zammad using remote ES stops local ES during update

### ISSUE THREAD

**Issue by JakubJachym** [zammad/zammad#2811] opened 2019-11-19 11:29 UTC
### Infos:

* Used Zammad version: 3.1.0-1574099652
* Installation method (source, package, ..): apt package
* Operating system: Ubuntu 18.04.3 LTS
* Database + version: Postgres 10.10
* Elasticsearch version: 5.6.0
* Browser + version: N/A

### Expected behavior:

* Using ES installed on remote server and performing update of Zammad, the update script should NOT disable local elasticsearch instance.

### Actual behavior:

* Zammad update script actually disables local ES instance breaking another services using the ES (specifically Graylog server in my case).

### Steps to reproduce the behavior:

* Install ES on local and remote machine and make sure they are running
* Install Zammad and configure it to use remote ES
* Update Zammad 
* It should display following message:
```
[...]
It seems you're running an external Elasticsearch server on [REMOTE_IP_ADDRESS:PORT]
Stopping local elasticsearch server...
```
* Check local ES instance if it is running.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-11-19 11:42
Sorry, but I believe that this is a mixture of enhancement request, existing issue (duplicate) and technical question (technical questions should live at the Community: https://community.zammad.org).


Just to sort it right before simply closing this issue:
* You're running a local graylog instance beside Zammad which uses the local ES
* You're running a second elasticsearch for Zammad on another node which is only used by Zammad

Did I get the above correct?
Most important questions then would be... why...? :o

Beside that - elasticsearch currently is a mandatory package, which is why our scripts to handle stuff around elasticsearch (mainly the attachment plugin). The past has shown that we need to handle the plugins upon updates, because many users forget to ensure to update their plugins if there was an elasticsearch update. Thus this is for convinience.

However, I agree that we should enhance the script to simply ignore the local elasticsearch server if it's detected as external. As this -to many parts- is a duplicate of this: https://github.com/zammad/zammad/issues/2400 I will later on close this issue for the favor of the other issue.

I will extend the existing issue to also hold your enhancement idea, because I think it's useful.

**Comment by JakubJachym** [comment] 2019-11-19 11:50
Hey!

I was using local ES for both Zammad and Graylog. A year ago (or so) I had to upgrade ES to 6.7, which was (at the time) not supported by Zammad. So I had to spin off another ES instance with legacy 5.x version on another server. So because of the incompatibility I had to use two ESs, one for Graylog, one for Zammad.

The issue is, that updating Zammad kills local ES instance which is not used by Zammad in any means. I thought it is a bug, as it shouldn't touch local ES instance when it is configured to use remote instance. :-)

(Btw. just checked the documentation and saw Zammad currently supports ES 6.x too, so performing migration as we speak. So this issue won't probably bother me anymore, but perhaps someone else can have the same setup and issue?)

**Comment by MrGeneration** [comment] 2019-11-19 11:55
I guess we suspect you to use Zammad as only application on the system.
Any way, understood your use case. :-)

Gladly you can migrate back to your local ES and even save ressources!
You might want to stick to `http://127.0.0.1:9200` at the moment, because of the above mentioned issue.

As I said, I like your approach and thus will update the other issue to hold your enhancement idea as well.

Thanks for your time!

**Closed as completed by MrGeneration** 2019-11-19 11:55 UTC
Labels: duplicate, question
