### ISSUE TITLE
Triggers for Internal/External & Customer/Agent/System not working

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1543] opened 2017-10-18 12:04 UTC
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

1. Trigger Visibility>External should trigger for all non-internal articles
2. Trigger Visibility>Internal should trigger for all non-external articles
3. Trigger Sender>Customer should trigger for all articles created by customer
4. Trigger Sender>Agent should trigger for all articles created by Agent
5. Trigger Sender>System should trigger for all articles created by System (mail notification comment)

### Actual behavior:

1. working as expected
2. gets triggered for external articles but not for internal ones
3. working for all articles created by customer; but also for mail notification comment automatically created by system when customer created article
4. working for all articles created by agent; but also for mail notification comment automatically created by system when agent created article
5. gets never triggered

### Steps to reproduce the behavior:

2. create trigger with condition "Visibility>Internal" and action "Mail" and create internal and external 
always articles 
3. create 2 triggers both with condition "Sender>Customer", action "Mail", subjects "Test1" & "Test2" and mail content "#{article.subject} and create an article with content "123" as customer; received mails will have 1) subject "RE: Test ..." and content empty and 2) subject "RE: Test2 ..." and content "Test"; meaning 2) was triggered because of 1) being triggered
4. create 2 triggers both with condition "Sender>Agent", action "Mail", subjects "Test1" & "Test2" and mail content "#{article.subject} and create an article with content "123" as agent; received mails will have 1) subject "RE: Test ..." and content empty and 2) subject "RE: Test2 ..." and content "Test"; meaning 2) was triggered because of 1) being triggered
5. create 2 triggers, 1 with condition "Sender>Agent" & 1 with condition "Sender>System", action "Mail" and create an article as agent; you will just receive mail generated by trigger 1); meaning mail notification comment is not created by system but by agent

--> Problem for 3.-5. is that mail notification comments get created by the user who created the correspoding article and not by system and this is why you're unable to determine whether trigger runs because of created article or because of created mail notification comment by another trigger

BTW: If 2 triggers have the same conditions, they should always be triggered always both, shouldn't they? Why is trigger 1) triggered by article creation and trigger 2) by notification of trigger 1)?

**Comment by martini** [comment] 2017-10-18 13:51
Just as additional info:

Currently triggers get only executed once. So if a trigger would trigger an other trigger rule it's not working right now (because of endless loop).

Affected is:

> 5. Trigger Sender>System should trigger for all articles created by System (mail notification comment)

**Comment by thorsteneckel** [comment] 2018-05-17 08:02
Hi @rlue - can you please have a look at this? Except of point 5 because @martini is currently working on this for a paying customer (as discussed yesterday).

**Comment by rlue** [comment] 2018-05-23 10:48
@Kartoiser, I can't reproduce your second bullet point (failure of trigger for Visibility: Internal) on the stable branch of Zammad. See [this screencast](https://www.youtube.com/watch?v=XTEtDb-WM-o) for a demonstration.

It may be possible that the bug was fixed between Zammad v2.1 and current stable branch. If you continue to encounter this issue, please consider upgrading. If upgrading does not fix it, please provide additional information to help us reproduce the problem.

The problem causing points 3 and 4 have been identified, and a fix is in the works.

**Comment by rlue** [comment] 2018-05-24 00:46
> BTW: If 2 triggers have the same conditions, they should always be triggered always both, shouldn't they? Why is trigger 1) triggered by article creation and trigger 2) by notification of trigger 1)?

To clarify: that's not quite what's happening. The second email notification trigger isn't firing _because of_ the first one; in fact, both are correctly firing for the original condition (_e.g.,_ new customer article). Internally, however, the `article` variable in `#{article.subject}` was [set to point to the wrong value](https://github.com/zammad/zammad/blob/develop/app/models/ticket.rb#L989).

**Comment by rlue** [comment] 2018-05-25 01:02
### Summary

1. Not a bug
2. Not reproducible
3. Fixed by 5dd699c
4. Fixed by 5dd699c
5. To be addressed in a separate issue.

**Closed by rlue** 2018-05-25 01:02 UTC
Labels: bug, needs verification
