### ISSUE TITLE
Linking Knowledgebase answers within Ticket impossible

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2718] opened 2019-08-23 14:24 UTC
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: latest Google Chrome, latest Firefox
* This bug has originally found by the user `bendergruppe` on the Community: https://community.zammad.org/t/find-knowledge-base-entry-from-ticket/2973

### Expected behavior:

When linking an KB-Answer to a ticket (from ticket to answer), you can search for your answer and then simply link it.

### Actual behavior:

When linking an KB-Answer to a ticket (from ticket to answer), the UI does not provide a selection for found answers. Logfile and developer console clearly show that there have been results, they "simply" don't show up within the UI.

### Steps to reproduce the behavior:

* create an knowledgebase answer
* ensure your searchindex is up to date
* go to any ticket (if none is available, create one)
* now try to link an answer to the ticket, by searching for a word that appears within the KB-Answer

### Screencast:
![adding-related-answers-impossible](https://user-images.githubusercontent.com/6549061/63599658-514f7580-c5c2-11e9-81f1-b0a5dc9ebcd2.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by nublaii** [comment] 2019-09-03 08:49
Same here, noticed it even before upgrading to version 3.1

**Comment by thorsteneckel** [comment] 2019-10-30 07:50
This was fixed via #2789 which is actually a duplicate of this issue here. Anyhow, therefore I'll close this issue here as well.

**Closed as completed by thorsteneckel** 2019-10-30 07:50 UTC
Labels: duplicate
