### ISSUE TITLE
Datepicker in bulk action not usable in bulk action if ticket list is longer the one page.

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2274] opened 2018-10-09 04:28 UTC
### Infos:

* Used Zammad version: develop
* Installation method (source, package, ..): git
* Operating system: CentOS7 
* Database + version: PostgreSQL 9.5
* Elasticsearch version: n.a.
* Browser + version: Firefox 62 macOS

### Expected behavior:

* Selecting a date

### Actual behavior:

* Date can't be selected

### Steps to reproduce the behavior:

* Choose an overview where the ticket list needs to be scrolled
* Select at least two tickets
* Scroll to the top of the overview
* Choose pending state
* Try to choose a date

![image](https://user-images.githubusercontent.com/378324/46646835-cbcefc80-cb8c-11e8-9af8-150c9c08984c.png)

Scrolling to the end of the overview still made the date picker usable.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2018-10-09 06:52
Duplicate of #2208
Mantas couldn't reproduce this on develop which is why we closed it. I had my trouble reproducing this too

**Comment by thorsteneckel** [comment] 2018-10-09 07:01
The issue occurred to me yesterday, too. However, knowing how to reproduce this is crucial for us to be able to fix it.

**Comment by mantas** [comment] 2018-10-09 07:07
@thorsteneckel on stable or develop? IIRC, @MrGeneration and I could replicate it on stable, but not on develop.

**Comment by thorsteneckel** [comment] 2018-10-09 07:09
`stable`! Let's close this. Please check `develop` or wait for `2.7` (which will be released soon) everbody. Thanks @mantas !

**Comment by thorsteneckel** [comment] 2018-10-09 07:34
Thanks to @rkaldung I was able to reproduce this. As described in the initial post it's mandatory to have a list of Tickets that is scrollable. Attention: There have to be at least 6 Tickets that are not in the visible area! Then make sure that the page is scrolled up to the top and select the top most two Tickets. Afterwards select the pending state in the bulk action menu and click into the date field. Notice the buggy behavior described earlier.

**Comment by mantas** [comment] 2018-10-09 07:39
@thorsteneckel you're correct. There has to be 6 under-the-fold tickets rather than 6 tickets in total as I was testing before.

I can look into this to get some fresh air from KB ;)

**Comment by martini** [comment] 2019-11-20 14:55
Note to reproduce it: It will only happen if ticket list is longer as one page.

**Closed as completed by martini** 2019-11-20 14:55 UTC
Labels: bug, overviews, verified, frontend

**Comment by rkaldung** [comment] 2019-11-20 15:05
What? Not reproducible?

**Comment by martini** [comment] 2019-11-20 15:06
> What? Not reproducable?

Was just a typo, it's already corrected.

-> Not**e** to reproduce it: It will only happen if ticket list is longer as one page.
