### ISSUE TITLE
String of email translation is missing 

### ISSUE THREAD

**Issue by Newan** [zammad/zammad#2163] opened 2018-08-02 10:52 UTC
### Infos:

* Used Zammad version: 2,5
* Installation method (source, package, ..): deb
* Operating system: ubuntu 16.04
* Database + version: postgres
* Elasticsearch version: n/a
* Browser + version: chrome

### Expected behavior:

* i cannot tranlate the string "You are receiving this because you "are in group" " to german over the tranlsation setting in the backend
 application.html.erb:
<% reason = t('You are receiving this because you "%s".') %>

### Actual behavior:

* the string "You are receiving this because you" and the reasons are not in the translation sektor of the backend

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-08-02 11:54
This is a (technical) duplicate of #2056. Closing now.

**Closed as completed by thorsteneckel** 2018-08-02 11:54 UTC
Labels: duplicate

**Comment by raid1** [comment] 2021-11-19 21:30
Even if it sounds like a technical duplicate, the mentioned workaround does not work for this.
Maybe because the string does not appear in the web ui but only in an email?

Please have another look at this. The footer of German emails is looking pretty awkward:

>> **You are receiving this because you "are in group". | Benachrichtigungseinstellungen verwalten**

**Comment by MrGeneration** [comment] 2021-11-19 21:33
It's a duplicate, no need to re-check.

**Comment by raid1** [comment] 2021-11-19 21:35
No. The string does not appear in the list of translations.

**Comment by MrGeneration** [comment] 2021-11-19 21:37
I'm locking this issue now as it has no use discussing it with you.
If you don't believe me or have a different opinion, feel free to share it in the community but not here please.
