### ISSUE TITLE
URLs destroyed by incorrect URL Encoding when sending Emails

### ISSUE THREAD

**Issue by MacLemon** [zammad/zammad#2283] opened 2018-10-11 17:16 UTC
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): Source
* Operating system: FreeBSD 11.2-p3
* Database + version: PostGreSQL 10.5
* Elasticsearch version: n/a
* Browser + version: Chromium 71.0.3557.0, Firefox 62.0.2 (Bug is browser agnostic)

### Expected behavior:

Links parts in emails should not get incorrectly encoded thereby keeping links in good order.

### Actual behavior:

URLs that contain a `+` character get mangled by Zammad, making them incorrect.
For example this URL `https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/` get's mangled in the way that the `+`characters get URL Encoded as `%20`. This is incorrect in multiple ways. `+` is ASCII Character `2b`and `+`must not be encoded in a URL at all.
Sadly this breaks the Link in the HTML Mime Part which looks like this:
```
<a href=3D"https://pads.c3w.at/pad/#/2/pad/edit/C%20ZhlACE9=
UTVE7v%20KxkEpHnk/" title=3D"https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlAC=
E9UTVE7v+KxkEpHnk/" rel=3D"nofollow noreferrer noopener" target=3D"_blank=
">https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/</a>
```
Where the `+` becomes `%20` in the `href` parameter breaking the URL. The text part of the anchor stays correct though.

The `text/plain` MIME part is also affected.
```

A link to a Rich-Text PAD:=0D
=0D
[1] https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/=0D
=0D

[1] https://pads.c3w.at/pad/#/2/pad/edit/C%20ZhlACE9UTVE7v%20KxkEpHnk/=0D=
```
where the resulting Markdown like text, also contains the text part correctly with `+` but the link reference in `[1]` shows the incorrect `%20` URL encoding.

### Steps to reproduce the behavior:

1. Create a new test ticket for Email
2. Add a link with a `+` in it, for example: `https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/`
3. Send email
4. Check email in your favourite mail user agent and check the links. MUAs that display HTML will have a clickable link that doesn't work because it has been altered.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2018-10-11 18:01
I cannot entirely verify this. i can only verify this within the Zammad-WebApp itself. My two favorite Mail-Agents (Roundcube and Thunderbird) don't care.

```
----==_mimepart_5bbf8d34cf1e2_7b87450a9c0566e5
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

[1] https://smrg.de/+/s

Marcel Herrguth

--
Zammad GmbH
--

[1] https://smrg.de/+/s
```

```
[...]
</head>
  <body style="font-family:'Helvetica Neue', Helvetica, Arial, Geneva, sans-serif; font-size: 12px;"><div><a href="https://smrg.de/+/s" rel="nofollow noreferrer noopener" target="_blank">https://smrg.de/+/s</a>
</div><div><br></div><div><br></div><div data-signature="true" data-signature-id="1">
  Marcel Herrguth<br>
<br>
--<br>
 Zammad GmbH<br>
--</div></body>
</html>
```

The same happens to your sample content btw:
```
----==_mimepart_5bbf8d8d827d5_7b87450a9c05698
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

[1] https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/

Marcel Herrguth

--
Zammad GmbH
--

[1] https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/
```

```
<body style="font-family:'Helvetica Neue', Helvetica, Arial, Geneva, sans-serif; font-size: 12px;"><span><a href="https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/" rel="nofollow noreferrer noopener" target="_blank">https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/</a></span>
<br><br><div data-signature="true" data-signature-id="1">
  Marcel Herrguth<br>
<br>
```


The only difference is the Zammad Webapp. Can you please verify this with a current Zammad-Application? (2.6.x)


![image](https://user-images.githubusercontent.com/6549061/46824241-8713b300-cd90-11e8-9de4-eb76ed82eefd.png)

**Comment by MacLemon** [comment] 2018-12-03 16:01
Reopening:
The problem still exists in 2.6 and 2.7. (Haven't yet updated to 2.8.)

**Comment by MrGeneration** [comment] 2018-12-04 10:25
Can you please verify this on an hosted instance? ( https://zammad.com/getting-started )

Also, plese take a look at my remarks, as we can't entirely reproduce this.

**Comment by MacLemon** [comment] 2018-12-04 19:46
As per your remarks: Do your favourite Email Clients, display the HTML MIME Part of the messages sent out by Zammad? The problem only exists in the HTML part in the <a> tag itself, but not in the Text/Plain MIME part.
Also I really don't see any reason why our self-hosted instance should generate any different emails than your hosted ones (unless you're running a patched version).

Just for completeness: I've tried this with the hosted instance and it shows *exactly* the same behaviour on the first try.

I guess you can access your Demo instances, so here's the link:
https://issue2283.zammad.com/#ticket/zoom/2

Here's the Email generated:
```
Subject: RE: Testing Issue 2283 [Ticket#98002]
Mime-Version: 1.0
Content-Type: multipart/mixed;
 boundary="--==_mimepart_5c06d809d206e_165d3d54f50522bb";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Organization: MacLemon
X-Powered-By: Zammad - Helpdesk/Support (https://zammad.org/)
X-Mailer: Zammad Mail Service

----==_mimepart_5c06d809d206e_165d3d54f50522bb
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5c06d809d1cc9_165d3d54f505201d";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_5c06d809d1cc9_165d3d54f505201d
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Outgoing Link

[1] https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/

> On Tuesday, December 4, 2018, 8:38:31 PM, MacLemon wrote:
>
> Incoming:
> [2] https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/

[1] https://pads.c3w.at/pad/#/2/pad/edit/C%20ZhlACE9UTVE7v%20KxkEpHnk/
[2] https://pads.c3w.at/pad/#/2/pad/edit/C%20ZhlACE9UTVE7v%20KxkEpHnk/
----==_mimepart_5c06d809d1cc9_165d3d54f505201d
Content-Type: multipart/related;
 boundary="--==_mimepart_5c06d809d1ddd_165d3d54f5052184";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_5c06d809d1ddd_165d3d54f5052184
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <style type="text/css">
      body {
        font-family:'Helvetica Neue', Helvetica, Arial, Geneva, sans-serif; font-size: 12px;;
      }
      img {
        outline: none;
        text-decoration: none;
        -ms-interpolation-mode: bicubic;
      }
      a img {
        border: none;
      }
      table td {
        border-collapse: collapse;
      }
      table {
        border-collapse: collapse;
        mso-table-lspace: 0pt;
        mso-table-rspace: 0pt;
        border: none;
        table-layout: auto;
        display: block;
        width: 100%;
        overflow: auto;
        word-break: keep-all;
      }
      table,
      pre,
      blockquote {
        margin: 0 0 16px;
      }
      td, th {
        padding: 7px 12px;
        border: 1px solid hsl(0,0%,87%);
      }
      th {
        font-weight: bold;
        text-align: center;
      }
      tbody tr:nth-child(even) {
        background: hsl(0,0%,97%);
      }
      col {
        width: auto;
      }
      p {
        margin: 0;
      }
      code {
        border: none;
        background: hsl(0,0%,97%);
        white-space: pre-wrap;
      }
      blockquote {
        padding: 8px 12px;
        border-left: 5px solid #eee;
      }
      pre {
        padding: 12px 15px;
        font-size: 13px;
        line-height: 1.45;
        background: hsl(0,0%,97%);
        white-space: pre-wrap;
        border-radius: 3px;
        border: none;
        overflow: auto;
      }
    </style>
  </head>
  <body style="font-family:'Helvetica Neue', Helvetica, Arial, Geneva, sans-serif; font-size: 12px;"><div>Outgoing Link</div><div><br></div><div>
<div><a href="https://pads.c3w.at/pad/#/2/pad/edit/C%20ZhlACE9UTVE7v%20KxkEpHnk/" rel="nofollow noreferrer noopener" target="_blank">https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/</a></div>
<br>
</div><div><blockquote type="cite" style="border-left: 2px solid blue; margin: 0 0 16px; padding: 8px 12px 8px 12px;">On Tuesday, December 4, 2018, 8:38:31 PM, MacLemon wrote:<br><br><div>Incoming:</div>
<div><a href="https://pads.c3w.at/pad/#/2/pad/edit/C%20ZhlACE9UTVE7v%20KxkEpHnk/" rel="nofollow noreferrer noopener" target="_blank">https://pads.c3w.at/pad/#/2/pad/edit/C+ZhlACE9UTVE7v+KxkEpHnk/</a></div>
<br>
</blockquote></div><div><br></div></body>
</html>
----==_mimepart_5c06d809d1ddd_165d3d54f5052184--

----==_mimepart_5c06d809d1cc9_165d3d54f505201d--

----==_mimepart_5c06d809d206e_165d3d54f50522bb--
```

In the outgoing Email even quoted Links that contain a `+` character do get mangled in the HTML part.

**Comment by MrGeneration** [comment] 2018-12-13 17:48
Thanks for testing, I could verify this!

**Comment by martini** [comment] 2020-07-21 06:24
I have good news. This is a duplicate of https://github.com/zammad/zammad/issues/2494 which is already fixed in stable branch. Just update Zammad to current stable.

Feedback is welcome, as always.

**Closed as completed by martini** 2020-07-21 06:24 UTC
Labels: duplicate
