### ISSUE TITLE
New Ticket object (text) leads to old tickets always showing that "changes" have been made.

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2288] opened 2018-10-17 09:08 UTC
### Infos:

* Used Zammad version: 2.6.x 
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: latest
* Elasticsearch version: latest
* Browser + version: Firefox

### Expected behavior:

* When adding new text objects to tickets through Admin->Objects->Ticket all old and new tickets should update without detecting a "change" for each ticket.

### Actual behavior:

* When the new text field is added, old tickets will show that they have been edited if you open one. It will show "Discard Changes" even though the agent did not change anything actively. Discard changes will also not do anything. If you leave the ticket page by closing it from the "recently open tickets" tab (the one in the picture) it will also ask if you want to discard changes or cancel the page leave:
![image](https://user-images.githubusercontent.com/44224243/47075221-64542500-d1fc-11e8-8592-13561e9ead49.png)

### Steps to reproduce the behavior:

* Create new Ticket Object while having already created tickets.
Default text can be anything or empty.
Access only to Agents.

Our current workaround is to go to the old already open tickets and press "Update" once so the Default string gets saved to the ticket data. This is however very tideous if you already have many tickets open and want to add a Ticket Object for your Agents at a later point.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-10-17 09:11
Hi @SEGGER-NV - thanks a lot for your comprehensive report! However, it is a duplicate of #2042 and we're already working on a fix 💪 Closing now.

**Closed as completed by thorsteneckel** 2018-10-17 09:11 UTC
Labels: duplicate
