### ISSUE TITLE
Agent ticket overview broken

### ISSUE THREAD

**Issue by skibson** [zammad/zammad#789] opened 2017-02-20 09:16 UTC
### Infos:

* Used Zammad version:  1.3.0
* Operating system: Ubuntu Server 16.04
* Browser + version: any

### Expected behavior:

* Overview My Tickets actually showing tickets where I'm chosen as a customer

### Actual behavior:

* Overview My Tickets does not show anything at all

### Steps to reproduce the behavior:

* For testing purposes I created testing installation of zammad. I created two groups (g1 and g2) and two users (u1 and u2) with role agent.

u1 belongs to g1
u2 belongs to g2 

simple

Now u1 wants to submit an issue for u2 to solve.

On ticket submitting screen user u1 chooses himself as ticket customer, group g2 and user u2.
(Remaining field are not important so filling them with random text)

I had an issue here with u1 not seeing ticket content but solved this by modifying app/models/ticket/permission.rb to look like this:
```
# Copyright (C) 2012-2016 Zammad Foundation, http://zammad-foundation.org/
module Ticket::Permission

=begin

check if user has access to ticket

  ticket = Ticket.find(123)
  result = ticket.permission(current_user: User.find(123))

returns

  result = true|false

=end

  def permission(data)

    # check customer
    if data[:current_user].permissions?('ticket.customer')

      # access ok if its own ticket
      return true if customer_id == data[:current_user].id

      # access ok if its organization ticket
      if data[:current_user].organization_id && organization_id
        return true if organization_id == data[:current_user].organization_id
      end

      # no access
      return false
    end

    # check agent
if data[:current_user].permissions?('ticket.agent')
    # access if requestor is owner
    return true if customer_id == data[:current_user].id
    return true if owner_id == data[:current_user].id

    # access if requestor is in group
    data[:current_user].groups.each { |group|
      return true if self.group.id == group.id
    }
    false
    end
  end
end
```

Now, when choosing My Tickets from dashboard, the list is empty and no tickets are displayed here, but in admin overview editing menu you choose to edit My Tickets overview there are all wanted tickets in overview.

But after changing u1 role to customer, wanted overview shows tickets correctly

**Comment by skibson** [comment] 2017-02-20 16:16
#792 solved by me

**Comment by thorsteneckel** [comment] 2018-01-25 17:15
Hi @skibson - We made a lot of changes and fixes for the overviews. Please check your case again in the latest `develop` version or in 2.3 which will be released soon and reopen if required. Thanks!

**Closed by thorsteneckel** 2018-01-25 17:15 UTC
Labels: bug, needs verification, overviews

**Comment by moellert** [comment] 2018-02-23 10:25
Hey @thorsteneckel - I hope it's okay when I answer this, because I got the same struggle. 
-> This doesn't work in 2.3.

In the Edit: Overview window it is shown right,
![edit](https://user-images.githubusercontent.com/30858921/36589166-b2de7878-188a-11e8-937a-ca8ad30dce12.png)

but the tickets are not displayed when I visit the overview.

![my tickets](https://user-images.githubusercontent.com/30858921/36589175-bd98ba30-188a-11e8-85a6-61f8eee1755c.png)

I am just able to see the tickets where I am the Customer when I have the Overview right for the group.
Furthermore I am not able too read the ticket unless I have the read right for the group and the same with updating or answering in this ticket without the change right.

Even if it's a workaround, you don't want to give every agents the rights to see/edit every ticket in every group

**Comment by muhammadn** [comment] 2018-02-23 10:34
@moellert Is the problem you are having to be similar to #1810 ?

**Comment by moellert** [comment] 2018-02-23 11:48
@muhammadn I don't think so, 1810 is about the rights you need for being an agent and this problems here just appear when an agent acts as a customer of another group he has no rights for.

Maybe an example helps:
I am an agent in the "Network" group and there is another group like "Unix" but there I have no rights except creating tickets.
When there is the need that the "Unix" colleagues do something for me, I can create an ticket in the group with me as the customer. But after this I can't do anything with this ticket even if I am the customer and it should be able to see and edit it, like the customers with the role Customer can do.

My suggestion is that the rights a role like agent gives you override the rights you have when you are the customer of a ticket.

**Comment by muhammadn** [comment] 2018-02-23 13:28
@moellert Thanks for the detailed info 👍 and sorry for the confusion!

**Comment by muhammadn** [comment] 2018-02-26 07:47
@moellert Currently, a user cannot be both an agent and customer at the same time and it is how Zammad was designed.

**Comment by moellert** [comment] 2018-02-27 08:58
@muhammadn Is it planned to change this?
I think it is a general use-case that an agent has a request in another group and acts as an customer for this.

**Comment by thorsteneckel** [comment] 2018-02-27 09:12
Yes it's planned but on the long run. There is no time schedule and nothing but the plan to do so.

**Comment by moellert** [comment] 2018-02-27 09:19
Ok, thanks for this informations
