### ISSUE TITLE
By changing the sorting order of the ticket history, the timestamps are lost 

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4489] opened 2023-02-09 11:27 UTC
### Used Zammad Version

5.3.x

### Environment

- Installation method: [e.g. source, package] any
- Operating system: any
- Database + version:   any
- Elasticsearch version: any
- Browser + version:: Microsoft Edge, v. 109.0.1518.78 (64-bit)

### Actual behaviour

By changing the ticket history sorting order, the timestamps are lost. By default, each change of the ticket history sorting order is listed, from oldest to newest, in separate timestamps. Changing the sorting order to, from newest to oldest, will merge the timestamps of multiple changes on the same day or on different days by the same user, creating a large block of information with missing timestamps. 

### Expected behaviour

By changing the default sorting order, I would expect the timestamps to remain unchanged, along with the matching articles, the only difference should be whether the listing is shown ascending or descending, everything else remains the same.

### Steps to reproduce the behaviour

Go to an existing ticket --> sidebar on the top right --> click on Ticket --> History --> change order --> observe the change. 

If you want to observe a fresh example, you can create a new ticket. In this case please add some information, e.g. change of attributes in the right sidebar (priority, tags, etc.). Also a change or implementation of SLAs can add more information to the ticket. If possible, this should be done at different times, better yet on different days. 
Changing the order in the ticket history condenses all the timestamps into one big block of text and information. 

https://user-images.githubusercontent.com/101350124/218780030-617c9942-e9c2-42cb-a0d3-3106f8d1645f.mp4

### Support Ticket

Ticket#10123032

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment] 2023-02-09 14:14
@Suhopoljac Can you maybe add a better reproduction description, because it's not happening in all situations? When I see it correctly you need to have some more data inside the history with different groupings.

**Comment by Suhopoljac** [comment] 2023-02-14 15:19
Hi @dominikklein, as promised, here is a video on this topic. 
I have also added more information in the description. If there are still open questions, feel free to ask.

**Comment by rolfschmidt** [comment] 2023-06-21 13:11
might be fixed with https://github.com/zammad/zammad/issues/4604 soon

**Comment by rolfschmidt** [comment] 2023-06-22 12:32
solved with #4604

**Closed as completed by rolfschmidt** 2023-06-22 12:32 UTC
Labels: bug, ticket, verified, prioritised by payment, frontend
