### ISSUE TITLE
Twitter integration: Zammad back-imports own answers as new tickets

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#406] opened 2016-11-13 17:40 UTC
I've integrated a Twitter account, so someone can send me a direct message via Twitter. That works perfectly including the answer which appears in the Twitter account of the customer immediately:

![zammad1](https://cloud.githubusercontent.com/assets/3321655/20247565/a11dd870-a9cf-11e6-8bea-07b916838503.jpg)

Unfortunately and unnecessary Zammad creates a total new ticket for the response which I have sent out to the customer by myself!

![zammad2](https://cloud.githubusercontent.com/assets/3321655/20247594/4ff88b2e-a9d0-11e6-9158-35198d13c80d.jpg)

The sender of this ticket is my own Twitter customer (@FBLev here) so I would answer to myself here. That's a bit strange!

Zammad should not back-import its own outgoing messages here.

Unfortunately I can't filter out these messages as there is no incoming filter for Twitter messages like for incoming eMail.

**Comment by jacotec** [comment] 2016-11-14 11:09
Addition:

This also happens when a tweet is posted.

Example:

- The Name of my Twitter account is "My Sportsclub e.V."
- Someone posts a Tweet "We are the champions"
- Zammad gets a new ticket to the group where the Twitter goes. The ticket just has the content "My Sportsclub e.V.", anytime. Not the Tweet content.
- The ticket is already CLOSED when it arrives!!!

Of course any agent in the Twitter group gets an email notifocation about this ...

**Comment by thorsteneckel** [comment] 2017-02-14 15:09
Hi @jacotec - sorry for the late response. I wasn't able to reproduce the issue. Is this still relevant? Can you please provide a step by step description how to reproduce the behavior? Thanks in advance.

**Comment by thorsteneckel** [comment] 2017-06-02 11:04
Seems to be not an issue anymore. Closing.

**Comment by thorsteneckel** [comment] 2017-06-02 11:05
```diff
diff --git a/test/integration/twitter_test.rb b/test/integration/twitter_test.rb
index 5b3375098..98611f3ad 100644
--- a/test/integration/twitter_test.rb
+++ b/test/integration/twitter_test.rb
@@ -359,8 +359,17 @@ class TwitterTest < ActiveSupport::TestCase
       created_by_id: 1,
     )

+    # remember current count of tickets
+    prev_ticket_count = Ticket.count
+
+    # send direct message
     Scheduler.worker(true)

+    # fetch updates from twitter
+    sleep 15
+    Channel.fetch
+    assert_equal(prev_ticket_count, Ticket.count, 'no new ticket/articles get created from send dm')
```

**Closed by thorsteneckel** 2017-06-02 11:04 UTC
Labels: wontfix
