### ISSUE TITLE
Deleting all tickets throws errors for old IDs

### ISSUE THREAD

**Issue by franckyz0r** [zammad/zammad#2066] opened 2018-06-11 13:32 UTC
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: -
* Elasticsearch version: -
* Browser + version: Chrome v67

### Expected behavior:

* Delete / destroy all tickets `Ticket.destroy_all` 
* Use Zammad without errors

### Actual behavior:

* Delete / destroy all tickets `Ticket.destroy_all` 
* Errors presented in the attached log will be present

### Steps to reproduce the behavior:

* Delete / destroy all tickets `Ticket.destroy_all` 
* Check Production log

After this, I upgraded to 2.5.x version with `yum update zammad`, but this did not solve the issue.
Something broke when I deleted the test tickets.
Also went on a test instance and issued same command (on 5 test tickets - on the other server I had more than 5) -> log in production-test.log. Had error on command issue, but currently there are no errors any more.

[production-test.log](https://github.com/zammad/zammad/files/2090119/production-test.log)
[production.log](https://github.com/zammad/zammad/files/2090007/production.log)

**Comment by thorsteneckel** [comment] 2018-06-11 13:36
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

This is caused by the fact that there are other objects that have references to the tickets (like articles, users etc.) which need to get deleted first. This functionality is currently not supported. You have to resolve this references yourself or make use of our commercial service over at https://zammad.com

**Comment by thorsteneckel** [comment] 2018-06-11 14:00
Hi @franckyz0r - after talking to @martini about this issue we found out that there are different variations of this which are actually bugs. So I reopen this issue and we will address it.

@rlue - please ping @martini for a detailed description how to reproduce. Thanks!

**Comment by franckyz0r** [comment] 2018-06-12 05:09
Thank you for looking into this and thank you for your work.
If any help from my side is needed for testing, let me know.

Regards,
Bogdan

**Closed as completed** 2018-07-20 09:51 UTC
Labels: bug, verified
