### ISSUE TITLE
API call to find tickets not working - elasticsearch errors

### ISSUE THREAD

**Issue by Tulan** [zammad/zammad#2583] opened 2019-05-22 13:18 UTC
### Infos:

* Used Zammad version: 2.9 (May 21th build)
* Installation method (source, package, ..): RPM package for CentOS
* Operating system: CentOS 7.6
* Database + version: PostgreSQL 9.2.24 
* Elasticsearch version: 5.6.13
* Browser + version: Firefox 60.6.1esr

### Expected behavior:

* When using API to retrieve tickets, it would give me tickets list in JSON format.

### Actual behavior:

*curl --user 'admin@dmz.ctl-sat:XXXXX' -k https://zammad-server:443/api/v1/tickets/search?query=state:new
{"tickets":[],"tickets_count":0,"assets":{}}

I have already tried to rebuild the search index without success. The ingest-attachment plugin is installed in Elasticsearch.
When using the search bar in Zammad GUI I can find tickets.

### Steps to reproduce the behavior:

* see "Actual behavior" section.

Yes I'm sure this is a bug and no feature request or a general question.

[logs_elastic.txt](https://github.com/zammad/zammad/files/3207470/logs_elastic.txt)
[logs_zammad.txt](https://github.com/zammad/zammad/files/3207479/logs_zammad.txt)

**Comment by MrGeneration** [comment] 2019-05-22 13:30
This is not a bug and functions as designed.
Reason behind this is, because you want to format your URL correct.

Replease `:` by `%3A` and you'll be fine.
Closing now.

For technical questions, please consult https://community.zammad.org

**Closed as completed by MrGeneration** 2019-05-22 13:30 UTC
Labels: question

**Comment by Tulan** [comment] 2019-05-23 08:46
Hi,
thanks for your answer.

So there is a bug in the [official documentation](https://docs.zammad.org/en/latest/api-intro.html#api-clients):

> Search for tickets (for tickets with state new and open ):
> curl -u test@zammad.com:test123 'https://xxx.zammad.com/api/v1/tickets/search?query=state:new%20OR%20state:open&limit=10&expand=true'

BTW if I replace the `:` by `%3A`, I have the same problem:
`curl --user 'admin@dmz.ctl-sat:XXXXX' -k https://zammad-server:443/api/v1/tickets/search?query=state%3Anew`

`{"tickets":[],"tickets_count":0,"assets":{}}`

When looking in logs files in my First message, it seems two queries are launched at same time, and in the first the query field seems empty:
```
[2019-05-22T12:51:44,338][DEBUG][o.e.a.s.TransportSearchAction] [ySN8m06] [zammad_production][3], node[ySN8m06BRG-OMAhHWrYdwg], [P], s[STARTED], a[id=VNDvzTZDQqaAbZ6xEOnUSQ]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[zammad_production], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[Ticket], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, source={
  "from" : 0,
  "size" : 50,
  "query" : {
    "bool" : {
      "must" : [
        {
          "query_string" : {
            "query" : "\"\"",
            "default_field" : "group_id",
            "fields" : [ ],
            "use_dis_max" : true,
            "tie_breaker" : 0.0,
            "default_operator" : "or",
            "auto_generate_phrase_queries" : false,
            "max_determinized_states" : 10000,
            "enable_position_increments" : true,
            "fuzziness" : "AUTO",
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "phrase_slop" : 0,
            "escape" : false,
            "split_on_whitespace" : true,
            "boost" : 1.0
          }
        },
        {
          "query_string" : {
            "query" : "state:new",
            "fields" : [ ],
            "use_dis_max" : true,
            "tie_breaker" : 0.0,
            "default_operator" : "and",
            "auto_generate_phrase_queries" : false,
            "max_determinized_states" : 10000,
            "enable_position_increments" : true,
            "fuzziness" : "AUTO",
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "phrase_slop" : 0,
            "analyze_wildcard" : true,
            "escape" : false,
            "split_on_whitespace" : true,
            "boost" : 1.0
          }
        }
      ],
```

**Comment by Tulan** [comment] 2019-05-23 08:53
OK my fault, it was a right problem T T

sorry for disturbing.

**Comment by MrGeneration** [comment] 2019-05-23 10:36
My bad, you're right.
Our documentation is outdated here and `:` sometimes seems to work.

I created an enhancement issue to address this. This will ensure that it's always working as expected.
https://github.com/zammad/zammad-documentation/issues/81
