### ISSUE TITLE
OTRS Migration plugin does not install

### ISSUE THREAD

**Issue by cornelinux** [zammad/zammad#504] opened 2016-12-04 21:28 UTC
I would like to migrate OTRS4.

According to the documentation at https://docs.zammad.org/en/latest/migration-otrs.html,
I download the migrator and try to install it to otrs. But I get:
 
    Sorry, can't install package, because package Znuny4OTRS-Repo v2.0.2 is required[..]

Version 2.0.2 is not available in the github repo. How am I supposed to proceed?

**Comment by monotek** [comment] 2016-12-04 21:31
http://portal.znuny.com/api/addon_repos/public/615/latest

**Comment by cornelinux** [comment] 2016-12-04 21:33
The version 5.0.15 seems to require OTRS 5:

    Message: Sorry, can't install/upgrade package, because the framework version required by the package (5.0.x;) does not match your Framework (4.0.11)!

**Comment by monotek** [comment] 2016-12-04 21:34
http://portal.znuny.com/api/addon_repos/public/309/latest

**Comment by cornelinux** [comment] 2016-12-04 21:50
This helped to install the two OTRS packages. I copied the link to the importer.
(I test the importer on a fresh zammad installation on ubuntu 16.04).
The importer starts but ends with:

    OTRS Migration
    Can't connect to Zammad Migrator Konfiguration	

    -/-	Base Objects	
   
    -/-	Benutzer	
    
    -/-	Tickets	


I get  such log entries in production.log:

<pre>
I, [2016-12-04T22:48:49.650706 #1526]  INFO -- : Started GET "/api/v1/import/otrs/import_status?_=1480887773297" for 172.16.200.108 at 2016-12-04 22:48:49 +0100
I, [2016-12-04T22:48:49.652576 #1526]  INFO -- : Processing by ImportOtrsController#import_status as JSON
I, [2016-12-04T22:48:49.652678 #1526]  INFO -- :   Parameters: {"_"=>"1480887773297", "import_otr"=>{}}
I, [2016-12-04T22:48:49.654401 #1526]  INFO -- : Completed 200 OK in 2ms (Views: 0.1ms | ActiveRecord: 0.2ms)
I, [2016-12-04T22:48:52.344672 #1526]  INFO -- : Started GET "/" for 172.16.200.108 at 2016-12-04 22:48:52 +0100
I, [2016-12-04T22:48:52.346206 #1526]  INFO -- : Processing by InitController#index as HTML
I, [2016-12-04T22:48:52.347727 #1526]  INFO -- :   Rendered init/index.html.erb within layouts/application (0.0ms)
I, [2016-12-04T22:48:52.348753 #1526]  INFO -- : Completed 200 OK in 2ms (Views: 1.2ms | ActiveRecord: 0.2ms)
I, [2016-12-04T22:48:52.759871 #1526]  INFO -- : Started POST "/api/v1/signshow" for 172.16.200.108 at 2016-12-04 22:48:52 +0100
I, [2016-12-04T22:48:52.762168 #1526]  INFO -- : Processing by SessionsController#show as JSON
I, [2016-12-04T22:48:52.762299 #1526]  INFO -- :   Parameters: {"fingerprint"=>"251706336", "session"=>{"fingerprint"=>"251706336"}}
I, [2016-12-04T22:48:52.807420 #1526]  INFO -- : Completed 200 OK in 45ms (Views: 10.1ms | ActiveRecord: 1.9ms)
I, [2016-12-04T22:48:52.821550 #1526]  INFO -- : Started GET "/api/v1/translations/lang/de-de?_=1480888133948" for 172.16.200.108 at 2016-12-04 22:48:52 +0100
I, [2016-12-04T22:48:52.823029 #1526]  INFO -- : Processing by TranslationsController#lang as JSON
I, [2016-12-04T22:48:52.823127 #1526]  INFO -- :   Parameters: {"_"=>"1480888133948", "locale"=>"de-de", "translation"=>{}}
I, [2016-12-04T22:48:52.841640 #1526]  INFO -- : Completed 200 OK in 18ms (Views: 15.2ms | ActiveRecord: 0.2ms)
I, [2016-12-04T22:48:52.853679 #1526]  INFO -- : Started GET "/ws" for 172.16.200.108 at 2016-12-04 22:48:52 +0100
I, [2016-12-04T22:48:52.855078 #1526]  INFO -- : Processing by ErrorsController#routing as HTML
I, [2016-12-04T22:48:52.855172 #1526]  INFO -- :   Parameters: {"a"=>"ws"}
E, [2016-12-04T22:48:52.856337 #1526] ERROR -- : No route matches [GET] /ws
E, [2016-12-04T22:48:52.856426 #1526] ERROR -- : nil
I, [2016-12-04T22:48:52.857225 #1526]  INFO -- :   Rendered inline template (0.4ms)
I, [2016-12-04T22:48:52.857487 #1526]  INFO -- : Completed 404 Not Found in 2ms (Views: 0.7ms | ActiveRecord: 0.2ms)
I, [2016-12-04T22:48:52.886570 #1526]  INFO -- : Started GET "/api/v1/getting_started?_=1480888133949" for 172.16.200.108 at 2016-12-04 22:48:52 +0100
I, [2016-12-04T22:48:52.888210 #1526]  INFO -- : Processing by GettingStartedController#index as JSON
I, [2016-12-04T22:48:52.888310 #1526]  INFO -- :   Parameters: {"_"=>"1480888133949", "getting_started"=>{}}
I, [2016-12-04T22:48:52.892715 #1526]  INFO -- : Completed 200 OK in 4ms (Views: 2.0ms | ActiveRecord: 0.7ms)
I, [2016-12-04T22:48:52.911748 #1526]  INFO -- : Started GET "/api/v1/import/otrs/import_status?_=1480888133950" for 172.16.200.108 at 2016-12-04 22:48:52 +0100
I, [2016-12-04T22:48:52.913343 #1526]  INFO -- : Processing by ImportOtrsController#import_status as JSON
I, [2016-12-04T22:48:52.913454 #1526]  INFO -- :   Parameters: {"_"=>"1480888133950", "import_otr"=>{}}
I, [2016-12-04T22:48:52.914939 #1526]  INFO -- : Completed 200 OK in 1ms (Views: 0.1ms | ActiveRecord: 0.2ms)
I, [2016-12-04T22:48:59.424549 #1526]  INFO -- : Started GET "/api/v1/import/otrs/import_status?_=1480888133951" for 172.16.200.108 at 2016-12-04 22:48:59 +0100
I, [2016-12-04T22:48:59.426445 #1526]  INFO -- : Processing by ImportOtrsController#import_status as JSON
I, [2016-12-04T22:48:59.426553 #1526]  INFO -- :   Parameters: {"_"=>"1480888133951", "import_otr"=>{}}
I, [2016-12-04T22:48:59.428140 #1526]  INFO -- : Completed 200 OK in 1ms (Views: 0.1ms | ActiveRecord: 0.2ms)
I, [2016-12-04T22:49:01.213447 #1524]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2016-12-04T22:49:05.935257 #1526]  INFO -- : Started GET "/api/v1/import/otrs/import_status?_=1480888133952" for 172.16.200.108 at 2016-12-04 22:49:05 +0100
I, [2016-12-04T22:49:05.937363 #1526]  INFO -- : Processing by ImportOtrsController#import_status as JSON
I, [2016-12-04T22:49:05.937472 #1526]  INFO -- :   Parameters: {"_"=>"1480888133952", "import_otr"=>{}}
I, [2016-12-04T22:49:05.939348 #1526]  INFO -- : Completed 200 OK in 2ms (Views: 0.1ms | ActiveRecord: 0.3ms)
I, [2016-12-04T22:49:12.447257 #1526]  INFO -- : Started GET "/api/v1/import/otrs/import_status?_=1480888133953" for 172.16.200.108 at 2016-12-04 22:49:12 +0100
I, [2016-12-04T22:49:12.449979 #1526]  INFO -- : Processing by ImportOtrsController#import_status as JSON
I, [2016-12-04T22:49:12.450144 #1526]  INFO -- :   Parameters: {"_"=>"1480888133953", "import_otr"=>{}}
I, [2016-12-04T22:49:12.451821 #1526]  INFO -- : Completed 200 OK in 1ms (Views: 0.1ms | ActiveRecord: 0.2ms)
</pre>

Zammad seems to be stick in this import process. Each time I return to the webui - even after rebooting the machine - I end up in the import error.

**Comment by monotek** [comment] 2016-12-05 00:44
You could try to stop Migration on the command line: https://docs.zammad.org/en/latest/migration-otrs.html#via-command-line

**Comment by cornelinux** [comment] 2016-12-05 06:33
Thanks a lot for your time. But for me the mentioned documentation does not work for me.
I figured, that I obviously need to run /opt/zammad/bin/rails  (from the zammad ubuntu packages).
But it seems to be missing some (virtual) environment:

<pre>
root@zammad:/opt/zammad# bin/rails  c
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/zammad/config/boot.rb:3:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'

</pre>

**Comment by monotek** [comment] 2016-12-05 07:11
Use: Zammad run rails c

**Comment by cornelinux** [comment] 2016-12-05 08:55
Thanks a lot. That worked for me. I was able to run the migration at the shell.
I added a PR for the documentation repository - to my understanding.

But after running the migration at the shell the users are migrated, but the tickets are not.
Should I open another ticket with another topic?

**Comment by monotek** [comment] 2016-12-05 09:10
Whats the output of the migrator?
What does production.log say?

**Comment by thorsteneckel** [comment] 2016-12-05 09:15
The log above looks a bit odd:

```
I, [2016-12-04T22:48:52.855172 #1526]  INFO -- :   Parameters: {"a"=>"ws"}
E, [2016-12-04T22:48:52.856337 #1526] ERROR -- : No route matches [GET] /ws
E, [2016-12-04T22:48:52.856426 #1526] ERROR -- : nil
```

It seems that the websocket server is not running. If the websocket server is not running it might be that the scheduler isn't running either?
The import runs as an asych task which is executed by the scheduler. If the import makes no progress it might be causes by the scheduler not running. Please check this, too.

**Comment by cornelinux** [comment] 2016-12-05 09:30
@monotek The output is gone, since I logged out. Can I simply rerun the import by resetting all the settings (import_mode=true, system_init_done=false)...?

**Comment by monotek** [comment] 2016-12-05 09:39
Not sure but should work.

**Comment by thorsteneckel** [comment] 2016-12-05 09:52
Please execute the following commands first:

```
zammad run rake db:drop
zammad run rake db:create
zammad run rake db:migrate
zammad run rake db:seed
```

Then your system is reset and you can restart the procedure.

**Comment by cornelinux** [comment] 2016-12-05 21:37
OK, I stopped zammad, zammad-web and zammad-worker. No zammad or ruby or whatever process running.

Now run ``zammad run rails c`` set the import url and key and the import_mode and init_done=false...

Please finde the output and the logfile attached.

[zammad.zip](https://github.com/zammad/zammad/files/632337/zammad.zip)

**Comment by cornelinux** [comment] 2016-12-05 21:39
After importing the files, I can not log in. I get the error message 

{"error":"Object already exists!","error_human":"Object already exists!"}

The tracebook looks badly readable. But I guess you can figure this out.
I am willing to start over the import/migration again and again, to help improve the migration process. Noone should use otrs anymore ;-)
[error500.zip](https://github.com/zammad/zammad/files/632343/error500.zip)

**Comment by thorsteneckel** [comment] 2016-12-06 15:35
Hi @cornelinux - thanks for the provided logs! I managed to find the bug and fixed it with the commit above 👍  I removed your files since they are no longer needed and contain information about your system.
I also improved the documentation with information how to perform a diff import and how to restart from scratch. See: https://github.com/zammad/zammad-documentation/commit/9eb586f584370a7178bd69b86417dc82b9485a50

To keep this issue clean and focused I'll close it. If there are any new or other issues feel free to open new issues. We do this to use the issues for our changelog and keep each change separated.

**Closed by thorsteneckel** 2016-12-06 15:35 UTC
Labels: documentation, import

**Comment by cornelinux** [comment] 2016-12-06 16:09
thx.

**Comment by Johannes-GitHub** [comment] 2016-12-18 15:07
Hi @all, 
had the same issue like @cornelinux .... 

Setup fresh Ubuntu 16.04 with following how to do: 
https://decatec.de/home-server/ubuntu-server-als-hyper-v-gastsystem-installieren-und-optimal-einrichten/

Importing all Tickets from OTRS Appliance 4.x 
1. with Plugin and browser -> every status is -/-
2. with command line 
3. with command line diff

Now i can log in, but if i want to set a Ticket in a new group, getting following error: 
{"error":"Object already exists!","error_human":"Object already exists!"}

Or want to rename agent etc.:
{"error":"Object already exists!","error_human":"Object already exists!"}

When i´m running "Restarting from scratch"
Then the following warning come up... 
Think it´s an permission issue or? 

root@LX01:~# zammad run rake db:drop
PG::InsufficientPrivilege: ERROR:  must be owner of database zammad_production
: DROP DATABASE IF EXISTS "zammad_production"
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:86:in `drop_database'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/postgresql_database_tasks.rb:28:in `drop'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:114:in `drop'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:128:in `block in drop_current'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:127:in `drop_current'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:28:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Couldn't drop zammad_production
root@LX01:~#

Thanks a lot for help.

**Comment by thorsteneckel** [comment] 2016-12-18 15:52
Hi @Johannes-GitHub - could you please create a new issue for your case? This one here is closed and we want to keep our issues separated so we can use them for our changelog and stuff. Please provide your used Zammad version so we can try to reproduce the issue. Additionally please try our develop branch package which contains a major rework of the importing logic and if this doesn't work please provide the `log/production.log` file which contains a lot of useful information for us. Thanks!
