### ISSUE TITLE
Custom field default value is not applied over API

### ISSUE THREAD

**Issue by nijel** [zammad/zammad#3177] opened 2020-09-02 09:45 UTC
### Infos:

* Used Zammad version: 3.4.x 
* Installation method (source, package, ..): using zammad.com sevice
* Operating system: 
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* When creating user using API, the default value for custom field should be applied

### Actual behavior:

* The custom field is empty when not specified in the request

### Steps to reproduce the behavior:

* Create a custom field on user object with a default value
* Create new user using API without specifying this field
* Observe that the custom field has empty value

**Comment by MrGeneration** [comment] 2020-09-02 10:25
This seems to be a duplicate of
* https://github.com/zammad/zammad/issues/1653

Please drop our support a short mail mentioning above issue so that we can add you to the list.

**Closed as completed by MrGeneration** 2020-09-02 10:25 UTC
Labels: duplicate

**Comment by nijel** [comment] 2020-09-02 11:03
#1653 doesn't mention API at all, that's why I didn't discover it when looking for existing issues.

**Comment by MrGeneration** [comment] 2020-09-02 11:40
I've extended the first article to hold that hint. I think that this will be a similar part of the application which why one issue should be fitting. :)
