### ISSUE TITLE
improvement suggestion: email address auto-complete

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1157] opened 2017-06-01 07:38 UTC
Hi 👋 
I would like to make an improvement suggestion.
When I'm creating a new ticket in zammad, I will get some e-mail-adresse suggestions for customers and agents which are already in the system. Which is awesome!
Like here:
![screenshot_1](https://cloud.githubusercontent.com/assets/4436931/26669155/0ebe4390-46ad-11e7-91b6-82d8a7981e02.jpg)
Sadly this won't work the 'CC' part in new tickets
![screenshot_2](https://cloud.githubusercontent.com/assets/4436931/26669203/40e82200-46ad-11e7-975e-4a4210394bd2.jpg)
or when I answere to a ticket via email:
![screenshot_3](https://cloud.githubusercontent.com/assets/4436931/26669211/4a371438-46ad-11e7-9ec4-7d9258d30786.jpg)
It would be much more comfortable, if the auto-complete would also work for the other parts of the system

Cheers! 😃

**Comment by thorsteneckel** [comment] 2017-06-01 08:15
Nice suggestion - but it's a duplicate of #338. Feel free to contribute to the discussion over there.

**Closed by thorsteneckel** 2017-06-01 08:15 UTC
