### ISSUE TITLE
change note

### ISSUE THREAD

**Issue by Bueschel** [zammad/zammad#1343] opened 2017-08-14 09:05 UTC
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: (source, package, ...)
* Operating system: Ubuntu 16.04
* Browser + version: Firefox 55

Hello

is it possible to change a existing note in a ticket? 
It would be helpful if at least the owner of a ticket can change a existing note.

**Comment by martini** [comment] 2017-08-14 09:25
Duplicate of #169

**Comment by martini** [comment] 2017-08-14 09:25
Thanks anyway! 👍

**Closed by martini** 2017-08-14 09:25 UTC
Labels: duplicate

**Comment by Bueschel** [comment] 2017-08-14 09:45
Thanks for the answer and the link.
But I don't want to delete a note. I want to change or edit a existing note.
Example:
In a ticket are a few notes. One note has a text "test". Now I want to edit this text or to add some more text to this note.
At the moment firstly I have to copy the text, then delete the note and make a new note to paste the text and add some new Information.

**Comment by martini** [comment] 2017-08-14 09:51
Hi @Bueschel 

sorry for confusing. I thought 193 is about both, delete and edit of notes (Allow users to delete and edit "Notes"). Right now, only deleting own notes is implanted in Zammad.

Editing notes is still open (to implement).

Feedback is welcome!

 -Martin

**Comment by ToubieObie** [comment] 2017-11-10 09:30
Please add the feature to edit notes with the next update. That would be awesome.

**Comment by bentalexanderhaase** [comment] 2018-09-25 11:22
Any updates on this? Editing notes would be a really useful feature. (Including a tiny "edited by ... + date" remark).

**Comment by MrGeneration** [comment] 2018-09-25 11:26
a) this is a duplicate
b) please don't keep asking when a feature comes. It's coming when it's ready :(
