### ISSUE TITLE
Tree Select values being discarded in overview configuration do not reset correctly

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3015] opened 2020-04-08 10:15 UTC
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: latest Google Chrome, Mozilla Firefox and Microsoft Edge
* Ticket-ID: #1072785

### Expected behavior:

When discarding overview dialogues, selected values are no longer set if they're not stored within the database.

### Actual behavior:

When using tree selects within overview configurations, Zammad will not discard set values being selected (but not stored!) and thus, when reopening the same overview for configuration, the tree select value is still the same like after discarding.

**Important Note regarding the value mentioned above**
This only happens, if you select a value **above** the current set value.
If you select a value *after* the set value, it will correctly reset to the setting that lives in the database.

The screencast below should show this best.

### Screencast:

![ticket-1072785_treeselects-cache-discarded-values](https://user-images.githubusercontent.com/6549061/78770450-dee3a800-798e-11ea-97fd-3e7e2899b498.gif)

### Steps to reproduce the behavior:

* create a tree select field with at least 3 rows
* update your database and restart Zammad
* go to your overview configuration and edit an existing overview
  * add a new condition (your new tree select) and select the second value
  * save the changes
* reopen the overview you just stored 
  * change the dropdown of your treeselect to the first value
  * do not submit, but either 
    * click into the background (discard message comes, acknowledge with "OK")
    * or click on [X] on the upper right of the dialogue
* reopen the overview you just discarded and check the value

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by bolah2009** [comment] 2021-02-10 17:16
Hi @MrGeneration, while investigating this issue. I noticed the following:
1. This issue happens only when a "new" condition is added. If the condition is there already, it seems to work fine. See screencast where the `JKL` was the initial value but when changed to `GHI` and then discarded, `JKL` still shows as excepted.

https://user-images.githubusercontent.com/36057474/107541656-a7094a80-6bc7-11eb-98c2-52bedf2088cd.mov

2. When another value is selected and then "submitted", it selects multiple including the previously select and the currently select value. See screencast below:

https://user-images.githubusercontent.com/36057474/107542722-c6ed3e00-6bc8-11eb-9f48-a6bbfcc7ab6c.mov

Can I treat (2) as the same issue?

**Comment by mantas** [comment] 2021-02-11 06:13
@MrGeneration looks like your and @bolah2009 screencasts were filmed before and after some sort of refactoring in this case. Looks like the bug you initially reported is now fixed?

The only somewhat similar issue is following:

- Overview with tree select condition exists
- Overview edit view is opened
- tree select condition removed (not submitting)
- tree select condition added back
- initial tree select value is applied

IMO this is not a bug - this is a reset to initial value.

@bolah2009 are you able to reliably reproduce the bug no.2? I tried to, but no luck :(

**Comment by bolah2009** [comment] 2021-02-11 06:54
> @bolah2009 are you able to reliably reproduce the bug no.2? I tried to, but no luck :(

@mantas, yes, I am able to reproduce it. You can check the setting for the treeselect object below

![image](https://user-images.githubusercontent.com/36057474/107609075-20438480-6c3e-11eb-82fa-80605b4c5827.png)

@mantas I agree that (1) is not an issue. However (2) seems to be a bug. After reloading the page the issue is resolved. See sreencast below:

In the screencast:

- I used another `treeselect`
- reloading the page clears the previously selected value


https://user-images.githubusercontent.com/36057474/107609451-3d2c8780-6c3f-11eb-82de-0b5e6e7569f5.mov

**Comment by bolah2009** [comment] 2021-02-11 07:13
For the bug, adding an else condition here solves it.

https://github.com/zammad/zammad/blob/40936da562774924724c12b6113239059341c078/app/assets/javascripts/app/controllers/_ui_element/_application_ui_element.coffee#L200-L209


This else condition deletes previously selected (but not saved) record.
```coffee
      else
        delete record.selected
        delete record.checked
```

**Comment by thorsteneckel** [comment] 2021-02-11 07:47
Tree select support was recently added by @martini because of https://github.com/zammad/zammad/issues/3333 via https://github.com/zammad/zammad/commit/f3fb482992f791c9c40c72a51066d5e36205ce88 and the follow up https://github.com/zammad/zammad/commit/5e2520fc5e84d9f4a3844a2347d601edc8a1a222 .

Maybe @martini can say something about the other behavior?

**Comment by bolah2009** [comment] 2021-02-11 08:05
@thorsteneckel  I think that solves the issue, I just updated the branch I am working now and everything seems to work fine.

**Comment by mantas** [comment] 2021-02-11 08:14
@thorsteneckel looks like we can close this issue?

**Comment by thorsteneckel** [comment] 2021-02-11 08:19
Yep, I'll label it as a duplicate of #3333 - @bolah2009 can you please create a new issue for the bug you found and refer your PR to this one then?

**Closed as completed by thorsteneckel** 2021-02-11 08:19 UTC
Labels: duplicate

**Comment by bolah2009** [comment] 2021-02-11 08:30
@thorsteneckel I think the bug I found was also solved by the https://github.com/zammad/zammad/commit/5e2520fc5e84d9f4a3844a2347d601edc8a1a222, after updating the branch I am working on, the bug was resolved.
