### ISSUE TITLE
Postmasterfilter | Trigger | Scheduler can't set value to a custom field

### ISSUE THREAD

**Issue by gvigneron** [zammad/zammad#2856] opened 2019-12-12 16:49 UTC
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Postmaster filer | Trigger | Scheduler should be able to set a custom field value of a ticket

### Actual behavior:

* Postmaster filer | Trigger | Scheduler are enable to set a custom field value

### Steps to reproduce the behavior:

* Create a Postmaster filer | Trigger | Scheduler that set a value to a custom field

Exemple of an actual Postmaster filter :
when executed, the tag ("Etiquette") is correctly set but not the custom field ("Filiale groupe")

![Capture d’écran 2019-12-12 à 17 35 05](https://user-images.githubusercontent.com/1419239/70731384-e5c31c80-1d06-11ea-9ed3-056f73864c7c.png)

**Comment by MrGeneration** [comment] 2020-08-13 11:34
Thank you so much for your patience.
I'm afraid that I can't reproduce this issue on either:

   * scheduler
   * postmaster filter
   * trigger

This might have been fixed in the mean time, to be honest, I'm not aware of such an issue but could be wrong!

**Closed as completed by MrGeneration** 2020-08-13 11:34 UTC
Labels: can't reproduce
