### ISSUE TITLE
RFE: Setting state to "pending reminder" in bulk action should ask for "pending till" value

### ISSUE THREAD

**Issue by eliasp** [zammad/zammad#958] opened 2017-04-17 07:51 UTC
### Infos:

* Used Zammad version: 1.4.0

### Expected behavior:

* When modifying the ticket state in a bulk action and set it to "pending reminder", I'd expect Zammad to ask for a "pending till" date

### Actual behavior:

* It just sets a "pending reminder" state without any date value assigned

### Steps to reproduce the behavior:

* Select multiple tickets (e.g. in **Overviews** → **Unassigned & Open**)
* Select **pending reminder** in the **State** dropdown
* Click **Confirm**
* Click **Update**

**Comment by thorsteneckel** [comment] 2018-04-12 09:47
This is a duplicate of #1930 which has some more information on it and is already labeled as `prioritized by payment` so I will close this one here even if it was "first".

**Closed by thorsteneckel** 2018-04-12 09:47 UTC
Labels: bug, verified
