### ISSUE TITLE
Shift-Ctrl-T deletes work (email response) in progress

### ISSUE THREAD

**Issue by Ejxqzgds** [zammad/zammad#2546] opened 2019-04-15 13:56 UTC
### Infos:

* Used Zammad version: 2.1.0-1510157740.86d5b882.stretch
* Installation method (source, package, ..): .deb package
* Operating system: Debian 9.8
* Browser + version: Firefox 52.9.0
* Relates to #656, but is a different issue

### Expected behavior:

* Shift-Ctrl-T does not throw away any work in progress

### Actual behavior:

* Shift-Ctrl-T throws away any work (response) in progress when starting "inline translations" (a feature we don't need)

### Steps to reproduce the behavior:

* Open a ticket, start a response to the client and press Shift-Ctrl-T

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2019-04-17 08:37
Hi @Ejxqzgds - thanks for creating this issue. This has the same root cause as #656 has: Keyboard shortcuts collide with browser shortcuts. Therefore I'll close this as a duplicate and we'll address it when we work on that issue.

**Closed as completed by thorsteneckel** 2019-04-17 08:37 UTC
Labels: duplicate
