### ISSUE TITLE
Issue with space (%20) in HyperLinks

### ISSUE THREAD

**Issue by tsbsi** [zammad/zammad#1902] opened 2018-03-26 13:02 UTC
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): Ubuntu install instructions on your website
* Operating system: ubuntu
* Database + version: Whatever comes in the installer
* Elasticsearch version: Latest
* Browser + version: Chrome Latest

### Expected behavior:

Add a URL to ticket with spaces (%20) in the URL.   Hyperlink keeps the %20.

### Actual behavior:

The spaces (%20) is stripped from the Hyperlink, even though the text remains the same.

### Steps to reproduce the behavior:

Add any URL with a %20 in it to a ticket,  when added to the ticket the hyperlink will strip the %20

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment] 2018-03-28 14:42
@tsbsi i cannot reproduce it on my end. When i created and then click on the ticket with `%20` (space, eg. http://localhost/zaihan%20test),  it opens a new tab with the URL with `%20` as expected.

**Comment by tsbsi** [comment] 2018-03-28 14:48
Hi,
Just retested here..  i can know why you cant reproduce it..

A folder with a space in it works fine, however if you add an extension to the end of it e.g. http://localhost/test%20test.pdf this fails.

**Comment by tsbsi** [comment] 2018-03-28 14:52
Update #2:  If the type of ticket is email this also fails for folders.

**Comment by thorsteneckel** [comment] 2018-03-28 14:55
Probably caused by this line: https://github.com/zammad/zammad/blob/develop/lib/html_sanitizer.rb#L377

Looks like this was added on purpose @martini ?

**Comment by thorsteneckel** [comment] 2018-04-03 15:48
This is fixed in latest develop and will be ready to install in about 30 minutes from now. There is no backport to 2.4 planned. Therefore this will be stable with Zammad 2.5 🚀 closing now. Feedback is welcome 👍

**Closed by thorsteneckel** 2018-04-03 15:48 UTC
Labels: bug, verified
