### ISSUE TITLE
Chat widget error "chat notice || Translation 'es' needed!"

### ISSUE THREAD

**Issue by miguelzabala** [zammad/zammad#1267] opened 2017-07-18 04:33 UTC
### Infos:

* Used Zammad version: 1.5.x 
* Used Zammad installation source: APT official repository (Upgrated right now)
* Operating system: ubuntu 16.04
* Browser + version: independent  (chome or firefox)

### Expected behavior:
When I put the code of chat. See chat window.
* 

### Actual behavior:
Not chat window. And console log show: chat notice || Translation 'es' needed!
* 

### Steps to reproduce the behavior:
Put the chat code on a web page. The regional code should be "Spanish Argentina"
*

**Comment by NeverMin** [comment] 2017-07-18 07:19
Hi @miguelzabala , can you push your translation to us ? Like this:
https://github.com/zammad/zammad/blob/develop/public/assets/chat/chat.coffee

**Comment by miguelzabala** [comment] 2017-07-18 13:19
@NeverMin How can get the tanslations?

**Comment by NeverMin** [comment] 2017-07-19 05:24
Hi @miguelzabala , Can you make a Spanish translation for Zammad? you can post in Comment:

```
'es':
        'English': 'Spanish, like this line'
        'Chat with us!': ''
        'Scroll down to see new messages': ''
        'Online': ''
        'Online': ''
        'Offline': ''
        'Connecting': ''
        'Connection re-established': ''
        'Today': ''
        'Send': ''
        'Chat closed by %s': ''
        'Compose your message...': ''
        'All colleagues are busy.': ''
        'You are on waiting list position %s.': ''
        'Start new conversation': ''

        'Since you didn\'t respond in the last %s minutes your conversation with %s got closed.': ''
        
        'Since you didn\'t respond in the last %s minutes your conversation got closed.': ''
        
        'We are sorry, it takes longer as expected to get an empty slot. Please try again later or send us an email. Thank you!': ''
```

Thanks.

edited: added miss line `Chat closed by %s`

**Comment by miguelzabala** [comment] 2017-07-19 13:05
'es':
        'English': 'Spanish, like this line'
        'Chat with us!': 'Chatee con nosotros!'
        'Scroll down to see new messages': 'Haga scroll hacia abajo para ver nuevos mensajes'
        'Online': 'En linea'
        'Online': 'En linea'
        'Offline': 'Desconectado'
        'Connecting': 'Conectando'
        'Connection re-established': 'Conexión restablecida'
        'Today': 'Hoy'
        'Send': 'Enviar'
        'Compose your message...': 'Escriba su mensaje...'
        'All colleagues are busy.': 'Todos los agentes están ocupados.'
        'You are on waiting list position %s.': 'Usted está en la posición %s de la lista de espera.'
        'Start new conversation': 'Iniciar nueva conversación'

        'Since you didn\'t respond in the last %s minutes your conversation with %s got closed.': 'Puesto que usted no respondió en los últimos %s minutos su conversación con %s se ha cerrado.'
        
        'Since you didn\'t respond in the last %s minutes your conversation got closed.': 'Puesto que usted no respondió en los últimos %s minutos su conversación se ha cerrado.'
        
        'We are sorry, it takes longer as expected to get an empty slot. Please try again later or send us an email. Thank you!': 'Lo sentimos, se tarda más tiempo de lo esperado para ser atendido por un agente. Inténtelo de nuevo más tarde o envíenos un correo electrónico. ¡Gracias!'

**Closed** 2017-07-21 12:30 UTC

**Comment by miguelzabala** [comment] 2017-07-27 13:53
I upgraded the zammad version today and the bug persist. I have zammad 1.5.x upgraded from ubuntu repo.

**Comment by martini** [comment] 2017-07-27 13:56
Hi @miguelzabala 

I can confirm (the chat widget need to get rebuild too - I'll do that). 

One more question. It your translation "es_AR" or is it also usable for "es" in general?

Thanks!

 -Martin

**Comment by miguelzabala** [comment] 2017-07-27 15:01
Is usable fot both, es and es-AR and es-MX

**Comment by martini** [comment] 2017-07-27 15:26
Thanks for feedback @miguelzabala !

I compiled the chat client with your translations. Packages are already build: https://packager.io/gh/zammad/zammad/builds/2266

Just update Zammad, reload your browser (make sure that the new chat.js is loaded in browser).

And your translation is available.

PS:  In case upgrade is not possible, please check https://github.com/zammad/zammad/issues/1294  - the repo file has changed.

**Comment by miguelzabala** [comment] 2017-07-27 17:59
Now I get: 
chat notice || Translation needed for '<strong>Chatee</strong> con nosotros!'
chat.min.js:1 chat notice || Translation needed for 'Scrolle nach unten um neue Nachrichten zu sehen'

**Comment by martini** [comment] 2017-07-28 12:21
Hi @miguelzabala 

thanks for feedback the second one was really a german default text - just updated it right now.

  -=> The chat widget appears now in Spanish, right?

 -Martin

**Comment by miguelzabala** [comment] 2017-07-28 13:00
Hi, @martini the are no updates in the ubuntu deb repo. I have updated right now.

**Comment by zojl** [comment] 2018-08-07 09:07
Hi!
I've just installed Zammad and tried to use chat with Russian translation.
So, I encuntered with the same error: "chat notice || Translation 'ru' needed!"
Here's translation for Russian:

```
'ru':
        'English': 'Russian, like this line'
        'Chat with us!': 'Напишите нам!'
        'Scroll down to see new messages': 'Прокрутите, чтобы увидеть новые сообщения'
        'Online': 'Онлайн'
        'Online': 'Онлайн'
        'Offline': 'Оффлайн'
        'Connecting': 'Подключение'
        'Connection re-established': 'Подключение восстановлено'
        'Today': 'Сегодня'
        'Send': 'Отправить'
        'Compose your message...': 'Напишите сообщение...'
        'All colleagues are busy.': 'Все сотрудники заняты.'
        'You are on waiting list position %s.': 'Вы в списке ожидания под номером %s.'
        'Start new conversation': 'Начать новую переписку.'
        'Since you didn\'t respond in the last %s minutes your conversation with %s got closed.': 'Поскольку вы не отвечали в течение последних %s минут, ваш разговор с %s был закрыт.'
        'Since you didn\'t respond in the last %s minutes your conversation got closed.': 'Поскольку вы не отвечали в течение последних %s минут, ваш разговор был закрыт.'
        'We are sorry, it takes longer as expected to get an empty slot. Please try again later or send us an email. Thank you!': 'К сожалению, ожидание свободного места требует больше времени. Повторите попытку позже или отправьте нам электронное письмо. Спасибо!'
        'Chat closed by %s': '%s закрыл чат'
```

**Comment by martini** [comment] 2018-08-07 09:17
@zojl thanks a lot! Just one line is missing:

        'Chat closed by %s': 'Chat closed by %s',

Thanks for feedback!

**Comment by zojl** [comment] 2018-08-07 09:36
Oh.
Added it into previous message.

**Comment by martini** [comment] 2018-08-07 10:40
@zojl thanks a lot, is available in next stable release (next day).

<img width="390" alt="screen shot 2018-08-07 at 12 39 43" src="https://user-images.githubusercontent.com/110226/43771292-1115e0bc-9a3f-11e8-85d1-aded9bb54cce.png">

**Comment by giannisftaras** [comment] 2021-05-24 12:50
Here's also the Greek translation for the chat widget!

    'el':
        '<strong>Chat</strong> with us!': '<strong>Επικοινωνήστε</strong> μαζί μας!'
        'Scroll down to see new messages': 'Μεταβείτε κάτω για να δείτε τα νέα μηνύματα'
        'Online': 'Σε σύνδεση'
        'Offline': 'Αποσυνδεμένος'
        'Connecting': 'Σύνδεση'
        'Connection re-established': 'Η σύνδεση αποκαταστάθηκε'
        'Today': 'Σήμερα'
        'Send': 'Αποστολή'
        'Chat closed by %s': 'Η συνομιλία έκλεισε από τον/την %s'
        'Compose your message...': 'Γράψτε το μήνυμα σας...'
        'All colleagues are busy.': 'Όλοι οι συνάδελφοι μας είναι απασχολημένοι.'
        'You are on waiting list position <strong>%s</strong>.': 'Βρίσκεστε σε λίστα αναμονής στη θέση <strong>%s</strong>.'
        'Start new conversation': 'Έναρξη νέας συνομιλίας'
        'Since you didn\'t respond in the last %s minutes your conversation with <strong>%s</strong> got closed.': 'Από τη στιγμή που δεν απαντήσατε τα τελευταία %s λεπτά η συνομιλία σας με τον/την <strong>%s</strong> έκλεισε.'
        'Since you didn\'t respond in the last %s minutes your conversation got closed.': 'Από τη στιγμή που δεν απαντήσατε τα τελευταία %s λεπτά η συνομιλία σας έκλεισε.'
        'We are sorry, it takes longer as expected to get an empty slot. Please try again later or send us an email. Thank you!': 'Λυπούμαστε που χρειάζεται περισσότερος χρόνος από τον αναμενόμενο για να βρεθεί μία κενή θέση. Παρακαλούμε δοκιμάστε ξανά αργότερα ή στείλτε μας ένα email. Ευχαριστούμε!'

**Comment by MrGeneration** [comment] 2021-05-24 12:57
Please don't recycle old closed issues. 
A PR on the affected file with the fix is warmly welcome!
