### ISSUE TITLE
New translation broke ticket view in Spanish language

### ISSUE THREAD

**Issue by tasagore** [zammad/zammad#4017] opened 2022-03-17 09:01 UTC
### Infos:

* Used Zammad version: 5.1 (upgraded from previous version that was running fine)
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04

### Expected behavior:

* Click on any ticket and it should be viewed

### Actual behavior:

* Click on any ticket and it shows a blank page

### Steps to reproduce the behavior:

* Click on any ticket

If I setup the user in English (EEUU) all works fine. If I setup te user in Spanish all works except the ticket view. No errors in  browser, zammad or apache log.

**Comment by mantas** [comment] 2022-03-17 09:38
@tasagore which Spanish locale are you using?

If you change same user locale back-and-forth, does it work fine in English and then broken in Spanish?

Could you try to reset cache, restart zammad and then try again? Most likely `zammad run rails r "Cache.clear"`

**Comment by tasagore** [comment] 2022-03-17 14:40
I'm using just Spanish (should be named Spanish-Spain)

Behavior: 

1) I have my profile in Spanish and I can't see the tickets
2) Change my profile to English EEUU, the language changes but still can't see the tickets
3) Logout and login
4) I can see the tickets

Reset cache doesn't change anything.

Regards

**Comment by mgruner** [comment] 2022-06-30 09:41
@tasagore unfortunately, we are not able to reproduce your issue. 
For the time being, I'll close this report. Please feel free to reopen with more information.

**Closed as completed by mgruner** 2022-06-30 09:41 UTC
Labels: needs verification
