### ISSUE TITLE
Objects Manager add new State

### ISSUE THREAD

**Issue by ECM80** [zammad/zammad#574] opened 2017-01-02 10:44 UTC
In the object manager, I can not create a new ticket status. If you click the manger / Tickets object, everything is not clickable

**Comment by ECM80** [comment] 2017-01-02 11:21
Could someone explain to me how I can add a new status. I need the status "Solved".

For any help I would be very grateful

**Comment by ECM80** [comment] 2017-01-04 09:40
UPDATE:

I have added a new TicketState in the documentation via API interface. The new status does not appear.

	{
		"id": 11,
		"state_type_id": 10,
		"name": "In Bearbeitung",
		"next_state_id": null,
		"ignore_escalation": true,
		"note": "In Bearbeitung",
		"active": true,
		"updated_by_id": 3,
		"created_by_id": 3,
		"created_at": "2017-01-02T21:13:27.003Z",
		"updated_at": "2017-01-02T21:13:27.003Z"
	}

![states](https://cloud.githubusercontent.com/assets/24757396/21638111/264d475c-d26a-11e6-85be-fcd73ee6b761.PNG)

**Comment by skibson** [comment] 2017-03-09 09:22
+1 
I also added new status via api but it doesn't show up. What could be wrong?

**Comment by ThePatzen** [comment] 2017-03-10 11:33
I also need a state "Work in progress" :+1:

**Comment by martini** [comment] 2017-03-14 15:49
In the meantime a small howto add a new state via rails console:

Add a new state, let's say "customer feedback":

```
rails c
```

```
Ticket::State.create_or_update(
  name: 'customer feedback',
  state_type_id: Ticket::StateType.find_by(name: 'open').id,
  ignore_escalation: true,
  created_by_id: 1,
  updated_by_id: 1,
)
```

As second you need to tell the ticket state attribute to allow it to select, here is a example, please take care (in case you are not know what you are going to do, create an database backup first)!

```
ObjectManager::Attribute.add(
  force: true,
  object: 'Ticket',
  name: 'state_id',
  display: 'State',
  data_type: 'select',
  data_option: {
    relation: 'TicketState',
    nulloption: true,
    multiple: false,
    null: false,
    default: Ticket::State.find_by(name: 'open').id,
    translate: true,
    filter: [
      Ticket::State.find_by(name: 'new').id,
      Ticket::State.find_by(name: 'open').id,
      Ticket::State.find_by(name: 'pending reminder').id,
      Ticket::State.find_by(name: 'closed').id,
      Ticket::State.find_by(name: 'pending close').id,
      Ticket::State.find_by(name: 'customer feedback').id,
    ],
  },
  editable: false,
  active: true,
  screens: {
    create_middle: {
      Agent: {
        null: false,
        item_class: 'column',
      },
      Customer: {
        item_class: 'column',
        nulloption: false,
        null: true,
        filter: [
          Ticket::State.find_by(name: 'new').id,
          Ticket::State.find_by(name: 'closed').id
        ],
        default: Ticket::State.find_by(name: 'new').id,
      },
    },
    edit: {
      Agent: {
        nulloption: false,
        null: false,
        filter: [
          Ticket::State.find_by(name: 'open').id,
          Ticket::State.find_by(name: 'pending reminder').id,
          Ticket::State.find_by(name: 'closed').id,
          Ticket::State.find_by(name: 'pending close').id,
          Ticket::State.find_by(name: 'customer feedback').id,
        ],
      },
      Customer: {
        nulloption: false,
        null: true,
        filter: [
          Ticket::State.find_by(name: 'open').id,
          Ticket::State.find_by(name: 'closed').id
        ],
        default: Ticket::State.find_by(name: 'open').id,
       },

    },
  },
  to_create: false,
  to_migrate: false,
  to_delete: false,
  position: 40,
)
```

**Comment by skibson** [comment] 2017-03-15 06:37
So you say API is wrong in this case? Maybe it should be noted in documentation?

**Comment by martini** [comment] 2017-03-15 06:57
> So you say API is wrong in this case? Maybe it should be noted in documentation?

You also can use the REST API to do this changes.

-=> Our goal is to cover it via the UI. So this is just a small mini howto/workaround unit the UI is available.

**Comment by cmadle** [comment] 2017-04-26 09:27
> Our goal is to cover it via the UI. So this is just a small mini howto/workaround unit the UI is available.

+1 for this UI enhancement

**Comment by dennybresch** [comment] 2017-05-08 07:32
+1 for this UI enhancement

**Comment by rkopplin** [comment] 2017-09-13 12:02
is there a way to access new created states via api? 
like query search state:newone ?

i've created 2 more states and they are working fine but need api access

**Comment by pebosi** [comment] 2017-11-08 14:02
@skibson Trying to make this change via API the following response is returned:

> "error": "Attribute not editable!"

**Comment by svnr-dvnkln** [comment] 2017-11-16 13:18
What do you have to alter to make a second or third state visible? 
It's only working for the first state we ever added via rails.

**Comment by AchuM** [comment] 2018-02-15 16:28
@martini 

I'm getting the following error when i followed your steps: 

`SyntaxError: (irb):11: syntax error, unexpected tIDENTIFIER, expecting ')'
name: 'state_id',`

Any idea why? 
I'm on zammad 2.3 
Thanks!

**Comment by muhammadn** [comment] 2018-02-15 16:31
@AchuM Maybe you forgot the last closing ")" parentheses. Try checking on that. 😊

**Comment by thorsteneckel** [comment] 2018-02-15 16:32
Hi @AchuM - seems there was an issue while copy pasting the content into the console. I would recommend to past the content into a file in your $ZAMMAD_DIR like e.g. `$ZAMMAD_DIR/add_state.rb` and execute it via `rails r add_state.rb` from your $ZAMMAD_DIR.

Seems you missed a comma in front of the described line `name: 'state_id',`.

**Comment by AchuM** [comment] 2018-02-16 06:23
Yes! `)` was my mistake  🙈 

@thorsteneckel  That's a very good tip, Thanks!  I will do that until we have this via UI 

Thank you!

**Comment by AchuM** [comment] 2018-02-28 06:13
@martini @thorsteneckel  Is there a way to completely disable state selection for customers? Thanks!

**Comment by gualican** [comment] 2018-03-05 10:19
@martini how would you translate those rails shell commands to pure Elasticsearch API calls?
Having installed the DEB package calling /opt/zammad/bin/rails c returns dependencies errors and, not being accustomed to ruby, I can't add a new state.

**Comment by anicoa** [comment] 2018-03-08 10:31
@gualican have you seen https://docs.zammad.org/en/latest/admin-console.html ? regards

**Comment by swissdeveloper** [comment] 2018-10-23 08:57
@martini do you know when does the UI for the state will be available? We would also like to set the color of the state. 

In additional we would also like that user are not able to change the state of a ticket. They often select a wrong one, only agent should be able to do it.

**Comment by kagashe** [comment] 2018-10-29 13:07
+1 for this feature as well.

**Comment by Premyslaw** [comment] 2018-12-05 08:52
+1 for this Feature

**Comment by Memphizzz** [comment] 2019-01-14 17:26
+1

**Comment by MrGeneration** [comment] 2019-01-14 18:14
Locking the conversation for now, as this issue hasn't received any usefull comments in the past, but just +1s.

**Comment by thorsteneckel** [comment] 2019-08-16 14:32
I'll close this issue since technically it's a duplicate of #1525. We describe [how you can already add states via the Zammad Rails console in the documentation](https://docs.zammad.org/en/latest/console/working-on-tickets.html#add-new-ticket-state) until we resolve #1525. Closing now.

**Closed by thorsteneckel** 2019-08-16 14:32 UTC
Labels: feature backlog
