### ISSUE TITLE
Can't process email

### ISSUE THREAD

**Issue by trabug** [zammad/zammad#4467] opened 2023-01-19 12:52 UTC
### Used Zammad Version

5.3.1-1673533381.40e192be.bullseye

### Environment

- Installation method: package
- Operating system: Debian GNU/Linux 11 (bullseye)
- Database + version:  PostgreSQL 13.9 (Debian 13.9-0+deb11u1)
- Elasticsearch version: 7.17.7
- Browser + version: not applicable

### Actual behaviour

Zammad can't process some emails, i.e. [production.log.txt](https://github.com/zammad/zammad/files/10456734/log.txt)

[redacted]

### Expected behaviour

Zammad processes email without error.

### Steps to reproduce the behaviour

I can't see a pattern but it happens regularly.

![unprocessable_mail](https://user-images.githubusercontent.com/123080574/213446264-0cd6d0f4-f89d-4d4e-8533-899f54baef15.png)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment] 2023-01-19 14:49
Duplicate of #4423

**Closed as completed by MrGeneration** 2023-01-19 14:49 UTC
Labels: duplicate
