### ISSUE TITLE
Zendesk migration fails due to multi-line custom ticket field - Validation failed: Data option must have one of text/password/tel/fax/email/url

### ISSUE THREAD

**Issue by shopblocks** [zammad/zammad#3311] opened 2020-11-29 14:30 UTC
During Zendesk migration the import failed due to the following error:

```
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:80:in `raise_validation_error': Problem with ObjectManager Attribute 'data_migration_notes': Validation failed: Data option must have one of text/password/tel/fax/email/url for :type (ActiveRecord::RecordInvalid)
```

Looking at our Zendesk configuration for the "Ticket Fields" settings we have an inactive ticket field called "Data Migration Notes" which looks like this:

![image](https://user-images.githubusercontent.com/14819903/100541762-e74e6300-323d-11eb-8d72-1277efc50713.png)

This could be related to https://community.zammad.org/t/zendesk-import-fails-multiline-text-custom-field-in-organization/2369 - however I can't see if that was ever migrated to Github as an issue, or solved, so I have created a new issue here

_Originally posted by @shopblocks in https://github.com/zammad/zammad/issues/3310#issuecomment-735385857_

**Comment by shopblocks** [comment] 2020-11-29 14:33
As a workaround here we have deactivated and deleted the Zendesk ticket fields that were an issue.

The ticket field had to be fully deleted in Zendesk as Zammad seems to bring across deactivated fields.

After the above error we ran into another error due to the ticket field having a `?` question mark symbol in its name - I will raise another separate issue for that one

**Comment by MrGeneration** [comment] 2020-11-29 14:51
Duplicate of #3307

Please use the search function before posting bug reports.

**Closed as completed by MrGeneration** 2020-11-29 14:51 UTC
Labels: duplicate

**Comment by shopblocks** [comment] 2020-11-29 14:58
@MrGeneration Ticket 3311 is this ticket? Which is the duplicated ticket?

**Comment by MrGeneration** [comment] 2020-11-29 14:59
Correct sorry, I meant #3307.
