### ISSUE TITLE
Alignment of permission matrix breaks border at "/#getting_started/agents"

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4821] opened 2023-09-18 09:41 UTC
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

In the "/#getting_started/agents" Screen, the permission matrix is breaking out of the border: 

![image](https://github.com/zammad/zammad/assets/69846837/3cf08c2e-6de5-41e1-9c55-9529da15f240)
 

### Expected behaviour

The permission matrix in "/#getting_started/agents" should be aligned correctly. 

### Steps to reproduce the behaviour

* Setup new selfhosted Zammad
* Find the bug at "http(s)://myzammad.rocks/#getting_started/agents"

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment] 2023-09-18 10:05
Duplicate of #4570

**Closed as not planned by mgruner** 2023-09-18 10:05 UTC
Labels: duplicate
