### ISSUE TITLE
Login screen does not load in private mode on Safari & Chrome for iOS

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#960] opened 2017-04-17 12:59 UTC
When trying to open the Zammad login page on Safari or Chrome for iOS (iOS 10.2, Chrome 57, corresponding up to date Safari), the page title is shown in the browser tab, but the screen stays blank.

**Comment by hanneshal** [comment] 2017-04-17 21:16
Hi,

this is not a bug, it's "privacy" feature / restriction which is enforced by the browsers. Zammad needs local storage, which is prohibited in private mode in almost every browser. 

 @martini a simple check if localstorage is available, in the browser detection function, should be enough. --> show a info box with a hint + hint for private mode.
What do you think?

![webinspector](https://cloud.githubusercontent.com/assets/804939/25105171/cd66171c-23c3-11e7-880e-b798b445f60d.jpg)

**Comment by babakkazemi** [comment] 2017-04-18 07:23
@hanneshal an info box with hint for private mode in case of disabled local storage is fine - then users know what to do (disable client storage in zammad settings or use normal browser session)

**Comment by martini** [comment] 2017-04-18 07:43
@hanneshal here would be a good point to check if local storage is working or not:

https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/lib/app_post/browser.coffee.coffee#L55

**Comment by thorsteneckel** [comment] 2018-06-22 14:56
Duplicate of #223. Closing.

**Closed by thorsteneckel** 2018-06-22 14:56 UTC
Labels: enhancement
