### ISSUE TITLE
Most of our agents confuse "note" and "reply"

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#1135] opened 2017-05-26 10:53 UTC
### Infos:

* Used Zammad version: 1.5.0-1495017264.48b4945.jessie
* Used Zammad installation source: deb
* Operating system: Debian 8
* Browser + version: Firefox on Debian 8

### Expected behavior:

* Agent replies (click on "reply" or "reply to all") to user, customer gets reply by email, everyone is happy

### Actual behavior:

* Agent accidently adds a note (text bubble) instead of clicking reply, customer does not get reply by email, both get frustrated by lack of answer

### Why does it happen?

Confucius said:
> If the same error happens again and again, it is the fault of the UI, not the users!

The "note" (next text bubble) field is large and "invites" the agent to type text. The "reply" buttons are small and sheepish. Agents are fooled into doing the wrong thing.

### How to solve it?

Easy! Why not just remove the default "note" field and add another button similar to "reply", e.g. "add note". That way agents have explicitely to decide whether to reply or add a note and will hopefully do the right thing.

**Comment by jarne** [comment] 2017-05-26 18:02
I would also prefer that reply is default instead of internal notes. Another possibility would be to create two buttons, one to create an internal note and one to send an answer. This would force the agent to choose which type of answer he wants to send.

Many agents who are new to this software are asking me why no reply is sent to the user.

**Comment by SimonWerner** [comment] 2017-05-26 19:36
What about two columns? One column for the conversation with the customer over various channels and the other one for internal notes.

**Comment by rchkb** [comment] 2017-07-11 05:16
I think I'd prefer to be able to set a default, but I also like the idea of having to click a button either way.

**Comment by martini** [comment] 2017-07-11 06:28
For me there is also a difference between not (which is usually just added at the end) and an reply (where a certain article/email is picked - with certain recipient list).

So for me (and I have seen it also on other instances) the following could be an solution?

1) Create an trigger where notes which are not marked as internal are sent to the customer automatically
2) Change the default note internal to note external if you open the ticket zoom screen (this can be done in current develop/master - you have some other ticket screen settings now too).

# What will change:
1) A agent open a ticket and just enter some feedback, this feedback is sent to customer automatically.
2) A agent open a ticket and just enter some internal feedback, need to change it to note internal and can update the ticket (no email is sent to customer).

Any feedback about this trigger/note (internal/external) solution?

**Comment by MartinBorg** [comment] 2017-07-11 06:46
Martini, what is the difference between sending a note compared to "reply" and "reply to all"? We do never want "unpersonal" notes to our customers, but always "personal" emails. "Dear xxx, ...blah, blah... ::br, -- long signature" etc. At the moment they only get an unpersonal message when a ticket is newly created, but then never again.

Also, I fear, that some agents might too easy forget "setting to internal" and customer would get a message not suitable for them. Currently, agents at least can differentiate email and note by the presence or absence of signature.

**Comment by rchkb** [comment] 2017-07-11 10:55
I think the idea of a note can be confusing to anyone who doesn't ordinarily work in a CRM or ticketing system.  For those who are more accustomed to email, they expect to be replying to the ticket when they start typing.

My preference would be an option to set what you want the default SetArticleType to be when you first open - note, email, etc. - and allow the admins to determine what an agent sees when they open the ticket zoom screen.

But @martini 's solution does solve the issue of customers not getting replies because agents are creating an internal note and thinking they are replying to a ticket, which is (I think) the original request.  :)

**Comment by chrisovad** [comment] 2018-03-31 05:10
No resolution on this? It's pretty confusing. Why doesn't the UI clearly indicate that it's a note? The icons don't mean anything to people trying to learn the system. We've been trained for decades that the text box at the bottom conversation sends a message, and here, it generates a local note. 

For context: I'm trying to move away from Zendesk because of file size limits. They use opposite logic there. The response is sent to the customer and you have to press an additional button to make it a note.

**Comment by sts** [comment] 2018-05-30 07:38
Same here, the UI is quite confusing!

**Comment by robclancy** [comment] 2018-06-14 16:30
The UX is simply very bad. Many mistakes and this issue from over a year ago gives me no confidence in this software so will have to move away.

**Comment by monotek** [comment] 2018-06-14 16:46
"Many mistakes". 

Which?

**Comment by thorsteneckel** [comment] 2018-06-14 21:55
Guys please keep it this on track. I can understand the frustration of @robclancy . But this is not the right place. This is our issue tracker. We track issues over here.
If you want to share your opinion use the [community board](http://community.zammad.org/) but make sure to provide some arguments with which we can work - as @monotek requested. Otherwise it's plain moaning without substance which helps nobody. 
Thanks for your understanding!

**Comment by robclancy** [comment] 2018-06-15 15:58
The last 2 replies are super puzzling. The issue has had the information you have needed since day 1. It is described in the original post. And as for "Many mistakes" - read the title of this issue, you don't even need to get to the content of it to understand it unless you have never actually used zammad.

How about instead of getting overly defensive about an issue that will confuse every user, unless they use the system 90% of the day and get used to it (and even then they will probably still make mistakes because of this bad design), how about you bring it to the attention of whoever works on the UI and make some basic changes so it uses common sense and doesn't cause mistakes.

I doubt the person who even made this issue even uses zammad now. We will be moving away next week. It's a shame because there are a lot of nice features but the main core feature of a support system has such bad UX there is no chance we can keep using it unless we forked and I'd rather just find something else that doesn't have a critical design issue open for over a year.

**Comment by adrianschneider94** [comment] 2018-11-11 20:25
Any updates on this?
I think @robclancy is right (but a bit aggressive in his tone 😉) — this should be a top priority.
It‘s a big problem and it‘s rather easy to fix.

**Comment by thorsteneckel** [comment] 2018-11-12 08:13
Hi folks. This is a hot topic that comes up every once in a while. There are two groups of users with a contradictory view on the topic and we (currently) can't satisfy both. However, [our position](https://github.com/zammad/zammad/issues/1135#issuecomment-314346118) hasn't changed. There is a workaround in place which works pretty well for our customers.
I will lock this topic - but feel free to head over to the [community board](http://community.zammad.org/) to discuss this topic and share your opinion.

**Comment by thorsteneckel** [comment] 2018-11-12 16:16
JFI: @mrflix just called and told me that he talked with @martini about this issue. He will work on a proper solution to resolve the workaround and improve the usability. We'll keep you updated.

**Comment by mrflix** [comment] 2018-11-13 13:32
Sorry for the confusion with this part of our UI and thank you for your feedback!
I wrote down our idea on how to address this issue in https://github.com/zammad/zammad/issues/372#issuecomment-438265852. Lets move this discussion over there.

**Comment by thorsteneckel** [comment] 2018-11-13 13:39
@mrflix and I agreed on that this issue is a duplicate of #372 - in which we will proceed with the fix. Please subscript to #372 to get notified about changes and progress. Thanks for your understanding and patience 👍 🚀

**Closed by thorsteneckel** 2018-11-13 13:39 UTC
Labels: UX/UI, enhancement, feature backlog
