### ISSUE TITLE
Profile not clickable on browsers with touch events or on some Chrome for Windows

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#1398] opened 2017-09-11 12:29 UTC
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: Chrome

### Expected behavior:

Just Updated to 2.0! Nice work! But when i click on "Profile" i get nothing. No reaction. 

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by hanneshal** [comment] 2017-09-11 12:38
Hi @Julian0o 
is there an output in the JS error Console? 
Have tried to log out login again? + Delete Cache 

regards

**Comment by Julian0o** [comment] 2017-09-11 13:15
Even with inkognito Tab no chance. 

How can i get the JS error Console?

**Comment by babakkazemi** [comment] 2017-09-11 14:33
maybe something to do with #1325 ?

**Comment by jannheider** [comment] 2017-09-11 14:51
We use Zammad 2.0 with Chrome and don't have that issue.

@Julian0o 
Open developer tools -> Console
Here more instructions -> https://developer.chrome.com/devtools

**Comment by ktwe** [comment] 2017-09-11 15:27
I can confirm this issue, but for me the whole submenus on the left pane doesn't work. So I can't sign off or create a new ticket as well.

The issues seems to be related to Chrome only (Version 61.0.3163.79 (Official Build) (64-bit)). I can't reproduce it in Firefox.

Zammad Ubuntu package is 2.1.1-1505128598.ef38800b.xenial.

**Comment by mweinelt** [comment] 2017-09-11 20:03
Works when using the Up/Down keys, but not with mouse cursor.

**Comment by nilsrb** [comment] 2017-09-12 05:59
Same issue here, i can open the menu, but can't click anything. Browser is also Chrome 61.0.3163.79
Arrow keys are working in the menu.

**Comment by mengine23** [comment] 2017-09-12 08:44
If i delete the element:
**<div class="dropdown-backdrop"></div>**
from rendered html, it works.

Maybe some overlay issue?

**Comment by martini** [comment] 2017-09-12 08:45
@mengine23 yes, it seems so. Properly an Chrome issue... working on a workaround...

**Comment by mengine23** [comment] 2017-09-12 08:49
@martini don't nkow this elemt is used for or if the z positioning is mandatory for it. maybe setting z-index tpo a negative value could help?

**Comment by martini** [comment] 2017-09-12 14:48
It's fixed in develop & stable. It would be nice to get feedback if it's also working on you side.

Packages are on the way: https://packager.io/gh/zammad/zammad/builds/2406 ETA about 17:30

**Comment by babakkazemi** [comment] 2017-09-12 15:18
Works on my iPad in Chrome and Safari and on my android in Chrome! Thanks!

**Comment by ktwe** [comment] 2017-09-12 15:30
Works for me in Chrome! Thanks for your fast response!

**Comment by Johannes-GitHub** [comment] 2017-09-12 15:45
Works for me too in Chrome, thanks a lot good fast job!

**Comment by nilsrb** [comment] 2017-09-13 06:22
Works! Thanks!

**Closed** 2017-09-13 06:53 UTC
Labels: bug, verified

**Comment by nonameolsson** [comment] 2018-09-26 21:16
I really don't understand if this is closed or not. We can't use Zammad on touch devices. All the dropdowns doesn't work. Nothing happens when the user presses an item in the dropdown.

**Comment by hanneshal** [comment] 2018-10-31 16:35
@nonameolsson The original issue was fixed and the users confirmed it as fixed. So the issue was closed. If you have issues using Zammad on touch devices please open a new issue and if possible attach screenshots and mark the spots. This would help a lot. 

Regards 
Johannes
