### ISSUE TITLE
Customer permissions do not work as intended

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5435] opened 2024-12-03 13:49 UTC
### Used Zammad Version

6.4

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

I have a user who has an "agent" and "customer" role.

If the user creates a ticket for him self and the ticket is in a Group where the Agent has only "read" permissions, the user can not update his own ticket.

### Expected behaviour

A user should always be able to update his tickets

### Steps to reproduce the behaviour

- Create an "agent" role with "read" permissions to a group.
- add the agent role to a user that has the "customer" role.
- create a ticket for the user in the group where he has "read" permissions.
- try to update the ticket connected as the customer for whom the ticket is created.

![Image](https://github.com/user-attachments/assets/a823b6f8-95c2-4adf-94b9-17d24d5c6d69)

### Support Ticket

Ticket#10165860

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dominikklein** [comment] 2024-12-03 19:15
Looks like a duplicate of this one here: https://github.com/zammad/zammad/issues/4649

**Comment by dominikklein** [comment] 2024-12-05 06:58
Closed because of duplicate of #4649

**Closed as completed by dominikklein** 2024-12-05 06:58 UTC
Labels: duplicate
