### ISSUE TITLE
Notification sounds do not work for all agents

### ISSUE THREAD

**Issue by MrJambos** [zammad/zammad#5382] opened 2024-10-28 15:33 UTC
### Used Zammad Version

 6.3.1-1729263800.69400098.noble

### Environment

- Installation method: [e.g. source, package] package for ubuntu
- Operating system  Ubuntu 24.04 LTS"
- 
- Database + version:   postgresql
- Elasticsearch version: [7.17.22]
- Browser + version: chrome Versione130.0.6723.70 (Build official) (64 bit)

### Actual behaviour

only one operator receives notification when a new ticket arrives. the other operators receive nothing

### Expected behaviour

I would like all the agents who work the tickets to be able to receive the audio and visual notification on the zammad page

### Steps to reproduce the behaviour

when a customer opens a new ticket on zammad, the ticket arrives and only an agent sees the sound and pop-up.
other agents receive no notification

### Support Ticket

-

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment] 2024-10-28 15:34
Smells like a duplicate of this community post:
https://community.zammad.org/t/new-ticket-notification/15829

Please fill in the missing information requested in the issue template.

**Comment by fliebe92** [comment] 2024-10-29 12:06
Hi @MrJambos.

I am not able to reproduce the issue you've reported, even your steps how to reproduce this issue are not complete/helpful. Therefore, for the moment, I am going to close this report.

Feel free to re-open it with more appropriate steps that can be used to really reproduce the issue. Otherwise, you could also ask in our community at https://community.zammad.org. Maybe some people ran into the same issue some time ago and could help you.

**Closed as not planned by fliebe92** 2024-10-29 12:06 UTC
Labels: question

**Comment by MrJambos** [comment] 2024-10-29 13:53
Hi Guys;
the link  you pasted is not vaild i think :)

**Actual behavior:**
A new ticket is sent via Email to Zammad.
The ticket history tells me a notification has been sent only to 1 of 6  agents.
just 1 agent have no problem ; other 5 agents don't recieve any notification.
All email triggers work fine.

i suspect it's a bug

**Steps to reproduce the behavior:**
Create a ticket → No email notifications are sent even though the setting is correct in the Agents profile and the ticket history tells only one agent received the notification
![image](https://github.com/user-attachments/assets/b08f073b-c20d-4cd6-90cf-87b50a358cad)

Thank you for the support guys

**Comment by MrGeneration** [comment] 2024-10-29 13:55
> the link you pasted is not vaild i think :)

Deleting your commnity account after the note is funny. :)

**Comment by MrJambos** [comment] 2024-10-29 13:57
i'm sorry but i don't know what you're referring to.... which account?
