### ISSUE TITLE
Duplicate tickets from one email. 

### ISSUE THREAD

**Issue by MBekspert** [zammad/zammad#1662] opened 2017-11-21 15:32 UTC
### Infos:

After receiving an e-mail on monitoring mailbox, two tickets with consecutive numbers appear in  Zammad. The client gets two notifications. The content of tickets is the same. 

The monitored box is on Office365.
The network is ok. I am attaching a log file from zammad
```
E, [2017-11-21T08:22:57.501360 #15699] ERROR -- : Can't use Channel::Driver::Imap: #<Net::IMAP::NoResponseError: Some of the requested messages no longer exist.>
E, [2017-11-21T08:22:57.501629 #15699] ERROR -- : ["/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/imap.rb:1194:in `get_tagged_response'", "/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/imap.r
b:1248:in `block in send_command'", "/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'", "/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/imap.rb:1230:in `send_comma
nd'", "/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/imap.rb:1410:in `block in store_internal'", "/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'", "/opt/zammad/
vendor/ruby-2.4.1/lib/ruby/2.4.0/net/imap.rb:1408:in `store_internal'", "/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/imap.rb:834:in `store'", "/opt/zammad/app/models/channel/driver/imap.rb:201
:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:177:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:177:in `fetch'", "/opt/zammad/app/models/channel.rb:63:in `fetch
'", "/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'", "/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_re
cord/relation/delegation.rb:39:in `each'", "/opt/zammad/app/models/channel.rb:31:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:178:in `eval'", "/opt/zammad/app/model
s/scheduler.rb:178:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:141:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:140:in `loop'", "/opt/zammad/app/models/sched
uler.rb:140:in `block in start_job'", "/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"]
I, [2017-11-21T08:22:58.824412 #15701]  INFO -- : Completed 200 OK in 12596ms (Views: 0.8ms | ActiveRecord: 5.6ms)

```
* Used Zammad version: 2.1.0-15095477
* Used Zammad installation source: package
* Operating system: Debian 9.2 (4.9.0-4-amd64)
* Browser + version: 57.0

### Expected behavior:

* from one email create one ticket.

### Actual behavior:

* Sometimes from one email create two ticket. 
[zammad_log.txt](https://github.com/zammad/zammad/files/1491914/zammad_log.txt)

### Steps to reproduce the behavior:

* n/a

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-03-01 10:29
Hi @MBekspert are you able to reproduce this? If so: Can you give us a detailed explanation how? We are not able to reproduce it. Closing now. Feel free to reopen if the issue still persists and you can tell us how to reproduce it. Thanks!

**Closed by thorsteneckel** 2018-03-01 10:29 UTC

**Comment by osarrat** [comment] 2022-09-29 15:32
For emails sent by Mandrill Transactional service, we are reproducing this issue every time.
I have updated our Zammad server from v3.6 to v5.2, and we still have the issue.

I'm open to provide any information to help fix this issue.

**Comment by MrGeneration** [comment] 2022-09-29 15:39
Please open a new issue. This one's 4 years old.
We'd need to know how this happens and how the affected email channel(s) and group(s) are configured.

If possible a eml (raw content from the ticket article) of an affected example mail would help a lot to understand what is happening.

**Comment by osarrat** [comment] 2022-09-29 16:13
As suggested, I was upon to open a new issue.
But while retrieving the log on a reproduction example, I had suddenly realized that between two of the email addresses monitored in Zammad there was an automatic redirection. Zammad was not able to identify the email was identical even though coming from two different sources (it would be an excessive expectation...), and thus two tickets are created from a single email (but copied to a second address).

Email monitoring disabled in Zammad for one of the two email address => issue solved for me.

I hope this comment will help anyone else in the same situation.
