### ISSUE TITLE
Office 365 Login error 422: The change you wanted was rejected.

### ISSUE THREAD

**Issue by WimTh** [zammad/zammad#2743] opened 2019-09-17 08:35 UTC
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..):  DEB
* Operating system:  Ubuntut 18.04 LTS
* Database + version: postgres (PostgreSQL) 10.10
* Elasticsearch version: 7.3.2
* Browser + version: Chrome 77.0.3865.75, Edge, Firefox 

### Expected behavior:

* When logging in with office 365 authentication be able to login.

### Actual behavior:
![image](https://user-images.githubusercontent.com/40689739/65025118-66f05a80-d936-11e9-9086-6ecca30a39ce.png)

* In chrome this gives an error 422: The change you wanted was rejected.
In edge beta this also gives the same problem
In edge and firefox this works

### Steps to reproduce the behavior:

* clicking on office 365 login
Last logs of production.log
I, [2019-09-17T08:33:25.528330 #51948-47047058076940]  INFO -- : Started GET "/" for 10.0.2.4 at 2019-09-17 08:33:25 +0000
I, [2019-09-17T08:33:25.534276 #51948-47047058076940]  INFO -- : Processing by InitController#index as HTML
I, [2019-09-17T08:33:25.535226 #51948-47047058076940]  INFO -- :   Rendering init/index.html.erb within layouts/application
I, [2019-09-17T08:33:25.535376 #51948-47047058076940]  INFO -- :   Rendered init/index.html.erb within layouts/application (0.0ms)
I, [2019-09-17T08:33:25.537174 #51948-47047058076940]  INFO -- : Completed 200 OK in 3ms (Views: 0.9ms | ActiveRecord: 0.3ms)
I, [2019-09-17T08:33:26.084257 #51948-47047058075020]  INFO -- : Started POST "/api/v1/signshow" for 10.0.2.4 at 2019-09-17 08:33:26 +0000
I, [2019-09-17T08:33:26.089248 #51948-47047058075020]  INFO -- : Processing by SessionsController#show as JSON
I, [2019-09-17T08:33:26.089306 #51948-47047058075020]  INFO -- :   Parameters: {"fingerprint"=>"1133631494"}
I, [2019-09-17T08:33:26.219750 #51948-47047058075020]  INFO -- : Completed 200 OK in 130ms (Views: 8.2ms | ActiveRecord: 3.7ms)
I, [2019-09-17T08:33:26.288995 #51948-47047058075760]  INFO -- : Started GET "/api/v1/translations/lang/en-us?_=1568709206979" for 10.0.2.4 at 2019-09-17 08:33:26 +0000
I, [2019-09-17T08:33:26.292525 #51948-47047058075760]  INFO -- : Processing by TranslationsController#lang as JSON
I, [2019-09-17T08:33:26.292580 #51948-47047058075760]  INFO -- :   Parameters: {"_"=>"1568709206979", "locale"=>"en-us"}
I, [2019-09-17T08:33:26.295378 #51948-47047058075760]  INFO -- : Completed 200 OK in 3ms (Views: 0.1ms | ActiveRecord: 0.2ms)
I, [2019-09-17T08:33:28.365516 #51948-47047058075300]  INFO -- : Started POST "/auth/microsoft_office365" for 10.0.2.4 at 2019-09-17 08:33:28 +0000
F, [2019-09-17T08:33:28.369370 #51948-47047058075300] FATAL -- :
F, [2019-09-17T08:33:28.369463 #51948-47047058075300] FATAL -- : ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
F, [2019-09-17T08:33:28.369505 #51948-47047058075300] FATAL -- :
F, [2019-09-17T08:33:28.369560 #51948-47047058075300] FATAL -- : vendor/bundle/ruby/2.5.0/gems/omniauth-rails_csrf_protection-0.1.2/lib/omniauth/rails_csrf_protection/token_verifier.rb:34:in `call'

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-09-17 11:35
I believe that this is a duplicate of:
* https://github.com/zammad/zammad/issues/2617
* https://github.com/zammad/zammad/issues/2700

Please check if this also applies to you and if so, close the issue.
If not, please give the exact way to reproduce this (the above is not enough!)

Especially when dealing with several browsers where "one works, the other one doesn't", ensure to point out differences (not just addons, but also if you have more than one session for office365 in the browser as example) and the exact ways. What are you seeing, what are you getting.

**Comment by WimTh** [comment] 2019-09-17 14:44
Hi,
It is not like #2617 we cannot get past "login via Office365 (in Zammad)
authenticate against microsoft "also the error is different in the log.
It is a lot like #2700 and indeed with all chromium-based browsers, without any plugin enabled or installed.
I can successful login with office 365 with edge or firefox. Both without plugins and in private mode 
and normal mode.

Steps to reproduce:
-add office 365 authentication
-goto zammad and press office 365 with chromium based browser (tried this on Pc and Mac)
-u get the 422 error.

**Comment by MrGeneration** [comment] 2019-09-17 15:12
Sorry, I'm unable to reproduce this on Chromium based Browsers (current Google Chrome and Edge (no beta)).

Please ensure that your App is configured correctly and if the mail address is already known to Zammad, that you have account linking enabled (if not do it manually first).

If you need further discussion on this, please consult the community, because I don't see this as a bug, but rather a technical question - I'm sorry.

**Closed as completed by MrGeneration** 2019-09-17 15:12 UTC
Labels: question, can't reproduce
