### ISSUE TITLE
StatusCode: 500  When searching for an article in a ticket and enter one digit

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#3148] opened 2020-08-05 10:02 UTC
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): package
* Operating system: Centos 7.7
* Database + version: Postgresql 9.2.24
* Elasticsearch version: 5.6.16
* Browser + version: Gooele chrome 84.0.4147.105 

### Expected behavior:

*

### Actual behavior:

When searching for an article in a ticket (with ??) if you enter one digit you get Internal Server Error 500

![2020-08-05 12-41-49](https://user-images.githubusercontent.com/11810187/89399753-8e514100-d71b-11ea-8b6f-be145e8fe03f.gif)

```
{"error":"No route matches {:action=\u003e\"show\", :answer=\u003e#\u003cKnowledgeBase::Answer::Translation id: 44, title: \"AAAA\", kb_locale_id: 4, answer_id: 3, content_id: 44, created_by_id: 3, updated_by_id: 3, created_at: \"2020-06-15 16:18:22\", updated_at: \"2020-06-15 16:20:27\"\u003e, :category=\u003enil, :controller=\u003e\"knowledge_base/public/answers\", :locale=\u003e\"en-us\"}, posse unmatched constraints: [:category]"}
```

```
I, [2020-08-05T12:35:54.810685 #3988-47315240906220]  INFO -- : Started POST "/api/v1/knowledge_bases/search" for  at 2020-08-05 12:35:54 +0300
I, [2020-08-05T12:35:54.816797 #3988-47315240906220]  INFO -- : Processing by KnowledgeBase::SearchController#search as JSON
I, [2020-08-05T12:35:54.816890 #3988-47315240906220]  INFO -- :   Parameters: {"query"=>"3", "flavor"=>"agent", "index"=>"KnowledgeBase::Answer::Translation", "url_type"=>"agent", "highlight_enabled"=>false}
I, [2020-08-05T12:35:54.822558 #3988-47315240906220]  INFO -- : # curl -X get "http://127.0.0.1:9200/zammad_production/KnowledgeBase::Answer::Translation/_search"
I, [2020-08-05T12:35:54.858782 #3988-47315240906220]  INFO -- : # 200
I, [2020-08-05T12:35:54.858876 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 50
I, [2020-08-05T12:35:54.858903 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 49
I, [2020-08-05T12:35:54.858931 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 48
I, [2020-08-05T12:35:54.858950 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 47
I, [2020-08-05T12:35:54.858967 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 46
I, [2020-08-05T12:35:54.858984 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 44
I, [2020-08-05T12:35:54.859011 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 43
I, [2020-08-05T12:35:54.859084 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 42
I, [2020-08-05T12:35:54.859130 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 41
I, [2020-08-05T12:35:54.859176 #3988-47315240906220]  INFO -- : ... KnowledgeBase::Answer::Translation 40
E, [2020-08-05T12:35:54.926379 #3988-47315240906220] ERROR -- : No route matches {:action=>"show", :answer=>#<KnowledgeBase::Answer::Translation id: 44, title: "AAAA", kb_locale_id: 4, answer_id: 3, content_id: 44, created_by_id: 3, updated_by_id: 3, created_at: "2020-06-15 16:18:22", updated_at: "2020-06-15 16:20:27">, :category=>nil, :controller=>"knowledge_base/public/answers", :locale=>"en-us"}, possible unmatched constraints: [:category] (ActionController::UrlGenerationError)
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/formatter.rb:57:in `generate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:744:in `generate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:775:in `generate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:822:in `url_for'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:273:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:214:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:331:in `block (2 levels) in define_url_helper'
/opt/zammad/app/controllers/knowledge_base/search_controller.rb:78:in `public_item_details_answer'
/opt/zammad/app/controllers/knowledge_base/search_controller.rb:62:in `public_item_details'
/opt/zammad/app/controllers/knowledge_base/search_controller.rb:42:in `block in search'
/opt/zammad/app/controllers/knowledge_base/search_controller.rb:42:in `map'
/opt/zammad/app/controllers/knowledge_base/search_controller.rb:42:in `search'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:194:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:18:in `block (4 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:180:in `subscribed'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:17:in `block (3 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:180:in `subscribed'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:16:in `block (2 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:134:in `process'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.4.3/lib/action_view/rendering.rb:32:in `process'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:191:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:252:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `serve'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:420:in `call_app!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-saml-1.10.1/lib/omniauth/strategies/saml.rb:89:in `other_phase'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:38:in `call_app'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2020-08-05T12:35:54.928822 #3988-47315240906220]  INFO -- : Completed 500 Internal Server Error in 112ms (Views: 0.2ms | ActiveRecord: 10.3ms)
```

### Steps to reproduce the behavior:

* Open ticket, type ?? And one digit

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-08-05 10:08
Thank you for your report. Please edit your first article and provide the browser you used. :) 
Thank you

**Comment by YosefAdPro** [comment] 2020-08-05 10:14
> Thank you for your report. Please edit your first article and provide the browser you used. :)
> Thank you

done :)

**Comment by mantas** [comment] 2020-08-05 10:44
@YosefAdPro looks like this is knowledge base structure issue (although it's still a bug, just in a different bit) rather than search itself.

Is this a publicly available or internal knowledge base?

Looks like this is the core bit:

```ruby
E, [2020-08-05T12:35:54.926379 #3988-47315240906220] ERROR -- : No route matches {:action=>"show", :answer=>#<KnowledgeBase::Answer::Translation id: 44, title: "AAAA", kb_locale_id: 4, answer_id: 3, content_id: 44, created_by_id: 3, updated_by_id: 3, created_at: "2020-06-15 16:18:22", updated_at: "2020-06-15 16:20:27">, :category=>nil, :controller=>"knowledge_base/public/answers", :locale=>"en-us"}, possible unmatched constraints: [:category] (ActionController::UrlGenerationError)
```

Does it fail same way if you search for `AAAA`?

Does it fail same way if you search for digit or `AAAA` when in another locale?

Is answer #3 accessible?

Is it assigned to an existing category?

Does it have translation in locale you're in?

Maybe one of parent categories don't have translation in this locale?

Sorry for so many questions, but I'm having a hard time to reproduce it.

**Comment by MrGeneration** [comment] 2020-08-05 11:09
I can't reproduce it as well as of now. :-x

No matter if searching for a single digit or several ones. No matter of numbers or laters, available by search or not.

**Comment by YosefAdPro** [comment] 2020-08-05 11:37
I use a knowledge base in Hebrew and I also had English (not in use) under Management> Knowledge Base.
I deleted the English and the phenomenon disappeared.
![image](https://user-images.githubusercontent.com/11810187/89408625-4a653880-d729-11ea-845a-64305745d0dd.png)

**Comment by mantas** [comment] 2020-08-05 11:40
@YosefAdPro good to know!

@MrGeneration don't close this issue, I'll try to reproduce it and track down the 🐛

**Comment by YosefAdPro** [comment] 2020-08-05 11:50
@mantas 
I think I understood what the cause was.
When I add an English translation to an article in Hebrew, but do not add a translation to the category the problem occurs.

**Comment by YosefAdPro** [comment] 2020-08-05 11:51
I went through all the options and you were right.

> Maybe one of parent categories don't have translation in this locale?

**Comment by mantas** [comment] 2020-08-05 11:59
@YosefAdPro thank you! I'll look into preventing this issue in the future.

**Closed as completed** 2020-10-19 09:58 UTC
Labels: bug, search, verified, knowledge base
