### ISSUE TITLE
Triggers referencing deleted attributes cannot be edited

### ISSUE THREAD

**Issue by drbw** [zammad/zammad#3280] opened 2020-11-12 16:53 UTC
### Infos:

* Used Zammad version: 3.5.0
* Installation method (source, package, ..): Docker
* Operating system: CentOS 7
* Database + version: Postgres 9.6
* Elasticsearch version: 7.9.3
* Browser + version: Firefox 82.0.2

### Steps to reproduce the behavior:

* Create a new input attribute abcd on a user or organization object and restart Zammad
* Create a trigger "When user.abcd contains efgh then create note ijkl" or similar
* Delete the newly created attribute and restart Zammad
* Click the newly created trigger

### Expected behavior:

* The trigger can be opened
* The trigger cannot be saved any more until the invalid reference is cleared

### Actual behavior:

* Clicking the trigger has no effect
* Suprisingly, it doesn't seem to throw any errors in the logs, either, it just does nothing
* After a major restructuring of our custom attributes, this requires us to create all of our existing triggers from scratch, requiring a lot of work vs. a few minutes of selecting the correct fields as they are now.

### Notes

* At least automations are affected by the same bug, potentially everything that can reference custom fields (we didn't have such references elsewhere)

Yes I'm sure this is a bug and no feature request or a general question.

Although I would appreciate pointers on how to work around this, saving us the required work.

**Comment by MrGeneration** [comment] 2020-11-12 16:54
Duplicate of #2560

**Closed as completed by MrGeneration** 2020-11-12 16:54 UTC
Labels: duplicate

**Comment by drbw** [comment] 2020-11-12 16:56
Oops, sorry - it wasn't clear to me that this was what that issue was about from the title.

**Comment by MrGeneration** [comment] 2020-11-12 16:57
No worries.
It technically doesn't matter if you deactivate or remove the object in question, it breaks triggers and similar functions in the same way.
