### ISSUE TITLE
using checklist template causes checklist items reordering when the items get marked as done for the first time

### ISSUE THREAD

**Issue by Skaryl** [zammad/zammad#5414] opened 2024-11-15 10:01 UTC
### Used Zammad Version

6.4

### Environment

- Version: 6.4.0-1731532686.9edee425.bookworm

### Actual behaviour

checklist items from a checklist template get pushed to the end of the list if marked as done for the first time

### Expected behaviour

checklist items stay at their predefined position and can only be reordered manually

### Steps to reproduce the behaviour

1. create a checklist template with multiple items (A|B|C)
2. add this list to a ticket
3. check item (A) as done an it gets pushed to the end -> (B|C|A)

4. check item (C) as done, it get's reodered -> (B|A|C)

5. uncheck the item (A)
6. check (A) as done again, now it doesn't get reordered

7. check item (B) as done, it gets reordered -> (C|A|B))

no further reordering will happen here, as every item was reordered already once

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment] 2024-11-15 11:10
Very strange. I cannot reproduce it. Which database are you using - mysql or postgres? Do you reload browser between steps?

Just to make sure - all those steps are carried out via UI, not API?

**Comment by fliebe92** [comment] 2024-11-19 14:58
@Skaryl ping, maybe you can attach a screencast.

**Comment by Skaryl** [comment] 2024-11-21 16:11
sorry, got so much to do, so i had no time to reply earlier

All steps are carried out via UI, not API.
A screencast isn't possible directly from work, cause I don't have recording software on my system and due to group policies I can't install it
will try to add a screencast using my personal notebook

i didn't reload the browser between the steps.

if I reload the browser after adding a list from a checklist template, this strange bug doesn't happen
the used browser is edge version 130.0.2849.89 (official build) (64bit)

**Comment by mantas** [comment] 2024-11-22 15:37
@Skaryl thank you for your response! Could you try if you can reproduce on a different browser too? For example Firefox or Chrome?

**Comment by Skaryl** [comment] 2024-11-25 09:53
Our zammad testing server is not accessible from the internet and our productive version is 6.3.1.
So I'm stuck with only edge as possible browser for the time being.
For the same reason I failed to get a working screencast, as I wasn't able to access the testing-server directly from my private computer at home. Logging into our company network and then into the 6.4 server just didn't work with screen recording.

I'll test this again, once our productive zammad is updated. I can't give an estimation when this will be done though.

**Comment by fliebe92** [comment] 2024-11-25 10:13
> I'll test this again, once our productive zammad is updated. I can't give an estimation when this will be done though.

Thanks for your answer, @Skaryl! For the time being, I will close this issue because we're simply not able to reproduce it at all. Feel free to provide us with more information here, and we're more than happy to re-open this one. Thanks for your time and your understanding!

**Closed as not planned by fliebe92** 2024-11-25 10:13 UTC
Labels: waiting for feedback, needs verification
