### ISSUE TITLE
Zendesk migration fails due to custom ticket field having question mark symbol in its name

### ISSUE THREAD

**Issue by shopblocks** [zammad/zammad#3312] opened 2020-11-29 14:37 UTC
This is related to #3310 and #3311 - see #3310 for details of Zammad version number and OS.

In this case the zendesk migration failed with the following error:

```
Problem with ObjectManager Attribute 'domaintransferrequired?': Validation failed: Name Only letters from a-z because numbers from 0-9 and _ are allowed
```

In our Zendesk account this field is called "Domain Transfer Required?". On a sidenote, this field is deactivated in Zendesk but it seems Zammad still brings these across. A workaround for this issue is to fully delete the ticket field in Zendesk, which in our case is possible because we're not using the field anymore.

**Comment by MrGeneration** [comment] 2020-11-29 14:53
The following characters are supported by Zammad:
`[a-Z]` and `_`.

This is a duplicate of #3310

The workaround is to rename or delete the fields.

**Closed as completed by MrGeneration** 2020-11-29 14:53 UTC
Labels: duplicate
