### ISSUE TITLE
No error/warning message if Agent tries to send e-mail reply that is larger than max. e-mail size.

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2342] opened 2018-11-12 16:46 UTC
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: 
* Elasticsearch version: 
* Browser + version: Firefox

### Expected behavior:

* Agent receives warning message if he tries to send an e-mail with attachments that is higher than the configured max. e-mail size.

### Actual behavior:

* Agent does not receive any notification and believes the customer received the answer as the history log shows e-mail sent.

### Steps to reproduce the behavior:

* Have sendmail set up for sending mails (SMTP setup untested)
* Reply to customer
* Attach file that is higher than allowed max. e-mail size value
* Update ticket
* No warnings or error issued to Agent, sendmail never receives e-mail from Zammad for sending.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2018-11-12 17:21
This is a duplicate of #2092

Thanks for posting! We're on it already. :)

**Closed as completed by MrGeneration** 2018-11-12 17:21 UTC
Labels: duplicate
