### ISSUE TITLE
NoMethodError Can't process email

### ISSUE THREAD

**Issue by visiondimension** [zammad/zammad#687] opened 2017-01-30 15:09 UTC
We have issues fetching mails more and more, how can we fix it?

------snip-----
E, [2017-01-30T16:03:11.873053 #29295] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//aaeb3202515a5476dc999328a90bb00f.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2017-01-30T16:03:11.873205 #29295] ERROR -- : ERROR: #<NoMethodError: undefined method `strip!' for nil:NilClass>
E, [2017-01-30T16:03:11.873336 #29295] ERROR -- : ERROR: ["/opt/zammad/app/models/channel/email_parser.rb:111:in `rescue in parse'", "/opt/zammad/app/models/channel/email_parser.rb:104:in `parse'", "/opt/zammad/app/models/channel/email_parser.rb:413:in `_process'", "/opt/zammad/app/models/channel/email_parser.rb:389:in `process'", "/opt/zammad/app/models/channel/driver/imap.rb:194:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:90:in `eval'", "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:56:in `loop'", "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"]
-----snap-----

### Infos:

* Used Zammad version: 1.2.0
* Operating system: centos 7

**Comment by martini** [comment] 2017-01-30 15:16
Hi @visiondimension 

can you attach the file located under tmp/unprocessable_mail/aaeb3202515a5476dc999328a90bb00f.eml to this issue?

In case you need to keep is secret, just send it to your support at zammad dot com address.

 -Martin

**Comment by visiondimension** [comment] 2017-01-30 15:29
Hallo Martin

sorry, already deleted but here is the next mail, also not processable


E, [2017-01-30T16:26:34.516527 #1193] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//d6e167204f7200e116982bc2e7b0fcb2.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2017-01-30T16:26:34.516679 #1193] ERROR -- : ERROR: #<NoMethodError: undefined method `strip!' for nil:NilClass>
E, [2017-01-30T16:26:34.516827 #1193] ERROR -- : ERROR: ["/opt/zammad/app/models/channel/email_parser.rb:111:in `rescue in parse'", "/opt/zammad/app/models/channel/email_parser.rb:104:in `parse'", "/opt/zammad/app/models/channel/email_parser.rb:413:in `_process'", "/opt/zammad/app/models/channel/email_parser.rb:389:in `process'", "/opt/zammad/app/models/channel/driver/imap.rb:194:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:90:in `eval'", "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:56:in `loop'", "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"]
I, [2017-01-30T16:26:34.756286 #1193]  INFO -- : done






Best Regards
 
Michael Hoffmann

**Comment by martini** [comment] 2017-01-30 15:33
Dear @visiondimension 

> sorry, already deleted but here is the next mail, also not processable

For us it's important to get the issue reproducible. So can you attach this second unprocessable mail to this issue? Otherwise we can't help you!

 -Martin

**Comment by visiondimension** [comment] 2017-01-30 15:35
pls check last mail, it was attached


here again..

**Comment by martini** [comment] 2017-01-30 15:37
Sorry, I can't see an attachment. I guess github is not adding it to the issue.

**Comment by visiondimension** [comment] 2017-01-30 15:40
ok, sent to  support at zammad dot com now


Best Regards
 
Michael Hoffmann

**Comment by martini** [comment] 2017-01-30 15:57
@visiondimension I got the mail. It got processed without any issue.

Can I get the log/production.log too? Would also remote login possible?

 -Martin

**Comment by visiondimension** [comment] 2017-01-30 16:06
sent by mail ...

**Comment by martini** [comment] 2017-01-31 08:00
As discussed today via teamviewer. The issue was not a bug.

**Comment by martini** [comment] 2017-01-31 14:36
Note: The problem was a plesk server which adds to all emails headers like:

```
Authentication-Results: server227.dnsdomain.de;\r\r\n
  dkim=none (not signed) header.i=me@example.com\r\r\n
```

Which breaks the email processing.

**Comment by visiondimension** [comment] 2017-01-31 14:46
Martin, thanks a lot for your fantastic Support!!

**Comment by visiondimension** [comment] 2017-01-31 14:47
also plesk now has detected this issue and will fix it this week: https://talk.plesk.com/threads/email-corruption-on-outlook-when-dkim-enabled-on-server.341405/

**Comment by martini** [comment] 2017-01-31 15:21
@visiondimension thanks for feedback! So we will not include a fix into Zammad, since the issue is also on other mail clients and will be fixed soon.

**Closed by martini** 2017-01-31 15:21 UTC
Labels: wontfix
