### ISSUE TITLE
Feature: Responsive Design?

### ISSUE THREAD

**Issue by M0BI0S** [zammad/zammad#307] opened 2016-10-26 07:49 UTC
Responsive Design:
I have tried to view Zammad via iPhone6 and iPad Air2. I was left under the impression, that responsive design is not implemented yet. With the iPhone it seemed to be unusable and with the iPad just about. 
Have I overlooked something or will this be part of a future feature?

Coming from OTRS, I really like the fresh approach of Zammad and I feel that such a System (targeted at small - middle sized companies approx. 25 users in Zammad,- did I get this right?) would need to be on par with today´s user  habits using mobile devices.

**Comment by monotek** [comment] 2016-10-26 08:07
Duplicate of https://github.com/zammad/zammad/issues/223

**Closed** 2016-10-26 08:08 UTC
