### ISSUE TITLE
Layout problems in Restart Warning

### ISSUE THREAD

**Issue by vic-t** [zammad/zammad#3201] opened 2020-09-18 11:52 UTC
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04
* Browser + version: Edge

### Description:

After making a change to the user object, I get the following message about Zammad needing a restart: 

![image](https://user-images.githubusercontent.com/13408858/93594451-22b6f080-f9b6-11ea-91dd-baa71c64568f.png)

I guess there are some minor formatting problems.

**Comment by mantas** [comment] 2020-09-18 11:54
Duplicate of https://github.com/zammad/zammad/issues/3171 :)

**Closed as completed by mantas** 2020-09-18 11:54 UTC
Labels: duplicate
