### ISSUE TITLE
Can't login anymore / Couldn't find Overview id

### ISSUE THREAD

**Issue by ntinti** [zammad/zammad#375] opened 2016-11-07 18:49 UTC
Suddenly I can't login again. Message at the top of the site: "Couldn't find Overview with 'id'=14"

Indeed there is no overview with that id in the database. I've played a litte bit with a new overview, maybe I delete it in zammad gui.

Delete and disabled cache and delete all cookies doesn't solve the problem 

After cloning a row of the overview table and give it the id 14 login is possible again ... (???)

**Comment by martini** [comment] 2016-11-07 18:52
Hi @ntinti a way how to reproduce would be fine. Without that I can't help.

-> Also remote login would be a option.

**Comment by ntinti** [comment] 2016-11-07 18:52
And now I can see there is a ticket in that overview ...
That means I can delete an overview with a related ticket and after the I can't login anymore ?

**Comment by martini** [comment] 2016-11-07 18:53
You can delete/create/update overviews anytime without any issue.

Just tell me how to reproduce this behaviour.

**Comment by ntinti** [comment] 2016-11-07 19:15
I've changed the eMail address of the related ticket-customer too. 

Maybe that are the steps:
1) Make overview with rule customer is specific customer = a@b.c
2) change email address of that customer that is in the database to x@y.z
3) delete overview

**Comment by ntinti** [comment] 2016-11-07 19:21
Now the overview is empty. But if I delete it now, I can't login again ...  "Couldn't find Overview with 'id'=14" - same procedure, I had to put a row with id 14 manually in the table to login.

**Comment by ntinti** [comment] 2016-11-07 19:34
With debug on, I see many of such queries. But the table "overviews_users" is completely empty (?)

`D, [2016-11-07T20:26:54.384786 #70129] DEBUG -- :    (0.1ms)  SELECT `users`.id FROM `users` INNER JOIN `overviews_users` ON `users`.`id` = `overviews_users`.`user_id` WHERE `overviews_users`.`overview_id` = 6
D, [2016-11-07T20:26:54.453649 #70129] DEBUG -- : client(17316718540) push overview_list all_escalated for user 3
D, [2016-11-07T20:26:54.456879 #70129] DEBUG -- :    (0.1ms)  SELECT `users`.id FROM `users` INNER JOIN `overviews_users` ON `users`.`id` = `overviews_users`.`user_id` WHERE `overviews_users`.`overview_id` = 9
D, [2016-11-07T20:26:54.457587 #70129] DEBUG -- :    (0.1ms)  SELECT `users`.id FROM `users` INNER JOIN `overviews_users` ON `users`.`id` = `overviews_users`.`user_id` WHERE `overviews_users`.`overview_id` = 9
D, [2016-11-07T20:26:54.552361 #70129] DEBUG -- : client(17316718540) push overview_list my_closed_tickets for user 3
D, [2016-11-07T20:26:54.561250 #70129] DEBUG -- :    (0.2ms)  SELECT `users`.id FROM `users` INNER JOIN `overviews_users` ON `users`.`id` = `overviews_users`.`user_id` WHERE `overviews_users`.`overview_id` = 11
D, [2016-11-07T20:26:54.561902 #70129] DEBUG -- :    (0.1ms)  SELECT `users`.id FROM `users` INNER JOIN `overviews_users` ON `users`.`id` = `overviews_users`.`user_id` WHERE `overviews_users`.`overview_id` = 11
D, [2016-11-07T20:26:54.639880 #70129] DEBUG -- : client(17316718540) push overview_list internal for user 3
D, [2016-11-07T20:26:54.645757 #70129] DEBUG -- :    (0.1ms)  SELECT `users`.id FROM `users` INNER JOIN `overviews_users` ON `users`.`id` = `overviews_users`.`user_id` WHERE `overviews_users`.`overview_id` = 14
D, [2016-11-07T20:26:54.646409 #70129] DEBUG -- :    (0.1ms)  SELECT `users`.id FROM `users` INNER JOIN `overviews_users` ON `users`.`id` = `overviews_users`.`user_id` WHERE `overviews_users`.`overview_id` = 14`

**Comment by ntinti** [comment] 2016-11-07 19:48
Maybe my two issues today belong together. There is another overview id, that is not found, id 10.
After 10 of that errors  the scheduler stops working

I will put overview id 10 also manual in the table and wait what happens

E, [2016-11-07T20:25:52.386040 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:26:18.091043 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:26:43.822515 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:27:09.628387 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:27:35.209097 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:28:01.051929 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:28:26.759952 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:28:52.447153 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:29:18.232980 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:29:44.145411 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>

**Comment by ntinti** [comment] 2016-11-07 19:50
Sorry:
`E, [2016-11-07T20:25:52.386040 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:26:18.091043 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:26:43.822515 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:27:09.628387 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:27:35.209097 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:28:01.051929 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:28:26.759952 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:28:52.447153 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:29:18.232980 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>
E, [2016-11-07T20:29:44.145411 #70129] ERROR -- : thread_client 17316718540 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=10>`

**Comment by ntinti** [comment] 2016-11-07 20:02
I can't believe - next overview id isn't found. ( I don't play with overviews the last hours). After 10 attempts the scheduler stops working...

`E, [2016-11-07T20:43:28.846520 #69045] ERROR -- : Couldn't find Overview with 'id'=13
E, [2016-11-07T20:43:34.490356 #69045] ERROR -- : Couldn't find Overview with 'id'=13
E, [2016-11-07T20:44:29.107196 #69045] ERROR -- : Couldn't find Overview with 'id'=13
E, [2016-11-07T20:46:25.062823 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:46:51.017250 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:47:17.079814 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:47:42.059405 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:48:08.081449 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:48:34.021068 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:48:59.179013 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:49:24.222305 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:49:50.305885 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:50:16.271426 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>`

**Comment by ntinti** [comment] 2016-11-07 20:09
Because I've deleted overviews, the ids were not continuously. Is this a possible reason?
I've put another dummy overview in the table so that all ids from 1 to 15 (my last one) are present. I will test if that helps with the scheduler.

**Comment by ntinti** [comment] 2016-11-07 20:49
After inserting dummy overviews direct in the table overviews with id numbers that are filling the sequence unto my last id number there are no more errors, the scheduler is working. 
I suppose the reason that I can't login, was that the missing overview with id 14 was also present in the left (black) menu that is combined with my user-id. Is this possible?

**Comment by martini** [comment] 2016-11-07 22:04
@ntinti can I get remote login to your instance? I can't follow the questions/what's happen.

**Comment by martini** [comment] 2016-11-07 22:05
Seems to be the same issue https://github.com/zammad/zammad/issues/374#issuecomment-258970292

**Comment by martini** [comment] 2016-11-08 13:08
Duplicate of #374

**Closed by martini** 2016-11-08 13:08 UTC
Labels: duplicate
