### ISSUE TITLE
Feature request: automation with specific mail recipient

### ISSUE THREAD

**Issue by chrstmnn** [zammad/zammad#2428] opened 2019-01-11 10:54 UTC
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..):
* Operating system: centOS
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* Create new automation with action that sends an e-mail. 
* Add recipient of e-mail or specific mailadress.

### Actual behavior:

* Create new automation with action that sends an e-mail. 
* Select Group or customer that receives the mail.

**Comment by MrGeneration** [comment] 2019-01-11 16:45
Hello,

thanks for your time to fill in this issue, Unfortunately this is not a bug, but a feature request.
Please post feature requests over at our community: https://community.zammad.org

Closing now.

**Closed as completed by MrGeneration** 2019-01-11 16:45 UTC
Labels: question
