### ISSUE TITLE
Scheduler on high load leads to HTML processing issue

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4260] opened 2022-09-19 15:32 UTC
### Infos:

* Used Zammad version: 5.2.2
* Installation method (source, package, ..): any 
* Operating system: any
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any 
* Ticket: #10114725

### Expected behavior:

* All E-Mails should be displayed regularly as articles.  

### Actual behavior:

* In case of high load on the scheduler, sanitizing a HTML email can take so log (>180 seconds) that the scheduler stops processing the article and thus it is displayed the following way: 

`"This message cannot be displayed due to HTML processing issues. Download the raw message below and open it via an Email client if you still wish to view it."      `

### Steps to reproduce the behavior:

* Receive and view a long HTML email article while the scheduler is on high load. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-09-21 09:04
Duplicate of #2706

**Closed as not planned** 2022-09-21 10:10 UTC
Labels: duplicate
