### ISSUE TITLE
Trigger on "Closing Issue"

### ISSUE THREAD

**Issue by GreXXL** [zammad/zammad#1938] opened 2018-04-10 12:46 UTC
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): RPM
* Operating system: Ubuntu
* Database + version: bundled
* Elasticsearch version:
* Browser + version: Safari 11.0.2

### Expected behavior:

* Trigger on Issue "Close" should send email

### Actual behavior:

* Trigger for "Close" not working properly / not action

### Steps to reproduce the behavior:

* Either Close a ticket manually
* Or sent a ticket to "pending close" and let it be closed automatically

![bildschirmfoto 2018-04-10 um 14 43 14](https://user-images.githubusercontent.com/1630413/38557588-cd042ede-3ccd-11e8-8e42-7576145ece11.png)

I tried "State is closed" which has no effect.
Then I changed to "Closed at updated" - then the form gets red for no apparent reason (might be a second issue after all)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment] 2018-04-10 13:07
Hi @GreXXL 

can you try it with the following condition?

1) Action: update
2) ticket.state: closed

Then it should work/trigger should get executed. If that is working for you, you can extend it with additional conditions like tags.

PS: article.type is email means that the trigger is only executed if the ticket got closed with an email. IMO this will not fit here.

**Comment by victorcezario** [comment] 2018-04-10 20:59
Hi @GreXXL !
Try using this setting, I'm currently using it and it works fine!
![image](https://user-images.githubusercontent.com/19748477/38583248-d05830d8-3ce8-11e8-95e0-3ed8c5daf960.png)

**Comment by GreXXL** [comment] 2018-04-21 12:45
This makes no change for me. Tried with only state = closed and it still will not send the mail.
@martini can I contribute anything else so you can track this issue?

**Comment by thorsteneckel** [comment] 2018-05-09 18:39
Hi @GreXXL - can you please setup Zammad instance over at https://zammad.com/getting-started and post the name of the instance here afterwards? This will help us on finding the cause and reproduce the issue. Thanks!

**Comment by GreXXL** [comment] 2018-05-12 19:31
Hm. Thanks tried that and it worked. I revisited my configuration and got it to work (with the latest patch level) on my instance as well. So https://test-1938.zammad.com/ is unnecessary. The only thing that still would be cool is if you could select which channel types this should be for (type is only for the last update as mentioned)

**Comment by thorsteneckel** [comment] 2018-05-13 09:27
Hi @GreXXL - Thanks for your feedback. I'll close this one here since it's resolved.

Regarding your "channel types" point: Zammad Tickets are not limited to one channel. So you can have an incoming Tweet and over time you could switch over to e.g. Email. So this would be a mixed-channel Ticket. 
What do you think on how should Zammad act in this situation? Feel free to move this discussion over to our [community board](http://community.zammad.org/) and mention me directly. Thanks!

**Closed by thorsteneckel** 2018-05-13 09:27 UTC
Labels: bug, needs verification
