### ISSUE TITLE
SMIME decrypt failed when e-mail is signed and send from Microsoft Outlook

### ISSUE THREAD

**Issue by urbantrooper** [zammad/zammad#3734] opened 2021-09-10 14:53 UTC
### Infos:

* Used Zammad version: 4.1.0
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.2.24
* Elasticsearch version: 7.14
* Browser + version: doesn't matter

### Expected behavior:

* Encrypted and signed e-mails send from Microsoft Outlook should be decrypted with the private key stored under system/integration/smime
![image](https://user-images.githubusercontent.com/87754194/132872276-8a8a6338-0fd5-4b9b-9e30-6cbead42490b.png)

### Actual behavior:

* If a customer send an e-mail encryted and signed from Microsoft Outlook (2013, 2016) to zammad, the e-mail can't be decrypted although the private key is stored
![image](https://user-images.githubusercontent.com/87754194/132872490-fd52b457-bae1-4974-9958-9365615ce9a7.png)
* If a customer send an e-mail encryted and not signed to zammad, the e-mail will be decrypted
* We have the problem with our users here on site and with our customers
* The strange thing is, emails decrypted and signed from Mozilla Thunderbird are decrypted in zammad without any issues

**Comment by MrGeneration** [comment] 2021-09-10 14:55
Duplicate of #3705

**Closed as completed by MrGeneration** 2021-09-10 14:55 UTC
Labels: question

**Comment by MrGeneration** [comment] 2021-09-10 15:38
Sorry my bad, not a duplicate but a technical question. 🙀
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
