### ISSUE TITLE
The navigation arrows randomly disappear while I switch from one ticket to another within an overview.

### ISSUE THREAD

**Issue by kingmanfri** [zammad/zammad#5293] opened 2024-08-08 08:00 UTC
### Used Zammad Version

6.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Selecting a view from those available in 'Overviews' and choosing a ticket, if I change tickets using the navigation arrows in the top right corner...
![navigating arrows](https://github.com/user-attachments/assets/0ebc4bcb-9881-4117-b9c9-c19fbe4767b0)

after a while, the navigation arrows randomly disappear (without necessarily reaching the last ticket).
![navigating arrows disapper](https://github.com/user-attachments/assets/9f06b0da-ce3b-41d3-9a82-d7a776ac5a1b)

### Expected behaviour

I expect that while navigating through different tickets within an overview, the navigation arrows should not randomly disappear. It doesn’t always happen, but I believe it might be a bug.

### Steps to reproduce the behaviour

I click on the 'Overviews' tab in the left menu. I select one of the available views and open a ticket. On the detail page, in the top right corner, I see the navigation arrows (forward and backward; in my case, the backward arrow is disabled because I selected the first ticket in the list). If I click the forward arrow to scroll through the tickets, after a while the arrows disappear.

### Support Ticket

None

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2024-08-09 08:30
Hi @kingmanfri. Could you please be more specific what `after a while` means? Do you perform any other actions in Zammad in the meantime?

I do have an overview with 40+ tickets and can navigate through all tickets, both directions. Works fine.

**Comment by fliebe92** [comment] 2024-08-26 06:47
No feedback, closing for now.

**Comment by kingmanfri** [comment] 2024-09-04 15:28
Sorry, I was on vacation. I’m posting a video showing the behavior of the navigation arrows disappearing. I noticed that closing some items in the left sidebar prevents the issue of the arrows disappearing from reoccurring.

For privacy reasons, I had to obscure the ticket information, but you can see that I am inside an Overview while scrolling through the tickets in the list.
https://github.com/user-attachments/assets/06b43003-2464-4415-ab4f-292546325e4f

**Comment by fliebe92** [comment] 2024-09-11 07:34
Hi @kingmanfri. How many entries do you have in the left sidebar?

**Comment by binsky08** [comment] 2024-09-11 12:51
and could you please answer the "Environment" section of the issue ;)

**Comment by kingmanfri** [comment] 2024-09-16 10:59
I wouldn't know a fixed number of entries where the problem occurs. What I've noticed is that it tends to happen more often when I have a lot of them. Is it related?

**Comment by fliebe92** [comment] 2024-09-16 11:57
> I wouldn't know a fixed number of entries where the problem occurs. What I've noticed is that it tends to happen more often when I have a lot of them. Is it related?

We don't know. Several people tried to reproduce your described behavior, without success.

When it happens on your side, is there any warning or error logged in the browser console? Which browser are you using?

**Comment by MrGeneration** [comment] 2024-09-16 12:07
I have an idea:
Open the ticket and navigate through them with arrows 2-3 times, then send a new mail to the system which appears in the used overview, ideally not on top or bottom of the list and see what happens. I'd bet it's either cause by the list being longer, shorter or adjusted in the mean time. Hard to test, hard to overcome in the current UI I'd bet.

**Comment by binsky08** [comment] 2024-09-16 12:49
When navigating with the buttons, the order always seems to go by creation date, even if the ticket view is sorted differently beforehand (e.g. by name). Newly created tickets (e.g. starting with “g”) are then unfortunately not sorted in the middle but always at the end.

Or is there perhaps a strategy to achieve this?

**Comment by kingmanfri** [comment] 2024-09-18 21:06
> he

No error message. I'm using Google Chrome

**Comment by kingmanfri** [comment] 2024-09-18 21:09
> When navigating with the buttons, the order always seems to go by creation date, even if the ticket view is sorted differently beforehand (e.g. by name). Newly created tickets (e.g. starting with “g”) are then unfortunately not sorted in the middle but always at the end.
> 
> Or is there perhaps a strategy to achieve this?

It's not a matter of ordering tickets.. The point is that navigation arrows in overviews randomly disapper..

**Comment by fliebe92** [comment] 2024-09-27 08:44
Hi @kingmanfri. We spent some time again to investigate this issue, but we're still not able to reproduce it at all. We navigated through an overview with 50+ tickets, both directions (start -> end & end -> start) are working fine without losing the context to the overview.

Without being able to reproduce it and therefore no chance to investigate further, we're closing this issue again.

Feel free to re-open it with clear reproduction steps. We're happy to help in any case then.

Thanks for your understanding.

**Closed as not planned by fliebe92** 2024-09-27 08:44 UTC
Labels: waiting for feedback, needs verification

**Comment by kingmanfri** [comment] 2025-02-27 23:23
Thanks, the fix is actually working for me.
