### ISSUE TITLE
Zammad Chat No JQuery version don't work without button element

### ISSUE THREAD

**Issue by BertrandGouny** [zammad/zammad#2561] opened 2019-05-03 19:33 UTC
### Infos:

* Used Zammad version: 2.9.0

### Expected behavior:
Chat should work if no open button element exists ?

### Actual behavior:

```
Uncaught TypeError: Cannot read property 'classList' of null
    at s.onError (chat-no-jquery.min.js:1)
    at Object.onError (chat-no-jquery.min.js:1)
    at WebSocket.ws.onclose (chat-no-jquery.min.js:1)
```

Problematic line : 
https://github.com/zammad/zammad/blob/2de61bd4c53df469df5838173cc0147447364418/public/assets/chat/chat-no-jquery.js#L745

### Steps to reproduce the behavior:
remove that line :
https://github.com/zammad/zammad/blob/2de61bd4c53df469df5838173cc0147447364418/public/assets/chat/znuny-no-jquery.html#L113

**Comment by MrGeneration** [comment] 2019-05-03 21:48
Please use the complete issue form and describe your problem better. If it helps, you can also use screencasts.

**Comment by BertrandGouny** [comment] 2019-05-04 09:19
@MrGeneration reading the 2 lines of code quoted should be enough for any javascript developer to see that `document.querySelector("." + this.options.buttonClass)` might be null so `document.querySelector("." + this.options.buttonClass).classList.add(this.inactiveClass);` give the error

not sure why you need a screencast for that

**Comment by MrGeneration** [comment] 2019-05-04 12:45
Again: Please do complete the issue template, as it is incomplete.
I will have to close this if it's not completed.

**Comment by mantas** [comment] 2019-05-04 16:07
@BertrandGouny developer here. Knowing which line causes the crash won't tell me how to reproduce the bug.

**Comment by BertrandGouny** [comment] 2019-05-04 16:16
@mantas as stated in "Steps to reproduce the behavior" you can  reproduce the bug by taking back znuny-no-jquery.html example file and removing the dom element with class="open-zammad-chat"

**Comment by mantas** [comment] 2020-01-30 22:49
Closing as this issue seems to be fixed along the way in `develop` branch.

**Closed as completed by mantas** 2020-01-30 22:49 UTC
Labels: bug, chat, verified

**Comment by BertrandGouny** [comment] 2020-01-31 08:13
thanks :)
