### ISSUE TITLE
When Forwarding emails the Attachment is sometimes missing

### ISSUE THREAD

**Issue by lorenzgroup** [zammad/zammad#1789] opened 2018-01-30 16:37 UTC
### Infos:

* Used Zammad version: 2.2
* Installation method (source, package, ..): DEB
* Operating system: Ubuntu16.04.03
* Database + version: Mysql version 5.7.21-0ubuntu0.16.04.1
* Elasticsearch version: 
* Browser + version: Any

### Expected behavior:
When Forwarding an email with an Attachment, the new Email should include the Attachment too

### Actual behavior:
Sometimes the new email is missing the Attchment.
I can´t find any rules or Similarities for the not-includes Attachments.
- Size doesen´t seem to be the Problem ( 96 KB xls does not Work, 112Kb .xls works)
- File extension is not the Problem (We get Mostly .pdf or .xls(x) or .doc(x) Files)
- Upper/lowercase  has no effect
- Switching the File Storage from DB to File had no effect.

MAYBE This Could be an Issue (But Not 100% Verified):
- Blanks within the Filename (Yes, I LOVE Windows Users)
- German "Umlaute" such as Ä,Ö,Ü in the Filename might be an Issue

### Steps to reproduce the behavior:
Forward an email with attachment from Ticket View

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by lorenzgroup** [comment] 2018-02-01 10:40
Update: With Version 2.3X forwaring Emails with "ä,ö,ü" in Attachment Filenames seems to Work.

**Comment by jepf** [comment] 2018-02-06 12:32
Hi @lorenzgroup 

Thank you for reporting this issue.
Could you please provide one of the e-mails with missing attachments? When you click on the article in Zammad there will be a link "E-mail Raw" where you can download the EML file. Can you please send this file to support@zammad.com?

Thank you.

**Comment by martini** [comment] 2018-02-12 07:50
Maybe this is related https://github.com/zammad/zammad/issues/1778 https://github.com/zammad/zammad/commit/8895e878f01cd41a86157e776c6c05fad72bb99c

**Comment by thorsteneckel** [comment] 2018-05-09 18:33
Since there is no feedback in three month I will close this issue. Feel free to provide the needed information on how to reproduce this. Other users please open a new issue. Thanks!

**Closed by thorsteneckel** 2018-05-09 18:33 UTC
Labels: waiting for feedback
