### ISSUE TITLE
SLA overview broken, if custom attribute has been removed

### ISSUE THREAD

**Issue by saz** [zammad/zammad#3796] opened 2021-10-08 06:37 UTC
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): source
* Operating system: Ubuntu 18.04
* Database + version: Postgresql 9.6
* Elasticsearch version: 7.15.0
* Browser + version: Google Chrome 94

### Expected behavior:

* Working SLAs, even if a custom attribute is missing or it's not possible to delete the still-in-use custom attribute

### Actual behavior:

* SLA overview breaks with an error message and won't load
* Making changes on a ticket are broken with a DB error, as the referenced field is missing in the table schema

### Steps to reproduce the behavior:

* Settings => Objects => Ticket => New Attribute
* Add a new attribute and restart Zammad
* Create a new SLA and use the newly created attribute
* Remove the custom attribute, restart Zammad
* Go to Settings => SLAs or make changes to a ticket

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2021-10-08 06:44
Regression of https://github.com/zammad/zammad/issues/3769 ?

**Comment by saz** [comment] 2021-10-08 06:53
Here's the error message I'm seeing (note: this is zammad 5.1.x using docker)
![image](https://user-images.githubusercontent.com/402629/136511565-f5f7070d-102e-47a5-8880-8af6c97adc8a.png)

**Comment by saz** [comment] 2021-10-08 06:55
I'm quite sure, there was a different error message on 5.0.x, but I don't have a copy.
Behavior is still the same on both versions and I think it shouldn't be possible to delete the attribute, if it's in use.

**Comment by MrGeneration** [comment] 2021-10-08 06:56
5.1 is not yet released and the docker container is not stable for production. It looses data upon restart.
In case you missed that part. 🙏

**Comment by saz** [comment] 2021-10-08 07:28
Thanks for the heads up. I'm fully aware of that. It's just for testing purposes, because I can't break production multiple times :smile:

**Comment by mantas** [comment] 2021-10-08 07:33
Looks like this is already solved in `develop`. For some reason the duplicate issue is marked as 5.0, but it didn't make it to 5.0...?

**Comment by thorsteneckel** [comment] 2021-10-08 07:52
Will be available in 5.0.1

**Comment by MrGeneration** [comment] 2021-10-08 09:19
Duplicate of #3769

**Closed as completed by MrGeneration** 2021-10-08 09:19 UTC
Labels: duplicate
