### ISSUE TITLE
Microsoft365/OAuth fails when family name contains utf8 characters

### ISSUE THREAD

**Issue by PSI-RZ** [zammad/zammad#5380] opened 2024-10-24 09:03 UTC
### Used Zammad Version

6.3.1

### Environment

- Installation method: docker
- Operating system (if you're unsure: `cat /etc/os-release` ): 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
- Database + version:  (postgres:${POSTGRES_VERSION:-15.7-alpine})
- Elasticsearch version: (elasticsearch:${ELASTICSEARCH_VERSION:-8.14.3})
- Browser + version: Edge 130.0.2849.46

### Actual behaviour

Zammad reports unknown error when user with special character tries to connect using O365 channel. 

Log from zammad:
zammad-railsserver-1    | E, [2024-10-24T10:46:21.691886#1-1915260] ERROR -- : unexpected token at '{"aud":"a467d96a-1ae6-4402-98e0-86337161528d","iss":"https://login.microsoftonline.com/d4ac9a2f-8451-4de1-89b6-1c84aa9495d3/v2.0","iat":1729759281,"nbf":1729759281,"exp":1729763181,"email":"dvorak.m@xxx.xx","name":"Marek Dvafp�Z�
                                                                                         ��H�����
                                                                                                 ؘ�N
                                                                                                    L
                                                                                                     X�L�M�M�XNXKM
MNH��Y�\��Y�\�\��[YH����ܘZ˛P�K�ވ����                                                                              ��
\\�Q��ML��␦Q\\Ռ                     �T�PS
XNMMYNX��LX�   ������ґ[S���Lњ[�ِPYˈ��X�����X^RY��V�K[ӝ�R���ՙLP��Zێ[Z��[�Y^\�␦���
     �]␦H��������\�^V
                     T�ٙ��X�PH��\������' (JSON::ParserError)
zammad-railsserver-1    | lib/external_credential/microsoft365.rb:285:in `user_info'
zammad-railsserver-1    | lib/external_credential/microsoft365.rb:51:in `link_account'
zammad-railsserver-1    | app/models/external_credential.rb:21:in `link_account'
zammad-railsserver-1    | app/controllers/external_credentials_controller.rb:43:in `callback'
zammad-railsserver-1    | app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
zammad-railsserver-1    | app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
zammad-railsserver-1    | app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
zammad-railsserver-1    | app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
zammad-railsserver-1    | I, [2024-10-24T10:46:21.692606#1-1915260]  INFO -- : Completed 500 Internal Server Error in 446ms (ActiveRecord: 6.3ms | Allocations: 7211)
zammad-railsserver-1    | F, [2024-10-24T10:46:21.692957#1-1915260] FATAL -- :
zammad-railsserver-1    | [520f5b11-76b3-4158-9def-4609f051e8cb] ArgumentError (invalid byte sequence in UTF-8):
zammad-railsserver-1    | [520f5b11-76b3-4158-9def-4609f051e8cb]

### Expected behaviour

User even with special character (like ěščřžýáíéůú) should be able to connect theirs account to O365 channel. 

### Steps to reproduce the behaviour

Add user with special character in name. Like Marek Dvořák. 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment] 2024-10-24 09:08
Do you mean the third party authentication via M365 or the configuration of the email channel for M365? Maybe you can add some better steps to reproduce.

**Comment by PSI-RZ** [comment] 2024-10-24 09:20
I mean configuration of email channel for M365 (https://admin-docs.zammad.org/en/latest/channels/microsoft365/index.html?highlight=microsoft%20365). 

Connection of other accounts from same domain is working without any issue. Problem is with user whose name contains special character - **ř**. 

**How to reproduce**
Try to add email of user whose name contains special character to email channel M365.

**Comment by rolfschmidt** [comment] 2024-10-28 11:43
We tried to create a test email address with the family name **Dvořák**, but there were no issues while linking the MS365 account. Without any reproducibility it is hard to fix it.

I have a guess what the cause could be, this could be the cause:
```diff
diff --git a/lib/external_credential/microsoft365.rb b/lib/external_credential/microsoft365.rb
index d6c7c00116..feed00c386 100644
--- a/lib/external_credential/microsoft365.rb
+++ b/lib/external_credential/microsoft365.rb
@@ -282,7 +282,7 @@ class ExternalCredential::Microsoft365
     split = id_token.split('.')[1]
     return if split.blank?

-    JSON.parse(Base64.decode64(split)).symbolize_keys
+    JSON.parse(Base64.decode64(split).force_encoding('UTF-8')).symbolize_keys
   end
```

If you are fit with docker you could try to edit the file and restart the rails server and see if it helps. Else we would more infos, how to reproduce the issue, not sure how we could proceed here.

**Comment by fliebe92** [comment] 2024-10-29 12:12
@PSI-RZ ping, not sure if you got the notification from yesterday.

**Comment by PSI-RZ** [comment] 2024-10-29 12:23
I will try to test this week and let you know how it goes.

**Comment by fliebe92** [comment] 2024-11-01 19:38
@PSI-RZ > Any news?

**Comment by PSI-RZ** [comment] 2024-11-05 08:45
I tried the change you suggested, but it didn't work. I've managed to change the user name in azure from Marek Dvořák to Marek Dvorak and it works.

**Comment by fliebe92** [comment] 2024-11-12 20:35
We're closing this issue for now, because there is a workaround available, and we are still not able to reproduce it, hence we cannot investigate it even further.

Feel free to ping us here when you do have more information available.

**Closed as not planned by fliebe92** 2024-11-12 20:35 UTC
Labels: can't reproduce
