### ISSUE TITLE
IMAP Wrong max message size - 0.0 MB

### ISSUE THREAD

**Issue by Schack17** [zammad/zammad#766] opened 2017-02-16 08:11 UTC
[production.txt](https://github.com/zammad/zammad/files/779413/production.txt)

### Infos:
Zammad don't receive e-mails from imap/pop account.
After deactivating the mail account in zammad a red box shows the error message:
ignore message 1/2 - because message is too big (is:0.008173942565917969 MB/**max:0.0 MB**)

The max size is set to 10 MB...

* Used Zammad version:  1.3 (clean with Docker-compose)
* Operating system: docker 1.13.1 on Ubuntu 14.04.5 LTS
* Browser + version: Chrome 56.0.2924.87 / Firefox 53.0a2 64-Bit Dev Edition

### Expected behavior:
Fetch mails

### Actual behavior:
No mails

### Steps to reproduce the behavior:
* Clean docker-compose-installation
* Configure a imap account with ssl 993

**Comment by Schack17** [comment] 2017-02-16 08:19
After a zammad restart it works. Seems to be only a problem with the first start.

**Comment by thorsteneckel** [comment] 2017-02-16 08:27
This might be a duplicate of #751 ... keep investigation.

**Comment by thorsteneckel** [comment] 2018-01-03 08:49
Hi @Schack17 - we can't reproduce this issue and apparently it didn't happen anymore. Closing for now. Everybody feel free to provide further information on how to reproduce.

**Closed by thorsteneckel** 2018-01-03 08:49 UTC
Labels: can't reproduce, wontfix
