### ISSUE TITLE
Failed to fetch https://deb.packager.io/gh/zammad/zammad/dists/xenial/stable/binary-amd64/Packages  Writing more data than expected (7831 > 2237)

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1341] opened 2017-08-11 13:58 UTC
### Infos:

* Used Zammad version: 
```
# apt policy zammad
zammad:
  Installed: 1.5.0-1500642196.6db156e.xenial
  Candidate: 1.5.0-1500642196.6db156e.xenial
  Version table:
 *** 1.5.0-1500642196.6db156e.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
        100 /var/lib/dpkg/status
     1.5.0-1500564396.df8b055.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1500455354.da1ce36.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1500447589.61d19ab.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1500378755.2c8ae4a.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
```
* Operating system: Ubuntu 16.04.2 LTS

### Expected behavior:
`apt update` working.

### Actual behavior:
When I do `apt update` I get:
```
# apt update
[...]
Ign:9 https://deb.packager.io/gh/zammad/zammad xenial InRelease                    
Ign:12 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
Err:12 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
  Writing more data than expected (7831 > 2237)
Fetched 1,339 kB in 2s (636 kB/s)
Reading package lists... Done
E: Failed to fetch https://deb.packager.io/gh/zammad/zammad/dists/xenial/stable/binary-amd64/Packages  Writing more data than expected (7831 > 2237)
E: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by martini** [comment] 2017-08-11 13:59
Hi @passboltUser 

what ist the content of your Zammad repo file?

`cat /etc/apt/sources.list.d/zammad.list`

 -Martin

**Comment by passboltUser** [comment] 2017-08-11 14:01
```
# cat /etc/apt/sources.list.d/zammad.list
deb https://deb.packager.io/gh/zammad/zammad xenial stable
```

**Comment by martini** [comment] 2017-08-11 14:08
Thanks, you need to update it. https://docs.zammad.org/en/latest/appendix-repo-file.html

It's also as headline on https://zammad.org

**Comment by martini** [comment] 2017-08-11 14:09
It's a duplicate of https://github.com/zammad/zammad/issues/1294

**Closed by martini** 2017-08-11 14:09 UTC

**Comment by passboltUser** [comment] 2017-08-11 14:13
Thanks, works.
