### ISSUE TITLE
Safari IOS - Input not visible while typing

### ISSUE THREAD

**Issue by highree** [zammad/zammad#661] opened 2017-01-23 12:50 UTC
* Used Zammad version:  Latest
* Operating system: Debian
* Browser + version: Safari IOS Latest

### Expected behavior:
chat should go up when enter a message.

### Actual behavior:

input field not visible

### Steps to reproduce the behavior:

Open Chat on ios Safari

**Comment by thorsteneckel** [comment] 2017-01-24 08:11
Hi @highree - our iOS focus is currently on the implementation of an native client. Therefore this issue has a lower priority. We'll announce the native app in our release notes.

**Comment by thorsteneckel** [comment] 2018-06-22 14:58
Duplicate of #223. Closing.

**Closed by thorsteneckel** 2018-06-22 14:58 UTC
Labels: UX/UI, browser, chat
