### ISSUE TITLE
Email - full quote time specification

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#1426] opened 2017-09-16 11:06 UTC
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: source
* Operating system: CentOS 7
* Browser + version: Firefox 55.0.3

### Expected behavior:
Time when creating the article about the quote, as in OTRS 
for example: 

16.09.2017 13:06 - Firstname Lastname wrote:
>Quote
* 

### Actual behavior:
Only the last article is cited. No time is displayed above the quote to create the article.
* 

### Steps to reproduce the behavior:
Ticket > Settings > Email - full quote > yes
Reply to an item in the ticket
*

**Comment by dsukhin** [comment] 2018-04-27 02:55
Also agree this should be done. It looks like this is the commit (https://github.com/zammad/zammad/commit/bd061fb5c1d4c63f064dccfe0d92016c1c3ba1c2) where the original support was added for full history quotes. 

I am still getting familiar with the code base but it seems it should be easy enough to add the date and customer name/email to the front of the "selected" variable somewhere after line 411 in app/assets/javascripts/app/controllers/ticket_zoom/article_actions.coffee at the commit above. Documenting this here for myself or anyone else who wants to help.

As soon as I figure out where/how the customer/ticket/sender attributes are accessed/stored in that file, I'll add something with the following format:

**Comment by KoJie** [comment] 2018-08-02 08:51
This is a feature request from one of our Zammad support customer (T#1024308).

***Current behavior:***
You can forward an E-mail sent from Zammad within Zammad.
 
This currently looks like this:

---Begin forwarded message:---

Hello Mr. xxx,
.....


 
***Expected behavior:***
The date and time of the original mail should be listed in the forwarded mail (similar to forwarding a mail from a usual mail program)

This would look like this:

 "Zammad Support Team" <enjoy@zammad.com>> wrote on Monday, July 23, 2018 at 11:01 AM:
---Begin forwarded message:---

Hello Mr. xxx,
…

**Comment by martini** [comment] 2018-08-28 14:13
"read more" is broken now

Just reply to an customer where you quote the customer message.

<img width="621" alt="screen shot 2018-08-28 at 08 32 11" src="https://user-images.githubusercontent.com/110226/44728560-1dd82900-aadd-11e8-9cfd-4d6fa38883d2.png">

Zammad will identify the new quote feature as position to add the "read more" feature. Which makes no sense in this use case.

**Comment by dsukhin** [comment] 2018-08-28 15:14
Hey @martini, I'm curious what you think the correct behavior should be? I think it makes sense that the "on Tuesday...." portion is quoted as meta data and part of the old message that you replied to. That portion is quoted on Apple mail for example as well as other mail clients that include it.

**Comment by martini** [comment] 2018-08-28 15:50
A user just want to see the own message which was created by the agent and sent to the customer. And not a "see more" option. 

On apple mail if I go to the sent folder I also can read my now messages without press "see more".

<img width="691" alt="screen shot 2018-08-28 at 17 48 59" src="https://user-images.githubusercontent.com/110226/44734635-b1642680-aaea-11e8-9ab3-b03abf9a8deb.png">

What different do you expect?

**Comment by dsukhin** [comment] 2018-08-28 16:45
Ahh I understand and see your issue. You are putting some content below where the quote of the previous email started. Was this an issue before? I'm not sure I understand how adding the time the previous message was sent to the top of the quoted message changed the "see more" behavior. I agree this should be fixed up.

**Comment by martini** [comment] 2018-08-29 07:06
Exactly, sorry for not making clear. It was not an issue before because Zammad tries to find first "On XXX wrote:" (which was only on quotes from customers). But now it also appears on own quotes where the actual content of the article is below of the own "On XXX wrote:".

**Comment by dsukhin** [comment] 2018-08-29 13:44
Got it. This should probably be fixed by looking for the last unquoted line instead and putting see more below that. This should be rather easy in the plaintext coveted form since that's just the last line that doesn't start with a ">".

**Comment by SummerStorm** [comment] 2018-10-11 02:44
Closed via 9c02d2e02b732bf4cb2845b389d353e5570e213d

**Closed by SummerStorm** 2018-10-11 02:44 UTC
Labels: feature backlog, prioritized by payment, ticket
