### ISSUE TITLE
Overview "state"-field does not update (circle does)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2284] opened 2018-10-11 17:47 UTC
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a
* Ticket-ID: #1028574

### Expected behavior:

* The ticket state is being updated (circle and field "state") when a closed Ticket is being updated by a customer (and thus reopened).

### Actual behavior:

* The ticket state is being **not** updated (circle and field "state") when a closed Ticket is being updated by a customer (and thus reopened).
* The circle updates from green to orange, the state field does not (only after refreshing the whole webapp)

![image](https://user-images.githubusercontent.com/6549061/46823297-153a6a00-cd8e-11e8-8e14-2b4efc03aafb.png)

### Steps to reproduce the behavior:

* create a E-Mail ticket and send it, close it
* reply to the ticket (the ticket state will refresh accordingly)
* now reply to the ticket again and close it (in most cases simple closing is enough)
* reply to the ticket again
  -> the ticket circle will update to orange, the field state will not

Please note that this seems to be a refreshing issue within the WebApp - I learned that it can be a difference if the ticket is opened within a tab or not. It also just happened, if at least two articles have been in the ticket.

Can supply screencast if needed.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2018-11-02 16:20
Small update as @SummerStorm asked me for reverification:
This only happens in 2.7, if you close the ticket tab. It does not matter how many articles you have!

Screencast is attached.
![state-feature](https://user-images.githubusercontent.com/6549061/47927442-9d122080-dec3-11e8-8844-c96c2a10b3f3.gif)

**Comment by rolfschmidt** [comment] 2021-10-13 09:19
Seems to be fixed on zammad 5.0. Please add note if you have more information how to reproduce it on zammad 5.0.

**Closed as completed by rolfschmidt** 2021-10-13 09:19 UTC
Labels: can't reproduce
