### ISSUE TITLE
UI: Label in LDAP integration broken

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad#4789] opened 2023-09-01 07:53 UTC
### Used Zammad Version

6.2.x

### Environment

- Installation method: source
- Operating system (if you're unsure: `cat /etc/os-release` ): fedora 38
- Database + version:  -
- Elasticsearch version: -
- Browser + version: firefox 116.0.3 / chrome 116.0.5845.140

### Actual behaviour

The label for the titel of the 2nd column is cut off:
![grafik](https://github.com/zammad/zammad/assets/60067527/55c136af-9b0a-4210-acb8-8067b866d033)

### Expected behaviour

It should not be cut off, if space is available

### Steps to reproduce the behaviour

Activate LDAP integration

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment] 2023-09-01 07:56
Duplicate of https://github.com/zammad/zammad/issues/4656.

**Closed as not planned by fliebe92** 2023-09-01 07:56 UTC
Labels: duplicate
