### ISSUE TITLE
Creating new overview: option "only available for replacement users" will not be saved

### ISSUE THREAD

**Issue by chrisblech** [zammad/zammad#1804] opened 2018-02-02 23:50 UTC
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): package (Zammad DEB repo)
* Operating system: Debian 9.3
* Database + version: PostgreSQL 9.6.6
* Elasticsearch version: 5.6.7
* Browser + version: Chrome 64.0.3282.140

### Expected behavior:

* When creating a new overview and selecting "ONLY AVAILABLE FOR USERS WHICH ARE REPLACEMENTS FOR OTHER USERS." -> "YES", this setting is saved and honored.

### Actual behavior:

* When creating a new overview and selecting "ONLY AVAILABLE FOR USERS WHICH ARE REPLACEMENTS FOR OTHER USERS." -> "YES", this setting is ignored.
The new overview is shown to all users.
When re-opening the modal dialog to edit, "NO" is shown in this replacement setting dropdown.

### Steps to reproduce the behavior:

* Settings - Overviews - Create new Overview
* Set "Only available ... replacements ..." to "yes"
* Click "save"
* Click on the new entry in list, to re-open it for editing
* "no" is shown

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2018-12-24 10:54
Hey,

I can't reproduce this on a current Zammad installation.
Could you please check if the problem persists on your side on a current Zammad installation?

If so, please provide the configuration of your Overview-Filters. :)
In the meantime I will close this - if the problem still occurs, let me know and I'll reopen this issue when I received further details. :)

**Closed by MrGeneration** 2018-12-24 10:54 UTC
Labels: can't reproduce
