### ISSUE TITLE
Ticket creation - allow to create users without email

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#562] opened 2016-12-20 15:27 UTC
It happens often that customer calls which is not in the customer db and his problem is solved while on phone. These customers refuses often to hand out their mail address but we want to have this calls in the statistics anyway.

In this case our agents enter some fantasy mail address. Unfortuantely every agent uses his own fantasy mail address for this.

Therefore an option to add an "unknown" checkbox beside "CUSTOMER *" would be nice. Would also enable us to see how many unknown users we have.

**Comment by thorsteneckel** [comment] 2016-12-20 15:35
Hi @monotek - you can already achieve this with the object manager. Just add a new attribute to your ticket and configure in it in the relevant views. 👍

**Comment by monotek** [comment] 2016-12-20 15:51
This does not help as long as customer user filed is mandatory.
Imho the suggested box should just set an predefined mail address or some placeholder like "#unknownuser#".

**Comment by thorsteneckel** [comment] 2017-01-13 10:28
@monotek - might be #613 a duplicate of/possible solution for this?

**Comment by monotek** [comment] 2017-01-13 10:37
I still would prefer a checkbox for this purpose.
If there is an option instead that makes zammad accept every string, email adresses would no longer be checked for validity, which i still like to have.

**Comment by thorsteneckel** [comment] 2017-01-13 14:13
I don't like the introduction of an(other) UI which might be unneeded for a lot of people. This overloads the interface. Would it be possible to add a dummy user with a devnull address and assign all tickets to it? In case the user has or becomes a valid account the ticket can be reassigned.

My point is that I'm looking forward to multi-identifier users (email, phone etc.) but one without an identifier is hard see in my picture of the Zammad context.

**Comment by monotek** [comment] 2017-01-13 14:39
What i want to achieve is to have the same identifier for all unknown users (for stats).
If the agent is able to use anything and there is no easy way to assign unknown by only 1 click i'm pretty sure every agent will use his own placeholder there (what happens in my old company already).

**Comment by martini** [comment] 2017-07-14 10:00
No it's possible to create customers without email address (at least firstname, lastname, email or phone need to be there).

It's available in current develop.

**Closed by martini** 2017-07-14 10:00 UTC
Labels: feature, proposal
