### ISSUE TITLE
Mails with "Content-Type: text/plain" not displayed with monospaced fonts

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#2493] opened 2019-02-25 13:47 UTC
### Infos:

* Used Zammad version: 2.9.0-1550483988.7f4899e0.jessie
* Installation method (source, package, ..): deb from Zammad repository
* Operating system: Debian 8 Jessie
* Database + version: MariaDB 10.0.38-0+deb8u1
* Elasticsearch version: 5.6.15
* Browser + version: Firefox 52.8.0 ESR (Linux)

### Expected behavior:

Display text-based tables as

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   64C    P0    76W / 250W |  27220MiB / 32480MiB |    100% E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:2F:00.0 Off |                    0 |
| N/A   70C    P0   146W / 250W |  11524MiB / 32480MiB |    100% E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  Off  | 00000000:86:00.0 Off |                    0 |
| N/A   62C    P0   210W / 250W |  11530MiB / 32480MiB |    100% E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   59C    P0    79W / 250W |  26698MiB / 32480MiB |    100% E. Process |
+-------------------------------+----------------------+----------------------+

```

### Actual behavior:

Display text-based tables as

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   64C    P0    76W / 250W |  27220MiB / 32480MiB |    100% E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:2F:00.0 Off |                    0 |
| N/A   70C    P0   146W / 250W |  11524MiB / 32480MiB |    100% E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  Off  | 00000000:86:00.0 Off |                    0 |
| N/A   62C    P0   210W / 250W |  11530MiB / 32480MiB |    100% E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   59C    P0    79W / 250W |  26698MiB / 32480MiB |    100% E. Process |
+-------------------------------+----------------------+----------------------+

### Steps to reproduce the behavior:

Send above table as plaintext mail (`Content-Type: text/plain`) to Zammad.

### Why a bug and not a feature request?

text/plain mails should be displayed as they are meant to be read :-)

**Comment by MrGeneration** [comment] 2019-02-25 14:39
Thanks for your contribution.
However: This is not a bug, but rather an enhancement request.

Zammad currently does not support text E-Mails which is why it also does not support monospace.

Beside, this is a duplicate of: #1055 and #325  which is why I will close this issue.
We currently have no roadmap in implementing this, as we're focussing on other points in Zammad.
You can discuss this feature request over in our community (https://community.zammad.org) or, if you need this feature urgent, you're welcome to request a custom development.

**Closed as completed by MrGeneration** 2019-02-25 14:39 UTC
Labels: works as designed / wontfix

**Comment by fthommen** [comment] 2019-02-25 16:04
Two comments:
1.  this is _not_ a duplicate of #1055 or #325 even though it touches a similar topic, but this issue is _not_ about disabling HTML emails (#325) and it is _not_ about editing tickets (#1055)
2. Zammad does support posting tickets by mail.  As such it must (IMHO) support text mails.  You cannot force users to send html mails (how would they know anyway, that they have to send formatted mails)

**Comment by MrGeneration** [comment] 2019-02-25 16:59
Personally I think this partially affects both mentioned issues above.
If not, this is a feature request.

Github is the wrong place for Feature Requests - please use our Community (https://community.zammad.org) for this - we're also using our community for determining the overall need of features.
