### ISSUE TITLE
Elasticsearch stops during update to 3.1 and inside 3.1

### ISSUE THREAD

**Issue by Michael-salutecGmbH** [zammad/zammad#2662] opened 2019-07-11 21:23 UTC
### Infos:

* Used Zammad version: 3.1.0-1562865639
* Installation method (source, package, ..): YUM Repo
* Operating system: CentOS 7
* Database + version: Postgres 9.2 (from CentOS repo)
* Elasticsearch version: 5.6
* Browser + version: N/A

### Expected behavior:

* Zammad and ES runs after upgrade normally

### Actual behavior:

* Zammad is running, but ES is down and no index is build

### Steps to reproduce the behavior:

* upgrade from 3.0 to 3.1 and update 3.1 to newer 3.1 version. I check this three times.
The update runs normally but at that procedure ES will stopped, in follow the index can't be build again and after Zammad starts, ES is still down.
Workaround is after update to start ES, then rebuild the index and after this Zammad/ES works normal.

At ES logs during the update:
[2019-07-11T22:42:20,462][INFO ][o.e.c.m.MetaDataDeleteIndexService] [T1Jrriu] [zammad_production/6unTf0BbQq6-yzuoI3Ta6w] deleting index
[2019-07-11T22:42:53,248][INFO ][o.e.n.Node               ] [T1Jrriu] stopping ...
[2019-07-11T22:42:53,263][INFO ][o.e.n.Node               ] [T1Jrriu] stopped
[2019-07-11T22:42:53,263][INFO ][o.e.n.Node               ] [T1Jrriu] closing ...
[2019-07-11T22:42:53,273][INFO ][o.e.n.Node               ] [T1Jrriu] closed

It looks like Zammad update stop ES, but didn't start it again.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-07-11 21:31
Hey,

thanks for letting us know.
This is actually a duplicate of https://github.com/zammad/zammad/issues/2400 which is missing the information that the service is being stopped and not started again ;/

**Closed as completed by MrGeneration** 2019-07-11 21:31 UTC
Labels: duplicate
