### ISSUE TITLE
LDAP User filter "Invalid filter syntax."

### ISSUE THREAD

**Issue by sscholl** [zammad/zammad#1935] opened 2018-04-09 21:32 UTC
### Infos:

* Used Zammad version:2.4.x
* Installation method (source, package, ..): docker 

### Expected behavior:

* "User filter" persists between multiple changes of settings

### Actual behavior:

* "User filter" is empty, if you change the config.  You have to enter it again.

### Steps to reproduce the behavior:

* set up LDAP with specific "User filter"
* change config
* "User filter" will be empty

**Comment by thorsteneckel** [comment] 2018-04-10 06:52
This is a duplicate of #1854.

**Closed by thorsteneckel** 2018-04-10 06:52 UTC
