### ISSUE TITLE
Google OAuth redirect_uri_mismatch when https is used

### ISSUE THREAD

**Issue by schurig** [zammad/zammad#647] opened 2017-01-18 19:20 UTC
### Infos:

* Used Zammad version: 1.2.0
* Operating system: Ubuntu 16.04

### Expected behavior:

* use https in callback url for google oauth

### Actual behavior:

* uses http in callback url for google oauth

### Steps to reproduce the behavior:

* set http type to `https`
* logout
* authorise with google on login page

### Known workaround
redirect `http` to `https` in nginx and add the http version to the authorised callback urls in the google api console

**Comment by thorsteneckel** [comment] 2018-04-22 16:29
Duplicate of #723 - closing now.

**Closed by thorsteneckel** 2018-04-22 16:29 UTC
Labels: bug
