### ISSUE TITLE
Pending Till reminder

### ISSUE THREAD

**Issue by BF-LX** [zammad/zammad#2763] opened 2019-10-04 06:24 UTC
### Infos:

* Used Zammad version: 3.2.X
* Installation method (source, package, ..): source: https://dl.packager.io/srv/rpm/zammad/zammad/develop/sles/12/$basesearch
* Operating system: SLES 12 SP3
* Database + version: PostgreSQL
* Elasticsearch version:7.3.2
* Browser + version: Opera 63.0.3368.94

### Expected behavior:
*

### Actual behavior:

If I want to put the State in the Ticket View into Pending reminder, I cant see the Calendar.
![image](https://user-images.githubusercontent.com/56147775/66185122-a7faa580-e67e-11e9-9df8-f8594a877ea8.png)

### Steps to reproduce the behavior:

I Can reproduce it in the Chrome and Opera Browser.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2019-10-04 14:44
Sorry, but I can't reproduce this on a current `develop` and `stable`.
Can you please update and ensure your Zammad is current to check again?

**Comment by mantas** [comment] 2019-10-04 14:52
@MrGeneration did you try the same technique as in https://github.com/zammad/zammad/issues/2274 ?

Looks like my fix for it got lost and never merged

**Comment by MrGeneration** [comment] 2019-10-04 15:19
@mantas thanks for the follow up, you're right. I missed that spot.

This is a duplicate of https://github.com/zammad/zammad/issues/2274

**Closed as completed** 2019-10-04 15:20 UTC
Labels: duplicate
