### ISSUE TITLE
Zammad stopped fetching emails via imap

### ISSUE THREAD

**Issue by uli-heller** [zammad/zammad#2013] opened 2018-05-10 13:45 UTC
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): source
* Operating system: ubuntu 18.04
* Database + version: mysql
* Elasticsearch version: 5.6.x
* Browser + version: Chrome

### Expected behavior:

* Fetch emails from the imap server and put the content of the emails in new tickets or existing tickets

### Actual behavior:

* Roughly two hours ago, zammad stopped fetching emails

### Steps to reproduce the behavior:

* Unfortunately, I don't know how
* When I edit an existing inbound email account, then
    * a dialog shows up explaining that there is an email available
    * everything looks good at first sight
    * but the email is never fetched
* Editing the account again shows similar result
* What can I do to debug the issue? I looked at "production.log", but didn't find anything promising :(

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-05-10 13:48
Looks like a duplicate of #1861 to me. Since it's not clear what causes it I would recommend keeping an eye on it and report any information about how to reproduce this in the other issue. You can restart your scheduler to make Zammad fetch your mails again.

**Closed by thorsteneckel** 2018-05-10 13:48 UTC

**Comment by uli-heller** [comment] 2018-05-10 13:56
Unfortunately, restarting the scheduler doesn't work. I stopped all 3 processes and restarted them. Within the log, I see `I, [2018-05-10T15:54:38.014479 #2765]  INFO -- : Scheduler running...` but the imap fetching doesn't work.

**Comment by uli-heller** [comment] 2018-05-10 13:57
BTW: I doubt that my imap server wasn't available...

**Comment by thorsteneckel** [comment] 2018-05-10 13:59
Please redo a restart and provide your `log/production.log`, `log/scheduler_err.log` and `log/scheduler_out.log` after another restart so we can reason about it.

**Comment by thorsteneckel** [comment] 2018-05-10 14:04
Hi @uli-heller - if you are in doubt that your server wasn't available please post all the requested files over here. Please don't just post parts of the logs but everything that was logged after your restart. Thanks.

**Comment by uli-heller** [comment] 2018-05-10 14:25
@thorsteneckel I'll collect the files and place them here after filtering hostnames and usernames. Will take a couple of minutes. Thanks for taking the time caring about my issue.

**Comment by thorsteneckel** [comment] 2018-05-10 14:28
Sure - you're welcome. We will find a solution 👍 Please consider that each comment creates/sends an email to everybody subscribed to the issue and/or watching the Zammad repository. This might create a lot of noise for at least 100 people 🤓

**Comment by thorsteneckel** [comment] 2018-05-10 15:05
I'm glad that it's resolved. Let's blame it on the weather 😉In case it occurs again please use our [community board](https://community.zammad.org/) first to verify that's an actual issue that affects all Zammad instances to prevent sending of mails to the 100 folks "watch"ing the repository. Enjoy using Zammad.
