### ISSUE TITLE
Article Forward

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#693] opened 2017-01-31 09:22 UTC
Hello,

is it possible to implement a "forward"-option to ask someone other than customer?
![zammadreply](https://cloud.githubusercontent.com/assets/9305993/22458846/99610b90-e79e-11e6-8635-2774cdd9c7ab.PNG)

Sometimes we have to ask someone other than the customer for additional information. Then we have to delete the customer email and insert the right one. If there is a forward button, which leaves the to and cc field blank, we are one click faster ;-)

Greetings 
tobibe

**Comment by tobibe** [comment] 2017-02-06 08:40
I forgot: Also it may keep the attachments?

Greetings
tobibe

**Comment by thorsteneckel** [comment] 2017-02-15 09:58
duplicate of #581

**Closed by thorsteneckel** 2017-02-15 09:58 UTC
Labels: feature, proposal
