### ISSUE TITLE
Retweet conversion setting not working

### ISSUE THREAD

**Issue by GreXXL** [zammad/zammad#2736] opened 2019-09-10 10:39 UTC
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.6 LTS
* Database + version: Postgres 9.5.19
* Elasticsearch version: 5.6.16
* Browser + version: Chrome Version 76.0.3809.132
* Ticket-ID: 1078194

### Expected behavior:

* Retweets don't create new articles if conversion is turned off

### Actual behavior:

* Retweets generate new tickets / articles although setting is turned off

### Steps to reproduce the behavior:

* Turn conversion of Twitter Retweets off.
* Create a retweet
* Ticket gets created

Please find attached two screenshots of our configuration and a sample ticket created.

![3](https://user-images.githubusercontent.com/1630413/64607045-f9897a80-d3c7-11e9-9da5-e08fa2de7d2d.png)
![1](https://user-images.githubusercontent.com/1630413/64607047-f9897a80-d3c7-11e9-9e5e-92bf24d1bbf3.png)

**Comment by MrGeneration** [comment] 2019-09-10 10:43
Thanks for your contribution.
I believe that this is a duplicate of https://github.com/zammad/zammad/issues/2571 - would you agree?

**Comment by GreXXL** [comment] 2019-09-10 10:46
No I don't think so. I read this report but this states that there are search results implemented to get tickets for certain search phrases. We don't have searches set up an still get tickets for retweets. See screenshot of our configuration.

![Anmerkung](https://user-images.githubusercontent.com/1630413/64607501-ed51ed00-d3c8-11e9-8d41-eb2c9b3cfdd8.png)

* edit: This setting has worked but has stopped working some versions ago. I think it's a bug and not a desired feature. I didn't get a chance to open a ticket though up until now :/

**Comment by MrGeneration** [comment] 2019-09-10 10:49
Okay, thanks for your feedback.
Please give us some time for verification. :)

**Comment by MrGeneration** [comment] 2020-08-17 12:50
Sorrys for the huge waiting time on this. :-/

**Comment by orangesunny** [comment] 2020-08-17 14:02
@MrGeneration Lovely! Please fix it ASAP to make our Zammad usable and free of those unwanted tickets. Thank you!

**Closed as completed** 2020-08-24 10:54 UTC
Labels: bug, channel, verified, prioritised by payment

**Comment by orangesunny** [comment] 2020-08-26 12:34
Thank you @thorsteneckel for the fix. Can you, please, tell when 3.5.0 will reach our instance hosted by Zammad?

**Comment by thorsteneckel** [comment] 2020-08-26 12:38
Hey @orangesunny - we work with [milestones for our release planing](https://github.com/zammad/zammad/milestones). Once we know the concrete date we will set the `due date` on those milestones. As you can see we have not concrete date yet. We plan the 3.5 release in about 3 weeks from now.

We can deploy the `develop` branch to your instance if you can't wait that long. Please get in touch with the support team and refer to this issue to request that change.

**Comment by orangesunny** [comment] 2020-08-26 15:58
> Hey @orangesunny - we work with [milestones for our release planing](https://github.com/zammad/zammad/milestones). Once we know the concrete date we will set the `due date` on those milestones. As you can see we have not concrete date yet. We plan the 3.5 release in about 3 weeks from now.
> 
> We can deploy the `develop` branch to your instance if you can't wait that long. Please get in touch with the support team and refer to this issue to request that change.

Yes, I asked because I didn’t see the `due date` in the milestone. Thanks for the estimate and the information! I will eventually contact customer service.

Thank you for your work and a lovely piece of software!
