### ISSUE TITLE
Migrating to gmail oauth2 breaks email send, reverting to previous working setup does not resolve the issue

### ISSUE THREAD

**Issue by slapplebags** [zammad/zammad#4059] opened 2022-04-14 17:35 UTC
### Infos:

* Used Zammad version: 5.1.X
* Installation method (source, package, ..): Packages
* Operating system: Ubuntu 20.04
* Database + version: (PostgreSQL) 12.9
* Elasticsearch version: 7.17.2
* Browser + version: chrome 99.0.4844.84

### Expected behavior:

* Migrating from a working email channel setup with a gmail account / app specific password to gmail oauth2 channel using the Migrate Now button and then reverting the migration email will continue to send

### Actual behavior:

* After migrating from a working email channel setup with a gmail account / app specific password to gmail oauth2 channel using the Migrate Now button and then reverting using the Roll Back Migration button causes no email to send

### Steps to reproduce the behavior:

* Setup a gmail account using the email channel and verify mail can be sent / received
* Select the Migrate now button in Zammad to move to gmail oauth2 authentication
* Mail will be received but cannot be sent 
* Revert to the previous setup using the Rollback Migration button
* Mail will be received but cannot be sent
* Adding new accounts, changing to a local MTA, etc will not be able to send email. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2022-04-14 17:48
Duplicate of #4056 which is a technical question.

**Closed as completed by MrGeneration** 2022-04-14 17:48 UTC
Labels: duplicate, question

**Comment by slapplebags** [comment] 2022-04-14 17:59
this is not a duplicate, i would expect the rollback migration to get zammad back to its previously working state. my previous ticket didnt mention the rollback issue.

**Comment by slapplebags** [comment] 2022-04-15 22:10
issue was caused by zammad being left in import mode.
