### ISSUE TITLE
Scheduler not running with DEB Ubuntu 16.04

### ISSUE THREAD

**Issue by zheonline** [zammad/zammad#1081] opened 2017-05-13 16:50 UTC
### Infos:

* Used Zammad version: 1.5.0-1494609142.a96442f.xenial
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04 LTS
* Browser + version: 

I've installed the Package form the repo. Looks okay so far, but the scheduler isn't running.
The scheduler_err.log shows me this error:
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `exec': could not receive data from server: Bad file descriptor (PG::UnableToSend)

I've tried to restart the postgre and zammad but nothing helps.
any idea?

**Comment by zheonline** [comment] 2017-05-13 17:32
After adding the code from thorsteneckel
form https://github.com/zammad/zammad/issues/1080

+    # reconnect in case db connection is lost
+    begin
+      ActiveRecord::Base.connection.reconnect!
+    rescue => e
+      logger.error "Can't reconnect to database #{e.inspect}"
+    end
+

to the scheduler.rb
now the scheduler works. But its a stable version?

**Comment by thorsteneckel** [comment] 2017-05-13 17:34
Hi @zheonline - this is a duplicate of #1080 . Please update to the latest package version: [zammad_1.5.0-1494688262.89b9849.xenial_amd64.deb (68.83 MiB)](https://packager.io/gh/zammad/zammad/build_runs/2046#95541) 

Your version is one to low 🙉

**Closed by thorsteneckel** 2017-05-13 17:34 UTC
