### ISSUE TITLE
Can't add e-mail account in e-mail channel configuration

### ISSUE THREAD

**Issue by edneymatias** [zammad/zammad#1473] opened 2017-09-25 20:16 UTC
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: package
* Operating system: Debian Jessie
* Browser + version: 61.0.3163.100

### Expected behavior:

* When adding a new e-mail account on 1.5 version, Zammad would allow me to specify advanced configurations like imap server, authentication method, username, etc. 

### Actual behavior:

* Now on 2.0 version I get a gateway error like the one bellow:

![image](https://user-images.githubusercontent.com/22533602/30828607-961abf7c-a214-11e7-92c2-a0a8f58f84e4.png)

### Steps to reproduce the behavior:

* On admin, click e-mail configuration;
* Clic new to add a new account;
* Enter the basic information (Organization & Department Name, e-mail, password and destination group);
* Click connect and wait for error.

**Comment by edneymatias** [comment] 2017-09-25 20:29
Hi there! I updated Zammad to the 2.1.1 develop version and problem is gone!

**Comment by martini** [comment] 2017-09-26 06:47
@edneymatias normally the error message has noting todo with Zammad 2.0 or Zammad 2.1.

It seems that the auto probing of your mail account takes too long and nginx/apache will raise an timeout issue.

Can you check what read timeout https://github.com/zammad/zammad/blob/develop/contrib/nginx/zammad.conf#L46 of your current config?

In certain cases it can take more then 180 seconds. So my proposal would be to move up to 300 seconds in our example.

Feedback is welcome!

**Comment by edneymatias** [comment] 2017-09-26 14:53
Hi! I raised the config to the suggested value and got the same result. Then I tried with 500 seconds and had no luck either.

**Comment by martini** [comment] 2017-09-26 17:19
> Hi! I raised the config to the suggested value and got the same result. Then I tried with 500 seconds and had no luck either.

Thanks for feedback. Can you reproduce it on a https://zammad.com/ instance?

**Comment by edneymatias** [comment] 2017-09-26 17:42
No, I can't reproduce it there! On zammad.com, the probe works just fine which makes me think of Google Cloud Platform. The Google Platform blocks SMTP traffic. On 1.5, the probe would fail and Zammad would allow me to specify another port. On Google Cloud, I have to connect to SMTP servers on port 2525 since it isn't blocked. Indeed I use Sendgrid to send emails from Google instances.

**Comment by edneymatias** [comment] 2017-09-26 19:40
Man! 

When I click the experts link on an empty form I get this:

![image](https://user-images.githubusercontent.com/22533602/30880338-a532a6f4-a2d8-11e7-8bbc-a1e8f235c47a.png)

Why do I have to fill the form to gain access to advanced options?

Just by chance, I clicked the link again after filling the form! Just to find the advanced options!

![image](https://user-images.githubusercontent.com/22533602/30880451-04c55ce2-a2d9-11e7-8a03-8d95450fdc34.png)

Now I can set the right options without the probe!

**Comment by monotek** [comment] 2017-09-26 20:52
I also ran in this before: https://github.com/zammad/zammad/issues/224#issuecomment-261257567

Really annoying. Should be changed.

**Comment by edneymatias** [comment] 2017-09-26 21:04
Not very intuitive, but now I can resume my tests!

**Comment by thorsteneckel** [comment] 2018-04-24 15:05
This one is resolved and/or a duplicate of #224. However, I'll close this one here.

**Closed by thorsteneckel** 2018-04-24 15:05 UTC
Labels: waiting for feedback
