### ISSUE TITLE
handling of incoming mails seems strange / customer is not set correctly

### ISSUE THREAD

**Issue by gwingend** [zammad/zammad#1351] opened 2017-08-19 16:06 UTC
### Infos:

* Used Zammad version: 1.6.1
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:
incoming mails should be associated to correct customer
 

### Actual behavior:
I set up a mailbox (e.g. Helpdesk@companyname.com) in our internal mail system. 
zammad is catching the emails from the inbox of helpdesk with imap and creates a ticket in group helpdesk.
That works as expected!

If an external user (i.e. testuser@googlemail.com) sends a email to helpdesk (helpdesk@companyname.com) everything if fine.
zammad is pulling the mail out of the inbox of "helpdesk" and creates a ticket. 
This ticket is correctly created for customer "testuser@googlemail.com".

But if an internal user (user@companyname.com) sends an email to this mailbox  "helpdesk@companyname.com", something is going wrong!

zammad is correctly pulling the email out of the inbox of "helpdesk" and creates a ticket.

But this ticket is not created for user@companyname.com!
Instead zammad created the ticket for "helpdesk@companyname.com". 

This means every ticket of internal users get assigend to customer "helpdesk" instead of the individual internal users.

### Steps to reproduce the behavior:
Do the described setup.
Or I can show you the wrong behaviour on my system in a remote session.

**Comment by martini** [comment] 2017-08-21 06:58
Hi @gwingend 

that sounds strange or maybe it's just a misunderstand of the UI.

The customer of an ticket is shown above the ticket title (the avatar - just hover) and in the ticket sidebar (your have an extra icon for that).

Question: Is the customer for tickets created by the agent still Helpdesk@companyname.com ?

If yes, do you have any postmaster filters configured?

JFI: This is no Zammad standard behaviour.

 -Martin

**Comment by gwingend** [comment] 2017-08-21 07:50
Hi Martin,
due to datasecurity reasons I didn´nt want to post the screenshots public.

Have a look in your ticketsystem: [Ticket#107711]

Best regards
Gerhard

**Comment by martini** [comment] 2017-08-21 07:53
@gwingend thanks for response. In the screenshots it's not 100% clear to me (because there is no sidebar visible / just with the avatar - without hover it seems that the customer is in both cases Helpdesk@companyname.com).

So my next question is:  There are any postmaster filters configured?

Thanks!

 -Martin

**Comment by martini** [comment] 2017-08-22 10:41
Update: I was able to reproduce the issue. Fix is on the road...

**Comment by gwingend** [comment] 2017-08-22 11:07
YESSS! :-)


>>> Martin Edenhofer <notifications@github.com> Dienstag, 22. August
2017 12:41 >>>
Update: I was able to reproduce the issue. Fix is on the road...

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/zammad/zammad/issues/1351#issuecomment-323988838 
-- 
Diese E-Mail wurde von Sophos UTM auf Viren überprüft.

**Comment by martini** [comment] 2017-08-22 13:37
It's fixed in all branches. Please update the OS packages and restart all Zammad processes.

Feedback is welcome!

 -Martin

**Closed by martini** 2017-08-22 13:37 UTC
Labels: bug

**Comment by gwingend** [comment] 2017-08-22 19:53
Works perfekt!
Thanks!

**Comment by rapante85** [comment] 2018-10-01 16:50
Hello,
i am new to zammad and facing a similar problem on Version 2.6., except that this issue only appears if the sender of the email is an agent to.

**Comment by MrGeneration** [comment] 2018-10-01 17:25
@rapante85 the behaviour you describe currently works as designed. (see: https://github.com/zammad/zammad/issues/967#issuecomment-369577763 )

Please do not recycle old issue posts. Also please note that replying to issues causes a lot of noise to people watching this tracker. It really is just for bug issues.

No offense though!
