### ISSUE TITLE
Return and arrow keys stop working while replying to a ticket

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#3033] opened 2020-04-22 18:06 UTC
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 10
* Database + version: PostgreSQL from docker-compose
* Elasticsearch version: ES from docker-compose
* Browser + version: Chrome 80

### Expected behavior:

* Return and up/down arrow keys shouldn't stop working while typing a reply in the ticket zoom.

### Actual behavior:

This bug occurs very rarely. When it does, it has the following effects while replying to an article in the ticket zoom:

* Both Return and Enter keys stop working. I can still enter normal text (ie. A-Z, 0-9, space and so on), but I am unable to create a line break - pressing Enter or Return simply does nothing. The same when trying to use modifier keys like shift, alt, ctrl with Enter/Return. The only way to insert a linebreak is by copypasting it into the reply.
* The up/down arrow keys do not work; I cannot use them to move the cursor up or down a line.
* The left/right arrow keys work normally. I can use them to move the cursor (also to move the cursor up/down by holding them long enough). I can also freely position the cursor using the mouse.
* The following exception is logged in the browser console every time I press Return:

	```
	application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:14346 Uncaught TypeError: Cannot read property 'removeChild' of undefined
		at a.measureScrollbar (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:14346)
		at a.checkScrollbar (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:14329)
		at a.show (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:14195)
		at HTMLDivElement.<anonymous> (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:14163)
		at Function.each (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:815)
		at rt.fn.init.each (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:726)
		at rt.fn.init.o [as modal] (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:14158)
		at e.render (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:37113)
		at e.render (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:36497)
		at e [as constructor] (application-01a4da841f8a792e08fd857172daf169ddfc1bcd14c4c0ddbd456000e692743c.js:formatted:37015)
	```

This bug seems to occur very rarely - I had gotten reports back from multiple users back in 05/2019 that this had occurred, but today is the first time that I encountered it. As this might be almost impossible to reproduce, I attempted to collect some more information in the debugger that might help to track this down:

![inspector](https://user-images.githubusercontent.com/6863569/80016851-fca72600-84d3-11ea-96fa-4b916e194030.png)

Full console log: [zammad.iserv.eu-1587576836529.log](https://github.com/zammad/zammad/files/4518154/zammad.iserv.eu-1587576836529.log)

The issue can be resolved by reloading the Zammad browser tab.

### Steps to reproduce the behavior:

* I do not know how to reproduce this bug.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-04-23 14:17
@mantas is this enough to fiddle around?
I've seen it as well, it's a veeerrrryyyyyy rare issue that usually only get's resolved by reloading.
We had this after a update after pressing on the notification bird but addressed that as far as I'm aware.

**Comment by mantas** [comment] 2020-04-23 14:24
@MrGeneration I _think_ I've seen this too. No luck to reproduce it so far :(

@martinvonwittich did you notice if there's any correlation with using text modules in the same browser session?

**Comment by thorsteneckel** [comment] 2020-04-23 15:09
Just a tiny detail that I noticed and might be useful in the future. The screenshot shows that the `this` context is `div.modal.js-recipientDropdown.open` when the exception was raised. This means that the current input context is an [open! Organization autocompletion dropdown](https://github.com/zammad/zammad/blob/db9f0eb772ffcab2889c0b67dc2fef5b1cff9397/app/assets/javascripts/app/lib/app_post/_object_organization_autocompletion.coffee#L2). I assume you have not noticed any visible one @martinvonwittich as your inputs ref to text/content input?

As the `this` context and exception message refers to an open! Organization autocompletion dropdown which fails to calculate the hight of the scrollbar I assume the root cause was an Organization autocompletion selection where something went wrong (technically!).

Just a wind guess/thought: Maybe an empty Organization search result or a search with an active AJAX request was canceled and broke the state of the element? The [event handlers of this element](https://github.com/zammad/zammad/blob/db9f0eb772ffcab2889c0b67dc2fef5b1cff9397/app/assets/javascripts/app/lib/app_post/_object_organization_autocompletion.coffee#L156-L238) might be still active and capture the user input?

@martinvonwittich can you remember any interaction with an Organization selection before that error occurred?

Hope this helps in any way.

**Comment by martinvonwittich** [comment] 2020-05-10 14:07
> @martinvonwittich did you notice if there's any correlation with using text modules in the same browser session?

Hmm, I do believe that our agents use text modules regularly ([though I wish I could track this ^^](https://community.zammad.org/t/text-module-usage-counter/4349)), but I can't determine whether this could be related.

I am almost certain that I did use a text module while replying to this ticket; my reply begins with "Hallo Frau XXX,", and we have a text module `::hf` -> `Hallo Frau ##ticket.customer.lastname},` for that purpose.

> This means that the current input context is an open! Organization autocompletion dropdown. I assume you have not noticed any visible one @martinvonwittich as your inputs ref to text/content input?

Nope, it definitely wasn't visible; my focus was in the reply textbox. I still have the complete screenshot here where the rest of the view is visible:

![screenshot-redacted](https://user-images.githubusercontent.com/6863569/81501218-6185bd00-92d7-11ea-8942-131cd63baa18.png)

Unfortunately the organization text field is out of the viewport due to the debugger, so we can't tell if there's anything funky with it :/ 

> Just a wind guess/thought: Maybe an empty Organization search result or a search with an active AJAX request was canceled and broke the state of the element? The event handlers of this element might be still active and capture the user input?

Sounds like a good lead to me. I've fiddled around with the organization autocomplete in the new ticket screen a bit to see if I can find a way to break it somehow, but no luck so far :(
	
> @martinvonwittich can you remember any interaction with an Organization selection before that error occurred?

Nope, sorry. Though, wait a minute... the screenshot shows that I was replying to an existing ticket, and not creating a new one. There is no organization dropdown in the reply view, is there? There's only the To/CC fields. And as far as I can tell from the debugger, `<div class="dropdown js-recipientDropdown open">` is definitely the organization selector from the new ticket view.

I'm starting to wonder if this issue is actually distributed over multiple ticket tabs. Maybe we need to something with a new ticket view in one tab, which then could cause the issue while replying to a ticket in another tab?

**Comment by martinvonwittich** [comment] 2020-05-10 21:39
Just noticed that I had posted about this issue before in the community, had totally forgotten about that. I'm not sure if it was even the same root cause back then, but I'll link it here in case there's something interesting in there: https://community.zammad.org/t/mysterious-unreproducible-bug-return-key-stops-working-while-replying/2516/2

**Comment by dominikklein** [comment] 2023-05-04 12:46
I will close the issue because we didn't get reports like this in the past. And also, the editor will be replaced at some point by a new implementation.

**Closed as completed by dominikklein** 2023-05-04 12:46 UTC
Labels: can't reproduce

**Comment by sabolc** [comment] 2024-07-04 08:37
I just had the exact same behavior (in Chrome). It would not go away until I shut down the browser and opened up Zammad fresh. I'll try to reproduce it (of course now it is working fine).
