### ISSUE TITLE
Copy image from browser not getting pasted in text fields. Console error thrown

### ISSUE THREAD

**Issue by vishnus** [zammad/zammad#1376] opened 2017-08-30 14:53 UTC
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: deb
* Operating system: Ubuntu 16.04
* Browser + version: Chromium  60.0.3112.78 and Firefox 55.0.2 

### Expected behavior:

* Image copied from browser to be shown in text boxes (including text modules). 

### Actual behavior:

* Console error 
![image](https://user-images.githubusercontent.com/598121/29878695-d3b35ce4-8dc0-11e7-8715-40254c5e8a5d.png)

### Steps to reproduce the behavior:

* Right click on any image from any website, click copy image, and then paste in any text field in Zammad. If you do the same in Gmail, github etc, it works. But not in Zammad. PS, screen grab when I copy to clipboard and paste, it works. Just doesnt work from web pages.

**Comment by thorsteneckel** [comment] 2020-02-19 16:58
This has been fixed in the meantime. Probably with 3.2 already 😱 Let me know if this is still an issue for you on latest `stable` and please provide an example where we can reproduce. Closing now because I can't reproduce it anymore.

**Closed by thorsteneckel** 2020-02-19 16:58 UTC
Labels: enhancement, feature backlog
