### ISSUE TITLE
Column width is resized to a non readable minimum

### ISSUE THREAD

**Issue by xf-** [zammad/zammad#2031] opened 2018-05-18 16:19 UTC
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): deb package
* Operating system: Debian
* Database + version: 
* Elasticsearch version:
* Browser + version: Firefox 62a (also saw this issue in normal stable version)

### Expected behavior:

* Column adjust with
* At least a way to reset the standard column width

### Actual behavior:

* Sometimes column width breaks including getting a scollbar
![image](https://user-images.githubusercontent.com/1295633/40245902-34a11914-5ac7-11e8-950a-cc04899dd428.png)

Localstroage ID 2:
```json
{"headerWidth":{"icon":0.023275145469659187,"title":0.03325020781379884,"customer_id":0.03325020781379884,"group_id":0.8165128869250897,"created_at":0.03325020781379884,"updated_by_id":0.03325020781379884,"updated_at":0.03325020781379884}}
```

-> Only fix is to clear the Loalstorage

### Steps to reproduce the behavior:

* Maybe resizing the window, switch the active instance (no persisten way to recreate the issue)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment] 2018-05-22 06:32
Thx for the report. We are hunting this for  a while now.... 

https://community.zammad.org/t/we-need-your-help-columns-in-overviews-are-resized-to-the-unreadable/665/3

If you find a way to reproduce, let us now.

**Comment by xf-** [comment] 2018-06-02 14:33
@hanneshal looks like it stats if i resize the window and at some point later it breaks. I tried to force it and found no clear way, only reoccurring pattern is it happens after a resize but no intimidate. And after it breaks if you manually fix the column it is not responsive anymore (maybe a place to look).

**Comment by xf-** [comment] 2018-06-02 14:39
Maybe it is fixed - Last update added the new more responsive menu on top and it recalculates all the columns on resize (much better as before)

**Comment by thorsteneckel** [comment] 2018-06-04 08:42
Please let us know if it still persists 👍 Closing (for) now.

**Comment by xf-** [comment] 2018-06-17 20:51
Hi @thorsteneckel ,

it still happens (less often). Looks like it only happens if a resize of window happened at some point. Issue appears mostly after increasing the window size or go to fullscreen.

**Comment by thorsteneckel** [comment] 2018-06-17 21:37
Thanks for your feedback! Would be great if you could find a way to reproduce it and create an issue with a step by step description.

**Comment by xf-** [comment] 2018-06-19 21:38
@thorsteneckel i don't think it will happen. i can't find a clear pattern.

**Comment by MrGeneration** [comment] 2018-08-22 11:31
This also (still) applies to 2.6

**Comment by thorsteneckel** [comment] 2018-08-22 11:41
We're still not able to reproduce it. If anyone know how we're happy to fix it.

**Comment by martini** [comment] 2018-11-19 09:23
Update: Maybe I was able to reproduce it. It looks not 100% like in opening screenshot. But very similar. Follow the following steps to reproduce it:

1) Resize your browser window to 1400x800.
2) Click on a new overview where tickets in it
3) Resize the columns.
4) Resize the browser window to 1024x800.
5) Wait until the table is re-rendered (e. g. let an agent close tickets in it). 

The result is:

<img width="1054" alt="screen shot 2018-11-19 at 10 20 34" src="https://user-images.githubusercontent.com/110226/48697454-ef05b680-ebe4-11e8-9856-611ae111b315.png">

**Comment by xf-** [comment] 2018-11-19 12:06
This is the same issue. Depends a little bit on different screen/window sizes and after starting breaking it will get worse. But i never found a way to reproduce.

**Comment by martini** [comment] 2018-11-19 12:08
@xf- do you "resize" the browser window?  I only can reproduce it this way. But it seems that nobody was using "resize" the browser window.

**Comment by xf-** [comment] 2018-11-19 12:22
i never touched the columns. Sometimes it happens 3 times a day, next time it happens once a month. I often tried to reproduce it, but never found a way.

**Comment by martini** [comment] 2018-11-19 13:57
@xf- Thanks for feedback. Do you use bulk action or macros from overview?

**Comment by xf-** [comment] 2018-11-20 17:51
I don't use bulk (because i can't tag stuff - e.g. select all spam/newsletter and tag as spam -> delete task handles the rest). Macro in overview is the drag and drop stuff? No, because i always forget about tat feature.

**Comment by xf-** [comment] 2018-11-20 17:59
I found a way how to reproduce my issue.
- deleted all storage (firefox)
- force reload
- make the window smaller as initial size and i get an scroll bar. (increase the size and resource it to old one works).

I use a multi monitor setup with different resolutions and ppi.

**Comment by martini** [comment] 2018-12-10 14:29
Hi all,

any feedback would be welcome if you still have the issue in Zammad 2.8.

Thanks!

 -Martin

**Comment by MrGeneration** [comment] 2018-12-13 17:44
I have no customer Feedback yet.
I did not see this issue any more within 2.8.

Edit: 1/2 customers verified that this issue has been adressed.

**Comment by xf-** [comment] 2018-12-14 18:04
looks like resize works always

**Comment by martini** [comment] 2019-01-16 13:23
@xf- thanks for feedback! 👌 I'm closing for now.

**Closed by martini** 2019-01-16 13:23 UTC
Labels: bug, verified
