### ISSUE TITLE
Allow URLs on the login page

### ISSUE THREAD

**Issue by Vogelkoje** [zammad/zammad#3130] opened 2020-07-24 13:05 UTC
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version:any
* Elasticsearch version: any
* Browser + version: any
* Note: This article has been updated by @MrGeneration to clear up the goal of this enhancement.

### Desired behavior:

A option to provide custom URLs to the login page.
Especially links for:

   * data privacy
   * imprint
   * TOS ?

### Actual behavior:

You currently can't add custom HTML or urls to provide data privacy or imprint urls to Zammad.
This is an issue for users in countries were this is required.

This is technically possible by adjusting templates, but this isn't update safe.

**Comment by MrGeneration** [comment] 2020-09-22 15:00
I'm sure that this was because of a paying customer, however, I can't find any reference to that. If this was a ticket of a paying customer, please let me know and provide the ticket number. :-)

**Comment by MrGeneration** [comment] 2022-07-26 13:20
Duplicate of #3875

**Closed as completed by MrGeneration** 2022-07-26 13:20 UTC
Labels: duplicate
