### ISSUE TITLE
Create incoming mail as private article, if outgoing one was private as well

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2453] opened 2019-01-28 15:39 UTC
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1035855

### Expected behavior:

* Zammad should recognize if a incoming mail article should be public or private based on what vibility type has been used in the article that has been sent to the mail address before (if applicable).

**Use case:**
Let's say you have a customer with a problem, where you need further information from a e.g. supplier.
To reduce your work and keep your overview over the stuff, you decide to forward parts of the received article of your customer to your supplier. As you don't want your customer to know about this step, you choose to send the supplier a private article by mail.

Now, if your supplier replies, Zammad will recognize that you wrote the supplier earlier in the same ticket and will see that your visbility was set to private - Zammad will thus set the vibility of the incoming answer of your supplier to private. You can now answer your customer, without the customer ever seeing the private conversation.

### Actual behavior:

* Zammad does not care about the visibility of sent mails. Thus a private mail to your supplier (or at least parts) might be revealed when your supplier answers (the article will be public).

### Steps to reproduce the behavior:

* Receive a ticket from your customer
* forward the article (vibility: private) to another person
* answer (another person) to the forwarded mail
* see a public article that sometimes should be private

**Note** This feature should be on by default, but one should be able to change this in E-Mail-Settings via GUI.

**Comment by thorsteneckel** [comment] 2021-05-03 08:15
Hi @bolah2009 and @MrGeneration - this sounds like a duplicate of https://github.com/zammad/zammad/issues/3467

Do you agree?

**Comment by MrGeneration** [comment] 2021-05-03 08:16
Yep, issue 3467 is a duplicate of this issue, I agree.

**Comment by thorsteneckel** [comment] 2021-05-03 09:19
Closing as duplicate of #3467 then.

**Closed as completed by thorsteneckel** 2021-05-03 09:19 UTC
Labels: duplicate

**Comment by MrGeneration** [comment] 2021-05-03 09:22
I just migrated the ticket and priotisement information to the "duplicate".
