### ISSUE TITLE
NEW person call on the phone without(!) telling an email address - how to save the ticket?

### ISSUE THREAD

**Issue by sunshine450** [zammad/zammad#1057] opened 2017-05-08 15:50 UTC
Hello everyone,

when someone new calls without telling his/her email address - how can I save a ticket?

I must create a contact to save the ticket, and an email address is required!

Thank you very much for your help in advance!

Regards,
sunshine450

**Comment by monotek** [comment] 2017-05-08 16:51
Duplicate of https://github.com/zammad/zammad/issues/247

**Closed by monotek** 2017-05-08 16:51 UTC
