### ISSUE TITLE
Every session comes from 127.0.0.1

### ISSUE THREAD

**Issue by skibson** [zammad/zammad#742] opened 2017-02-06 11:27 UTC
As in screenshot, every user shows connecting from localhost. 
Zammad on Ubuntu installed from repo
Is that nginx configuration fault? 

![screencapture-zadania-koba-pl-1486380236953](https://cloud.githubusercontent.com/assets/6915534/22645425/3e3cdbb8-ec67-11e6-91d6-20983eb03003.png)

**Comment by martini** [comment] 2017-02-06 11:35
Hi @skibson 

can you check if you have three line in your nginx config?

```
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
 -Martin

**Comment by skibson** [comment] 2017-02-06 11:37
here's my nginx config for this location 

    location / {                                                                          
        proxy_set_header Host $http_host;                                                 
        proxy_set_header CLIENT_IP $remote_addr;                                          
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;                      
        proxy_read_timeout 180;                                                           
        proxy_pass http://zammad;                                                         
                                                                                          
        gzip on;                                                                          
        gzip_types text/plain text/xml text/css image/svg+xml application/javascript appli
        gzip_proxied any;                                                                 
    }                                                                                     
}

**Comment by jannheider** [comment] 2017-02-14 15:31
Was it a clean Ubuntu install ?

Is there any other System between your Ubuntu Server <-> Browser ?
Loadbalancer, Proxy?

Please attach your nginx.conf und the vhost configuration.

**Comment by skibson** [comment] 2017-02-14 15:50
It is clean ubuntu container. No proxy, no loadbalancer.
Wouldn't it pass loadbalancer's or proxy IP if they would exist? For me it looks like it's ruby's fault of reading wrong ip from nginx. In zammad.access.log lines begin with proper ip address.
My nginx config files are default from zammad repo installation 

[nginx.conf.txt](https://github.com/zammad/zammad/files/774581/nginx.conf.txt)
[zammad.conf.txt](https://github.com/zammad/zammad/files/774580/zammad.conf.txt)

**Comment by jannheider** [comment] 2017-02-14 16:15
It depends on the setup of loadbalancer and proxy's how they are configured and working. But if you don't have them than everything ist fine.

In the vhost config, check the **server_name**, you have an ip in here what does not make sense.
If zammad is the only site on this server write this **server_name _ ;** ... restart and test. Or better put here the FQDN like zammad.somedomain.com or what your domain name should be.

If it it still show 127.0.0.1 then add this to your zammad vhost conf:
add_header X-Forwarded-For **$proxy_add_x_forwarded_for;**
just bevor the last closing bracket "}" and reload nginx.

This will write the var $proxy_add_x_forwarded_for in the http header.
You can then view the HTTP Header it with "curl -I http://yourservername" or with Chrome Browser (http://stackoverflow.com/questions/4423061/view-http-headers-in-google-chrome)
Look for "X-Forwarded-For" an show us the result

**Comment by skibson** [comment] 2017-02-15 13:31
X-Forwarded-For:192.168.0.108 - chrome on PC
X-Forwarded-For: 192.168.225.62 - curl -I from zammad container host

**Comment by GrexAut** [comment] 2018-01-23 15:46
I have the same problem, clean ubuntu install, and I get always spammed with mail:
"Zammad Helpdesk Nameldung erfasst von einem neuen Gerät", but there is no new device, and the IP in the mail is always 127.0.0.1.

All sessions under system are listed as 127.0.0.1 too

**Comment by monotek** [comment] 2018-01-23 16:16
Do you run Zammad on your local machine?
Is it a Docker or a DEB install?

**Comment by GrexAut** [comment] 2018-01-23 16:19
I created a new issue, because this is tagged  as question, but I think it is a config mistake / bug. Because my problem is more than this, I get E-Mails from new devices too, see:
https://github.com/zammad/zammad/issues/1774

For completion: cleean ubuntu install with deb pkg install.

**Comment by monotek** [comment] 2018-01-23 16:30
Do you run Zammad on your local machine?

**Comment by GrexAut** [comment] 2018-01-23 16:30
No, zammad is running on Ubuntu on ESXi Vmware machine in network.

**Comment by monotek** [comment] 2018-01-23 17:53
Sorry, can't help. Do not have any experience with VMware networking.

**Comment by GrexAut** [comment] 2018-01-24 08:48
This does not depending VMware networking, I think it is a proxy misconfigure.

**Comment by monotek** [comment] 2018-01-24 08:56
The nginx config delivered by the installer does not have this problem. 
Must be problem on your side.

**Comment by vittee** [comment] 2018-06-04 04:54
This is because you're using private IP address.

WEBrick removes all private IP addresses from the X-Forwarded-For header.

File: `webrick/httprequest.rb`
```ruby
    PrivateNetworkRegexp = /
      ^unknown$|
      ^((::ffff:)?127.0.0.1|::1)$|
      ^(::ffff:)?(10|172\.(1[6-9]|2[0-9]|3[01])|192\.168)\.
    /ixo
```

**Comment by thorsteneckel** [comment] 2018-06-04 06:46
Thanks for the input guys! IMHO this answers the question. If not please use our [community board](http://community.zammad.org/) for further (technical) discussions.

**Closed by thorsteneckel** 2018-06-04 06:46 UTC
Labels: question

**Comment by veritaspoutine** [comment] 2018-08-02 11:05
Hi I am just wondering because most of agents would be working on tickets within a LAN therefore it is expected agents would initiate a session from a private IP for most of the time. 

If the sessions feature intends to inform the administrator the location of all the active agents, then why have  `webrick/httprequest.rb` to remove private IP from the X-Forwarded-For header?

Just having a hard time wrapping my head around the reasoning here.

**Comment by thorsteneckel** [comment] 2018-08-02 12:09
Hi @veritaspoutine - I'm not sure why you came by this old and closed issue but please be aware that every comment on the issue tracker leads to sending mails to over 100 people. Please use the [community board](http://community.zammad.org/) for technical questions.

However, we discourage the usage of webrick and only support unicorn and puma because of various reasons (performance etc.).

**Comment by thorsteneckel** [comment] 2018-10-04 14:46
We were able to reproduce this. While doing research on a possible solution we found out that GitLab actually uses [the same one](https://gitlab.com/gitlab-org/gitlab-ce/blob/0e1fc6e04c96ce989062e02d9e706031cea87c36/config/initializers/trusted_proxies.rb#L23).

The fix is available in the `develop` branch and will be ready in about 30 minutes from now in all repos.

**Comment by klou** [comment] 2020-12-02 02:49
Is there any way to have a configurable fix for this?  Adding to the array in `production.rb` (from a reverse proxy) will not persist on packaged installs.

https://community.zammad.org/t/configure-make-persistent-trusted-proxies-on-packaged-releases/5689

**Comment by MrGeneration** [comment] 2020-12-02 07:54
@klou Please don't recycle old and (long) closed issues.
This would be a feature request that should live in the community.
