### ISSUE TITLE
SLA Escalation time by phone comment not updated 

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3642] opened 2021-06-29 18:17 UTC
### Infos:

* Used Zammad version: 4.1 (latest)
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04
* Database + version: Postgres
* Elasticsearch version: 7
* Browser + version: Microsoft Edge 91

### Expected behavior:
If I create a ticket our SLA set an escalation time. The State is „Offen“ (open). The escalation time says below the title „eskaliert in 8 Stunden“.

If I post a comment in this ticket and select as comment-type „phone“, the comment changes from private to a public note. Now the escalation time switches to 2 days after saving.

Thats all fine! Thats right.

Now the Problem: If I set the comment-type to phone again (now the private note switches to a public note) and set the type back from public to private the escalation time is not updates to „2 days“. The escalation time is „in 8 Stunden“.

I think thats not right

**Comment by MrGeneration** [comment] 2021-06-29 18:20
Your steps to reproduce are unclear. 
This issue can't go into verification process until we know exactly what else does change.

This does sound like a technical question due to configurations and possibly group / sla changes.
Please clarify.

**Comment by Dennis1993** [comment] 2021-07-02 10:47
Okay, I created some screenshots.

1. Create ticket:
![image](https://user-images.githubusercontent.com/1473674/124262719-a7808e80-db32-11eb-9704-223cf1f6e27d.png)

2. Write a comment with "phone" and not private-mode (without red border):
![image](https://user-images.githubusercontent.com/1473674/124262907-e9a9d000-db32-11eb-8573-668f6b8ef757.png)

Save it and see the escalation time:
![image](https://user-images.githubusercontent.com/1473674/124263056-11009d00-db33-11eb-9a77-87c4ea55a7ce.png)

3. Now I write a comment with mode "phone" and activate the read border. Now the escalation time is not updated:
![image](https://user-images.githubusercontent.com/1473674/124263390-7a80ab80-db33-11eb-920a-31a63295812a.png)

I hope you can understand it.

Our SLA config:
![image](https://user-images.githubusercontent.com/1473674/124263483-971ce380-db33-11eb-84e5-d2b068472ed6.png)

**Comment by mantas** [comment] 2021-07-02 13:10
Hi @Dennis1993

If I understand correctly, the issue is that escalation time does not change when internal item is added. This is intended.

Escalations are bumped after agent contacts customer (or vice versa). Since customer is aware that he was contacted, there's no need to keep that bit private :) If you want to keep some comments private, you should create a separate internal note.

Closing this issue now.

**Closed as completed by mantas** 2021-07-02 13:10 UTC
Labels: works as designed / wontfix
