### ISSUE TITLE
Issues in the rights-management 

### ISSUE THREAD

**Issue by ManuTaurus** [zammad/zammad#1810] opened 2018-02-06 10:15 UTC
### Infos:
* Used Zammad version: 2.3.x
* Installation method: Package
* Operating system: CentOS7
* Database version: PostgreSQL 9.2.23
* Elasticsearch version: 5.6.6
* Browser: Safari 11.0.3 / Firefox 58.0.1

### Expected behavior:
1.) A supporter from group X has only „create“ rights on group Y. So he has the possibility to forward a ticket to supporter-group Y by selecting group Y in the dropdown menu of the ticket. (Zammad v2.2.x)

2.) A supporter can forward a ticket only to all the groups he has „create“-rights. (Zammad v2.2.x)

3.) If a supporter does not have the full rights on the selected group, he can still select an owner from a selection of zammad user. (Zammad v2.2.x)

### Actual behavior:
1.) A supporter from group X needs „change“ rights on group Y to select group Y in the dropdown menu of the ticket. (Zammad v2.3.x)

2.) A supporter can forward a ticket only to all the groups he has „change“-rights. (Zammad v2.3.x) 

3.) A supporter needs „full“ rights for a group to select an owner for a ticket. (Zammad v2.3.x)

I can’t find anything to that changes of the rights-management in the changelog, so yes I'm sure this is a bug and no feature request or a general question.

**Comment by moellert** [comment] 2018-02-06 11:13
Addition
**Expected behaviour:**
When I setup a trigger which sends an e-mail to all agents, it is send to all agents who have the "read"-rights on the group.

**Actual behavior:**
The email is only send to agents who have the "full"-rights on the group.

I don't know if this changed too, but I think it  belongs to this.

**Comment by thorsteneckel** [comment] 2018-02-12 17:16
@muhammadn - could you please verify that this has changed? Let me know afterwards - thanks!

**Comment by thorsteneckel** [comment] 2018-02-14 10:32
We have verified the issue and can reproduce it. I'm pretty sure it was introduced by this change: https://github.com/zammad/zammad/commit/6f87ebf7c7c5366b6ce4fd64a12e1fbde30ea1a3#diff-b6731e315bdb4dffdc3ddfab309e1f2d

However, further analyses is needed. We'll come back to you.

**Comment by thorsteneckel** [comment] 2018-02-27 09:50
This is fixed with the two commits above and available in develop and stable ~30 minutes from now. Feedback is appreciated.

**Closed by thorsteneckel** 2018-02-27 09:50 UTC
Labels: bug, verified

**Comment by thorsteneckel** [comment] 2018-02-27 10:52
Hi @moellert - sorry to say but we had to revert the notification change to avoid spamming of unrelated users. It's currently not possible to achieve the use case you are describing. Good thing: We are now aware of it and will think about a possible solution. However, this will take time and has currently no priority since we are working on further features and customer tasks.

Just a sidenote: This functionality was always this way and was not changed in the past couple of months/years.

**Comment by ManuTaurus** [comment] 2018-02-28 13:32
Hi @thorsteneckel . Thanx for working on the Issue. I’ve tested your changes and I can confirm, that a supporter from group x needs now just „create“-rights on group y to select group y in the ticket. So the supporter can select every group from the dropdown in the ticket, where he has "create"-rights.

But I have still the problem, that a supporter can forward a ticket to all the groups he has „change“-rights. Shouldn’t he be possible to select only those groups from the dropdown in the ticket where he has „create“- or „full“-rights? So if a supporter does not have "create"- or "full"-rights, he shouldn't be able to see the group in the dropdown of the ticket. At least this was the behaviour in v2.2.

A supporter does still need „full“-rights for the group that is assigned to the ticket to select an owner. In v2.2 the supporter could select an owner from a selection of zammad user even if he had no rights on the assigned group.

**Comment by chrklo** [comment] 2018-02-28 13:54
see also https://github.com/zammad/zammad/issues/967

**Comment by thorsteneckel** [comment] 2018-03-06 15:33
Hi @ManuTaurus ,

I took the time an reviewed 2.2:
> So if a supporter does not have "create"- or "full"-rights, he shouldn't be able to see the group in the dropdown of the ticket. At least this was the behaviour in v2.2.

As you can see an Agent with only `change` rights in a Group is and was able to create/forward Tickets to it.
![22create](https://user-images.githubusercontent.com/3873515/37041181-e0b6b3a8-215b-11e8-8185-d34a6c9e49a4.gif)
So there was no change in behavior.

From our point its only reasonable that way. Changing a Ticket means having advanced rights in that group.

Please understand that we won't take any actions.

**Comment by ManuTaurus** [comment] 2018-03-08 12:29
Hi @thorsteneckel 

Thank you for your quick answer!

But the strange thing is, that I have a different behaviour in Zammad v2.2. 
As you can see, my Zammad-instance works as I described before: Only the group, the user has „create“-rights, is shown up in the dropdown of the ticket. The group, the user has „change“-rights, does not show up. 
Do you have an idea what could cause this divergent behaviour?

![zammad_screen_record](https://user-images.githubusercontent.com/9370340/37151148-a6034620-22d4-11e8-9135-7f927ab933fe.gif)

**Comment by thorsteneckel** [comment] 2018-03-08 12:34
That is actually strange! Can you specify your exact Zammad version? It's visible in CentOSs yum Zammad package info.

**Comment by ManuTaurus** [comment] 2018-03-08 13:02
'yum info zammad' tells me the following:

Name       : zammad
Architektur : x86_64
Version    : 2.2.0
Ausgabe    : 1513237090.47a1bb76.centos7
Größe : 266 M
Quelle      : installed
Aus Quelle  : zammad

**Comment by thorsteneckel** [comment] 2018-03-08 13:45
Hi @ManuTaurus ,

I just tested this with the exact same version and the result differs. Has to be something different. Can you please do the following:

1.) Create a file called `debug_groups.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_groups.rb` or `rails r debug_groups.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized!
4.) Delete the `debug_groups.rb` file

```ruby
result = Ticket::ScreenOptions.attributes_to_change(
  ticket:       Ticket.find_by(number: 89095),
  current_user: User.find_by(login: 'dumpf1'),
)

puts JSON.pretty_generate(result[:assets][:Group]); nil
puts JSON.pretty_generate(User.find_by(login: 'dumpf1').group_names_access_map); nil
```

Thanks!

**Comment by ManuTaurus** [comment] 2018-03-08 14:24
[zammad@xxxxxxxxxxx zammad]$ zammad run rails r debug_groups.rb
{
  "3": {
    "id": 3,
    "signature_id": null,
    "email_address_id": 6,
    "name": "Haustechnik Support",
    "assignment_timeout": null,
    "follow_up_possible": "yes",
    "follow_up_assignment": true,
    "active": true,
    "note": "",
    "updated_by_id": 3,
    "created_by_id": 3,
    "created_at": "2017-10-24 13:27:30 UTC",
    "updated_at": "2017-12-14 15:11:24 UTC",
    "user_ids": [
      379,
      131
    ]
  },
  "1": {
    "id": 1,
    "signature_id": 1,
    "email_address_id": null,
    "name": "Users",
    "assignment_timeout": null,
    "follow_up_possible": "yes",
    "follow_up_assignment": true,
    "active": true,
    "note": "Standard Group/Pool for Tickets.",
    "updated_by_id": 3,
    "created_by_id": 1,
    "created_at": "2017-10-16 09:27:49 UTC",
    "updated_at": "2017-12-14 08:47:55 UTC",
    "user_ids": [

    ]
  },
  "2": {
    "id": 2,
    "signature_id": 1,
    "email_address_id": 7,
    "name": "VST Support",
    "assignment_timeout": null,
    "follow_up_possible": "yes",
    "follow_up_assignment": true,
    "active": true,
    "note": "",
    "updated_by_id": 3,
    "created_by_id": 3,
    "created_at": "2017-10-23 14:21:44 UTC",
    "updated_at": "2017-12-14 15:11:31 UTC",
    "user_ids": [
      3,
      131
    ]
  },
  "4": {
    "id": 4,
    "signature_id": null,
    "email_address_id": 8,
    "name": "Admins",
    "assignment_timeout": null,
    "follow_up_possible": "yes",
    "follow_up_assignment": false,
    "active": true,
    "note": "",
    "updated_by_id": 3,
    "created_by_id": 379,
    "created_at": "2017-10-26 12:07:31 UTC",
    "updated_at": "2017-12-14 15:11:47 UTC",
    "user_ids": [

    ]
  },
  "5": {
    "id": 5,
    "signature_id": null,
    "email_address_id": null,
    "name": "only_change",
    "assignment_timeout": null,
    "follow_up_possible": "yes",
    "follow_up_assignment": false,
    "active": true,
    "note": "",
    "updated_by_id": 130,
    "created_by_id": 130,
    "created_at": "2018-03-07 14:02:01 UTC",
    "updated_at": "2018-03-07 14:02:01 UTC",
    "user_ids": [

    ]
  },
  "6": {
    "id": 6,
    "signature_id": null,
    "email_address_id": null,
    "name": "only_create",
    "assignment_timeout": null,
    "follow_up_possible": "yes",
    "follow_up_assignment": false,
    "active": true,
    "note": "",
    "updated_by_id": 130,
    "created_by_id": 130,
    "created_at": "2018-03-07 14:02:19 UTC",
    "updated_at": "2018-03-07 14:02:19 UTC",
    "user_ids": [

    ]
  }
}
{
  "Haustechnik Support": [
    "full"
  ],
  "VST Support": [
    "full"
  ],
  "only_change": [
    "change"
  ],
  "only_create": [
    "create"
  ]
}

**Comment by thorsteneckel** [comment] 2018-03-08 14:27
Thanks for your fast reply. Let's dig deeper! Can you please post the complete content of the file `app/models/ticket/screen_options.rb` from your Zammad installation?

**Comment by ManuTaurus** [comment] 2018-03-08 14:40
Here is the content of my screen_options.rb:

# Copyright (C) 2012-2016 Zammad Foundation, http://zammad-foundation.org/
module Ticket::ScreenOptions

=begin

list attributes

  result = Ticket::ScreenOptions.attributes_to_change(
    ticket_id: 123,
    article_id: 123,

    ticket: ticket_model,
    current_user: User.find(123),
  )

returns

  result = {
    type_id:            type_ids,
    state_id:           state_ids,
    priority_id:        priority_ids,
    owner_id:           owner_ids,
    group_id:           group_ids,
    group_id__owner_id: groups_users,
  }

=end

  def self.attributes_to_change(params)
    raise 'current_user param needed' if !params[:current_user]

    if params[:ticket_id]
      params[:ticket] = Ticket.find(params[:ticket_id])
    end
    if params[:article_id]
      params[:article] = Ticket::Article.find(params[:article_id])
    end

    filter = {}
    assets = {}

    # get ticket states
    state_ids = []
    if params[:ticket]
      state_type = params[:ticket].state.state_type
    end
    state_types = ['open', 'closed', 'pending action', 'pending reminder']
    if state_type && !state_types.include?(state_type.name)
      state_ids.push params[:ticket].state.id
    end
    state_types.each do |type|
      state_type = Ticket::StateType.find_by(name: type)
      next if !state_type
      state_type.states.each do |state|
        assets = state.assets(assets)
        state_ids.push state.id
      end
    end
    filter[:state_id] = state_ids

    # get priorities
    priority_ids = []
    Ticket::Priority.where(active: true).each do |priority|
      assets = priority.assets(assets)
      priority_ids.push priority.id
    end
    filter[:priority_id] = priority_ids

    type_ids = []
    if params[:ticket]
      types = %w[note phone]
      if params[:ticket].group.email_address_id
        types.push 'email'
      end
      types.each do |type_name|
        type = Ticket::Article::Type.lookup( name: type_name )
        next if type.blank?
        type_ids.push type.id
      end
    end
    filter[:type_id] = type_ids

    # get group / user relations
    agents = {}
    User.with_permissions('ticket.agent').each do |user|
      agents[ user.id ] = 1
    end

    dependencies = { group_id: { '' => { owner_id: [] } } }

    filter[:group_id] = []
    groups = if params[:current_user].permissions?('ticket.agent')
               params[:current_user].groups_access('create')
             else
               Group.where(active: true)
             end

    groups.each do |group|
      filter[:group_id].push group.id
      assets = group.assets(assets)
      dependencies[:group_id][group.id] = { owner_id: [] }

      User.group_access(group.id, 'full').each do |user|
        next if !agents[ user.id ]
        assets = user.assets(assets)
        dependencies[:group_id][ group.id ][ :owner_id ].push user.id
      end
    end

    {
      assets:    assets,
      form_meta: {
        filter:       filter,
        dependencies: dependencies,
      }
    }
  end

=begin

list tickets by customer groupd in state categroie open and closed

  result = Ticket::ScreenOptions.list_by_customer(
    customer_id: 123,
    limit:       15, # optional, default 15
  )

returns

  result = {
    ticket_ids_open:   tickets_open,
    ticket_ids_closed: tickets_closed,
    assets:            { ...list of assets... },
  }

=end

  def self.list_by_customer(data)

    # get closed/open states
    state_list_open   = Ticket::State.by_category(:open)
    state_list_closed = Ticket::State.by_category(:closed)

    # get tickets
    tickets_open = Ticket.where(
      customer_id: data[:customer_id],
      state_id: state_list_open
    ).limit( data[:limit] || 15 ).order('created_at DESC')
    assets = {}
    ticket_ids_open = []
    tickets_open.each do |ticket|
      ticket_ids_open.push ticket.id
      assets = ticket.assets(assets)
    end

    tickets_closed = Ticket.where(
      customer_id: data[:customer_id],
      state_id: state_list_closed
    ).limit( data[:limit] || 15 ).order('created_at DESC')
    ticket_ids_closed = []
    tickets_closed.each do |ticket|
      ticket_ids_closed.push ticket.id
      assets = ticket.assets(assets)
    end

    {
      ticket_ids_open: ticket_ids_open,
      ticket_ids_closed: ticket_ids_closed,
      assets: assets,
    }
  end
end

**Comment by thorsteneckel** [comment] 2018-03-08 14:43
Probably the last check: Please run `User.find_by(login: 'dumpf1').permissions?('ticket.agent')` on your [Zammad Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console) and post the output here.

**Comment by ManuTaurus** [comment] 2018-03-08 14:49
The Output is "true":

irb(main):001:0> User.find_by(login: 'dumpf1').permissions?('ticket.agent')
=> true

**Comment by thorsteneckel** [comment] 2018-03-08 15:02
Hi @ManuTaurus ! Again not what I expected 🙃Can you please do the following:

1.) Create a file called `debug_groups.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_groups.rb` or `rails r debug_groups.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized!
4.) Delete the `debug_groups.rb` file

```ruby
result = Ticket::ScreenOptions.attributes_to_change(
  ticket:       Ticket.find_by(number: 89095),
  current_user: User.find_by(login: 'dumpf1'),
)

puts JSON.pretty_generate(result[:filter][:group_id]); nil

role_group_access = RoleGroup.includes(:group).where(role_id: User.find_by(login: 'dumpf1').role_ids, access: 'create', groups: { active: true })

puts JSON.pretty_generate(role_group_access); nil
puts JSON.pretty_generate(User.find_by(login: 'dumpf1').groups_access('create')); nil

```

Thanks!

**Comment by ManuTaurus** [comment] 2018-03-08 15:21
I receive an error-message. The problem is caused by the line 6:

[zammad@xxxxxxxxx zammad]$ zammad run rails r debug_groups.rb
debug_groups.rb:6:in `<top (required)>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:34:in `load'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:34:in `perform'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from /opt/zammad/bin/rails:4:in `require'
	from /opt/zammad/bin/rails:4:in `<main>'

**Comment by thorsteneckel** [comment] 2018-03-08 15:31
Sorry, my bad. Can you please retry with the updated code from above?

**Comment by ManuTaurus** [comment] 2018-03-08 15:53
ok, now it looks better:

[root@xxxxxxxxx zammad]# zammad run rails r debug_groups.rb
[
  3,
  2,
  6
]
"#<RoleGroup::ActiveRecord_Relation:0x00562d48fa53

**Comment by thorsteneckel** [comment] 2018-03-08 15:56
There is some (interesting) output missing 😱

**Comment by ManuTaurus** [comment] 2018-03-08 15:57
Sorry, you're right!

[root@xxxxxxxxx zammad]# zammad run rails r debug_groups.rb
[
  3,
  2,
  6
]
"#<RoleGroup::ActiveRecord_Relation:0x005555b4857050>"
"#<Group::ActiveRecord_Relation:0x005555b5dd49c8>"

**Comment by thorsteneckel** [comment] 2018-03-08 15:59
Had to update it again... 🙄

**Comment by ManuTaurus** [comment] 2018-03-08 16:05
ok, now i've got the following output:

[root@xxxxxxxxx zammad]# zammad run rails r debug_groups.rb
[
  3,
  2,
  6
]
#<ActiveRecord::Relation [#<RoleGroup role_id: 4, group_id: 3, access: "create">]>
#<ActiveRecord::Relation [#<Group id: 3, signature_id: nil, email_address_id: 6, name: "Haustechnik Support", assignment_timeout: nil, follow_up_possible: "yes", follow_up_assignment: true, active: true, note: "", updated_by_id: 3, created_by_id: 3, created_at: "2017-10-24 13:27:30", updated_at: "2017-12-14 15:11:24">, #<Group id: 2, signature_id: 1, email_address_id: 7, name: "VST Support", assignment_timeout: nil, follow_up_possible: "yes", follow_up_assignment: true, active: true, note: "", updated_by_id: 3, created_by_id: 3, created_at: "2017-10-23 14:21:44", updated_at: "2017-12-14 15:11:31">, #<Group id: 6, signature_id: nil, email_address_id: nil, name: "only_create", assignment_timeout: nil, follow_up_possible: "yes", follow_up_assignment: false, active: true, note: "", updated_by_id: 130, created_by_id: 130, created_at: "2018-03-07 14:02:19", updated_at: "2018-03-07 14:02:19">]>

**Comment by moellert** [comment] 2018-03-19 14:01
@thorsteneckel, after you reverted the changes for the email notifications send by triggers I checked another workaround and there I noticed something.

Why is it the same behavior as described above with the default notifications which can be managed by every agent for himself? 
I would say that when you are allowed to read tickets in a group it could be possible that you want to get online/email notifications even if you don't have "full" rights and in this case you are able to manage this by yourself and you are not forced to get get them like in the case of sending emails via trigger.

**Comment by thorsteneckel** [comment] 2018-03-20 11:22
Just wanted to let you know @ManuTaurus and @moellert that Zammad 2.4 will be released soon and we are busy getting the last things done. I'll come back to you afterwards.

@ManuTaurus - This is really strange! We have to dig further. Maybe a direct call with TeamViewer would be good. I'll contact you.

**Comment by ManuTaurus** [comment] 2018-03-20 11:32
Hi @thorsteneckel! Thanks for the info and for your help. Sure, you can contact me any time.

**Comment by thorsteneckel** [comment] 2018-04-10 14:10
Hi @ManuTaurus - Thanks for providing the result via mail in Ticket# 1017553. I was able to spot the difference:

There is a condition which groups should get returned over here:
https://github.com/zammad/zammad/blob/47a1bb76a647aaf448af878446403c9cfc8cdcfd/app/models/ticket/screen_options.rb#L92-L96

In my environment the code in the if case is processed. In your environment the else path. That is what I expected already [in an earlier comment](https://github.com/zammad/zammad/issues/1810#issuecomment-371506994).

I'm not yet sure why but it seems the difference is in the file `/opt/zammad/app/models/user.rb` after line `451`. Could you please send me the file of your system to the ticket mentioned above? I want to have a look at that. Thanks!
