### ISSUE TITLE
Using more than one mail-address for an user.

### ISSUE THREAD

**Issue by martinbenz** [zammad/zammad#1104] opened 2017-05-17 09:45 UTC
current Zammad Version including update from April

In our business it's a request from a lot of customers to assign more than one mailaddress to a single user/customer within an Organisation. 
If customers are opening a ticket very often more than person should be informed. Currently in Zammad its possible to assign only one mailaddress to one user.     
E.g. one customer opens a ticket and some more colleagues or a defined group should be informed . 
It would be good to have a simple possibility to assigne more than one mailaddress. This could be done by an additional ""CC"-field in the master data of an user. In this field more than one mailaddresses should be added. If the field contains some data, these data should be automatically loaded in the CC-Field of the mail. If the field is empty -> no action.     
I assume that such solution is useful as well for some other companies using Zamma.

**Comment by babakkazemi** [comment] 2017-05-24 06:37
Second extension to this FR: more than one mail-domain per organisation

**Comment by thorsteneckel** [comment] 2017-05-28 15:47
This is a duplicate of #613 - feel free to contribute to the discussion over there 🚀

**Closed by thorsteneckel** 2017-05-28 15:47 UTC
