### ISSUE TITLE
text field cuts content on submit if too long

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2241] opened 2018-09-19 10:19 UTC
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a 
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Google Chrome, Internet Explorer (can test further browsers)

### Expected behavior:

* when having a field with maxlength of e.g. 4 letters Zammad should ensure the user can only enter 4 letters and not as many as he wants to

### Actual behavior:

* * when having a field with maxlength of e.g. 4 letters Zammad let's the user basically type as much as he wants into the field and cuts all exceeding letters when submitting the ticket / updating the ticket.

### Steps to reproduce the behavior:

* Create a custom object as text field with maxlength of e.g. 4
* create a new ticket and enter more characters than the maxlength allows & submit the ticket
  -> Zammad will cut what's too much
* try updating the ticket with too many characters - again, Zammad will gladly take it all and then simply throw away what's too much.

![textfield-bug](https://user-images.githubusercontent.com/6549061/45747425-1c92ab80-bc06-11e8-980a-b89e67e6efce.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SummerStorm** [comment] 2018-09-19 10:49
This is a duplicate of #738.

**Closed as completed by SummerStorm** 2018-09-19 10:49 UTC
Labels: duplicate
