### ISSUE TITLE
Redirect to original URL after third party login via e. g. MS 365

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3409] opened 2021-02-15 08:23 UTC
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket #1083688

### Expected behavior:

* A user receives a link that points to the Zammad knowledge base (kb) or any other item
* The user is opening this url and gets the Zammad login page
* The user is authentication against MS 365
* After successfull authentication the user is redirected to requested URL/link

### Actual behavior:

* A user receives a link that points to the Zammad knowledge base (kb) or any other item
* The user is opening this url and gets the Zammad login page
* The user is authentication against MS 365
* After successfull authentication the user is redirected to Zammad-Dashboard (not requested URL/link)

### Steps to reproduce the behavior:

* Don't log in to Zammad
* Follow a link that points to a knowledge base article
* Use O365 SSO to log in
* Find yourself at the Zammad dashboard

Actually it's not a bug because O365 doesn't preserve the link to the knowledge base, but it's possible to circumvent this behavior.

**Comment by martini** [comment] 2021-02-15 10:11
This is a duplicate of #2266

**Closed as completed by martini** 2021-02-15 10:11 UTC
Labels: duplicate
