### ISSUE TITLE
When forwarding e-mails the attachment is missing

### ISSUE THREAD

**Issue by svenschumacher** [zammad/zammad#2097] opened 2018-06-25 10:23 UTC
### Infos:

* Used Zammad version: 2.5.x
* Installation method (source, package, ..): Docker-Compose
* Operating system: Ubuntu
* Database + version: Latest
* Elasticsearch version: Latest
* Browser + version: Chrome 67.0.3396.87 

### Expected behavior:

* When forwarding an E-Mail with attachments, the sent E-Mail should include the attachments with it´s content.

### Actual behavior:

* Sent E-Mails have empty attachments.
![image](https://user-images.githubusercontent.com/19308158/41845025-55d8f00c-7872-11e8-9fec-90218c03052f.png)
### Steps to reproduce the behavior:

* Forward an E-Mail with attachment. I tried different atttachments like .eml, jpg, pdf. The storage is defined as database.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by svenschumacher** [comment] 2018-06-25 10:23
I opened this, because #1789 is closed.

**Comment by thorsteneckel** [comment] 2018-07-04 08:07
Hi @SummerStorm - can you please verify this? @mantas has a private branch ready for merge that fixes an issue similar to this one (#1123) . Please verify if the issue occurs in this fix-branch to ensure that his change doesn't fix this already. Thanks!

**Comment by HLFH** [comment] 2018-07-10 13:28
Hi. Is https://github.com/zammad/zammad/commit/7bb7e7a438d1bb4a969d878d06c705f74cd11701 fixing #2097?

**Comment by SummerStorm** [comment] 2018-07-16 16:05
Hi @svenschumacher. I can't seem to reproduce this on ef179bf, 3545893 and ca454dd.

Is every forwarded email missing its attachments or does this issue only occur sporadically? Other than the missing attachments, are you able to send and receive emails successfully? Would you mind providing a step by step guide on how to reproduce this? Thanks.

**Comment by svenschumacher** [comment] 2018-07-18 09:34
Hi @SummerStorm, yes it´s missing in every forwarded E-Mail. The steps to reproduce follow immediately.

**Comment by svenschumacher** [comment] 2018-07-18 09:55
We do this steps in our Zammad:
![image](https://user-images.githubusercontent.com/19308158/42874356-31a6033e-8a81-11e8-9a8c-b43c7f41956b.png)

Afterwards, the mail is showing the empty images:
![image](https://user-images.githubusercontent.com/19308158/42874398-52bdb44a-8a81-11e8-9dcf-54bad8118914.png)

@SummerStorm Please check my steps. Thanks a lot!

**Comment by martini** [comment] 2018-07-18 10:56
Hi @svenschumacher 

it may depend on the content of the email which is forwarded. Can you attache the example to this issue which ist not working on your side by downloading it via:

<img width="354" alt="screen shot 2018-07-18 at 12 53 28" src="https://user-images.githubusercontent.com/110226/42877421-d5794356-8a89-11e8-94ca-50ed677f28f6.png">

With this example we may can reproduce it.

 -Martin

**Comment by thorsteneckel** [comment] 2018-07-28 07:10
Hi @svenschumacher - can you please verify this in the latest version of `develop` (where the fixes for #1123 were applied)? Otherwise please provide a sample mail (as @martini requested in the previous comment) and we can check it. I'll close this for now since we can't reproduce it (anymore). Thanks for your understanding.

**Closed as completed by thorsteneckel** 2018-07-28 07:10 UTC
Labels: duplicate
