### ISSUE TITLE
Chat does not work due to errors in WebSocket (Database connection)

### ISSUE THREAD

**Issue by d--j** [zammad/zammad#2353] opened 2018-11-14 18:30 UTC
### Infos:

* Used Zammad version: develop / 2.7.0-1541516430.05f1354
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: Postgres 9.5
* Elasticsearch version: 5.6.13
* Webserver: nginx 1.15.6
* Browser + version: all with WebSocket support

### Expected behavior:

* Chat should work (as Agent or Customer)
* WebSocket messages/events should return meaning full data like 
```
[{"event":"chat_status_agent","data":{"waiting_chat_count":0,"waiting_chat_session_list":[],"running_chat_count":0,"running_chat_session_list":[],"active_agent_count":0,"active_agent_ids":[],"seads_available":0,"seads_total":0,"active":false/*,…*/}}]
```

### Actual behavior:

* When a customer opens a page with embedded chat or when an agent opens the Zammad interface a WebSocket connection gets established
* One message that gets send on this WebSocket early on is chat_status_customer / chat_status_agent. This message gets an error response: 
```json
[{"event":"error","data":{"error":"No connection pool with 'primary' found.","payload":{"event":"chat_status_agent"}}}]
```

### Steps to reproduce the behavior:

* Open Zammad with activated chat as agent in Google Chrome
* Open Network Panel of the Developer Tools, select the WebSocket connection.
* Search for the chat_status_agent message and you will find the error message as response to it
![websocket error](https://user-images.githubusercontent.com/100674/48503649-ff174200-e842-11e8-8956-7e93292b9c60.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-11-15 13:04
Hi @d--j - I don't get it 🤔 I'm not aware of any chat related issues as you describe them here. Can you please reproduce this with one of our [free hosted instances](https://www.zammad.com/getting-started) and let us know the name? That would help. Thanks!

**Comment by d--j** [comment] 2018-11-15 13:48
Hi @thorsteneckel ,

the error does not occur on your hosted instances. Looks like you are using a different way of handling WebSockets than the Zammad package version in Ubuntu 16.04 does. (Maybe it is opening the database connection unconditionally for every socket)

Anyways have a look at my pull request #2354 – The way you handle establishing a database connection (`self.database_connection_required` setting the class level instance variable `@ database_connection` to true) only works when it is called in each and every sub class of `Sessions::Event::Base` that needs database access. But there is a class `Sessions::Event::ChatBase` that calls `database_connection_required` because all sub classes of it (like `Sessions::Event::ChatStatusAgent`) need database access. The sub classes of `Sessions::Event::ChatBase` do not call `database_connection_required` anymore. This does not work. Either you call `database_connection_required` in each and every sub (sub) class of `Sessions::Event::Base` that needs database access explicitly or you use my pull request (or a variation of it) to inherit the class level instance variable.

Some pointers:
http://wiseheartdesign.com/articles/2006/09/22/class-level-instance-variables/
https://stackoverflow.com/questions/10728735/inherit-class-level-instance-variables-in-ruby

**Comment by thorsteneckel** [comment] 2018-11-15 14:26
Hi @d--j - thanks for your fast reply but now I'm even more confused. Websocket handling is part of the application context and independent of the OS it's running on. Another thing that confuses me is that it's not reproducible on our hosted instance. I can hardly imagine that this hasn't pop up in any other installation earlier. Maybe there is something different on your setup? Please understand that I can't take the risk of changing things without a test case - especially since this is an issue we haven't heard of yet. I'd love to move this over to the [community board](http://community.zammad.org/) where we can discuss this further to reduce the noise on the issue tracker (which will send out an email to >100 people for each comment). Please notify my via @thorsteneckel in the community thread you created. Thanks for your understanding!

**Comment by martini** [comment] 2018-11-16 18:04
Update: Thank @d--j - I added some tests to your PR. It's currently on our CI. 

-=> Bugfix is on the road. Thanks for your support! 😻 👍🏻

**Comment by martini** [comment] 2018-11-17 06:44
@d--j thanks a lot! It's fixed now in develop and stable. 😻🤓👌

**Closed as completed by martini** 2018-11-17 06:44 UTC
Labels: bug, verified
