### ISSUE TITLE
default select ticket attribute after remove the default value

### ISSUE THREAD

**Issue by lr1980** [zammad/zammad#1840] opened 2018-02-18 08:43 UTC
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): zammad-docker

### Expected behavior:

* create a new select ticket attribute and mark a value as default
* later remove the default value so that no value is marked as default anymore
* now you have a list without a default value

### Actual behavior:

* after you remove the default value, its use the first value as default

### Steps to reproduce the behavior:

* create a new select ticket attribute and mark a value as default
* update db
* remove default value
* update db

**Comment by muhammadn** [comment] 2018-03-01 14:20
@lr1980 I cannot reproduce on the current develop branch. (and 2.4.x is not released yet and will be based on develop`

**Comment by thorsteneckel** [comment] 2018-03-01 14:47
@lr1980 - we did some changes with [this commit](https://github.com/zammad/zammad/commit/afb78f2200728a4c7ea3767d5ad46a944a8a1944#diff-37245a8ba37670d51dc477d1c0f4a841R476) that probably fixed this issue, too. So we'll close this for now. Please reopen in case your issue still persists after you've upgraded to develop or Zammad 2.4 (after the release). Thanks for reporting it!

**Closed by thorsteneckel** 2018-03-01 14:47 UTC
Labels: can't reproduce
