### ISSUE TITLE
timezone issue with report graphs not displaying or displaying $timezone hours out of step

### ISSUE THREAD

**Issue by chesty** [zammad/zammad#2089] opened 2018-06-19 13:14 UTC
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): zammad-docker-compose
* timezone: +10

### Expected behavior:

* lines on graphs on day tab appear and lined up with the correct time 

### Actual behavior:

* if server is running on UTC, lines on the graph in the day tab are $timezone hours out of step, if server is running on +10, lines on the graph in the day tab don't display. tickets in the box below the graph do appear. 

### Steps to reproduce the behavior:

* set up an environment in +10 timezone, desktop, emails, server on UTC and another test with everything on +10 including the server.

**Comment by MrGeneration** [comment] 2019-03-07 14:28
Hey,

sorry I can't really get the issue here or rather can't reproduce this.

## What I did

* I changed the timezone of my Zammad-Server to GMT +10 Australian time
* I could verify this. as long as my browser did not have the correct timezone (by default it has +1 because of my location)
* I then disabled geo location services within Zammad and installed a addon manually adjusting my timezone from +1 to +10

When checking reporting, you can see the current timezone of your Browser (see screenshot).
Zammad will show all information (especially date time based stuff) according to the agents timezone.

So this might be a Browser related issue.
Could you please test again and see if it works by now?

Also, what Browser are you using and what does the timezone information below the reporting graph say?

![image](https://user-images.githubusercontent.com/6549061/53963404-8a1b9100-40ed-11e9-871f-efa18c1106c7.png)

![image](https://user-images.githubusercontent.com/6549061/53963451-a5869c00-40ed-11e9-95cb-a3d4b924bade.png)
As soon as I disable my manual timezone manipulation, Zammad jumps back to my timezone. This is correct in my opinion.

**Comment by chesty** [comment] 2019-03-08 00:27
Thank you. Maybe it's fixed now.
I've changed position and no longer admin zammad, I haven't been using zammad or keeping an eye on development.

**Comment by MrGeneration** [comment] 2019-03-14 10:56
My bad! Sorry about that.
Martin could verify this and I indirectly already did as well, I didn't notice that it does only affect the graph (which I did ignore and did not notice that it didn't move at all).

We'll reopen this and are working on adressing it.

**Comment by martini** [comment] 2019-03-26 07:41
Available/fixed in current stable package. Feedback is welcome.

**Closed as completed by martini** 2019-03-26 07:41 UTC
Labels: bug, reporting, verified
