### ISSUE TITLE
Reply does not work as expected

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2184] opened 2018-08-13 12:08 UTC
### Infos:

* Used Zammad version: develop (pre 2.7)
* Installation method (source, package, ..): source
* Operating system: CentOS 7
* Database + version: PostgreSQL
* Elasticsearch version: ./.
* Browser + version: Chrome lates, FF lates, all macOS

### Expected behavior:

* When replying to an article the sender of the article should be used as the recipient.

### Actual behavior:

* The customer of the ticket is used as the recipient.

### Steps to reproduce the behavior:

* Create a phone ticket from customer a
* Change the customer
* Reply via e-mail to the first article

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment] 2018-09-19 08:34
The [reply recipient logic](https://github.com/zammad/zammad/blob/46db068a65158aa8e8ca3571d860561d6b1033d4/app/assets/javascripts/app/lib/app_post/utils.coffee#L966) caused quite a bit of trouble over the time. Because of that we have [a comprehensive list of tests](https://github.com/zammad/zammad/blob/46db068a65158aa8e8ca3571d860561d6b1033d4/public/assets/tests/html_utils.js#L1775) for the different cases.

The reply logic for tickets created by an agent via the ticket create view should work as described below:

### Received Call

1 . Create a "Received Call" Ticket
2. Change the Customer of the Ticket
3. Reply to the first Article

Recipient **IS** Ticket Customer.
Recipient **SHOULD BE** Article `From`.

See:
![localhost_3000_ 1](https://user-images.githubusercontent.com/3873515/45740754-3f1cc880-bbf6-11e8-849b-534974a00336.png)
![localhost_3000_ 3](https://user-images.githubusercontent.com/3873515/45740886-8efb8f80-bbf6-11e8-9645-593c8582c09f.png)

### Outbound Call

1 . Create a "Outbound Call" Ticket
2. Change the Customer of the Ticket
3. Reply to the first Article

Recipient **IS** blank.
Recipient **SHOULD BE** Article `To`.

See:
![localhost_3000_ 4](https://user-images.githubusercontent.com/3873515/45740984-cf5b0d80-bbf6-11e8-8eb1-81e6004411b9.png)
![localhost_3000_ 5](https://user-images.githubusercontent.com/3873515/45741000-d5e98500-bbf6-11e8-964a-27b55b8a90ba.png)

### Send Email

1 . Create a "Send Email" Ticket
2. Change the Customer of the Ticket
3. Reply to the first Article

Recipient **IS AND SHOULD BE** Article `To`. This is correct and no change is required.

See:
![localhost_3000_ 6](https://user-images.githubusercontent.com/3873515/45741098-09c4aa80-bbf7-11e8-8904-03fb6e42d064.png)
![localhost_3000_ 7](https://user-images.githubusercontent.com/3873515/45741099-0b8e6e00-bbf7-11e8-8cbd-a45ff0a9d2bb.png)

## Summary

The [behavior for "Received Call" and "Outbound Call" need to change](https://github.com/zammad/zammad/blob/46db068a65158aa8e8ca3571d860561d6b1033d4/app/assets/javascripts/app/lib/app_post/utils.coffee#L966) as described. "Send Email" is correct and should stay that way. The [tests](https://github.com/zammad/zammad/blob/46db068a65158aa8e8ca3571d860561d6b1033d4/public/assets/tests/html_utils.js#L1775) need to get extended/corrected.

**Comment by hanneshal** [comment] 2018-10-22 15:24
This issue has triggered caused a regression.
It is not possible to reply on phone tickets / split tickets anymore. 
The "TO" field gets cleared / is not filled at all.

**Comment by martini** [comment] 2018-10-25 00:38
Fixed with https://github.com/zammad/zammad/commit/47120f058537066e6faf6a655181018519e947f4

**Closed as completed by martini** 2018-10-25 00:38 UTC
Labels: bug, verified, frontend
