### ISSUE TITLE
Problem with the integration of a Bot

### ISSUE THREAD

**Issue by a101y** [zammad/zammad#4209] opened 2022-08-09 10:34 UTC
Hey everyone,

I wanted to integrate the Telegram bot into zammad. I got the following error message: "Der Webhook konnte von Telegram nicht gespeichert werden, es scheint eine ungültige URL zu sein."

<img width="331" alt="telegrambot" src="https://user-images.githubusercontent.com/109666147/183627013-cbf28461-d230-4b69-9bcb-d15f8cbea616.PNG">

### Infos:

* Zammad runs on Ubuntu 20.04 LTS on port 80.
* HTTPS encryption runs via an Nginx proxy server.
* in Zammad, https is set under System

Could anyone help me with this?

Kind regards

a101y

**Comment by fliebe92** [comment] 2022-08-09 10:36
Duplicate of #4156 🤔

**Comment by MrGeneration** [comment] 2022-08-09 10:45
At least try to search this issue board. Use the issue template next time it's there for a reason.

**Closed as completed by MrGeneration** 2022-08-09 10:45 UTC
Labels: duplicate, missing issue template
