### ISSUE TITLE
Returning to the search field in the internal KB view results in %20 being added between the searched keywords

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4511] opened 2023-03-01 11:57 UTC
### Used Zammad Version

5.3.x

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge, Version 110.0.1587.57 (Official Build) (64-bit)

### Actual behaviour

In the Knowledge Base internal search field, type any two words (e.g. custom development) separated by a blank character --> click on the article --> when you´re in the article, click on "Return to search results" --> depending on the words you searched for, you will get something like this: custom%20development. To start the search anew, you need to remove the %20 from the previously empty field. This behaviour is not visible in the public view of the Knowledge Base.

### Expected behaviour

In the Knowledge Base public search field, enter any two words (e.g. custom development) separated by a space --> click on the article --> there is no "return to search results" here --> if you go one page back, the keywords you searched for are displayed in their original form, with no %20 separating the keywords. The same behaviour would be expected in the internal KB search field for consistency reasons.

### Steps to reproduce the behaviour

Type any two words (e.g. custom development) separated by a blank character --> click on the search result --> when you're in the article, click on "Return to search results" --> depending on the words you searched for, you will get something like this: custom%20development. 

### Support Ticket

Ticket#10123757

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment] 2023-11-30 14:51
Duplicate of https://github.com/zammad/zammad/issues/4707

**Closed as completed by dominikklein** 2023-11-30 14:51 UTC
Labels: duplicate
