### ISSUE TITLE
Email / Google Channel Reconfiguration Issue

### ISSUE THREAD

**Issue by vidcentum** [zammad/zammad#3284] opened 2020-11-17 01:39 UTC
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): package
* Operating system: ubuntu 20.04
* Database + version: postgress (default installation while installing via package)
* Elasticsearch version: 7.10.0
* Browser + version: Chrome 86.0.4240.198

### Expected behavior:

* I have configured Channels Google, Email (With App Password)
Everything was working fine.
* I had to change my Gmail password and App Password due to security reasons. 
* I logged into Zammad
* I navigated to Settings and Channels. Google, Email
* I received the error - 
{"error":"Failed to refresh XOAUTH2 access_token of provider 'google'! #\u003cRuntimeError: Request failed! ERROR: invalid_grant (Token has been expired or revoked.)\u003e"}
The above error is justifiable.

* I should be able to see the accounts and update my passwords of the channels (Google, Email)

### Actual behavior:

* {"error":"Failed to refresh XOAUTH2 access_token of provider 'google'! #\u003cRuntimeError: Request failed! ERROR: invalid_grant (Token has been expired or revoked.)\u003e"} 
Message box is appearing all the time. I closed the message box. And again the same message box appears after some time.
I am not able to update / reconfigure the channels. 

### Steps to reproduce the behavior:

* Zammad: Configure Google, Email Channel with App Password.
* Google: Change your passwords (gmail password And App Password)
* Zammad - Go to Channels -> Email or Google
{"error":"Failed to refresh XOAUTH2 access_token of provider 'google'! #\u003cRuntimeError: Request failed! ERROR: invalid_grant (Token has been expired or revoked.)\u003e"}
* It is not letting to update or reconfigure the channels.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment] 2020-11-17 07:35
Duplicate of #3240

**Closed as completed by MrGeneration** 2020-11-17 07:35 UTC
Labels: duplicate

**Comment by vidcentum** [comment] 2020-11-17 08:58
@MrGeneration Thank you for quickly analysing the issue. I tend to agree that it is duplicate of #3240.

It is OK to remove and re-add accounts (as #3240 suggests) in our case as there are very few channels. However, I am facing an issue that I am unable to navigate to channels screen as the error message box keeps popping up and waiting spinner appears. 

May I request you if there is any console command or workaround (till the issue is fixed) to remove accounts from the channels?

Best Regards
Maruthi

**Comment by MrGeneration** [comment] 2020-11-17 09:02
Sorry, but please post technical questions on the community board instead of Github: https://community.zammad.org
